### ISSUE TITLE
Migrate to leven to find the closest match for an unknown command

### ISSUE THREAD

**Issue by jamesgeorge007** [gridsome/gridsome#1001]
## Summary

Switch over to `leven` for command suggest feature.

### Motivation

As of now [didyoumean.js](https://github.com/dcporter/didyoumean.js/) matching engine is used to suggest matching commands if the user mistypes. But it is not longer actively maintained. Instead I would suggest switching over to [leven](https://github.com/sindresorhus/leven) which is the fastest JS implementation of the Levenshtein distance algorithm.

> `leven` returns the distance between 2 strings which can be made use of to find the exact match.

**Comment by jamesgeorge007** [comment]
@hjvedvik I will shoot a PR soon :+1:

**Comment by hjvedvik** [comment]
@jamesgeorge007 `leven` seems like a good replacement :)
