### ISSUE TITLE
Invalid HTML breaks routing

### ISSUE THREAD

**Issue by Stegosource** [gridsome/gridsome#1011]
## Description

This is a very obscure bug. Apparently, the HTML `<pre>` tag is not allowed to be nested inside a `<p>` tag. I did not realize this, and my editor did not complain, and everything was working as expected in dev mode when I wrote my component like this.

However, when I pushed to production, my application routing stopped working on the one page that had the incorrectly nested `<pre>` tag. I wasn't until I narrowed down every single line of the file that I found this bug. Once I fixed the invalid HTML nesting, my app worked in prod as expected (also, my code-formatting worked).

### Steps to reproduce

1. Create a basic project with routing. On the home page add:
  ```
  <p>
    <pre>test</pre>
  </p>
  ```
  also include a `<g-link>` to a different page.

2. Build the project for prod

3. Open the project on a server (`npx serve /dist`)

4. Try to open the link to the other page.

### Expected result

The routing to the second page should work.

### Actual result

Nothing happens.

### Environment

```
System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v13.2.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12 
```

I'm not sure if this is a Gridsome bug or what, but it's worth mentioning here in case someone else runs into this very strange issue.

Also note that I did not heavily test with other invalid HTML.

**Comment by brandonpittman** [comment]
This a Vue issue, I think. Something to do with Vue being unable to hydrate malformed HTML.

**Comment by sebj54** [comment]
Possible duplicate? https://github.com/gridsome/gridsome/issues/650

**Comment by brandonpittman** [comment]
If it’s breaking because the user’s HTML is invalid, it doesn’t seem like an issue with Gridsome.

**Comment by Stegosource** [comment]
@sebj54 I think you're right about the duplicate. I'll close this thread and move the conversation over there. 

@brandonpittman I think you're right that it's a Vue thing and not just a Gridsome thing, but maybe there is something that can be done to make the experience a bit better. For example, if it breaks in dev, that's fine because it tells me something is wrong. Or maybe it logs a console warning. I'm not sure how this would work, but the current system allows for a bug to work in dev mode, and only break in prod.

**Comment by brandonpittman** [comment]
@Stegosource If you write invalid HTML, like not closing a header, you might see everything being bolded. No error messages. That’s how HTML always works. 

Generating an error for this would require Gridsome or Vue to validate your HTML for everything, it would seem.

**Comment by Stegosource** [comment]
@brandonpittman That's correct. And maybe that's more than what the frameworks should do. However, the real issue I have is an inconsistent behavior between dev and prod which causes bugs that don't appear in dev to be pushed to prod. I would prefer that the bug also present in dev so I can catch it early.

**Comment by jeff-ofobrukweta** [comment]
@AustinGil i totally agre with u, I think that extra validation of html syntax would be of help , like ive literarily spent 3hrs on this
