### ISSUE TITLE
Imagemin Support

### ISSUE THREAD

**Issue by jamelt** [gridsome/gridsome#1020]
I'm trying to integrate imagemin into the gridsome build. I'd like to convert everything to webp. Are there any gotchas, anything to look out for to make this happen? I'm curious to find out where to look to see where gridsome is handling image processing.

**Comment by EldoranDev** [comment]
Image processing is done in `gridsome/lib/workers/image-processor.js`. In a quick check I did not see a way to change image format in the current implementation so this would need some changes to the current pipeline.

**Comment by jamelt** [comment]
Thanks for sharing, I just wanted to throw this code snippet out there in case someone wants quick & easy image compression. This will work for all images that get picked up by the webpack loader. 

For example, if you access images via an `img` tag or a `g-image` tag, They won't get converted. 
 However, any image defined in your CSS, they will converted/compressed and updated.

Add this to your `gridsome.config.js`:
``` javascript
  configureWebpack(config) {
    const imgRule = config.module.rules.find(r => r.test.test('.png'))
    imgRule.use.push({
      loader: 'webp-loader',
      options: {
        quality: 80
      }
    })
    const options = imgRule.use[0].options;
    options.name = options.name.replace('[ext]', 'webp')
  }
```

The only node module need is:
``` bash
npm i -D webp-loader
```
