### ISSUE TITLE
How to remove Vue Router?

### ISSUE THREAD

**Issue by michaelpumo** [gridsome/gridsome#1021]
## Summary
I have a single page (literally) app that does not require routing, yet Vue Router is in the final build script. This takes a significant amount of KB's to the overall bundle that's not needed.

### Motivation
Not every app built with Gridsome would require routing and it would be good to somehow have the ability to remove this. I've searched all over the docs and cannot find any resource on how this gets configured.

Any help greatly appreciated. I wasn't certain this was a bug so put in as a feature request.

**Comment by ahsath** [comment]
You cannot remove Vue Router since Gridsome internally uses it to create your index.html file. If you want file size improvements you will have to wait until Vue 3 is release

**Comment by a-kriya** [comment]
For single page sites, just using Vue CLI may be enough. The prototype feature has been very handy to me: https://cli.vuejs.org/guide/prototyping.html. It allows development and building for production with zero-config.

@michaelpumo Are you using any specific Gridsome features that would be hard to integrate separately?

**Comment by YazanSneneh** [comment]
npm uninstall vue-router


then u can remove files from the project
