### ISSUE TITLE
Strapi source plugin: add support for single types.

### ISSUE THREAD

**Issue by poltimmer** [gridsome/gridsome#1030]
## Summary

Single types got introduced in beta 19: https://strapi.io/blog/beta-19-single-types-uid-field

At the moment, the strapi source plugin doesn't support this type.

### Basic example

Since single types can only have 1 entry, the api route is now singular, not plural. It also returns an object, instead of an array of objects.

Collection type api response:

```
[
  {
    "id": 1,
    "title": "Lorem ipsum dolor",
    "subtitle": "Ullamcorper porttitor etiam lorem elit cubilia semper porta odio nec nulla.",
    "created_at": "2020-02-18T12:46:49.377Z",
    "updated_at": "2020-03-04T11:24:54.158Z"
  }
]
```

Single type api response:
```
{
  "id": 1,
  "title": "Leiderschap in Brainport regio Eindhoven",
  "subtitle": "Exclusief leiderschapsprogramma Ullamcorper porttitor etiam lorem elit cubilia semper porta odio nec nulla.",
  "created_at": "2020-02-18T12:46:49.377Z",
  "updated_at": "2020-03-04T11:24:54.158Z"
}
```

From a user perspective, you shouldn't be required to specify an ID when then querying this single type through the graphQL datalayer.

Collection type graphQL query:
```
strapiHero(id: 1) {
  title
  subtitle
}
```

Single type graphQL query:
```
strapiHero {
  title
  subtitle
}
```

### Motivation

The use case of single types is obviously for data you only want 1 entry of. Think of an about page, a hero, etc. End of the day, it's a quality of life improvement. (besides the fact that the single type from strapi is currently straight up incompatible with the source plugin)

**Comment by jlsjonas** [comment]
@hjvedvik is it me or did that PR only handle a part of this ticket?
I could only retrieve _null_ results until I added `(id: 1)` to my single-type resource; even though it's supposed to be a singular resource; i.e. without query requirements.
Was that considered out of scope? Is there a follow-up ticket?
