### ISSUE TITLE
gridsome create is not working for default theme

### ISSUE THREAD

**Issue by JWeis** [gridsome/gridsome#1033]
## Description

cli create is not creating a new site from default theme

### Steps to reproduce

gridsome create <name>

### Expected result

New Site

### Actual result

Error

### Environment
Node 12.16.1

Paste the information here as shown by `gridsome info`

```
➜ gridsome create site
❯ Clone https://github.com/gridsome/gridsome-starter-default.git
❯ Update project package.json
❯ Install dependencies
Error: Command failed: git clone https://github.com/gridsome/gridsome-starter-default.git /Users/james/Projects/gridsome/site --single-branch
nullnull
    at Object.task (/usr/local/share/.config/yarn/global/node_modules/@gridsome/cli/lib/commands/create.js:42:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by zacnomore** [comment]
@JWeis Could you share the output of `gridsome info`?

**Comment by JWeis** [comment]
Sorry about that. Here it is:

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Safari: 13.0.5
```

**Comment by JWeis** [comment]
I got it working. For some reason, I needed to reset Xcode Command Line Tools.  Thanks!

**Comment by webdevbrian** [comment]
I'm getting the same error, uninstalled / reinstalled xcode CLI, still have the same issue. Here is my `gridsome info`:

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.75
    Firefox: 68.6.0
    Safari: 13.0.3
  npmGlobalPackages:
    @gridsome/cli: 0.3.2
```

**Comment by mosaabramadan** [comment]
is there a solution for this? i have the exact same problem. i removed xcode cli completely, nothing.

**Comment by dejurin** [comment]
> is there a solution for this? i have the exact same problem. i removed xcode cli completely, nothing.
brew doctor

**Comment by alanbosco** [comment]
I am having the same issue on windows. 

`
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.77)

`
