### ISSUE TITLE
DatoCMS apiURL

### ISSUE THREAD

**Issue by MZOG** [gridsome/gridsome#1037]
Hi,

I am new to gridsome and I would like to connect my app with DatoCMS.
I found a plugin with some options to fill.

There is apiUrl field and I have no idea what to add there..
Current value is ```https://site-api.datocms.com```.

If I save the gridsome.config.js and run my app I am getting errors.

When I visit site-api.datocms.com i get ```{"data":[{"id":"cf3acb","type":"api_error","attributes":{"code":"INVALID_ENDPOINT","details":{}}}]}```.

Could someone explain how it works? How I can get data from DatoCMS?

**Comment by thetre97** [comment]
@MZOG That is an optional field, you shouldn't need it - if you omit it, it will connect to the default endpoint.

**Comment by thetre97** [comment]
@MZOG If your issue has been fixed, could you close this issue? Thanks.
