### ISSUE TITLE
[question] Best way to handle Single Page Query for different types

### ISSUE THREAD

**Issue by liambarr** [gridsome/gridsome#1040]
What would be the best way to handle a single page query for different post types?
Rather than setting up 2 templates that'd be the exact same code (except the query), is there a way to Query one type or the other depending on the route?

**Comment by noxify** [comment]
Hi @liambarr 

could you please explain what you're trying to do?
Maybe an example/use case could be good to have the same understanding.

Thanks!

**Comment by liambarr** [comment]
For example having a single template PostEntry, which could be used for both Articles and News.

Commonly, the structure would be to have a:
ArticleEntry.vue 
&
NewsEntry.vue

Usually containing a page query similar to the following:
```
query News($recordId: ID!) {
  entry : news(id: $recordId) {
    title
    content
    excerpt
    createdAt(format:"Do MMMM YYYY")
}
```

Is there a way to do a query on News and Articles dependent on recordId?

**Comment by noxify** [comment]
@liambarr - I don't think so.

Ideas:
* Create the pages programmatically ( via `gridsome.server.js` ) and pass the complete node as `context` to the template 
* Create a wrapper template for each type and run the query, then pass the result to a component, which will render the entry.

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
