### ISSUE TITLE
active-class for <a> (Specifically for anchor links)

### ISSUE THREAD

**Issue by liambarr** [gridsome/gridsome#1041]
## Summary

It'd be good if active-class and exact-active-class could work with <a>'s.

### Basic example / Motivation

For use in a Table of Contents to show user what section of a post they're on.

Or for filtering data through anchors.

**Comment by noxify** [comment]
Hi @liambarr 

could you please explain what you're trying to do?
Maybe an example/use case could be good to have the same understanding.

Thanks!

**Comment by liambarr** [comment]
Sure, apologises (I've simply mocked it up with jQuery) - if you can't already tell, I'm still wrapping my head around Vue. But using your articles starter for example. When an anchor link is clicked, add class Active.

https://streamable.com/qzu6v

**Comment by noxify** [comment]
@liambarr - ok I understood.
Not sure if your question is related to gridsome. 🤔

**Comment by noxify** [comment]
Hi @liambarr 

If you haven't found a way to set a active flag to anchors, here it is: https://github.com/mrcrmn/docc

The related component: https://github.com/mrcrmn/docc/blob/master/src/components/OnThisPage.vue

Hope this helps.

Regards,
Marcus
