### ISSUE TITLE
pathPrefix is not prepended when hard reloading view

### ISSUE THREAD

**Issue by mattbrailsford** [gridsome/gridsome#1043]
## Description

There is an issue in gridsome when a component can't be found, it performs a hard reload. However that hard reload doesn't contain the pathPrefix like it should. 

The problem is, client side your routes don't contain the pathPrefix, which is fine for the client side code, but if those routes can't be found, then it is requested from the server instead, but the server is expecting the route to be prefixed with pathPrefix.

I've noticed this as part of my deployment setup using netlify, where I have it setup to be on a /docs/ sub directory. However, every time I deploy, if I have the site already open, then try to continue navigating the site, the client side routes can't be found and so it requests the page from the server, where I get a 404 because the route it's requesting is without the pathPrefix.

**Comment by mattbrailsford** [comment]
I don't know the gridsome codebase very well but I think it could be this at fault:

https://github.com/gridsome/gridsome/blob/3acbada56288327dee7118bde7b0d1e9b898bd5c/gridsome/app/entry.client.js#L30

If you are forcing a redirect, the `fullPath` variable needs to have the `config.pathPrefix` prefixed onto it.

**Comment by mattbrailsford** [comment]
Hmm, probably here too:

**Comment by tkhquang** [comment]
I have my site set up on /blog/ sub directory with Netlify too and I suspect the same.

**Comment by mattbrailsford** [comment]
I've created a PR for this https://github.com/gridsome/gridsome/pull/1044/files
