### ISSUE TITLE
Navigation error in production

### ISSUE THREAD

**Issue by CorneilleEdi** [gridsome/gridsome#1049]
## Description

Website freeze when trying to navigate

### Steps to reproduce

- create a gridsome app
- deploy on gitlab page

### Expected result

- navigate without errors

### Actual result

have some errors in the console

```javascript
TypeError: Cannot read property '_isDestroyed' of undefined
    at destroy (app.b3f83923.js:7)
    at _ (app.b3f83923.js:7)
    at _ (app.b3f83923.js:7)
    at a.__patch__ (app.b3f83923.js:7)
    at a.t.$destroy (app.b3f83923.js:7)
    at destroy (app.b3f83923.js:7)
    at _ (app.b3f83923.js:7)
    at _ (app.b3f83923.js:7)
    at _ (app.b3f83923.js:7)
    at _ (app.b3f83923.js:7)
``` 

### Environment
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 13.9.0 - /usr/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.13.7 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 74.0
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0 
    @gridsome/remark-prismjs: ^0.2.0 => 0.2.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.5.0 => 0.5.0 
    @gridsome/vue-remark: ^0.1.10 => 0.1.10 
    gridsome: ^0.7.0 => 0.7.13 
    gridsome-plugin-flexsearch: ^0.1.13 => 0.1.15 
    gridsome-plugin-remark-codetitle: ^0.2.2 => 0.2.2 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

**Comment by CorneilleEdi** [comment]
Additionnal error

```javascript
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

**Comment by kamit-transient** [comment]
> Additionnal error
> 
> ```js
> Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
> ```

I am facing the same but I have deployed on netlify instead

**Comment by CorneilleEdi** [comment]
I kind of solve the problems by making some changes.
- move every created() to mounted()
- replace every a tag by a g-link

Now it is working just fine
