### ISSUE TITLE
How to prevent generate of `data-vue-meta` attributes during build

### ISSUE THREAD

**Issue by lusarz** [gridsome/gridsome#105]
## Description
When I use `gridsome build` to build final html I'd like to have output html as simple as possible. Currently my HTML contains a lot of unnecessary attributes, like:

- data-vue-meta="lang"
- data-html-server-rendered="true"
- data-server-rendered="true"

Is there way to configure it to prevent these attributes to be rendered ?

### Steps to reproduce

    gridsome create my-gridsome-site
    cd my-gridsome-site
    gridsome build
    cat ./dist/index.html

### Expected result

    <!DOCTYPE html>
    <html lang="en">
      <head>
       <title>My page</title>
       <meta charset="utf-8" />
      </head>
    </html>

### Actual result

    <!DOCTYPE html>
    <html data-html-server-rendered="true" lang="en" data-vue-meta="lang">
      <head>
       <title data-vue-meta="true">My page</title>
       <meta data-vue-meta="true" charset="utf-8" />
      </head>
    </html>

**Comment by EldoranDev** [comment]
The attributes you listed are created by the Vue Server Side renderer. They are needed by the Vue Instance, to Hydrate (or work with) the generated html.

May I ask why you want to get rid of the attributes ?

**Comment by lusarz** [comment]
I would like to generate clean and production ready static HTML using `gridsome build`.

**Comment by hjvedvik** [comment]
`data-vue-meta="lang"` and `data-html-server-rendered="true"` is added by `vue-meta` which Gridsome uses internally and it depends on those attributes to work. I agree that it would be better if we could find another solution that doesn't add extra attributes, but it isn't a priority right now.

And as @EldoranDev wrote, the `data-server-rendered="true"` is added by Vue SSR and is required for hydration so we cannot remove it.

**Comment by lusarz** [comment]
Thank you for explanation. As a workaround I've used [sanitize-html](https://www.npmjs.com/package/sanitize-html) after `gridsome build`. Maybe it would be useful for someone else.
