### ISSUE TITLE
Conditional template generation 

### ISSUE THREAD

**Issue by pislarm** [gridsome/gridsome#1052]
I have blog posts categorised as 'jobs' within wordpress posts.

I want to create pages from posts that have category 'jobs'. I think this is a good use case for templates but this will create pages from all of the posts not just the one with category 'jobs'.

Is there a way to conditionally create pages from posts with a certain category?

I'm thinking something like:
 ```
WordPressPost: [
      { 
        name: 'jobs',
        path: (node) => {
          if (node.category === 'jobs') {
            return `/jobs/job-blog/${node.slug}`
          }
        },
        component: './src/templates/Blogs.vue'
      }
    ]

```
Thanks in advance!

**Comment by noxify** [comment]
Hi @pislarm,

I hope I understood your problem correctly.
The goal is to create only pages which has `jobs` as category?

You can use the Pages API to create your own pages.
There you can check whatever you want and set then the template which should be used:
https://gridsome.org/docs/pages-api/#createpageoptions

You can find an example here: https://gridsome.org/docs/pages-api/#create-pages-from-graphql

In your `gridsome.config.js` you have to ensure, that in the `templates` section, you only have defined the `path` but not `component`.
Also, ensure that the name from the template ( the vue file ) is different to the name from the collection.

Alternative, you could use the [onCreateNode](https://gridsome.org/docs/server-api/#apioncreatenodefn) to filter the not needed records. Then you got only the required nodes.

Hope that helps.

Regards,
Marcus

**Comment by pislarm** [comment]
Hey @noxify  yes this helped resolve the issue! 

Many thanks for you prompt reply and help!
Best!
