### ISSUE TITLE
Build throws an error referencing a third party package

### ISSUE THREAD

**Issue by rhanmiano** [gridsome/gridsome#1059]
## Description

Hi,

I am creating a portfolio site using **Gridsome**. I was trying to integrate a third party vue package named [@smartweb/vue-flash-message](https://github.com/smwbtech/vue-flash-message), and just follow through the installation process. Everything seems to be working fine during `gridsome develop` but had issues when trying to build the project `gridsome build`.

#### Setup `main.js`
```
// This is the main.js file. Import global CSS and scripts here.
// The Client API can be used here. Learn more: gridsome.org/docs/client-api

require('./assets/scss/main.scss')
import VueFilterDateFormat from 'vue-filter-date-format'
import FlashMessage from '@smartweb/vue-flash-message'

import DefaultLayout from '~/App.vue'
import Unicon from 'vue-unicons'
import { 
  // list of icons here
} from 'vue-unicons/src/icons'

Unicon.add([
  // list of icons here
])

export default function (Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component('App', DefaultLayout)
  Vue.use(Unicon)
  Vue.use(VueFilterDateFormat, {
    // some config here
  })
  Vue.use(FlashMessage, {
    name: 'flashMessage',
    tag: 'FlashMessage',
    time: 3000,
    strategy: 'single'
  })
}

```
Tried solutions mentioned here #408 #180 [Add External Scripts](https://gridsome.org/docs/assets-scripts/) but still could not solve my issue.

Am I missing something? Any help would be much appreciated. Thank you!

### Steps to reproduce

Everything works fine during development, but cannot go through a successful build.

Will just share the repo of the project. [radian-gridsome-frontend](https://github.com/rhanmiano/radian-gridsome-frontend)

### Expected result

Should build the static files for the Gridsome site.

### Actual result

Errors during `gridsome build`

![error](https://user-images.githubusercontent.com/31644925/77268267-52738d00-6ce0-11ea-8f2e-ca9c3875b83d.png)

### Environment

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.16.1 - ~Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - ~Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - ~Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.13

```

**Comment by tkhquang** [comment]
I tried to use the method mentioned in #180 and it works for me.

Remove the import at the beginning

```js
export default function (Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component('App', DefaultLayout)
  Vue.use(Unicon)
  Vue.use(VueFilterDateFormat, {
    // some config here
  })
  if (isClient) {
    const FlashMessage = require("@smartweb/vue-flash-message").default;

    Vue.use(FlashMessage, {
      name: "flashMessage",
      tag: "FlashMessage",
      time: 3000,
      strategy: "single"
    });
  }
}

```

**Comment by rhanmiano** [comment]
Thanks @tkhquang for taking the time to look at this issue. I've managed to solve my issue with what you have suggested.
