### ISSUE TITLE
Add CHANGELOG to repository

### ISSUE THREAD

**Issue by renestalder** [gridsome/gridsome#106]
## Summary

Nowadays, most open-source projects keep a changelog in the repository for easy accessing and searching for changes between versions.

Gridsome is currently missing any form of a changelog. There is no changelog in the releases on GitHub and not in the repository

### Basic example

https://keepachangelog.com/en/1.0.0/

### Motivation

Git commit history alone isn't easy enough to read and understand changes made between releases. Users of a library or framework want to easily scan for new features, fixes and breaking changes.

**Comment by hjvedvik** [comment]
This repository uses Lerna with conventional commits to generate changelogs and create tags automatically. But Lerna creates the logs in each package folder. The `gridsome` changelog is found in the [gridsome folder](https://github.com/gridsome/gridsome/blob/master/gridsome/CHANGELOG.md).

I've been thinking about including the logs on [gridsome.org](https://gridsome.org/), but haven't been able to do it yet :)

**Comment by renestalder** [comment]
@hjvedvik Ah, there we are. Thanks for the info. Exactly what I looked for.

That's fine. Maybe then I recommend quickly copy/paste the output to the release notes in the release tab of GitHub when you create a new one just to also have it at one of those places where one is usually looking for it.

But as long as there at least a changelog somewhere, that's good. :)

**Comment by hacknug** [comment]
Could we maybe add a link to the changelog on the navbar? GitHub icon could link to the repo and version number to the changelog.

**Comment by SteveEdson** [comment]
Yeah it'd be great if the changelog could be made more obvious, ideally in the root of the repo.

Thanks
