### ISSUE TITLE
error occurs when dockerize 

### ISSUE THREAD

**Issue by Abdubek** [gridsome/gridsome#1061]
I added Dockerfile in gridsome project:

    FROM node:10.16-alpine as build
    RUN apk update && apk upgrade
    RUN apk --no-cache add --virtual native-deps git\ g++ gcc libgcc libstdc++ linux-headers make python

    WORKDIR /app
    COPY . /app
    ENV PATH /app/node_modules/.bin:$PATH
    RUN yarn global add @gridsome/cli
    RUN rm -rf /app/node_modules/sharp/vendor
    RUN yarn add pngquant-bin
    RUN yarn
    RUN yarn build

    FROM nginx:alpine
    COPY --from=build /app/dist /usr/share/nginx/html
    RUN rm /etc/nginx/conf.d/default.conf
    COPY nginx/nginx.conf /etc/nginx/conf.d
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]

And get the following error:

Step 11/17 : RUN yarn build
 ---> Running in 6f28441cabf5
yarn run v1.17.3
$ gridsome build
**/bin/sh: lscpu: not found**
Gridsome v0.7.12

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.05s
Create pages and templates - 0.13s
Generate temporary code - 0.06s
Bootstrap finish - 1.48s
gridsome-plugin-manifest: "icon_path" must target an existing file
gridsome-plugin-manifest: 1.292ms
Compiling assets...
Compile assets - 23.09s
Execute GraphQL (9 queries) - 0s
Write out page data (9 files) - 0.01s
Render HTML (9 files) - 0.6s
Process files (0 files) - 0s
Processing images (21 images) - 0%**/bin/sh: lscpu: not found**
Error: Failed to process image src/favicon.png. Cannot set property 'then' of undefined
    at pMap (/app/node_modules/gridsome/lib/workers/image-processor.js:113:13)
(node:353) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -8
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:551:9)
    at module.exports (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:205:26)
    at input (/app/node_modules/imagemin-pngquant/index.js:57:13)
    at Function.module.exports.buffer (/app/node_modules/imagemin/index.js:71:31)
    at Object.exports.processImage (/app/node_modules/gridsome/lib/workers/image-processor.js:93:29)
(node:353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.

How to solve it?

**Comment by noxify** [comment]
Hi,

I had the `lscpu` error/warning with the alpine node image in k8s, too.

But the result was as expected. So I don't think that 

```
/bin/sh: lscpu: not found
```

is your problem.

Based on your output, it seems that your favicon is missing.

```
Error: Failed to process image src/favicon.png.
```

Could you please check if everything is working after creating a favicon ?

**Comment by Abdubek** [comment]
I removed all the g-image tags and favicon.png in the src directory in the assembly was successful

**Comment by Microflash** [comment]
Instead of using `node:alpine` and installing several utilities on the top of it, why don't you use `node:buster` which already comes with all those utilities?

Since you're using a multi-stage Dockerfile, `node:buster` image should not impact the final nginx-based image.

```dockerfile
FROM node:10.16-buster as build
WORKDIR /app
COPY package.json .
RUN yarn
COPY . .
RUN yarn build

FROM nginx:1.17.9-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
