### ISSUE TITLE
Option to Remove Pager fields

### ISSUE THREAD

**Issue by joeelia** [gridsome/gridsome#1065]
## Description

Cannot remove Pager Fields

firstLabel | « |  
prevLabel | ‹ |  
nextLabel | › |  
lastLabel | » | 

I created my own fields for previous and next and I would like to remove the default labels without DOM manipulation. 

### Steps to reproduce
1. Go to https://gridsome.org/docs/pagination/
2. Note there is no option to remove Pager labels

### Expected result

Have the ability to remove the default Pager labels

**Comment by a-kriya** [comment]
@joeelia Aren't you looking for `showNavigation` prop?

Looking at the component source, setting it to false will not render those links: https://github.com/gridsome/gridsome/blob/master/gridsome/app/components/Pager.js#L66

**Comment by joeelia** [comment]
@a-kriya 

`<Pager :info="..." linkClass="..." showNavigation="false"/>`

Still shows those label navigations. It's fine though. They are relatively small and don't hurt the UX. Closing my this ticket because this doesn't affect me too much.

**Comment by a-kriya** [comment]
@joeelia You need to have `:show-navigation="false"`. The `v-bind` or `:` is important for it to be treated as a JS expression, and not a String (which resolves as a truthy value).

Please see docs at https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean.

**Comment by joeelia** [comment]
@a-kriya Just learned something today about passing camelCase props in Vue.

It works now. Thanks!

**Comment by a-kriya** [comment]
No problem. Just to note, either of `:showNavigation` or `:show-navigation` will do the job (the latter is just the recommended style for props). What solved the issue is the use of `:`, which in turn is shorthand for `v-bind:` (as seen in the docs linked above).
