### ISSUE TITLE
Can't access props within component object

### ISSUE THREAD

**Issue by moritzlaube** [gridsome/gridsome#1066]
I am using Gridsome with Storyblok and followed the Storyblok's setup guide: [https://www.storyblok.com/tp/gridsome-multilanguage-website-tutorial](url)

So I am basically passing the Storyblok data to a template which then dynamically renders out the content types and components like so:

`<component
      v-if="story.content.component"
      :key="story.content._uid"
      :blok="story.content"
      :is="story.content.component"
    />`

I then have a Page component where I can access the `blok` prop like so:

```
<script>
export default {
  name: "CorporatePageComponent",
  props: ["blok"]
};
</script>
```

When I then access the `blok` prop in the template section everything works just fine:

```
<template>
  <div>
    <h1>{{blok.title_tag}}</h1>
  </div>
</template>
```

But when I am trying to access that very data within the component object to fill the title tag it gives me a console warning that `blok` is undefined. 

```
<script>
export default {
  name: "CorporatePageComponent",
  metaInfo: {
    title: this.blok.title_tag,
    meta: [{ name: "description", content: this.blok.meta_description }]
  },
  props: ["blok"]
};
</script>
```

What am I doing wrong here? Thanks for your help!

**Comment by hjvedvik** [comment]
The `metaInfo` property needs to be a function to access props. You can read more about it [here](https://vue-meta.nuxtjs.org/faq/component-props.html#how-to-use-component-props-or-data). Try something like this instead:
```js
export default {
  name: "CorporatePageComponent",
  props: ["blok"],
  metaInfo() {
    return {
      title: this.blok.title_tag,
      meta: [{ name: "description", content: this.blok.meta_description }]
    }
  }
}
```

**Comment by moritzlaube** [comment]
That's it! Thanks so much for your lightning-fast help!
