### ISSUE TITLE
Can't add global attrs to HTML or BODY

### ISSUE THREAD

**Issue by branquito** [gridsome/gridsome#107]
## Description

I am not able to see my class is added as an attribute to a `<html>` or `<body>` tags.

### Steps to reproduce

I tried as suggested in this page, https://gridsome.org/docs/body-html-attributes/

### Expected result

I did expect to see my class attribute added to `<html>` or `<body>` tags

### Actual result

Viewing the source of the page in browser, I couldn't see my class attribute has been added to neither of aforementioned tags.

![image](https://user-images.githubusercontent.com/1226132/50802750-f34a7800-12e7-11e9-95fd-1a1ed9be9cea.png)

**Comment by EldoranDev** [comment]
Are you running develop or build ? 

If you are running Develop did you try looking at it using the [element inspector](https://developers.google.com/web/tools/chrome-devtools/) instead of "view source"?

**Comment by branquito** [comment]
Yes I was running develop. You are right, they are present in element inspector view.
