### ISSUE TITLE
Cannot query field "allCollection1"

### ISSUE THREAD

**Issue by smth** [gridsome/gridsome#1070]
Using [source-wordpress](https://github.com/gridsome/gridsome/tree/master/packages/source-wordpress) I added some collections as described in the example, e.g

```js
plugins: [
    {
      use: '@gridsome/source-wordpress',
      options: {
        baseUrl: process.env.WORDPRESS_URL, // required
        typeName: 'WordPress', // GraphQL schema name (Optional)
        customEndpoints: [
          {
            typeName: "Collection1",
            route: "/wp/v2/posts?categories=3",
            normalize: true,
          },
          {
            typeName: "Collection2",
            route: "/wp/v2/posts?categories=5",
            normalize: true,
          },
        ]
      }
    }
  ]
```

As I understand it, these collections should now be query-able with `allCollection1` and `allCollection2`. With the following though I'm getting `Cannot query field \"allCollection1\"`

```
query Home ($page: Int) {
  allCollection1 (page: $page, perPage: 10) @paginate {
    pageInfo {
      totalPages
      currentPage
    }
    edges {
      node {
        id
        title
      }
    }
  }
}
```

There is no mention of "Collection" in the schema.

**Comment by mario-neuhold** [comment]
If you have used the [Default WordPress Starter](https://gridsome.org/starters/default-word-press-starter/) you have to update your package.json to use the 0.5.x Version of the @gridsome/source-wordpress package:
```javascript
  "dependencies": {
    "@gridsome/source-wordpress": "^0.5.0",
```

I hade the same problem and have submitted a [PR](https://github.com/gridsome/gridsome-starter-wordpress/pull/25/commits/3870020077a64d2cc7022ea38a3fae024961e150) for the starter repo.

**Comment by smth** [comment]
Yup, that fixed the issue for me too. Thanks.

**Comment by hjvedvik** [comment]
The PR is merged now, so I'll close this.
