### ISSUE TITLE
Gridsome pages not loading

### ISSUE THREAD

**Issue by chs242** [gridsome/gridsome#1071]
## Description

My site deployed is deployed on Netlify and when clicking on any link on the landing page, the url updates but the content does not show unless i refresh the page. note on my local development server this is not an issue. Its only an issue on the live site

Note: there is not much literature on this. Issue #324 and issue #337 both raised the same issue though the answers are not applicable in my project.

### Steps to reproduce

ezrasnashim.netlify.com

click to the check out the project

try click on any links on the landing page

### Expected result

the page should load

### Actual result

instead only the url updates. the content doesn't show

### Environment

@gridsome/cli v0.3.1
gridsome v0.7.12

browser:
firefox developer browser

google chrome browser

**Comment by Yiddishe-Kop** [comment]
See this issue: #661 

The solution will solve this problem.

**Comment by chs242** [comment]
After going through the site, I found the isuue was some invalid HTML, which the browser fixes [changes around], which changed the actual DOM from the virtual DOM, which caused the Vue hydration to break.

I still dont understand why it was running fine on my development server.

https://ssr.vuejs.org/guide/hydration.html#hydration-caveats

**Comment by chs242** [comment]
thanks @Yiddishe-Kop

**Comment by a-kriya** [comment]
@chs242 Still some JS errors on the donate page, after which the navigation breaks. But since you've resolved your original issue, would you mind closing this ticket?
