### ISSUE TITLE
Pages (Sometimes) Not Loading on Netlify

### ISSUE THREAD

**Issue by michaelpelletier** [gridsome/gridsome#1072]
## Description

Creating a site for a client using Gridsome, really liking it so far.
But I'm hitting a problem with navigation.
- Entering the site from any root page works fine and all navigation works fine. 
  - https://covid-protocols.netlify.com/
  - https://covid-protocols.netlify.com/about
  - https://covid-protocols.netlify.com/quick-links
- Entering via a subpage locks you to that "subdirectory"
  - https://covid-protocols.netlify.com/protocols/01-clinical-course-prognosis-and-epidemiology - Cannot navigate to About/QuickLinks or Home
  - https://covid-protocols.netlify.com/addendum/01-pal-care - As above but also cannot navigate to the Protocols pages.

The URL in the address bar still updates properly, and this issue does not occur locally. 

I did also turn on `config.mode('development');` in my gridsome.config.js to see if Vue was giving me hydration warnings, but I don't see any. I was particularly concerned about this idea since my content is generated via Google Docs, so I also ran a test with removing all of the queries and data and just having it as a few static pages, with the same results: https://5e860a5999b34f000640d4eb--covid-protocols.netlify.com/

A couple of file snippets:

**gridsome.server.js**
```
  api.createPages(({ createPage }) => {
    createPage({
      path: '/protocols/:id',
      component: './src/pages/protocols/Protocol.vue'
    })
    createPage({
      path: '/addendum/:id',
      component: './src/pages/addendum/Addendum.vue'
    })
  })
```

**netlify.toml**
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

### Steps to reproduce

I'll work on making a demo project now, but in the hopes of this being a quick fix, I'm hoping to get some thoughts / eyes on this in the interim.

**Comment by michaelpelletier** [comment]
Looks like the problem, hilariously, did seem to be non-semantic HTML!

**Comment by CodingCarter** [comment]
> Looks like the problem, hilariously, did seem to be non-semantic HTML!

What was the non-semantic HTML?
