### ISSUE TITLE
[transformer-remark] Update dependency html-to-text

### ISSUE THREAD

**Issue by noxify** [gridsome/gridsome#1075]
## Description

Created a new project and got the following audit message:

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @gridsome/transformer-remark                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @gridsome/transformer-remark > html-to-text > optimist >     │
│               │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### Steps to reproduce

1. Run `gridsome create new-project-name`
2. Run `npm i -s @gridsome/source-filesystem @gridsome/transformer-remark`

### Expected result

No audit issues are shown

### Actual result

Got an audit message

### Environment

Paste the information here as shown by `gridsome info`

```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.1
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.5.0 => 0.5.0 
    gridsome: ^0.7.13 => 0.7.13 
    gridsome-plugin-tailwindcss: ^2.2.43 => 2.2.43 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

## Additional Information

I have already analyzed the audit issue and it seems that `html-to-text` isn't maintained anymore.
Here the related comment from the package author: https://github.com/werk85/node-html-to-text/issues/198#issuecomment-606622234

## Alternative packages

* https://github.com/priotas/html-to-text/tree/next
  * Currently not available at npm 
* https://github.com/KillyMXI/node-html-to-text
  * Available at npm: https://www.npmjs.com/package/@mxiii/html-to-text

**Comment by a-kriya** [comment]
Sounds like the author may be handing it off to someone for maintenance. If it happens soon enough, Gridsome may not need to migrate to a fork just yet.

**Comment by grace-snow** [comment]
html-to-text isn't the issue here, its that transformer-remark is using an old version of html-to-text, which has an out of date dependency (optimise - no longer maintained and no longer listed as a dependency of html-to-text in recent versions) 

Solution would be for [transformer-remark] to replace `"html-to-text": "^4.0.0",` with `"html-to-text": "^5.0.0"` as a dependency I think.

**Comment by noxify** [comment]
@grace-snow  the answer is "yes and no"

No:
The problem is that the used `minimist` version is set to `1.2.0` in their `package-lock.json`.
There is a DependBot PR to use `1.2.3` as version --> https://github.com/werk85/node-html-to-text/pull/199

Yes:
After the PR is merged, we can solve it by upgrading the `html-to-text` version to `^5.0.0`.

But please correct me, if I'm wrong.

Thanks!

**Comment by ahsath** [comment]
Any news?

**Comment by a-kriya** [comment]
@ahsath werk85/node-html-to-text#200

**Comment by missmatsuko** [comment]
@noxify That PR has been merged now. Looks like their version of minimist in package.json is updated:
https://github.com/werk85/node-html-to-text/blob/00adb127abf1a34d858e117c69b1b2cc223baf6f/package.json#L31

**Comment by noxify** [comment]
@missmatsuko thanks for the hint - I will check it

**Comment by noxify** [comment]
@missmatsuko tested it with a fresh installation, but I got the same audit message.

It seems that they have to release the changes

**Comment by KillyMXI** [comment]
This can be closed, it seems.

**Comment by noxify** [comment]
Hey @KillyMXI 

thanks for the update - i will give it a try and will close the issue if everything is working as expected.

**Comment by noxify** [comment]
Tested it with

```
    "@gridsome/transformer-remark": "^0.6.3",
    "gridsome": "^0.7.21",
```

and the alert isn't shown anymore.
