### ISSUE TITLE
Getting TypeError on two separate code projects

### ISSUE THREAD

**Issue by johncherba** [gridsome/gridsome#1078]
When I run ```gridsome develop``` I get the following errors. Any ideas?

```
Initializing plugins...
Load sources - 3.89s
TypeError: schemaComposer.get(...).hasInterface is not a function
    at createTypeComposers (/Users/johncherba/IdeaProjects/dotcom-gridsome/node_modules/gridsome/lib/graphql/nodes/index.js:72:41)
    at createNodesSchema (/Users/johncherba/IdeaProjects/dotcom-gridsome/node_modules/gridsome/lib/graphql/nodes/index.js:30:3)
    at createSchema (/Users/johncherba/IdeaProjects/dotcom-gridsome/node_modules/gridsome/lib/graphql/createSchema.js:59:3)
    at Schema.buildSchema (/Users/johncherba/IdeaProjects/dotcom-gridsome/node_modules/gridsome/lib/app/Schema.js:28:28)
    at Plugins.createSchema (/Users/johncherba/IdeaProjects/dotcom-gridsome/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
MacBook-Pro:dotcom-gridsome$ gridsome -v
@gridsome/cli v0.3.1
gridsome v0.7.13

```

**Comment by a-kriya** [comment]
@johncherba Looks like it's related to GraphQL. Are you using any page or static queries in your components? Can you share them? Or are you noticing this error in newly created projects?

**Comment by johncherba** [comment]
Hi @a-kriya,

Thanks for the reply. I think I found it related to a plugin. Probably should post this in the plugin repo, but haven't had success in responses.

In `gridsome.config.js` there is:

` plugins: [
    {
      use: '@meeg/gridsome-source-kentico-kontent',
      options: {
        deliveryClientConfig: {
          projectId: process.env.KENTICO_KONTENT_PROJECT_ID
        }
      }
    },
  ],`

and the schema it's trying to pull is, it should do it automagically but here is the `schema.graphql` file:

`type SystemInfo {
    id: String!
    name: String!
    codename: String!
    language: String!
    type: String!
    lastModified: String!
}
interface ContentItem {
    system: SystemInfo!
}
type MultipleChoiceElementOption {
    name: String!
    codename: String
}
type TaxonomyTerm {
    name: String!
    codename: String
}
type Asset {
    name: String
    type: String
    size: Int
    description: String
    url: String
    width: Int
    height: Int
}
type Link {
    codename: String
    itemID: String
    urlSlug: String
    type: String
}
type RichTextImage {
    imageId: String!
    url: String!
    description: String
    width: Int
    height: Int
}
type TextElement {
    type: String!
    name: String!
    value: String
}
type NumberElement {
    type: String!
    name: String!
    value: Int
}
type DateTimeElement {
    type: String!
    name: String!
    value: String
}
type MultipleChoiceElement {
    type: String!
    name: String!
    value: [MultipleChoiceElementOption]
}
type UrlSlugElement {
    type: String!
    name: String!
    value: String
}
type TaxonomyElement {
    type: String!
    name: String!
    value: [TaxonomyTerm]
    taxonomyGroup: String
}
type AssetElement {
    type: String!
    name: String!
    value: [Asset]
}
type RichTextElement {
    type: String!
    name: String!
    value: String
    linkedItemCodenames: [String]
    links: [Link]
    images: [RichTextImage]
    resolvedHtml: String
}
type LinkedItemsElement {
    type: String!
    name: String!
    value: [ContentItem]
    itemCodenames: [String]
}
type CustomElement {
    type: String!
    name: String!
    value: String
}

type CarouselCardContentType implements ContentItem {
    system: SystemInfo!
    icon: LinkedItemsElement
    customer_story: LinkedItemsElement
    demo: LinkedItemsElement
    solution: TaxonomyElement
    video: LinkedItemsElement
    card_content: LinkedItemsElement
    whitepaper: LinkedItemsElement
    value_proposition: LinkedItemsElement
    url: TextElement
    overview_deck: LinkedItemsElement
    pdf: AssetElement
    use_case: TaxonomyElement
    carousel_content_types: TaxonomyElement
    card_title: TextElement
    original_content_link: TextElement
    visibility: TaxonomyElement
}

type CustomerStoryContentType implements ContentItem {
    system: SystemInfo!
    original_content_link: TextElement
    image: LinkedItemsElement
    use_case: TaxonomyElement
    lob: TaxonomyElement
    industry: TaxonomyElement
    url: TextElement
    content: AssetElement
    description: TextElement
    solution: TaxonomyElement
}

type DemoContentType implements ContentItem {
    system: SystemInfo!
    solution: TaxonomyElement
    description: TextElement
    pdf: AssetElement
    industry: TaxonomyElement
    original_content_link: TextElement
    video: TextElement
    use_case: TaxonomyElement
    image: LinkedItemsElement
    lob: TaxonomyElement
    app: TextElement
}

type HomepagePackageContentType implements ContentItem {
    system: SystemInfo!
    lob_description: TextElement
    metadata__metadata_description: TextElement
    industry_description: TextElement
    lob_industry_title: LinkedItemsElement
    metadata__metadata_title: TextElement
    anaplan_navigator: UrlSlugElement
    industry_tagline: TextElement
    intro_video: LinkedItemsElement
    intro_text: TextElement
    lob_tagline: TextElement
    banner_image: LinkedItemsElement
    intro_title: TextElement
}

type ImageContentType implements ContentItem {
    system: SystemInfo!
    image_use_description: TextElement
    lob: TaxonomyElement
    image: AssetElement
    industry: TaxonomyElement
    accessibility_description: TextElement
}

type IndustrySubSectorContentType implements ContentItem {
    system: SystemInfo!
    short_text: TextElement
    solution_package: LinkedItemsElement
    industry: TaxonomyElement
    medium_text: TextElement
    icon: AssetElement
}

type LobIndustryContentType implements ContentItem {
    system: SystemInfo!
    sitemap: TaxonomyElement
    banner_image: LinkedItemsElement
    industry: TaxonomyElement
    short_text: TextElement
    lob: TaxonomyElement
    medium_text: TextElement
}

type LobIndustryLandingPackageContentType implements ContentItem {
    system: SystemInfo!
    metadata__metadata_description: TextElement
    lob_industry: LinkedItemsElement
    metadata__metadata_title: TextElement
    anaplan_navigator: UrlSlugElement
    industry_sub_sector: LinkedItemsElement
    type: TaxonomyElement
    icon: AssetElement
    solution_package: LinkedItemsElement
}

type NavigationItemContentType implements ContentItem {
    system: SystemInfo!
    metadata__metadata_description: TextElement
    metadata__metadata_title: TextElement
    url: UrlSlugElement
    page_item: LinkedItemsElement
    subitems: LinkedItemsElement
    sitemap: TaxonomyElement
    title: TextElement
    description: TextElement
}

type OverviewContentType implements ContentItem {
    system: SystemInfo!
    description: TextElement
    original_content_link: TextElement
    pdf: AssetElement
}

type SolutionPackageContentType implements ContentItem {
    system: SystemInfo!
    video: LinkedItemsElement
    icon: AssetElement
    use_cases: LinkedItemsElement
    carousel_card_s_: LinkedItemsElement
    multi_length_description__long_text: TextElement
    multi_length_description__medium_text: TextElement
    differentiator___medium_text: TextElement
    sitemap: TaxonomyElement
    multi_length_description__short_text: TextElement
    connections_image: LinkedItemsElement
    solution: TaxonomyElement
    lob: TaxonomyElement
    differentiator___short_text: TextElement
    industry: TaxonomyElement
    differentiator___long_text: TextElement
}

type StandardPackageDescriptionsContentType implements ContentItem {
    system: SystemInfo!
    medium_description: TextElement
    short_description: TextElement
    image: LinkedItemsElement
}

type UseCasePackageContentType implements ContentItem {
    system: SystemInfo!
    scoping_checklist_description: LinkedItemsElement
    anaplan_navigator: UrlSlugElement
    metadata__metadata_description: TextElement
    carousel_card_s_: LinkedItemsElement
    solution: TaxonomyElement
    architectural_overview_description: LinkedItemsElement
    architectural_overview___original_content_link: TextElement
    metadata__metadata_title: TextElement
    banner_image: LinkedItemsElement
    scoping_checklist_pdf: AssetElement
    icon: AssetElement
    sitemap: TaxonomyElement
    scoping_checklist___original_content_link: TextElement
    multi_length_description__long_text: TextElement
    multi_length_description__medium_text: TextElement
    best_practices_video: LinkedItemsElement
    architectural_overview_pdf: AssetElement
    architectural_overview_image: LinkedItemsElement
    industry: TaxonomyElement
    multi_length_description__short_text: TextElement
    best_practices_description: LinkedItemsElement
    use_case: TaxonomyElement
    lob: TaxonomyElement
}

type ValuePropositionContentType implements ContentItem {
    system: SystemInfo!
    url: TextElement
    pdf: AssetElement
    description: TextElement
    original_content_link: TextElement
}

type VideoContentType implements ContentItem {
    system: SystemInfo!
    caption: TextElement
    lob: TaxonomyElement
    use_case: TaxonomyElement
    visibility: TaxonomyElement
    description: TextElement
    industry: TaxonomyElement
    solution: TaxonomyElement
    video_url: TextElement
}

type WhitepaperContentType implements ContentItem {
    system: SystemInfo!
    pdf: AssetElement
    description: TextElement
    original_content_link: TextElement
    url: TextElement
}`

On newly created projects gridsome has worked great. I think it may be an issue with this plugin trying to parse data that has not had logic written for it in the plugin, I've tried to debug but need to learn more on how to get verbose output if that's possible from plugin.

Thanks! Any help appreciated.

**Comment by johncherba** [comment]
The issue was with older data in Kontent. Thanks!

**Comment by a-kriya** [comment]
Didn't do anything (except be a rubber duck, I suppose :), but glad you figured it out.
