### ISSUE TITLE
G-Image with SCSS

### ISSUE THREAD

**Issue by chug2k** [gridsome/gridsome#108]
## Summary

I have a local image that I want to reference from my SCSS; e.g. the background image of a hero section.

### Basic example
```
<section class="hero is-large has-bg-img"> 
   <div class="hero-body"> 
     <div class="container has-text-centered"> 
     <h1 class="title">Title 1</h1> 
     <h2 class="subtitle">Subtitle 3</h2> 
    </div> 
   </div> 
</section>
---scss---

.has-bg-img { background: url('/assets/images/img.jpg')center center; background-size:cover; }
```

### Motivation

Most websites need this type of functionality.

**Comment by EldoranDev** [comment]
If you do not need the resizing and lazy loading of the g-image then you allready can to that by placing your assets inside of the [static](https://gridsome.org/docs/directory-structure/#the-static-directory) folder.

**Comment by chug2k** [comment]
thanks for the super fast reply. ah, i didn't know that, makes a few things easier. (i was wondering how gridsome was finding my favicon, it's not in any static directory.)

it would be nice to be resized and lazy-loaded too, as hero-images are pretty big. but this is a good enough workaround for now. thanks!
