### ISSUE TITLE
Is there a better way to create a page for each category?

### ISSUE THREAD

**Issue by RankinKeanan** [gridsome/gridsome#1082]
I use `gridsome-source-mysql` plugin to get data from MySQL.

The articles has more than 50 categories, I want to create a page for each category.

Now my code looks like this:

-  `./src/components/Category01.vue` file: 
```
<template>
  ...
  ...
</template>

<static-query>
query {
  allPosts(filter: { Category: { in: ["Category01"] }})  {
    edges {
      node {
        id
        Category
        Title
      }
    }
  }
}
</static-query>

<script>
export default {
    name: "Category01",
};
</script>
```

-  `./src/components/Category02.vue` file: 
```
<template>
  ...
  ...
</template>

<static-query>
query {
  allPosts(filter: { Category: { in: ["Category02"] }})  {
    edges {
      node {
        id
        Category
        Title
      }
    }
  }
}
</static-query>

<script>
export default {
    name: "Category02",
};
</script>
```

All are the same except for the different category name.

Is there a better way to create a page for each category?

Thank you!

**Comment by noxify** [comment]
Hi,

yes, you can!

You only need one template for your categories.

### Preview
* https://gridsome-starter-casper-v3.now.sh/category/getting-started
* https://gridsome-starter-casper-v3.now.sh/category/health/

### How did I solved it?

In the `gridsome.config.js` I have defined a template for the `Category` collection:
It includes the template which should be used and also the path ( see the preview links above ).
Source: https://github.com/noxify/gridsome-starter-casper-v3/blob/master/gridsome.config.js#L75

The template contains the the html logic and runs a query against the `category` collection.
And here is the difference to your current solution. You're currently using the `posts` collection.

https://github.com/noxify/gridsome-starter-casper-v3/blob/master/src/templates/Category.vue#L38

Maybe you have to configure some relations in the `gridsome.config.js` to make it work ( if you haven't ;) ) .

Hope that helps.

Regards,
Marcus

**Comment by RankinKeanan** [comment]
@noxify This is a good idea, thank you! ❤
