### ISSUE TITLE
g-image width/height not being set

### ISSUE THREAD

**Issue by jmeintrup** [gridsome/gridsome#1084]
## Description

The width and height of g-image are being ignored.

### Steps to reproduce

```
<template>
<g-image
        :src="$page.article.image"
        width="500"
        height="500"
/>
<template>
```
```
<page-query> 
query ($path: String!) {
    article: articles (path: $path) {
        image 
    }
}
</page-query>
```

article.md:
```
---
image: /uploads/pexels-photo-167698.jpeg
---
```

### Expected result

The image should have widht/height 500px.

### Actual result

The resulting img:
```<img data-v-54cdc180="" src="/uploads/pexels-photo-167698.jpeg" class="g-image">```
has no width or height set.
src is correctly set.

When using a normal ```<img>``` it works as expected.

### Environment
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  Binaries:
    Node: 13.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.13
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9
    gridsome-plugin-tailwindcss: ^2.2.43 => 2.2.43

**Comment by a-kriya** [comment]
This is due to using v-bind (the `:` in `:src`), and there's an open bug report at #292 with some workarounds. Would you mind closing this ticket?
