### ISSUE TITLE
Does someone have an solution for vue2-leaflet to do not display window is not defined

### ISSUE THREAD

**Issue by Jasperfr74** [gridsome/gridsome#1092]
## Description

All the time when I try to build my project I have an error throw by Leaflet window is not defined ..
I'va try a lot to fix this but I cannot can someone have a solution to this problem please ?

Describe the issue that you're seeing.

7:07:04 PM: ReferenceError: window is not defined
7:07:04 PM:     at assets/js/app.164f23d4.js:4961:17
7:07:04 PM:     at module.exports.version (node_modules/leaflet/dist/leaflet-src.js:7:61)
7:07:04 PM:     at Object.<anonymous> (node_modules/leaflet/dist/leaflet-src.js:10:1)

### Steps to reproduce

Just run gridsome, install leaflet, make a map and try to build, you will have this ssr error showing "window is not defined" ....

### Expected result

to build ...

### Actual result

"window is not defined" 

Paste the information here as shown by `gridsome info`

<ClientOnly>
   <Leaflet />
</ClientOnly>

I've wrap it into ClientOnly but doesn't work .. and I do not share this component globally so nothing in my main.js .. 

Can someone help me please ..

**Comment by whizkydee** [comment]
If you already wrapped the components in `ClientOnly`, did you make sure to async import them like:

```js
export default {
  components: {
    LMap: () =>
      import('vue2-leaflet')
        .then(m => m.LMap)
        .catch(),
    LTileLayer: () =>
      import('vue2-leaflet')
        .then(m => m.LTileLayer)
        .catch(),
  }
}
```

Let me know how that works out for you.

**Comment by Jasperfr74** [comment]
Yep sorry to replay late,i finally figure it out  by doing the way you've showed me. I did it into my main.js and wrap it into (if isclient) Then it works ! Thx for your help !
