### ISSUE TITLE
Add Custom Frontmatter Properties Avilable in GraphQL

### ISSUE THREAD

**Issue by RehanSaeed** [gridsome/gridsome#1094]
## Summary

I would like to add additional custom frontmatter properties like the ones below and have them be available in my GraphQL query:

```
---
dateModified: "2010-01-01"
cover_image_height: 900
cover_image_width: 1600
cover_image_alt: "Alternative text for the cover image"
---
```

If `cover_image_height` and `cover_image_width` can be automatically generated and available in GraphQL then even better.

```
<page-query>
query Post ($id: ID!) {
  post: post (id: $id) {
    title
    date (format: "YYYY-MM-DD")
    dateModified (format: "YYYY-MM-DD")
    cover_image (blur: 10)
    cover_image_height
    cover_image_width
    cover_image_alt
  }
}
</page-query>
```

### Motivation

Custom properties can be usefule for lots of things. I want the fields above because:

1. `dateModifed` is used in Google structured data and Open Graph meta tags.
2. `cover_image_height` and `cover_image_width` is required for meta tags too but might also be useful for other reasons.
3. `cover_image_alt` is to fill in the `alt` tag for `<g-image>`.

**Comment by a-kriya** [comment]
I have a page query as such:
```
query {
  allMgmtTeam(sortBy: "id", order: ASC) {
    edges {
      node {
        id
        name
        title
        photo
        content
      }
    }
  }
}
```

`name`, `title` and `photo` are custom frontmatter props, and I didn't have to do anything special. Does it not work for you? Did you try restarting server, and browsing in GQL playground?

**Comment by RehanSaeed** [comment]
Seems to be working now. Strange...
