### ISSUE TITLE
plugin-critical: Prototype Pollution

### ISSUE THREAD

**Issue by dargmuesli** [gridsome/gridsome#1101]
See https://app.snyk.io/vuln/SNYK-JS-YARGSPARSER-560381.
Should be fixed by `critical:v2.0.0-24`.

**Comment by hjvedvik** [comment]
Yes, looks like `v2.0.0-24` will fix this :) It's not released as the latest version yet, so I'm not sure how stable it is. But I'll try to do some tests tomorrow.

**Comment by dargmuesli** [comment]
Hey there, any results yet? :)

**Comment by dargmuesli** [comment]
For some reason I needed to follow this guide as my docker builds failed after updating `plugin-critical` to `0.2.0`: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

But it works now! Thank you!

**Comment by hjvedvik** [comment]
Thanks for the info, @dargmuesli. Glad you got it working! It seems to work fine on Netlify, but we can probably add something to the readme file if more people struggle to get it working in other environments.
