### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by cbaone** [gridsome/gridsome#1102]
## Description

Build error on netlify.  

### Steps to reproduce

Use similar code to this:
```javascript
data: () => ({
    showMessage: !localStorage.getItem("hideMessage"),
}),
methods: {
  dismissMessage: function(){
    this.showMessage = false;
    localStorage.setItem("hideMessage", true);
  },
```

### Expected result

Should build and deploy in Netlify without issue

### Actual result

Got errors and build failed. localStorage is not defined

```
12:00:04 PM: ReferenceError: localStorage is not defined
12:00:04 PM:     at a.data (src/layouts/Default.vue:232:18)
12:00:04 PM:     at /opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28667
12:00:04 PM:     at /opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28727
12:00:04 PM:     at pn (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28934)
12:00:04 PM:     at a.e._init (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32700)
12:00:04 PM:     at new a (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
12:00:04 PM:     at Vi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:66307)
12:00:04 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70537)
12:00:04 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70210)
12:00:04 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67457)
```

### Environment

Gridsome 0.7.13

Sorry about the noob question, but I get a build error running a build in netlify. Obviously, it builds fine locally, but it errors out when building in netlify. I found this: https://github.com/gridsome/gridsome/issues/191 and it seems like it's nearly identical - except I'm not referencing external library use of localStorage.

What's the best way to get Netlify to ignore the localStorage reference?

**Comment by hjvedvik** [comment]
`localStorage` isn't available in a Node.js environment, unfortunately... So it fails when generating the markup. You can use `process.isClient` to check if you are in the browser. Something like this should work:

```js
data: () => ({
    showMessage: process.isClient
        ? !localStorage.getItem("hideMessage")
        : false,
})
```

**Comment by yb-admin** [comment]
worked like a charm! thanks!
