### ISSUE TITLE
Displaying a background image

### ISSUE THREAD

**Issue by sebastien-metzger** [gridsome/gridsome#1103]
Hello,

This is the first time that I use Gridsome and I have chosen Tailwind as a CSS framework. I am trying to display a background image with the following code but the image is not found:
```
<section
            id="hero"
            class="bg-no-repeat bg-center w-full h-24"
            style="background-image: url('~@/assets/images/hero-left.jpg');"
        ></section>
```

My assets are located in src directory (project_root/src/assets/images). What am I doing wrong?

Have a great day.
Best regards,

**Comment by a-kriya** [comment]
A few things:

- With single-file components, there's little reason to write inline styles, unless you're making them reactive and binding to something.
- One alias should be used. So, either `~` or `@`, but not both.
- As far as I know, neither of those work outside of JS. So, for CSS, I've had to use relative paths.

```vue
<template>
  <section
    id="hero"
    class="bg-no-repeat bg-center w-full h-24"
  ></section>
</template>

<style scoped>
#hero {
  background-image: url(../../assets/images/hero-left.jpg);
}
</style>
```

The number of `../` will depend on how deep that component file is nested under src/.

**Comment by nicolaisimonsen** [comment]
@sebastien-metzger

`:style="{
                  'background-image':
                    'url(' + require('../assets/images/hero-left.jpg') + ')'
                }"`

OR you could reference the image in props / data() and then do:

>  :style="`background-image: url( ${image.url} )`" 

Hope that helps 🙂

**Comment by sebastien-metzger** [comment]
Thank you @a-kriya and @nicolaisimonsen !

I am using the current solution:
`
<template>
<section
            id="hero"
            class="bg-hero py-40 bg-cover bg-no-repeat bg-center flex justify-center"
        ></section>
</template>
<style>
.bg-hero {
        background-image: url("~@/assets/images/hero-background.jpg");
    }
</style>
`

I must use "~@" and I think it is related to Webpack.

Have a great day!

**Comment by a-kriya** [comment]
@sebastien-metzger Great! I can fix those relative paths in my project now, too. Thanks!
