### ISSUE TITLE
[question] best cms for headless with gridsome

### ISSUE THREAD

**Issue by Acadomia** [gridsome/gridsome#1111]
Hi,

I am wondering what is the best cms out of the box to use with Gridsome ?

I am building the front of a website with Gridsome, so far, so good, having great optimized static pages and loving to query datas with GraphQl ( I am still on the learning curve though and still need to use computed properties sometimes to filter the datas I want ).

What are you guys using ? And what is your feedback about it ?
I see more and more choices available and many some still in betas and quite recent.

In my requirements, it is necessary to use a components system so in the cms admin, it is possible to choose several components ( like a hero block, a map bloc, ... )  with datas per page and create pages of course.

**Comment by joeelia** [comment]
I like Forestry.io. No need to worry about a server crashing with git based updates! I honestly sleep a little easier now

**Comment by nicolaisimonsen** [comment]
We use Wordpress w/ [WPGraphQL](https://www.wpgraphql.com/). It's not new or sexy, and likely not the "best", but it's been a rather painless transition to headless cms. 👍 
Definitely want to try out strapi.io soon. The pricing on Craft, Contentful is really up there.

**Comment by dikaio** [comment]
I'd think [Prismic](https://prismic.io) would be at the top of the list too.

**Comment by nelsonacadomia** [comment]
> We use Wordpress w/ [WPGraphQL](https://www.wpgraphql.com/). It's not new or sexy, and likely not the "best", but it's been a rather painless transition to headless cms w/ Gridsome. 👍
> Definitely want to try out strapi.io soon. The pricing on Craft, Contentful is really up there.

I'm wondring if you use WP and Gridsome with the WP Gutenberg or custom acf ?

**Comment by nicolaisimonsen** [comment]
@nelsonacadomia 
Custom ACF. It's supported by WPGraphQL as well 🙂

**Comment by invatom** [comment]
I tried Netlify CMS (gitbased). It just did not work for us. 
So we build a version with forestry, worked ok but felt a bit simplistic for our use (not picking on it, this might be a feature depending on what you look for).
Eventually after checking a few other (ghost, strapi) we ended up with Storyblok that has worked very nicely for us. Can recommend. www.storyblok.com

**Comment by MarcelloTheArcane** [comment]
[Voting to close this as opinion-based](https://meta.stackexchange.com/help/closed-questions) 😉 

In all honesty, all you're going to get is a list of every possible CMS, as everyone has a different preference and use-case.

**Comment by rafasoares** [comment]
While I agree with @MarcelloTheArcane, an objective way to answer this question would be "which CMS has the best integration with Gridsome?"

I started out using Contentful, and while it does serve our needs in terms of content management, the integration with Gridsome is lacking in some ways, like not supporting tags or locales out of the box. It also uses the REST API, while Contentful has since launched [their own GraphQL API](https://www.contentful.com/developers/docs/references/graphql/).
