### ISSUE TITLE
Build freezing browser and not loading properly

### ISSUE THREAD

**Issue by luandro** [gridsome/gridsome#1112]
## Description

When developing site seems to be working perfectly. But once deployed it freezes the browser and doesn't load properly.

### Steps to reproduce

A deployed version can be seen here:
https://jovial-neumann-1ef56d.netlify.app/

The project code lives here:
https://github.com/luandro/portfolio-gridsome

### Expected result

Since it's just static website, it should simply load without any problems.

### Actual result

Freezes the browser, doesn't load the images and the whole content.

### Environment

```
  System:
    OS: Linux 5.5 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v10.17.0/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Firefox: 74.0
  npmPackages:
    @gridsome/source-filesystem: ^0.5.0 => 0.5.0 
    @gridsome/transformer-remark: ^0.3.2 => 0.3.2 
    gridsome: ^0.6.0 => 0.6.7 
```

**Comment by hjvedvik** [comment]
It seems to freeze when loading the JSON data. But I'm not sure why yet. Can you try to update to the latest version of Gridsome and see if the issue still exists?

**Comment by luandro** [comment]
Thanks for the response @hjvedvik! Updated all dependencies to latest, but the problem seems to persist. Any ideas?

**Comment by hjvedvik** [comment]
You have a few issues in the HTML markup. I'm not sure if it will fix this issue, but you can try to change these lines into `div` elements instead:
- https://github.com/luandro/portfolio-gridsome/blob/master/src/components/Timeline.vue#L15
- https://github.com/luandro/portfolio-gridsome/blob/master/src/components/ProjectList.vue#L30

**Comment by luandro** [comment]
Yes, that seems to have solved the issue! Great catch @hjvedvik, thank you :tada:

**Comment by rasulkireev** [comment]
I'm running into the same issue. 

I am loading data via a JSON file, and the browser freezes on load (in production). It used to work just fine, but I can't really tell what happened to cause this. Would anyone have any clue as to why this could be happening?

this is how I load it in **[Newsletter.vue](https://github.com/rasulkireev/gridsome-personal-webite/blob/master/src/pages/Newsletter.vue)**:

```html
<template>
    <Layout>
        <section id="letters">
            <ul v-for="letter in newsletter.reverse()" :key="letter.id">
                <li>
                    <a :href="letter.url">
                        {{ letter.title }}
                    </a>
                </li>
            </ul>
        </section>
    </Layout>
</template>

<script>
import { newsletterLetters } from "../data/newsletter.js"

export default {
    data () {
        return {
            newsletter: newsletterLetters,
        }
    },
}
</script>
```

and **newsletter.js**

```javascript
export const newsletterLetters = [
    {
        id: 1,
        url: 'https://buttondown.email/rasulkireev/archive/letter-1-fresh-start-correction/',
        title: "Letter #1 - Fresh Start",
        date: '2020/05/12',
    },
    ...
]
```

**Comment by rasulkireev** [comment]
@hjvedvik Can we please reopen this issue, since the underlying problem was not solved?

**Comment by hjvedvik** [comment]
@rasulkireev I've looked at your project now, and I don't think there is an issue with Gridsome :)

The newsletter array is added to the component data, which will make it reactive. And when `newsletter.reverse()` is called within the template, it will trigger an infinite update loop. Because `reverse()` mutates the original array. The issue can be fixed in numerous ways. But the simplest solution might be to just copy the array before reversing it, like: `newsletter.slice().reverse()`.

**Comment by rasulkireev** [comment]
Well, that's embarassing... 

Thanks a ton @hjvedvik.
