### ISSUE TITLE
[Question] Loading screen on page load / before app is rendered

### ISSUE THREAD

**Issue by nicolaisimonsen** [gridsome/gridsome#1113]
Lovers of Gridsome 👋,

No bug - just a buggy developer. However, I could really use some help:

How would you go about creating a loading screen that fires on the page load? A screen that's visible before Gridsome renders all of the vue instances, routing etc. Should be the absolute first thing visible. 

Any thoughts/tips? 🙂

**Comment by Microflash** [comment]
You can always create an App.vue or index.html and add your transitions inline for this purpose. An example of **index.html** usage is on the Official Gridsome site [here](https://github.com/gridsome/gridsome.org/blob/master/src/index.html). The documentation is available [here](https://gridsome.org/docs/overriding-index/#overriding-indexhtml).

**Comment by nicolaisimonsen** [comment]
Thanks a lot @Microflash !
