### ISSUE TITLE
Creating new app fails installing dependencies!

### ISSUE THREAD

**Issue by olakara** [gridsome/gridsome#1115]
## Description

Creating a new Gridsome application fails while installing dependencies

### Steps to reproduce

1. Install latest version of CLI
2. Run command: `gridsome create first-gridsome`
3. Does not complete installation of dependencies.  

### Expected result

Should install dependencies and be ready to run 

### Actual result

`error D:\Workspace\Trails\first-gridsome\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\Workspace\Trails\first-gridsome\node_modules\pngquant-bin
Output:
‼ Response code 500 (Internal Server Error)
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed`

### Environment

 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  Binaries:
    Node: 10.18.0 - C:\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.14

**Comment by dikaio** [comment]
@olakara Maybe uninstalling and reinstalling libpng-dev?

**Comment by olakara** [comment]
Deleting the CLI and reinstalling it some how fixed the issue. I am not sure what caused the problem. I am not able to reproduce this after few hours.
