### ISSUE TITLE
[Question] Querying gridsome.config.js

### ISSUE THREAD

**Issue by gitcro** [gridsome/gridsome#1116]
I've tried to puzzle things together from the official docs, didn't succeed though...

So: How can I query the 'siteUrl' field in gridsome.config.js on a page using <page-query>? Does anyone have a working example?

Thanks!

**Comment by noxify** [comment]
Hi @gitcro ,

the `siteUrl` should be available in the `metadata` collection in graphql.
But if it's not filled in the ´gridsome.config.js`, it should be `null`.

Hope that helps.

**Comment by joeelia** [comment]
In config you need something like this

module.exports = {
  siteName: 'Awesome Site',
  siteUrl: 'https://awesomesite.com',
  metadata: {
   siteUrl: 'https://awesomesite.com',
  },
.........
}

Then when you want to call the metadata in a .vue file do this:

<static-query>
query {
  metadata {
    siteUrl
  }
}
</static-query>

Print the value inside of <Template> like this:

$static.metadata.siteUrl

Print the value inside of <script> like this:

this.$static.metadata.siteUrl


Excuse my formatting. On mobile

**Comment by gitcro** [comment]
Thanks @joeelia, I did that. But to 

`this.$static.metadata.siteUrl`

inside the <script> tag the browser responds with

> TypeError: Cannot read property '$static' of undefined

Any idea why?

**Comment by gitcro** [comment]
Oh, someone explained it nicely: https://github.com/gridsome/gridsome/issues/306#issuecomment-475967333
