### ISSUE TITLE
gridsome build somehow breaks styles all over site

### ISSUE THREAD

**Issue by Waaflee** [gridsome/gridsome#1117]
## Description

Using latest packages when building for deploys all my stiles are screwed up. When using gridsome develop all seems to be fine, but after the build (I serve with python HTTP.server module because gridsome serve it's also broken) the site it's messed up. This happens on netlify deploy also so it's not just my node version doing weird things.

Edit: rolling back several version commits when building the same page with gridsome 7.11 everything works well, so it's current version issue.

### Steps to reproduce
using gridsome v7.14
Develop using gridsome develop and get surprised with what you see after gridsome build.

### Expected result

What should happen?

The site should be displayed correctly.

### Actual result

Something partially broke all my css.

### Environment

  System:
    OS: Linux 5.6 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  Binaries:
    Node: 13.13.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Firefox: 75.0

**Comment by noxify** [comment]
Are you using purgecss or a similar plugin?

**Comment by Waaflee** [comment]
Yes, I'm using tailwindcss plugin and therefore pugecss, any fix?

**Comment by joeelia** [comment]
Trying following this article and it should work fine: https://thevueguy.com/blog/how-to-install-tailwind-gridsome/

**Comment by Waaflee** [comment]
Will try thank you so much, really. Currently I've disabled purgecss on
tailwind plugin configuration. I will try to migrate to this more
conventional config. Awesome community around here, keep it up.

**Comment by joeelia** [comment]
@Waaflee if it worked for you close the issue.
