### ISSUE TITLE
(transformer-remark) Generate excerpt automatically

### ISSUE THREAD

**Issue by bongnv** [gridsome/gridsome#1133]
## Summary

Currently, with `@gridesome/transformer-remark`, `excerpt` has to be added manually in the markdown file. There is a work around to generate it automatically by passing a custom [`excerpt` function](https://github.com/bongnv/transformer-remark/blob/master/index.js#L121) to gray matter. However, the function is limited due to that content is raw and not parsed.

Therefore, it would be nice to have an autogenerated excerpt which is a prefix text extracted from the content. One example of the implementation can be `excerpt` in [`Gatsby`](https://using-remark.gatsbyjs.org/excerpts/)

I've implemented one for my personal blog. You can refer to https://github.com/bongnv/transformer-remark/blob/master/index.js#L121 to have a review.

### Basic example

In order to achieve backward compatibility, we can add new field `prunedText` and it can be queried with GraphQL like:
```
<page-query>
  query {
    posts: allBlogPost {
      edges {
        node {
          id
          title
          date(format: "D. MMMM YYYY")
          path
          timeToRead
          excerpt
          prunedText(pruneLength: 200)
        }
      }
    }
  }
</page-query>
```

Later, it can be rendered like:
```
{{ post.excerpt || post.prunedText }}
```

### Motivation

Not every posts have an excerpt, the feature will provide an automated excerpt to increase the richness of transformed content.

**Comment by noxify** [comment]
We have already a PR for this topic :)

Checkout: https://github.com/gridsome/gridsome/pull/1085

**Comment by noxify** [comment]
I close this issue since the related PR is merged - but feel free to reopen it, if the mentioned PR isn’t the same as what you have described.

Regards,
Marcus

**Comment by bongnv** [comment]
Yes, it's what I would expect. Somehow I couldn't see it in my search. Thanks
