### ISSUE TITLE
File-Based Dynamic Routing Parameters Returning undefined

### ISSUE THREAD

**Issue by CodingCarter** [gridsome/gridsome#1141]
## Description

I am trying to use the file-based dynamic routing with the tmdb api, but when I try to pull the parameters from the url, it always returns undefined.

### Steps to reproduce

Go to http://localhost:8080/movie/550 to see the error

The file below is located in ~/pages/movie/[id].vue

```
<template>
    <Layout>
        <div v-if="movie">
            {{movie}}
        </div>
    </Layout>
</template>

<script>
export default {
  data() {
    return {
      movie: null
    }
  },
  async mounted() {
    const { movieID } = this.$route.params.id
   
    const response = await fetch(
        `https://api.themoviedb.org/3/movie/${movieID}?api_key=MY_API_KEY`,
        {
            "Content-Type": "application/json;charset=utf-8'"
        }
    )

    this.movie = await response.json()
  }
}
</script>
```

### Expected result

The div should be printing out a json object with the response from the fetch!

### Actual result

The div is printing out 
{ "status_code": 34, "status_message": "The resource you requested could not be found." }

I looked in the console and saw that the url that the fetch function used was
https://api.themoviedb.org/3/movie/undefined?api_key=MY_API_KEY

Therefore, there is something wrong with the parameters being loaded into my file.

### Environment
  System:
    OS: Windows 10 Pro
    CPU: x64 Intel(R) Core(TM) i7-8550U CPU @ 2.00GHz
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12 
  npmGlobalPackages:
    @gridsome/cli: 0.2.1

**Comment by hjvedvik** [comment]
Can you try to change this line and see if it helps?
```diff
- const { movieID } = this.$route.params.id
+ const movieID = this.$route.params.id
```

**Comment by CodingCarter** [comment]
> Can you try to change this line and see if it helps?
> 
> ```diff
> - const { movieID } = this.$route.params.id
> + const movieID = this.$route.params.id
> ```

Oh my gosh thank you so much!  I don't understand why that didn't work though, because that is the exact code that is found on the gridsome documenation.  https://gridsome.org/docs/dynamic-routing/#file-based-dynamic-routes
