### ISSUE TITLE
Cannot addEventListener (scroll)

### ISSUE THREAD

**Issue by oskery** [gridsome/gridsome#1143]
## Description

I am attempting to add eventlisteners for scrolling, something that I am familiar with in VueJS at least, but I cannot get it to work in Gridsome.

### Steps to reproduce

I am using the below code in my Template. I have tried this code in a page component as well, and even created a custom App.vue to see if I had to put it there.

`
created () {
    window.addEventListener('scroll', this.handleScroll);
  },
  destroyed () {
    window.removeEventListener('scroll', this.handleScroll);
  },
  methods: {
    handleScroll (event) {
      console.log("Scrolling")
    }
  }
`

### Expected result

Logging "Scrolling" when the user is scrolling.

### Actual result

Nothing is being logged. If I register this.handleScroll() instead the method is being called once (obviously I guess, dont know if that says anything though).

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 12.16.3 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    @gridsome/source-graphql: ^0.1.0 => 0.1.0 
    gridsome: ^0.7.0 => 0.7.13 
    gridsome-plugin-simple-analytics: ^1.1.0 => 1.1.0

**Comment by a-kriya** [comment]
Does that work on dev server, but you see a `window` not defined error during build?

If so, try switching that `created()` to `mounted()`.

**Comment by oskery** [comment]
> Does that work on dev server, but you see a `window` not defined error during build?
I am experiencing this problem during development. I know that issues occur with window/document keyword and SSR/SSG but this is not related to my current issue.

> If so, try switching that `created()` to `mounted()`.
Same problem when adding the listener in mounted instead.

**Comment by a-kriya** [comment]
It must be something else interfering with it then. I just copied your code as is to the starter template, and it works:

<img src="https://user-images.githubusercontent.com/26761352/80915685-98a51d00-8d71-11ea-803b-c889ddeaf404.png" height="200" />

<img src="https://user-images.githubusercontent.com/26761352/80915666-74e1d700-8d71-11ea-845f-6a46436820f6.png" height="200" />

**Comment by oskery** [comment]
Okey that is good to know! I will look over the code, especially the javascript related stuff. Since it is a Template it does not have many wrapping functions/containers but I guess since everything is statically generated it could be caused by anything, anywhere in the project?

This are my dependencies btw:

    "@gridsome/plugin-sitemap": "^0.2.3",
    "@gridsome/source-graphql": "^0.1.0",
    "gh-pages": "^2.2.0",
    "gridsome": "^0.7.0",
    "gridsome-plugin-simple-analytics": "^1.1.0",
    "less": "^3.11.1",
    "less-loader": "^5.0.0",
    "smoothscroll-polyfill": "^0.4.4",
    "typeface-open-sans": "^0.0.75",
    "vuex": "^3.1.3"

**Comment by oskery** [comment]
Is there anyway I can debug this in a smart way, I am looking for errors in the console but nothing appears.

**Comment by a-kriya** [comment]
>since everything is statically generated it could be caused by anything, anywhere in the project?

As far as I can tell, that shouldn't be the case. Try to create a new static page with static content and just those handlers. You can use this if you want.

```vue
<template>
  <Layout>
    <h1>Hello, world!</h1>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur excepturi labore tempore expedita, et iste tenetur suscipit explicabo! Dolores, aperiam non officia eos quod asperiores
    </p>

    <p class="home-links">
      <a href="https://gridsome.org/docs/" target="_blank" rel="noopener">Gridsome Docs</a>
      <a href="https://github.com/gridsome/gridsome" target="_blank" rel="noopener">GitHub</a>
    </p>

    <h1>Hello, world!</h1>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur excepturi labore tempore expedita, et iste tenetur suscipit explicabo! Dolores, aperiam non officia eos quod asperiores
    </p>

    <p class="home-links">
      <a href="https://gridsome.org/docs/" target="_blank" rel="noopener">Gridsome Docs</a>
      <a href="https://github.com/gridsome/gridsome" target="_blank" rel="noopener">GitHub</a>
    </p>

    <h1>Hello, world!</h1>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur excepturi labore tempore expedita, et iste tenetur suscipit explicabo! Dolores, aperiam non officia eos quod asperiores
    </p>

    <p class="home-links">
      <a href="https://gridsome.org/docs/" target="_blank" rel="noopener">Gridsome Docs</a>
      <a href="https://github.com/gridsome/gridsome" target="_blank" rel="noopener">GitHub</a>
    </p>

  </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: 'Hello, world!'
  },

  created() {
    window.addEventListener('scroll', this.handleScroll);
  },

  destroyed() {
    window.removeEventListener('scroll', this.handleScroll);
  },

  methods: {
    handleScroll(event) {
      console.log("Scrolling")
    }
  }
}
</script>

<style>
.home-links a {
  margin-right: 1rem;
}
</style>
```

**Comment by oskery** [comment]
Thank you for the suggestion! I tried to do it in src/layouts/Default.vue and indeed it worked!

Default.vue wraps my template so I tried to inject the listener to the container div inside Default and then it works:

Default.vue
```
<template>
  <div id="app">
    <custom-header />
    <slot />
    <custom-footer />
  </div>
</template>
```
Template.vue
```
beforeDestroy () {
  document.getElementById("app").removeEventListener('scroll', this.handleScroll);
},
mounted() {
  document.getElementById("app").addEventListener('scroll', this.handleScroll);
},
methods: {
  handleScroll(e) {
    console.log('Scrolling')
  }
}
```
Not sure that this is an optimal solution, but at least it works.

**Comment by a-kriya** [comment]
Okay, great. Did you have to switch to `#app` because `window` still didn't work?

**Comment by oskery** [comment]
> Okay, great. Did you have to switch to `#app` because `window` still didn't work?

Correct, window still does not work inside Template.vue. It only works in Default.vue but I need my scrollhandler inside Template.vue so this was the only solution I could think of.

**Comment by a-kriya** [comment]
Shouldn't happen unless the scroll event is somehow not being bubbled up to window. Do you have multiple scrollable/overflowing elements on the page?

Can you try attaching a scroll handler to window in the JS console of the browser instead of in the components?

**Comment by oskery** [comment]
At the start of this project (I think) I might have tried to tweak with some of the root divs, in VueJS I always remove the wrapping div and use the body tag instead (personal preference). I did look at some example projects for Gridsome however and I cannot identify any differences, I have also been playing around with Gatsby so I might be mixing up memories.

> Can you try attaching a scroll handler to window in the JS console of the browser instead of in the components?

`window.addEventListener('scroll', () => console.log("ey"))` (in Chrome console)

returns undefined, same if I reference `this.handleScroll` instead of arrow function

**Comment by a-kriya** [comment]
The call to `addEventListener` will indeed return undefined, and `this.handleScroll` cannot be referenced outside the component where it's defined so that's all good. What _is_ expected is `ey` being logged when you scroll on the page after running that in the console. Does that happen?

By the way, you can also inspect/remove any existing scroll listeners on Window object in the DevTools when you select the html element in the Elements pane:

<img src="https://user-images.githubusercontent.com/26761352/80917931-ac578000-8d7f-11ea-8dc5-8da1a41a3b29.png" height="200" />

This may help checking if smoothscroll polyfill is affecting anything.

**Comment by oskery** [comment]
> What is expected is ey being logged when you scroll on the page after running that in the console. Does that happen?

No, nothing is being logged after I wrote that. The event listeners tab however suggest that the event is registered? 
![Screenshot from 2020-05-03 17-29-14](https://user-images.githubusercontent.com/28003429/80918145-ac498700-8d63-11ea-916a-4dcbf13d7a56.png)

**Comment by oskery** [comment]
> This may help checking if smoothscroll polyfill is affecting anything.

I tried to remove that package completely and all of its references but it did not help.

**Comment by a-kriya** [comment]
>I mean I have nested divs in the wrapping div#app but no, in the end it is one specific div that is causing the y-axis to overflow.

Overflow the page or just `#app`? Do you have any `overflow` CSS props on any container elements? It may be easier to tell that in Firefox DevTools as it tags the elements with `scroll`:

<img src="https://user-images.githubusercontent.com/26761352/80918425-74057100-8d82-11ea-8ac3-78acd3e0b5f5.png" height="200" />

**Comment by oskery** [comment]
Nice suggestions! I have not disabled y-scroll anywhere in my css, in Firefox DevTools only #app has this scroll icon next to it, so that differs from what you are displaying. If I add `html { overflow-y: scroll; }` to my css I get a scroll icon next to the html tag as in your image, but still no logging. I tried to register the listener in firefox console too but no logging, just as chrome.

![Screenshot from 2020-05-03 17-44-54](https://user-images.githubusercontent.com/28003429/80918539-d308bd00-8d65-11ea-85ad-bc0a81176e62.png)

**Comment by a-kriya** [comment]
Oh, I just took that screenshot while inspecting stackoverflow page as an example, so ignore the differences. Can you remove all the CSS that's applied to #app element? It looks like it has an overflow property, so just uncheck/deselect it in the DevTools.

**Comment by oskery** [comment]
Hey, that was the problem! :D As you said I had scroll styling on #app for some reason, not sure why I added that. Removing the below row from #app-style fixed the issue:
`overflow-y: scroll;`

**Comment by oskery** [comment]
I will add that I don't really understand why this happens, but I am glad that I can resolve the issue :exploding_head:

**Comment by a-kriya** [comment]
Alright, sweet! Does that allow you to attach scroll listener on window in Template.vue as well? If so, I suppose this ticket is solved : ]

**Comment by oskery** [comment]
> Alright, sweet! Does that allow you to attach scroll listener on window in Template.vue as well? If so, I suppose this ticket is solved : ]

Yes, that was the first thing I tried. Thank you so much for the support! :pray:

**Comment by a-kriya** [comment]
No problem. I'll create a simple fiddle to test out scroll event bubbling since I have some doubts on it as well, and share here in a bit.

**Comment by oskery** [comment]
So I investigated a bit further. The problem with my code was this:
```
html {
}

#app {
  overflow-y:scroll;
  overflow-x: hidden;
  width: 100vw;
  height: 100vh;
}
```
This resulted in that the html did not cover the whole page while #app did. If I move the code to the html styling it works much better:
```
html {
  overflow-y:scroll;
  overflow-x: hidden;
  width: 100vw;
  height: 100vh;
}

#app {
}
```

**Comment by a-kriya** [comment]
I see. By the way, you may want to set `overflow-y` to `auto` in case you don't want vertical scrollbar when there's content that does not cover the viewport height.

Here's a quick test, and as we noticed here, scroll events are _not_ bubbled up to the document: https://jsfiddle.net/k36bmo0t/

**Comment by oskery** [comment]
> Here's a quick test, and as we noticed here, scroll events are not bubbled up to the document

Guess that make sense, as you say it would be very costly otherwise.

> you may want to set overflow-y to auto

Yeah I removed it altogether, corrected my comment.

**Comment by oskery** [comment]
> By the way, you may want to set overflow-y to auto in case you don't want vertical scrollbar when there's content that does not cover the viewport height.

Actually I just remembered that is exactly what I want, since otherwise the layout will jump whenever the vertical scrollbar appears.
