### ISSUE TITLE
404 Error with Dynamic Routing

### ISSUE THREAD

**Issue by CodingCarter** [gridsome/gridsome#1145]
## Description

When you reload or go to the page's url specifically that is using dynamic routing, you get a 404 error.  However, when you start from the home page and click a link that takes you to the **same exact url**, the website works fine without errors!

### Steps to reproduce

Go to https://codingcarter.netlify.app/ and click the "courses" button on the top right.  Next, click on the first course page.  Then reload the page and VOILA, it stops working.  Try to go to a different page using the links and the page url changes, but no visual changes occur.  Look at the console to see the errors.  I litterally copied and pasted the code from the gridsome docs on dynamic routing, but it still won't work.

### Expected result

The page should show the same content as before you refreshed.  From looking at other errors, I think it has something to do with data that is available when you launch the website from a different page isn't available on a different page.

### Actual result

The page shows 404 error and there is errors in the console.

### Environment

    "gridsome": "^0.7.0",
    "node-sass": "^4.14.0",
    "sass-loader": "^8.0.2",
    "style-resources-loader": "^1.3.3"

**Comment by CodingCarter** [comment]
Well, I found a very odd fix to the problem.  If you place in some raw text above all of my v-if and v-for statements, the page will not return 404 even after refreshing.  I applied this by making the height of the text 0 while wrapping it in a span tag, and it worked.  I don't know why....I don't know how.....but whatever.  If you can add an actual solution and reason for this, please comment!

**Comment by qntndev** [comment]
Hey @CodingCarter 

You need to handle it server side, it's not a gridsome related issue.

_________________________________________________________________________________

Create a file in your dist directory - `netlify.toml`
and put this code in the file
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

```
commit and push to your git repo

_Originally posted by @siddhartharora02 in https://github.com/vuejs/vuepress/issues/457#issuecomment-463745656_

**Comment by asefcamel** [comment]
@qntndev now it's showing a blank page, it will not load the data 😫

**Comment by F0rsaken** [comment]
We managed to solve this problem, with specific redirects per dynamic route via server. Here is a tutorial we found:

https://shouts.dev/gridsome-rewrite-rules-for-dynamic-routes-after-build

**Comment by cameronrr** [comment]
@F0rsaken depending on your setup, you might be able to achieve this programmatically, without needing to manually maintain the redirects file as the project changes.

Source: https://gridsome.org/docs/dynamic-routing/#generating-rewrite-rules

Example for Netlify. The generated _redirects file can co-exist with a netlify.toml for other settings.

```javascript
//gridsome.server.js

const fs = require('fs')

module.exports = function (api) {

  // ... some dynamic pages using the Pages API i.e. api.createManagedPages() or api.createPages()

  api.afterBuild(({ redirects }) => {
    if (redirects) {
      let rules = []
      for (const rule of redirects) {
        rules.push(`${rule.from}\t${rule.to}\t${rule.status}`)
      }
      fs.appendFileSync('./dist/_redirects', rules.join('\n'))
    }
  }) 
}
```
