### ISSUE TITLE
Importing component in gridsome from other folder gives error in console

### ISSUE THREAD

**Issue by jd-0001** [gridsome/gridsome#1146]
## Description

Hi, I am using bootstrap-vue for my project and for docs I am using gridsome. I want to show some components I made in gridsome docs & one of them uses bs-collapse component. When I import my custom component from outside of gridsome package folder it throws error but when I paste same component in gridsome package folder and toggle collpase it works fine. IDK why :thinking: 

### Steps to reproduce

1. Clone repo: [Visit](https://github.com/jd-0001/issue-gridsome-bs-collpase)
2. Follow steps
3. See error

### Expected result

I think it should work no matter from where I import my component

### Actual result

It throws error if I import component from outside of gridsome package.

### Environment

```
  System:
    OS: Linux 5.6 Linux Mint 19.3 (Tricia)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
  npmPackages:
    @gridsome/vue-remark: ^0.2.0 => 0.2.0 
    gridsome: ^0.7.0 => 0.7.14
```

**Comment by Sergix** [comment]
I wouldn't recommend important any component from outside your project's directory or installed `node_modules`. Can you share the specific error message you're receiving?

**Comment by jd-0001** [comment]
Hi @Sergix I have already uploaded GIF demonstrating the issue:
https://github.com/jd-0001/issue-gridsome-bs-collpase/blob/master/grdisome-bs-collapse-import-issue.gif

**Comment by Sergix** [comment]
Yes, I see the GIF, but it's too small to read the error message. Can you paste the specific error message here?

**Comment by jd-0001** [comment]
Hi @Sergix Here's I made video:
https://drive.google.com/file/d/1YzqGOmRezshq9Rhr4xms01X4YzMZj0NG/view?usp=sharing

Demo page URL is: localhost:8000/docs

**Comment by jd-0001** [comment]
I moved to VuePress so closing this.
