### ISSUE TITLE
Medium Zoom stops working if I refresh the page within vue remark content, But works everywhere else

### ISSUE THREAD

**Issue by ramsane** [gridsome/gridsome#1149]
## Description

I am trying to use medium zoom in my project with vue remark. Medium zoom works perfectly for any g-image's in any component.

When I try to use that in the markdown. It works if it is rebuilding the component. But when I refresh the page, zoom stops working.

I change something in the `Article.vue` to re-render the page. But after refresh the page, it stops working for the images in vueremark content.
changing something like this in my file.

```jsx 
mounted() {
    mediumZoom("img", {
      margin: 40
    });
  }
```

### Environment
``` jsx
   "@gridsome/vue-remark": "^0.2.0",
    "gridsome": "^0.7.0",
    .....
    "medium-zoom": "^1.0.5",
    ....
```

** It is worth mentioning that it works perfectly when used with source filesystem and transformer remark. I checked it. Because we get HTML content from the graphql, so medium zoom is able to capture that image successfully.***

Any help would be appreciated. Been trying to figure it out for 3 days. It might be the problem with how vue remark renders the markdown.

Thanks in advance.

**Comment by CodingCarter** [comment]
Same thing happening for me with dynamic routing!  I tried using gridsome a while back and this same bug happened.  Never figured it out and just quit.  Now, I just built a whole portfolio + blog with gridsome and this bug is KILLING me!  No help on my issue, but if you want to see it go to https://github.com/gridsome/gridsome/issues/1145

**Comment by CodingCarter** [comment]
Well, I found a crappy fix, if you add in the following code into your layout script used for the broken pages it will fix it, kind of.
```
mounted() {
    let currentURL = window.location.pathname;
    // console.log(currentURL);
    setInterval(function() {
      if (currentURL !== window.location.pathname) {
        location.reload();
      }
    }, 250);
  }
```

**Comment by amxmln** [comment]
Could it be because the child-component, i.e. the content-outlet for the rendered Markdown, hasn’t
loaded yet when `mounted()` is called? Have you tried wrapping your call to `medium-zoom` in a
`this.$nextTick()`?

**Comment by ramsane** [comment]
@amxmln Thanks for the Idea. Even though it didn't work. It pushed me in the right direction. To cut it short, you need to put that in both `mounted()` and `updated()`. It just works.

When I register the medium zoom in `updated()`, it won't work for when we come from any other page to the current page. In order to work, you need to refresh it. And it is clearly opposit for if we register zoom in `mounted()`. ie., it works if we come from a different page. But it doesn't work if we refresh the page. 

To solve this, I just put that in both places
```jsx
.....

mounted() {
    // when we revisit the page, we need to register it
    mediumZoom("img");
  },
  updated() {
    // register everytime we refresh the page..
    mediumZoom("img");

....
  }
```

For the images outside of the Vueremark content, it works regardless.

I think the reason is similar to what @amxmln mentioned. The Vue remark content is not available. transformer remark stores HTML in the Graphql and therefore no issue. And I think Vue remark is a component that renders a Json. Maybe this is the reason for the odd behaviour. 

Anyway, thanks once again @amxmln. Couldn't have done without you.
