### ISSUE TITLE
Is it possible to have some pages VUE reactive?

### ISSUE THREAD

**Issue by ckissi** [gridsome/gridsome#1152]
## Summary

I want to generate my site in Gridsome but need some pages to have Vue reactivity (like classic Vue page).

Let's say I want to add a simple Vue calculator component to some page that should work.

**Comment by qntndev** [comment]
Hey @ckissi , it's already the case. Gridsome is a Vue app under the hood. 
So you can use vue components magic on client after your site has been build by Gridsome.
