### ISSUE TITLE
Deprecate api.store and store.adContentType()

### ISSUE THREAD

**Issue by thiti-y** [gridsome/gridsome#1153]
## Description

When i run develop it show warning follow below image.

![2020-05-07_23-48-38](https://user-images.githubusercontent.com/7018802/81322895-cd410d80-90be-11ea-94f1-6a46d5ccbb67.png)

**Comment by hjvedvik** [comment]
Can you try the latest version of `@gridsome/source-filesystem` and see if it helps?

**Comment by thiti-y** [comment]
I update @gridsome/source-filesystem to last version solve for me

Thank you :]
