### ISSUE TITLE
addSchemaTypes documentation omits the id field

### ISSUE THREAD

**Issue by iam-jam** [gridsome/gridsome#1155]
## Summary

`addSchemaTypes` documentation omits the `id` field.

Taking the following example from the [docs](https://gridsome.org/docs/schema-api/#addschematypestypes):

```
api.loadSource(({ addSchemaTypes }) => {
  addSchemaTypes(`
    type Post implements Node {
      title: String
    }
  `)
})
```

You will get something like:

`Error: Interface field Node.id expected but Menu does not provide it.

The docs should be updated like so:

```
api.loadSource(({ addSchemaTypes }) => {
  addSchemaTypes(`
    type Post implements Node {
      id: ID!
      title: String
    }
  `)
})

**Comment by noxify** [comment]
@iam-jam - could you create a PR with the changes at https://github.com/gridsome/gridsome.org ?

**Comment by iam-jam** [comment]
@noxify 
https://github.com/gridsome/gridsome.org/pull/422
I'll open issues for docs in the gridsome.org repo next time :)

**Comment by noxify** [comment]
PR https://github.com/gridsome/gridsome.org/pull/422 is merged.
I close this issue.
