### ISSUE TITLE
Gridsome compare with JAMstack frameworks

### ISSUE THREAD

**Issue by Maxhodges** [gridsome/gridsome#1156]
I know Gridsome was inspired by Gatsby, but how feature complete are you now? Does Gridsome support same capabilities with regard to the JAMstack paradigm?

I'd like to know how it compares along these lines:
https://www.gatsbyjs.org/features/jamstack/

specifically we're interested created a pre-rendered on build, **rich, dynamic full-featured app**

![image](https://user-images.githubusercontent.com/957271/81426360-0b5c3100-9194-11ea-8108-9b2ea50f91cf.png)

**Comment by tomtev** [comment]
Yes, Gridsome does support the exact same features for building JAMstack websites. IMO this is more about Static VS Server-side rendering. If you go the static route you need to use serverless APIs to update your front-end on the client-side. Gridsome can, for example, have dynamic routes on Netlify: https://gridsome.org/docs/dynamic-routing/

**Comment by Maxhodges** [comment]
Thanks. You are you aware of any project that are taking this approach with Gridsome? We've built multiple static sites, and multiple SPA type applications. We are interested in the static + dynamic data techniques, but we've been unable to find a single demo or even one article which talks about this this detail for Gridsome. It appears as if everyone is only using Gridsome as a static site generator. We wonder why there aren't more (any) example projects or articles of the JAMstack approach (calling apis post-build).

**Comment by nawalnew** [comment]
@Maxhodges 
Ive seen a lot of Tutorials for using it with API driven content and made it work by myself with Strapi CMS. 

You just need Axios and Dynamic routes. Ive just tested it little bit. 

But also any Headless CMS Tutorials are with api based content. 

The obly thing you than need, are dynamic routes from the post above. 

Let me know if you still have questions.

**Comment by serebrov** [comment]
@Maxhodges As I understand from the discussion in #193, you have found a way to use gridsome to build a dynamic application.

Could you share your experience? I am trying to find more information about the flow for authenticated users and in-app pages:
- Public web site pages are generated statically
- There is a login / signup area for users registration to access "in-app" pages
- All "in-app" pages should be protected (only available after registration)
- Most of "in-app" pages can be statically rendered too with user-specific content fetched dynamically and layered on top of static pages
- Some of "in-app" pages are built dynamically (like user profile page)

For example, imagine a news website where part of the content is public and part is available after registration. Registered users also can mark content as read, unread, favorite, add highlights, and notes.

[Dynamic routing](https://gridsome.org/docs/dynamic-routing/) looks like base a solution for the in-app pages flow, but the documentation page is quite short, so I am trying to find more information on the topic.

For example, gatsby has much more information on this topic, in particular [client-side only routes guide](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/), [building a web-site with authentication](https://www.gatsbyjs.org/docs/building-a-site-with-authentication/), [authentication tutorial](https://www.gatsbyjs.org/tutorial/authentication-tutorial/).

**Comment by Maxhodges** [comment]
hi @serebrov my current thinking thinking is that JAMstack is not a very viable way to build modern web applications. We're big fans of static sites and Gridsome, but when it comes to full-featured applications, the JAMstack approach doesn't hold up well. I see it as mostly a marketing ploy (lead by Netlify) without much substance to back it up.

After much research and efforts, I'm come to agree with this take away:

>There’s still a place for static sites on the web, but it’s shrinking, not growing, and likely still the domain of developer portfolios and side-projects. Sure, it’s possible to engineer a workflow in 2020 that manages to smoosh together a set of disparate 3rd parties, a version-control-system backed CMS and a bunch of template files into a working (and fast!) site, but the value is questionable. Instead of reducing complexity, the JAMStack just shifts it around.

>Security and performance are real concerns and will undoubtedly continue to plague developers, library authors and product owners as long as software development lives, however, the solution won’t be found in a reduction of responsibility.

>It’s fitting that we have taken the simplest form of a website — static HTML — and transformed it into a complex landscape of build processes, tooling and services that more than rivals the complexity it set out to supplant.

https://www.browserlondon.com/blog/2020/04/20/issues-with-jamstack-you-might-need-backend/

We still use Gridsome for landing pages, but we're building our app in Vue, Apollo, GraphQL, Hasura.
