### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by iam-jam** [gridsome/gridsome#1157]
## Summary
Breadcrumb support would be really helpful. As a minimum Gridsome could provide the hierarchical data needed for developers to use with their own breadcrumb components but Gridsome could also provide a component for out of the box support.

**Comment by tomtev** [comment]
A built-in breadcrumb component is a really good idea!

**Comment by tomtev** [comment]
I'm closing this now, but we have added it to feature request list :)

**Comment by iam-jam** [comment]
Hi @tomtev I'd really like to contribute to the development of this feature if possible - I've been exploring the options a little on a project I'm working on at the moment - what would be the best way for me to get involved?
