### ISSUE TITLE
CJK support for variable: timeToRead

### ISSUE THREAD

**Issue by spencerwooo** [gridsome/gridsome#1159]
## Summary

> Brief explanation of the feature.

Currently Gridsome exposes a `timeToRead` query element for `Posts`. I find that this variable doesn't work well with articles consisting of CJK characters. I suggest utilizing word count libraries that support CJK characters. (For instance: [word-count](https://github.com/yuehu/word-count))

### Basic example

> Include a basic example or links here.

Considering Gridsome's default read speed, which is 230 words per min:

- [An article entirely written in English](https://blog.spencerwoo.com/2020/02/stdout-overhead/) have an estimated reading time of 6 min, which approximates to ~1380 words, falling close to what Typora calculates:

	![image](https://user-images.githubusercontent.com/32114380/81479518-53438c80-9256-11ea-88fb-1ab46c9296da.png)

- However, the estimated reading time of [an article consisting a mix of English and Chinese](https://blog.spencerwoo.com/2020/05/debugging-netlify-static-site/) is 3 min, ~690 words, which is nowhere near Typora's calculation of 2850 words:

	![image](https://user-images.githubusercontent.com/32114380/81479694-61de7380-9257-11ea-80e0-5bf98fa1b80c.png)

### Motivation

> Why are we doing this? What use cases does it support? What is the expected outcome?

I first tried to add this feature on my own by adding two custom nodes `cjkWordCount` and `cjkReadTime` to the `Posts` collection using the Data Store API. I'm not that familiar with GraphQL so I didn't succeed. I **was** able to use the `word-count` library and count words by stripping HTML tags given by `post.content`, but I thought that this wasn't quite elegant and I also wasn't able to pass this value to pages other than inner blog posts. I think it would be best if something like this were implemented on the server side of Gridsome and passed through the GraphQL interface.

**Comment by spencerwooo** [comment]
I think this should be fairly easy to implement inside [@gridsome/transformer-remark](https://github.com/gridsome/gridsome/blob/master/packages/transformer-remark/index.js), I'm more than happy to make a PR and implement this feature. 😆

**Comment by tomtev** [comment]
@spencerwooo Go for it 😉
