### ISSUE TITLE
Impossible to use array of images within content type

### ISSUE THREAD

**Issue by cyberbobs** [gridsome/gridsome#117]
## Description

It is [described in docs](https://gridsome.org/docs/images#insert-images-via-graphql-query) that images for using with g-image can be added with frontmatter in Markdown documents transformed by remark transformer. It doesn't work the same way for image arrays.

### Steps to reproduce

1. Create Markdown file and add some images with frontmatter:
```markdown
---
cover: ./1.jpg
images:
  - ./1.jpg
  - ./2.jpg
  - ./3.jpg
---
...
```

2. Add remark transformer and filesystem source to `gridsome.config.js`.

3. Add basic template showing your newly created content type.

I've made a small demo app for it: [demo](https://5c3727163066900b78016ec4--gridsome-image-array-test.netlify.com/portfolio/test), [source](https://github.com/cyberbobs/gridsome-image-array-test)

### Expected result

Images mentioned in `images` field in Markdown must be imported as images and rendered with g-image.

### Actual result

Images are imported as absolute local filepaths.

**Comment by hjvedvik** [comment]
You're right! Will fix that in the next release.

**Comment by cyberbobs** [comment]
Thank you. Temporary workaround for anyone stuck with it like me: list of objects containing image in a field works just fine: 

```markdown
---
cover: ./1.jpg
samples:
- image: ./1.jpg
  title: Cat number one
- image: ./2.jpg
  title: Cat number two
- image: ./3.jpg
  title: Cat number three
---
...
```

You could also select images in several different resolutions:
```graphql
query { 
  allPortfolio {
    totalCount
    edges {
      node {
        path
        title
        cover (width: 500, height: 500, quality: 80, fit: cover)
        samples {
          preview: image (width: 500, height: 500, fit: cover)
          image (width: 1280, quality: 80)
          title
        }
        content
      }
    }
  }
}
```

**Comment by SimeonGriggs** [comment]
> You're right! Will fix that in the next release.

...was this fixed? Still having this exact issue.

**Comment by u12206050** [comment]
Same here, but workaround mentioned by @cyberbobs does work however would be nice that it works out of the box.
