### ISSUE TITLE
Gridsome GraphQL doesn't infer image field properly

### ISSUE THREAD

**Issue by amitash** [gridsome/gridsome#1171]
## Description

A source plugin `gridsome-source-firestore` downloads my external images and creates nodes with absolute paths as a string. I have two such fields "gallery" and "content". Gridsome processes the paths in the gallery field and converts it into the image type. However, the content field remain unprocessed and continue to be strings (path) instead of being processed into an image object. 

```
query {
  allFireStories {
    edges {
      node {
        gallery {
          imageRef (has full image features src, width etc)
        }
        content {
          imageRef (is only a string of the absolute path of the image, not processed)
        }
      }
    }
  }
}
```
The reason I think this happens is because in my CMS, content image is optional and in some cases can be empty. So gridsome might be inferring its schema as string based on the empty fields and skipping processing the field as image even if content is available in this field in other cases.

### Environment
```
System:
OS: Windows 10 10.0.18363
CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Binaries:
Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 44.18362.449.0
npmPackages:
gridsome: ^0.7.0 => 0.7.14
gridsome-source-firestore: https://github.com/amitash/gridsome-source-firestore => 1.2.0
```

**Comment by iam-jam** [comment]
@amitash you can define the types of your graphql fields using `addSchemaTypes` 
https://gridsome.org/docs/schema-api/#addschematypestypes

**Comment by amitash** [comment]
> @amitash you can define the types of your graphql fields using `addSchemaTypes`
> https://gridsome.org/docs/schema-api/#addschematypestypes

@iam-jam I tried to do that and added the type to be an Image but imageRef becomes null after rebuilding.

**Comment by amitash** [comment]
This is what I have tried and then the imageRef becomes null.

```
api.loadSource(({ addSchemaTypes }) => {
 addSchemaTypes(`
   type FireStories implements Node @infer {
     content: StoryContent
   }
   type StoryContent {
     heading: String
     imageRef: Image 

   }
 `)
})
```

**Comment by iam-jam** [comment]
@amitash I think you'll need to implement `Node` on your `StoryContent` type too. 

```
type StoryContent  implements Node {
     heading: String
     imageRef: Image
}
```

**Comment by amitash** [comment]
@iam-jam thanks for your help but `StoryContent` is not a collection. Its a field with sub fields. Anyway, when I try to implement `Node`, I get an error:

`Error: Type StoryContent does not have resolver with name 'referenceOne'`

```
api.loadSource(({ addSchemaTypes }) => {
 addSchemaTypes(`
   type FireStories implements Node @infer {
     content: StoryContent
   }
   type StoryContent implements Node {
     heading: String // all data becomes null
     imageRef: Image // also becomes null but Type successfully changed to Image

   }
 `)
})
```

**Comment by amitash** [comment]
Data still null
```
    addSchemaResolvers({
      StoryContent: {
        imageRef(obj, args, context, info) {
          return obj.imageRef;
        },
      },
    });
```

**Comment by iam-jam** [comment]
@amitash you either need to use `addSchemaResolvers` ([docs](https://gridsome.org/docs/schema-api/#addschemaresolversresolvers)) or define your type using the factory methods, e.g. 

```
addSchemaResolvers({
  YourType: {
    yourField: {
      type: 'String',
      resolve: (obj) => obj.yourField
    }
  }
})
```

**Comment by iam-jam** [comment]
Sorry, ignore that example. Should have been:

```
schema.createObjectType({
        name: 'YourType
        interfaces: ['Node'],
        fields: {
          id: 'ID!',
          yourField: {
            type: 'String',
            resolve: (obj) => obj.yourField
          }
        }
```

**Comment by iam-jam** [comment]
@amitash `console.log` `obj` in your resolver to see what's available. Also, Github issues isn't really the best place for this sort of support. You may better off asking for help on Discord:

https://discord.gg/zagyPD

**Comment by amitash** [comment]
> @amitash Github issues isn't really the best place for this sort of support. You may better off asking for help on Discord

Agreed @iam-jam Thank you!

**Comment by amitash** [comment]
I finally fixed this. It was a mistake on my side. Type `StoryContent` should have been `[StoryContent]` as it is an array. No need to `addSchemaResolvers`.

```
    addSchemaTypes(`
      type FireStories implements Node @infer {
        content: [StoryContent]! // this here
      }
      type StoryContent {
        heading: String
        imageRef: Image
      }
    `);
```
