### ISSUE TITLE
vue-remark - .md include feature

### ISSUE THREAD

**Issue by rickbsgu** [gridsome/gridsome#1177]
## Summary

Allow .mds to include other .mds

### Basic example

include '/somedir/prefix.md'

Some content...

### Motivation

I've created a set of components to get the page to look how I want - some 8 and counting.  Vue-remark, is working great.

However, I have to preface every article/blog page with the list of components I want to define.

It would be nice if there was an 'include' feature - beyond my immediate needs, it would be useful to to build up documents from fragments.

### Caveats

I don't know - this might be a more of a 'remark' thing.  I looked through the list of remark plugins and nothing jumped out at me.

**Comment by philoozushi** [comment]
According to the doc, you can do that already.

```markdown
// Import any Vue Component. Even other .md files!
import AboutUs from '~/sections/AboutUs.md'
<AboutUs />
```

cf. https://gridsome.org/plugins/@gridsome/vue-remark

**Comment by rickbsgu** [comment]
Yeah, I tried that.  That's an import, not an include.

I'm not exactly sure what that means - in a vue component (or javascript object) that yields whatever the component exports.  If you import an md file, what is the result?  I'm a bit fuzzy on that.

Thanks for any illumination.

**Comment by philoozushi** [comment]
Oh, I think I understand better what you're trying to achieve.
I wanted to do something similar having 10+ components, but I don't think it's the right approach to import every components in each file. If we end up with a lot of Markdown files, refactoring could become hell...

I ended up doing that in my Vue template :

```html
<script>
import Component1 from '~/components/Component1.vue'
import Component2 from '~/components/Component2.vue'
Vue.component('Component1', Component1)
Vue.component('Component2', Component2)
</script>

<template>
  <vue-remark-content />
</template>

<page-query>
...
</page-query>
```

That way, no need to the components import in the Markdown files, and if I need to refactor my components or change their path or name, no problems.

**Comment by rickbsgu** [comment]
Ah!  I had tried importing the components in the template page and then listing them in the 'components:' part of the export, but that didnt work.

Actually, I realized I could just do this approach in the main.js, and then the components would be available everywhere.

Thanks for the response.

**Comment by philoozushi** [comment]
Yes, registering Vue components in the main.js works as well, with the difference that they will be included in the main bundle at the 1st load time. If you register them in a template file however, Gridsome is supposed to do some code splitting and load them only when a template page is required.
Glad it works for you too anyways.
