### ISSUE TITLE
g-image ignores exif rotation

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#1178]
Sometimes JPEG images specify a rotation with an EXIF tag.  `g-image` ignores this and generates an image without the rotation information.

gridsome=0.7.14

**Comment by hjvedvik** [comment]
That's the default behavior for `Sharp` and the `imagemin` packages which Gridsome use to process images. But we can add a `images.stripMetadata` (default: `true`) config to include it in the final image.

**Comment by hjvedvik** [comment]
Another solution, which might be better, would be to rotate the image when processing it, based on the EXIF rotation. Then remove the EXIF metadata. I've tested it on a few images and it seems to work well. I just have to do some more tests.
