### ISSUE TITLE
Image added via GraphQL query ignores width and height attributes

### ISSUE THREAD

**Issue by cyberbobs** [gridsome/gridsome#118]
## Description

It is [described in docs](https://gridsome.org/docs/images#insert-images-via-graphql-query) that images for using with g-image can be added with frontmatter in Markdown documents transformed by remark transformer. When we try to render image added this way using g-image, it ignores `width` and `height` attributes.

### Steps to reproduce

1. Create Markdown file and add some images with frontmatter:
```markdown
---
cover: ./1.jpg
images:
  - ./1.jpg
  - ./2.jpg
  - ./3.jpg
---
...
```

2. Add remark transformer and filesystem source to `gridsome.config.js`.

3. Add basic template showing your newly created content type.

I've made a small demo app for it: [demo](https://5c3727163066900b78016ec4--gridsome-image-array-test.netlify.com/portfolio/test), [source](https://github.com/cyberbobs/gridsome-image-array-test)

### Expected result

Cover image is rendered in 500×500 square container

### Actual result

Image is rendered in full size ignoring g-image component attributes.

**Comment by hjvedvik** [comment]
You have to set width and height in the GraphQL query like this `cover (width: 500, height: 500)`. The width and height attributes only work when referencing a file. We should probably make this more clear in the docs :)
