### ISSUE TITLE
Question: Best approach for versioning docs

### ISSUE THREAD

**Issue by jd-0001** [gridsome/gridsome#1183]
## Summary

I am currently contributing to open source project and redesigning docs completely. For this I decided to use gridsome. I have created some pages but versioning is the thing I am stuck at.

### Basic example

I have docs in `content/docs/v1.0` and md files in there. If I will create another version of app then I will add v2.0 in `content/docs` folder along with.

My URL is `domain/docs/<v1.0>/introduction`

Also I am using `@gridsome/vue-remark`

**Other:** Other than docs I will also have API versioning endpoint for the same reason.

Regards ~

**Comment by Sergix** [comment]
Hey @jd-0001,

For versioning anything, use `git` to track your changes, and I recommend following the [semantic versioning specification](https://semver.org/) to identify and number your versions.

**Comment by jd-0001** [comment]
Hi @Sergix Thanks for response. I am already git for my code versioning. But I am asking for displaying docs of different version in my frontend.

Like in gridsome in right-top corner we have version, right? I also want to show docs of older versions also just like bootstrap.

So, what is best approach for it.

**Comment by jd-0001** [comment]
Closing this. I switched to VuePress.

**Comment by andrewrynhard** [comment]
@jd-0001 Same issue here. I don't see documentation on how VuePress solves this. Mind pointing me in the right direction? @Sergix I would love to use gridsome, but this is a blocker for me. Any idea on how I might get this working?

**Comment by jd-0001** [comment]
@andrewrynhard for me VuePress is much simpler and quicker to get up and running so I moved there. Certainly, if you have more complex requirements then you need to use the awesomeness of gridsome.

Best of luck.
