### ISSUE TITLE
vue-remark remark plugin to preprocess frontmatter data

### ISSUE THREAD

**Issue by philoozushi** [gridsome/gridsome#1185]
Hi there,
Thanks for the Gridsome project & vue-remark plugin, I'm enjoying it so far!

Now, I'm trying to preprocess the frontmatter data of my Markdown files before that data reach the GraphQL layer. Are any remark plugin supposed to work?
The plugins modifying the markdown / mdast work perfectly.
However, my plugin trying to modify the frontmatter data doesn't.
How can one achieve that?

---
More info :

Remark plugins receive 2 params :
- `tree` the [mdast](https://github.com/syntax-tree/mdast) tree
- `file` the [vfile](https://github.com/vfile/vfile)

vue-remark seem to remove the frontmatter node and store 3 things in the `file.data` :
- `data` the frontmatter data
- `layout` the layout component infos
- `resourcePath` the Markdown path

doing that before reaching plugins.

I tried to change the `file.data.data` directly in my plugin, also a stupid thing as adding a new frontmatter node, but nothing works.

Can someone tell more about the vue-remark architecture and how to preprocess frontmatter data before it reaches the GraphQL layer?
Thanks a lot.

**Comment by philoozushi** [comment]
In that issue https://github.com/gridsome/gridsome/issues/707#issuecomment-535996112, someone pointed out :
> It appears that markdown is being processed first, and then the remark plugins are running after the fact.

So maybe a better place to preprocess Markdown frontmatter data is in the `gridsome.server.js` eventually. With the Data Store API and manually using remark at that moment.

If so, it may be worth noting that in the documentation to save some time to other users :)

**Comment by Sergix** [comment]
https://github.com/gridsome/gridsome.org/pull/448

**Comment by gimyboya** [comment]
can we have a more practical example please. I still didn't figure out how to add the frontmatter data to the Graphql layer

**Comment by songololo** [comment]
This caught me out as well. Would it make sense to add this comment directly to the `vue-remark` docs as well? (I didn't think to look in the server-api docs...)
