### ISSUE TITLE
Markdown whitespace being ignored

### ISSUE THREAD

**Issue by mattbrailsford** [gridsome/gridsome#1186]
## Description

I have some markdown which has a link directly next to a bold string with a space between

    **Some bold text** [a link](https://gridsome.com)

However when this is rendered on the front end, the space between the bold tag and the link is removed and the text touches. It seems gridsome is ignoring whitespace somewhere.

### Expected result

I expect the space to be kept

### Actual result

Space is lost

**Comment by a-kriya** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/26761352/82909318-be939b00-9f86-11ea-935b-b5d1b104a88b.png)

Can you please share a reproduction?

**Comment by webmasterowi** [comment]
@mattbrailsford are you using tailwind css?

**Comment by mattbrailsford** [comment]
@webmasterowi i am yea

**Comment by webmasterowi** [comment]
@mattbrailsford You need to add style to the html that is generated by markdown, usually you can do it by creating a class call markdown and inside add style to the elements that you need like in here: [Gridsome Starter](https://github.com/cossssmin/gridsome-starter-bleda/blob/master/src/assets/css/components/markdown.css). After that, you will need import that  in the same file where you are importing tailwind [Main.css](https://github.com/cossssmin/gridsome-starter-bleda/blob/master/src/assets/css/main.css)
Then add the chainWebPack with the required plugins like this: [Plugins](https://github.com/cossssmin/gridsome-starter-bleda/blob/2884883c9d268aae7bbd7e7c83a8fca7b10d69f0/gridsome.config.js#L80)
I hope that helps.

**Comment by Sergix** [comment]
Add something like this to your CSS (using Tailwind):

```css
strong {
  @apply mr-2;
}
```
