### ISSUE TITLE
JavaScript heap out of memory generating 1200 pages

### ISSUE THREAD

**Issue by mattbrailsford** [gridsome/gridsome#1192]
## Description

I'm creating a documentation site for a project and have recently setup a generator to generate reference docs for the associated code library. This generates just over 1000 pages of ref docs. When testing locally with `gridsome develop` it all works fine, just taking a little while to generate, but when I or Netlify try to build the project, I just get an exception.

````
==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF71353463D]
Security context: 0x00ebc6fc08a1 <JSObject>
    1: fnModule(aka fnModule) [000000CEE1F2CBC9] [C:\PATH_TO_PROJECT\node_modules\webpack\lib\Stats.js:~510] [pc=00000051C28A6663](this=0x03c8262404a9 <undefined>,0x02056b3b3949 <DependenciesBlock map = 000003D6EDCD9AC1>)
    2: /* anonymous */(aka /* anonymous */) [000000CEE1F2CC01] [C:\Users\Sto...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200526.104731.49488.0.001.json
Node.js report completed
 1: 00007FF71296232F napi_wrap+124543
 2: 00007FF7129036A6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+34502
 3: 00007FF712904366 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+37766
 4: 00007FF713108C5E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF7130F0CA1 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF712FBE56C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF712FC9910 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF712FC6444 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF712FBBCD3 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF712FBA4A4 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2356
11: 00007FF712FDB775 public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType) __ptr64+53
12: 00007FF712D478D7 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __ptr64+3687
13: 00007FF71353463D public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+567949
14: 00000051C28A6663
````

I've seen a couple of issues around this, with potential workaround being to use dynamic routes, but because these are reference docs, each page has a unique URL and so I'm unable to use a dynamic URL in this way.

Is there anything I can do to get this working? My site is currently unbuildable as it stands.

### Steps to reproduce

Create 1000+ .md files and try to build the site.

### Expected result

That the site would get generated, just it might take a little time.

### Actual result

Error as described above.

### Environment

````
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.7 => 0.7.13
````

**Comment by mattbrailsford** [comment]
PS the source code for this project is at https://github.com/vendrhub/vendr-documentation if you need to see the implementation as we do have some unique things going on to populate the GraphQL layer, though not sure if that is related

**Comment by hjvedvik** [comment]
I'm not sure why you get the out of memory error, but I'll do some debugging tomorrow. You can try to use the filesystem plugin with the Remark transformer instead of `vue-remark` for the ref docs (if they don't need to mix Markdown and Vue components). As it won't be so webpack intensive.

**Comment by mattbrailsford** [comment]
Great tip, thanks @hjvedvik

**Comment by hjvedvik** [comment]
Yes, I think it should work. The `vue-remark` plugin has a `ignore` option you can try to ignore the markdown files that the filesystem plugin will process.

**Comment by mattbrailsford** [comment]
Ahh, great stuff, thanks, I'll look into that :+1:

**Comment by mattbrailsford** [comment]
So I was able to split up the reference docs like you said and used some `--max-old-space-size` magic as suggested by a chap on Twitter and I do now have things building, but I'm currently seeing 15 minute build times on netlify.

**Comment by hjvedvik** [comment]
It looks like `vue-remark` still processes the reference docs because they have the same collection type name. So the filesystem plugin and `vue-remark` are adding nodes to the same collection. I did a few changes in your project and was able to get the build time down to 60 seconds. This is basically what I did:

- Rename the filesystem type name to `DocRefPage`.
- Duplicate `DocPage.vue` and change the query to use the `docRefPage` field.
- Use `<div class="markdown" v-html="$page.doc.content" />` on line 4.
- Register the template for `DocRefPage` in `gridsome.config.js`:
```js
templates: {
  DocRefPage: [
    {
      path: node => node.path,
      component: './src/templates/DocRefPage.vue'
    }
  ]
}
```
- And do this in `gridsome.server.js:182`.
```js
const docNodes = getCollection('DocPage').data();
const docRefNodes = getCollection('DocRefPage').data();
[...docNodes, ...docRefNodes].forEach((n, i) => { ...
```

I hope that makes sense. But I'm not very familiar with your site, so I might have missed something.

**Comment by mattbrailsford** [comment]
Oh wow, thank you, that is awesome that you reviewing this. Thank you so much.

Makes total sense and after implementing it did indeed come down massively. 

One last question if I may, should given the filesystem source is using the remark-translater, should the @gridsome/remark-prismjs plugin still work for the filesystem build pages?

**Comment by mattbrailsford** [comment]
Ahh, got it, it looks like my plugins needed to be inside the remark config object. All working now 👍

Thanks again for the awesome support
