### ISSUE TITLE
build failure with package graphql installed for vue-apollo

### ISSUE THREAD

**Issue by violoncelloCH** [gridsome/gridsome#1197]
## Description

I wanted to use `vue-apollo` to send queries to a graphql backend, so I installed it as described in https://apollo.vuejs.org/guide/installation.html#manual-installation . I then noticed that the gridsome build is now failing ẁith 
`Error: You should provide GraphQLDirective to schemaComposer.addDirective(), but recieved: 
  @infer` 
and traced it down to the `graphql` package; the error occurs as soon as this one is installed.

<details>
<summary>build log/error</summary>

```
Initializing plugins...
Load sources - 0s
Error: You should provide GraphQLDirective to schemaComposer.addDirective(), but recieved: 
  @infer
    at SchemaComposer.addDirective (/home/jonas/repos/AfKU/Frontend/node_modules/graphql-compose/lib/SchemaComposer.js:698:13)
    at addExtensionDirectives (/home/jonas/repos/AfKU/Frontend/node_modules/gridsome/lib/graphql/extensions/index.js:44:20)
    at addDirectives (/home/jonas/repos/AfKU/Frontend/node_modules/gridsome/lib/graphql/extensions/index.js:29:3)
    at createSchema (/home/jonas/repos/AfKU/Frontend/node_modules/gridsome/lib/graphql/createSchema.js:49:3)
    at Schema.buildSchema (/home/jonas/repos/AfKU/Frontend/node_modules/gridsome/lib/app/Schema.js:28:28)
    at Plugins.createSchema (/home/jonas/repos/AfKU/Frontend/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AfKU@ build: `gridsome build`
npm ERR! Exit status 1
npm ERR! 
```

</details>

### Steps to reproduce

1. have a gridsome project
2. install the package `graphql` (`npm install --save graphql`) (to use with vue-apollo as described in their documentation)

### Expected result

gridsome should still build without errors

### Actual result

error during build as described above

### Environment

<details>

```
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 14.2.0 - /usr/bin/node
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    gridsome: ^0.7.0 => 0.7.14 
    gridsome-plugin-tailwindcss: ^2.2.48 => 2.2.48 
  npmGlobalPackages:
    @gridsome/cli: 0.3.3
```

</details>

**Comment by thetre97** [comment]
Hey @violoncelloCH ,

You shouldn't need to install graphql, as Gridsome already includes it in it's dependencies. Try removing it, and seeing if the build works.

**Comment by Sergix** [comment]
Hi @violoncelloCH!

@thetre97 is correct. [Gridsome already provides the `graphql` package as a dependency](https://github.com/gridsome/gridsome/blob/master/gridsome/package.json).

Currently, [fetching from an external GraphQL API is not officially documented.](https://gridsome.org/docs/client-side-data/#fetch-from-graphql-api) It's technically possible, but you lose a lot of the advantages of Gridsome by doing dynamic fetching client-side. See https://github.com/gridsome/gridsome/issues/468 for more details.
