### ISSUE TITLE
pagination page-query returns 1 total pages

### ISSUE THREAD

**Issue by eman1986** [gridsome/gridsome#1198]
## Description

if I enter my graphql query into the graphql playground, it shows the correct amount of pages but when used on a page it's only showing up as one page is available.

### Steps to reproduce

create a query that can be paginated, explore it on the graphql playground then add it to a page.

### Expected result

depending on how many items, it should show more than 1 page for both the playground and a page.

### Actual result

just shows totalpages as 1 on a page but correctly on the playground.

### Environment

Paste the information here as shown by `gridsome info`

```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 12.17.0 - /usr/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    @gridsome/plugin-google-analytics: 0.1.1 => 0.1.1 
    @gridsome/plugin-sitemap: 0.3.0 => 0.3.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: 0.6.0 => 0.6.0 
    gridsome: 0.7.15 => 0.7.15 
    gridsome-plugin-remark-prismjs-all: ^0.3.5 => 0.3.5 
    gridsome-plugin-robots-txt: ^1.0.2 => 1.0.2 
```

**Comment by noxify** [comment]
Hi @eman1986 

could you please share your query?

Thanks!

**Comment by eman1986** [comment]
```
query($page: Int) {
    posts: allPost(
        filter: { published: { eq: true } },
        sortBy: "date",
        order: DESC,
        perPage: 4,
        page: $page,
    ) @paginate {
        totalCount
        pageInfo {
            totalPages
            currentPage
        }
        edges {
            node {
                title
                date(format: "MMMM DD, YYYY")
                timeToRead
                description
                path
                tags {
                    id
                    title
                    path
                }
            }
        }
    }
}
```

**Comment by rodrigomata** [comment]
This is happening to me too, it was working fine when I was on version 0.7.0 but then I updated to 0.7.15 and it broke. Literally I changed nothing and it returns `totalPages` with 1

**Comment by noxify** [comment]
Tested it shortly, and I can confirm, the bug exists if you're using `0.7.15`.
With `0.7.14` it was working fine.

@hjvedvik - Any idea how to solve this?

**Comment by hjvedvik** [comment]
@noxify I can take a look at this tomorrow.

**Comment by stikoo** [comment]
Same bug here. If you go to a paginated route i.e, products/2, you get the correct totalPage count and the pagination works. Page 1 link on the Pager component doesn't correctly link to a paginated page though.

**Comment by eman1986** [comment]
@stikoo I've noticed that myself

**Comment by hjvedvik** [comment]
A new version (0.7.16) was just published and should fix this.

**Comment by noxify** [comment]
Hi @hjvedvik 

thanks for the quick fix.

I have tested it shortly and can confirm that the bug is fixed.

@eman1986 - Please test and close the issue if your test were successful :)

**Comment by eman1986** [comment]
I can confirm it's working now
