### ISSUE TITLE
Question: How to implement query of featured / related page 

### ISSUE THREAD

**Issue by ueberf** [gridsome/gridsome#1202]
Hey together,
I'm pretty new to gridsome and vue.js in general, so this might be a basic question, but I'm happy for every comment or suggestion that can point me in a direction.

### Setup
I am building a portfolio website using gridsome together with [forestry.io](https://forestry.io/) as my headless CMS and @gridsome-source-filesystem to compile the markdown files. This setup also works very well so far.

What I want to do is to display a **selection of featured posts** on the front page. Currently I am doing this by filtering my projects like described in the [Gridsome Documentation](https://gridsome.org/docs/filtering-data/).

```
// Current way of showing featured posts
query {
    posts: allPost(filter: {featured: {eq: true}}) {
      edges{
        node {
          id
          path
          title
        }
      }
    }
  }
```

This works so far, but what I would like to have is a **sortable list of posts** so that I can also easily customise their order.

The foresty documentation shows an [example of such a field ](https://forestry.io/docs/settings/fields/select/), which returns the following json structure. My issue is that the according entry in GraphQL is just this array and I don't know how to turn those into usable objects or use them further.
```
// JSON file 
{
  "featured_posts": [
    "src/posts/Project-A.md",
    "src/posts/Project-B.md",
    "src/posts/Project-C.md"
  ],
  "title": "Landing"
}

// GraphQL query output 
"allJson": {
      "edges": [
        {
          "node": {
            "id": "056110feace329a1e94bd19a1bf20ceb",
            "featured_posts": [
               "src/posts/Project-A.md",
               "src/posts/Project-B.md",
               "src/posts/Project-C.md"
            ]
          }
        }
```

### Question
How can I query the featured posts linked in the JSON array on my index page? Is there another way that might be easier?

Thanks so much in advance for any tips!

**Comment by Sergix** [comment]
Do you have a link to your code/repository? I kind of understand what you're asking but I think I need a bit more clarification. 😅

From the Forestry docs page you linked, are you wanting a sortable dropdown of your featured posts?

**Comment by ueberf** [comment]
Thanks for your reply, @Sergix! I think it might be easiest to explain it with [one of the starter templates](https://github.com/itsnwa/gridsome-forestry-starter) from Forestry.

By default this template queries all project posts and displays them on index.vue. So far so good.
```
query Posts {
  projects: allProjectPost {
    edges {
      node {
        id
        date (format: "YYYY")
        title
        categories
        thumbnail (quality: 90)
        path
      }
    }
  }
}
```

I [cloned the repository ](https://github.com/ueberf/gridsome-forestry-starter) and added a [sortable list ](https://forestry.io/docs/settings/fields/sortable-list/) in [.foresty/front_matter/templates/theme-configuration.yml](https://github.com/ueberf/gridsome-forestry-starter/blob/master/.forestry/front_matter/templates/theme-configuration.yml) which let's me select from all available posts
![Forestry Select](https://user-images.githubusercontent.com/19748898/83645115-5f4f0f80-a5b2-11ea-8f3f-2aa4f073fa71.png)


What this outputs is an array with the selected project paths in data/theme.json.
```
"featured_posts": [
    "projects/sunk.md",
    "projects/3d-graff.md"
  ]
```

![Screenshot 2020-06-03 at 16 01 35](https://user-images.githubusercontent.com/19748898/83646250-b1dcfb80-a5b3-11ea-9880-2dacb82ee6d9.png)

This array I import into my Index.vue, but this is where I get stuck. I certainly can query allProjectPost with GraphQL, but how can I query _only those selected posts_ in order to access and show their thumbnail etc?

**Comment by Sergix** [comment]
Ahhh, ok, I see what you're saying.

I've been thinking of how to solve this at build time, but I think the best solution may be to do it client-side rather than directly modify the GraphQL query.

Here's the code I came up with for `Index.vue`:

```vue
// Index.vue

<template>
  <Layout>
    <div class="container">
      <Hero />
      <h1>{{settings.featured_posts}}</h1>

      <ProjectsGrid :projects="featuredPosts" />
    </div>
    <!-- etc -->
  </Layout>
</template>

<page-query>
# same query as in the starter
</page-query>

<script>
// ...
import settings from "../../data/theme.json"

export default {
  // ...
  computed: {
    featuredPosts() {
      const featuredPostsPaths = settings.featured_posts.map(path => `/${path.substring(0, path.length - 3)}/`)
      const featuredProjects = this.$page.projects.edges.filter(({ node: project }) => featuredPosts.includes(project.path))

      return featuredProjects
    }
  },
  data(){
    return{
      settings
    }
  }
}
</script>
```

The computed `featuredPosts` function first modifies the paths to be consistent (in the objects returned by the GraphQL query, the paths look like `/projects/sunk/`) and stores them in `featuredPostsPaths`. Then, the `allProjectPost` object in the page is filtered and finds whatever posts are featured, and then renders them in the `<template>`.

Let me know if this works for you!

**Comment by ueberf** [comment]
Fantastic, thank you so much for your help! 🚀
Your code works great, only that it had to be _featuredPosts**Paths**.includes(project.path)_ instead of _featuredPosts.includes(project.path)_.

The only issue that remained was the ordering of the projects, as I'd like them to appear in the same order as selected in the CMS. I solved this by iterating over the two arrays and push a successful match to a new array, which is then used for displaying the posts.

```
featuredPosts() {
      const featuredPostsPaths = settings.featured_posts.map(path => `/${path.substring(0, path.length - 3)}/`)
      const featuredUnorderedProjects = this.$page.projects.edges.filter(({ node: project }) => featuredPostsPaths.includes(project.path))

      const featuredProjects = [];
      for(let i = 0; i < featuredPostsPaths.length; i++){
        for(let j = 0; j < featuredUnorderedProjects.length; j++){
            if(featuredPostsPaths[i] == featuredUnorderedProjects[j].node.path){
              featuredProjects.push(featuredUnorderedProjects[j])
            }
          }
        }

      return featuredProjects
    }
  }
```

I'm wondering if there would be a more elegant way to do this, but other wise this approach works great for now. 
Thanks again, @Sergix!

**Comment by Sergix** [comment]
Awesome! No problem, glad it works now!
