### ISSUE TITLE
Question: How to load JSON as a separate file that will be added to the output directory.

### ISSUE THREAD

**Issue by Daniel-Novikov** [gridsome/gridsome#1206]
## Summary

How to load JSON as a separate file that will be added to the output directory. (Lottie json file animation)

### Basic example

This is how I add animation atm:
```js
  const animObj = lottie.loadAnimation({
      wrapper: this.$refs.animationRef,
      animType: 'svg',
      loop: true,
      autoplay: true,
      animationData: require('~/assets/animations/animation-hero-home.json')
    })
```

It generates the js bundle with that JSON inside.

The problem with that - if I have 20 animations throughout my static site, my bundle file will be around 20mb (each animation is 200-500kb)

### What I want to do
Ideally I want to use `path` prop, that accept relative path to the file.

```js
  const animObj = lottie.loadAnimation({
      wrapper: this.$refs.animationRef,
      animType: 'svg',
      loop: true,
      autoplay: true,
      path: require('~/assets/animations/animation-hero-home.json')
    })
```

Which will generate .json file inside my output directory, and replace `require` with a path to the file. So It will load the file depending on the page I'm in. (Plus I can gzip on the server separately)

The only resource I've found that address that is here: https://github.com/webpack/webpack/issues/6586

But not sure how to implement that in Gridsome.

Any help would be greatly appreciated.

**Comment by Sergix** [comment]
If you want to add extra webpack configuration to Gridsome's build process, you can use the [`configureWebpack` and `chainWebpack` options](https://gridsome.org/docs/config/#configurewebpack) in `gridsome.config.js`.

You can also [use the server API within `gridsome.server.js`](https://gridsome.org/docs/server-api/#apiconfigurewebpackfn) by adding handlers via `api.configureWebpack(fn)` and `api.chainWebpack(fn)`.

If configuring webpack doesn't work, let me know!

**Comment by Daniel-Novikov** [comment]
Thanks @Sergix.

If anyone needs a solution, resolved like this:

```
  configureWebpack: {
    module: {
      rules: [
        {
          type: 'javascript/auto',
          test: /\.json$/,
          include: [path.resolve(__dirname, 'src/assets/animations')],
          use: [
            {
              loader: 'file-loader'
            }
          ]
        }
      ]
    }
  },
```
