### ISSUE TITLE
vm.$refs

### ISSUE THREAD

**Issue by mamzellejuu** [gridsome/gridsome#1207]
Hi,

I'm trying to see how can we access to the vm.$refs.

https://vuejs.org/v2/api/#vm-refs

is it possible ?

**Comment by Sergix** [comment]
Add the `ref` tag to your element and use `this.$refs` in your page or component to access the referenced element.

For example —

```vue
<template>
  <div ref="myElement">Get the reference of this element</div>
</template>

<script>
export default {
  mounted() {
    const myElement = this.$refs.myElement
    console.log(myElement) // will log your HTML element to the console
  }
}
</script>
```
