### ISSUE TITLE
Question: Google Analytics Plugin doesn't track subsequent page views?

### ISSUE THREAD

**Issue by gitcro** [gridsome/gridsome#1208]
I have installed the Google Analytics plugin as described in the docs. 

When I open a page, a request is sent to GA. But when I follow an internal link on that page, no request is being sent to GA anymore (checked with the network activity monitor in Google Chrome dev tools). What am I doing wrong?

Thx!
Chris

**Comment by Sergix** [comment]
Could this be part of it? [https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/untracked-hits.md](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/untracked-hits.md)

**Comment by gitcro** [comment]
I've used the 'vue-analytics' package now instead of the '@gridsome/plugin-google-analytics' package. From the layout component I then called the send pageview function on mounted and it now works.
