### ISSUE TITLE
Trailing slash must be included in directory URLs

### ISSUE THREAD

**Issue by greg-raven** [gridsome/gridsome#121]
## Description

gridsome build generates directory links with an invalid configuration. Directory URLs must have a trailing slash.

### Steps to reproduce

run generate build and then attempt to validate the resulting code.

### Expected result

Links that look like this: <a href="/about/"

### Actual result

Links that look like this: <a href="/about"

**Comment by hjvedvik** [comment]
You're right :) Gridsome currently defaults to pretty URLs but that requires the server to redirect when linking directly to a page. We have plans to have a few options for how the URL structure should be. Some want to have `/about.html` and other wants `/about/`. We will also provide rewrite rules which plugins can use to generate `_redirects` or `.htaccess` etc. to make `/about` work without a redirect.

**Comment by robaxelsen** [comment]
@hjvedvik has this already been implemented perhaps?

**Comment by hwmaier** [comment]
Please don't abolish the pretty URLs and consider the option to have non-trailing slash URLs as well. Refer to https://github.com/gridsome/gridsome/issues/444#issuecomment-499799636. I understand those won't work out of the box and require some .htaccess magic compared to trailing slash URLs, but worth the effort. So users can choose conventional `/about/`   or pretty `/about` URLs . This is particular important for site migrations where you would want to maintain existing URLs without redirects.

**Comment by hjvedvik** [comment]
@hwmaier We will add a config option to keep the current behavior :)

**Comment by hacknug** [comment]
Looks like this might fix #589 :tada:
