### ISSUE TITLE
Unable to build with navigation guard

### ISSUE THREAD

**Issue by soongsta** [gridsome/gridsome#1210]
## Description

We are trying to build an app with navigation guards. When executing the command 
`gridsome build` we get an error:
`Error: Redirected from "/" to "/protected/test/" via a navigation guard.`

### Steps to reproduce

Demo repo found here https://github.com/soongsta/router_beforeEach

Or

1. Create a new app by `gridsome create appname`
2. Create folder called protected in the pages folder
3. Create a single vue page in the protected folder (or just copy paste "about.vue" page and rename to test.vue)
4. edit main.js and add the following code:

```
  router.beforeEach((to, from, next) => {
    // Do stuff before next page load
    if (to.path.includes("protected")) {
      next("/") //right now just redirect back to home, add authentication later
    } else {
      next() 
    }
  })
```

5. run gridsome develop (any page in protected folder is redirected to root folder)
6. run gridsome build fails with error **Could not generate HTML for "/protected/test/":**

### Expected result

Application builds

### Actual result

 build fails with error **Could not generate HTML for "/protected/test/":**

### Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.16

**Comment by jamacon36** [comment]
Hey @soongsta try adding a [client process](https://gridsome.org/docs/client-api/) check around the guard:

```javascript
  if (process.isClient) {
    router.beforeEach((to, from, next) => {
      // Do stuff before next page load
      if (to.path.includes("protected")) {
        next("/");
      } else {
        next(); // make sure to always call next()!
      }
    });
  }
```
