### ISSUE TITLE
graphql page-query in an external file

### ISSUE THREAD

**Issue by soongsta** [gridsome/gridsome#1215]
## Summary

Some of our pages has several graphql queries. It would be nice feature to have the graphql outside the page. Reduces clutter etc

### Basic example

It would be nice to either 
import postsqry from "@/postqry.ql";

Or

`<page-query src="@/postqry.ql">`

### Motivation

Why are we doing this?
Less code in a single file

What is the expected outcome?
Maintenance friendly code

**Comment by hjvedvik** [comment]
This is planned to be included in v0.8. See #806. It will hopefully be ready sometime next weekend.
