### ISSUE TITLE
Hydration issue

### ISSUE THREAD

**Issue by falseresync** [gridsome/gridsome#1216]
## Description

I see this error, but only in production:
```
HierarchyRequestError: Node.appendChild: Cannot add children to a Text
```

### Steps to reproduce

Can be seen at https://fabric.falseresync.ru/gradle-info (if weren't solved by now)

### Page source

https://github.com/falseresync/fabric-website/blob/0ea1e8e368090d4f4b3cbf6d7a54f32a9d60f3cb/src/pages/GradleInfo.vue

### Environment
```
  Binaries:
    Node: 12.16.2 
    npm: 6.14.4
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    gridsome: ^0.7.0 => 0.7.16
```

**Comment by hjvedvik** [comment]
I think the issue is the `h2` element inside the [`noscript`](https://github.com/falseresync/fabric-website/blob/0ea1e8e368090d4f4b3cbf6d7a54f32a9d60f3cb/src/pages/GradleInfo.vue#L3-L5) tag. You can try something like this instead and see if it helps:

```html
<noscript v-html="`<h2>...</h2>`" />
```

**Comment by falseresync** [comment]
That solved it, thanks!
