### ISSUE TITLE
innerHeight displays wrong value on mobile in dev mode

### ISSUE THREAD

**Issue by chrispreisler** [gridsome/gridsome#1221]
## Description

I would like to get the height of the viewable area of a website. In JS you can archive this with "window.innerHeight" or "document.documentElement.clientHeight". When displaying the values on Desktop, everything works fine. But when I query the data on mobile (Safari 13.1) in dev mode, I get a height which is three times the correct value. I think this is related to the pixel density. The weird thing is when I change the site to the About Page and back it shows the right height. Also when I build it, it always shows the right height. 

Do you have any idea why I get the wrong value in dev mode?

### Steps to reproduce

I build a Codesandbox, where you can experience it by loading the url in dev mode on an iPhone. When you tap on About and back on start it corrects the values.

https://codesandbox.io/s/focused-gauss-c8gt6?file=/src/pages/Index.vue

Build Vercel Link:
https://csb-c8gt6-8lgvgk4vc.now.sh/

### Expected result

Always show the correct height

### Actual result

On load it shows the 3*height.

Thank you very much for your help.

**Comment by chrispreisler** [comment]
Hey, thanks for looking into that. 

Yeah it is only working on an iPhone directly. Here the steps to reproduce:

1. Open mobile Safari on iPhone X or iPhone Xs or iPhone 11
2. Open Codesandbox link.
3. Now it should show the wrong height (3*correct height)
4. Click on About and back on Start.
5. Now it should show the correct height
6. Open Vercel link and it shows the correct height from the beginning.

I hope this helps you.

Best regards
Chris

**Comment by Sergix** [comment]
@chrispreisler 

So this occurs on CodeSandbox but not your actual build, correct? If so then it's probably just something involving CodeSandbox's `<iframe>`.

**Comment by chrispreisler** [comment]
Hey guys,

no, I first experienced it in dev mode on my local environment. And after that I built the CodeSandbox to check if it has something to do with my code or any plugin or it is also happening with just gridsome installed. And then I saw that it is also happening in CodeSandbox. So I don't think it has anything to do with CodeSandbox.

Thanks again for looking into that.

Best regards
Chris

**Comment by Sergix** [comment]
Ok, so to clarify, this is an issue involving the development server, correct?

**Comment by chrispreisler** [comment]
Yes it happens, when I start the dev server with „gridsome develop“

**Comment by cco3** [comment]
But does it not do the same thing in production?  This doesn't quite seem like a gridsome issue.  Feel free to reopen if it is.
