### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by soongsta** [gridsome/gridsome#1222]
## Description

gridsome build fails to build with the following error:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### Steps to reproduce

Currently occurs in our project which we cannot post publicly.

How we resolve it, but does not always work
1 delete dist folder
2 delete node_modules folder
3 delete package-lock.json 

We upgrade from node 10 to 12 (google search indicated that this could be a possible solution)

Another google search suggested solution was NODE_OPTIONS=--max_old_space_size=4096
But we are unsure where to put this for gridsome.

### Expected result

Project builds

### Actual result

Initializing plugins...
Load sources - 1.18s
Create GraphQL schema - 0.39s
Create pages and templates - 0.47s
Generate temporary code - 0.04s
Bootstrap finish - 3.27s
Compile assets - 41.21s
Execute GraphQL (4519 queries) - 66.39s
Write out page data (4519 files) - 2.57s
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7A86946CF napi_wrap+113583
 2: 00007FF7A863F7C6 v8::base::CPU::has_sse+66646
 3: 00007FF7A86405C6 v8::base::CPU::has_sse+70230
 4: 00007FF7A8E542AE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7A8E3C381 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7A8D088CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7A8D13B00 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7A8D10624 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7A8D05E23 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7A8D04494 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7A8D257DB v8::internal::Factory::NewFixedArrayWithFiller+107
12: 00007FF7A8D1E7A7 v8::internal::Factory::InternalizeString<unsigned short>+471
13: 00007FF7A8B78429 v8::internal::HashTable<v8::internal::NameDictiFATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
onary,v8::internal::NameDictionaryShape>::NewInternal+57
14: 00007FF7A8B77C0C v8::internal::HashTable<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::New+108
15: 00007FF7A8B77926 v8::internal::BaseNameDictionary<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::New+22
16: 00007FF7A8BB276B v8::internal::JSReceiver::HasProperty+10731
17: 00007FF7A8BB39BF v8::internal::JSObject::MigrateToMap+351
18: 00007FF7A8B9808D v8::internal::LookupIterator::TransitionToAccessorProperty+413
19: 00007FF7A8BA851A v8::internal::JSObject::AddProperty+4794
20: 00007FF7A8BB9301 v8::internal::JSObject::TransitionElementsKind+2497
21: 00007FF7A8BB4832 v8::internal::JSObject::NormalizeProperties+1778
22: 00007FF7A8BA92C5 v8::internal::JSObject::DefineAccessor+3461
23: 00007FF7A8DCABEA v8::internal::Builtins::builtin_handle+72746
24: 00007FF7A92A780D v8::internal::SetupIsolateDelegate::SetupHeap+546893
 1: 00007FF7A86946CF napi_wrap+113583
 2: 00007FF7A863F7C6 v8::base::CPU::has_sse+66646
 3: 00007FF7A86405C6 v8::base::CPU::has_sse+70230
 4: 00007FF7A8E542AE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7A8E3C381 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7A8D088CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7A8D13B00 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7A8D10624 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7A8D05E23 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7A8D04494 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7A8D2569D v8::internal::Factory::NewFillerObject+61
12: 00007FF7A8A8BF21 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF7A92A770D v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 00007FF7A9310688 v8::internal::SetupIsolateDelegate::SetupHeap+976584
15: 00007FF7A922C6BC v8::internal::SetupIsolateDelegate::SetupHeap+42748
16: 00000008E2CFD5C5

### Environment
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.1
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3
    @gridsome/remark-prismjs: ^0.3.0 => 0.3.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    gridsome: ^0.7.17 => 0.7.17
    gridsome-plugin-flexsearch: ^0.1.20 => 0.1.20

**Comment by soongsta** [comment]
We import all our contentTypes from json files in gridsome.server.js. Is this the best approach? 

const countries = require('./content/countries.json');
const cities = require('./content/cities.json');
const regions = require('./content/regions.json');
const tags = require('./content/tags.json');
const authors = require('./content/authors.json');
const categories = require('./content/categories.json');
const events = require('./content/events.json');
const posts = require('./content/posts.json');
const jobs = require('./content/jobs.json');
const venues = require('./content/venues.json');

And then use addCollection like below:

```
  api.loadSource(store => {
    const contentType = store.addCollection({
      typeName: 'Country',
    });
    for (const item of countries) {
      contentType.addNode({
        id: item.id,
        name: item.name,
        countrycode: item.countrycode,
        image: item.image,
        content: item.content,
      })
    }
  })
```

We only have 1400 events. Which is not much. If we delete some events, then we can build without any issue

**Comment by Sergix** [comment]
@soongsta 

It seems like you're loading way too much into memory. Can you delay loading any of these assets until needed? That should solve your issue.

This shouldn't be an issue with Gridsome specifically, so I'll close this issue, but if you have any more questions I'll try my best to answer them.

**Comment by soongsta** [comment]
Thanks. 
Can you give an example of how to delay loading the assets.

**Comment by Sergix** [comment]
For instance, rather than adding each JSON file as a new collection to the GraphQL data layer, could you import the JSON files in the components that depend on them?

**Comment by soongsta** [comment]
So essentially doing a graphql join later (when needed) rather than earlier in the gridsome.server.js?

**Comment by soongsta** [comment]
@Sergix Do you think switching to MD file is better than json? Would there be a MD file MAX limit?

**Comment by Sergix** [comment]
I would say just not using GraphQL if not absolutely necessary. Just load the JSON file as an object in the component and access it that way.

And I would definitely not use markdown for this; JSON is designed for storing data, while Markdown (MD) is for documentation and prose. And yes, any type of data has a theoretical max limit, which in this case is the size of the process allocation heap.
