### ISSUE TITLE
Cache images with g-image

### ISSUE THREAD

**Issue by theisws** [gridsome/gridsome#1229]
I got an issue with g-image, it seems, that it won't cache images.
The site loads very slow, and all images is blurry in 2-4 seconds, it would be fine first time you enter det page. But if I refresh the site it does it again. 
Is there any way, where g-image caches the images in local storage, and only blur images that hasn't been loadet before?

**Comment by Sergix** [comment]
It's typically up to your browser to cache the images. What browser are you using?

You can also try reducing the image's file size to lower the loading times.

**Comment by CodingCarter** [comment]
Converting your images to jpg and then using tinypng.com on them usually does the trick to get the fastest loading you can.  (Also try actually resizing the image before all of those steps if you want to)
