### ISSUE TITLE
After build, CSS file is being added twice on HTML head

### ISSUE THREAD

**Issue by CodingCreate101** [gridsome/gridsome#1236]
## Description

After the build, the CSS file is being added twice on HTML head. This can be seen on the Gridsome official site as well.
This might impact performance.

### Steps to reproduce

> Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

Open the following on your web browser:
view-source:https://gridsome.org/

Search for `.css`. 

Two of those CSS files are going to be exactly the same.

### Expected result

There should be only one CSS file link

### Actual result

There are two:
1. `<link rel="preload" href="/assets/css/0.styles.543b8858.css" as="style" onload="this.onload=null;this.rel='stylesheet'">`
2. `<link rel="stylesheet" href="/assets/css/0.styles.543b8858.css">`

### Environment
Production

**Comment by noxify** [comment]
For me, it seems that the behavior is correct.

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by CodingCreate101** [comment]
I think you are right, @noxify . This was a misunderstanding. 
Thank you for clarifying. :)

**Comment by mamoyz** [comment]
@CodingCreate101  I'm having same problem (can't say it's a problem)
But the problem is when I try to test my website with PageSpeed Insights.
It gives me an error "Remove unused Javascript" because Google thinks it's a redundant script.
![image](https://user-images.githubusercontent.com/18643250/90646701-2c76f800-e240-11ea-8bda-ca1b32c6ab4e.png)

**Comment by CodingCreate101** [comment]
I understand your pain. 

My opinion is that, Google wants you to load absolutely necessary assets during the rendering phase. At this point, user isn't doing anything on the page. No hover, no modals open, no JS state changes etc. So, I think Lighthouse expects us to load ONLY things that make the initial visual content. Later, it might be okay to load. I've no idea whether that's true or how to test it. It's such a pain.
