### ISSUE TITLE
[Question] Pattern for handling incorrect params in the routes in production

### ISSUE THREAD

**Issue by sagrawal-idrc** [gridsome/gridsome#1239]
I have defined a route in gridsome.server.js: `/resource/:uid` and create several pages for this route. They get generated correctly when I build. However, if I try to access `/resource/<uid-doesn't-exist>`, it gets redirected to the 404 custom page, but there are several errors from the component (for the route) and because of that the lazy images etc on the 404 page fail to load. There is no corresponding directory (containing index.html) for <uid-doesn't-exist> inside the dist/resource directory. Directories for existing uids are present.

What is the correct way to handle this?

**Comment by Sergix** [comment]
Can you attach the error messages you receive from the component?

**Comment by sagrawal-idrc** [comment]
The error messages are application specific. There is `<page-query>` in the the template page component which retrieves an entity from the Gridsome GraphQL API and uses it further. The error messages are related to that entity not being available.

Please note that this happens in the production build.

**Comment by hacknug** [comment]
@sagrawal-idrc should be fixed in v0.7.18. Can you try if it works as you'd expect it and report back?

**Comment by sagrawal-idrc** [comment]
Hi, sorry for the late reply @hacknug 

Thank you, the the fix works good. Closing the ticket.
