### ISSUE TITLE
vue-remark have bug with symbolic link

### ISSUE THREAD

**Issue by sebtiz13** [gridsome/gridsome#1251]
## Description
For my project I have two directory to separate gridsome of content (markdown). In gridsome project I have make an symbolic link (with ln -s) to get access easily to my markdown from gridsome. It's work perfectly with source-filesystem but i don't realy understand why not work with vue-remark plugin.

### Steps to reproduce

1. `gridsome create symbolic-test`
2. `cd symbolic-test`
3. `yarn add @gridsome/vue-remark`
4. Add plugin to gridsome.config.js
```
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'MarkdownPage',
        baseDir: './content',
        template: './src/templates/MarkdownPage.vue'
      }
    }
```
5. Create template "src/templates/MarkdownPage.vue"
```
<template>
  <Layout>
    <h1>{{ $page.vueRemarkPage.title }}</h1>
    <VueRemarkContent />
  </Layout>
</template>

<page-query>
  query MarkdownPage($id: ID!) {
    markdownPage(id: $id) {
      title
    }
  }
</page-query>

```
6. `mkdir test`
7. `echo "---\ntitle: test\n---\n\ntest" >> test/page.md`

### Expected result

Compile markdown files

### Actual result

> Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
\> ---
| title: title
\
@ ./src/.temp/routes.js 53:13-55:72
@ ./node_modules/gridsome/app/router.js
@ ./node_modules/gridsome/app/entry.sockjs.js
@ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

### Environment

> System:
OS: Linux 5.4 Manjaro Linux
CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
Binaries:
Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
Yarn: 1.22.4 - /usr/bin/yarn
npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
Browsers:
Firefox: 77.0.1
npmPackages:
@gridsome/source-filesystem: ^0.6.2 => 0.6.2
@gridsome/transformer-remark: ^0.6.0 => 0.6.0
@gridsome/vue-remark: ^0.2.1 => 0.2.1
gridsome: ^0.7.17 => 0.7.17
gridsome-plugin-remark-shiki: ^0.3.1 => 0.3.1
gridsome-plugin-typescript: ^0.4.0 => 0.4.0
npmGlobalPackages:
@gridsome/cli: 0.3.3

**Comment by hjvedvik** [comment]
The main "under the hood" difference between `source-filesystem` and `vue-remark` is that `vue-remark` processes the Markdown files in a webpack loader. The loader will only process files that are within the `baseDir` option, and since webpack resolves symlinks to its original location by default, they are considered to be outside that folder.

You can work around it by using the [`includePaths`](https://github.com/gridsome/gridsome/tree/master/packages/vue-remark#includepaths) option to tell `vue-remark` to process files in another location to:
```js
includePaths: ['/absolute/path/to/original/directory']
```

Or disable symbolic link resolving in the [webpack  config](https://gridsome.org/docs/config/#chainwebpack):
```js
chainWebpack(config) {
  config.resolve.set('symlinks', false)
}
```

**Comment by sebtiz13** [comment]
Thanks you very much.
Finaly I use fs.realpathSync to solve the problem.

```javascript
const fs = require('fs');
module.exports = {
  plugins: [
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'MarkdownPage',
        baseDir: 'fs.realpathSync('./my-symbolic-dir')',
        route: '/pages/:slug'
      }
    }
  ]
}
```
But why `source-filesystem` and `vue-remark` not use same method ? It's due to vue components support ?

Otherwise, It's possible to add this details in documentation of vue-remark ?
