### ISSUE TITLE
Unable to run project due to python error

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#1255]
## Description

Tried running the project locally, received the error below.

I have tried installing Python as it says below (not sure why I need Python, I've been running this project for over a year without it). However, that hasn't fixed the issue.

### Steps to reproduce

Node modules is already installed and updated, however it prompted me to run 'yarn' to install dependencies.

Ran yarn, and the following error below happened.

### Expected result

The project should run.

### Actual result

The project doesn't run. Instead, this error displays:

yarn install v1.19.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution in
consistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
warning "netlify-cms > netlify-cms-media-library-cloudinary@1.3.4" has unmet peer dependency "netlify-cms-lib-util@^2.1.3-beta.0".
warning "netlify-cms > netlify-cms-widget-code@1.1.1" has unmet peer dependency "@emotion/core@^10.0.9".
warning "netlify-cms > netlify-cms-widget-code@1.1.1" has unmet peer dependency "lodash@^4.17.11".
warning "netlify-cms > netlify-cms-widget-code@1.1.1" has unmet peer dependency "netlify-cms-ui-default@^2.6.2".
warning "netlify-cms > netlify-cms-app > netlify-cms-core > react-hot-loader@4.12.18" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning "netlify-cms > netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > style-resources-loader@1.3.3" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
[7/7] ⠈ node-sass
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
error C:\Users\MyName\Desktop\development\infused-gridsome\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: C:\Users\MyName\Desktop\development\infused-gridsome\node_modules\sharp
Output:
info sharp Using cached C:\Users\MyName\AppData\Roaming\npm-cache\_libvips\libvips-8.7.0-win32-x64.tar.gz
info sharp Creating C:\Users\MyName\Desktop\development\infused-gridsome\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\MyName\Desktop\development\infused-gridsome\node_modules\sharp\vendor\lib to C:\Users\MyName\Desktop\development\infused-gridsome\node_mo
dules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\MyName\Desktop\development\infused-gridsome\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.16.1 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\MyName\Desktop\development\infused-gridsome\node_modules\sharp

### Environment

Windows.

**Comment by tkhquang** [comment]
Possibly duplicate: https://github.com/gridsome/gridsome/issues/585

**Comment by jd-fillmore** [comment]
@tkhquang tried everything in that thread, none of the solutions worked.

Anyone have any idea?

I've had this project for over a year running totally fine. Suddenly, for the last week, I haven't been able to run the project at all.

**Comment by jd-fillmore** [comment]
Update: solved.

Managed to solve the issue by going into the project and running by going into the project and:

1. rm -rf node_modules
2. yarn upgrade --latest
3. yarn install

Then I could run the project.

**Comment by marcodeluca** [comment]
Anyone still trying to get this legacy project to work, i had another solution to add to https://github.com/gridsome/gridsome/issues/585 that worked for me.
