### ISSUE TITLE
gridsome develop does not yield the same as gridsome build

### ISSUE THREAD

**Issue by branquito** [gridsome/gridsome#126]
## Description

In my `src/main.js` file, I added this snippet of code:

```
appOptions.render = h =>
  h("layout", {}, [h("router-view", {attrs: {id: "app"}})])
```

This way I don't have to wrap each page into a layout component, and the order is different because this now wraps the router, my page components will be nested under `layout` component and not vice-versa.

So in vue inspect you would actually see this:

```
<About>
  <Layout>
```

instead of: 

```
<Layout>
  <About>
```

I did this to be able to add transition over `<slot>` component which is inside my `layout` component, because it otherwise wouldn't work, as the layout component was recreated on each page/route change.

So now I got the desired behavior in my development environment, but for some reason `gridsome build` doesn't take this into account, and does some weird stuff, which makes double nesting, so the page components aren't visible at all, when site is being deployed.

### Steps to reproduce

Having that appOptions overriden like above, when you run `gridsome develop` I get the expected result, and components are
behaving well, however running `gridsome build` then deploying that or running on local static server, doesn't work and components aren't rendered properly.

### Expected result

Both should yield the same result, `gridsome develop` and `gridsome build`

### Actual result

`gridsome build` doesn't give exepected results, as build is different.

**Comment by hjvedvik** [comment]
You should keep the `app` id on the root element since Vue gets hydrated on `#app`. Try with this instead `h("layout", {attrs: {id: "app"}}, [h("router-view")])`.

**Comment by branquito** [comment]
Yes it works that way, thanks. But it's still strange the dev version works fine even without this change. Aren't they supposed to be equivalent?

**Comment by hjvedvik** [comment]
The `develop` command renders a `<div id="app"></div>` and mounts the Vue app on that. That's why it works in development. We can see if it is possible to make Gridsome use something else to target the root element to avoid problems like this :)

**Comment by branquito** [comment]
That would be great. Because really semantically layout should be parent element not the child one, that way it exposes much more flexibility regarding slot usage I think, also It wouldn't re-render on each route change. Anyway, Gridsome is very good project, congrats on that!
