### ISSUE TITLE
Set content of named layout slot from within Markdown

### ISSUE THREAD

**Issue by cvh23** [gridsome/gridsome#1260]
Is there any possibility to set content of a named layout slot (e.g. sidebar) from within Markdown like in VuePress?
Or is there at least a possibility to query certain elements of a Markdown page, which are not part of the frontmatter?

**Comment by a-kriya** [comment]
Querying parts of content in GraphQL? I don't think that's possible. Not even sure how that would work. Querying them in JS after the content has been transformed is, though. Defining slots as in VuePress is also not possible. Would https://gridsome.org/plugins/@gridsome/vue-remark suit your purposes instead?
