### ISSUE TITLE
[Gridsome CLI] - Dont accept another kit starter

### ISSUE THREAD

**Issue by JoshDev1205** [gridsome/gridsome#127]
## Description

When you try to create a new project with a different KIT than Wordpress or default that launch an Error

### Steps to reproduce

gridsome create <name> contentful 

### Expected result

What should happen?

![image](https://user-images.githubusercontent.com/20880980/51117835-ded11880-17dc-11e9-92f9-fb0b4698d494.png)

### Actual result

What happened.

![image](https://user-images.githubusercontent.com/20880980/51117613-518dc400-17dc-11e9-8f95-124a901bf572.png)

**Comment by JoshDev1205** [comment]
Hello

I wanna help with this Issue but i wanna ask something.

U'll host all the starter kits ???

Confirm that to send my PR for this, if u want to do that.

Good Job :)

**Comment by hjvedvik** [comment]
Currently the command only supports shorthands for the `default` and `wordpress` starters. But you can install any starter on Github with `gridsome create site {REPOSITORY_URL}`.

We aren't sure what to do with the command yet. I think we are only going to maintain a few very basic starters in core. Maybe for each core source plugin where it is possible. But we want to create a starter overview on the website with «copy to clipboard» commands when there are enough starters out there. But I don't think we can expect to see many starters until Gridsome is released as `1.0`.

We are also considering theme functionality which will work much better than starters. :)

**Comment by JoshDev1205** [comment]
Ok 

In that case i'll close that issue.

Good Job :)
