### ISSUE TITLE
"Position" Parameter Missing for Image Requests via GraphQL

### ISSUE THREAD

**Issue by amxmln** [gridsome/gridsome#1283]
## Description

When using `<g-image>` it is possible to supply a `position` prop in order to control from which sides the image gets cropped if it’s not sized within its aspect ratio. This is not possible if the image is included via a GraphQL query, since all props get ignored and there’s no way to pass a `position` parameter to the query.

### Steps to reproduce

Request an image (intrinsic 800x600px) via GraphQL:

```
query($id: ID!) {
  post(id: $id) {
    image(width: 300, height: 300, position: "left")
  }
}
```

Display it on a page via `<g-image :src="$page.post.image />`.

### Expected result

The image should be cropped from the right, honoring the `position: "left"` parameter.

### Actual result

There’s an Error: `"Unknown argument \"position\" on field \"image\" of type \"Post\"."`

Not passing that parameter and using `<g-image :src="$page.post.image` position="left" />` instead causes the image to be cropped from the centre as the prop is ignored and the default value for `position` is used.

### Environment

Node.js 14.5.0, Gridsome 0.7.19 and prior versions

Thank you for your time. :blush:

**Comment by theshanergy** [comment]
Any workaround for this?
