### ISSUE TITLE
Improve documentation for default global metadata

### ISSUE THREAD

**Issue by a-kriya** [gridsome/gridsome#1294]
The current documentation for `siteUrl` does not mention that it's added to global metadata by default, and nor does the _Global metadata_ docs:

https://gridsome.org/docs/config/#siteurl (this does not deep-link on Chromium-based browsers for me)
https://gridsome.org/docs/metadata/

It'd be good to document all the queryable fields of `metadata`, and mention the utility of `siteUrl` config field.

**Comment by tkhquang** [comment]
This issue should be opened in the [gridsome.org repo](https://github.com/gridsome/gridsome.org/issues) instead
