### ISSUE TITLE
Build is not transpiled

### ISSUE THREAD

**Issue by FistMeNaruto** [gridsome/gridsome#130]
## Description

The build does not seem to get transpiled with babel and causes issues on IE11.

### Steps to reproduce

1. Create a gridsome using the default starter
2. Build it and deploy (here is the unmodified default starter hosted on Netlify: [https://transpile-gridsome.netlify.com](https://transpile-gridsome.netlify.com)
3. Open `dist/assets/js/app.*.js` and search for `=>`
4. Or open the page on IE11

### Expected result

Javascript running without errors, `g-image` loading.

### Actual result

Getting an error on IE11:
![screenshot from 2019-01-15 15-48-20](https://user-images.githubusercontent.com/13431677/51184806-0e1b7e80-18de-11e9-9c9b-df8a89998b59.png)
which corresponds to the following arrow function:
![screenshot from 2019-01-15 15-48-38](https://user-images.githubusercontent.com/13431677/51184817-183d7d00-18de-11e9-8426-ad6af4d5fd9c.png)

**Comment by hjvedvik** [comment]
Oh, I can publish a fix for this in a few hours :)

**Comment by Devportobello** [comment]
we had some discuss about that on discord, i solved some error by editing `package.json` and declaring supported browser versions (this gonna used by `babel-preset-env` and `autoprefixer`)
``json
...
"browserslist": [
  "last 4 versions",
  "ie 11"
]
...
``
_I was facing error from vue-meta who use `Symbol` but not from `g-image`_

**Comment by FistMeNaruto** [comment]
Awesome, on 0.4.4 the arrow functions are transpiled, but I'm still getting the `'Symbol' is undefined` error and g-image fails to load.
![screenshot from 2019-01-16 02-17-13](https://user-images.githubusercontent.com/13431677/51218434-1bb02300-1935-11e9-9287-340a217c355c.png)

I have tried adding the browserlist config to `package.json` in the project root, as @Devportobello mentioned, but the issue persists. [This comment](https://github.com/babel/babel-preset-env/issues/203#issuecomment-285820866) on a similar issue mentions that use of polyfills is required in this case. This comment is a few years old and `babel-polyfill` package has been replaced with `@babel/polyfill` and `@babel/preset-env` provides `UseBuiltIns` option [described here](https://babeljs.io/docs/en/babel-polyfill#usage-in-node-browserify-webpack).

Since not everyone needs old browser support, is there a way to control the gridsome babel config per project basis?

**Comment by peXed** [comment]
I just ran into the same issue. Is it already possible to compile Gridsome with modern mode?

**Comment by thasmo** [comment]
@hjvedvik Not sure how this should work but I'm using the latest gridsome version and custom browserslist and babel.config.js files and still the object-spread operator is not properly transpiled into something older browsers understand. Can't find *any* information about babel in the docs. I'm lost here.

**Comment by derevandal** [comment]
i'm having this same issue too...

In Edge 40+:
![image](https://user-images.githubusercontent.com/1340508/66264585-74cf2800-e7de-11e9-84fb-750ec878be07.png)

inside my package.json:
```json
"browserslist": [
    "last 4 versions",
    "ie 11"
  ],
```

@hjvedvik, could you help us?
