### ISSUE TITLE
Generate purely non dynamic site without app bundle

### ISSUE THREAD

**Issue by J-Rojas** [gridsome/gridsome#1306]
## Summary

I'd like to generate a site that doesn't require an app bundle or the Vue.js client side framework. I would like to use Gridsome for it's SSG features, but doesn't require dynamic app support on the client side.

Currently the build generates a rather large js bundle and loads it however this is unnecessary for purely static sites.

Is there a way to configure gridsome to eliminate building and loading these JS assets?

**Comment by J-Rojas** [comment]
After some experimentation, I figured out the way to override this behavior is to change the template for the html page using a custom `src/index.html`.

A look at the Gridsome source shows there's some template definitions for various custom link, meta, script tags that you can embed into the document wherever you'd like, along with removing the Gridsome defined ones as well. This means you can remove the links to the Vue app bundle and the page scripts if they are not necessary for your static output.

**Comment by MrMacStripe** [comment]
@J-Rojas Could you provide the index.html you used to achive this?

**Comment by J-Rojas** [comment]
Index.html example

    <!DOCTYPE html>
    <html lang="en">
        <head>
            ${title}
            ${vueMetaTags}
            ${vueMetaLinks}
        </head>  
        ${app}  
    </html>
