### ISSUE TITLE
Bump serialize-javascript dependency

### ISSUE THREAD

**Issue by dappjumper** [gridsome/gridsome#1307]
## Description

NPM Audit produces High-severity alert for a vue-server-renderer called serialize-javascript

This can be fixed on projects by adding

```
"serialize-javascript": ">=3.1.0"
```

To my project's package.json, but it should be done on gridsome itself, not for every new project using gridsome

### Steps to reproduce

Create any gridsome cli app and try running it

### Expected result

No high severity issues out-of-the-box

### Actual result

High severity issue out-of-the-box

### Environment
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gridsome: ^0.7.0 => 0.7.19
```

**Comment by hjvedvik** [comment]
I noticed the security message earlier today. A [PR](https://github.com/vuejs/vue/pull/11434) for upgrading it was merged in `vue-server-renderer` some hours ago. You should be able to update your lock file once they have publish a new version :)
