### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by mottox2** [gridsome/gridsome#131]
## Summary
I would like to use yaml with gridsome.
so I made gridsome-transformer-yaml plugin as a local plugin.

https://github.com/engineers-lt/portal/tree/master/plugins/gridsome-transformer-yaml

Are you planning to support yaml?

### Basic example

```js
const jsYaml = require('js-yaml')

class YamlTransformer {
  static mimeTypes () {
    return ['text/yaml']
  }

  parse(content, options) {
    const yaml = jsYaml.load(content)

    return {
      fields: {
        yaml
      }
    }
  }
}

module.exports = YamlTransformer
```

This is plugin code.

```yaml
- title: title1
  description: desc
- title: title2
  description: desc2
```

We will convert this data as follows

```graphql
query {
  report: report(path: "/data/reports") {
    yaml {
      title
      description
    }
  }
}
```

```
report {
  yaml [
    {
       title: 'title1',
       description: 'desc'
    },
    {
       title: 'title2',
       description: 'desc2'
    }
  ]
}
```

### Motivation

It is preferable to make it in a format like yaml when trying to make it with less budget.

I would to submit Pull Request.

**Comment by hjvedvik** [comment]
Yes, create a PR for it :)

**Comment by rchrdnsh** [comment]
hmmmm...trying to use the plugin but I don’t really understand what to do. Maybe there could be a little tutorial on the plugin page on how to use it?
