### ISSUE TITLE
Web pictures are not lazy loading

### ISSUE THREAD

**Issue by jalenchuh** [gridsome/gridsome#1315]
## Summary

Web pictures are not lazy loading. Only local images lazy loading.

Hope to support lazy loading of web pictures.

**Comment by hjvedvik** [comment]
@jalenchuh You're right. Gridsome currently only processed and lazy-loads local images. The plan is to make Gridsome download and process them etc. But you can use a package like [vue-lazyload](https://www.npmjs.com/package/vue-lazyload) to lazy-load your images in the meanwhile.

**Comment by jalenchuh** [comment]
Thanks. But how can I have no methods to use `v-lazy` install of `:src` when the generating of images in `.md`, I can only use vue-lazy in other pages. Is there any ways?

###### English is not my native language; please excuse typing errors.

**Comment by Mini-ghost** [comment]
@jalenchuh Maybe you can try to use [@gridsome/vue-remark](https://gridsome.org/plugins/@gridsome/vue-remark) plugin. It allows you to import any Vue Component, any JSON or other `.md` files in your `.md` file

**Comment by jalenchuh** [comment]
@Mini-ghost Maybe I can not manage it, but thank you all the same.
