### ISSUE TITLE
[question] adding reset css before all css

### ISSUE THREAD

**Issue by u007** [gridsome/gridsome#1326]
## Summary

Need a way to prepend a reset css before all other css , like uikit

### Basic example

src/main.js

```
export default function (Vue, { router, head, isClient }) {
  //push also does not work
  head.link.unshift({
    rel: 'stylesheet',
    href: 'https://unpkg.com/reset-css/reset.css',
  });
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)
}

```

### Motivation

need a way to have a reset css to have consistant look for all browser

**Comment by noxify** [comment]
Hey @u007 

I assume you're also using `less` or `scss` for your styling.
You could import `reset-css` at the top of your main style file ( e.g. `app.less` or `app.scss` ).

* https://www.npmjs.com/package/reset-css#usage

**Comment by noxify** [comment]
Alternative, you could also override the default `index.html` and add your code above the `${head}`.

https://gridsome.org/docs/overriding-index/

**Comment by u007** [comment]
> Hey @u007
> 
> I assume you're also using `less` or `scss` for your styling.
> You could import `reset-css` at the top of your main style file ( e.g. `app.less` or `app.scss` ).
> 
> * https://www.npmjs.com/package/reset-css#usage

based on gridsome blog sample with strapi, which file should i add this? main.js?

**Comment by noxify** [comment]
I assume you're talking about: https://github.com/strapi/strapi-starter-gridsome-blog

Untested, but could work:

1. Add `reset-css` as dependency in the `frontend/package.json`
2. Import `reset-css`

For step 2, i have two options in mind:

#### Load the `reset-css` stuff directly
In the `frontend/src/main.js` you have to insert the following line `import 'reset-css'`
 
#### Use a separate file to import
1. Create a new file `frontend/src/assets/scss/main.scss`
2. Add the following line at the top of the `main.scss`: `@import '/path/to/reset-css/sass/reset';`
3. In the `frontend/src/main.js` you have to insert the following line `import '~/assets/scss/main.scss'`


----

Hope that helps :)

**Comment by u007** [comment]
hi @noxify thank you , ive tried it, but it seems that the reset.css is added after uikit

**Comment by u007** [comment]
is there hot reload to support on the fly changes?

**Comment by noxify** [comment]
> hi @noxify thank you , ive tried it, but it seems that the reset.css is added after uikit

could you share how you have implemented it?

**Comment by u007** [comment]
okay i did this and it works, modified index.html and removed the static uikit css n js, and then modified main.js
```
import DefaultLayout from '~/layouts/Default.vue'
// import "reset-css";
export default function (Vue, { router, head, isClient }) {

  head.link.unshift({
    rel: 'stylesheet',
    href: 'https://fonts.googleapis.com/css?family=Staatliches',
  });

  head.link.unshift({
    rel: 'stylesheet',
    href: 'https://cdn.jsdelivr.net/npm/uikit@3.3.1/dist/css/uikit.min.css',
  });

  head.link.unshift({
    rel: 'stylesheet',
    href: 'https://unpkg.com/reset-css/reset.css',
  });

  head.script.push({
    src: 'https://cdn.jsdelivr.net/npm/uikit@3.3.1/dist/js/uikit.min.js',
    body: true
  });

  head.script.push({
    src: 'https://cdn.jsdelivr.net/npm/uikit@3.3.1/dist/js/uikit-icons.min.js',
    body: true
  });

  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)
}

```

**Comment by noxify** [comment]
Perfect - so we can close this issue?

**Comment by u007** [comment]
yes thank you :)
