### ISSUE TITLE
Is there any way to make the data from my site publicly available via GraphQL?

### ISSUE THREAD

**Issue by rasulkireev** [gridsome/gridsome#1327]
## Summary

I'm not sure if this exists already, but I was wondering if it is possible to make the data available publicly.

### Basic example

For example, when I develop with `gridsome develop`, I can access the data at `http://localhost:8080/___explore`. Is it possible to have the same at `rasulkireev.com/___explore`?

### Motivation

This way I can use my data elsewhere.

**Comment by dominiquedutra** [comment]
Hey @rasulkireev 

Gridsome builds a graphql server during build time or during develop time to provide data to the application.
If you want to make your data available via graphql to be consumed by ie an external application, you would have to do so yourself. There are many graphql server implementations and you would have to take care of that, of keeping the process running, of building it on the server etc, of authentication etc.

Anyways, this does not belong within gridsome IMO.

Depending on the size of your project and depending of the original source (Api? Google Sheets?) you could use something like Hasura to easily implement graphql in front of your original source.

Best regards,

**Comment by rasulkireev** [comment]
@dominiquedutra thanks for your response. I'll look into options.
