### ISSUE TITLE
Unable to implmenet HSTS into site.

### ISSUE THREAD

**Issue by jmodanwal** [gridsome/gridsome#1346]
Hi
I want to implement [HSTS](https://hstspreload.org/)   into our site https://0707.agency/.
This can be added by send this information **Strict-Transport-Security: max-age=63072000; includeSubDomains; preload** into header. 
I have tried using gridsome-htaccess plugin but it seems that htaccess is worked with Apache server only. My site is hosted on AWS.
Can you please help me out in this? 

Many Thanks

**Comment by noxify** [comment]
Could this help?

https://aws.amazon.com/de/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/

**Comment by jmodanwal** [comment]
Thanks for reply.
I didn't use lambda function yet. My site is using AWS Amplify not S3. Is that help with Amplify app?

**Comment by noxify** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html

google is your friend ;)

**Comment by jmodanwal** [comment]
Thanks Buddy. This helps me lot. Hats Off!
