### ISSUE TITLE
Get all Images in Folder with additional Data

### ISSUE THREAD

**Issue by nawalnew** [gridsome/gridsome#1347]
## Summary

I have a special case and wanted to know if someone has a solution for that.
Im good ad Gridsome and different use cases. 

@gridsome/source-filesystem and remark are pulling .md files.

But I need following:
I need all Images in specific folder. And in best case additional Data with the image. 
I could do a .md file for every image ( more than 300 images ). That would be crazy overhead. 

Does someone know another solution for that? pulling dynamicliy images from folder and sort them by image name or something like that. 

### Basic example

It should be a Portfolio Page for Photography for fast adding new images. just push them to folder and show them in frontend. But as I told with additional data like "Image Size, Caption and so on" 

I would like to get fresh Ideas how to solve this Problem. 
If I will find a solution, I will share it with the community! 

Thank you :) 

### My Progress

Okay I have a direction. 
https://travishorn.com/creating-a-photo-gallery-with-vue-css-grid-3e0a3dd25285

This inspired me to use:
**gridsome-source-static-meta and a .json object with all images.** 

I think for the Moment its the only possibility. If someone know a better solution or things I can consider, i would appreciate it.

**Comment by noxify** [comment]
Hi,

i don't think you need a static json file.

Just an idea: create a custom `loadSource` logic to create the needed nodes.
https://gridsome.org/docs/collections/#add-collections-with-data-store-api

Via https://github.com/gomfunkel/node-exif you should have all available information from each image.
To get all files from a directory you could use https://github.com/sindresorhus/globby or something else.

**Comment by noxify** [comment]
I close this issue for now - feel free to reopen it or create a new issue.
