### ISSUE TITLE
`gridsome build` - Compiling assets take a lot of time

### ISSUE THREAD

**Issue by mortir** [gridsome/gridsome#1349]
### Description

When `yarn build` is runned, compiling assets take a lot of time. For small project with 8 pages it takes 5 minutes

![image](https://user-images.githubusercontent.com/26040834/93898719-2d49f080-fcfc-11ea-8a4b-4ecfccf7744f.png)

### Environment
Libs:
- gridsome version: 0.7.17
 
For Tooling issues:
- Node version: 12.18.2
- Platform:  Debian GNU/Linux 9

Others:
- Yarn version: 1.17.3

**Comment by noxify** [comment]
Could you test it with the latest gridsome version? 

Which assets do you use? 
Do you have the repo public so we can try to reproduce the problem?

**Comment by dota2eexim** [comment]
With the latest version of gridsome (0.7.21) everything is the same.
On PC with SSD compiling assets take 130s, on dev server with hdd it takes 350s.
At first glance this is the case,

I use typescript, scss, sentry integration, + others small libs

**Comment by noxify** [comment]
we had something similar some time ago: https://github.com/gridsome/gridsome/issues/1190

**Comment by dota2eexim** [comment]
Thanks, I'll check it

**Comment by mortir** [comment]
Resolved)
TypeScript and it's type checking is problem,

P.S. `transpileOnly: true` in production mode saved my life)

Issue closed for now)
