### ISSUE TITLE
CSS not loading after page reload

### ISSUE THREAD

**Issue by JosBroers** [gridsome/gridsome#1355]
## Description

When I rebuild my website in Vercel after an adjustment the CSS no longer shows on subpages. This has to do with caching and changing `app.code.js` and `page--src--pages--contact-vue.code.js` names.

For instance. Before the new build, these files are called:

`app.0a0000b0.js` and `page--src--pages--contact-vue.1b1111v1.js`

After the new building, these no longer exist. Instead, these files are now called:

`app.9z9999c1.js` and `page--src--pages--contact-vue.7d7777r7.js`

Because the names have been changed the site can't load them.

### Steps to reproduce

- Build Gridsome site with subpage
- Host site on Vercel
- Load site and load subpage
- Make changes and rebuild
- Visit site and subpage
- Reload subpage

### Expected result

CSS should load properly

### Actual result

CSS isn't loading at all.

### Environment

[Scouting Drunen](https://scouting-drunen.josbroers.now.sh/)

**Comment by Sergix** [comment]
The file names are changed to "bust" the cache in the browser and force a fetch of the new assets. The link to the website you provided isn't giving any `404` errors for the CSS files in my environment. What browser are you viewing the website with?

**Comment by JosBroers** [comment]
> The file names are changed to "bust" the cache in the browser and force a fetch of the new assets. The link to the website you provided isn't giving any `404` errors for the CSS files in my environment. What browser are you viewing the website with?

I'm using Chrome but same problem on other browsers. Currently I can load the css, but it's still loading an older file. When using hard-refresh I'm getting the correct file.

Site using hard-refresh (Latest version)
![1](https://user-images.githubusercontent.com/31503728/95061018-55bdeb80-06fb-11eb-98ba-d9cdbe329b3a.png)

Site with normal refresh (Older version)
![2](https://user-images.githubusercontent.com/31503728/95061082-6cfcd900-06fb-11eb-956b-e360297de309.png)

**Comment by JosBroers** [comment]
I still have the problem. After contacting Vercel Support, we came to the conclusion it isn't Vercel related. We ran two test:

Test 1:
```shell
~ curl -I -s https://scoutingdrunen.nl | grep etag
etag: <a value here>
```

Test 2:
```shell
~ curl -I -s https://scoutingdrunen.nl | grep etag
etag: <different value here>
```

So it has to do something with Gridsome.

**Comment by ShouravRakshit** [comment]
I am having similar issues like when I am commenting the css file and then uncomment it the css file works. In addition, when I reload the css does not work.
![image](https://github.com/gridsome/gridsome/assets/69850843/885f8cdb-a2c7-4307-b112-90794e83e9c0)
![image](https://github.com/gridsome/gridsome/assets/69850843/974f717f-b8cc-401b-b519-c9578d44ab4b)
This is actually weird casue the opacity works but the background color does not change for some reason.
![image](https://github.com/gridsome/gridsome/assets/69850843/0615e319-64ec-4a19-a19a-15a525458551)
