### ISSUE TITLE
Source plugin enhancement: Add support for WordPress menus

### ISSUE THREAD

**Issue by hacknug** [gridsome/gridsome#136]
## Summary

It would be great if `@gridsome/source-wordpress` supported at least one of the existing plugins to expose menus to the API.

- **https://es.wordpress.org/plugins/wp-api-menus/** (linked on the WP REST API website)
- https://es.wordpress.org/plugins/wp-rest-api-v2-menus/
- https://es.wordpress.org/plugins/ultimate-wp-rest/
- **https://github.com/WP-API/wp-api-menus-widgets-endpoints** (also linked on the WP REST API website but not on the official plugin repository)

### Basic example

Plugin should add something like `wordPressMenu` and `allWordPressMenu` to the schema. Menu locations are also a thing so `wordPressMenuLocations` and `allWordPressMenuLocations` should also be added.

### Motivation

This would make it easier to build sites using Gridsome and WordPress since menus are not exposed by default.

**Comment by 0aveRyan** [comment]
As valuable/important as this is, I'd suggest holding off on this particular integration as that part of the WP-API is actively being worked on.

There's currently [ongoing](https://wordpress.slack.com/archives/C02RQC26G/p1547749760252800) [discussion](https://wordpress.slack.com/archives/C02RQC26G/p1548516088412100) on putting menu endpoints [in WordPress Core](https://core.trac.wordpress.org/ticket/40878). 

More than casual, would-be-nice discussion too as the next phase of WordPress' Gutenberg editor project will include a new menu UI, which will need to be API-driven. 

I'd love to see wp menus in this source pkg eventually, and maybe another source plugin leveraging [an approach](https://github.com/royboy789/gutenberg-object-plugin) that pulls each Block in WordPress Post/Page content as it's own data object, but relatively low-lift to manually insert these data into the gridsome GraphQL layer from a custom API call so I'd wait until those APIs stabilize.

**Comment by hacknug** [comment]
Then maybe we can have a snippet here and/or in the docs to show users how they would add support for it manually in the meantime?

**Comment by 0aveRyan** [comment]
@hacknug definitely could/should live in docs! I'm booked solid until late february but hoping to add some wordpress-centric docs and tutorials this spring :)

few rough notes:
* [in wp](https://developer.wordpress.org/reference/functions/register_rest_route/), developer would register endpoint with `reigster_rest_route()` to return menu data.
* responsibility of the developer creating the integration to make parity between permalinks (i.e. wordpress might have posts at `/yyyy/mm/dd/slug` but gridsome might be setup to create routes at `/blog/yyyy/mm/slug/id`)
* another note on parity: wp's menu system expects to be the only source of truth for routing. a wordpress page could be setup at `/about` but if there's a file setup at `/src/pages/About.vue` in gridsome with different content, there could be unexpected results. additionally, if gridsome has routing setup to put wp pages at `/pages/:slug` this could also cause some unexpected results.
* in the `gridsome.server.js` a developer would need to request data from endpoint, `addContentType()` [to gridsome's store](https://gridsome.org/docs/data-store-api#collectionaddnodeoptions), make http request for data from endpoint, loop response objects and `addNode()` into created content type and then loop nodes in a navigation component file, injecting into `<g-link>`'s

**Comment by robaxelsen** [comment]
Closing this due to valid points by @0aveRyan. Feel free to open new issue for improved documentation, or submit a PR for it.

**Comment by kukac7** [comment]
and what about `child_items`?
