### ISSUE TITLE
scroll-margin-top not working

### ISSUE THREAD

**Issue by philippkuehn** [gridsome/gridsome#1361]
## Description

I can’t get [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top) to work as expected. It’s working fine on any other site but fails on any gridsome page.

Is there any magic happening on anchor clicks in gridsome?

### Steps to reproduce

add CSS:

```css
*[id] {
    scroll-margin-top: 100px;
}
```

click on any link with anchor. 

### Expected result

element should be 100px below top after scrolling.

### Actual result

element is 0px below top after scrolling.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 81.0.1
    Safari: 14.0
```

**Comment by cco3** [comment]
I had to change the router scroll behavior to get it to work:

```
// Overwrite the router options.
  router.options.scrollBehavior = async (to, from, savedPosition) => {
      const elem = document.querySelector(to.hash)
      // vue-router does not incorporate scroll-margin-top on its own.
      if (elem) {
        const offset = parseFloat(getComputedStyle(elem).scrollMarginTop)
        return {
          selector: to.hash,
          offset: { y: offset }
        }
      }
    }
    if (savedPosition) return savedPosition
    return { x: 0, y: 0 }
  }
```

I actually have a lot of other things in here to get scrollBehavior to do what I want, but this should get you started.

**Comment by philippkuehn** [comment]
@cco3 Thanks. that works great!

**Comment by sevensidedmarble** [comment]
This is some pretty strange default behaviour. Any way we can get this merged in somehow?

**Comment by cco3** [comment]
I think it might be an issue for vue-router rather than gridsome.

**Comment by mmorris8** [comment]
> // Overwrite the router options.
>   router.options.scrollBehavior = async (to, from, savedPosition) => {
>       const elem = document.querySelector(to.hash)
>       // vue-router does not incorporate scroll-margin-top on its own.
>       if (elem) {
>         const offset = parseFloat(getComputedStyle(elem).scrollMarginTop)
>         return {
>           selector: to.hash,
>           offset: { y: offset }
>         }
>       }
>     }
>     if (savedPosition) return savedPosition
>     return { x: 0, y: 0 }
>   }

router.options is private. How does this work?
