### ISSUE TITLE
Custom fields from the Markdown files?

### ISSUE THREAD

**Issue by benrolfe** [gridsome/gridsome#1368]
## Description

When using `@gridsome/source-filesystem`, how do I access custom fields from the Markdown files?
Ie: featured_image, author_name

### Environment

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.80
    Edge: 86.0.622.48
    Firefox: 77.0.1
    Safari: 14.0
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.2 => 0.1.2 
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
    @gridsome/remark-prismjs: ^0.3.0 => 0.3.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.21 => 0.7.21 
  npmGlobalPackages:
    @gridsome/cli: 0.3.4
```

**Comment by noxify** [comment]
Hey @benrolfe 

In case you have a md file like this:

```md
---
title: Troes retardat
image: ./images/josh-spires-dronenr-sQalFlXIsLs-unsplash.jpg
author: author1
---
// content
```

Then you can use the following query inside your template:

```
<page-query>
  query($id: ID!) {
    blog(id: $id) {
      title
      image(width:1600, height:800)
   }
}
```

Inside the `<template>` part of your template, you can use something like this:

```
<g-image
        :src="$page.blog.image"
        width="1400"
        height="400"
        class="object-cover absolute -z-10 h-full w-full"
></g-image>
```

For the author name, i assume you have a different collection which contains the author information and inside your `gridsome.config.js` you have defined the reference already.

If this is the case, here the `page-query`:

```
<page-query>
  query($id: ID!) {
    blog(id: $id) {
      title
      image(width:1600, height:800)
      author {
          id
          name
          image
          path
      }
   }
}
```

Via `$page.blog.author.name` you will get the name of the author :) 

Here some links which could help :)

* https://gridsome.org/docs/images/#usage-via-graphql
* https://gridsome.org/docs/templates/
* https://github.com/gridsome/gridsome/tree/master/packages/source-filesystem#refs

**Comment by noxify** [comment]
I close this issue for now - feel free to reopen it or create a new issue.
