### ISSUE TITLE
Passing img src to component using G-image

### ISSUE THREAD

**Issue by nolfranklin** [gridsome/gridsome#137]
## Description

First off, absolutely loving Gridsome! 

Not quite sure how to pass an image src as a prop to components using g-image and then having it render. Images in console throw a 404. In this case should a computed property be used in the ImageBlock component? 

**Page Template using ImageBlock:**

`<ImageBlock image="~/assets/images/studio.jpg" />`

**Image Component:**

```
<template>
	<div class="block block--image">
		<figure class="block--image__figure">
			<g-image :src="image" />
		</figure>
	</div>
</template>

<script>
export default {
	props: {
		image: { type: String }
	}
}
</script>
```

Thanks for your help! :)

**Comment by nolfranklin** [comment]
False alarm! Adding a computed property to the ImageBlock component did the trick.

```
computed: {
	setImage: function() {
		return require("@/assets/images/" + this.image);
	}
}
```

**Comment by bbugh** [comment]
If anyone else sees this, the proposed solution isn't actually working as expected. I created a new issue because this is still a bug.

https://github.com/gridsome/gridsome/issues/292
