### ISSUE TITLE
<g-image> loads immediately even if immediate-Prop is set to false

### ISSUE THREAD

**Issue by amxmln** [gridsome/gridsome#1370]
I  have noticed that all my images which are put on the page with the `<g-image>` component are loaded immediately if they have an `immediate` prop, regardless of whether that prop is `true` or `false`. I believe that’s caused by this line:

https://github.com/gridsome/gridsome/blob/accd1090a882bdbdbed1cdb29d7c5b67058db910/gridsome/app/components/Image.js#L23

Is there any specific reason why `immediate` has to be `true` if it’s not `undefined`? If so, I think that should be added to the docs, because the way it’s written now made me think I can have the "immediateness" controlled by the user.

Currently working around it with `:immediate="condition || undefined"` seems to work, but it unnecessarily bloats the template (and adding a computed prop just for it seems excessive as well). 😅

Thanks for your time!

**Comment by Erbenos** [comment]
Addressed by #1372
