### ISSUE TITLE
[source-datocms] ApiException: 500 Internal Server Error when building site.

### ISSUE THREAD

**Issue by dominic-lear** [gridsome/gridsome#1376]
## Description

When i run `npm run develop` or `npm run build` i receive the error.

ApiException: 500 Internal Server Error
    at /Users/XXX/node_modules/datocms-client/lib/Client.js:140:31

This error occurred on Friday and still persists today.

### Steps to reproduce

1. Setup a gridsome site  https://gridsome.org/starters/default-starter/
2. Setup a datocms instance
3. Integrate both via source-datocms
4. Run "npm run build"

### Expected result

Site builds successfully

### Actual result

 ApiException: 500 Internal Server Error 
    at /Users/XXX/node_modules/datocms-client/lib/Client.js:140:31

### Environment
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 80.0.1
    Safari: 14.0
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.1
    @gridsome/source-datocms: ^0.2.1 => 0.2.1
    gridsome: ^0.7.12 => 0.7.19
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

The same error is present on AWS amplify.

**Comment by hjvedvik** [comment]
Should be fixed in [`@gridsome/source-datocms@0.3.0`](https://www.npmjs.com/package/@gridsome/source-datocms)
