### ISSUE TITLE
Working example for Vue-Remark including markdown and Vue components?

### ISSUE THREAD

**Issue by J-Rojas** [gridsome/gridsome#1380]
I'm having trouble getting markdown included from another markdown template to work properly. The docs suggests this should work. Is there any working example of this case?

```
---
title: A cool title
excerpt: Lorem Ipsum is simply dummy text.
---
// Import any Vue Component. Even other .md files!
import YouTube from '~/components/YouTube.vue'
import AboutUs from '~/sections/AboutUs.md'

// Import any JSON if you need data.
import data from '~/data/youtube.json'

// Use front-matter fields anywhere.
# {{ $frontmatter.title }}
> {{ $frontmatter.excerpt }}

// Use your imported Vue Components.
<YouTube :id="data.id" />
<AboutUs />

Isn't it great? 🥳
```

**Comment by adamdehaven** [comment]
I have no issue with this -- you may want to check your config and that you have `@gridsome/vue-remark` properly installed.

**Comment by J-Rojas** [comment]
Thanks, I know there is a configuration issue. I'm looking for a good example to debug this.

**Comment by adamdehaven** [comment]
What you have above is literally a good example. It works.

**Comment by J-Rojas** [comment]
How is that a good example when you need configuration as you mention above?

**Comment by adamdehaven** [comment]
There is a full example outlined in the [plugin documentation](https://gridsome.org/plugins/@gridsome/vue-remark). You have to add the settings in `gridsome.config.js` and the `<VueRemarkContent />` component in the corresponding template.

**Comment by cco3** [comment]
Closing since as-is, the request is already fulfilled.  @J-Rojas if you have a specific error or something, you can start a new issue.

**Comment by J-Rojas** [comment]
@cco3 The simple request is to add a full working of Vue-Remark example to the examples folder with configuration.

**Comment by cco3** [comment]
Which examples directory are you referring to?

**Comment by J-Rojas** [comment]
Sorry, didn't mean the "examples" directory - which is a common pattern in other projects. I meant having an example in the starter projects mentioned on the Gridsome.org site. I didn't see one that uses this plugin. If there is one, would love a link to it.
