### ISSUE TITLE
Detect invalid collection names

### ISSUE THREAD

**Issue by stefaang** [gridsome/gridsome#1388]
## Description

Failure to start gridsome due to invalid collection name with an unclear error. 
```
TypeError: schemaComposer.get(...).hasInterface is not a function
```

### Steps to reproduce

In `gridsome.server.js`
```
    api.loadSource(async ({ addCollection }) => {
        const files = addCollection('File')
    }
```

### Expected result

An error or warning that `File` is an invalid collection name.

### Actual result

Unclear error, see above.

### Workaround

Change collection name to `MyFile`.

**Comment by hjvedvik** [comment]
I agree. That error message wasn't very helpful. Will improve it in the next version :)
