### ISSUE TITLE
Solid react component usage possible?

### ISSUE THREAD

**Issue by voordev** [gridsome/gridsome#139]
React components seems stronger; like more design tools and bigger eco system. I love gridsome for the less complicated out of the box approach. 

Would it be possible to use react components instead of vue components though? Is there an solid way to use react components? 

Love the project!

**Comment by Maxhodges** [comment]
@voordev are already mature static site generators for React. I can recommend https://www.gatsbyjs.org/. You may also want to take a look at https://phenomic.io/

This current project is inspired by Gatsby, but focused on Vue. Cheers!

**Comment by hjvedvik** [comment]
We have been thinking about supporting other libraries, but as @Maxhodges wrote, Gridsome will only focus on Vue for now.
