### ISSUE TITLE
addNode doesn't populate the graphql

### ISSUE THREAD

**Issue by lightyaer** [gridsome/gridsome#1407]
## Description
I sourced a list of todos from https://jsonplaceholder.typicode.com/, used addCollection and addNode. I cannot see the new Todos/allTodos Schema in graphql.

### Steps to reproduce

npx @gridsome/cli create gridsome-site
yarn add axios

this is my gridsome.server.js
```
const axios = require('axios');

module.exports = function (api) {
    api.loadSource(({addCollection}) => {

        axios.get('https://jsonplaceholder.typicode.com/todos').then((response) => {
            const c = addCollection('Todos');

            for (let item of response.data) {
                c.addNode({...item});
            }
        })
    })

}

```
![Capture](https://user-images.githubusercontent.com/5101454/103154779-efa7a880-47bf-11eb-820e-e4de6540c56b.PNG)

Cannot see the Todos in graphql

### Expected result
Should be able to see the new Todos schema in graphql

What should happen?

### Actual result

What happened.

### Environment

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23

**Comment by lightyaer** [comment]
It does work when I specify the schema using addSchemaTypes 

```
api.loadSource(({ addSchemaTypes }) => {
  addSchemaTypes(`
    type Post implements Node {
      id: ID!
      title: String
      userId: String
    }
  `)
})
```

**Comment by lightyaer** [comment]
Is there a way it can self generate the schema

**Comment by noxify** [comment]
Hi,

i have tested it quickly with the following code:

```js
// gridsome.server.js
const axios = require('axios')

module.exports = function (api) {
  api.loadSource(({
    addCollection
  }) => {

    // this is the difference to your example
    // in your example, you're running `addCollection` inside the axios `then` part.
    const todoCollection = addCollection('Todo')

    axios
      .get('https://jsonplaceholder.typicode.com/todos')
      .then((response) => {
        for (let item of response.data) {
          todoCollection.addNode({
            ...item
          });
        }
      })
  })
}
```

And it seems to work as expected.

My `package.json` is the following:

```json
{
  "name": "todo-app",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "gridsome": "^0.7.23",
    "axios": "^0.21.1"
  }
}
```

Hope that helps.

I will close this issue for now - feel free to reopen it, if it's not working.

Regards,
Marcus

**Comment by noxify** [comment]
Not sure why, but the `addNode` inside the `then` definition wasn't working as expected.
In the collection, only `id` was available.

Here the updated code snippet:

```js
// gridsome.server.js

const axios = require('axios')

module.exports = function (api) {
  api.loadSource(async actions => {

    const todoCollection = actions.addCollection({
      typeName: 'Todo'
    })

    try {
      const {data: response} = await axios.get('https://jsonplaceholder.typicode.com/todos')
      response.forEach(item => {
        todoCollection.addNode(item)
      });
    } catch(e) {
      console.log('API ERROR: ', e);
    }
    
  })
}
```

**Comment by lightyaer** [comment]
Hi @noxify, 
I had another question, post changing gridsome.server.js to your code, the graphql schema exists, but only with id field.
How do I query for all fields? 

I am trying to build a gridsome-source plugin, the objective is to source json, markdown and images from AWS S3, possibly even deploy to a S3 bucket.
In that case, the the graphql schema needs to be dynamic.

![Capture](https://user-images.githubusercontent.com/5101454/103155914-b411dc00-47c9-11eb-8584-062ede9dec07.PNG)

**Comment by noxify** [comment]
Hi @lightyaer 

i have added another snippet with a fix for this :)
