### ISSUE TITLE
Template should redirect to 404 when page-query not found

### ISSUE THREAD

**Issue by kaceo** [gridsome/gridsome#141]
Currently the layout templates do not have any error handling if the permalink returns no result.

e.g. page-query
query Single ($path: String!) {
  blogPost (path: $path) {
    title
  }
}

this query results a single result if $path is found
but an error if $path is not found

In the second case, the template should should be written to effect a transfer to 404.vue
How to achieve this?

**Comment by kaceo** [comment]
To be more clear, I am referring to the situation of a permalink pattern and not a general case, since for most deployment situation, it is up to the server to redirect to 404 any lost page.

The permalink pattern introduced by a data source definition, e.g. "blog/:year/:slug" creates inside Gridsome's router the permalink pattern to direct "blog/*/*" to the backend graphql layer for resolution.

This means a permalink which is correct will return a template page with json filled in properly = a correct result page.

This also means a permalink which is incorrect (e.g. :year or :slug is not found) will return a template page without json, means the page is empty.

For verification, run the following steps:

1. Install gridsome/gridsome-starter-markdown-blog
2. change the gridsome.config.js plugin route from "/:slug" to "/blog/:slug"
3. yarn develop
4. click to /blog/third => correct page
5. browse to /blog/notexist => empty page

Although a general control flow to 404 is the expected default behaviour, it may be more useful to have options inside the template page-query to allow the developer to catch the page-not-found error.

**Comment by sanscheese** [comment]
I am hitting this issue, with the `404.vue` setup in pages. 

404s are as expected for error paths, that have no template handler`/i-am-wrong/so-very-wrong/`.

However, if I have a Blog template setup to handle "/blob/:slug", then a non-valid blog path `/blog/does-not-exsist` will return a blank screen with the GraphQL error in the console.
