### ISSUE TITLE
Render html for markdown from external api 

### ISSUE THREAD

**Issue by milindsingh** [gridsome/gridsome#1412]
## Summary

I am using Strapi as cms for my blog articles. The `content` field contains markdown data in `articles` and is imported via graphql source in Gridsome.
I am using `VueMarkdown` component to render page query `content` data as HTML in my `article` pages.

```html
<vue-markdown v-bind:external-preview="true"
                  v-if="content"
                  :source="content"
                  id="content"/>
```

### Basic example

Can Gridsome plugin for render files into HTML pages be used here to render markdown from external API?

### Motivation

`VueMarkdown` is compatible with SSR but its getting re-rendered on page load replacing the SSR content. Will Gridsome Markdown renderer be able to solve this?

**Comment by thetre97** [comment]
@milindsingh You could use the Gridsome Remark transformer, then you will get the transformed HTML in your GraphQL queries, and therefore in your built HTML - See https://discord.com/channels/476372673564246017/519254857174089729/702097847163813928 for an example...

**Comment by thetre97** [comment]
@chiubaca If you do something similar to the above link, then users could use a Gridsome transformer which would parse the MD for them. In essence, you would need to add a `mimetype` to your content nodes, so the transformer knows what it needs to edit...
```js
{
	internal: {
		mimeType: 'text/markdown',
		content: node.markdown,
		origin: node.id
	}
}
```
Otherwise, you could just add your own MD parser, as you currently have.

**Comment by chiubaca** [comment]
Thanks for the info @thetre97. Cant seem to access to the discord link though.

**Comment by thetre97** [comment]
Ah sorry - see below ecerpt:

```js
module.exports = function (api, store) {

  api.onCreateNode((node, collection) => {
    if (node.internal.typeName === 'StrapiTutorial') {
      const markdownStore = collection._store.addCollection('StrapiMarkdown')

      const markdownNode = markdownStore.addNode({
		// any other fields, id, slug, title etc
        internal: {
          mimeType: 'text/markdown',
          content: node.content,
          origin: node.id
        }
      })

      node.content = collection._store.createReference(markdownNode)
    }
  })
}
```
that will create a faux collection with the markdown content transformed
then in your graphql query, you'd add:
```graphql
content {
    content
}
```
and lastly in your template:
`<div class="mb-10 markdown" v-html="$page.post.content.content"></div>`
```

**Comment by milindsingh** [comment]
Thanks @thetre97 I have updated my code with your suggested script and its working.

**Comment by thetre97** [comment]
Great - can this issue now be closed?

**Comment by milindsingh** [comment]
The problem which I was trying to solve didnt get resolved but @thetre97 you can close this issue.

https://github.com/gridsome/gridsome/issues/1408#issuecomment-784800398
