### ISSUE TITLE
Cannot add global SCSS variables.

### ISSUE THREAD

**Issue by onurusluca** [gridsome/gridsome#1417]
## Description

Using [this](https://gridsome.org/docs/assets-css/#import-a-global-style) method from official documentation but I can't still use global variables. I can use the SCSS file globally but can't import global variables.

### Steps to reproduce

Add these to your "gridsome.config.js".

`const path = require('path')

function addStyleResource (rule) {
  rule.use('style-resource')
    .loader('style-resources-loader')
    .options({
      patterns: [
        path.resolve(__dirname, './src/assets/sass/_globals.sass'),
        // or if you use scss
        path.resolve(__dirname, './src/assets/sass/_globals.scss'),
        // you can also use a glob if you'd prefer
        path.resolve(__dirname, './src/assets/sass/*.sass'),
        // or scss
        path.resolve(__dirname, './src/assets/sass/*.scss'),
      ],
    })
}

module.exports = {
  chainWebpack (config) {
    // Load variables for all vue-files
    const types = ['vue-modules', 'vue', 'normal-modules', 'normal']

    types.forEach(type => {
      addStyleResource(config.module.rule('sass').oneOf(type))
    })

    // or if you use scss
    types.forEach(type => {
      addStyleResource(config.module.rule('scss').oneOf(type))
    })
  }
}
`

### Expected result

This code should inject global variables but won't.

### Actual result

Cannot use global variables.

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Binaries:
    Node: 14.11.0 - C:\Program Files\nodejs\node.EXE     
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Chrome: master_preferences
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23

**Comment by bosbode** [comment]
Did you set the language to scss (lang="scss") in your style tag? That seemed to have fixed it for me.

**Comment by onurusluca** [comment]
@bosbode Thanks for the reply. Yes of course. However it is still same.

**Comment by cameronrr** [comment]
There seems to be an issue where sass-loader@11 is incompatible with Vue@2.6 (current version used by Gridsome). If you're using @11, uninstall sass-loader and instead downgrade to latest v10 `npm install sass-loader@^10.1.1`.
