### ISSUE TITLE
Source Request: Ghost

### ISSUE THREAD

**Issue by gottlike** [gridsome/gridsome#142]
## Summary

Ghost (https://github.com/TryGhost/Ghost) recently announced it can be used as a fully headless CMS and they even have a Gatsby starter + plugin: https://blog.ghost.org/jamstack/

Therefore it would be great to have a Ghost source plugin for Gridsome!

### Basic example

Ghost content API: https://docs.ghost.org/api/content/

Gatsby source: https://github.com/tryghost/gatsby-source-ghost

### Motivation

I very much like Ghost as a CMS, but I don't particularly like React - so Gridsome + Ghost would be great!

**Comment by technoSpino** [comment]
I think this can be closed

**Comment by gottlike** [comment]
You're right - thanks :)
