### ISSUE TITLE
Confusing error when creating a "Page" collection

### ISSUE THREAD

**Issue by TeNNoX** [gridsome/gridsome#1424]
## Description

I tried to create a `Page` collection, but got the error blow - and the only thing i found after a while of searching is this **[Japanese forum site](https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fqiita.com%2Fshumiyao%2Fitems%2F97b4892e351f2ed5319d)** telling me it's already an internal collection

### Steps to reproduce

1. add the collection:
```javascript
templates: {
  Page: '/:title',
},
```
2. Run `gridsome develop`

I think it's obvious, but I can make a repo if you want.

### Expected result

- it should work
- _or_ i should throw a clear error message.
- _and_ it should be mentioned in the docs

### Actual result
I got this error:
> Error: Cannot get field 'id' from type 'Page'. Field does not exist.

### Environment

Paste the information here as shown by `gridsome info`

```
  System:
    OS: Linux 5.8 Pop!_OS 20.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.20.1 - /tmp/yarn--1611241092687-0.4657089396725618/node
    Yarn: 1.22.5 - /tmp/yarn--1611241092687-0.4657089396725618/yarn
    npm: 6.14.10 - /usr/bin/npm
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.1 
    @gridsome/remark-prismjs: ^0.2.0 => 0.2.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4 
    gridsome: ^0.7.23 => 0.7.23 
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9 
    gridsome-plugin-tailwindcss: ^3.0.1 => 3.0.1
```

**Comment by NickSto** [comment]
Yeah I just ran into that myself. It took a bunch of troubleshooting before I realized `Page` must be an internally used name. It'd be great if there was an error message that let me know that right off the bat.

**Comment by noxify** [comment]
`Page` and `Node` are reserved type names in gridsome.

Reference: https://github.com/gridsome/gridsome/blob/f9cfa4b3a4c5156c55001320b8771504438df479/gridsome/lib/graphql/utils.js#L19

**Comment by TeNNoX** [comment]
@noxify Yeah thanks, but this issue is not about that. I have figured out the underlying issue.

Don't you care about developer experience?

No offense if you don't have time for these details, I can understand if that is the case. But otherwise... :tipping_hand_man:

**Comment by noxify** [comment]
You're right 🙈

Have seen just the keywords for `Page` and `does not work` in the next - not the error below.
Sorry for that.

**Comment by noxify** [comment]
> or i should throw a clear error message.

Alternative, we could print a warning and exclude the templates definition.
`throw` and `warn` could be added somewhere here:
https://github.com/gridsome/gridsome/blob/888317662d84995a2da622845b7c6bbe622d2254/gridsome/lib/plugins/TemplatesPlugin.js#L134

> and it should be mentioned in the docs
Where would you suggest the changes?

For both points - If you want, feel free to create a PR with a fix ✌️

**Comment by TeNNoX** [comment]
Yes! I like it!
I want to take responsibility for open source projects I use.

I put it on my to-do list for next week. Let's see what happens :p

**Comment by NickSto** [comment]
I'd lean toward throwing an error rather than warning and ignoring. Having an entire collection fail is a pretty big issue that probably needs an immediate fix. And if the error message is clear, it should be a straightforward fix.
