### ISSUE TITLE
Error on starting gridsome develop when using gridsome-plugin-robots

### ISSUE THREAD

**Issue by fmigliorato** [gridsome/gridsome#1436]
## Description

Hello, I just installed _gridsome-plugin-robots_ and configured It in _gridsome.config.js_ but unfortunately I get this error while start the development:

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

That's only happen when I use the env option. Below my config:

```
module.exports = {
  siteName: "My website",
  siteUrl: process.env.SITE_URL || 'https://www.example.com',
  plugins: [
    {
      resolve: "gridsome-plugin-robots",
      options: {
        host: null,
        sitemap: null,
        env: {
          development: {
            policy: [{ userAgent: "*", disallow: ["/"] }]
          },
          production: {
            policy: [{ userAgent: "*", allow: "/" }]
          }
        }
      }
    }
  ]
};
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

Start gridsome develop without any error

### Actual result

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### Environment

```System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE    
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD       
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.63)
  npmPackages:
    gridsome: ^0.7.23 => 0.7.23
    gridsome-plugin-robots: ^0.2.1 => 0.2.1```

**Comment by noxify** [comment]
It seems there is a typo in the package documentation.

Could you replace `resolve` with `use` ?

**Comment by noxify** [comment]
Ref: https://github.com/rkalkani/gridsome-plugin-robots/issues/7

**Comment by fmigliorato** [comment]
@

> It seems there is a typo in the package documentation.
> 
> Could you replace `resolve` with `use` ?

Perfect! Now it works, thank you :)
