### ISSUE TITLE
Blurry Images when using Netlify

### ISSUE THREAD

**Issue by dominikager** [gridsome/gridsome#1437]
## Description

I am getting blurry Images with gridsome on Netlify, when using netlify-forms.

I have this errors since i actived the gridsome cache on netlify, but i already removed this plugin... but didnt helped.

Thanks!

**Comment by hjvedvik** [comment]
Can you try what's described in this comment and see if it helps? https://github.com/gridsome/gridsome/issues/324#issuecomment-477185976

**Comment by dominikager** [comment]
@hjvedvik thanks a lot!
