### ISSUE TITLE
Safari does not prefetch pages linked with <g-link>

### ISSUE THREAD

**Issue by tanc** [gridsome/gridsome#144]
## Description

`<g-link>` component provides a way for the site to prefetch linked pages which speeds up navigation considerably. Unfortunately it seems that Safari on MacOS and Safari on iOS don't prefetch pages and therefore there is a delay when navigating around a site for the first time.

### Steps to reproduce

Open the network tab in Chrome devtools.
Visit the [gridsome.org](https://gridsome.org/docs/) docs page in Chrome.
Note that pages types and content are prefetched, these are js files named things like `component--blog-post.d08379fa.js` and `24.5f8a2c20.js`. There should be quite a few of them.
Scroll down the menu and observe in the network tab that the content files are loaded in without clicking on a link.

Open the network tab in Safari devtools.
Visit the [gridsome.org](https://gridsome.org/docs/) docs page in Safari
Note that pages types are not prefetched, there are only two js files starting with `component--`. There are only two content js files. Scrolling the menu does not load in any more files. 

### Expected result

The Chrome and Firefox behaviour is the expected one, prefetching should work.

### Actual result

Safari does not prefetch content from `<g-link>` components.

**Comment by hjvedvik** [comment]
Looks like Safari doesn't support `IntersectionObserver` which `g-link` uses to know if a link is within the view. We could include a polyfill, but it might be better to just wait for Safari to support it natively.

**Comment by tanc** [comment]
Looks like Safari Technology Preview has support for it so doesn't seem worth adding a polyfill.

I tried adding the polyfill in my project to add support in the short term by using this in `main.js`:

```
head.script.push({
  src: 'https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver',
})
```

The polyfill is added and loaded but doesn't seem to do anything. Is there some extra config for the polyfill for this particular project?

**Comment by tanc** [comment]
I just re-read my comment and I think I should clarify: As Safari TP includes IntersectionObserver support I don't think its worth adding a polyfill to Gridsome core. But it would be useful to be able to add a polyfill per-project if the developer wants to support Safari in the near-term.

**Comment by tanc** [comment]
This is now working with the commits on master. To use a polyfill for Safari you can make your `main.js` look something like:

```
import DefaultLayout from '~/layouts/Default.vue'

if (process.isClient) {
  require('intersection-observer')
}

export default function (Vue, { head }) {
 Vue.component('Layout', DefaultLayout)
}
```

And add the `intersection-observer` package: `yarn add intersection-observer`
