### ISSUE TITLE
Sass Loader not working

### ISSUE THREAD

**Issue by youcci** [gridsome/gridsome#1440]
## Description

Gridsome giving Error when importing Sass Stylesheets or using inline Sass

### Steps to reproduce

Installed npm install -D sass-loader node-sass like in the Docs and imported import '~/assets/scss/styles.scss' in main.js

### Expected result

Had hoped to load scss files normally and see my site being styled

### Actual result

 error  in ./src/assets/scss/styles.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Users\Youcef\Desktop\vue\youcci\node_modules\sass-loader\dist\index.js:25:24)

 @ ./src/assets/scss/styles.scss 4:14-293 14:3-18:5 15:22-301
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

### Environment

System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.63)
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23
    gridsome-plugin-sass-resources-loader: 0.0.3 => 0.0.3

**Comment by cameronrr** [comment]
sass-loader@11 is incompatible with Vue@2.6 (current version used by Gridsome). Instead you'll need to uninstall sass-loader and instead downgrade to latest v10 `npm install sass-loader@^10.1.1`

**Comment by DesignedByNino** [comment]
@cameronrr it's rather strange having to do this because there's no mention in the gridsome docs, but it worked wonders. Thank you.

**Comment by iampava** [comment]
Had the exact same error message but regarding React + Storybook. The solution above works! Thanks 👍

**Comment by rickalex21** [comment]
Here is what you need to do to get sass working.

I followed the instructions in the docs but I was still having problems and could not install node-sass. This is what worked for me:

1.  Don't use node-sass.
2. Don't use the '~' as mentioned in the docs for the import.
3. Do the following

```sh
gridsome create test-sass && cd test-sass
mkdir -p assets/sass
echo -e '$primary: red;\n\nbody{\ncolor:$primary;\n}' >assets/sass/styles.scss
npm install -D sass-loader@^10.1.1
npm install --dev sass
```

Add the import to src/main.js

```javascript
import DefaultLayout from '~/layouts/Default.vue'
import '/assets/sass/styles.scss'
export default function (Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)
}
```

Run ```gridsome develop``` and you should see the page with red font. 

Tested, works on a fresh install.

**Comment by scottlinddk** [comment]
> Here is what you need to do to get sass working.
> 
> I followed the instructions in the docs but I was still having problems and could not install node-sass. This is what worked for me:
> 
> 1. Don't use node-sass.
> 2. Don't use the '~' as mentioned in the docs for the import.
> 3. Do the following
> 
> ```shell
> gridsome create test-sass && cd test-sass
> mkdir -p assets/sass
> echo -e '$primary: red;\n\nbody{\ncolor:$primary;\n}' >assets/sass/styles.scss
> npm install -D sass-loader@^10.1.1
> npm install --dev sass
> ```
> 
> Add the import to src/main.js
> 
> ```js
> import DefaultLayout from '~/layouts/Default.vue'
> import '/assets/sass/styles.scss'
> export default function (Vue, { router, head, isClient }) {
>   // Set default layout as a global component
>   Vue.component('Layout', DefaultLayout)
> }
> ```
> 
> Run `gridsome develop` and you should see the page with red font.
> 
> Tested, works on a fresh install.

Just here to say a massive THANK YOU! Had an issue with using partials and your install guide solved it. Although it only worked when I used '~/assets/...' in main.js.

**Comment by itc-xovos** [comment]
> npm install -D sass-loader@^10.1.1

Thank you very much.
