### ISSUE TITLE
createPage path works for develop but not for build

### ISSUE THREAD

**Issue by jayanthbagare** [gridsome/gridsome#1444]
## Description

createPage works when I run gridsome develop, and it also displays the pages, however when I run build I get an error stating that it is not able to build the page.

### Steps to reproduce

My code is     
```
data.allStoryDetails.edges.forEach(({ node }) => {
        createPage({
          path: '/main/person/' + node.id ,
          component: "./src/templates/DetailsPage.vue",
          context: {
            id: node.id 
          }
        })
    })
  })
```

and the DetailsPage is
```
<template>
    <Layout>
        <div v-for="edge in $page.allStoryDetails.edges" :key="edge.node.id">
          <h2>{{ edge.node.title }}</h2>
          <b-carousel
            :id="edge.node.id"
            controls
            indicators
            img-width=500
            img-height=500
          >

            <span v-for="a in edge.node.coverPhotoWeb">
                <b-carousel-slide :img-src="getCarouselPhotos(a)"></b-carousel-slide>
            </span>
            </b-carousel>
          <h3>{{ edge.node.story }}</h3>
        </div>
    </Layout>
</template>

<page-query>
query ($id:ID!){
  allStoryDetails(filter:{id:{eq:$id}}){
    edges{
      node{
        id
        title
        story
        coverPhotoWeb{
          thumbnails{
            large{
              url
              width
              height
            }
          }
        }
        status
      }
    }
  }
}
</page-query>

<script>
export default {
  methods:{
    getCarouselPhotos:function(photos){
        return photos.thumbnails.large.url;
    }
  }
}
</script>

```
Paste the information here as shown by `gridsome info`
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.68)
  npmPackages:
    @gridsome/source-airtable: ^0.2.0 => 0.2.0
    gridsome: ^0.7.0 => 0.7.23
    gridsome-plugin-i18n: ^1.6.0 => 1.6.0

**Comment by thetre97** [comment]
What is the error thrown?
From what I can see, it appears as if you are using https://bootstrap-vue.org/docs/components/carousel, so it may be an error to do with SSR support for that component.

**Comment by jayanthbagare** [comment]
Thanks I've followed it up in bootstrapvue
