### ISSUE TITLE
template issue

### ISSUE THREAD

**Issue by peterpander** [gridsome/gridsome#1447]
## Description

When following official strapi-gridsome tutorial, trying to create new pages from ID numbers 

### Steps to reproduce

npm: '6.14.9',   
node: '14.14.0',
strapi '3.5.0'

### Expected result

http://localhost:8080/categories/1 
should show data from API but instead shows 404 page

### Actual result

When running gridsome develop...

ERROR  Failed to compile with 1 errors                                                
This dependency was not found:
..\my-gridsome-site\src\templates\Category.vue in ./src/.temp/routes.js

_**gridsome.server.js**_
```
module.exports = function (api) {
  api.loadSource(({ addCollection }) => {
    // Use the Data Store API here: https://gridsome.org/docs/data-store-api/
  })

  api.createPages(async ({ graphql, createPage }) => {
    const { data } = await graphql(`
      {
        allStrapiCategory {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    `);

    const categories = data.allStrapiCategory.edges;

    categories.forEach(category => {
      createPage({
        path: `/categories/${category.node.id}`,
        component: './src/templates/Category.vue',
        context: {
          id: category.node.id,
        },
      });
    });
  });
};
```

**_src\templates\category.vue_**
```
<template>
  <Layout>
    <div>
      <h1>{{ $page.category.name }}</h1>
      <ul>
        <li v-for="restaurant in $page.category.restaurants">{{ restaurant.name }}</li>
      </ul>
    </div>
  </Layout>
</template>

<page-query>
  query Category($id: ID!) {
      category: strapiCategory(id: $id) {
        name
        restaurants {
          id
          name
        }
      }
    }
</page-query>
```

**Comment by noxify** [comment]
Not sure if it's just a typo while describing the issue, but did you tried it with the same filename?

your file: `category.vue`

But in the `gridsome.server.js` you want to load `Category.vue`

**Comment by peterpander** [comment]
> Not sure if it's just a typo while describing the issue, but did you tried it with the same filename?
> 
> your file: `category.vue`
> 
> But in the `gridsome.server.js` you want to load `Category.vue`

Do you mean it should be category.vue instead of Category.vue?

**Comment by cameronrr** [comment]
The naming convention is for files to be named with an uppercase, so 'Category.vue' instead of 'category.vue'.

In gridsome.server.js you reference 'Category.vue' (uppercase first letter), and the error message says it cannot find that file. 

There's a good chance based on your component example, described as 'src\templates\category.vue' that you have the actual file as 'category.vue' instead of 'Category.vue' on the file system. Just have a check that the capitalisation of the filename matches.

**Comment by peterpander** [comment]
Thanks guys and well spotted you're both correct I named it category.vue - will try it tomorrow. Much appreciated :)

**Comment by noxify** [comment]
@peterpander is it now working?  If so, feel free to close the issue :)
