### ISSUE TITLE
Add a metatag to the head to stop Safari iOS from transforming numbers to links

### ISSUE THREAD

**Issue by tanc** [gridsome/gridsome#145]
## Summary

This was my original problem:

> I'm having a bit of trouble with iOS devices (and the Simulator in XCode) where the site loads, appears to hydrate properly, but clicking on links does not display the next page. In the web inspector I can see the next page's files get loaded in, they just don't update the display. All other browsers are fine and Safari for MacOS is also fine, its just Safari on iOS that appears to have trouble. There are no errors in console.

The issue was due to Safari iOS converting numbers it finds on the page (in my case a VAT number in the footer) to links prefixed with a `tel:`. This then caused hydration to break. The solution was to add a metatag:

```
export default function (Vue, { head }) {
  Vue.component('Layout', DefaultLayout)

  head.meta.push({
    name: 'format-detection',
    content: 'telephone=no'
  })
}
```

### Motivation

hjvedvik suggested it might be good to have this automatically added by gridsome to avoid this hard to diagnose error in the future. If the metatag could be removed/overridden then people could re-enable it if their site requires it.

**Comment by hjvedvik** [comment]
A fix was published in `0.4.6` :)
