### ISSUE TITLE
Migrating from SASS @import to @use & @forward

### ISSUE THREAD

**Issue by RehanSaeed** [gridsome/gridsome#1451]
## Description

When migrating the SASS from the deprecated `@import` statement to the new [`@use`](https://sass-lang.com/documentation/at-rules/use) and [`@forward`](https://sass-lang.com/documentation/at-rules/forward) statements, no CSS is output to a file at all and there is no link tag in the index.html file.

You can see an example of this migration not working in this PR: https://github.com/RehanSaeed/rehansaeed.github.io/pull/268.

### Steps to reproduce

Go to your `src/assets/index.scss` file which is imported in `main.js` with `import "~/assets/style/index.scss";` and instead of using `@import`, switch it to use `@use` and `@forward`.

### Expected result

CSS should be output as normal.

### Actual result

There is no CSS file after running a build and no link tag in the HTML.

### Environment

Paste the information here as shown by `gridsome info`

```
System:
    OS: Windows 10 10.0.21292
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Spartan (44.21292.1000.0), Chromium (88.0.705.74)
  npmPackages:
    @gridsome/plugin-critical: ^0.2.0 => 0.2.0
    @gridsome/plugin-google-analytics: ^0.1.2 => 0.1.2
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.23 => 0.7.23
    gridsome-plugin-brotli: ^0.1.3 => 0.1.3
    gridsome-plugin-flexsearch: ^1.0.5 => 1.0.5
    gridsome-plugin-pwa: ^0.0.18 => 0.0.18
    gridsome-plugin-remark-prismjs-all: ^0.3.5 => 0.3.5
    gridsome-plugin-robots: ^0.2.1 => 0.2.1
    gridsome-remark-embed-snippet: ^1.0.3 => 1.0.3
    gridsome-source-static-meta: ^1.0.1 => 1.0.1
```

**Comment by RehanSaeed** [comment]
The issue is described very well in this blog post: https://carterbancroft.com/sass-and-webpack/

The solution is to switch from using the node-sass NPM package to https://www.npmjs.com/package/sass instead. Once you do this, everything works again. This should be the new default.

**Comment by hjvedvik** [comment]
Thanks for finding a solution, @RehanSaeed. I see our docs [here](https://gridsome.org/docs/assets-css/#use-sass--css-pre-processors) are suggesting `node-sass`. But I just noticed that the `node-sass` package is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate). So we should probably update the docs :)

**Comment by kecrily** [comment]
This issue should be closed, as I have updated this section of the docs

https://github.com/gridsome/gridsome.org/commit/19695fd22c384630e27141f6dd64a7450d26d13c#diff-fdec52953e6fe8f7f51330dabed9be9891a38048b0e8e3e04c01f0088a4bb9be
