### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by nokhod** [gridsome/gridsome#1455]
## Description

I'm using some lit-element-based components in which they are heavily dependent on DOM API(document, window).
I import them in `src/main.js` cause they are repeated multiple times across components.
It is worthy to mention that the `gridsome develop` is fine.

### Steps to reproduce

importing components in `main.js`:

`import '@gabn/header-panel-business';`

### Expected result

Smooth build using `gridsome build`

### Actual result

Receiving build-time error:
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run build:prod --scripts-prepend-node-path=auto

> build:prod
> gridsome build

Gridsome v0.7.23

Initializing plugins...
Load sources - 0.28s
Create GraphQL schema - 0.13s
Create pages and templates - 0.06s
Generate temporary code - 0.03s
Bootstrap finish - 1.06s
10% building 8/19 modules 11 active .../gridsome/node_modules/cache-loader/dist/cjs.js??ref--1-0!/Users/gridsome/gridsome/node_modules/babel-loader/lib/index.js??ref--1-1!/Users/gridsome/src/.temp/plugins-server.js[Browserslist] Could not parse /Users/gridsome/package.json. Ignoring it.
Compile assets - 10.3s
Execute GraphQL (114 queries) - 0.16s
Could not generate HTML for "/tool/p7Ca6CL33RRBdIh5wcbQD/":
ReferenceError: window is not defined
    at Module.GMCd (node_modules/lit-html/lib/template-result.js:27:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.XI78 (node_modules/lit-html/lib/parts.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.wmha (node_modules/lit-html/lib/render.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.qcns (node_modules/lit-html/lib/shady-render.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.CQbg (node_modules/lit-element/lit-element.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)

Process finished with exit code 1
```

### Environment

production

**Comment by noxify** [comment]
Hey,

there are several issues with the same issue, here are some examples:

* https://github.com/gridsome/gridsome/issues/474
* https://github.com/gridsome/gridsome/issues/180
* https://github.com/gridsome/gridsome/issues/800

Also, please check the documentation https://gridsome.org/docs/assets-scripts/#without-ssr-support

**Comment by zgmrvn** [comment]
It happens because `window` doesn't exist when Server Side Generation renders the static HTML. You have to conditionnaly import your lib depending on weither it's the client of the server that's executing the script:
`const yourThing = process.isClient ? require('@gabn/header-panel-business') : undefinded`
And maybe use the [ClientOnly](https://gridsome.org/docs/assets-scripts/#without-ssr-support) component which prevents the SSG from rendering what's inside it.

**Comment by noxify** [comment]
I close this issue for now - feel free to reopen the issue.
