### ISSUE TITLE
Plugin request: Create an RSS feed (or multiple feeds)

### ISSUE THREAD

**Issue by flamby** [gridsome/gridsome#147]
## Summary

RSS/atom feeds for gridsome site.

### Basic example

Gatsby most famous feed plugin could be an inspiration : https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-feed

### Motivation

Feeds are important for blogs. Per category feeds would be a plus.

**Comment by darthmeme** [comment]
Hey @flamby! I actually had to implement RSS into Gridsome at work, and since there aren't any plugins for it, I decided to make one!

Check it out: https://github.com/darthmeme/gridsome-plugin-rss - it's not perfect, but I'd appreciate any feedback / suggestion 😄

**Comment by robaxelsen** [comment]
@darthmeme Awesome! Would you be up for trying to port this to a PR, as an official plugin?

**Comment by flamby** [comment]
Hi @darthmeme 

thank you very much. it works like a charm!

+1 for making it plugin-core ;-)

**Comment by flamby** [comment]
@darthmeme 
sorry for the question, i'm quite a newbie in vue.
I don't see how to change the output directory. e.g. dist/blog/rss.xml instead of dist/rss.xml

**Comment by darthmeme** [comment]
@robaxelsen Absolutely! I'd love to make it an official plugin! Is there anything I need to follow / change  while porting it over?

**Comment by darthmeme** [comment]
@flamby - I just pushed an update that adds an `output` option! [gridsome-plugin-rss#output](https://github.com/darthmeme/gridsome-plugin-rss#output)

**Comment by flamby** [comment]
@darthmeme thanks !

**Comment by tomtev** [comment]
Great plugin @darthmeme 😊🎉 It’s live on gridsome.org. I will close this now

**Comment by tomtev** [comment]
We might move this into core, but we’ll contact you when we do :)
