### ISSUE TITLE
Reduce blur

### ISSUE THREAD

**Issue by mishushakov** [gridsome/gridsome#1479]
I think the default `40px` blur of progressive images is too much
one can recognise gridsome websites just by looking at the amount of blur the images have when the page is loading compared to, let's say gatsby sites

maybe, consider reducing the amount of blur, so the images don't stick out so much?

**Comment by silasabbott** [comment]
You can adjust the amount of blur on each individual image using [the blur option shown in the docs](https://gridsome.org/docs/images/#options). I don't know if there's a way to set this globally though.

**Comment by mishushakov** [comment]
@silasabbott thanks a lot, but what i really meant to ask is if there is any way to enable it globally?

**Comment by hjvedvik** [comment]
@mishushakov @silasabbott You can set `images: { defaultBlur: 10 }` in `gridsome.config.js`. It's not documented yet, because we might move the image processor to a separate plugin. But it should be safe to use for now.

**Comment by mishushakov** [comment]
great, thanks!
