### ISSUE TITLE
Navigation is not working on some page for prod

### ISSUE THREAD

**Issue by devunion** [gridsome/gridsome#1481]
## Description

The problem exists on production version only. All is OK with dev version when I launch it locally.
Navigation links on some pages are not working. 

### Steps to reproduce

1. Go  to page https://pageoptimus.com/ru/articles/
2. Press 'English' link at the right top corder.

### Expected result
https://pageoptimus.com/articles page should be loaded

### Actual result
Nothing happens.

But for some reason it work on some other pages:

https://pageoptimus.com/ru/pages/politika-konfidenczialnosti

Ru->En switching works as it should.

Menu is implemented as *g-link*. No any other event handlers on the menu items. No exceptions in console.

### Environment
```
 System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
  Binaries:
    Node: 12.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.23 => 0.7.23
    gridsome-helper-json: ^1.0.3 => 1.0.3
    gridsome-plugin-flexsearch: ^1.0.5 => 1.0.5
    gridsome-plugin-gtag: ^0.1.10 => 0.1.10
    gridsome-plugin-i18n: ^1.6.0 => 1.6.0
    gridsome-plugin-remark-prismjs-all: ^0.3.5 => 0.3.5
    gridsome-plugin-robots-txt: ^1.0.2 => 1.0.2
    gridsome-plugin-tailwindcss: ^4.1.1 => 4.1.1
    gridsome-remark-figure-caption: ^1.1.3 => 1.1.3
    gridsome-source-static-meta: ^1.0.1 => 1.0.1
```

**Comment by noxify** [comment]
Hey @devunion 

i have seen your comment in #1205 .

I checked the HTML code ( since this was the rootcause in the other issue ), but it seems that it's not the problem.

I have seen that you're using `gridsome-plugin-i18n` - Do you use the available functionality from the plugin to rewrite the routes etc.?

It would be good if you could provide some more information, if you're using it and how.

**Comment by devunion** [comment]
@noxify, thank you for the update. I've debugged my template and found the problem. It was related to localization. `gridsome-plugin-i18n` does not work with Markdown/GraphQL content. So, it was necessary to add some hacks to make it work. And one of them caused the problem.

As for template, I'm trying to get 100 / 100 with Google Page Speed, The last one critical problem is related to `g-image`:

![image](https://user-images.githubusercontent.com/1061496/115694041-2a35e200-a369-11eb-86e0-e75305471101.png)

The code is simple:
```
        <g-image
            src="~/assets/images/page-optimus-logo-dark.png"
            :alt="$t('header.logo_alt')"
            width="198"
            height="31"/>
```

Do you have an idea how to troubleshoot this problem? In this particular case I'll replace `g-image` with standard `IMG` tag and use SVG version for the logo. But what about the fix which will work in the other cases?

P.S. Is there some official community? It will be nice to have some place to discuss a such questions.

**Comment by noxify** [comment]
> P.S. Is there some official community? It will be nice to have some place to discuss a such questions.

There is a discord channel - Just click the discord icon ( in the top nav ) at https://gridsome.org/

> Do you have an idea how to troubleshoot this problem? In this particular case I'll replace g-image with standard IMG tag and use SVG version for the logo. But what about the fix which will work in the other cases?

Unfortunately I can't help you - Maybe using a `img` tag is a good workaround.

---

I close this issue for now, since the main problem is solved :)
