### ISSUE TITLE
Can source-filesystem plugin use directory structure to infer extra node fields?

### ISSUE THREAD

**Issue by yacoob** [gridsome/gridsome#1526]
I plan to use gridsome to generate pages from data like [this](https://github.com/yacoob/gcu/blob/72f1285bd25d9c6aae93b27fd32dd561322f7b14/kits/hg/ahead-smultron.yaml). If you look at the whole [dataset](https://github.com/yacoob/gcu/tree/72f1285bd25d9c6aae93b27fd32dd561322f7b14/kits) and compare it with the [resulting site](https://gcu.tactical-grace.net/hg/ahead-smultron/), you can see that there's one extra field, called `grade` inferred from the name of the directory in which the file is residing. Is there a way to get `source-filesystem` plugin to parse that automatically into a field? 

Failing that, is there any way to pre/post process loaded data? I'd prefer to avoid having a copy of `source-filesystem` plugin with three extra lines added :)

Thanks for any suggestions!

**Comment by NickSto** [comment]
I'm not sure if `source-filesystem` can do it but I use the Server API's [`onCreateNode()`](https://gridsome.org/docs/server-api/#apioncreatenodefn) hook to add a field to my nodes based on the directory of the file. You might have to add the fields first with [`addSchemaTypes()`](https://gridsome.org/docs/schema-api/#addschematypestypes).

Feel free to look at [how I do it](https://github.com/NickSto/gridhub/blob/fab4abd1a93797478a83b4cbc55fa0669efb4f39/gridsome.server.js#L196), though unfortunately it's in the middle of a lot of other abstractions and node alteration. The heart is [here](https://github.com/NickSto/gridhub/blob/fab4abd1a93797478a83b4cbc55fa0669efb4f39/gridsome.server.js#L161) where I define the `category` field based on the `node.path`.

**Comment by yacoob** [comment]
Thanks, that looks reasonable :> I've also rooted around in what's available via graphql, and realised that with my files laid out in a single subdirectory hierarchy `fileInfo.directory` gives me exactly what I need.
