### ISSUE TITLE
Is Gridsome at the end of its journey ?

### ISSUE THREAD

**Issue by matt88120** [gridsome/gridsome#1531]
The question is in the title.

**Comment by sanscheese** [comment]
Whilst it's been a while between major releases, the core maintainers have still been working towards a next release. @tomtev and @hjvedvik have [commented](https://github.com/gridsome/gridsome/issues/1459#issuecomment-797146289) that a big part of their focus of late has been on their visual editor for Gridsome/Vue sites. However, they are still giving time to Gridsome where they can.

For example @hjvedvik recently worked on the [PR for webpack 5](https://github.com/gridsome/gridsome/pull/1523)

Can keep an eye on the issue for [Vue 3 support](https://github.com/gridsome/gridsome/issues/1289) as updates are made there.

The ['in progress' section of the roadmap roadmap](https://github.com/gridsome/gridsome/projects/2#column-5408217) can also give some idea on the current focus of the core dev work.

Being open source and relying on free time of the maintainers, it's not possible to say when a next release will be ready. It's a matter of patience. And PRs are always welcome, if able lend a hand 😁

**Comment by matt88120** [comment]
Glad to read that !

**Comment by pushand** [comment]
Was Glad to hear a similar statement a year ago. Moved on to Nuxt Jamstack It's not we can't wait for it it's about contributors who neither say yes nor no about progress

**Comment by vsirghii** [comment]
The Gridsome@latest (0.7.23) has some vulnerabilities (moderate and critical) due to its dependencies (see please issue #1547 ). 
I wonder how well and how often Gridsome is reviewed by its team in terms of being at least up to date if not new features?
I was pretty impressed in my past projects with how Gridsome works. Now I'm seriously looking for more repayable alternatives, like NUXT...

**Comment by matt88120** [comment]
I have finally learned Gatsby and use it instead of Gridsome.
