### ISSUE TITLE
Change gridsome's requirement for node versions from 8.x to 12.x

### ISSUE THREAD

**Issue by kecrily** [gridsome/gridsome#1546]
## Summary

Change gridsome's requirement for node versions from 8.x to 12.x.

https://github.com/gridsome/gridsome/blob/9b77f76057b9f3d343fb732fae4c9bf0b6b71657/package.json#L33

### Motivation

Node 8.x reached its stated end point back on 2019-12-31. This happened more than a year ago. Its successor, 10.x, also ended its life four months ago (2021-04-30).

Gridsome is still stuck at 8.x. Providing support for versions of node that are no longer maintained is a heavy burden, and gridsome should not try to support older node LTS versions.

Always follow the oldest LTS that is still under maintenance is the best choice. Now let's go to 12.x

**Comment by ThomOrlo** [comment]
Done 👍
https://github.com/gridsome/gridsome/commit/10c5ac1eef96e6c7f62f5be86dbf468a21d7d043
