### ISSUE TITLE
How do we leverage Gatsby?

### ISSUE THREAD

**Issue by dubcanada** [gridsome/gridsome#155]
## Summary

GatsbyJS is obviously where the idea came from, and largely the biggest different is react vs vue. So how do we take what GatsbyJS has done and leverage the open source components, so this project doesn't end up reinventing the wheel and die out because GatsbyJS is a larger ecosystem?

Is there possibility to build parts of the plugin system, or cache system where plugins from GatsbyJS could be used? Or leverage parts of the core of GatsbyJS so some consistency can be allowed?

### Basic example

A few things come to mind

- Plugin System
- Cache System

### Motivation

I really enjoy Gridsome and I love vue, but I understand that React is a much larger community and the Gatsby community is large. I don't see any reason why we should be reinventing the entire system when Gridsome could borrow parts of Gatsby to allow some level of interchangeability. For example if we could find some way to use Gatsby plugins, that means Gridsome now has access to every Gatsby plugin, and a plugin built for one can be used on the other.

Thoughts?

**Comment by josepjaume** [comment]
Maybe being able to use `source` or `transformer` plugins interchangeably could be a good idea?

**Comment by yann-yinn** [comment]
> So this project doesn't end up reinventing the wheel and die out because GatsbyJS is a larger ecosystem

I see no reason why this project would die because of Gatsby : Vue.js and React are two different communities. Take a look at Nuxt.js and Next.js, both solutions exists and are great, on very similar problematics.

**Comment by dubcanada** [comment]
I don't doubt they can both coexist, but wouldn't it be great if Gridsome could use some Gatsby plugins? And vice versa?

If source plugins worked for both systems, since there is no React specific components at that stage, Gridsome goes from having a few integrations to every single one Gatsby has.

**Comment by yann-yinn** [comment]
Yep, i agree that, theorically, some kind of agnostic data fetcher and plugins system usable by all JS  JAMStack solutions like Gridsome, Nuxt and Gatsby would be sexy. But I guess this might not as easy as it sounds, because plugin system might also be tightly tied to a more high level features ... So maybe this is re-inventing the wheel, but maybe this is sane concurrency to move faster to new features that Gatsby or Nuxt can't have ?

**Comment by tomtev** [comment]
I will close this for now. They are very different under the hood, so I don't see any simple solution for this 😅
