### ISSUE TITLE
Gridsome site not displaying HTML content after build and deployment

### ISSUE THREAD

**Issue by DRD161** [gridsome/gridsome#1554]
I am currently working on a static site that is being deployed to Netlify. After building and deploying the site none of the content is displayed but the style sheet is present. This is my first time using Gridsome so it's probably user error. I have also tried uploading the static files to another hosting provider and got the same result which leads me to believe it's a problem on my end. I get no errors when running the build both locally and on Netlify.

**Environment:**
OS - MacOS Catalina 10.15.7
Browser(s) - Firefox & Chrome
IDE - Webstorm 2021.2.1

**Site URL:**
https://reverent-nobel-6d466a.netlify.app/

**Git repo:**
https://github.com/DRD161/Gridsome-Portfolio

**Build output:**
```
Gridsome v0.7.23

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.02s
Create pages and templates - 0.02s
Generate temporary code - 0.01s
Bootstrap finish - 1.28s
Compile assets - 9s
Execute GraphQL (2 queries) - 0s
Render HTML (2 files) - 0.22s
Process files (0 files) - 0s
Process images (0 images) - 0.2s


  Done in 11.35s
```

**package.json:**
```
{
  "name": "my-website",
  "private": true,
  "scripts": {
    "develop": "gridsome develop",
    "explore": "gridsome explore",
    "build": "gridsome build"
  },
  "dependencies": {
    "@chakra-ui/vue": "^0.8.0",
    "emotion": "^11.0.0",
    "gridsome": "^0.7.0",
    "vue-animejs": "^2.1.1",
    "vue-feather-icons": "^5.1.0"
  },
  "devDependencies": {
    "@emotion/css": "^11.1.3",
    "chakra-loader": "^1.0.3",
    "node-sass": "^6.0.0",
    "sass-loader": "^10.2.0",
    "vue-svg-loader": "^0.16.0"
  }
}
```

**Comment by cameronrr** [comment]
I haven't tested, but just an idea. What happens if you change the root node in App.vue from `<ClientOnly>` to something else like a plain div, then nest client only inside that? It looks like there is no container for the app to mount to on client-side after SSR.

**Comment by DRD161** [comment]
I found that my problem was in fact the way I was using <ClientOnly>. I had initially wrapped my whole Index.vue file in it and that was causing the build to go through but not allowing the content to render. Instead I moved <ClientOnly> to the Layout.vue file.
