### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by lohnsonok** [gridsome/gridsome#1560]
## Description

The website that i develop is passed in production in editable version (all the contents of the site, the pages etc) on contentful, when I start in local all happens no error is present in the console but in setting in production I obtain this error: 

And the rich text in rendering mode with the contentful [rich-text-html-renderer extension](https://www.npmjs.com/package/@contentful/rich-text-html-renderer) are duplicated

Please note that i get this error in Console : `DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

### Steps to reproduce

1. convert page to editable contenful content
2. use rich-text-html-renderer for rich Text
3. build

### Expected result

All should work properly such as local development

### Actual result

Getting error in console with duplicate content rendering

### Environment

  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
  Binaries:
    Node: 14.17.6 - /tmp/yarn--1631800088484-0.4508437553079223/node
    Yarn: 1.22.11 - /tmp/yarn--1631800088484-0.4508437553079223/yarn
    npm: 7.23.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 92.0
  npmPackages:
    @gridsome/plugin-critical: ^0.2.0 => 0.2.0 
    @gridsome/plugin-google-analytics: ^0.1.2 => 0.1.2 
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0 
    @gridsome/remark-prismjs: ^0.5.0 => 0.5.0 
    @gridsome/source-contentful: ^0.6.0 => 0.6.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4 
    @gridsome/vue-remark: ^0.2.6 => 0.2.6 
    gridsome: ^0.7.23 => 0.7.23 
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1 
    gridsome-plugin-remark-youtube: ^1.0.1 => 1.0.1 
    gridsome-plugin-robots-txt: ^1.0.2 => 1.0.2 
    gridsome-plugin-tailwindcss: ^4.1.1 => 4.1.1

**Comment by AllanChain** [comment]
Have you checked #249?

**Comment by lohnsonok** [comment]
> Have you checked #249?

Thank you. This [comment](https://github.com/gridsome/gridsome/issues/249#issuecomment-625539828) solve my problem
