### ISSUE TITLE
Images stuck in lazy loading state when linked from markdown

### ISSUE THREAD

**Issue by mansour-ahmed** [gridsome/gridsome#158]
## Description

Images stay in the loading state even when it is in the viewport. This happen only to the images loaded through markdown. It occurs on both the production builds and locally. 

When I save a change in my local environment the image load correctly but if I refresh the browser it again gets stuck on the progressive loading state.

I wonder if the image format would have any effect? Also am I using the correct syntax here?

### Steps to reproduce
inside a loaded markdown file and add the following to the content:
```  ![Image description.](./image.png "Image's title")```

the file image.png is found within the same directory as the markdown file.

e.g. `content/posts/article1.md` && `content/posts/image.png`

### Expected result

The added image should be loaded correctly when it is in the view port.

### Actual result

The image stays blurry in progressive loading state.

**Comment by hjvedvik** [comment]
Does this happen in all browsers? And do you see any errors in the terminal?

**Comment by mansour-ahmed** [comment]
Hey man, thanks for responding quickly.

I figured out the issue after all, it turn out that I had a bit of an issue how I am handling the `v-app` component from `vuetify`.

I had a problem earlier with building the project and as a work around I added the loading flag to my layout component. Turns out that workaround was breaking the images being lazy loaded.

if I add this line https://github.com/mansour-ahmed/gridsome-lazy-loading-images/blob/77f701a96e7b0e2a949ebad5841c32f0fb0bf7df/src/layouts/Default.vue#L30
and comment out the `$nextTick` callback it actually works as expected.

Just thought to share in case it might be helpful.

Otherwise good work with maintaining Gridsome, been working really well! 👍

**Comment by mansour-ahmed** [comment]
I still have the issue after all, now I moved my `loading` flag to be set to `false` on the life cycle `mounted` and not `created`, the images now are not fully loading only on the initial load and if I navigate away and come back then images start working normally again. 

I am guessing the way the component g-image works depending on the cycle mounted and me adding my workaround `loading` flag have some conflicts.

Would you have any ideas how to go around this?

**Comment by hjvedvik** [comment]
Does it happen in all browsers? I know there have been problems with something similar in Safari. I can try to debug this later today.

**Comment by mansour-ahmed** [comment]
yes it occurs on all browsers, tested on safari, firefox and chrome. Awesome! 👍 

I am quite certain it it has something to do with me setting the `loading` flag in the `mounted` flag. Removing it resolves the issue but then I run into other issues on the production built version.
