### ISSUE TITLE
Images are stretched using current git version

### ISSUE THREAD

**Issue by oripka** [gridsome/gridsome#1581]
## Description

For developing on Apple Silicon I created a git repository that takes the current Gridsome repository and makes installable using this entry in the packages.json `gridsome": "git+https://github.com/oripka/gridsomemain.git",`

The main reason for this is that the currently released version 0.7.23 does not work on Apple Silicon because the old version entry for "sharp". The git version works, BUT images are stretched and not displayed in the proper ratio.

I think it is because of this commit https://github.com/gridsome/gridsome/commit/71f41848a5fb53d180513118a662aeef6344e436

I didn't want to deep dive into the code so I just reverted these commits and included them in the repository mentioned above.

Somebody more familiar with the code should be able to come up with a proper fix.

### Steps to reproduce

This should be reproducible with the current git version of Gridsome and the https://github.com/gridsome/gridsome.org repository as example project.

### Expected result

Images should be in the proper ratio.

### Actual result

Images are stretched

**Comment by hjvedvik** [comment]
@oripka  I noticed the same on gridsome.org when I was working on the next version. The solution was to add `img { height: auto; }` to the CSS. The height attribute was added because it is recommended for preventing layout shifts etc.

**Comment by oripka** [comment]
This works, thanks for the quick response.
