### ISSUE TITLE
Gridsome site not deploying to Zeit

### ISSUE THREAD

**Issue by YogliB** [gridsome/gridsome#159]
## Description
Build failing on Zeit.
[Logs](https://zeit.co/yogli_b/yogevbb/deployment/kdc976el7/logs)

### Steps to reproduce
1. Clone the [git repo](https://github.com/YogliB/yogevbb.com)
2. run ```npm i```
3. run now

### Expected result
Successful build

### Actual result
Build failing.

### More info
https://spectrum.chat/?t=896c0f96-18cb-4acc-b1e3-d036665a0ff6

**Comment by hjvedvik** [comment]
Looks like it fails when the image processing starts. We can probably use`imagemin-mozjpeg` instead of `imagemin-jpegoptim` if it's that package that causes problems. I see that the Gatsby Sharp plugin uses `imagemin-mozjpeg` too and that plugin works for you?

**Comment by YogliB** [comment]
@hjvedvik When I try to build and serve the site locally it works fine, if that's what you're asking.

**Comment by blubMe** [comment]
try to add this to the scripts on package.json 

```json
"now-build": "yarn build"
```

and add now.json also
```json
{
  "name": "your-app",
  "version": 2,
  "builds": [
    { "src": "package.json", "use": "@now/static-build" }
  ]
}

```

**Comment by YogliB** [comment]
@blubMe Already did that...
I just decided to use Netlify, it's simpler.

**Comment by blubMe** [comment]
@YogliB yeah same, it's easier to deploy on Netlify.

**Comment by tomtev** [comment]
Does this work with 0.5.0 ? We changed to `imagemin-mozjpeg`

**Comment by YogliB** [comment]
@tomtev Works like a charm :)
