### ISSUE TITLE
Gridsome not properly installing on Mac M1 Monterey due to an old version of sharp

### ISSUE THREAD

**Issue by moritzlaube** [gridsome/gridsome#1596]
## Description

I am trying to npm install my repo that worked perfectly fine before on my Mac M1. But on the M1 an error is thrown.

### Steps to reproduce

Install Gridsome on a Mac M1 with Monterey OS

### Expected result

It should install without any problems

### Actual result

The terminal throws the following error:

```
npm ERR! code 1
npm ERR! path /Users/moritzlaube/Projekte/crossinx/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
```
The problem is actually with Sharp as discussed in this thread: https://github.com/lovell/sharp/issues/2460

At the very bottom the sharp developer says:

> Please can everyone using Apple M1 devices upgrade to sharp v0.28.0, which removes the need to install/compile things via Homebrew.
> Even better, please can you open PRs to update any downstream packages (such as cordova-res) that are still using older versions.
> https://sharp.pixelplumbing.com/install#apple-m1
> I'm going to lock this issue now. If you're still having problems, please open a new installation issue and answer all of the questions.

Would you be able to update the sharp dependency to make Gridsome work on M1? Or do you have a different work-around? Thanks!

**Comment by stfnnklc** [comment]
Same issue here! I followed the instructions found here lovell/sharp#2460 , but none of those worked for me.

**Comment by moritzlaube** [comment]
I cloned the gridsome repo and you are actually using sharp 0.29.3. But for some reason, when installing gridsome via npm, it tries to install sharp 0.25.4 and throws the following error message:

```
> fsevents@1.2.13 install /Users/moritzlaube/Projekte/crossinx/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> sharp@0.25.4 install /Users/moritzlaube/Projekte/crossinx/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-arm64v8.tar.gz
ERR! sharp Prebuilt libvips 8.9.1 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:23:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/moritzlaube/.nvm/versions/node/v14.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.2.0
gyp ERR! command "/Users/moritzlaube/.nvm/versions/node/v14.18.2/bin/node" "/Users/moritzlaube/.nvm/versions/node/v14.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/moritzlaube/Projekte/crossinx/node_modules/sharp
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.25.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/moritzlaube/.npm/_logs/2021-12-23T13_35_37_633Z-debug.log
````

I symlinked the gridsome repo to my project and the same is happening.

**Comment by moritzlaube** [comment]
Anyone with an idea why it's not working?

**Comment by Marco-Pagani** [comment]
I've been following the M1 build issues for a few months on and off. If you haven't already, I suggest you check out some of the previous issues where people have suggested solutions that worked for them (sometimes). #1503, #1519 and #1555 have some useful suggestions, although I spent a couple hours trying things with no luck personally.

That being said this has been an ongoing issue for quite awhile and I haven't seen any dev input anywhere. I'm waiting for a fix for this and the upgrade to Vue3 (#1289) but haven't seen any movement there either, so don't hold your breath. Considering moving my small project to nuxt...

Hopefully this helps someone with this issue at least! If any of these solutions work for you please share what you did 🙂

**Comment by moritzlaube** [comment]
Thanks for that. Yeah, I've seen those issues but they haven't worked for me. I experimented a little bit with running everything in a Docker container but didn't succeed. Unfortunately, converting over to Nuxt would be quite some effort, since I am running a bigger website entirely on Gridsome...

**Comment by Marco-Pagani** [comment]
Of course, telling you to use a different tool isn't exactly a solution and I wouldn't seriously suggest it to anyone. Unfortunately none of the above solutions worked for me either, so I'm stuck in a holding pattern if I want to use my new machine for development.

I would like to correct myself though, there has been a commit addressing the issue (d2beec0) that wasn't there last time I tried to build. If I have some success now I'll be sure to update you with my results, best of luck.

**Comment by matthewmorek** [comment]
@moritzlaube This isn't an issue with Gridsome, but with the underlying libraries that despite receiving apropriate build for M1 still cause issues. I have had similar problems back in the summer after receiving a brand new MacBook Pro with M1, but I solved it by manually installing defective libs (in this case `sharp`) via Homebrew.

Gatsby was one of many project affected by this and they solve this with the following routine:

```shell
$ xcode-select --install
$ brew install gcc
$ brew reinstall vips
$ brew info vips
$ yarn install # or npm i
```

Provided this fails, try removing `vips` and then `sharp` should download pre-built library. Back then I had to rebuild vips and sharp from source to make it work and haven't had issues since.

Ref: https://github.com/gatsbyjs/gatsby/discussions/29891

**Comment by stfnnklc** [comment]
@matthewmorek Your solution works for me when starting a new Gridsome project, but for some reason it doesn't work on my old project. I copied sharp folder from the new node_modules to the old node_modules and the old project now works as well. 

Thanks!

**Comment by matthewmorek** [comment]
@moritzlaube Awesome! Could you please close this issue then? Hopefully it'll be a good reference for future issues related to `sharp` or `vips`.

**Comment by mattaningram** [comment]
@matthewmorek This is a problem with Gridsome though, the currently released version uses an old version of Sharp that does not work on M1 Macs. Newer Gridsome code uses a more recent version of Sharp that should work fine, but has not been released by Gridsome yet.

Many people who are just trying to get into website development with tools like Gridsome aren't going to want or know how to go through all the listed fixes when a simple `package.json` update would fix it.

**Comment by adamlogic** [comment]
FWIW, my workaround was to use Yarn's [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force a newer version of Sharp:

```json
  "resolutions": {
    "gridsome/sharp": "0.29.3"
  }
```

Take it with a grain of salt, though, because my initial error was a bit different. I could *install* Gridsome (and Sharp) no problem, but building the site would fail with the following error:

```
Error: Failed to process image src/images/why-rails-autoscale.gif. Input buffer contains unsupported image format
    at ImageProcessQueue.preProcess (/Users/adam/src/rails-autoscale-static/node_modules/gridsome/lib/app/queue/ImageProcessQueue.js:81:13)
...
```

This was happening for any GIF file, and only GIF files. Forcing the new version of Sharp fixed it. 🤷‍♂️

**Comment by moritzlaube** [comment]
@adamlogic Awesome! Your approach worked for me! In fact, all the time I was looking for that "resolutions" functionality that yarn offers And I haven't been able to find it. It is so handy! Thanks!

**Comment by mattaningram** [comment]
@adamlogic Thank you! This worked for me without any issues.

**Comment by mgd722** [comment]
following @adamlogic 's approach, but using npm you add the following to `package.json`:
```
"overrides": {
  "gridsome": {
    "sharp": "0.29.3"
  }
}
```
**NOTE: you must use npm v8.3.0 or higher to have access to the [overrides feature](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).**

doing this i was able to get everything to build, but get an openssl error when running `gridsome develop`. i am pretty sure that's due to some unrelated M1 shit.
