### ISSUE TITLE
User authentication, form submission and GraphQL subscriptions

### ISSUE THREAD

**Issue by lewebsimple** [gridsome/gridsome#16]
Nice project! Are there any plans for supporting user authentication, form submissions or real-time updates via GraphQL subscriptions?

**Comment by tomtev** [comment]
Hi @lewebsimple. Thank you! The internal GraphQL layer is only used in development mode and for generating static content at build time. So it's not used in production. You would need something like Vue Apollo or serverless functions to talk to external services in production.

We do have a plan to have some kind of service that let you run the internal GraphQL database on a Node.js server with real-time updates.

**Comment by dannybrown73** [comment]
This is a sweet project! 

A potential solution for user auth is to host your project on a service like Netlify  (not affiliated and won't link but a good example) that specialize in hosting static websites but offer dynamic apps. Sites will still be super fast thanks to gridsome.

**Comment by sureshvv** [comment]
Netlify charges $45 per month for password protected sites. That is quite steep for a hobby project.

**Comment by TiborUdvari** [comment]
Can't you host your own instance though?

**Comment by sureshvv** [comment]
Yes. I am doing that. But a plugin may be nice.
