### ISSUE TITLE
<static-query> gets cached inside node_modules/gridsome/node_modules/.cache

### ISSUE THREAD

**Issue by crsten** [gridsome/gridsome#160]
## Description

Static Queries are getting cached inside node_modules/gridsome/node_modules/.cache which can lead to false builds

### Steps to reproduce

1. Create component
2. Use static-query to fetch collection of items (i used contentful)
3. run "npm run build"
4. Change content (i used contentful)
5. run "npm run build" 

### Expected result

static-queries should not be cached

### Actual result

static-query contained old data which lead to falsy build output. page-query is not cached and works as expected

**Comment by hjvedvik** [comment]
Just published a fix for this in `0.4.6` :)
