### ISSUE TITLE
How to insert script just after the <head> tag?

### ISSUE THREAD

**Issue by ligne13** [gridsome/gridsome#1605]
Hi,

I need to insert a <script> tag just after the <head> tag ? I tried using head.script.push but it is inserted at the end of the <head> tag.

Thanks.

**Comment by hjvedvik** [comment]
You can look into how to override the HTML that Gridsome uses [here](https://gridsome.org/docs/overriding-index/). It should let you insert your `<script>` tag where you want it.

**Comment by ligne13** [comment]
Awesome ! thanks @hjvedvik
