### ISSUE TITLE
Internal links break on build

### ISSUE THREAD

**Issue by petethompson** [gridsome/gridsome#161]
## Description

I'm experimenting with gridsome-wordpress, and including data sources for another API. In the development environment, all of the links work. 

1) When I run gridsome build, there are no errors reported, and the build is successful, but none of the routes work from a click event. The address bar changes but the view stays.

2) Other strange behavior: If I include data in the template, from the graphql query, outside of a v-for loop on these pages, everything works fine in the dev environment. But, if I run the build command, it breaks the entire layout and puts elements in the wrong place.

It's unclear if these two things are related. It's also unclear if this is due to a bug or if it's user error.

### Steps to reproduce

You can view the experiment in its current state here:
https://submariner-rabbit-77726.netlify.com
Issue 1 (links breaking) can be seen there.

The repo is here:
https://github.com/petethompson/quougue-gallery-vuejs

Issue 2 (layout breaking) occurs if I include $page data, for instance, the page title or content, outside of the v-for loop on the Index.vue or Artist.vue file.

**Comment by hjvedvik** [comment]
I think something goes wrong in your `main.js`. It can be something in the scripts you import that doesn't work well in server-side rendering. So the `Layout` component doesn't get registered which causes the app to fail in the browser. I'll publish a fix in a few hours which will give you much better error messages to help debug this kind of issues.

**Comment by petethompson** [comment]
@hjvedvik Thanks! I see - that makes sense. 

I removed the scripts from main.js. I'm including them in the components and pages instead, and the build process is no longer breaking the layout. 

Error messaging for this situation will be very helpful. Thanks again.
