### ISSUE TITLE
Gridsome on Mac M1, upgrade sharp please

### ISSUE THREAD

**Issue by positivecrash** [gridsome/gridsome#1651]
I'm trying to install node packages within existing Gridsome projects on my Mac M1 (they work on other machines).

It says 
`Failed at the sharp@0.25.4 install script`

---

If I write in package.json:
```
"overrides": {
    "gridsome": {
      "sharp": "^0.30.7"
    }
 }
```

I get this error when Gridsome develop run
```
Gridsome v0.7.23

Initializing plugins...
Error: 

Vue packages version mismatch:

- vue@2.6.14
- vue-template-compiler@2.7.10
```

---

I tried every solution suggested from previous issues, nothing helped

**Comment by bauhem** [comment]
Hi, here is my DockerFile content that work with Docker on my Mac M1 using : docker-compose run --rm gridsome yarn install

----

`FROM node:16-bullseye-slim AS development

ARG DOCKER_UID=-1

ARG DOCKER_GID=-1

RUN set -eu; \
  if [ "$DOCKER_UID" -gt -1 ]; then \
    usermod -u "$DOCKER_UID" node; \
    groupmod -g "$DOCKER_GID" node; \
    mkdir -p /home/node/.npm; \
    chown -R node:node /home/node; \
  fi;
COPY --chown=node:node  . .
ENV PATH=$PATH:./node_modules/.bin

WORKDIR /app
USER node
RUN yarn global add @gridsome/cli sharp@^0.28.0
RUN echo "export PATH=${PATH}:`yarn global bin`" >> /home/node/.bashrc
`

**Comment by nobilix** [comment]
Following, the sharp version should be updated.


> ```
> "overrides": {
>     "gridsome": {
>       "sharp": "^0.30.7"
>     }
>  }
> ```

Worked for me though

**Comment by positivecrash** [comment]
Thanks for your feedback!

> Following, the sharp version should be updated.
> 
> > ```
> > "overrides": {
> >     "gridsome": {
> >       "sharp": "^0.30.7"
> >     }
> >  }
> > ```
> 
> Worked for me though

I tried one more time, thought this should work for me also. And it worked after removing vips and reinstalling node:

```
brew remove vips
nvm uninstall 17
nvm install 17
nvm use 17
rm -rf node_modules
npm i
```

But still looking forward to the update with sharp version and Vue 3 also ))

**Comment by nobilix** [comment]
@positivecrash glad it's fixed for you. However, I guess it'd be better to leave this ticket open until the sharp version is not updated. Basically, it's a low-hanging fruit to fix that, and before that's done Apple Silicon users will have hard times installing Gridsome.
