### ISSUE TITLE
Remark Transformer Auto Link Class Name

### ISSUE THREAD

**Issue by danvega** [gridsome/gridsome#166]
## Description

I create a new blog post and I have some blank spaces next to my h2 headings. This is because that class that gets inserted there is 

`<span class="icon icon-link"></span>`

To fix this I noticed that I should be able to override that style in the configuration. 

### Steps to reproduce

I updated my configuration to look like this: 

```
module.exports = {
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'blog/**/*.md',
        typeName: 'Post',
        route: '/blog/:slug',
        resolveAbsolutePaths: true,
        remark: {
          autolinkClassName: 'fas fa-hashtag',
          externalLinksTarget: '_blank',
          externalLinksRel: ['nofollow', 'noopener', 'noreferrer'],
          plugins: [
            // zeit
            [ 'gridsome-plugin-remark-shiki', { theme: 'nord' } ]
          ]
        }
      }
    }
  ]
  
}
```

### Expected result

That should give me the hashtag from font-awesome and give me something like this

`<span class="fas fa-hashtag"></span>`

### Actual result

It doesn't replace the class name and leaves it with the default icon icon-link.

![gridsome-css-issue](https://user-images.githubusercontent.com/349507/52092437-914afe80-2585-11e9-94e1-c0779ebe591d.png)

**Comment by hjvedvik** [comment]
Looks like the transformer is only using global `remark` options. I'll fix that :) But for now, it will work if you move all options (except `plugins`) to a `transformers.remark` property like this:

```js
module.exports = {
  plugins: [],
  transformers: {
    remark: {
      autolinkClassName: 'fas fa-hashtag',
      externalLinksTarget: '_blank',
      externalLinksRel: ['nofollow', 'noopener', 'noreferrer']
    }
  }
}
```

**Comment by robaxelsen** [comment]
@hjvedvik had this been fixed?

**Comment by hjvedvik** [comment]
@robaxelsen Sorry for this late reply... I believe this has been working for a while :)
