### ISSUE TITLE
Is there a way to merge grid some into nuxt?

### ISSUE THREAD

**Issue by bastianhilton** [gridsome/gridsome#1693]
## Summary

Brief explanation of the feature.

Because of gridsome graphql layer and source plugins I feel like it would be a great thing to have it into nuxt and keep the cool features of gridsome alive.

### Basic example

Include a basic example or links here.

Anything that gridsome can do nuxt static site generator can do and support 

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

To continue the efforts that the amazing community has put into this framework

**Comment by hacknug** [comment]
This project might be what you're looking for: https://nuxt-graphql-middleware.dulnan.net/
