### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by soulaimaneyahya** [gridsome/gridsome#1694]
## Description

Build error
```
npm run build

Gridsome v0.7.23

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.05s
Create pages and templates - 0.07s
Generate temporary code - 0.04s
Bootstrap finish - 0.72s
Error: assets/js/styles.b8185833.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
```

package.json
```
  "scripts": {
    "develop": "gridsome develop",
    "build": "gridsome build",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "bootstrap": "^5.3.2",
    "gridsome": "^0.7.0"
  },
  "engines": {
    "nvm": "20",
    "node": "^20"
  }
```

### Environment
I'm using nodejs v20

### Issue
It works on dev v16 and v20, but the build is successful on node v16 and fails on node v20.

**Comment by frederikheld** [comment]
Same here. The Readme in the repo root says "this project is under active development" but the last commit was 2 years ago. Looks abandoned to me :-(

**Comment by absentees** [comment]
Add the node parameter `NODE_OPTIONS=--openssl-legacy-provider` to your build/run command. 
So `NODE_OPTIONS=--openssl-legacy-provider gridsome build`.

Worked for me on my local machine.

**Comment by dyslab** [comment]
Rolling back to node v14 (or v16) by [nvm](https://github.com/nvm-sh/nvm). As this repo update stopped, this will be the best approach to run a gridsome project.

**Comment by soulaimaneyahya** [comment]
@dyslab Yes right
