### ISSUE TITLE
`:filename` param for the dynamic route

### ISSUE THREAD

**Issue by mittalyashu** [gridsome/gridsome#17]
Add `:filename` param for the dynamic routing.

## Reference

[![image](https://user-images.githubusercontent.com/29014463/47370538-9507f300-d703-11e8-882e-fc80aa87a214.png)](https://discordapp.com/channels/476372673564246017/504192730667155466/504308781438730241)

**Comment by patrickcate** [comment]
I'd love to see this.

**Comment by hjvedvik** [comment]
Yes, you are correct @matt-e-king. I'm making it possible in #53.

**Comment by kaceo** [comment]
To make it more general, the use of :filename as a route variable should also be separated to two cases:
- a raw :filename
- a coded :filename-slug which reduces to Null string when it matches the index field of the plugin settings in gridsome.config.js

The second case would allow permalinks generated programmatically inside templates, e.g. menus, to match the GraphQL path expressions.

Example: 
      using @gridsome/source-filesystem
      index: ["README"]
      path: "mycontent/doc/**/*.md"
      route: "documentation/:filenameslug"

source files:
     mycontent/doc/part-one.md      => route = documentation/part-one
     mycontent/doc/README.md      => route = documentation/

**Comment by hjvedvik** [comment]
This should be possible with a route like `/docs/:fileInfo__name`.
