### ISSUE TITLE
404 on index page

### ISSUE THREAD

**Issue by samdbeckham** [gridsome/gridsome#172]
## Description

When I navigate to the index page for my app, it loads everything fine, then renders a 404 once the JS kicks in. (You can see the result [here](https://samdbeckham.gitlab.io/-/frontendne.co.uk/-/jobs/155290768/artifacts/public/index.html)). (**EDIT:** *This page has now expired*)

I have a feeling it's to do with the site being served from a heavily nested subdir, but I'm not sure why exactly. I've correctly set the `publicPath` in the settings as it's being propagated to all the CSS and JS links.

It works on a [lesser nested route](https://samdbeckham.gitlab.io/frontendne.co.uk/) when I deploy to there, so I know the `publicPath` works in that case at least. Maybe it's the `/-/` parts inthe url that are throwing it off?

### Steps to reproduce

You can see the project over on [GitLab](https://gitlab.com/samdbeckham/frontendne.co.uk/merge_requests/1/diffs) and the failing build [here](https://samdbeckham.gitlab.io/-/frontendne.co.uk/-/jobs/155290768/artifacts/public/index.html). If needed I can provide the artifacts of the built site too.

You should be able to fork that project and tests the builds if you have a GitLab account.

### Expected result

It should render the index page as normal

### Actual result

The index page loads, then the JS kicks in and displays a 404 message.

**Comment by samdbeckham** [comment]
As is usually the case with these things. I have found the source of the issue 5 minutes after posting the issue itself.

It seems the app is accessing the ENV file at two different points during the build. Once when generating the HTML and again when generating the JS. When generating the HTML it has access to the ENV variables I need and is setting the paths for the JS correctly. But when the JS is being generated, it doesn't have access to them and is sending an incorrect `publicPath` to the Vue Router.

I'll do a bit more digging to see why it's getting two different values during the same build process, but it may be an issue outside of this repo.

**Comment by samdbeckham** [comment]
It may be an issue with [this line](https://github.com/gridsome/gridsome/blob/master/gridsome/app/router.js#L9) in the router file. Changing it to the below might help, though testing it against my build is proving difficult

` base: config.pathPrefix || process.env.PUBLIC_PATH,`

**Comment by awulkan** [comment]
When it comes to SEO it's not a good idea to make the same page accessible from different routes, unless you add a permanent redirect from the index.html route or something. To me it feels like a non-issue that index.html returns a 404, because I doubt any user would access that page directly.

**Comment by samdbeckham** [comment]
The page isn't accessible from different routes. It's only accessible from `/index.html` on the server side. But it's only accessible from `/` on the vue-router which is where the confusion comes from. 

My suggestion would be to be able to configure whether the home page is at `/` or at `/index.html` in the router. That way you can have whichever server setup you like and gridsome won't break it.

**Comment by awulkan** [comment]
You said:

> "The issue is because I was accessing the page at example.com/index.html instead of example.com/ and vue router didn't have an entry for index.html, which explains the flashing and the redirect to a 404.
> 
> I'm not sure if this is something that should be covered with Gridsome, given that it does generate a page at index.html but no corresponding vue-router route."

Which led me to believe that you wanted the Vue router to acknowledge and route `index.html` as well. But maybe I misunderstood. Because that would make the page accessible from different routes.
