### ISSUE TITLE
gridsome build - cannot read property of minify of undefined

### ISSUE THREAD

**Issue by mantis** [gridsome/gridsome#173]
## Description

Gridsome build currently fails on a new install. I'm guessing this is due to https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

### Steps to reproduce

Installed gridsome for 1st time, and ran "gridsome build" off the default site

### Expected result

static site generated

### Actual result

(undefined) assets/js/app.2509d1fe.js from Terser
TypeError: Cannot read property 'minify' of undefined

**Comment by mantis** [comment]
Work around for now is to force version in packages.json:

"resolutions": {
  "terser": "3.14.1"
}

**Comment by hjvedvik** [comment]
Thanks for posting a solution for this :) A PR has been opened to fix it in terser-js/terser#254.

**Comment by hjvedvik** [comment]
Closes this since the issue has been fixed in the latest [`terser`](https://github.com/terser-js/terser/blob/master/CHANGELOG.md#v3161) release :)
