### ISSUE TITLE
ACF not displaying in GraphQL

### ISSUE THREAD

**Issue by vdiaza** [gridsome/gridsome#174]
I have been trying to display my ACF fields on GraphQL but I have had no luck with it.
I do have installed the ACF to REST plugin, and I added this code to functions.php
add_filter( 'acf/format_value', function ( $value ) {
  if ( $value instanceof WP_Post ) {
    return [
      'post_type' => $value->post_type,
      'id'        => $value->ID,
    ];
  }

  return $value;
}, 100 );

I have been trying to modificate the code, and testing with different post types, but I am not able to solve this.

**Comment by hjvedvik** [comment]
Which version of the source plugin are you using? And can you check if the posts have the `acf` property in your Rest API results?

**Comment by vdiaza** [comment]
@hjvedvik 
    "@gridsome/source-wordpress": "^0.1.0",
    "gridsome": "^0.4.0"

and yes, it does show up one the REST API url: http://localhost/wp-json/wp/v2/pages

**Comment by hjvedvik** [comment]
ACF was adden in 0.2. It should work if you update the source plugin :)

**Comment by vdiaza** [comment]
That did it, thank you!

**Comment by kubarazny** [comment]
Could you show your query to get ACF field, please?
