### ISSUE TITLE
Deploying to Netlify is failing

### ISSUE THREAD

**Issue by YogliB** [gridsome/gridsome#175]
## Description
Build is failing.

### Steps to reproduce
1. Clone [this](https://github.com/YogliB/yogevbb.com) repo.
2. Deploy to Netlify

### Expected result
Successful build and deployment.

### Actual result
[Netlify's log](https://app.netlify.com/sites/relaxed-lovelace-b17888/deploys/5c585340e9f1a7017e704422)

**Comment by hjvedvik** [comment]
You import `./components/footer/Index.vue` but the filename is actually `index.vue` (lower cased `i`)

**Comment by YogliB** [comment]
My

**Comment by YogliB** [comment]
You're right, my bad.
