### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by NWBY** [gridsome/gridsome#176]
The version number is that is logged to the terminal is `0.0.7` when running `gridsome -V` or `gridsome --version`. 

Not a major issue, just to newcomers can look like they have an outdated version installed.

**Comment by hjvedvik** [comment]
I agree :) I can make it output `@gridsome/cli v0.0.7` instead.

**Comment by tomtev** [comment]
Maybe output cli version and current project folder version?

**Comment by hjvedvik** [comment]
Would this output be helpful? It will list installed core and third-party `gridsome` plugins.

```sh
$ gridsome -v
@gridsome/cli v0.0.7

Project dependencies:
- gridsome v0.4.7
- @gridsome/plugin-critical v0.1.0
- @gridsome/remark-prismjs v0.0.4
- @gridsome/source-filesystem v0.2.0
- @gridsome/transformer-remark v0.1.3
- @gridsome/plugin-google-analytics v0.1.0
```

**Comment by physcocode** [comment]
Well I would like to vote for just cli and gridsome version for the version command and a separate command for list of all plugin
