### ISSUE TITLE
Feature request: add classes to markdown

### ISSUE THREAD

**Issue by diomed** [gridsome/gridsome#18]
`![Image](https://picsum.photos/4000/6016?image=949){:.className}`

please make adding classes for photos possible in gridsome.

**Comment by hjvedvik** [comment]
`@gridsome/transformer-remark` could have this plugin built-in if it looks okay? Just a slightly different syntax, but allows more attributes. https://github.com/arobase-che/remark-attr

**Comment by chadananda** [comment]
How would one go about implementing this?

**Comment by hjvedvik** [comment]
@chadananda You can use any Remark plugins like this:
```js
module.exports = {
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        remark: {
          plugins: [require('remark-attr')]
        }
      }
    }
  ]
}
```

**Comment by alpinogusto** [comment]
Is there an example available for resizing images? aka:
`![alt](img){attrs} / ![alt](img){ height=50 }
`

I could load the remark-attr plugin but the build is failing with:
```
Module build failed (from ./node_modules/gridsome/lib/webpack/loaders/static-query.js):
Eror: Missing parser to attach `remark-attr` [link] (to)
```

**Comment by jarred** [comment]
Hi, I am getting the same error as @alpinogusto when trying to use the `remark-attr` plugin implemented as above. Does anyone have a solution?

**Comment by simduchaine** [comment]
I got the same issue than @jarred and @alpinogusto

**Comment by hjvedvik** [comment]
The `remark-attr` plugin should work with the latest version of the Remark transformer now.

**Comment by sk8Guerra** [comment]
I'm getting a similar error: 

<img width="429" alt="Screen Shot 2021-10-02 at 12 26 44" src="https://user-images.githubusercontent.com/18681676/135727864-2d601f90-9e6c-4e18-9bfa-7bd868dfa1d4.png">

I have just upgraded to gatsby `3.14.1`. is `gatsby-remark-attr` compatible with that version of gatsby?

This is how my `gatsby-config.js` looks like:

<img width="387" alt="Screen Shot 2021-10-02 at 12 28 57" src="https://user-images.githubusercontent.com/18681676/135727928-268f21b6-1073-4459-befd-e68ab5918b65.png">

Thanks for your help!
