### ISSUE TITLE
Including 3rd party libraries

### ISSUE THREAD

**Issue by Jurero123** [gridsome/gridsome#180]
## Description

This is probably not a bug, but can't find any info (and I have been searching a lot) about how to include 3rd party libraries like https://github.com/euvl/vue-js-modal

It works perfectly fine with command "gridsome develop", but it fails with "gridsome build". It says that "window is not defined".

I have checked source code of "gridsome.org" where you successfully included "vue-typer" library directly as a component, but I just can't get it to work with any other library.

What is the best way to include 3rd party library that will also work with "gridsome build".
A short "how-to" would be really great (maybe in the docs, since I am probably not the only one with such problem).

**Comment by physcocode** [comment]
Well to tell you in short the plugin you just mentioned does not support server side render so you have to load component dynamically when mounted and you should wrap the component usage inside <ClientOnly></ClientOnly> once the pull request is merged it would be available in docs 
cc : @tomtev

**Comment by Jurero123** [comment]
@physcocode thanks for a prompt reply.

I will try to make it work with the examples you provided. Thanks!

**Comment by physcocode** [comment]
@Jurero123 you may use this link to see the docs for external dependencies https://deploy-preview-68--gridsome-org-dev.netlify.com

**Comment by Jurero123** [comment]
@physcocode Amazing, thank you!

**Comment by Manuel-Suarez-Abascal** [comment]
@physcocode could you help me integrate [vue-scroll-reveal](https://www.npmjs.com/package/vue-scroll-reveal) on my [my website here](https://manuel-suarez-abascal.github.io/manuel-abascal-website/)? It doesn't work when making the build. This is the [github repo](https://github.com/Manuel-Suarez-Abascal/manuel-abascal-website). 

Any help will be really appreciated!

**Comment by OctoD** [comment]
@Manuel-Suarez-Abascal try this

In your **main.js** file default exported function

```js
if (process.isClient) {
    const ScrollReveal = require('vue-scroll-reveal').default;
    
    Vue.use(ScrollReveal);
}
```
