### ISSUE TITLE
Gridsome + Corpusvision = <3

### ISSUE THREAD

**Issue by physcocode** [gridsome/gridsome#181]
hello @tomtev @hjvedvik I am really impressed by the efforts and hard work you have put towards making @gridsome . We have found this really useful and @corpusvision has decided to help towards betterment of Gridsome in following ways.
1) Help Gridsome to complete documentation 
2) Host a Gridsome community website, with forums and datastore for community plugins
3) Make a interface for Gridsome command line from which plugins can be downloaded directly from community website.
4) Commitment to make at least one pull request a month for betterment of Gridsome
5) Provide financial aid if required for server infrastructure or other things required by Gridsome

We can discuss further on hello@corpusvision.com , happy to help :)

**Comment by physcocode** [comment]
Also a question, do you guys accept donations somewhere ? 

Side note: Thank You for such a awesome project

**Comment by tomtev** [comment]
Hi @physcocode, thank you for your commitment to @gridsome. We really appreciate it!

1. This is nice. Just continue to submit PRs and we'll review them as fast as possible.
2. Community plugins will be listed on gridsome.org, but if you want to make an unofficial forum go ahead :) Might be useful for the community.
3. We encourage to add plugins to NPM so they can be installed like normal npm packages.
4. Aewsome :)
5. Thanks! Gridsome is currently self-funded, but we might look at Patreon or Opencollective to get community support.

Cheers :)

**Comment by physcocode** [comment]
@tomtev tell me once you have a Opencollective account 💯💯, also are we including community plugin in gitsome.org ?

**Comment by tomtev** [comment]
@physcocode Yes, any plugin tagged with Gridsome at NPM
