### ISSUE TITLE
How to pass component prop values to static-query GraphQL

### ISSUE THREAD

**Issue by nolfranklin** [gridsome/gridsome#182]
Is is possible for a Vue component to accept a prop value and pass it into its GraphQL static query? ex: ID of reference from parent. 

```
<template>
	<div class="component component--jumbotron">
		{{ $static.jumbotron.heading }}
	</div>
</template>
<static-query>
	query Jumbotron($id: String!) {
		jumbotron: contentfulJumbotron(id: $id) {
			heading
		}
	}
</static-query>
<script>
	export default {
		props: {
			id: String
		}
	}
</script>
```

Greatly appreciate the insights! Thanks.

**Comment by nolfranklin** [comment]
Still a bit new to Gridsome and wanted to follow up. Is this the wrong way of looking at how to bring in a long-form list of referenced content types? (in this case via Contentful). Thanks! :)

**Comment by hjvedvik** [comment]
Both `page-query` and `static-query` are handled on the server, so they don't have access to JavaScript variables, unfortunately. But you will be able to have the current node id as the `$id` variable in your `page-query` in the next version of Gridsome :)

**Comment by sanscheese** [comment]
Should this be closed? 

Am i right in saying "'static-query' is called static as it can not accept any variables" I can add this to the docs.

**Comment by hjvedvik** [comment]
@sanscheese Yes, that's correct. I want to look into giving it a global state sometime. Maybe it could be meta data from the project config. That would at least make it possible to give it some context.

**Comment by Acidic9** [comment]
So whats the alternative solution?

**Comment by Kainkainkain** [comment]
@hjvedvik so to confirm, does this mean that a component in gridsome can never access the store for any data other than what can be queried with its own ID? 
For example, rendering a side navigation for a sub-section- where I want to query pages that are children of a parentID passed as a prop?

**Comment by Kainkainkain** [comment]
@hjvedvik & @nolfranklin perhaps I should query all pages in v-for and v-if until I get values matching props. Move the logic out of graphql query since I can't feed it custom variables from props... 

@nolfranklin you can also grab all and v-for v-if to get the one you want. Inefficient, but thats a cost on gridsome build which is only seconds anyway.

**Comment by hjvedvik** [comment]
@Kainkainkain You can get data based on static IDs in the query, but it won't be possible to pass JS variables into the query, unfortunately. I would get all navigation items in one query and have a helper method to find items base on a parent ID. Maybe something like this:

```html
<template>
  <ul>
    <li v-for="edge in getNavItems(null)">
      <ul>
        <li v-for="edge in getNavItems(edge.node.id)">...</li>
      </ul>
    </li>
  </ul>
</template>
```

```js
export default {
  methods: {
    getNavItems(parentId) {
      return this.$page.allNavItem.edges.filter(edge => {
        return edge.node.parentId === parentId
      })
    }
  }
}
```

**Comment by Kainkainkain** [comment]
Slick! Sweet I'll use that code. Will help also for a top nav with show / hides for children.
