### ISSUE TITLE
Multiple templates per content-type

### ISSUE THREAD

**Issue by kaceo** [gridsome/gridsome#183]
## Summary

Currently Gridsome routes each content-type to one fixed template file, e.g. blogs to /template/BlogPost.
It should also allow the possibility of sending content-type to multiple template files, e.g. /template/BlogPost/Basic and /template/BlogPost/Extended

### Basic example

A static website for Travel information:
content-type = cities
for each city, there are News, Maps, and Yellow Pages, each with different node contents and layouts

### Analysis

Currently Gridsome sends each content type to one single template file.  The path used to match expects a full string match.  This is fine for simple content, but not versatile for more complex sites with deep contents.

Each template file has a Page-Query script, but this script is not versatile enough to cater for all cases.
e.g. Query retrieves by Path
if path = '/city/newyork'  matches the target page returns one single result set.

The match is more useful if it matches partial or with regular expression.
e.g. '/city/newyork/subpage/name' so that the rest of this query can be passed to the page scripts.

Then the creation of sublayouts can be the responsibility of the page author.

**Comment by kaceo** [comment]
After considering the SSR limitations, I propose this strategy:

1. Template/CityInfo.vue catches all routes beginning with "/city/:cityname+", as this is a wildcard.  This is already the current routing.

2. In the pre-caching of Page Queries, an extra variable $pathbase is added to the list of GraphQL parameters.  This variable is the base segment of the path, so e.g. "/city/newyork", "/city/newyork/specials", "/city/newyork/latest/promotions" all resolves to the same $pathbase "/city/newyork".

3. The Page Query can then use the $pathbase as parameter to fetch the content type.

Currently, the Page Query returns null for those paths that has multiple segments, and there is nothing the template author can do to catch the error.

**Comment by hjvedvik** [comment]
Do you think this could be solved with the new [`belongsTo`](https://github.com/gridsome/gridsome/pull/119) field in the GraphQL schema? You could, for example, create three content types: `News`, `Map` and `YellowPages` and have a field on each node in them which refers to a `City` node.  Each city would then be able to list it's news, maps and yellow pages and link to their pages/templates.

**Comment by hjvedvik** [comment]
But I see routing can be a problem with that approach because Gridsome currently cant use a referenced node field as a route params.

**Comment by kaceo** [comment]
I think belongsTo extension of the GraphQL schema will enable more complex content types to be represented in Gridsome, mainly the 1:N and M:N relationships between content types.  This can be very powerful for instance, to build an IMDB type content management system.

But for this particular issue, it is not related to hierarchical content types.  Rather it has to do with the expressive power of Page Query as it currently is implemented in Gridsome.

For instance, a content type CityInfo has a template CityInfo.vue, which contains a Page Query section:
      <page-query>
         query CityInfo ($path : String!) {
             cityInfo (path: $path) {
                cityname
                countryname
                venues { name address }
             }
          }
       </page-query>
      
In Gridsome's /lib/app/graphql/schema/nodes/createQuery.js this nodeType is called with
args { _id, id, path, nullable } and resolves as a collection.findOne ( {path} ) or collection.findOne( {id} ).  This means that the Page Query can only find a node by path or id.

It appears that the code precludes the possibility of finding a node by other ways, e.g. by slug, by title, or by contentType node attributes, in the previous case, by cityname, by countryname.

I am still learning about how different parts of Gridsome fit together so I don't want to make changes yet.  But do tell me if the Page Query inside the templates working with id and path and no other argument is by design or just an oversight.

**Comment by hjvedvik** [comment]
Currently, it's only possible to get the node by `path`. I merged in a [PR](https://github.com/gridsome/gridsome/pull/77) yesterday which opens up all node fields as possible variables. But I think the `id` will work in most cases.

We are going to open up more APIs for adding pages and templates once the internal stuff has been sorted out. Would registering more templates for a single content type, then get the node by `id` in each template and query for different data on the same node work for you?

Something like:

```js
api.addTemplate({
  typeName: 'CityInfo',
  route: '/city/:cityname/extended',
  component: './src/templates/CityInfoExtended.vue'
})
```

**Comment by kaceo** [comment]
Are these APIs to be placed inside gridsome.config.js and gridsome.server.js?   I am rather confused by them, as it is not clear at which phase they are invoked, and they are powerful javascript expressions easy to code wrongly.  In Nuxt this detail is refactored into packaged scripts in /plugins and /middleware, so the config file simply mentions the option. This makes it easier for content builders (non-coders) to learn to use the system's extended power.

I have solved my original problem --- resolve a permalink "/cityinfo/cityname/extended" to execute a Page Query using only "/cityinfo/cityname" as the $Path.  This is done by modifying the core file /lib/graphql/schema/nodes/createQuery.js.   I added "Pathbase: {type: GraphQLString}" to the args list (so that GraphQL queries accept the Pathbase as a parameter), and added an resolve expression to truncate Pathbase to Path (by dropping the 3rd/extra segments), so that the node = collection..findOne({path}) function succeeds.  Currently it works correctly both in Develop and Build.

Can you suggest to me how I can avoid modifying the core Gridsome file?  Perhaps is there a plugin / api method to hook into the CreateQuery?  This would be more versatile than hardcoding, and allow users to develop their own page query strategies to fit their own permalinks.

**Comment by Al-Rozhkov** [comment]
I worked with Nuxt a lot and I used to its [router configuration](https://nuxtjs.org/guide/routing). But I wonder can it work for Gridsome?

Templates are very similar to nuxt [Dynamic Routes](https://nuxtjs.org/guide/routing#dynamic-routes). It would be great to use route params in page query block. That way app is going to be build around routes, lets say one entity instead of `pages` and `templates`.

@hjvedvik what do you think?

**Comment by hjvedvik** [comment]
@kaceo Sorry for not checking back here sooner. But I think the [`templates`](https://gridsome.org/docs/templates/) config that was introduced in v0.7 could resolve this issue. It allows you to define multiple templates for each collection (previously content type). Example config:

```js
module.exports = {
  templates: {
    BlogPost: [
      {
        path: '/blog/:slug',
        component: './src/templates/BlogPost.vue'
      },
      {
        path: '/blog/:slug/extended',
        component: './src/templates/BlogPostExtended.vue'
      }
    ]
  }
}
```

You can also use the [Pages API](https://gridsome.org/docs/pages-api/) instead if you need to do something more advanced.

@Al-Rozhkov The [Pages API](https://gridsome.org/docs/pages-api/) was added after your comment and should let you use more variables in `page-query`. Not the route params, but a context or query variables which are attached to each page :)

**Comment by matthewmorek** [comment]
@Al-Rozhkov @hjvedvik Would you happen to have an example how to use it with source plugins, such as `filesystem` for rendering Markdown files? Here's what I'm trying to do.

```js
templates: {
  Api: [
    {
      path: "/api/:title",
      component: "./src/templates/ApiOverview.vue",
    },
    {
      name: "reference",
      path: "/api/:title/reference",
      component: "./src/templates/ApiReference.vue",
    },
  ],
},
plugins: [
  {
    use: "@gridsome/source-filesystem",
    options: {
      typeName: "Api",
      baseDir: "./content/api",
      path: "**/*.md",
      index: ["index.md"],
      refs: {
        apispec: {
          typeName: "ApiSpec",
          create: true,
        },
      },
    },
  },
  {
    use: "@gridsome/source-filesystem",
    options: {
      typeName: "Api",
      baseDir: "./content/api",
      path: "**/*.md",
      index: ["reference.md"],
      refs: {
        apispec: {
          typeName: "ApiSpec",
          create: true,
        },
      },
    },
  },
}
```

What I'm trying to do is nest pages that belong to a single collection but have different content. One is a true `index` page, and another is a subpage (`reference`). Unfortunately the above setup does not work.

Would you have any ideas on how to make it work?
