### ISSUE TITLE
Generated Schema does not include all front matter keys on arrays

### ISSUE THREAD

**Issue by nathobson** [gridsome/gridsome#184]
## Description

When there is an array of elements within markdown front matter but there are different keys/variables used within elements inside of the array, only the keys from the first array element are generated in the GraphQL schema. As an example example, the markdown front matter may look like this:

```
---
slider:
  - 
    slide_text: Minimum impact on the environment
  - 
    slide_image: /assets/slide-image.jpg
---
```

In this example, a user has had the option (in the backend) of having a slide contain an image or text, so the keys used for each slide may be different. From the above front matter, only `slideText` will be available within the GraphQL schema. However, if the first item contains `slide_text` and `slide_image` then both will be available in the schema.

### Steps to reproduce

[Demo project](https://github.com/nathobson/gridsome-md)

In the GraphQL explorer, try: 

```
{
  allMdPage {
    edges {
      node {
        slider {
          slideText
        }
      }
    }
  }
}
```

Which will work fine, then try

```
{
  allMdPage {
    edges {
      node {
        slider {
          slideImage
        }
      }
    }
  }
}
```

Which will not work. 

Check the markdown file within `src/mdpages/home.md`

### Expected result

All the keys present would be present within the schema.

### Actual result

Only keys present in the first element of an array are added the GraphQL schema.

**Comment by hjvedvik** [comment]
Thanks for noticing :) A fix will be included in the next release.

**Comment by nathobson** [comment]
Perfect! Great project 😎
