### ISSUE TITLE
DOC : how do we create tags for blog posts with Mardown files

### ISSUE THREAD

**Issue by yann-yinn** [gridsome/gridsome#188]
## Summary

Awesome project !

I'm trying for fun to rebuild https://yineo.fr (statically built with Nuxt.js and hosted on netlify) with Gridsome. Data source is **markdown files** and my blog post have some "tags" (at the bottom of the page https://yineo.fr/blog/react-ou-vue-js-osef-les-deux-sont-formidables) + there is a "tag page", where you can see every blog post related to a tag : https://yineo.fr/tag/vue

How can we do this with gridsome ? Should i play with "references" in `gridsome.server.js` ? https://gridsome.org/docs/data-store-api/#collectionaddreferencefieldname-options

**Comment by hjvedvik** [comment]
You will be able to have tags and category pages in the next version (`0.5`). Each content type in the schema will have a `belongsTo` field that lists all nodes which refer to that node. The field will also be able to have pagination etc. I hope to publish it this week if everything goes well :)

**Comment by yann-yinn** [comment]
Cool, can't wait for `belongsTo` field ! Congrats for the way GraphQL Schema is handled, it's very easy to use.

**Comment by yann-yinn** [comment]
Hello, so belongsTo field is here today, but not sure i'm supposed to used it to connect my tags to my post and feels a bit lost with documentation. Is anyone can help me on this ? On this page, `addContentType` method is used, but my content types are already created by a plugin and yaml files: https://gridsome.org/docs/taxonomies#creating-a-taxonomy-page

Should I combine getContentType + create a loop on each Post to reference tags ?

Here is my gridsome.config.js 📝

```js
module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/posts/*.md',
        typeName: 'BlogPost',
        route: '/post/:slug',
        remark: {
          plugins: ['@gridsome/remark-prismjs']
        }
      }
    },
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/posts/*.md',
        typeName: 'Tag',
        route: '/tag/:slug'
      }
    }
  ]
}
```

**Comment by hjvedvik** [comment]
We are going to write more docs for the filesystem source, but you can use a `ref` option that will connect your nodes. Read more in the [source-filesystem](https://gridsome.org/plugins/@gridsome/source-filesystem) readme.

It would be something like this for your `BlogPost` options:

```js
{
  use: '@gridsome/source-filesystem',
  options: {
    path: 'content/posts/*.md',
    typeName: 'BlogPost',
    route: '/post/:slug',
    refs: {
       // if you have a field with tag ids named 'tags':
      tags: 'Tag',
      // or auto create all tags based on the 'tags' field:
      tags: {
        typeName: 'Tag',
        route: '/tag/:id',
        create: true
      }
    },
    remark: {
      plugins: ['@gridsome/remark-prismjs']
    }
  }
}
```

**Comment by yann-yinn** [comment]
Did not manage to make it work, here are my yaml files:

📝 `content/posts/post-example.md`

```md
---
title: 'Retour d’expérience sur Vue.js'
tags:
  - vue
  - graphql
  - react
  - rest
---

# my awesome post

blabla
```

📝 `content/tags/vue.md`

```md
---
name: Vue
slug: vue
---
```

📝 `gridsome.config.js`
```js
module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/posts/*.md',
        typeName: 'BlogPost',
        route: '/post/:slug',
        refs: {
          tags: 'Tag',
          route: '/tag/:slug',
          create: true
        },
        remark: {
          plugins: ['@gridsome/remark-prismjs']
        }
      }
    },
  ]
}
```

**Comment by hjvedvik** [comment]
It looks like you have the correct setup. Which version of `@gridsome/source-filesystem` and `@gridsome/transformer-remark` are you using?

**Comment by yann-yinn** [comment]
```js
{
  "name": "my-gridsome-site",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/remark-prismjs": "^0.0.4",
    "@gridsome/source-filesystem": "^0.2.0",
    "@gridsome/transformer-remark": "^0.1.3",
    "gridsome": "0.5.0"
  }
}
```

**Comment by hjvedvik** [comment]
Should work if you update to `@gridsome/source-filesystem ^0.3.0` and `@gridsome/transformer-remark ^0.2.0` :)

**Comment by yann-yinn** [comment]
Yep, now that works like a charm !

**Comment by nolfranklin** [comment]
Thanks @yann-yinn and @hjvedvik. 

Having some issues with the source-filesystem refs feature. Have an almost identical config as @yann-yinn's above with the latest source-filesystem and transformer. Everything is working as intended with the exception that the ids are being randomly generated, ex: **id: "running"** gets converted to **id: 7f6c29c5d84eadfee38ea95bac846221**.

```
{
  ....
  "dependencies": {
    "@gridsome/source-filesystem": "^0.5.0",
    "@gridsome/transformer-remark": "^0.2.1",
    "gridsome": "^0.6.3",
    "gridsome-plugin-netlify-cms": "^1.0.7",
    "netlify-cms": "^2.9.1"
  }
}
```

```
module.exports = {
        ...
	transformers: {
		remark: {
			externalLinksTarget: '_blank',
			externalLinksRel: ['nofollow', 'noopener', 'noreferrer'],
			anchorClassName: 'icon icon-link',
			plugins: [
			]
		}
	},
	plugins: [
		{
			use: '@gridsome/source-filesystem',
			options: {
				path: '_experiments/*.md',
				route: '/experiments/:slug',
				typeName: 'Experiment',
				refs: {
					status: 'Status'
				}
			}
		},
		{
			use: '@gridsome/source-filesystem',
			options: {
				path: '_status/*.md',
				typeName: 'Status',
				route: '/experiments/status/:slug'
			}
		}
	]
}
```

```
---
title: Running
id: "running"
---
```

The only way to get the refs working is by pulling the random ids from GraphQL explorer.

**Comment by mgd722** [comment]
@nolfranklin Did you ever get this working without having to pull the non-human-readable IDs from the GraphQL explorer?
