### ISSUE TITLE
g-image component doesn't work with svg as expected

### ISSUE THREAD

**Issue by arttemiuss43** [gridsome/gridsome#189]
When using g-image with svg, blurred inlined image not found. [You can see](https://prnt.sc/mjv2d5). But when loaded it's allright.
Are there any advantages of using svg with g-image or we can just use usual img tag for svg?

**Comment by tomtev** [comment]
It's better to just normal <img> for SVGs :) If it's a small SVG I recommend to just add it inline.

**Comment by SteveEdson** [comment]
I have a SVG reference in my markdown file, but gridsome is automatically trying to do the lazy loading on it, which is broken (I get a broken image in chrome). Can there be an option to disable g-image for SVGs in markdown (or just disable it by default?).

Thanks

**Comment by cco3** [comment]
You can use [immediate="true"](https://gridsome.org/docs/images/#options)
