### ISSUE TITLE
Auto Transformation of .xyz string in plugin

### ISSUE THREAD

**Issue by Nivek92** [gridsome/gridsome#190]
## Description

I have a storyblok plugin which get's a string which ends on .xyz (an email address) but in the schema it's not a String but a Json with the following structure
```
{
        "type": "file",
        "mimeType": "chemical/x-xyz",
        "src": "foo@foo.xyz"
}
```
(the original text coming from storyblok was foo@foo.xyz)

### Steps to reproduce

Here's a gist with the plugin
https://gist.github.com/Nivek92/75d71826c80553c0540d17cf4f97f6e3

As one can see the console.log(response.data.stories) correctly shows a string so it happens during the node creation

### Expected result

Get a string instead of a json

### Actual result

Getting 
```
{
        "type": "file",
        "mimeType": "chemical/x-xyz",
        "src": "foo@foo.xyz"
}
```
instead of foo@foo.xyz

**Comment by hjvedvik** [comment]
This will work as expected in the upcoming `0.5` release :) Gridsome currently tries to resolve too many strings. But from now on it will only resolve relative file paths like `./file.png`.

**Comment by Nivek92** [comment]
ok I guess then you can close this issue :smile: 

Thanks :+1:
