### ISSUE TITLE
`ReferenceError: localStorage is not defined` probably caused by GoTrue.js

### ISSUE THREAD

**Issue by Nivek92** [gridsome/gridsome#191]
## Description

I have a project that runs successfully in development more but fails during the build process with

`ReferenceError: localStorage is not defined`

which seems to be caused by Go.True.currentUser

### Steps to reproduce

It's a private repository which I can't share and it's too many files to create a gist with all of it.

### Expected result

It should build

### Actual result

```
ReferenceError: localStorage is not defined
    at Function.recoverSession (node_modules/gotrue-js/lib/user.js:212:0)
    at GoTrue.currentUser (node_modules/gotrue-js/lib/index.js:158:0)
    at _n.data (src/main.js:37:31)
    at _n.<anonymous> (/home/nivek/Programming/WunderPay/dashboard/node_modules/vue/dist/vue.runtime.common.prod.js:6:8227)
    at /home/nivek/Programming/WunderPay/dashboard/node_modules/vue/dist/vue.runtime.common.prod.js:6:27854
    at /home/nivek/Programming/WunderPay/dashboard/node_modules/vue/dist/vue.runtime.common.prod.js:6:27914
    at fn (/home/nivek/Programming/WunderPay/dashboard/node_modules/vue/dist/vue.runtime.common.prod.js:6:28121)
    at _n.e._init (/home/nivek/Programming/WunderPay/dashboard/node_modules/vue/dist/vue.runtime.common.prod.js:6:31887)
    at new _n (/home/nivek/Programming/WunderPay/dashboard/node_modules/vue/dist/vue.runtime.common.prod.js:6:29347)
    at module.exports.__webpack_exports__.default (src/main.js:34:25)
```

**Comment by hjvedvik** [comment]
`localStorage` is only available in the browser. You can check for `process.isClient` to prevent some code from being executed during server-side rendering. Or run the code inside the `mounted` hook in your components. Maybe something like this could work:

```js
if (process.isClient) {
  const { default: GoTrue } = require('gotrue-js')
  const auth = new GoTrue(...)
}
```

**Comment by Nivek92** [comment]
ok, it works. Thanks for your help :pray:

**Comment by proofoftom** [comment]
@hjvedvik 
> run the code inside the mounted hook
This was _EXACTLY_ the advice I needed, as `isClient` and other process variables were all always `undefined` 🙏

**Comment by cbaone** [comment]
Sorry about the noob question, but I got a similar error running a build in netlify. Obviously, it builds fine locally, but it errors out when building in netlify. I don't have any external libraries referencing localStorage just a simple banner.

Here the snippets of code I'm using:

`data: () => ({
    showMessage: !localStorage.getItem("hideMessage"),
}),
methods: {
  dismissMessage: function(){
    this.showMessage = false;
    localStorage.setItem("hideMessage", true);
  },
`


`12:00:04 PM: ReferenceError: localStorage is not defined
12:00:04 PM:     at a.data (src/layouts/Default.vue:232:18)
12:00:04 PM:     at /opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28667
12:00:04 PM:     at /opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28727
12:00:04 PM:     at pn (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:28934)
12:00:04 PM:     at a.e._init (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32700)
12:00:04 PM:     at new a (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
12:00:04 PM:     at Vi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:66307)
12:00:04 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70537)
12:00:04 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70210)
12:00:04 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67457)`

What's the best way to get Netlify to ignore the localStorage reference?

**Comment by Umoren** [comment]
@cbaone this worked for me
process.isClient ? !localStorage.getItem("hideMessage") : false
