### ISSUE TITLE
Netlify variables 

### ISSUE THREAD

**Issue by arttemiuss43** [gridsome/gridsome#192]
How can we use netlify build variables? It would be very useful.

**Comment by hjvedvik** [comment]
They should be available as `process.env.{name}`. The next Gridsome release will let you use the variables in the browser as well if you prefix them with `GRIDSOME_`.

**Comment by arttemiuss43** [comment]
Will it be available on the server side?

**Comment by hjvedvik** [comment]
Yes, all variables will be available on the server.

**Comment by arttemiuss43** [comment]
I will give it a try. Thank you:)

**Comment by arttemiuss43** [comment]
process.env.{name} not working with netlify build variables. It returns undefined.
