### ISSUE TITLE
May be a strange question

### ISSUE THREAD

**Issue by findborg** [gridsome/gridsome#195]
Ok this may sound a little strange but what I am trying to do is build a blank page and use global components in the page rendered.  I am doing this because I can not use slots or named slots after build.
so what I want is this to work:
```
<!DOCTYPE html>
<html data-html-server-rendered="true" lang="en" data-vue-tag="lang">
  <head>
    <title data-vue-tag="true">findborg - Ad free social find engine</title><meta data-vue-tag="true" charset="utf-8"/><meta data-vue-tag="true" name="generator" content="Gridsome v0.4.7"/><meta data-vue-tag="true" data-key="viewport" name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta data-vue-tag="true" data-key="format-detection" name="format-detection" content="telephone=no"/><meta data-vue-tag="true" name="keywords" content="HTML,CSS,XML,JavaScript"/><link data-vue-tag="true" rel="icon" type="image/png" sizes="16x16" href="/assets/static/favicon.ce0531f.24315ee.png"/><link data-vue-tag="true" rel="icon" type="image/png" sizes="32x32" href="/assets/static/favicon.ac8d93a.24315ee.png"/><link data-vue-tag="true" rel="icon" type="image/png" sizes="96x96" href="/assets/static/favicon.b9532cc.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="76x76" href="/assets/static/favicon.f22e9f3.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="152x152" href="/assets/static/favicon.62d22cb.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="120x120" href="/assets/static/favicon.1539b60.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="167x167" href="/assets/static/favicon.dc0cdc5.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="180x180" href="/assets/static/favicon.7b22250.24315ee.png"/><link data-vue-tag="true" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/><noscript data-vue-tag="true" ><style>.g-image--loading{display:none;}</style></noscript><link rel="preload" href="/assets/css/styles.566155ce.css" as="style"><link rel="preload" href="/assets/js/app.f8496dae.js" as="script"><link rel="preload" href="/assets/js/component--home.5e84536a.js" as="script"><link rel="prefetch" href="/assets/js/page-query.7a5eef1a.js"><link rel="stylesheet" href="/assets/css/styles.566155ce.css">
  </head>
  <body data-vue-tag="">
    <div data-server-rendered="true" id="app">
      <idmenu></idmenu>
    </div>
    <script src="/assets/js/app.f8496dae.js" defer></script><script src="/assets/js/component--home.5e84536a.js" defer></script>
  </body>
</html>

**Comment by findborg** [comment]
Note**
It would be super awesome if I could get that to work on any page that I add after the Index.vue

**Comment by physcocode** [comment]
have you tried registering your component in index.js ? something like `  Vue.component('Layout', DefaultLayout)` does it or you can register it by `Vue.use(MyComponent)` here is an un merged pull request that might help to answer your question https://github.com/gridsome/gridsome.org/pull/68 and here is the documentation the page adds https://deploy-preview-68--gridsome-org-dev.netlify.com/docs/assets-scripts , if you still stuck in issue feel free to leave me a comment :)

**Comment by findborg** [comment]
Yes I did register with vue.use in main.js and it works just fine in Index.vue But,  it does not work after the build in index.html.  I tested both ways.  I also tried using only a slot in index vue and nothing happens if I alter the index.html after it has been built.  I also tried named slots.  I will check out the links you presented.

**Comment by physcocode** [comment]
is the component id menu SSR compatible ? if not then you don't have to use Vue.use , you would have to import it to your default layout using component()

**Comment by findborg** [comment]
I need this because your build is so awesome.  I am getting 80s to 100s on lighthouse.  All 100s on a standard build like for about pages where I do not need to pull info from the server. So I decided to use gridsome to build my shell page templates.   Normally,  I can build the page and just use props or slots to add server content to the components.  I do not use rails but here is a good video of what I normally do.  [A video](https://gorails.com/episodes/vuejs-components-in-rails-views?autoplay=1)

**Comment by findborg** [comment]
For right now this is all idmenu is:
```
<template>
    <div>
        <slot>Replace Id-menu</slot>
    </div>
</template>

**Comment by findborg** [comment]
Then I want to be able to use ``<idmenu>My server output here``</idmenu>

**Comment by findborg** [comment]
[This is the page that I am rebuilding](http://www.findborg.com/).  Right now it is built with gridsome.  
I am replacing the search box with vue-simple-suggest pluging.  It works just fine so far. 
If you look in the top right you will see notifications This is a slot.  I can not replace it in the built index.html.  the idmenu component would be just to the right of the app icon. 
If you view the source,  can see that I can edit the head and I can also edit anything outside of the #div app.  This leads me to believe that maybe the cache is keeping vue from catching the global components and or slots or props.

**Comment by findborg** [comment]
> Ok this may sound a little strange but what I am trying to do is build a blank page and use global components in the page rendered. I am doing this because I can not use slots or named slots after build.
> so what I want is this to work:
> 
> ```
> <!DOCTYPE html>
> <html data-html-server-rendered="true" lang="en" data-vue-tag="lang">
>   <head>
>     <title data-vue-tag="true">findborg - Ad free social find engine</title><meta data-vue-tag="true" charset="utf-8"/><meta data-vue-tag="true" name="generator" content="Gridsome v0.4.7"/><meta data-vue-tag="true" data-key="viewport" name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta data-vue-tag="true" data-key="format-detection" name="format-detection" content="telephone=no"/><meta data-vue-tag="true" name="keywords" content="HTML,CSS,XML,JavaScript"/><link data-vue-tag="true" rel="icon" type="image/png" sizes="16x16" href="/assets/static/favicon.ce0531f.24315ee.png"/><link data-vue-tag="true" rel="icon" type="image/png" sizes="32x32" href="/assets/static/favicon.ac8d93a.24315ee.png"/><link data-vue-tag="true" rel="icon" type="image/png" sizes="96x96" href="/assets/static/favicon.b9532cc.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="76x76" href="/assets/static/favicon.f22e9f3.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="152x152" href="/assets/static/favicon.62d22cb.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="120x120" href="/assets/static/favicon.1539b60.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="167x167" href="/assets/static/favicon.dc0cdc5.24315ee.png"/><link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="180x180" href="/assets/static/favicon.7b22250.24315ee.png"/><link data-vue-tag="true" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/><noscript data-vue-tag="true" ><style>.g-image--loading{display:none;}</style></noscript><link rel="preload" href="/assets/css/styles.566155ce.css" as="style"><link rel="preload" href="/assets/js/app.f8496dae.js" as="script"><link rel="preload" href="/assets/js/component--home.5e84536a.js" as="script"><link rel="prefetch" href="/assets/js/page-query.7a5eef1a.js"><link rel="stylesheet" href="/assets/css/styles.566155ce.css">
>   </head>
>   <body data-vue-tag="">
>     <div data-server-rendered="true" id="app">
>       <idmenu></idmenu>
or <div slot="My named slot"> I replace slot</div>
>     </div>
>     <script src="/assets/js/app.f8496dae.js" defer></script><script src="/assets/js/component--home.5e84536a.js" defer></script>
>   </body>
> </html>
> ```

If we can figure out how to get the above to work...    The possibilities are enormous.  Just because your build is so strong....!
But, the thing to remember

**Comment by findborg** [comment]
Anybody have any idea on how to get this to work as stated above?  I still have not had any luck

**Comment by physcocode** [comment]
@findborg I have been stuck in little work I'll look into this today and let you know

**Comment by physcocode** [comment]
@findborg  Ok so I had a chance to get it working, maybe you have been doing something wrong

1) I made a file src/components/idmenu.vue with following source
```javascript
<template>
    <div>
        <slot>Replace Id-menu</slot>
    </div>
</template>

<script>
export default {
}
</script>
```

2) I register the component in my src/index.vue binding it to <idmenu> tag
```javascript
// This is the main.js file. Import global CSS and scripts here.
// The Client API can be used here. Learn more: gridsome.org/docs/client-api

import DefaultLayout from '~/layouts/Default.vue'
import IDMenu from '~/components/idmenu.vue'

export default function (Vue, {router, head, isClient}) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)
  Vue.component('idmenu', IDMenu)
}
```

3) I used the component inside src/pages/Index.vue
```javascript
<template>
  <Layout>
    
   <idmenu></idmenu>
  </Layout>
</template>

<script>
export default {
}
</script>
```

Here is the final output after running Gridsome build
```javascript
<!DOCTYPE html>
<html data-html-server-rendered="true" lang="en" data-vue-tag="lang">

<head>
  <title data-vue-tag="true">Gridsome - Gridsome</title>
  <meta data-vue-tag="true" charset="utf-8" />
  <meta data-vue-tag="true" name="generator" content="Gridsome v0.4.7" />
  <meta data-vue-tag="true" data-key="viewport" name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta data-vue-tag="true" data-key="format-detection" name="format-detection" content="telephone=no" />
  <link data-vue-tag="true" rel="icon" type="image/png" sizes="16x16" href="/assets/static/favicon.ce0531f.9bb7ffa.png" />
  <link data-vue-tag="true" rel="icon" type="image/png" sizes="32x32" href="/assets/static/favicon.ac8d93a.9bb7ffa.png" />
  <link data-vue-tag="true" rel="icon" type="image/png" sizes="96x96" href="/assets/static/favicon.b9532cc.9bb7ffa.png" />
  <link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="76x76" href="/assets/static/favicon.f22e9f3.9bb7ffa.png" />
  <link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="152x152" href="/assets/static/favicon.62d22cb.9bb7ffa.png" />
  <link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="120x120" href="/assets/static/favicon.1539b60.9bb7ffa.png" />
  <link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="167x167" href="/assets/static/favicon.dc0cdc5.9bb7ffa.png" />
  <link data-vue-tag="true" rel="apple-touch-icon" type="image/png" sizes="180x180" href="/assets/static/favicon.7b22250.9bb7ffa.png" /><noscript
    data-vue-tag="true">
    <style>
      .g-image--loading {
        display: none;
      }
    </style>
  </noscript>
  <link rel="preload" href="/assets/css/styles.970af96c.css" as="style">
  <link rel="preload" href="/assets/js/app.f09b6c1c.js" as="script">
  <link rel="preload" href="/assets/css/2.styles.c6f58f08.css" as="style">
  <link rel="preload" href="/assets/js/component--home.70cc92b5.js" as="script">
  <link rel="prefetch" href="/assets/js/component--about.05edff8a.js">
  <link rel="prefetch" href="/assets/js/page-query.2e2e68d9.js">
  <link rel="stylesheet" href="/assets/css/styles.970af96c.css">
  <link rel="stylesheet" href="/assets/css/2.styles.c6f58f08.css">
</head>

<body data-vue-tag="">
  <div data-server-rendered="true" id="app" class="layout">
    <header class="header"><strong><a href="/" class="active--exact active">Gridsome</a></strong>
      <nav class="nav"><a href="/" class="nav__link active--exact active">Home</a><a href="/about" class="nav__link">About</a></nav>
    </header>
    <div>Replace Id-menu</div>
  </div>
  <script src="/assets/js/app.f09b6c1c.js" defer></script>
  <script src="/assets/js/component--home.70cc92b5.js" defer></script>
</body>

</html>
```

As you can see the final build contains ` <div>Replace Id-menu</div>`. I hope this answers your question have a great day.

Feel free to close this issue

**Comment by physcocode** [comment]
Also forgot to mention you may use `<idmenu>My Server Render</idmenu>` which outputs following after build ` <div>My Server Render</div>`

**Comment by physcocode** [comment]
@findborg also on a note YOU CAN USE SLOTS even after build 
wrapping your component inside `<ClientOnly></ClientOnly>` will stop it from being rendered on server then you can use the <idmenu></idmenu> as a client side Vue script or here is a simple trick
```javascript
<template>
  <Layout>
     <idmenu v-if="isMounted"></idmenu>
  </Layout>
</template>

<script>
export default{
data: function(){
 return{
isMounted:false,
 } 
},
mounted(){
this.isMounted = true;
}
}
</script>

<style>
.home-links a {
  margin-right: 1rem;
}
</style>

</script>
```

This will avoid your component to be rendered by SSR during build time and you can use it as your client side vue

**Comment by findborg** [comment]
Looks good,  I will give it a go this evening..  
Thanks for your time on this "side project"
I will come back and advise if I get it functioning or not.

**Comment by findborg** [comment]
Good Hacking!  It worked by loading the <idmenu> </idmenu>(in the after build page!!).
Note that I tried just for the heck of it to alter the idmenu div text directly.  Not that I need that now that the above works.  Anyway,  it would not change the text.  I am betting that someone is going to ask about that in the future.
Very excited and thankful.  In my honest opinion this is how web components are supposed to work and now gridsome has the ability to work with "web components".

**Comment by findborg** [comment]
Bad news.  It is not working.  So I am trying to get a work around done using vue-custom-element.  I have it working in develop mode but it will not build out.  Would you be willing to help me get it working?
Here is the link to [vue-custom-element](https://github.com/karol-f/vue-custom-element)

**Comment by findborg** [comment]
Here is the build error I keep getting
```Failed to render /
ReferenceError: HTMLElement is not defined
    at C:\wamp64\www\frames\home1\node_modules\vue-custom-element\dist\vue-custom-element.js:47:49
    at Object.setPrototypeOf (C:\wamp64\www\frames\home1\node_modules\vue-custom-element\dist\vue-custom-element.js:7:82)
    at Object.<anonymous> (C:\wamp64\www\frames\home1\node_modules\vue-custom-element\dist\vue-custom-element.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! home1@ build: `gridsome build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the home1@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by findborg** [comment]
@physcocode 
Did you see my comments above?  I am still working on trying to get this to work....

**Comment by physcocode** [comment]
How did you hook in custom element? , Need little more elaboration on this one
