### ISSUE TITLE
Problems with g-image

### ISSUE THREAD

**Issue by johannesholmberg** [gridsome/gridsome#198]
## Description

On my local environment I’m getting the following error when I’m using `g-image`: `Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)`

Publishing on Netlify works fine, but annoying since I can’t see the images on my machine. Any one else experiencing this as well?

**Comment by hjvedvik** [comment]
This [PR](https://github.com/gridsome/gridsome/pull/199) should fix the issue. Will publish it within the next days if it works well :)

**Comment by johannesholmberg** [comment]
@hjvedvik Works fine now :)
