### ISSUE TITLE
Source request: Google Spreadsheet plugin

### ISSUE THREAD

**Issue by robaxelsen** [gridsome/gridsome#200]
## Summary

The request is to make an Google Spreadsheet source plugin for Gridsome.

### Basic example

An official Gridsome plugin, like the any of the currently published source plugins: https://gridsome.org/plugins

### Motivation

Would love to have this as a source plugin. ~~I would love to have this for my own personal use, and see no better way to accomplish that than to contribute upstream in the process :wink: :tada:~~

**Comment by robaxelsen** [comment]
Unassigning myself from this due to my delay in completing this. Anyone else feel to implement.

**Comment by spenwall** [comment]
I would like to take a shot at this if that is ok.

**Comment by robaxelsen** [comment]
@spenwall thanks for the offer, and sorry for the late reply. I see you've already created the plugin on your own! Well done :)

Feel free to make a PR where you make the plugin an official @gridsome/source-google-sheets plugin.
