### ISSUE TITLE
Can't query by $slug

### ISSUE THREAD

**Issue by darthmeme** [gridsome/gridsome#205]
## Description

I can't seem to use the `$slug` variable on a `page-query` as described [here](https://gridsome.org/docs/querying-data/#query-data-in-templates). Webpack throws an error as shown below.

Gridsome: `v0.5.0`

### Steps to reproduce

Write a query such as:
```
query($slug: String!) {
  item: productItem(slug: $slug) {
    id
  }
}
```

### Expected result

The query should return an item based on the URL slug

### Actual result

An error is thrown:
> Unknown argument `slug` on field `productItem` of type `Query`

**Comment by hjvedvik** [comment]
Single nodes can't be queried by `slug` because it's not a unique field. I would recommend using `$id` to get the node in templates. The other variables are there to be used for filtering collections. I'll update the docs to show that more clearly :)
