### ISSUE TITLE
GraphQL problem with wordPressPage id

### ISSUE THREAD

**Issue by Slavvomir** [gridsome/gridsome#208]
Hi,

I have problem with query of specific page from Wordpress
I have query:

```
query Home {
  allWordPressPage {
    edges {
      node {
        _id
      }
    }
  }
}
```

It shows me different pages with its IDs. I want to get page with specific ID e.g. 20. I'm sure it exist.

```
query Page {
  wordPressPage (id: "20"){
    path
    id
  }
}
```

And there is error with message:

`"message": "A WordPressPage with id 20 was not found",`

How can I get the specific page?

**Comment by robaxelsen** [comment]
@Slavvomir here you go, just tried this and it works:

```
query Page {
  wordpressPage (id: "20"){
    id
    path
  }
}
```

The problem was simply naming of wordPressPage; should be wordpressPage.
