### ISSUE TITLE
Dato CMS querying for modular content throws errors

### ISSUE THREAD

**Issue by theCubix** [gridsome/gridsome#209]
When I try to query for modular content provided by Dato CMS, I receive the following error:

<pre>
{
  "error": {
    "errors": [
      {
        "message": "Field \"content\" must not have a selection since type \"String\" has no subfields.",
        "locations": [
          {
            "line": 13,
            "column": 17
          }
        ]
      }
    ]
  }
}
</pre>

I recreated the data model as shown in [this tutorial](https://www.datocms.com/docs/introduction/modular-content/) and I'am now trying to retrive the content using this query:

<pre>
{
  allDatoCmsArticle {
    edges {
      node {
        content {
          ... on DatoCmsQuote {
            quote
            author
          }
        }
      }
    }
  }
}
</pre>

What am I missing? Or is modular content currently not supported by the dato cms source plugin?

**Comment by hjvedvik** [comment]
Gridsome currently overrides the content field. You can name it something else, but I’ll try to fix it in the next publish :)

**Comment by theCubix** [comment]
Oh, wow. Thank you for the very fast response! 👍 Changed it and it works now.

Follow up question: how can I find out the type of the modular content block?

In the tutorial mentioned in my initial question, they used `_modelApiKey`, but this throws the following error:

<pre>
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"_modelApiKey\" on type \"DatoCmsQuote\".",
        "locations": [
          {
            "line": 7,
            "column": 13
          }
        ]
      }
    ]
  }
}
</pre>

Any ideas?

**Comment by hjvedvik** [comment]
You can try to see if you find what you are looking for if you go to `http://localhost:8080/___explore` when you run `gridsome develop`.

**Comment by theCubix** [comment]
Alright, thanks again for your input 👍 
Unfortunately, I wasn't able to directly query for the content type, so I just configured Dato CMS to add a text field with a default value (e.g. imageBlock).

**Comment by gilesbutler** [comment]
Just following up @theCubix - `_modelApiKey` was added back in May (via https://github.com/gridsome/gridsome/pull/369) so you don't have to add custom text fields to Dato anymore.

**Comment by theCubix** [comment]
@gilesbutler thank you for letting me know 👍🏼 I'll look into it
