### ISSUE TITLE
Can't load images locally from my src into my project

### ISSUE THREAD

**Issue by jaeyholic** [gridsome/gridsome#211]
## Description
trying to load an image locally into my project, I always end with errors. I am new to Gridsome and I have followed the docs but still can't find a solution to this problem since yesterday. if someone some helps me on how I can load images locally using g-image into my project. I will be grateful
Describe the issue that you're seeing.

**Comment by tomtev** [comment]
Hi @jaeyholic, how are you trying to load the image? 

Did you read this carefully:
https://gridsome.org/docs/images

**Comment by jaeyholic** [comment]
Thank you so much, I fixed it. And another thing
How can I add Bootstrap to gridsome? I have an existing nuxt app and I'm rebuilding everyrhing in gridsome and I installed Bootstrap and imported it in the main.js but it doesn't work. Kindly help me please

**Comment by robaxelsen** [comment]
@jaeyholic How exactly did you install bootstrap, and what did you add in main.js? Have you also imported the bootstrap css separately in main.js?

**Comment by jaeyholic** [comment]
I did a little bit of googling and also figuring stuffs out.
I imported the Vue from the node modules 
I used Vue.use(Vue)
And called the Bootstrap 

It worked. Thanks
