### ISSUE TITLE
Feature request: Pager component: show only prev/next links

### ISSUE THREAD

**Issue by cossssmin** [gridsome/gridsome#215]
Looks like it's not possible to show only next/prev links with the Pager.

From my understanding, `showLinks` would be used to enable/disable the _numeric_ page links? Because if it's meant to completely remove the pagination, you just wouldn't use the component, right?

If I set `showLinks` to `false`, the entire navigation disappears.

### Steps to reproduce

Try using the Pager component like this:

```vue
<Pager :info="$page.myobject.pageInfo" :showLinks="false"/>
```

### Expected result

See only next/prev links in pagination (numeric page links removed).

### Actual result

Pagination is completely removed.

**Comment by cfaddict** [comment]
I get that this could be a feature of the pager out of the box... but I wanted my own pagination so I just rolled my own using the css framework that I am using (Bulma) and it was fairly easy. I could just as easy take out the links if I wanted to...Just wanted to share in case its helpful. 

https://github.com/cfaddict/danvega-me/blob/master/src/components/BulmaPagination.vue

**Comment by hellocosmin** [comment]
Yup, built my own component too, along the same lines. Just thought it might be useful for the included Pager component :)

**Comment by robaxelsen** [comment]
@hellocosmin Thanks for the request, and sounds like a good idea to me. What do you think @tomtev @hjvedvik?

@hellocosmin  @cfaddict if you'd like to make an attempt at creating a PR for this (utilizing your existing own pagination) let me know, and I'll assign the issue to you.
