### ISSUE TITLE
Transfer gridsome-helper-json to gridsome organization

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/gridsome#219]
## Summary

I made this package for Vetur's autocompletion.
https://github.com/tyankatsu0105/gridsome-helper-json
PR is here
https://github.com/vuejs/vetur/pull/1101
I suggest maintain this package under the Gridsome organization

### Motivation

Maybe this package should maintain by various maintainers from now on

**Comment by tyankatsu0105** [comment]
I want to ask various people's opinions🤔

**Comment by hjvedvik** [comment]
Yes, we should have a repository for it in this organization :) I'll create one for you tomorrow.

**Comment by tyankatsu0105** [comment]
OK thanks !

**Comment by hjvedvik** [comment]
I have added you as an admin for this repository now :)
https://github.com/gridsome/gridsome-helper-json

Anything else that should be done?

**Comment by tyankatsu0105** [comment]
Awesome! 
Thanks @hjvedvik 
It will be fine 👌
