### ISSUE TITLE
Add support for local plugins

### ISSUE THREAD

**Issue by mattbrailsford** [gridsome/gridsome#22]
I'm working on a source plugin and it took a little while to get it working. Ultimately I couldn't get `require.resolve` to resolve my plugin in a local plugins folder. In the end, I had to set my plugins `use` parameter to `../../../../src/plugins/source-umbraco` to work.

Would be good if there was a nice way to be able to include local plugins as well as ones installed via NPM

**Comment by hjvedvik** [comment]
I'm surprised you got it working :) `gridsome@0.3.0` was just published and should make this much easier. There is also some documentation about it [here](https://gridsome.org/docs/install-plugins#using-local-plugins). Version 0.3 also makes it possible to use the plugin API directly from a `gridsome.server.js` file on root in your project. That allows you to fetch data from Umbraco without using plugins. Check out the new [Data Store API](https://gridsome.org/docs/data-store-api).

You can also follow the [How to contribute](https://github.com/gridsome/gridsome#how-to-contribute) if you want to create a `@gridsome/source-umbraco` plugin. The repository uses Yarn workspaces to resolve local packages.

**Comment by VincentPFG** [comment]
[Page not found](https://gridsome.org/docs/install-plugins#using-local-plugins) and no mention of local plugins usage in the documentation anymore :/

**Comment by josepjaume** [comment]
It looks like you can use `~/plugins/whatever` if you have `plugins/whatever` in your project's root path :)
