### ISSUE TITLE
Add meta data in gridsome.config.js

### ISSUE THREAD

**Issue by hjvedvik** [gridsome/gridsome#225]
## Summary

Meta data can be added by using the `store.addMetaData(key, value)` method in `gridsome.server.js`, but it would be nice to also be able to do it in `gridsome.config.js` by adding a `metaData` object to the configuration.

Maybe `siteName`, `siteDescription` and `siteUrl` also can be moved into `metaData`.

### Basic example

```js
module.exports = {
  metaData: {
    siteName: 'Gridsome',
    customValue: 'A custom value',
    object: {
      test
    }
  }
}
```

```graphql
query {
  metaData {
    customValue
    object {
      test
    }
  }
}
```

**Comment by hellocosmin** [comment]
Yes please, I was going to ask about a way of adding custom variables to the config 🙂
