### ISSUE TITLE
Google Tag Manager tag is not working

### ISSUE THREAD

**Issue by sergeyfilimonov** [gridsome/gridsome#228]
## Description

When trying to build with [Vue GTM module](https://www.npmjs.com/package/vue-gtm), it throws an error "ReferenceError: window is not defined"

### Steps to reproduce

1. Install [Vue GTM module](https://www.npmjs.com/package/vue-gtm)
2. Configure it in `main.js`
3. Build.

Demo repo is [here](https://github.com/sergeyfilimonov/sergeyfilimonov.com)

### Expected result

I am expecting a successful build.

### Actual result

Build failed.

### Environment

<pre><code>
Libs:
- gridsome version: 5.0.3
 
For Tooling issues:
- Node version: 8.12 
- Platform:  Mac
</code></pre>

**Comment by hellocosmin** [comment]
Looks like it doesn't support SSR, have you tried using `<ClientOnly></ClientOnly>` ?

https://gridsome.org/docs/assets-scripts/#without-ssr-support

**Comment by sergeyfilimonov** [comment]
Thanks! But I can't configure out now how do I import Google Tag Manager.

Maybe I should import it in mounted() within a layout but to configure it it needs to connect to the router. Do you think this code

```
Vue.use(VueGtm, {
    id: 'GTM-WH2RFDV',
    enabled: true,
    debug: true,
    vueRouter: router
  })
``` 
can be put within a layout not main.js?

**Comment by hellocosmin** [comment]
Haven't tried importing it globally. Also, it looks like importing a non-SSR component like in the docs link above (inside `components {}`) is returning a Vue runtime error:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
```

So here's what I did to get [vue-parallaxy](https://www.npmjs.com/package/vue-parallaxy) working in a component:

```
<template>
  <div>
    <ClientOnly>
      <parallax :speed-factor="0.4">
        <img :src="post.image" :alt="post.title">
      </parallax>
    </ClientOnly>
  </div>
</template>

<script>
import Parallax from "vue-parallaxy"

export default {
  components: {
    Parallax
  },
  props: ['post'],
}
</script>
```

Hope this helps, try it out and let us know how it goes :)

**Comment by hjvedvik** [comment]
@sergeyfilimonov You can try to use `require` like this:

```js
export default function (Vue) {
  if (process.isClient) {
    const { default: VueGtm } = require('vue-gtm')
    Vue.use(VueGtm, {})
  }
}
```

**Comment by sergeyfilimonov** [comment]
@hjvedvik tried this:

```
<template>
  <div>
  </div>
</template>

<script>
export default function (Vue) {
  if (process.isClient) {
    const { default: VueGtm } = require('vue-gtm')
    Vue.use(VueGtm, {
      id: 'GTM-WH2RFDV',
      enabled: true,
      debug: true,
      vueRouter: router
    })
  }
}
</script>
```

Registered this as a component and then added it to the default layout.

And got this:

```
process-update.js?e135:28 TypeError: Cannot set property 'render' of undefined
    at normalizeComponent (componentNormalizer.js?2877:24)
    at eval (GTM.vue?82fc:9)
    at Module../src/components/GTM.vue (app.a1139386d19cf64f800a.hot-update.js:35)
    at __webpack_require__ (app.js:767)
    at Object.hotApply [as apply] (app.js:686)
    at cb (process-update.js?e135:66)
    at eval (process-update.js?e135:82)
```

**Comment by hjvedvik** [comment]
Probably because the `router` variable is not defined. Just get it in the second argument:
```js
export default function (Vue, { router }) { ...
```

**Comment by hjvedvik** [comment]
But the example I posted was supposed to be in `main.js`. It won't work in a component.

**Comment by sergeyfilimonov** [comment]
@hjvedvik thanks! Seems to be working on https://sergeyfilimonov.com/
