### ISSUE TITLE
VUEX how to use it

### ISSUE THREAD

**Issue by hamidsouth** [gridsome/gridsome#229]
i followed the docu and here is my  main.js file 
```
import DefaultLayout from '~/layouts/Default.vue'
import Vuex from 'vuex'
import '~/assets/css/bootstrap.css';
export default function (Vue, { router, head, isClient, appOptions }) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)
  Vue.use(Vuex);
  appOptions.store = new Vuex.Store({
    state:{
      filter:true,
    },
    mutations: {
      increment (state) {
        state.filter = false;
      }
    }
  });
}

```
Now how can i access store prop ? in pages or layout

**Comment by hjvedvik** [comment]
The store should be available in your components as `this.$store` :)

**Comment by robaxelsen** [comment]
@hamidsouth to add to what @hjvedvik said, you can also use the mapState() helper. For more information, [see the vuex docs.](https://vuex.vuejs.org/guide/state.html#the-mapstate-helper).

Closing, as the question has been answer. For further Vuex questions, I recommend[ VueLand (Vue.js Chat)](https://vue-land.js.org/) and the [Vue.js Forums](https://forum.vuejs.org/tags/vuex).
