### ISSUE TITLE
WooCommerce example + checkout page

### ISSUE THREAD

**Issue by karimhossenbux** [gridsome/gridsome#233]
I saw the WooCommerce icon in the official website header and I was wondering if you guys had an example of Gridsome working with it?

And also how do you manage that **checkout** page? Is that even possible right now?

Thank you in advance 👌

**Comment by hjvedvik** [comment]
It is possible to get products from WooCommerce right now if you use their `woocommerce-api` package and the Gridsome [data store](https://gridsome.org/docs/fetching-data#add-data-from-apis).

We are working on a source plugin, but I don't know when it's ready. We also think their API isn't optimized for our use case, so we might create a helper plugin for WordPress that should be used with the source plugin we create :)

**Comment by maciekkus** [comment]
Not sure if I see this properly but maybe in this case you could use (hopefully incoming soon) graphql-source plugin and wp-graphql plugin installed on wordpress site (https://www.wpgraphql.com/)

**Comment by robaxelsen** [comment]
Closing, as OP questions have been answered. Feel free to re-open if you have any follow-ups @karimhossenbux.

**Comment by simplenotezy** [comment]
@robaxelsen / @hjvedvik any updates on this? And whether gridsome and woocommerce are still a good idea?

**Comment by andriilive** [comment]
Hey, woo graphql was realized
https://github.com/wp-graphql/wp-graphql-woocommerce

See NextJs example: https://github.com/imranhsayed/woo-next

If even this doesn't speed up the development process, pls just remove the icon
