### ISSUE TITLE
Pages and templates folder : why a difference ?

### ISSUE THREAD

**Issue by matthieubellon** [gridsome/gridsome#234]
## Summary

For newcomers (as I am) there is no reason why the page listing nodes and the page displaying one node should be in different folders or named differently (page and template).  This lead to another confusion where pages displaying nodes collection can be named how we want but templates must be named following the collection name.

UX wise, without clear indications on why this must be, it forces the user to frequently refers to the documentation.

At least I did not find a reason in the documentation. If there is a reason is it written somewhere for me to understand ?

### Basic example

Example #1 : 
pages/
--about.vue
--blogpost/
----detail.vue 
----list.vue

No more templates (so less documentation needed, less onboarding friction)
A folder name as I want to name it (less error prone magic, less documentation) and easy to understand dedicated vue files. 

With https://mywebsite.com/blogpost/ > I hit the list.vue file
With https://mywebsite.com/blogpost/ahyu78hwb > I hit the detail.vue file and have 'ahyu78hwb' in view router params

### Motivation

Simplicity means success. Here we have complexity for (apparently) no gain (as a end user speaking, maybe there is a gain for the product owner or a gain I missed somewhere)

**Comment by SteveEdson** [comment]
I think it makes sense as it is, simply:

`Pages` are individual pages that have their own route.

`Templates` are used for a collection of posts, they don't have their own direct route, they're just the basis for the content from the data sources.

**Comment by matthieubellon** [comment]
As I am just starting to work with GraphQL maybe there are concepts I do not get that make sense here.

Because you say templates are for "collection of posts" (plural) so I assume a list. But the documentation is clear, template is for a single node view and pages are for listing GrpahQL collections (I assume list of nodes)

I really think there are GraphQL concepts I do not know that are here central and that's why i do not get it.

Thnaks for your feedback

**Comment by SteveEdson** [comment]
> "template is for a single node view"

Correct, but it's the template that is used for the single node view, when the node is part of a collection. So you might have a Post template, which will create a page for each node in your collection of posts, pulled in from a markdown folder, or an API etc.

A page is something you might create yourself, e.g. an about page

**Comment by matthieubellon** [comment]
> A page is something you might create yourself, e.g. an about page

not only because pages are also for GraphQL collections. Not only "hand made" content but also content pulled from API, Markdown ...

And Templates are also for GraphQL pulled content, but single node.

So GraphQL pulled content spans over two different folders. Not a big deal, but IMO, confusing as I don't see why.

**Comment by tomtev** [comment]
We might create a graphic that explains this better. 
We have tried to explain it quickly here: 
<img width="865" alt="skjermbilde 2019-03-01 kl 21 45 31" src="https://user-images.githubusercontent.com/48070/53665317-61b61180-3c6b-11e9-81f3-84323886bb02.png">

**Comment by tomtev** [comment]
Maybe @SteveEdson could improve the text a bit? :) I like what you wrote above here.

**Comment by matthieubellon** [comment]
Okay, there is something I have read several times but not "really read" in the doc and I missed it.

Pages : URL without dynamic params
Templates : URL with dynamic params.

That's why you can have GraphQL list of node in Pages but not in Templates.
Still standing by my github issue and don't see the why those files should be in different folders (maybe a framework internal interest of doing so) but I won't waste your time anymore ! Thanks for you feedback.

**Comment by tomtev** [comment]
It's really good feedback @matthieubellon :) I have had the same thoughts, but always end up as we have it now. We just need to communicate it better somehow.

**Comment by kaceo** [comment]
Although Gridsome is mainly a Static Site Generator, a non-techie may not find it better than Jekyll or Hugo.  In its current form, it is more verbose (configurations in JS instead of YAML), less user friendly (CLI is requried to build), and themes cannot be external.  

For techies, Gridsome's data layer is the masterpiece of this project.  During build it extracts the GraphQL queries from Vue sources and stages a temporary data layer for it.  This simplifies the access to complex data.  But Gridsome does not combine Pages and Templates, because it is coded as two different lifecycle similar to how Gatsby/React does.

Gridsome is highly opinionated as to how routing, variable visibility, and lifecycle hooks are used, and Vuejs is only a rendering stage.  Thus, developer power is limited -- markdown contents do not automatically expand into Vuejs custom components, queries do not have Vuejs variables, and lifecycle hooks cannot be overridden by Vuejs hooks. But it is certainly possible to make Vuejs do more if we let it.
