### ISSUE TITLE
markdown excerpts 

### ISSUE THREAD

**Issue by roborich** [gridsome/gridsome#237]
## Summary
Currently the @gridsome/transformer-remark plugin extracts an `excerpt` field from gray-matter parser which is always empty.  

### Basic example
https://github.com/gridsome/gridsome/blob/48bf6004de6ee578eeea40871a0dbedb034a923a/packages/transformer-remark/index.js#L49

The `exerpt` field is always empty because no excerpt options are passed to the gray-matter function. (Options are passed as a second parameter. See https://www.npmjs.com/package/gray-matter#options)

This should either be removed or the excerpt functionality should be added.  As the `except` field appears in the graphql schema, and can never be used.

### Motivation

I can currently stand to benefit from excerpt functionality.  Specifically, I could benefit from having a small portion of my .md file's content pre-formatted, as I will be showing exerpts of posts in a "recent posts" section on my site.

I haven't dug into the code enough yet to know how we would pass excerpt options in, but I am willing to help contribute to this if it's something that would be helpful.

Currently gray-matter has two excerpt options
```js
exerpt // Boolean|Function
excerpt_separator // String
```
we could offer those as direct options to the remark plugin, or simplify gray-matter's somewhat wonky excerpt function api and allow a simple transform function to be used.  Where someone could pass something like...

```js
{
  transformers: {
    remark: {
      createExcerpt: (rawContent) => rawContent.split('\n')[0];
      // ... 
    },
  },
}
```

**Comment by roborich** [comment]
Made a PR #301

**Comment by apvarun** [comment]
Any update on this PR?

**Comment by jlabs** [comment]
Also interested in an update? 
Was hoping to use the excerpt field on a blog I'm making - have an idea of a workaround, but it's too hacky for my likings.

**Comment by sangeet** [comment]
You can use this function on any content field and generate excerpt during runtime. Strips out the HTML tags and extracts only the fiirst n characters.

Not the cleanest way to do things, but it's a handy utility.

```
    function generateExcerpt(textToStrip, length) {
      let regex = /(<([^>]+)>)/gi
      return textToStrip.replace(regex, "").slice(0,length)
    },
```

**Comment by noxify** [comment]
Here an alternative way to create the excerpt:

```js
//gridsome.server.js

  api.loadSource(({addSchemaResolvers}) => {
    addSchemaResolvers({
      Article: {
        excerpt(obj) {
          var longText = (obj.excerpt.length > 200) ? '...' : '';
          return obj.excerpt.replace(/^(.{200}[^\s]*).*/, "$1"+longText);
        }
      }
    })
  })
```

I found the replace function here: https://stackoverflow.com/a/5454297/2769836

**Comment by mtlynch** [comment]
Fixed in #1085

**Comment by D-Marc1** [comment]
Are there any plans to add this to Vue-Remark as well?

**Comment by songololo** [comment]
Another request for this functionality in Vue-Remark. Thanks.
