### ISSUE TITLE
remark-math

### ISSUE THREAD

**Issue by DavidCouronne** [gridsome/gridsome#238]
## Summary

For my blog, I need to use Katex. So I need to use remark-math parser.

The @gridsome/tranformer-remark don't allow to add a remark-parser, only plugins.

### Basic example

https://github.com/gridsome/gridsome/blob/78413dcedb3a7525043059764b6503ee0a419289/packages/transformer-remark/index.js#L43

In order to use remark-math, I transform manually

```
…
const math = require('remark-math')
….

this.toAST = unified().use(remarkParse).use(math).parse

```

So, I think it may be a good idea to add optionnal parser, in this way for example:

```
transformers: {
    remark: {
      parsers: [
        'remark-math'
      ],
      plugins: [    
        '@gridsome/remark-prismjs',
      ]
    }
  },
```

Or in the Gatsby way:

https://github.com/gatsbyjs/gatsby/blob/13cb764d64623e3bc63467a76d1c2006a5ee40c7/packages/gatsby-remark-katex/src/index.js#L23

**Comment by eleijonmarck** [comment]
@DavidCouronne have you managed to use katex in your blogs? Found your issue through obessive searching. I have setup a blog using [blog-starter](https://gridsome.org/starters/gridsome-blog-starter)

**Comment by DavidCouronne** [comment]
@eleijonmarck i found a way to manage katex:

Step 1:
```shell
yarn add remark-math remark-html-katex remark-html
```

Step 2: configuration

```js
remark: {
      plugins: [
        'remark-math',
        'remark-html-katex',
        'remark-html',
        '@gridsome/remark-prismjs'
      ]
    }
```

Step 3: Add CSS

In your template, `BlogPost.vue`for example:

```vue
<template>
  <Layout>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css" integrity="sha384-yFRtMMDnQtDRO8rLpMIKrtPCD5jdktao2TV19YiZYWMDkUR5GQZR/NOVTdquEx1j" crossorigin="anonymous">

...

</Layout>
</template>
```

Step 4: Write LaTeX :)

Inline Math:
```md
$x^2-3x+1$
```
Display Math:
```md
$$
\lim_{x \to +\infty}\frac{1}{x}=0
$$
```

**Comment by eleijonmarck** [comment]
@DavidCouronne I feel that I am missing something here.

My application becomes blank due to 'remark-math' plugin. :(

In the version I am using my configuration looks like the following:
```
module.exports = {
  siteName: 'test',
  siteDescription: 'test',

  plugins: [
    {
      // Create posts from markdown files
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'Post',
        path: 'content/posts/*.md',
        route: '/:slug',
        refs: {
          // Creates a GraphQL collection from 'tags' in front-matter and adds a reference.
          tags: {
            typeName: 'Tag',
            route: '/tag/:id',
            create: true
          }
        }
      }
    }
  ],

  transformers: {
    //Add markdown support to all file-system sources
    remark: {
      externalLinksTarget: '_blank',
      externalLinksRel: ['nofollow', 'noopener', 'noreferrer'],
      anchorClassName: 'icon icon-link',
      plugins: [
        'remark-math',
        'remark-html-katex',
        'remark-html',
        '@gridsome/remark-prismjs'
      ]
    }
  },
}
```

Removing 
```
'remark-math',
```

Makes the application render but again not using latex rendering.

**Comment by KingOfDireWolves** [comment]
@eleijonmarck Have you found a solution? I am having the same problem.
