### ISSUE TITLE
Transition not working

### ISSUE THREAD

**Issue by blumgart** [gridsome/gridsome#24]
Hi, in the Default.vue layout, if you wrap a slot in a transition, nothing happens. It just doesn't work. What am I doing wrong?

**Comment by hjvedvik** [comment]
You are not doing anything wrong :) The layout component is currently re-rendered on each route, so page transitions wont work. But it is something we really want to find a solution for before v1.0.

**Comment by edimitchel** [comment]
@blumgart I'm front of the same issue !
Please, provide another way to use layout without an entire rerendering :)

**Comment by sebastiancarlsson** [comment]
imho this information should be more visible in the docs. I skimmed the links on the left hand side of the site to get an overview of the features and saw "Page transitions", thought "great I'll get to that later", and set up my project, then browsed to that page and discovered that it's not supported lol 🤣

**Comment by altitudems** [comment]
FYI, you can get page transitions right now. 

Gridsome defines the root components render function here: https://github.com/gridsome/gridsome/blob/952148db357c2ca80db5977a90f6ffadd588601f/gridsome/app/app.js#L24

To add a transition tag you need to override the render property of appOptions in either the gridsome.client.js or /src/main.js
```javascript
export default function(Vue, { appOptions }) {
  // Wrap the router-view with a transition tag.
  // You could do the same with keep-alive etc.
  appOptions.render = h =>
    h(
      "transition",
      { props: { name: "page" } },
      // The router-view component as defined in 0.5.4
      [h("router-view", { attrs: { id: "app" } })]
    );
}
```

Then in some global css file, add your transition css
```css
.page-enter-active, .page-leave-active {
  transition: opacity .5s;
}
.page-enter, .page-leave-to {
  opacity: 0;
}
```

You can pretty much do everything else that you might need. Transition hooks, etc.

**Comment by robaxelsen** [comment]
@altitudems thanks for taking the time to share this, with helpful instructions! Closing this issue, as the question has been answered, and workaround given. As for your mention of @sebastiancarlsson "Page transitions" being mentions is listed in the docs, I understand the confusion. I don't see a better way of mentioning it in the docs though, as "enter transitions" are supported, and it's helpful with a docs section dedicated to that.

**Comment by Larsklopstra** [comment]
@altitudems Would it be possible to add it to the documentation as an experimental work around? I'd really like to use enter & leave transitions 😄

**Comment by rich-choy** [comment]
I was able to get wrap my `router-view` with a `transition` by following @altitudems workaround.
```
<transition name="some-transition">
  <router-view/>
</transition>
```

**Comment by rich-choy** [comment]
Thanks to @altitudems I was able to get both enter and leave transitions working.

`src/main.js`:
```javascript
import DefaultLayout from '~/layouts/Default.vue'
import App from '~/components/App';

export default function (Vue, { router, head, isClient, appOptions}) {
  appOptions.render = h => h(App);
  Vue.component('layout', DefaultLayout)
}
```

`components/App.vue`
```vue
<template>                                                                                                                                             
  <div id="app">
    <component v-bind:is="layouts[layout]"/>
  </div>
</template>

<script>
  import DefaultLayout from '~/layouts/Default';
  export default {
    props: {
      layout: {
        type: String,
        default: 'default',
      },
    },
    data () {
      return {
        layouts: {
          default: DefaultLayout,
        },
      };
    },
  };
</script>
```

`layouts/Default.vue`
```vue
<template>
  <div class="layout">
    <main-menu />
    <transition name="fade">
      <router-view/> 
    </transition>
  </div>
</template>

<script>
  import MainMenu from '~/components/MainMenu';
  export default {
    components: {
      MainMenu,
    },
  };
</script>

<static-query>
  query {
    metaData {
      siteName
    }
  }
</static-query>

<style>
  .fade-enter-active, .fade-leave-active {
    transition-property: opacity;
    transition-duration: 0.5s;
  }

  .fade-enter-active {
    transition-delay: 0.5s;
  }

  .fade-enter, .fade-leave-active {
    opacity: 0
  }
</style>
```

`src/pages/Index.vue`
```vue
<template>
  <div class="container">
    <g-image alt="Example image" src="~/favicon.png" width="135" />
    <h1>Hello, world!</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur excepturi labore tempore expedita, et iste tenetur suscipit explicabo! Dolores, aperiam non officia eos quod asperiores
    </p>
  </div>
</template>

<script>
  export default {
    metaInfo: {
      title: 'Hello, world!'
    }
  }
</script>
```

**Comment by edlefebvre** [comment]
@rich-choy Thank you for this solution! How would you extend this so that it works for a route change on a same template component?

For instance, having two WordPress posts using the same template component `templates/WordPressPost.vue`, changing the route between the two posts doesn't trigger the transition.

**Comment by codybarr** [comment]
> this solution! How would you extend this so that it works for a route change on a same template c

Also interested in a solution for this.

**Comment by yet-another-dev** [comment]
> > @rich-choy Thank you for this solution! How would you extend this so that it works for a route change on a same template component?
> > For instance, having two WordPress posts using the same template component `templates/WordPressPost.vue`, changing the route between the two posts doesn't trigger the transition.
> 
> Also interested in a solution for this.

From https://stackoverflow.com/a/55999879/1971662

```js
beforeRouteUpdate (to, from, next) {
    // called when the route that renders this component has changed,
    // but this component is reused in the new route.
    // For example, for a route with dynamic params `/foo/:id`, when we
    // navigate between `/foo/1` and `/foo/2`, the same `Foo` component instance
    // will be reused, and this hook will be called when that happens.
    // Explicitly calling `next` here forces the component to re-render.
   next()
}
```
