### ISSUE TITLE
how to set Syntax highlighting for code with remark-prismjs ?

### ISSUE THREAD

**Issue by yann-yinn** [gridsome/gridsome#242]
## Description
Hello, i tried to install remark-prismjs to highlight my code block but my code is still not highlighted. https://yineo.fr/post/animer-vos-transitions-de-page-facilement-avec-nuxt-js-et-vue-js
Shoud I include manually a js file ?

Here is my gridsome.config.js

```js
module.exports = {
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/posts/*.md',
        typeName: 'BlogPost',
        route: '/post/:slug',
        refs: {
          tags: 'Tag',
        },
        remark: {
          plugins: [
            '@gridsome/remark-prismjs'
          ]
        }
      }
    },
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/tags/*.md',
        typeName: 'Tag',
        route: '/tag/:id'
      }
    },
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/blocks/*.md',
        typeName: 'Block'
      }
    }
  ]
}
```

and my `package.json`

```js
{
//
  "dependencies": {
    "@gridsome/remark-prismjs": "^0.0.4",
    "@gridsome/source-filesystem": "0.3.0",
    "@gridsome/transformer-remark": "0.2.0",
    "axios": "^0.18.0",
    "gridsome": "^0.5.0",
    "striptags": "^3.1.1"
  },
//
}
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.0
- @gridsome/cli version: 0.0.7

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by hellocosmin** [comment]
Try adding the Remark plugin [globally](https://github.com/gridsome/gridsome-starter-blog/blob/4a2e536c909ae61bd69a1100b7870dd0a50b452e/gridsome.config.js#L31-L41) instead of on the collection.

**Comment by yann-yinn** [comment]
Will try that as soon as I can !  Correct me if i am wrong but the syntax I used is the first one on the documentation : https://github.com/gridsome/gridsome/tree/master/packages/remark-prismjs#usage

Are those instructions outdated ?

**Comment by hellocosmin** [comment]
I remember seeing an issue opened here about how Remark transformers didn't work when added to collections, can't remember why. I belive it's being worked on, but for now add it globally - as you can see, Gridsome does the same :)

**Comment by yann-yinn** [comment]
did not work for me. I checked Gridsome.org site, they use it in collections too : https://github.com/gridsome/gridsome.org/blob/master/gridsome.config.js

My html is correctly transformed in all cases, maybe am i supposed to include manually a css file ?

**Comment by yann-yinn** [comment]
PS : i gave up and used https://github.com/EldoranDev/gridsome-plugin-remark-shiki instead

**Comment by hellocosmin** [comment]
Yup, you'll need to add a Prism theme too, as you can see in the gridsome.org repo:

https://github.com/gridsome/gridsome.org/blob/abf67bd0a5b3bdb3afb73db1e34bf66076af3ee9/src/main.js#L2

Alternatively, you could also serve a theme file from a CDN - check this out:

https://github.com/evilfactory-community/rebase/blob/4bd22cceaddc83e6cd5f3e6fb7863c0fb0689140/src/main.js#L25-L29

But yeah, I also use Shiki :)

**Comment by yann-yinn** [comment]
ha thanks, i looked for css in assets and static directories, i did not think about main.js ... This is should be in the doc, i'm going to make a PR on that point
