### ISSUE TITLE
How to import scss in stylesheets?

### ISSUE THREAD

**Issue by NadiaRom** [gridsome/gridsome#246]
I have a typical project structure: `src/assets/scss/` folder, where in file `style.scss` I import `@import '/assets/scss/variables.scss'`. There are also links to fonts stored in `src/assets/fonts/`. It works fine if I import this scss in `.vue` component, but fails when import from `src/main.js`. Please help me to import it properly

**Comment by robaxelsen** [comment]
@NadiaRom how are you importing it? Would be helpful if you could share relevant code snippet from src/main.js.

**Comment by Devportobello** [comment]
@NadiaRom [Is this helping ](https://github.com/gridsome/gridsome/issues/71#issuecomment-446905270) ?

**Comment by robaxelsen** [comment]
Closed, as @NadiaRom [reported the problem resolved in another issue comment.](https://github.com/gridsome/gridsome/issues/71#issuecomment-470055497)
