### ISSUE TITLE
Firebase Firestore and its components Plugins

### ISSUE THREAD

**Issue by 1onedb** [gridsome/gridsome#250]
## Summary
I know its too early but it would be awesome to be part of the plugins

Brief explanation of the feature.
Integration of Firebase Components

### Basic example
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-firebase-firestore`,
      options: {
        // pass you Firebase credentials in here.
        credential: require("../firebase-env.json"),
        databaseURL: "https://dev-juice.firebaseio.com",
        // An array of the different Firestore resources you want to make available to Gatsby.
        types: [
          {
            // The TypeName - Will become `FirebaseLike` in Gatsby
            // *required*
            type: "Like",
            // The path to the resource in your Firestore database
            // *required*
            path: "likes",
            // Any additional Firestore queries
            // Default: (ref) => ref
            query: ref => ref.limit(50),
            // Use the map function to transform your nodes however you like.
            // Default: (node) => node
            map: node => {
              node.id = `like-${node.id}`
              return node
            },
          },
        ]
      }
    }
  ]
}

**Comment by u12206050** [comment]
@1onedb 
https://gridsome.org/plugins/gridsome-source-firestore
This uses Firebase's Firestore.

**Comment by robaxelsen** [comment]
Closing this as we already have (as @u12206050 pointed out :point_up:) a source plugin for firestore. Please reopen or create a new issue if you'd like to created enhancements/additions to this plugin.
