### ISSUE TITLE
Netlify Large Media integration

### ISSUE THREAD

**Issue by DerekAlanGilbert** [gridsome/gridsome#251]
## Description

Attempting to configure netlify large media to work with my gridsome, netlifyCMS site.

### Steps to reproduce

1. Have a gridsome site hosted on netlify with netlifyCms integrated.
2. Follow the netlify Large media docs step by step in integrating.
3. Run `git lfs track "static/youimagefolder/**"` , ( i also ran `git lfs track "*.jpg" "*.png"`)(which i think might have been my problem, undoing hasn't fixed however )
4. Attempt to push your changes live via github, etc. and your build with fail.

### Expected result

Build passes, Netlify Large media works.

### Actual result
 ```
netlify:
TypeError: Cannot destructure property 'width' of 'undefined' or 'null'.
5:46:23 PM:     at ImageProcessQueue.preProcess (/opt/build/repo/node_modules/gridsome/lib/app/queue/ImageProcessQueue.js:72:41)
5:46:23 PM:     at <anonymous>

locally: 
TypeError: ImageProcessQueue is not a constructor
    at new AssetsQueue (/node_modules/gridsome/lib/app/queue/AssetsQueue.js:11:19)
    at App.init (//node_modules/gridsome/lib/app/App.js:68:18)
```

### Environment

<pre><code>
Libs:
- @gridsome/cli v0.0.8
- gridsome v0.5.4

Browser:
- [ ] Chrome (desktop) version

For Tooling issues:
- Node version: v10.15.3  
- Platform: Mac
Others:

**Comment by DerekAlanGilbert** [comment]
## update

I was able to fix this problem. I tracked two files in the src directory because i ran `git lfs track "*.jpg" "*.png")`.

**Comment by tomtev** [comment]
@DerekAlanGilbert Thanks for the update :) Should we write something about Netlify Large Media integration in the docs? And could it be a plugin?
