### ISSUE TITLE
Pager styling

### ISSUE THREAD

**Issue by Berkmann18** [gridsome/gridsome#257]
## Description

I've seen [here](https://alligator.io/vuejs/gridsome-list-posts/#adding-pagination) that `Pager` has a `:linkClass` property which allows me to style the links like how one would do with `:class` in VueJS.

### Steps to reproduce

Follow [this tutorial](https://alligator.io/vuejs/gridsome-list-posts) then add ` :linkClass="{ pageNum: true }"` to `<Pager ... />`.

### Expected result

The links should have a `pageNum` class.

### Actual result

The links have a `[object Object]` class.

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.4
- @gridsome/cli version: 0.0.8

Browser:
- [X] Chrome (desktop) version 72.0.3626.121
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v11.0.0
- Platform:  Ubuntu WSL on Windows 10

Others:

</code></pre>

**Comment by tomtev** [comment]
Hi @Berkmann18 ,
What class are you trying to add? :linkClass should be something like `:linkClass="my-custom-link-class""

**Comment by Berkmann18** [comment]
Hi @tomtev I'm trying to add the `pageNum` class.
I tried using `:linkClass=pageNum` but it resulted in an empty `class` on the rendered HTML links.

**Comment by hjvedvik** [comment]
This should work better in version `0.5.5`.

**Comment by Berkmann18** [comment]
Awesome, it works now.

**Comment by BobWalsh** [comment]
but is not working in 7.7:
```
<Pager :info="$page.posts.pageInfo",:linkClass="my-custom-link-class" />```

yields:

<nav role="navigation" aria-label="Pagination Navigation">
<a href="/" class="active--exact active" aria-label="Current page. Page 1" aria-current="true">1</a><a href="/2/" class="" aria-label="Go to page 2">2</a>
<a href="/3/" class="" aria-label="Go to page 3">3</a>
<a href="/2/" class="" aria-label="Go to next page. Page 2">›</a>
</nav>
```
no observable my-custom-link-class.

**Comment by karltynan** [comment]
I am also seeing this issue in `0.7.13`:

```
<Pager :info="$page.allPost.pageInfo" :linkClass="text-blue-500" />
```

The above code returns an empty class attributes on the links:

```
<nav role="navigation" aria-label="Pagination Navigation">
   <a href="/blog" class="" aria-label="Go to previous page. Page 1">‹</a>
   <a href="/blog" class="" aria-label="Go to page 1">1</a>
   <a href="/blog/2" class="active--exact active" aria-label="Current page. Page 2" aria-current="true">2</a><a href="/blog/3" class="" aria-label="Go to page 3">3</a>
   <a href="/blog/3" class="" aria-label="Go to next page. Page 3">›</a>
</nav>
```

**Comment by soongsta** [comment]
> my-custom-link-class

i was confused as well but you have to pass an object like below

`
<Pager :info="$page.posts.pageInfo" :linkClass="{ 'my-custom-link-class': true }" />
`

**Comment by soongsta** [comment]
correction, the following works

`<Pager :info="$page.posts.pageInfo" :linkClass="`my-custom-link-class`" />`

**Comment by karltynan** [comment]
You only need `:linkClass=""` (notice the ":") if you are doing something programmatic like checking if something is `true` or `false`. Try `linkClass="my-custom-class"` without the ":" instead.
