### ISSUE TITLE
Run in Cloud, Automatic Build & Deploy on Content Change in CMS

### ISSUE THREAD

**Issue by GrayAnchor** [gridsome/gridsome#258]
## Summary

Is it possible to run Gridsome in the cloud so that on content change in a headless CMS (Netlify CMS, for example), Gridsome builds and deploys the site automatically? I'm new to the Jamstack world, so I apologize if this is out of scope and/or is otherwise a simple question.

### Basic example

Use case: client updates a blog post in Netlify CMS and Gridsome(running in the cloud) 'sees' the update, and then runs the build and deploy processes.

### Motivation

This is the functionality I'm looking for as a direct replacement for a traditional CMS, where clients can update content from any web browser, and the build process is automatic, without developer involvement.

**Comment by msgeissler** [comment]
Not sure this is something Gridsome itself is going to implement (please correct me if I am wrong), as it is using source-plugins to query the data. So this would be something each source plugin would have to implement with regard to all the different technologies they support (filesystem, GraphQL, REST etc.). Furthermore it is "just" a static website generator, it is not really a server that is continually running (except for the development mode, but that has a different purpose). What you have in your cloud is most likely some static webserver hosting your pre-compiled pages.

What you are looking for, I think, is something commonly known as _webhooks_ and this would be something your CMS (most likely already) supports. Webhooks usually allow you to call or send data to a specified URL (most likely a CI in your case) for different events in your CMS, which then in turn could rebuild and redeploy your site.
E.g. GitLab has pipeline triggers, which are basically special URLs you can generate for your project to remotely trigger a certain job (build, deploy etc.).

So your use-case is basically already possible, but most likely out-of-scope for Gridsome.

**Comment by GrayAnchor** [comment]
Ok, thanks for the insight. Yes, it sounds like webhooks support is what I'm looking for - a way to trigger the build process from the CMS. Could an Express server run the build process when a certain URL endpoint is hit by the CMS? I mention Express because it's the only node server I'm somewhat familiar with, but if any other type of node server would work better I would be interested. Thanks again.

**Comment by tomtev** [comment]
@GrayAnchor Netlify can do this for you :) https://www.netlify.com/docs/webhooks/

**Comment by msgeissler** [comment]
Hmm, I haven't really worked with Express and haven't touched it in quite a while, but I don't think that is an approach I would recommend or have ever come across yet. You would most likely have to implement the whole build steps inside of your Express server, install all dependencies into it(!) and then securely expose a URL for that. Not something I would personally do for a website or blog (or at all for that matter).

Depending on your actual setup, there are also some potential problems with that:
Are you running a single instance in the cloud? If not, you will have a problem updating all instances with that approach (you would need to sync the changes across the cluster).
Do you have persistent storage for your cloud server (which is not a given)? If not, you will likely lose your changes if your instance switches to a new machine in the cloud.

What is your current setup? How are you delivering your changes at the moment? Or are you still in the planning phase?
You could also have a look at CI / CD (continuous integration and continuous delivery) if you are not familiar with those yet. At least that would be my approach (details would vary widely depending on the selected technology stack), but I not using any 3rd party CMS offers.

**Comment by msgeissler** [comment]
Btw Netlify has two different offers: Netlify CMS and Netlify (as a hosting service).

The CMS can be added to your project using this tutorial https://www.netlifycms.org/docs/add-to-your-site/
and then you can build and host it using Netlify https://www.netlify.com/docs/continuous-deployment/

The Netlify will store its data in your Git repository which in turn is linked to the Netlify hosting service. Using a config file you can let Netlify know how to build a Gridsome project and where to find the files for the static hosting.

That is if you wish to go to the Netlify route. There are many other possibilities as well.

**Comment by GrayAnchor** [comment]
It sounds like Netlify is probably what I'm looking for without diving into CI/CD. Good to know their build functionality can work with Gridsome. It looks very promising. Thank you!

**Comment by robaxelsen** [comment]
Closing, as question in OP has been addressed. @GrayAnchor: feel free to reopen if you have further questions related to this.
