### ISSUE TITLE
Allow access to client options in loadSource-method

### ISSUE THREAD

**Issue by msgeissler** [gridsome/gridsome#260]
## Summary

I want to be able to access client options in the gridsome.server.js `api.loadSource`-method the same way the core plugin does https://github.com/gridsome/gridsome/blob/master/gridsome/lib/plugins/core/index.js

Currently this does not work, because the actual options are undefined in the `options`-object.

### Basic example

E.g.:
```js
module.exports = function (api, options) {
  api.loadSource(store => {
    store.addMetaData('siteDescription', options.siteDescription)
  })
}
```

### Motivation

Allow developers to make client options available via the `metaData` schema to avoid duplication.

**Comment by msgeissler** [comment]
Follow up to #259.

**Comment by hjvedvik** [comment]
The `options` argument is the plugin options. You have access to the project config at `api.config`. But we are going to add a [meta data config](https://github.com/gridsome/gridsome/issues/225) where you can have any data in `0.6`. That will make it much easier to add meta data :)

**Comment by msgeissler** [comment]
`api.config.siteDescription` works like a charm!
I saw #225 but I somehow misunderstood the part
>Maybe siteName, siteDescription and siteUrl also can be moved into metaData.


Did I miss something in the documentation or would this be something that will be added to the documentation later on?

**Comment by hjvedvik** [comment]
I meant that `siteName`, `siteDescription` and `siteUrl` can be metadata instead of root config properties. But I think we'll keep them where they are now. And `api.config` isn't part of the public API yet, but we have no plans to change it. So we'll probably document it sometime later.

**Comment by smakinson** [comment]
Is the config accessible from main.js? I'd like to get at `siteUrl` for some full url meta like opengraph images, etc.

**Comment by ndom91** [comment]
Looking to acess `siteUrl`, `siteDescription`, etc. in `main.js` as well, but haven't found a way to do it. Is it possible?
