### ISSUE TITLE
Can't use Middleware in Gridsome

### ISSUE THREAD

**Issue by petar7777** [gridsome/gridsome#261]
## Summary

I would like to use middleware in Gridsome like Nuxt.

**Comment by tomtev** [comment]
Hi @petar7777. Gridsome can't do middleware. It's not an SSR framework like Nuxt. You can only do stuff after page load (client side). So if you need authentication etc. you'll need to check after page load and then redirect the user.

**Comment by petar7777** [comment]
@tomtev 
Thanks for your reply.
Now I have many pages with different layouts in Gridsome.
And I am using Vuex store in my project.
I am using same GraphQL in two layout(default and other layout) and save the fetched data to store in every layout.
So the way is duplicated in two layout.
I would like to implement this logic without duplication.
Where should I put this logic after fetch data using GraphQL?
The code is following:
`
<static-query>
    query OtherLayoutQuery ($page: Int) {
        allArticle (page: $page, sortBy: "pubdate", order: DESC) {
            edges {
                node {
                    title
                    author
                    pubdate
                    img
                    snip
                    language
                    path
                    likes
                    tags
                    category
                }
            }
        }
    }
</static-query>
<script>
export default {
mounted() {
                this.$store.commit('setAllArticles', this.$static.allArticle.edges)
        }
}
</script>
`

**Comment by petar7777** [comment]
OK. I decided to use Mixin in my two layouts.
But I can use the Mixin only for the `mounted()` function.
How can I use the GraphQL without duplication in two layouts?

**Comment by farnetani** [comment]
I need my blog to have authentication, this is possible, does anyone have any examples of how to embed a login / password to read the posts without using third party applications like netfly?

**Comment by donPuerto** [comment]
@petar7777 how to set up mixins in gridsome, got an error?
