### ISSUE TITLE
import json file in to graphql

### ISSUE THREAD

**Issue by hamidsouth** [gridsome/gridsome#262]
hi how can import json file ? i have tried this

```
module.exports = function (api) {
  api.loadSource(store => {
    // Use the Data store API here: https://gridsome.org/docs/data-store-api
    const data = '~/data/countries.json';
    const contentType = store.addContentType({
	    typeName: 'CountriesSelect',
	});
    for(const item of data){
    	contentType.addNode({
	        id: item.id,
	        title: item.countryCode,
	        date: item.created_at,
	        content: item.countryName
	     })
    }
  })
}
```
But no luck.

**Comment by hjvedvik** [comment]
You can use `require`, like this:

```js
const data = require('./data/countries.json');
```

**Comment by hamidsouth** [comment]
> You can use `require`, like this:
> 
> ```js
> const data = require('./data/countries.json');
> ```

Well i tried it but when restart the gridsome develop, it cannot find the module.

**Comment by hjvedvik** [comment]
The path depends on where you have the `countries.json` file. I assumed you had it in a `/data` folder, but since you tried with `~/` you might have it in `/src/data`? If so, use `require('./src/data/countries.json')`.

**Comment by hamidsouth** [comment]
> The path depends on where you have the `countries.json` file. I assumed you had it in a `/data` folder, but since you tried with `~/` you might have it in `/src/data`? If so, use `require('./src/data/countries.json')`.

Thank you. That worked

**Comment by hamidsouth** [comment]
> > The path depends on where you have the `countries.json` file. I assumed you had it in a `/data` folder, but since you tried with `~/` you might have it in `/src/data`? If so, use `require('./src/data/countries.json')`.
> 
> Thank you. That worked

Another error after, 

> vue-router.esm.js?8c4f:10 Uncaught Error: [vue-router] "path" is

**Comment by hjvedvik** [comment]
Okay. You can read about routing [here](https://gridsome.org/docs/routing#routing-for-custom-data-sources). You have to either give the content type a route (eg. `/countries/:title`) or have a path on each node (eg. `/countries/no`).
