### ISSUE TITLE
Navigation guard not working?

### ISSUE THREAD

**Issue by Paperasse** [gridsome/gridsome#264]
According to docs Gridsome uses Vue Router. I am trying to hook in a component into the navigation guard "beforeRouteUpdate" to do something when the route has changed. Seems that the hook is not called. At the moment, the only thing I do is write to the console. But nothing is showing up in the web console. Are the navigation guards available in Gridsome.

**Comment by hjvedvik** [comment]
Which component are you using the `beforeRouteUpdate` hook? It should work in pages and templates. `beforeRouteUpdate` is only called when the same route updates. Static routes only call `beforeRouteEnter`.

**Comment by Paperasse** [comment]
I am using the gridsome-starter-blog template. It has a component "Logo" which is used/imported in the layout. I have the navigation guard setup in that component, so it not in a page or template. The component is a kind of navbar. I want to access the router to create a bread crumb.

**Comment by hjvedvik** [comment]
The router hooks are only called for the route components (pages or templates). But you can probably use `this.$route` in a computed property to generate a breadcrumb in any component. And the router is available at `this.$router`.

**Comment by Paperasse** [comment]
Ok, I am going to give it a try. I am creating a web site for a small health care company. This is a development version: https://dz-e5fe18.netlify.com. I am thinking of creating a starter from this. Site is in Dutch language.

**Comment by Paperasse** [comment]
Ok, that works. Thanks 👍
