### ISSUE TITLE
Wordpress content never updates after first fetch

### ISSUE THREAD

**Issue by andrewhl** [gridsome/gridsome#268]
## Description

I've created a Gridsome project with [gridsome-starter-wordpress](https://github.com/gridsome/gridsome-starter-wordpress). All I've done is set up `gridsome.config.js` `baseUrl` to point to my Wordpress site.

When I run `gridsome develop`, it displays the my wordpress site's posts the first time. Any subsequent changes I make to the posts, via the wordpress admin, are not reflected on the Gridsome site. It seems to cache the first content response and never updates it thereafter.

### Expected result

The content should update when I modify content on the wordpress site, or at least upon rerun of `gridsome develop`.

### Actual result

Wordpress content never updates.

### Environment

Libs:
- gridsome version: 0.4.0
- @gridsome/source-wordpress: 0.1.0
- @gridsome/cli version: 0.0.8

Browser:
- [x] Chrome (desktop) version 72.0.3626.121 

For Tooling issues:
- Node version: 11.3.0
- Platform: Mac

**Comment by hjvedvik** [comment]
Update `gridsome` and `@gridsome/source-wordpress` to the latest versions and see if it works better.

**Comment by andrewhl** [comment]
@hjvedvik I updated to 
gridsome version: 0.5.5
@gridsome/source-wordpress: 0.2.1

After rerunning yarn I observed that it updated the content. However, subsequent changes to the wordpress site did not update. I wonder if this is some kind of cached response on the server's end?

**Comment by hjvedvik** [comment]
Gridsome loads content at startup and there is no way to detect changes in WordPress. We might create a helper plugin for WordPress sometime, but for now, you must restart to update.

**Comment by andrewhl** [comment]
@hjvedvik I'm killing my local dev server and rerunning `gridsome develop`, and also trying to redeploy the `/dist` folder to Netlify by first rerunning `gridsome build`. Am I not using the right approach to restarting the app?

**Comment by NickStees** [comment]
@andrewhl what you are doing is correct, you have to trigger a build `gridsome develop` or `gridsome build` and Gridsome will fetch the latest content from Wordpress only on build. To keep it up to date you can use [Webhooks in Netlify](https://www.netlify.com/docs/webhooks/) to "trigger" a rebuild of your static site [here is a guide that you can adapt for Gridsome](https://www.efficiencyofmovement.com/publish-a-wordpress-post-with-gatsbyjs-on-netlify/).
