### ISSUE TITLE
Netlify CMS Documentation (guide)

### ISSUE THREAD

**Issue by Larsklopstra** [gridsome/gridsome#273]
## Summary

Writing the documentation on how to implement the Netlify CMS for the default starter scaffold.

### Motivation

It's really useful and there aren't full guides anywhere else yet, I'd like to help out on this part

**Comment by Larsklopstra** [comment]
@robaxelsen Where would you like to see the documentation being added?

**Comment by robaxelsen** [comment]
@Larsklopstra I am a bit unsure (reading from your issue description) exactly what you want to document in regards to Netlify CMS. Adding Netlify as a source, deploying to Netlify, or something else?

For deployment, I would suggest adding to the existing section in the docs:

For source usage, I am not entirely sure. Either a guide that can be added to the docs, a blog post of your own, or [help improve the documentation of the existing Netlify source plugin.](https://github.com/gethypervisual/gridsome-plugin-netlify-cms)

**Comment by Larsklopstra** [comment]
@robaxelsen I wrote a full guide on how to implement Gridsome with Netlify CMS using GitHub as auth & source provider

**Comment by Larsklopstra** [comment]
https://github.com/gridsome/gridsome.org/pull/104
