### ISSUE TITLE
Single Page Query Returning Null

### ISSUE THREAD

**Issue by stolinski** [gridsome/gridsome#274]
## Description

Describe the issue that you're seeing.

Querying 
```
  page(_id: "1") {
    slug
  }
```

with 3 pages existing returns 

```
    "page": {
      "slug": null
    }
```
where a query for allPages returns the slug correctly.

### Steps to reproduce

`gridsome create new-app`

Then head to GraphQL playground and query for 

```
  page(_id: "1") {
    slug
  }
```

### Expected result

What should happen?

Should return object with slug equal to about or index.

### Actual result

What happened.

See above.

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8

**Comment by hjvedvik** [comment]
The `page` and `allPage` root fields are very outdated compared to the fields which are generated by the data store API. But we are working on that part of the schema so it will most likely change and give better information in one of the upcoming versions :)

**Comment by stolinski** [comment]
I'm not sure what you mean. This is querying for a single page. That single page query is not returning the correct data ie. null instead of the slug. The `allPage`  query returns the slug correctly. Why would the `page` query and the `allPage` query not have access to the same data?

**Comment by hjvedvik** [comment]
I meant that `page` and `allPage` should probably be removed from until we have a good schema for them. Each page has a unique generated id, so it can be hard to query for a single page. You will see the id's if you include an `id` field when you query for `allPage`.

**Comment by stolinski** [comment]
Gotcha. I'm currently recording a tutorial series and am showing page and allPage. We aren't using them for anything other than graphql basic concepts, but would be a bummer if they are removed entirely now. Not trying to query on pages for any practical reason (although it would be good for the main nav). I did see the `id` on the field, just thought that slug existing on the listing but not the individual query was odd.

**Comment by hjvedvik** [comment]
Cool :) You could show the `metaData` field instead. It doesn't have much data out of the box, but does work and will not be removed.

**Comment by stolinski** [comment]
I actually did, but I also showed allPage (already recorded). I can record an insert clip that mentions that they are for demonstration and might not exist in the future.
Thanks!

**Comment by hjvedvik** [comment]
Great! Looking forward to watching the tutorial :)

**Comment by Defite** [comment]
So how can I query data for single page now? I have page content in `content/pages`, but I can't query contents of `.vue` files inside it, because every time I have `title: null`.

**Comment by Kainkainkain** [comment]
This worked for me- 
I was attempting something different, which was to return children of an ID and the page of the ID also. 
I'm sure you can customise for your needs. 

# Write your query or mutation here
query Pages {
  parentpage: allPages (filter: { id: { regex: "12" } }) {
    totalCount
    pageInfo {
      currentPage  
    }
    edges {
      node { 
         
        id
        title {
          rendered
        }
        link
      }
    }
  }
  pages: allPages (filter: { parentid: { eq: 12 } }) {
    edges {
      node { 
        id
        title {
          rendered
        }
        link
      }
    }
  }
	

  

}
