### ISSUE TITLE
`_raw` route params shouldn't be converted to string

### ISSUE THREAD

**Issue by vberlier** [gridsome/gridsome#277]
## Description

[`path-to-regexp`](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp) allows you to generate paths with non-string parameters such as arrays and integers. For example, dynamic path segments require the parameter to be an array:

```js
const toPath = pathToRegexp.compile('/:pathSegments+')
console.log(toPath({ pathSegments: ['a', 'b', 'c'] }))
// Output: '/a/b/c'
```

The problem right now is that Gridsome [converts every parameter to a string](https://github.com/gridsome/gridsome/blob/dea7e8ecf13fc82fdb422ecea8069c6e166cd163/gridsome/lib/app/ContentTypeCollection.js#L304), even the `_raw` versions that are [supposed to contain the original value](https://gridsome.org/docs/routing#route-params). This means that the current behavior is analogous to the following:

```js
console.log(toPath({ pathSegments: String(['a', 'b', 'c']) }))
// Output: '/a%2Cb%2Cc'
```

### Steps to reproduce

Setup an example content type:

```js
// gridsome.server.js

module.exports = function (api) {
  api.loadSource(store => {
    const examples = store.addContentType({
      typeName: 'Example',
      route: '/example/:pathSegments_raw+'
    })

    examples.addNode({
      fields: {
        pathSegments: ['a', 'b', 'c']
      }
    })
  })
}
```

### Expected result

Run the following query in the playground:

```graphql
{
  allExample {
    edges {
      node {
        path
      }
    }
  }
}
```

The expected response would be:

```json
{
  "data": {
    "allExample": {
      "edges": [
        {
          "node": {
            "path": "/example/a/b/c"
          }
        }
      ]
    }
  }
}
```

### Actual result

Gridsome turns the `pathSegments` array into a string (`'a,b,c'`) which then gets encoded by path-to-regexp (`'a%2Cb%2Cc'`), and returns the following response:

```json
{
  "data": {
    "allExample": {
      "edges": [
        {
          "node": {
            "path": "/example/a%2Cb%2Cc"
          }
        }
      ]
    }
  }
}
```

### Environment

<pre><code>Libs:
- gridsome version: 0.5.5
</code></pre>

**Comment by vberlier** [comment]
Potential solutions for this problem:

- Skipping string conversion for parameters with the `_raw` suffix
- Introducing another suffix for the actual value of the field
- Skipping string conversion and slugification if the parameter is not a string

I'd be happy to work on a pull request.

**Comment by robaxelsen** [comment]
@vberlier Sounds good to me, but I am not to deep into this to comment on the specific issue.

@hjvedvik any comment?

**Comment by vberlier** [comment]
Awesome! Which solution should I implement?

**Comment by hjvedvik** [comment]
Would it be an idea to convert the array into segments only if the key has `repeat: true`, eg. `/path/:segments+`? We could also slugify each value in the array when not using the `_raw` suffix, maybe. And `/path/:segments` would just work as it does now.

**Comment by vberlier** [comment]
> if the key has `repeat: true`

Like this?

```js
const segments = ['a', 'b', 'c']
segments.repeat = true

examples.addNode({
  fields: { segment }
})
```

**Comment by vberlier** [comment]
Wait nevermind I got it:

```js
const keys = []
const regexp = pathToRegexp('/path/:segments+', keys)
console.log(keys[0].repeat)
// Output: true
```

**Comment by hjvedvik** [comment]
Yes, that's what I meant :) Can use that info when generating the paths [here](https://github.com/gridsome/gridsome/blob/master/gridsome/lib/app/ContentTypeCollection.js#L281).

**Comment by vberlier** [comment]
Okay sounds great! I'm going to start working on this :+1:
