### ISSUE TITLE
Cannot access this.$static.metaData in a vue component's data (script portiong of component.vue file)

### ISSUE THREAD

**Issue by mjatharvest** [gridsome/gridsome#278]
Hi there folks, dipping my toe into gridsome and have a question:

I cannot access this.$static.metaData in a vue component's data

It is available in the created hook and in the template section of the .vue however

What am I missing?

`
```
  <template>
      <div>
  	<!-- displays ok here -->
	{{$static.metaData.globalPhone}}
  </div>
  </template>

<static-query>
query {
  metaData {
    globalPhone
  }
}
</static-query>

<script>
export default {
  data () {
    return {
    	/* undefined here */
      text: 'phone ' + this.$static.metaData.globalPhone
    }
  },
  created () {
	/* available here */
    console.log(this.$static.metaData.globalPhone)
  }
}
</script>

<style></style>
```
`

**Comment by hjvedvik** [comment]
That's because `$static` is a computed property and doesn't exist when Vue runs the `data` function. You can create a computed property that uses `$static.metaData.globalPhone` like:

```js
export default {
  computed: {
    globalPhone () {
      return 'phone ' + this.$static.metaData.globalPhone
    }
  }
}
```

**Comment by mjatharvest** [comment]
Thanks for the quick reply.

Instead of storing text content references globals in a vue components data, perhaps I should store it in a local file and query for it. Would that be a better approach?

**Comment by robaxelsen** [comment]
@mjatharvest I see no problem with your flow in the example code, but I'll let @hjvedvik weigh in if he has a different opinion.

Keep in mind that GraphQL acts as a middle layer here, only available in the build process. So using a local file that you fetch via GraphQL in the build process, won't change things. 

Depending on the size of your app, you could always use vuex, which makes it easier to have a clean and consistent flow of data in your app. That way you have one (or several with vuex modules) place to store data.

**Comment by robaxelsen** [comment]
Closing this issue, as the original question has been answered, but feel free to reopen if you have more questions.

@hjvedvik feel free to add to (or correct) my answer, and reopen if needed.
