### ISSUE TITLE
Question: Installation error

### ISSUE THREAD

**Issue by Developerayo** [gridsome/gridsome#280]
Local server not starting say's `Unknown command develop` why?
I'm using the gridsome starter

```
$ gridsome develop
Unknown command develop
Done in 0.67s
```

**Comment by cossssmin** [comment]
Have you installed the CLI? You need it installed globally in order to access the command like that. 

`npm install -g @gridsome/cli`

**Comment by Developerayo** [comment]
The CLI is installed

**Comment by cossssmin** [comment]
If it says `unknown command`, then it means it can’t find it in your system’s $PATH. Are you sure you installed the CLI globally?

**Comment by Developerayo** [comment]
Yes, I just ran it again take a look @cossssmin 

```
$ npm install -g @gridsome/cli
C:\Users\ayo\AppData\Roaming\npm\gridsome -> C:\Users\ayo\AppData\Roaming\npm\node_modules\@gridsome\cli\bin\gridsome.js
+ @gridsome/cli@0.0.8
updated 1 package in 32.2s
```

**Comment by cossssmin** [comment]
Apologies, my mistake - what I said would have applied if it complained about `gridsome`, not `develop`.

I'm not able to reproduce that on my end with latest Gridsome (0.5.5). This might sound dumb, but just to check: you _are_ running `gridsome develop` inside the project directory, right?

**Comment by msgeissler** [comment]
@Developerayo did you execute `npm install` inside the project folder? You have to install all project dependencies first. Sadly the documentation is missing that step and the reported error message is also not very helpful.

**Comment by robaxelsen** [comment]
@Developerayo does `npm install` solve the issue for you?

**Comment by Developerayo** [comment]
Yes it does.

**Comment by Developerayo** [comment]
Thanks everyone

**Comment by jhalmu** [comment]
OS: MX Linux 18.1
1) Installing with yarn global -command, do not work, do not find gridsome. Installing without global works
2) Cant find gridsome develop -command. But  yarn gridsome develop starts developing.

Thank you. Putting this here. Maybe you can look in to it and update code or docs?

**Comment by rdsmarketing** [comment]
I made the mistake of running yarn to install the dependencies as well. It seems if you start with yarn or npm you have to stick with that or update packagelock.json
