### ISSUE TITLE
Feature request: Transformer for CSV

### ISSUE THREAD

**Issue by arjunchib** [gridsome/gridsome#282]
## Summary

A transformer similar to json and yaml, but for csv.

### Basic example

```javascript
const csvParse = require('csv-parse/lib/sync')

class CSVTransformer {
  static mimeTypes () {
    return ['text/csv']
  }

  parse (source) {
    const records = csvParse(source, {
      columns: true,
      skip_empty_lines: true
    })

    const fields = { records }

    return { fields }
  }
}

module.exports = CSVTransformer
```

This would parse a CSV source using csv-parser, using the first line for columns names. The parser creates an array of record objects. Each object has keys-value pairs corresponding to each entry's column name and value. This array is then returned as part of fields.

The records can then be queried like so
```
allFileNode {
  edges {
    node {
      records {
        column 1
        column 2
        column 3
      }
    }
  }
}
```
### Motivation

This will allow CSV data sources to be added and queried.

**Comment by vberlier** [comment]
I don't think this necessarily needs to be part of the official repository. Plugins and transformers are meant to be built and maintained by the community. Some of them are officially supported, but it shouldn't be too difficult to write your own and publish it on npm :+1:

**Comment by hjvedvik** [comment]
`CSV` is a pretty common format and would be nice to have it as a core plugin. So a PR is welcome :)
