### ISSUE TITLE
Mozjpeg dep issue

### ISSUE THREAD

**Issue by Truemedia** [gridsome/gridsome#287]
When creating a new gridsome instance I now get this error when installing node modules via yarn

ENONET: No such file lstat, mozjpeg (bunch of weird Unicode characters printed out).

I’ve seen this is also an issue with Gatsby and reported on there repo too.

**Comment by hjvedvik** [comment]
@Truemedia Is this still an issue with Gridsome 0.6?

**Comment by Truemedia** [comment]
@hjvedvik This was resolved as far I remember. Wasn't able to replicate recently when using new build.
