### ISSUE TITLE
Vue-Tilt.js Error

### ISSUE THREAD

**Issue by vdiaza** [gridsome/gridsome#290]
I am trying to add this plugin Vue-Tilt.js to my project, which works fine on development, but when I try to do gridsome build I get this error: 

workspace/gridsome/node_modules/vue-tilt.js/src/index.js:12
import VanillaTilt from 'vanilla-tilt';
       ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

I tried implementing a "fix" I saw in another thread:
	api.chainWebpack((config, { isServer }) => {
		if (isServer) {
			config.externals([
				nodeExternals({
					whitelist: [/^vue-tilt/]
				})
				])
		}
	})

which moved me to another error within the same plugin:

eferenceError: window is not defined
    at assets/js/app.d19e96e2.js:939:3
    at Object.<anonymous> (node_modules/vue-tilt.js/src/_polyfills.js:18:1)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.module.exports.CustomEvent (node_modules/vue-tilt.js/src/index.js:9:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (src/main.js:5:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (node_modules/gridsome/app/main.js:4:9)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (node_modules/gridsome/app/app.js:3:0)

Here is how i have the plugin setup:

import DefaultLayout from '~/layouts/Default.vue'
import VueTilt from 'vue-tilt.js'

export default function (Vue, {router, head, isClient}) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)
  Vue.use(VueTilt)
}

Let me know if you have any solution for this kind of errors, thanks!!

**Comment by tomtev** [comment]
Hi @vdiaza , the problem is that the plugin is not SSR compatible. You could try to run it inside a `<client-only>` tag?

**Comment by vdiaza** [comment]
@tomtev the problem is that i am not sure how to incorporate it into the project, since if I use Vue.use(VueTilt) it gives me an error.

I tried incorporating it into a component as gridsome explained for non SSR plugins like this:

`  VueTilt: () => 
      import ('vue-tilt.js')
      .then( m => m.VueTilt )
      .catch()`

but the problem is that the plugin is used as a directive, not a component. So I think this is not the proper way to include it into the project.

**Comment by gilesbutler** [comment]
Hey @vdiaza, I just had a similar issue with `vue-scrollama` as it requires the `window` object to be available.

The issue could possibly be that you're not importing the default export. This might need to be added to the docs too. But try this...

`VueTilt: () => import ('vue-tilt.js') .then( m => m.default ) .catch()`

---

@tomtev the examples in the [docs](https://gridsome.org/docs/assets-scripts/?#without-ssr-support) show:
```
Carousel: () =>
        import ('vue-carousel')
        .then(m => m.Carousel)
        .catch(),
```
Is there a reason it points to `m.Carousel`? Thoughts on changing this to `m.default`? This worked for me and I think it's correct as node modules usually have a `default` prop for exports but I'm not 100% certain. I'm happy to do a PR though if we think it's correct.

**Comment by jaahoo** [comment]
> but the problem is that the plugin is used as a directive, not a component. So I think this is not the proper way to include it into the project.

I find workaround with VanillaTilt.
First add VanillaTilt
`npm install vanilla-tilt` 
In your component put to **mounted** hook
```javascript
window.VanillaTilt = require('vanilla-tilt');
VanillaTilt.init(this.$refs.tilt);
```
and finally put **ref="tilt"** on element you want to tilt

**Comment by robaxelsen** [comment]
@tomtev please see question from @gilesbutler above, and imo this issue can be closed when that's addressed.

**Comment by hjvedvik** [comment]
@gilesbutler The example in the docs points to `m.Carousel` and `m.Slide` because the default export from `vue-carousel` is an installer object which should be passed to `Vue.use()`. But usually, `m.default` is the actual component.

**Comment by gilesbutler** [comment]
Nice one, thanks for clarifying @hjvedvik 👍
