### ISSUE TITLE
Feature request: Vue Typer, VueTilt & Any Vue Flex library

### ISSUE THREAD

**Issue by vdiaza** [gridsome/gridsome#291]
Hi,
I'm in the process of building a site through gridsome, and I was testing different libraries that didn't work when I tried to build my app.

Here are some that would be great if they could be incorporated to Gridsome:

[Vue Typer](https://www.npmjs.com/package/vue-typer)
[VueTilt](https://www.npmjs.com/package/vue-tilt.js)
[Vue-Flex](https://www.npmjs.com/package/vue-flex)

Thank you!

**Comment by SteveEdson** [comment]
Have you tried importing them into your layout, and setting them up in the `mounted` hook? E.g. the `Vue.use(...);` bit.

Gridsome will do server side rendering on your app, and if the Vue plugins rely on `window`, they will encounter errors. The mounted method only gets triggered on the client side version of the site.

**Comment by cossssmin** [comment]
Those components look like they don't support SSR. In addition to what Steve said, read the Gridsome docs on scripts without SSR support:

https://gridsome.org/docs/assets-scripts#without-ssr-support

**Comment by vdiaza** [comment]
Thank you I was able to add the VueTyper plugin through that guide, 
but I still having issues tying to add the VueTilt plugin. since it is not a whole component, just a property you add to a component: EX: **<h1 vue-tilt>Example</h1>**
I am not sure what would be the way to add this to a page or globally.

**Comment by robaxelsen** [comment]
Closing, as this is out of scope for a feature request. If you're still having issues with the libraries, please open a new issue, or visit us for help in our Discord channel.
