### ISSUE TITLE
Favicon should not be required

### ISSUE THREAD

**Issue by jackprosser** [gridsome/gridsome#296]
## Summary

At the moment the favicon is required by default. True, pretty much every website under the sun has a favicon of some sort, this shouldn't be required. A number of reasons for this, but generally for my clients, we have a range of assets for favicons that we use and are custom depending on the browser.

Where a lot of static builders fall down, is when they try to be site builder, not frameworks to allow for site building. I feel like this requirement for a favicon is forcing us to use it.

### Motivation

I'd suggest that favicon resizing becomes a plugin or extra attached, so that people can still do that, but by default, you have to add your own. Either in the head options, or better with a custom index.html.

**Comment by hjvedvik** [comment]
You can delete the `src/favicon.png` file if you want to and add icons manually instead. Either by using head options or have a custom `src/index.html` file. Or do you get any errors?

**Comment by jackprosser** [comment]
Strange, when I tried that yesterday it threw an error asking for a file to resize, hence it seemed to be a required option. Happy close this if that's working as expected now.

**Comment by hjvedvik** [comment]
Gridsome looks for the `src/favicon.png` file at startup, so you have to restart after removing it. I'll see if I can do something about it, but it should work as expected after restarting :)

**Comment by jackprosser** [comment]
Still, I seem to get this when I start a new project. Even if I clear .temp and node_modules. It disappeared on the last project I used Gridsome for, but now it's back on the next project.

Would be good to make this whole favicon an additional option or plugin, instead of default project setup. Can't see any reason why anyone would use this. Would also keep the complexity of the library down. Thoughts?

* !!assets-loader?alt=Example%20image&width=135!~/favicon.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/gridsome","cacheIdentifier":"48f71e56-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=template&id=4bc9d7de&

To install them, you can run: npm install --save ~/sass/styles.scss !!assets-loader?alt=Example%20image&width=135!~/favicon.png

**Comment by hjvedvik** [comment]
The favicon is also used in Index.vue in the default starter. Looks like that’s why it’s failing.

**Comment by jackprosser** [comment]
Finally got it working! Bit of a headache. Should have read the error a bit closer, sorry.
