### ISSUE TITLE
Plugin not finishing correctly?

### ISSUE THREAD

**Issue by peXed** [gridsome/gridsome#298]
Hello!

I'm currently working on a Direcuts (CMS) plugin for my projects and for the Gridsome library.

Unfortunatly I have a stange issue. The plugin seems to run perfect (no errors), however the building process will never finish correctly.
I get the "Done in 52.41s", but the process never exits.

Therefore my CI pipeline of the project will fail.
If I build it locally, I can simply stop the process and the created page works perfectly.

Is it possible that the plugin has some errors, but won't display them in the console? Is there a easy way to debug a Gridsome plugin?

Another question, is there already an API to let a plugin stop/fail the Gridsome build process (e.g. if the configuration of the plugin is wrong)?

**Comment by robaxelsen** [comment]
Hello @peXed :wave: Could you please share relevant code related to how you're configuring and using the plugin?

**Comment by peXed** [comment]
Hello @robaxelsen thank you for your replay.

I just released the first preview version of the plugin. You can have a look at the code here:
https://github.com/peXed/gridsome-source-directus

**Comment by hjvedvik** [comment]
Looks like `@directus/sdk-js` starts an interval when you log in. That will make the process running after the build is finished. You can try to call `logout` or `reset` at the end of your `loadSource` to stop it.

**Comment by peXed** [comment]
Thank you @hjvedvik !

Presist: false, did not work, but the logout did!

**Comment by wiven** [comment]
Hi @peXed 

I use your plugin (v0.1.1) and have the same problem.
How can I fix this myself, as I am stuck deploying?

Thanks!

**Comment by peXed** [comment]
Hello @wiven .
Are you sure the issue is caused by my plugin or is it possible that another plugin or function is not working correctly?

For me, the directus plugin is working in different environments and projects just fine after the fix last year. It should also print a message in the log, if it is done loading the data.
