### ISSUE TITLE
Prettier applied to page-query static-query 

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/gridsome#30]
Hi, I'm a big fan of Gridsome.

Prettier has parser 'graphql'.
`page-query` and `static-query` is GraphQL syntax.

So I want to format code in `page-query` and `static-query` block.

**Comment by hjvedvik** [comment]
I see you are working on eslint rules for `page-query` :) Is it possible to test it locally somehow?

**Comment by tyankatsu0105** [comment]
Thanks for the reply!!!

Please give me a moment. I'm almost ready to use my rule for gridsome😊

**Comment by hjvedvik** [comment]
Awesome! Just tested it and it works very well! I really like this plugin and it could be the official ESlint plugin for Gridsome. So you can consider if you want to maintain the repository under the Gridsome organization instead :)

**Comment by tyankatsu0105** [comment]
@hjvedvik 
I’m glad to hear that😊
I made this ESlint plugin for Gridsome.
Could you transfer this package to gridsome official GitHub repository.
I wanna use `yarn add @gridsome/eslint-plugin-gridsome`😏

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Please reply 😅👋

**Comment by hjvedvik** [comment]
Hi 😅 Yes, we can move it to this organization. I'll accept and give you the necessary permissions if you transfer the ownership to gridsome :)

**Comment by hjvedvik** [comment]
I haven't done this much myself, but I think you can follow this [guide](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization).

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Um...
I tryed transfer follow the guide.
The following error message appears.

>You don’t have the permission to create repositories on gridsome

Do I need to participate in the Gridsome organization?

**Comment by hjvedvik** [comment]
I'll just create a new empty repository and give you access. You should then be able to push all your commits to that repository.

**Comment by tyankatsu0105** [comment]
@hjvedvik 
The following error message appears.😂

>gridsome/eslint-plugin-gridsome already exists and You don’t have the permission to create repositories on gridsome

**Comment by hjvedvik** [comment]
I've sent you an invite to the repository :) Accept it, edit your remote git address and push to that repository instead. I think that will work.

**Comment by tyankatsu0105** [comment]
@hjvedvik 
thanks.
I succeeded !! XD
https://github.com/gridsome/eslint-plugin-gridsome

**Comment by tyankatsu0105** [comment]
@hjvedvik 
How do I setup of Travis CI?
eslint-plugin-gridsome was deployed by Travis CI :(

**Comment by tyankatsu0105** [comment]
@hjvedvik 
When I had worked in tyankatsu0105/eslint-plugin-gridsome,
eslint-plugin-gridsome was deployed by Travis CI.
Now this npm package is don't deploy by my Travis CI account.
If you invite me to Gridsome organization,I may be able to setup Travis.
Or could you setup Travis CI?

**Comment by tyankatsu0105** [comment]
@hjvedvik 
I'm sorry, I misunderstood. :(
Please permission level `admin` of `gridsome/eslint-plugin-gridsome` for me.
https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/

**Comment by hjvedvik** [comment]
Will you then be able to set up Travis CI again for that repo if you're an admin? I have added my email and a token in Travis. But You might have to add me as collaborators for the package on npm. Not sure how it works :)

**Comment by tyankatsu0105** [comment]
Now I add you to npm owner.
https://www.npmjs.com/package/eslint-plugin-gridsome
I suppose Travis is work.
I'm try.

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Yeah!!!
Thank you for all your help!!
Let's keep in touch :)
