### ISSUE TITLE
gridsome develop command fail when Contentful Entry title field contains only Japanese.

### ISSUE THREAD

**Issue by fuuki** [gridsome/gridsome#305]
## Description

`gridsome develop` command fail when Contentful Entry title field contains only Japanese.

#### commands

- `gridsome create <project>`
- `yarn add @gridsome/source-contentful`
- `yarn develop`

#### Contentful Model

![スクリーンショット 2019-03-22 23 08 23](https://user-images.githubusercontent.com/18389733/54831175-38822180-4cfd-11e9-9586-18ebb725d047.png)

#### Entity example

- title: 'テスト'
- article: 'test article'

### Expected result

- successfully compiled.

### Actual result

- error happened

```
fuuki@23:00:52 fuuki-blog $ yarn develop
yarn run v1.15.2
$ gridsome develop
Gridsome v0.5.5

Initialize - 0.19s
TypeError: Expected "slug" to match "[^\/]+?", but got ""
    at Object.createPath (/Users/shigenaka/Documents/GitHub/fuuki-blog/node_modules/path-to-regexp/index.js:180:17)
    at ContentTypeCollection._createPath (/<project-dir>/node_modules/gridsome/lib/app/ContentTypeCollection.js:309:25)
    at ContentTypeCollection.addNode (/<project-dir>/node_modules/gridsome/lib/app/ContentTypeCollection.js:76:14)
    at ContentfulSource.getEntries (/<project-dir>/node_modules/@gridsome/source-contentful/index.js:88:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Environment

- Libs
  - gridsome version: 0.5.5
  - @gridsome/cli version: 0.0.8

- Dependencies

```
  "dependencies": {
    "@gridsome/source-contentful": "^0.2.1",
    "gridsome": "^0.5.0"
  }
```

### my awareness

- Error message says `slug` should not be empty.
- In below code `this.slugify(node.title)` cuts Japanese charactors, and slug becomes empty.
  - https://github.com/gridsome/gridsome/blob/a0fcd10ca7d10adb2307685e482b6a7762a84d7b/gridsome/lib/app/ContentTypeCollection.js#L73

**Comment by ion1** [comment]
I don't know the best solution, but [Unidecode](https://www.npmjs.com/package/unidecode) is one option to generate very rough ASCII transliterations of any text.

```
> require('unidecode')('テスト')
'tesuto'
```

**Comment by fuuki** [comment]
If the empty slag is the real cause, I think there are some solutions.
- translate the title unicode to ASCII (as ion1 says), or use unicode escape sequence.
- use some other field (id, etc.) to slug when the slug becomes empty.

What is the best way?

**Comment by fuuki** [comment]
I confirmed that this code works properly.
```.js
// gridsome/gridsome/lib/app/ContentTypeCollection.js #Line 73
node.slug = options.slug || fields.slug || this.slugify(node.uid) 
```

I think this is the easiest way since it need not add dependency.

**Comment by hjvedvik** [comment]
You can also try to set custom routes which don't use `:slug`:

```js
{
  use: '@gridsome/source-contentful',
  options: {
    routes: {
      article: '/article/:id' // or any other field
    }
  }
}
```

**Comment by fuuki** [comment]
Thank you so much!
In my model, this code behave fine.
```
  use: '@gridsome/source-contentful',
  options: {
    routes: {
      Blog: '/blog/:id' // or any other field
    }
  }
```
However, slugify titles can cause failed builds to non-English titles, so I recommend to use an id for slug (or route) in the route configuration by default.
