### ISSUE TITLE
How do you use the queried GraphQL data in the <script>?

### ISSUE THREAD

**Issue by themindstorm** [gridsome/gridsome#306]
I'm using a simple query to fetch the site name:

```
<static-query>
  query {
    metaData {
      siteName
      siteDescription
    }
  }
</static-query>
```

I want to set this name as the site title. The default template for site titles is `%s - Site Title`, but for this page, I only want to set it to `Site Title`. I would like the use the queried data so that I do not have to update it in case I change the value of `siteTitle` in `module.exports`. 

This is what I tried:
```
<script>
export default {
  metaInfo: {
    // title: 'Site Title',  <--- not using this because it makes the title "Site Title - Site Title"
    titleTemplate: static.metaData.siteName
  },
}
</script>
```

But it was giving an error. I also tried putting a `$` in front of `static`, but it returned undefined. Is it possible to do this?

**Comment by tomtev** [comment]
It needs to be this.$static.metaData.siteDescription

**Comment by themindstorm** [comment]
@tomtev Thank you for your answer. However, I am still getting the Error: `vue-router.esm.js?8c4f:1897 TypeError: Cannot read property '$static' of undefined`

This is the code:

```
<script>
export default {
  metaInfo: {
    title: 'Index',
    titleTemplate: this.$static.metaData.siteName,  // <-- returns the type error
  },
  created() {
    console.log(this.$static.metaData.siteName);  // <-- Correctly console.logs the site's name
  }
}
</script>
```

And the query is the same

**Comment by bbugh** [comment]
Hi @themindstorm, this is a common sticking point with Vue. `this` is dynamically injected into Vue instances only when the context is evaluated. To have access to "this", the context needs to be a function. In this case, changing `metaInfo` from an object to a function with a return will fix your issue:

```javascript
// metaInfo doesn't have access to the Vue instance
metaInfo: {
  title: 'Index',
  titleTemplate: this.$static.metaData.siteName,  // <-- "this" is undefined
},
```
```javascript
// Use a function for metaInfo instead
metaInfo() {
  return {
    title: 'Index',
    titleTemplate: this.$static.metaData.siteName,  // <-- "this" is the Vue instance with $static
  }
},
```

**Comment by Spica2** [comment]
```data() {
  return {
    title: 'Index',
    titleTemplate: this.$static.metaData.siteName,  // <-- "this" is the Vue instance with $static
  }
},```
```[Vue warn]: Error in data(): "TypeError: Cannot read property 'metaData' of undefined"````
But using it in the data function causes this error. Any way to use it here?

**Comment by hacknug** [comment]
> But using it in the data function causes this error. Any way to use it here?

@tomtev any way to use it with `data()`?

**Comment by dargmuesli** [comment]
@bbugh is there any reason to use the function-less approach? Otherwise I'd update the docs to explain the way to do it with a function.
