### ISSUE TITLE
gridsome serve: reloading the same page doesn't work

### ISSUE THREAD

**Issue by AndreasHeintze** [gridsome/gridsome#307]
## Description
My browser (Chrome on Mac) just indicates waiting for page if I reload the same page.

### Steps to reproduce
gridsome create gridsome-site
gridsome build
gridsome serve
Go to http://localhost:8080 in your browser.
It works fine clicking the about link and start again, but as soon as you click a link to the same page or just reload the page you are on, the browser just waits for the page to load forever.

### Expected result
Reloading the same page.

### Actual result
Browser waits for page load forever.

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8

Browser:
- [X] Chrome (desktop) version 72.0.3626.121
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.0
- Platform:  Mac

Others:
</code></pre>

**Comment by hjvedvik** [comment]
The `gridsome serve` command is very unstable and I don't recommend using it. It serves gridsome from an Express server with server-side rendering, so it doesn't show the site you just built. You can use tools like [serve](https://www.npmjs.com/package/serve) to test your static site.
