### ISSUE TITLE
DOC: How do we create references between two posts with markdown files

### ISSUE THREAD

**Issue by vdilly** [gridsome/gridsome#314]
Hello and thanks for this project !

I'm trying to have a solid alternative to classical CMS with Gridsome and Netlify CMS. I'm new to the Jamstack world, but I'm really enjoying it and everything's was going fine so far...

Now I struggle on the matter of relationship between 2 contents.
**I want to have a simple Homepage, with a highlighted link to another post.**

With NetlifyCms, I can have **Home.md**, containing a field **highlightedPost**, with the Title from my blog2.md as value.
`highlightedPost: Mon Article 2`

But I don't know how can I get this specific node in my page-query in index.vue, since we can only access nodes from their ID

Netlify doesn't know about graphQL IDs ... 
I was thinking about something like:

1. Query my home.md and store highlightedPost value as a variable
2. Query AllBlogpost an filter the result by Title comparison with this variable

But I'm not sure how I can achieve that, and would like to know if there's a cleaner way that I'm missing

Any clue could help me understand this, thank for your help !

**Comment by Berkmann18** [comment]
In order to link a markdown post with another one, you need to link the route of that file.
Example:
```
gridsome-project
  | - posts\
  | -- post-a.md
  | -- post-b.md
```
In your `post-a.md` you'll need to use: `[some text](/posts/post-b)` and that should allow for a successful reference that users could use.

**Comment by LorenAmelang** [comment]
Just spent way too long trying to use the @Berkmann18 suggestion...

[Consumed by the Light](/light/) doesn't work
[Consumed by the Light](/consumed-by-the-light/) does
So it isn't the "light.md" filename from /content/posts
It isn't the visible "Consumed by the Light" filename in the displayed page
It is the end of the "http://localhost:8080/consumed-by-the-light" address from the browser address bar! 
The needed form does not appear anywhere in the source files, only in the built dist files! 
Unlike with /g-link, the ending '/' appears to be optional.

**Comment by Berkmann18** [comment]
@LorenAmelang I'm not sure if I understood what you wrote but it may be worth checking what route that file uses. 
Normally gridsome uses the filename for the route but if that's not the case (based on what routes are listed on the terminal and which ones lead to the correct posts) you could always change it to use the correct one.

**Comment by LorenAmelang** [comment]
I'm pretty ignorant about what happens behind the scenes, so I'm not sure what you mean by "route" and "terminal". 

Here's the start of my post:

```
title: Consumed by the Light 
date: 1953-11-15
tags: ['Psychic', 'Trauma', 'AccessoryNerve']
cover_image: ./images/loren-moonlight-1912.jpg
canonical_url: false
```

"Title:" seems to control what actually appears above the post and in the Main Outline - can't change that. 
The filename is /content/posts/light.md, I guess I picked that, but it isn't what shows in the working URL. 

So are you saying there is some config option somewhere that routes post filenames and titles to link URLs?

**Comment by Berkmann18** [comment]
The route is the URL path that will lead a user to a particular page (e.g. `https://some.site.com/posts/hello-world`).
Did you try navigating to `http://localhost:8080/content/posts/light` (assuming you have the dev server running on port 8080)?

> So are you saying there is some config option somewhere that routes post filenames and titles to link URLs?

AFAIK, it's only done internally but @robaxelsen or someone from the core team could shed a light on this.
