### ISSUE TITLE
Installed Netlify CMS with Gridsome. Why can't I see my published blog posts?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#317]
## Description

I've followed the Netlify CMS guide. I've setup Netlify CMS properly. I can login and make posts. But I have no idea where those posts are being published to, in terms of what URL they're being published live to.

I also don't know if there's an overall blog landing page, that lists all my blog posts.

### Steps to reproduce

[Netlify link](https://infused.netlify.com/)

Codesandbox [link](https://codesandbox.io/s/github/jd-fillmore/infused-gridsome)

### Expected result

I should ideally be seeing my published blog posts live on [my site](https://infused.netlify.com/). 

### Actual result

I don't see them anywhere. 

### Environment

<pre><code>
Libs:
- gridsome version: v.0.5.5
- @gridsome/cli version: v0.0.8

Browser:
- All of them
 
For Tooling issues:
- Node version: v8.12.0
- Platform:  Windows
</code></pre>

**Comment by Al-Rozhkov** [comment]
First you need to create a Template for your blog post: https://gridsome.org/docs/templates/

And “Blog.vue” file in your “src/pages” directory. You can use gridsome.org source code repo as an example (https://github.com/gridsome/gridsome.org/blob/master/src/pages/Blog.vue). 

(Sorry, typing that on my phone, can’t add helpful code examples)

**Comment by jd-fillmore** [comment]
Thanks for that @Al-Rozhkov !

I've updated my Netlify and Codesandbox link above. You'll see the [Blog page here](https://infused.netlify.com/blog/). I also added in the /templates/ folder, a blank 'BlogPost.vue' file.

I used the Blog template you linked to in their Github, but had to remove the query data from it because it was throwing errors and wouldn't build. I've never setup GraphQL before I think this is required to get this all working.

Now that I have those files setup, what's the next step?

**Comment by Al-Rozhkov** [comment]
Here is how your `src/pages/Blog.vue` could looks like:

```
<template>
  <Layout>
    <!--Hero-->
    <section class="inner-hero">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1>Blog</h1>
            <p>Our latest posts educating clients</p>
          </div>
        </div>
      </div>
    </section>
    <!--Content-->
    <section class="inner-content">
      <div class="container">
        <div class="row">
          <!--Content-->
          <div
            v-for="edge in $page.posts.edges"
            :key="edge.node.id"
            class="col-md-12 text-center"
          >
            <h2>
              <g-link :to="edge.node.path">{{ edge.node.title }}</g-link>
            </h2>
            <p>{{ edge.node.excerpt }}</p>
          </div>
        </div>
      </div>
    </section>
    <Footer></Footer>
  </Layout>
</template>

<page-query>
query BlogPosts {
  posts: allPost {
    edges {
      node {
        id
        title
        path
        date (format: "D. MMMM YYYY")
        excerpt
      }
    }
  }
}
</page-query>

<script>
export default {
  metaInfo: {
    title: 'Blog'
  }
}
</script>
```

Your blog post template have to be named `src/templates/Post.vue` because in your `gridsome.config.js` your typeName is 'Post'.

```
<template>
  <Layout>
    <Section class="post">

      <div class="post-header container-sm text-center mb">
        <h1 v-html="$page.post.title"/>
      </div>

      <p class="lead" v-html="$page.post.excerpt"/>

      <div v-html="$page.post.content"/>
    </Section>
  </Layout>
</template>

<page-query>
query BlogPost ($path: String!) {
  post (path: $path) {
    title
    date (format: "D. MMMM YYYY")
    content
    excerpt
  }
}
</page-query>

<script>
export default {
  metaInfo () {
    return {
      title: this.$page.post.title,
      meta: [
        {
          name: 'description',
          content: this.$page.post.excerpt
        }
      ]
    }
  }
}
</script>

<style lang="scss">
// Your styles goes here
</style>
```

**Comment by jd-fillmore** [comment]
Thank you so much @Al-Rozhkov ! It works!!
