### ISSUE TITLE
Question:  How to debug $path  or other variables that can be passed to GraphQL?

### ISSUE THREAD

**Issue by valentinvieriu** [gridsome/gridsome#32]
How to pass variables to GraphQL layer, and how to debug them?

**Comment by hjvedvik** [comment]
Gridsome currently use the route path and its param values as variables. But the plan is to use the node which belongs to the path as the variables context. So any fields on the node will be available as variables. But we are open for discussion on where the variables should come from and if it should be possible to inject own variables.

**Comment by robaxelsen** [comment]
Closing this due to question having been answered.
