### ISSUE TITLE
Command develop not working

### ISSUE THREAD

**Issue by tkrempser** [gridsome/gridsome#320]
## Description

Can't run `gridsome develop`

### Steps to reproduce

1. Run `gridsome create my-gridsome-site https://github.com/gridsome/gridsome-starter-blog.git`
2. Go to `my-gridsome-site` folder
3. Run `gridsome develop`
4. Make some code updates
5. Run `gridsome build`
6. Create the `gh-pages` branch
7. Delete all files and folders except `dist` folder
8. Copy file inside `dist` folter to project root
9. Run git commit and git push
10. Checkout `master` branch with all files and folders again
11. Try to run `gridsome develop` and fail

### Expected result

Run develop server.

### Actual result

I see the message `Unknown command develop` and nothing happens.

### Environment

<pre><code>Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.5.5

Browser:
- Chrome (desktop) version 73.0.3683.86 (Official Build) (64-bit)</code></pre>

**Comment by hjvedvik** [comment]
You need to install dependencies after checking out `master` in step 10 if you have deleted the `node_modules` folder. We should probably try to show a better message if the `gridsome` package is missing.

**Comment by tkrempser** [comment]
> You need to install dependencies after checking out `master` in step 10 if you have deleted the `node_modules` folder. We should probably try to show a better message if the `gridsome` package is missing.
