### ISSUE TITLE
Should plugins be installed as devDependencies?

### ISSUE THREAD

**Issue by Al-Rozhkov** [gridsome/gridsome#321]
Hi Gridsome community!
First of all I want to thank you for your awesome work on Gridsome! I worked with Nuxt for almost two years and my main area of interests is JAM stack. Gridsome is amazing tool and it much suitable for SSG.

I'm just starting to work with Gridsome and use gridsome.org as trustworthy example. I noticed that gridsome.org adds source and transformer plugins as devDependencies but plugins documentation recommends to add it as regular dependency.

I guess there is no any effect on build size. But I'm interested does it even matter how to install plugins and should docs reflect that?

**Comment by hjvedvik** [comment]
Glad you like Gridsome :) Separating packages in `dependencies` and `devDependencies` doesn't matter for an end project. But personally, I like to have packages used in the browser as `dependencies` and other things as `devDependencies`. The doc examples just install them as regular dependencies for simplicity, but we could probably encourage devs to install as dev dependencies.
