### ISSUE TITLE
Gridsome routes hard to debug

### ISSUE THREAD

**Issue by Al-Rozhkov** [gridsome/gridsome#322]
Vue-devtools 5.0.0 comes with "Routing" tab. But routes added with `router.addRoutes` not shown there and this is by design (see: https://github.com/vuejs/vue-router/issues/2280).

![2019-03-26_16-51-43](https://user-images.githubusercontent.com/16973264/55003001-8e4e1680-4fe8-11e9-9ef8-c7c9d55030ff.png)

Since routes are mostly known in moment of build process, wouldn't it be nice to change how Gridsome router is built?

Lets start this as discussion, not a feature request.

**Comment by hjvedvik** [comment]
Oh, I wasn't aware of that. I'll include a fix in the next update :)

**Comment by Al-Rozhkov** [comment]
Cool :) So it become feature request.

**Comment by hjvedvik** [comment]
Published 0.5.6 earlier today with a fix for this :)

**Comment by Al-Rozhkov** [comment]
![2019-03-30_13-55-41](https://user-images.githubusercontent.com/16973264/55275188-8e555b80-52f3-11e9-8e79-eff783208c23.png)

It works great! Thank you @hjvedvik
