### ISSUE TITLE
Can no longer connect to GraphQL endpoint via external app

### ISSUE THREAD

**Issue by Truemedia** [gridsome/gridsome#323]
## Description

I'm using a gridsome instance to serve data to an external application. Recently updated the version and can no longer query http://localhost:8080/___graphql (GraphiQL stil works fine using this).

### Steps to reproduce

Using postman create a new request to the above url using graphql content type header (Content-Type: application/graphql) and posting query as raw body data.

### Expected result

JSON results

### Actual result

Server just hangs with no errors and the request reaches a timeout on the postman client

### Environment

<pre><code>
Libs:
- gridsome version: latest (master)
- @gridsome/cli version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  11.10.0
- Platform:  Linux

Others:

</code></pre>

**Comment by Truemedia** [comment]
Also a quicker to test this is if you go on graphiql and click 'Copy CURL' and paste into a new terminal window you get same result.

**Comment by hjvedvik** [comment]
Update your `master` branch and see if it works better now :)

**Comment by Truemedia** [comment]
@hjvedvik That works now thanks :+1:
