### ISSUE TITLE
Why aren't my website's pages loading?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#324]
## Description

When I click on a link in the nav, the URL in the address bar changes, but it does not load the page.

This is only happening on Netlify. This does NOT happen on my local machine.

[Netlify link](https://infused.netlify.com/).

Note - if you click on a page, and the URL changes to the clicked page, hit refresh. Suddenly, everything works and you can navigate around the site.

### Steps to reproduce

[Codesandbox link](https://codesandbox.io/s/github/jd-fillmore/infused-gridsome).

1. Click on the Netlify link above
2. Try clicking on one of the main navigation items at the top right
3. Notice how the page doesn't load. But, the URL in the address bar changes.

### Expected result

The page that's clicked on should load.

### Actual result

It doesn't load. Instead, you're stuck on the home page.

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8

Browser:
- All of them

</code></pre>

**Comment by jfitzsimmons2** [comment]
I'm a newbie here but with that said, I think it has to do with your link markup.

`<b-nav-item to="/work"><g-link class="nav__link" to="/work">Work</g-link></b-nav-item>` 

is creating some weird markup on your production site.

Try changing it to:

`<g-link class="nav__link" to="/work">Work</g-link>`

and see if it works.

**Comment by jd-fillmore** [comment]
@jfitzsimmons2 

I've removed the <b-nav-item> tag and placed what you had there. Still doesn't work.

The <b-nav-item> tag is a bootstrap vue component.

**Comment by hjvedvik** [comment]
You still have multiple nested `a` elements in your main menu. Try fix that and see if it works better :)

**Comment by jd-fillmore** [comment]
@hjvedvik Removed all instances of <g-link> tags being nested in <b-nav-item> tags in the main menu, still not working. :(

**Comment by hjvedvik** [comment]
You can also try to add this element to your Netlify form ([ref](https://www.netlify.com/blog/2018/09/07/how-to-integrate-netlify-forms-in-a-vue-app/))
```html
<input type="hidden" name="form-name" value="home-contact" />
```
Looks like Netlify automatically adds it if it doesn't exists. But it will mess up the Vue rendered markup.

**Comment by jd-fillmore** [comment]
@hjvedvik I disabled the forms completely and my site works again! So yes, it's probably because Netlify adds those tag. Thanks for that.

**Comment by snowmanstudio** [comment]
hello. I also facing this issue but my site is on cloudflare pages. How can I solve this in cloudflare pages?
