### ISSUE TITLE
How do 301 redirects work with Gridsome?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#328]
## Description

I plan on launching a new site built with gridsome, but want to setup a 301 redirect. Usually this is done with a .htaccess file, and uploading it in the root. Is it that same with gridsome?

I plan on hosting this with Netlify.

**Comment by hjvedvik** [comment]
Have a `_redirects` file in your `/static` folder to configure redirects rules for Netlify. You can also add redirect rules with a `netlify.toml` file in the root folder of your project. Read more about it [here](https://www.netlify.com/docs/redirects/).

**Comment by jd-fillmore** [comment]
Thank you @hjvedvik !

**Comment by LocusT221** [comment]
@hjvedvik I was wondering if this could be done without Netlify as I'm using 'Contentful' as a CMS solution?

**Comment by dikaio** [comment]
@LocusT221 it should be possible with just about any host, how it's implemented really comes down to where the site is hosted but the redirects would be done on the hosting end not within Gridsome.

**Comment by 1aurabrown** [comment]
I've tried putting a _redirects file in my /static folder, but it doesn't seem to have any affect. Is this still where it is supposed to go?
