### ISSUE TITLE
How to setup meta titles and descriptions on blog posts?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#329]
## Description

I'd like to setup meta titles and descriptions for SEO on blog posts. I'm using Netlify and the files generated are .md files.

I set them up in normal pages fine, but when using the same format in .md files, they don't work.

Any idea how?

**Comment by danvega** [comment]
You can add meta info to your post template

```
  metaInfo() {
    return {
      title: this.$page.post.title,
      meta: [
        { name: "description", content: this.$page.post.excerpt }
     ]
   }
}
```

You can check out my blog for more > https://github.com/danvega/danvega-dev/blob/master/src/templates/Post.vue

**Comment by jd-fillmore** [comment]
Awesome! Thanks @danvega

**Comment by arjunkalburgi** [comment]
Hey @danvega, I followed your blog to customize the og:image meta tag using cover in graphQL to get the post-compiled image path. 

But it's not working for me, the GraphQL is returning ‘undefined’.

Could you take a peep, maybe you'll see what's wrong. https://github.com/arjunkalburgi/writing/blob/vue/src/templates/Post.vue

**Comment by danvega** [comment]
@arjunchib You have to have a property in your markdown frontmatter called cover. I looked at one your posts and I didn't see it there. Are you adding this property to your posts? 

```
---
slug: "vue3-ref-vs-reactive"
title: "Vue 3 Composition API: Ref vs Reactive"
date: "2020-02-12T16:27:46.472Z"
published: false
excerpt: "One question I keep hearing over and over is what method should I use to declare reactive data in the Vue 3 Composition API? In this article, I explain what ref() and reactive() are and try to answer that question."
author: "Dan Vega"
tags:
  - "vue"
cover: "./vue3-ref-vs-reactive-cover.png"
video: https://www.youtube.com/embed/cRwG96MOHp0
---
```

**Comment by arjunkalburgi** [comment]
@danvega yeah I’m only using it on specific posts, I didn’t do it to all of them. For example [here](https://github.com/arjunkalburgi/writing/blob/vue/content/posts/Life%20Story%202020%20Update/index.md) 
```
---
title: Life Story Update 2020
description: >-
  Over the last 5 years I've been learning strong UX skills to build web interfaces and products that connect and enable people. I want to look back on this journey, thinking about where I've been and some of the specific memories I have.
date: '2020-03-23T14:20:33.815Z'
slug: /life-story-update-2020
cover: ./arjun2020.jpg
---
```

I’ve also changed my getCoverImage function:
```
getCoverImage() {
        let path = "";
        const cover = this.$page.post.cover;
        if (cover != null && typeof(cover) != 'string') {
          console.log('cover: ', cover);
          path = `${this.getBaseUrl}${cover.src}`;
        } else if (cover != null && cover.includes('http')) {
          path = cover;
        } else {
          path = `${this.getBaseUrl}/writing/sra.jpg?${cover}`;
        }
        return path;
      } 
```
For me the `cover.src` returns as either undefined or some weird long path. I added the `?${cover}` on the default path to test this

http://debug.iframely.com/?uri=https%3A%2F%2Fwww.arjunkalburgi.com%2Fwriting%2Flife-story-update-2020%2F

This is showing that cover is `/home/runner/work/writing/writing/content/posts/Life%20Story%202020%20Update/arjun2020.jpg`

When It should be something like `https://www.arjunkalburgi.com/writing/assets/static/arjun2020.e6856d4.13bcd529ed3aac3554657e40c24e5ddc.jpg `

**Comment by arjunkalburgi** [comment]
@danvega do I have to use it in more of my posts for it to work? I have no idea why graphql would just quit on me for that one property.
