### ISSUE TITLE
How to set SiteURL in sitemap plugin?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#330]
## Description

Installed the sitemap plugin, and it says to set the SiteURL in the project config.

Is that in gridsome.config.js? And also, is it just siteURL: 'www.site.com' below siteName: 'site name' in module.exports?

**Comment by cossssmin** [comment]
You need to set it in `gridsome.config.js`, yes.

For example:

https://github.com/cossssmin/gridsome-starter-bleda/blob/ce5f657ba72cc6a9ed06ece82ee7178dff15c877/gridsome.config.js#L10

**Comment by jd-fillmore** [comment]
@cossssmin thank you!
