### ISSUE TITLE
Cannot read property 'startsWith' of undefined mergeSchemas 269:47

### ISSUE THREAD

**Issue by mariuswallin** [gridsome/gridsome#333]
Creating a project with version 0.5.6 I can´t build or develop the project due to the error mentioned above.

**Comment by Roninii** [comment]
having this issue as well.

**Comment by Roninii** [comment]
@hjvedvik confirmed this issue is caused by the latest `graphql-type-json`.

**Comment by doppelmutzi** [comment]
me too!

**Comment by Ezra-Siton-UIX** [comment]
me too!

![image](https://user-images.githubusercontent.com/16711871/55266176-b1005980-528c-11e9-9edb-7f49d9a524a2.png)

**Comment by mjosborne1** [comment]
Same here v is 0.5.6 
Anyone have this issue with v 0.5.5?

**Comment by mariuswallin** [comment]
Downgraded to 0.5.5 - no problem ;)

**Comment by Roninii** [comment]
You should instead be upgrading. The issue wasn't with gridsome. It was with a dependency that has since been fixed. This issue can be closed now. 😊

**Comment by mariuswallin** [comment]
Tnx for update
