### ISSUE TITLE
How to integrate AOS animations?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#335]
## Description

Is there a way to integrate [AOS animations](https://michalsnik.github.io/aos/)?

I've searched the web and have found ways to implement into Vue itself, but not sure if there's a better approach for Gridsome specifically.

**Comment by tomtev** [comment]
Gridsome is using Vue, so any Vue.js library that does this should work :)

**Comment by jd-fillmore** [comment]
@tomtev ,

I used [this solution for Vue ](https://github.com/michalsnik/aos/issues/87#issuecomment-313558488)specifically, and it doesn't work.

Screenshot of my code and compile error [here](https://imgur.com/a/mwxKmsv).

Any suggestions?

**Comment by akb20** [comment]
I also had trouble getting AOS working, but vue-scroll-reveal worked straight away.
Hope that helps.
https://github.com/tserkov/vue-scroll-reveal

**Comment by danieldocki** [comment]
@akb20 

How do you configured `vue-scroll-reveal`?
I do this below and it's dont working

main.js
```javascript
import DefaultLayout from '~/layouts/Default.vue'
import VueScrollReveal from 'vue-scroll-reveal'

export default function (Vue, { router, head, isClient }) {
  Vue.component('Layout', DefaultLayout)
  Vue.use(VueScrollReveal)
}
```

```
Failed to render /
ReferenceError: document is not defined
    at /Users/danieldocki/Projects/the-project/node_modules/scrollreveal/dist/scrollreveal.js:33:13
    at defaults.delay (/Users/danieldocki/Projects/the-project/node_modules/scrollreveal/dist/scrollreveal.js:13:82)
    at Object.<anonymous> (/Users/danieldocki/Projects/the-project/node_modules/scrollreveal/dist/scrollreveal.js:16:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:
```

**Comment by Manuel-Suarez-Abascal** [comment]
@akb20 I also tried to add vue-scroll-reveal and it doesn't work production. It seems the issue is related to this [issue](https://github.com/gridsome/gridsome/issues/180). PLease let me know if you make to work and I will keep trying on my side and I will update you if I make it work!

**Comment by miguelslp** [comment]
Also having @danieldocki problem, this time on vue-js-toggle-button

**Comment by puterakahfi** [comment]
hi @jd-fillmore 
you can use this way to register AOS in gridsome 
in main.js add this line inside the function 


import AOS from 'aos';
import 'aos/dist/aos.css'
export default function(Vue, { router, head, isClient }) {
  Vue.use(AOS.init());
}

don't forget to add data-aos attribute in your component
 
hope this help

**Comment by LukeXF** [comment]
I'm also having this problem. Because I can't use ClientOnly in my main.js file and using the following *doesn't* apply animation on the client side:

```
if (process.client) {
		const VueScrollReveal = () => import('vue-scroll-reveal');

		Vue.use(VueScrollReveal, {
			reset: false,
			class: 'v-scroll-reveal',
			duration: 500,
			distance: '20px',
			mobile: true,
			interval: 600,
			viewOffset: {
				top: 0,
				right: 0,
				bottom: 0,
				left: 0,
			}
		});
	}
```

Any suggestions?

**Comment by arifhussain353** [comment]
In `main.js`
```
import AOS from 'aos';
import 'aos/dist/aos.css'
```

```
export default function (Vue, { router, head, isClient ,appOptions }) {
  Vue.component('Layout', DefaultLayout)
  AOS.init()
}
