### ISSUE TITLE
<g-link /> components not opening new pages

### ISSUE THREAD

**Issue by gargleyark** [gridsome/gridsome#337]
## Description

I am linking to different parts of my site using the `<g-link />` component, which works correctly on my local environment. After building my website onto Netlify, the URL updates when the link is clicked but the site does not re-render with the new page.

[Netlify link](https://festive-knuth-ff5273.netlify.com/)

[Github link](https://github.com/gargleyark/gargleyark-web-2019)

<img width="346" alt="Screen Shot 2019-03-30 at 19 00 17" src="https://user-images.githubusercontent.com/2544288/55280480-1e0fff80-531e-11e9-81fe-5c58c3b6aa48.png">
g-link components that are failing

### Steps to reproduce

Go to https://festive-knuth-ff5273.netlify.com/ and try and click on any of the Bookbinder
Writer, or Artist links. The path will update to something like https://festive-knuth-ff5273.netlify.com/writing/, but the page will not update unless you refresh the browser.

### Expected result

The site should re-render with the new page.

### Actual result

Only the path changes in the browser.

What happened.

### Environment

Libs:
- gridsome version: v0.5.5
- @gridsome/cli version: v0.0.8

**Comment by tomtev** [comment]
Hi there, nice site :) There might be a Vue.js hydration error. Could you check if all HTML tags are closed properly?

**Comment by gargleyark** [comment]
Hi Tommy, thanks! That was one of my thoughts, but I've run the page through W3C's validator and did not get any warnings about unclosed tags.

**Comment by hjvedvik** [comment]
Try change [this](https://github.com/gargleyark/gargleyark-web-2019/blob/dd19dcb130a99f07afdc7b9a3269832c68f9d26f/src/components/HomeHeader.vue#L8) line into a `div` element and see if it helps.

**Comment by gargleyark** [comment]
Blimey, great spot - that's done the job

**Comment by devignerforhire** [comment]
> Try change [this](https://github.com/gargleyark/gargleyark-web-2019/blob/dd19dcb130a99f07afdc7b9a3269832c68f9d26f/src/components/HomeHeader.vue#L8) line into a `div` element and see if it helps.

@hjvedvik Can you elaborate on why changing to a div would resolve the hydration error? I'm having a similar issue with the live version of my site, where clicking navigation links update the url, but not the page content. I've gone through each of my pages, but not seeing anything out of place. The repo i'm working from is over here -> https://github.com/devignerforhire/smokeyfro-site.

**Comment by LukeXF** [comment]
I have the same problem, can someone explain why this solution works?

**Comment by hacknug** [comment]
@LukeXF paragraphs can only hold [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) according to the spec. What would happen [here](https://github.com/gridsome/gridsome/issues/337#issuecomment-478281759) is that you'd have all kinds of things nested inside the paragraph which wouldn't be valid HTML.

**Comment by shubhamzanwar** [comment]
This issue saved me a day of debugging and breaking my head!

Thanks ❤️

**Comment by 20was** [comment]
I am also facing a similar issue, When I navigate my website from the [home page](https://www.kontextsolution.com/), it works but when I open [this link](https://www.kontextsolution.com/early-bird-registration/) first and try to navigate to any other pages, then just title and route changes, but not the content of the page. 

I tried validating the code as well but didn't work. Any help will be appreciated.

**Comment by kwiat1990** [comment]
I have noticed that error on my production site as well. Locally all works just fine and what seems odd to me is the fact that the error (page reload after clicking `g-link`) is gone if I open dev tools.

**Comment by peterbaricic** [comment]
I also have the same problem. My last link in navbar (going to /about/) doesn't work on Netlify, but everything works on Vercel.

https://6028d17f02e4c8000890723c--zen-pasteur-8258a4.netlify.app/
https://smepripraveni-landing-m7jb0dnl2.vercel.app/

**Comment by kwiat1990** [comment]
@peterbaricic I don't know more what was the cause of this error on my page but I have got rid of it by a change in a template of one of my components (although according to HTML validator there was no error in markup per se).

**Comment by peterbaricic** [comment]
I discovered what caused my problem and fixed it. Problem was caused when I implemented netlify forms. I already submit my form using axios, but I also had data-netlify="true" attribute. When I removed it, everything started to work again.

**Comment by jakehandwork** [comment]
@peterbaricic Doesn't [this documentation](https://docs.netlify.com/forms/setup/) say that you still need the `data-netlify="true"` attribute even if you use axios to submit? Curious because I'm having the same problem. Submitting with axios, and I have the data-netlify attribute still. I also have the data-netlify-recaptcha. Were you using that as well.
