### ISSUE TITLE
How to use g-image with graphQL?

### ISSUE THREAD

**Issue by AndreasHeintze** [gridsome/gridsome#338]
It feels like we need a community somewhere to ask questions like mine here, but anyway. There seems to be some info missing in the documentation about g-image and how to use it with graphQL.

The section here https://gridsome.org/docs/images#usage-via-graphql does not state how to format the src link. So what should the link look like to work?

After a lot of googling and searching I got it working by writing it like this:
``<g-image :src="require(`!!assets-loader?width=552!@/${edge.node.image1}`)" width="552" />``
But that was a very ugly way of doing it, so is there a nicer way to do this?

**Comment by hjvedvik** [comment]
We have a community at [Discord](https://discord.gg/daeay6n) you could check out :)

You should not have to format the `src` attribute for `g-image`. The value is generated by a GraphQL resolver. That is why it says you have to set `width` and `height` in the query instead of attributes. So the example you linked to should work fine for local images.

```html
<g-image :src="$page.post.image" />
```
```gql
query ($id: String!) {
  post (id: $id) {
    image (width: 552)
  }
}
```

**Comment by AndreasHeintze** [comment]
I'm sorry but I can't get it to work. Can you direct me to a solution?
Where do you recommend me to put my images?

I have now placed them in a subfolder under /src/assets/...
..what should the path in image1 be if I have placed an image in /src/assets/images/my-image.jpg?
I want the images to lazy-load too.

```
contentType.addNode({
        id: 'prod_prod-s1/2',
        title: 'Sportavgassystem Peugeot 406 Sedan (1.6 / 1.8) 1995-2003',
        path: '/motor/avgassystem/sportavgassystem/peugeot-406-sedan-1.6/1.8-1995-2003',
        fields: {
          product_id: '121-103-17-1r',
          name: 'Sportavgassystem Peugeot 406 Sedan (1.6 / 1.8) 1995-2003',
          text: 'Bla bla',
          image1: '../assets/images/my-image.jpg',
          price: {
            "excl":1759.20,
            "incl":2199,
            "discount":0,
            "discount_type":"percent"
          },
          "price_org":{
            "excl":1759.20,
            "incl":2199
          }
        }
      })
```

**Comment by hjvedvik** [comment]
It should be fine to have them in `src/assets`. But you need to use an absolute file path as the field value or else Gridsome won't be able to find the image and process it.

**Comment by AndreasHeintze** [comment]
Ok, but I thought the path needed to be relative if I want the images to be compressed.
"Only local, relative image paths will be compressed by Gridsome."
So, what should the absolute path be in this case? I have tried /assets/images/my-image.jpg and a lot of other ways. Nothing has worked so far.

**Comment by hjvedvik** [comment]
Only local, relative image paths will be compressed when using `g-image` when the `src` attribute points to a local file like: `<g-image src="../assets/image.jpg" />`.

But when adding nodes to the GraphQL layer, you need to use an absolute file path. There are various methods for getting an absolute path like `path.resolve`, `path.join` or `require.resolve`:

```js
{
  image1: require.resolve('./src/assets/images/my-image.jpg')
}
```

**Comment by AndreasHeintze** [comment]
I finally understood, thank you!

I'm evaluating Gridsome to build a new platform that is going to be used to build e-commerce sites. I like it so far, but I am a little afraid because it's such a young project. We are looking at Nuxt too, but I really like the graphQL datalayer in Gridsome. Do you have any idea when it will reach v1.0.0?
Also, how will it handle a site that has maybe 500 000 products? I am thinking about creating one page per product so the SEO will work nicely with it. If I change the product data for just one of the products, I don't want the build process to rebuild all 500 000 pages. Do you think this is possible?

**Comment by hjvedvik** [comment]
I understand your concerns. We are trying to catch up features in other SSGs out there, but I'm not sure when we will reach v1.0 yet. Hopefully, it's not too far away.

We have only tested Gridsome with 10k pages so far, which works fine, but I'm not sure if it's ready for 500k. Our goal is to make it work and support incremental builds to only build what's necessary on re-builds. But that features isn't implemented yet..

Sorry for not having any ETAs. We are eager to get things done, but it takes time.. :)

**Comment by robaxelsen** [comment]
Closed this issue, as original question has been answered. @AndreasHeintze: feel free to create a new issue if you have new questions, or reopen if you have any follow-ups to this.

**Comment by yann-yinn** [comment]
I did not manage to make it work with gridsome 0.5.7 , this seems to have no effects on my attempts (image displayed is stil the original BIG one )

Here is my GraphQL query : https://github.com/yann-yinn/yineo-gridsome/blob/0fd13e8e8b2b428ad8f5db053bbd8ef4329a7361/src/pages/Index.vue#L52

```
  query Home {
    allBlogPost (perPage: 4) {
      edges {
        node {
          title
          image (width: 200)
          content
          path
          date(format: "D MMMM, YYYY")
        }
      }
    }
  }
```

and here is my g-image component:
https://github.com/yann-yinn/yineo-gridsome/blob/0fd13e8e8b2b428ad8f5db053bbd8ef4329a7361/src/components/PostTeaserHomepage.vue#L5


```vue
<template>
  <div>
    <div class="columns">
      <div class="column is-one-third">
        <g-image v-if="post.image" :src="post.image"/>
      </div>
      <div class="column">
        <h2 v-html="post.title"></h2>
        <PostDate :date="post.date"/>
        <div class="content" v-html="striptags(post.content).substr(0, 200) + '...'"></div>
        <div>
          <BulmaButtonLink :to="post.path">Lire l'article</BulmaButtonLink>
        </div>
      </div>
    </div>
  </div>
</template>
```

**Comment by AndreasHeintze** [comment]
What does your data look like if you run the query in http://localhost:8080/___explore ?

**Comment by yann-yinn** [comment]
@AndreasHeintze i removed `content` key for clarity : 

```json
{
  "data": {
    "allBlogPost": {
      "edges": [
        {
          "node": {
            "title": "Un mémo interactif des commandes Vim",
            "image": "/images/main-image-vim-memo.jpeg",
            "path": "/post/un-memo-interactif-des-commandes-vim-pour-utilisateurs-occasionnels",
            "date": "2 August, 2018"
          }
        },
        {
          "node": {
            "title": "REACT + GRAPHQL + WORDPRESS = REACTPRESS 💛",
            "image": "/images/main-image-react-wordpress.jpeg",
            "path": "/post/react-wordpress-reactpress",
            "date": "2 July, 2018"
          }
        },
        {
          "node": {
            "title": "Configurer un dédié avec Nginx avec certificat ssl renouvelable pour une application Node.js",
            "image": "/images/main-image-nginx.jpeg",
            "path": "/post/configurer-un-dedie-avec-nginx-avec-certificat-ssl-renouvelable-pour-une-application-node-js",
            "date": "2 May, 2018"
          }
        },
        {
          "node": {
            "title": "React ou Vue.js ? les deux mon capitaine.",
            "image": "/images/main-image-react-vs-vue.jpeg",
            "path": "/post/react-ou-vue-js-osef-les-deux-sont-formidables",
            "date": "23 April, 2018"
          }
        }
      ]
    }
  }
}
```

**Comment by AndreasHeintze** [comment]
Just try to make the value in image an absolute path to your image files. Like an example I have:
/Users/heintze/Desktop/_repos/my-gridsome-site/files/product/images/motor/avgassystem/sportavgassystem/sportavgassystem-peugeot-206-2.0-1998-2008/9e32ba31034a0319b12b6c7b74d0e584_0001.jpg

**Comment by yann-yinn** [comment]
Makes sense, Node can't know where is the file as said above... 
I'm using markdown plugin so i'm not adding the nodes myself and don't know where to add the `path.resolve`

**Comment by AndreasHeintze** [comment]
I don't use those plugins, maybe you can ask in the Discord community?

**Comment by yann-yinn** [comment]
Correct me if i am wrong but I guess this code is supposed to work, as long as `$page.post.image` is a correct relative path, e.g : `../../static/images/m-image.jpeg`

```vue
<g-image :src="$page.post.image" width="200" />
```
