### ISSUE TITLE
Incorrect package name for LowDB source plugin

### ISSUE THREAD

**Issue by ozanmuyes** [gridsome/gridsome#339]
## Description

On "Lowdb source for Gridsome" page ([https://gridsome.org/plugins/gridsome-source-lowdb](https://gridsome.org/plugins/gridsome-source-lowdb)) install instruction for **Yarn** is incorrect; it reads `yarn add @gridsome/source-lowdb`. Once I did that this error shows up;

```shell
yarn add v1.13.0
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@gridsome%2fso urce-lowdb: Not found".
info If you think this is a bug, please open a bug report with the information p rovided in "D:\\Code\\blog-tests\\blog-gridsome\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

and in the `yarn-error.log` file Trace follows;

`Error: https://registry.yarnpkg.com/@gridsome%2fsource-lowdb: Not found`

**But** when I install the package with this command, it worked;

```shell
$ yarn add gridsome-source-lowdb
```

### Steps to reproduce

```shell
$ gridsome create lowdb-source-bug
$ cd lowdb-source-bug
$ yarn add @gridsome/source-lowdb
```

### Expected result

It should install the package as dependency.

### Actual result

The error occured (mentioned above).

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.6
- @gridsome/cli version: 0.0.9
- gridsome-source-lowdb: 0.1.4
- yarn: 1.13.0

Browser: Irrelevant
 
For Tooling issues:
- Node version: 10.15.1  
- Platform:  Windows 

Others:

</code></pre>

**Comment by ozanmuyes** [comment]
To further extend; the plugin site ([https://gridsome.org/plugins/gridsome-source-lowdb](https://gridsome.org/plugins/gridsome-source-lowdb)) contains erroneous Usage instruction. It currently reads;
```js
export default {
  plugins: [
    {
      use: '@gridsome/source-lowdb',
      options: {
          path: "",
          entityName: "posts",
          typeName: 'LowdbPost'
      }
    }
  ]
}
```

and results in an error saying `Error: Cannot find module '@gridsome/source-lowdb'`, where it should be;

```js
export default {
  plugins: [
    {
      use: 'gridsome-source-lowdb',
      options: {
          path: "",
          entityName: "posts",
          typeName: 'LowdbPost'
      }
    }
  ]
}
```

(note the value of `use` key).

**Comment by hjvedvik** [comment]
That plugin is not maintained in this repository, so there isn't much we can do to fix it. I was able to find it in this repository: https://github.com/linuxing3/gridsome.org/tree/master/src/plugins/source-lowdb. So it looks like an internal plugin which has been published to npm.
