### ISSUE TITLE
Different "source-wordpress" in single page

### ISSUE THREAD

**Issue by Jurero123** [gridsome/gridsome#349]
Is there a way to use multiple WordPress sources conditionally (based on the domain name on which app is hosted) in a single Gridsome application?

I have WordPress multisite (one site for each language) where users will be adding products which will be displayed on different domains as product landing pages. Here is the example: https://top.vigoshop.si/pametna-ura-premium-elegant/

Everything is working great, but I would like to use single Gridsome app that will be deployed on multiple domains (per language) and to only get data from right source. If app is hosted on .DE domain, it would have to only get data for German site.

I am using plugin @gridsome/source-wordpress, but I would need to set some sort of condition in "gridsome.config.js" file. My first idea was to get domain name with javascript, but as far as I understood, this is not possible.

Thank you,
Jure

**Comment by hjvedvik** [comment]
You could try to get the URL from an env variable instead like `process.env.WORDPRESS_URL`. But the requests to WordPress would need to know which language you want to fetch?

**Comment by Jurero123** [comment]
@hjvedvik thanks, I will try to make it work using .env file (I will copy it in a deployment hook from external directory).
