### ISSUE TITLE
Frontmatter

### ISSUE THREAD

**Issue by bagahunda** [gridsome/gridsome#35]
I am trying to create a blog with markdown files as a post. And I didn't find a way how to use the custom info in frontmatter (like author, summary or cover for cover image). In Gatsby, we have access to frontmatter info and can use it in the template. What about gridsome?

**Comment by hjvedvik** [comment]
Your frontmatter data should be available as `node.fields.{fieldName}`. But you can access them directly on the node like `node.{fieldName}` if you update to Gridsome v0.3 (which was just published). You can also open `http://localhost:8080/___explore` in your browser after you run the `gridsome develop` command to explore your GraphQL schema and see if your data is there :)

**Comment by bagahunda** [comment]
I've updated Gridsome to v0.3 and now my page-query is broken. I've got an error `Unknown type "Int"` in page-query at `query Posts ($page: Int) {...`

**Comment by lobo-tuerto** [comment]
@bagahunda I think you should use a path instead of an `Int` now.

**Comment by hjvedvik** [comment]
@bagahunda I tested your `gridsome-test` repository. I didn't get the `Unknown type "Int"` error, but the Remark plugin failed to parse your post contents. But it works when updating to `gridsome@0.3.3` and `@gridsome/source-filesystem@0.2.0`. And also change `<g-link to="login">` to `<g-link to="/login">` in `pages/Index.vue`. Nice site :)

**Comment by YogliB** [comment]
@bagahunda Is this still an issue with Gridsome v0.5.0?

**Comment by hjvedvik** [comment]
I'm closing this as it should work as expected. Feel free to re-open if it's still a problem.
