### ISSUE TITLE
How to add Schema Markup?

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#352]
## Description

I want to add schema markup that I've created using Google's Structued Data Markup Helper tool.

Where do I place the below code?

<code>

<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "name",
  "telephone" : "number",
  "email" : "",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "street",
    "addressLocality" : "city",
    "addressRegion" : "state",
    "postalCode" : "postal code"
  }
}
</script>
</code>

**Comment by jd-fillmore** [comment]
Any movement?

**Comment by jd-fillmore** [comment]
@hjvedvik 

Does Gridsome not support schema?

**Comment by hjvedvik** [comment]
I haven't used the Structured Data Markup Helper myself, but I guess you want to add that to your markup? Take a look at the docs for adding `script` tags with here [`vue-meta`](https://github.com/nuxt/vue-meta#script-object).

**Comment by hjvedvik** [comment]
You can for example do this in the page component where you want the script. Just replace `innerHTML` with the contents of your script tag.

```html
<template>
  <Layout>...</Layout>
</template>

<script>
export default {
  metaInfo: {
    script: [
      { innerHTML: '{ "@context": "http://schema.org" }', type: 'application/ld+json' }
    ]
  }
}
</script>
```

**Comment by robaxelsen** [comment]
@jd-fillmore closing, as your issue has been addressed above :point_up:

Feel free to re-open if you're still in need of help!

**Comment by ftpyz** [comment]
hi add this method but rich test tool not find my rich snippet http://kolaytatligrid.surge.sh/yazilar/

**Comment by joeelia** [comment]
If you want you can do something like this if its cleaner for you.

`
data() {
   return {
     jsonld:  {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [{
        "@type": "Question",
        "name": "What is the return policy?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Most unopened items in new condition and returned within <strong>90 days</strong> will receive a refund or exchange. Some items have a modified return policy noted on the receipt or packing slip. Items that are opened or damaged or do not have a receipt may be denied a refund or exchange. Items purchased online or in-store may be returned to any store.<br /><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
        }
      }, {
        "@type": "Question",
        "name": "How long does it take to process a refund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "We will reimburse you for returned items in the same way you paid for them. For example, any amounts deducted from a gift card will be credited back to a gift card. For returns by mail, once we receive your return, we will process it within 4–5 business days. It may take up to 7 days after we process the return to reflect in your account, depending on your financial institution's processing time."
        }
      }, {
        "@type": "Question",
        "name": "What is the policy for late/non-delivery of items ordered online?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Our local teams work diligently to make sure that your order arrives on time, within our normaldelivery hours of 9AM to 8PM in the recipient's time zone. During  busy holiday periods like Christmas, Valentine's and Mother's Day, we may extend our delivery hours before 9AM and after 8PM to ensure that all gifts are delivered on time. If for any reason your gift does not arrive on time, our dedicated Customer Service agents will do everything they can to help successfully resolve your issue. <br/> <p><a href=https://example.com/orders/>Click here</a> to complete the form with your order-related question(s).</p>"
        }
      }, {
        "@type": "Question",
        "name": "When will my credit card be charged?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "We'll attempt to securely charge your credit card at the point of purchase online. If there's a problem, you'll be notified on the spot and prompted to use another card. Once we receive verification of sufficient funds, your payment will be completed and transferred securely to us. Your account will be charged in 24 to 48 hours."
        }
      }, {
        "@type": "Question",
        "name": "Will I be charged sales tax for online orders?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text":"Local and State sales tax will be collected if your recipient's mailing address is in: <ul><li>Arizona</li><li>California</li><li>Colorado</li></ul>"}
        }]
    }
   }
 },
 metaInfo() {
   return {
      script: [
        { innerHTML: JSON.stringify(this.jsonld), type: 'application/ld+json' }
      ]
}
},`
