### ISSUE TITLE
Major SEO problem with Gridsome. Not reading any image alt tags.

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#353]
## Description

Even when setting alt tags on images using Gridsome, when ran through any SEO checker, none of them can actually read the alt tags.

I have set alt tags on all of my images - yet, whenever running my site through an SEO alt tag checker, they all come back with "you have no alt tags set on any of your images".

Here's an example of the results [from an audit today](https://www.seoptimer.com/alt-tag-checker/infused.agency).

And here's an example of my [logo having a clear alt tag.](https://imgur.com/a/227UNN5)

This is a huge problem from an SEO perspective.

Does anyone have a fix?

### Steps to reproduce

[View this SEO alt tag checker audit of my site](https://www.seoptimer.com/alt-tag-checker/infused.agency).

### Expected result

It should catch and read all alt tags.

### Actual result

It doesn't.

**Comment by hjvedvik** [comment]
SEOptimer probably caches the results for some time. I get different results now: `We found 12 images on your page and 6 of them are missing the attribute`. Looks like the fallback images inside the `noscript` tags misses the `alt` attribute. It shouldn't have any impact on your SEO scores, but I'll fix it in the next version.

**Comment by jd-fillmore** [comment]
Thanks @hjvedvik !
