### ISSUE TITLE
Template vs component query

### ISSUE THREAD

**Issue by Jurero123** [gridsome/gridsome#355]
This is probably not a bug, but somebody else may find it useful.

Right now I have a huge page-query in the [main template](https://gridsome.org/docs/querying-data#query-data-in-templates) to fetch all WordPress + ACF data. I am assigning queried data to Vue instance data and passing it as props to child components.

I am wondering if there is a better way so that each component would have its own page-query or in this case <[static-query](https://gridsome.org/docs/querying-data#query-data-in-components)> and it would not need props (it would make it much more reusable)?

**Comment by Al-Rozhkov** [comment]
I think the way you doing this now is a best practice. This is normal Vue [One-Way Data Flow](https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow).

You have one place to fetch data (in your Template component) and several child components to display your data. Personally after working with Vue for awhile I find this approach convenient. It helps when your app grows and you going to refactor something.

**Comment by robaxelsen** [comment]
Closing, as answered by @Al-Rozhkov and +1'ed by @tomtev.
