### ISSUE TITLE
Vue router Scroll behavior

### ISSUE THREAD

**Issue by tweety101** [gridsome/gridsome#356]
I am looking to keep the scroll position on specific route changes. Strangely it worked by default in the the development mode but keeps scrolling to the top in production.

Does anyone know how to change the options (scrollBehavior) of Vue-router in Gridsome?

Thanks!!

**Comment by darkrubyist** [comment]
I'm having the same issue. Still trying to figure out how can I fix this on production.

**Comment by tweety101** [comment]
I found a way to do it. Not sure if it's the recommended way but it works (so far). @darkrubyist 

In the main.js file you can overwrite the scrollBehavior function on the router instance: 

export default function (Vue, { router, head, isClient }) {
  // standard gridsome stuff
  Vue.component('Layout', DefaultLayout);
  
  router.options.scrollBehavior = function(to, from , savedPosition) {
    
    if (savedPosition) {
      return  savedPosition;
    }
    if (to.hash) {
      return {selector: to.hash};
    }
    if ((from.name == 'project' && to.name == 'project') || ((from.name == 'work' && to.name == 'project'))) {
      return window.scrollHeight
    }
    return {x: 0, y: 0}
  }
}

Looking forward to any feedback on this.

**Comment by robaxelsen** [comment]
@hjvedvik :point_up:

**Comment by hjvedvik** [comment]
@tweety101 I think it's the only way to do it and seems to work pretty well :) We might add some method to modify the options passed to the router sometime later.

**Comment by cameronrr** [comment]
This also worked for me, though I needed to do some extra work to have it playing nicely with page transitions, since I am overriding App.vue for transitions on the router-view. Here is how I achieved it with proper 'back' scroll location set even with the mode="out-in" transitions, by hooking into the before-enter event.

```vue
<transition name="fade" mode="out-in" appear @before-enter="beforeEnter">
  <router-view />
</transition>
```

``` javascript
export default function (Vue, { router, head, isClient }) {
  Vue.component('DefaultLayout', DefaultLayout)

  router.options.scrollBehavior = function (to, from, savedPosition) {
    return new Promise((resolve) => {
      router.app.$root.$once('scrollBeforeEnter', () => {
        resolve(savedPosition ? savedPosition : { top: 0, behavior: 'smooth' })
      })
    })
  }
}
```
