### ISSUE TITLE
Gridsome blog posts aren't being indexed by Google, but newly created pages are.

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#358]
## Description

I have a sitemap, and all pages on my site are indexed, and even old blog posts are.

However, NEWLY created posts are not being indexed - even when fetching with Google.

I've created two blog posts in the past week, and have fetched them with Google. Even after Google mentions it's in the que to index, I checked back hours or days later, and they're not indexing.

But, I've created about 5-8 new actual pages - fetched those pages with Google, and those are indexed almost immediately by Google.

[Here's a code sandbox link to my site.](https://codesandbox.io/s/github/jd-fillmore/infused-gridsome)

Below are some posts that I've created in the past week, that when fetched with Google, aren't getting indexed:

[Blog one](https://infused.agency/posts/how-do-i-make-my-website-more-user-friendly)
[Blog two](https://infused.agency/posts/how-can-i-improve-my-local-seo-results/)

Is there something wrong with the sitemap plugin I'm using? Or something else?

### Steps to reproduce

1. Write blog post
2. Sign into Search Console
3. Fetch with Google
4. They don't index even after days, but pages do

### Expected result

Blog posts should be getting indexed.

### Actual result

They don't. Only newly created pages do.

**Comment by cossssmin** [comment]
Google indexing is not something that Gridsome influences. As long as those posts can be accessed with JavaScript disabled, it's not about the generator itself.

Regarding your sitemap, I do see you're using:

```
'/blog*': {
```

... while the docs say:

```
'/articles/*'
```

Notice the `/` before `*`.

So it might be that your sitemap URLs are broken/incorrect, and you need to wait more until Google crawls your site and indexes it.

**Comment by jd-fillmore** [comment]
Thanks @cossssmin , I've adjusted this.

Is there a way to, in the gridsome.config.js, to adjust how much Google crawls the blogs are weekly to daily? Is it just a matter of changing:

```
'/blog/*': {
    changefreq: 'weekly',
    priority: 0.5
}
```

to

```
'/blog/*': {
    changefreq: 'daily',
    priority: 0.5
}
```

?

**Comment by cossssmin** [comment]
Yes, you can do that. 

The [sitemap](https://www.npmjs.com/package/sitemap) package is used under the hood, by the way.
