### ISSUE TITLE
NodeList native class not defined on build

### ISSUE THREAD

**Issue by milesingrams** [gridsome/gridsome#359]
## Description

If any package (in my case Anime.js) references the class 'NodeList' gridsome build spits the error 'ReferenceError: NodeList is not defined'. This is odd since NodeList is a native class to all browsers.

### Steps to reproduce

put 'console.log(NodeList)' in any component in the created lifecycle hook.

### Expected result

successful gridsome build

### Actual result

gridsome develop will work but gridsome build will crash

What happened.

### Environment

<pre><code>
Libs:
- gridsome version: v0.5.7
- @gridsome/cli version: v0.0.9

For Tooling issues:
- Node version: v10.15.0
- Platform:  Max OS X
</code></pre>

**Comment by hjvedvik** [comment]
Gridsome renders each page "server-side" in Node.js and `NodeList` isn't available in that context. You can check for `process.isClient` to only run some code in the browser.

**Comment by milesingrams** [comment]
Awesome! Thanks so much for the quick response. I see now that I can wrap any call to animejs with the process.isClient check. Also very useful to know to avoid "server-side" rendering of particles in a particle effect. that would be quite a lot of elements.

**Comment by milesingrams** [comment]
So I'm still running into some issues. I have a dynamic component that I don't want SSR processed due to it being a randomly chosen component. If I put a v-if on it with a data property that is equal to process.isServer it gives me the error: "'appendChild' on 'Node': This node type does not support this method." Is there any way to have a Gridsome component that is equivalent to Nuxts <no-ssr> component? https://nuxtjs.org/api/components-no-ssr/

**Comment by milesingrams** [comment]
Sorry didn't see the <client-only> tag in the docs. thats perfect. Ignore my last comment!!

**Comment by hjvedvik** [comment]
No problem :)

**Comment by DaakyeHeneEmma** [comment]
NodeList is not defined in my Svelte/Sapper app, taking it out from the SSR and rendering it to only the client but still run int issues
