### ISSUE TITLE
Can someone show me the way to connect data?

### ISSUE THREAD

**Issue by findborg** [gridsome/gridsome#36]
I have everything working,  even added some pages.  All good.
I have tried all afternoon to get data to pass to the pages.  eventually,  I would like to parse outside json urls for list.  But,  for now I would be happy just getting a list to print out.   I need to be able to make a list of this.  A Tittle and image and a url.

**Comment by hjvedvik** [comment]
So you want to fetch data from a custom Rest API which gives you JSON in response?

In the latest version (`gridsome@0.3.0` was published a few hours ago) you can fetch data in a `gridsome.server.js` file in your project. You can see an example  [here](https://gridsome.org/docs/data-store-api#fetching-external-data) which fetches from an API and inserts the data into the data store. You can then access that data in your Vue components with GraphQL.

**Comment by findborg** [comment]
@hjvedvik Yes,  that is my ultimate goal.  However,  I am trying to work my way up.  For example,  you used yaml data to create your menu for the gridsome site in the data directory.  All I want at this time is to figure out how to put list data in the data directory and use it.  Basically,  I want to build a menu with icons and a title.  
That said,  I hope to graduate to the outside APIs soon and learn how to use that  GraphQL.  The interface for that is awesome,  but I was totally lost.  Have to do more research..

**Comment by findborg** [comment]
Ok,  I found where you do an import in your docs.vue file for the data.  I just need to practice that it would seem.  I just do not want to use yaml I want to use json...   For the practice.
