### ISSUE TITLE
Validation Error with Async and Defer

### ISSUE THREAD

**Issue by mjatharvest** [gridsome/gridsome#362]
## Description

This is a very small thing, when adding a script tag to the head via metaInfo in a layout.vue file I see that the async and defer attributes on the script tag have a value of true.

### Steps to reproduce

```
<script>
  import MainNav from '~/components/MainNav.vue'
  import Footer from '~/components/Footer.vue'

  export default {
    metaInfo: {
      script: [
        { src: '//www.google.com/recaptcha/api.js', async: true, defer: true }
      ]
    },

```
### Expected result
`<script data-vue-tag="true" src="//www.google.com/recaptcha/api.js" async defer></script>`

### Actual result
`<script data-vue-tag="true" src="//www.google.com/recaptcha/api.js" async="true" defer="true"></script>`

This end up giving a validation error: Bad value true for attribute async on element script.

### Environment

<pre><code>
- gridsome version: 0.5.7
</code></pre>
![Screen Shot 2019-04-12 at 9 27 09 AM](https://user-images.githubusercontent.com/285877/56044636-39f3a800-5d05-11e9-91de-fbbdd8f272a8.png)

**Comment by danvega** [comment]
This is coming from vue-meta https://github.com/nuxt/vue-meta but what you're doing there is ok. I have used that before and it worked just fine for me.

`script: [{ src: "https://platform.twitter.com/widgets.js", async: true }]`

**Comment by mjatharvest** [comment]
Thanks, perhaps I should post this on the vue-meta repo.
