### ISSUE TITLE
Ability to make links on the same host not be handled by the router

### ISSUE THREAD

**Issue by freaktechnik** [gridsome/gridsome#367]
## Description

It appears all links referring to the current host (whether explicitly, relative, or with target _blank) are handled by vue-router and lead to 404s if they are actually not part of the gridsome routes. Middle-clicking to open in a new tab works fine of course.

### Steps to reproduce

- Add a link like `<a href="/archive/v2">` to your page
- Have a separately managed page at `/archive/v2`
- Single click on link in your deployed page

Example: all the archive links on https://humanoids.be/archive

### Expected result

Links that the router doesn't recognize should be externally routable. Either by respecting `target="_blank"`, or something like `rel="external"` (not sure if that's semantically entirely accurate).

### Actual result

The link is handled by the router of gridsome and leads to a 404.

### Environment

Libs:
- gridsome version: 0.5.7
- @gridsome/cli version: 0.0.9

Browser:
- [x] Chrome (desktop) version 73
- [x] Chrome (Android) version 73
- [ ] Chrome (iOS) version XX
- [x] Firefox version 66
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.10.0
- Platform:  Linux

**Comment by Al-Rozhkov** [comment]
Related to #82 (Make it possible to use <g-link> on external links)

**Comment by robaxelsen** [comment]
@hjvedvik can this be closed, or PR merge not in release yet?

**Comment by hjvedvik** [comment]
@robaxelsen This was released in 0.5.8, so I'll close this :)
