### ISSUE TITLE
Contentful api connection doesn't work

### ISSUE THREAD

**Issue by bhenbe** [gridsome/gridsome#37]
Hello all,

it tried the Contentful plugin but it doesn't seems to work.

I set a contentful space and add the parameters (space & accesstoken) to the gridsome config file.
When i write "gridsome develop" in my console, here's the errors that occur:

**

> TypeError: api.loadSource is not a function
>     at new ContentfulSource (/Applications/gridsome/techyourchance/node_modules/@gridsome/source-contentful/index.js:17:9)
>     at Plugins.plugins.app.config.plugins.map.entry (/Applications/gridsome/techyourchance/node_modules/gridsome/lib/app/PluginsRunner.js:32:24)
>     at Array.map (<anonymous>)
>     at new Plugins (/Applications/gridsome/techyourchance/node_modules/gridsome/lib/app/PluginsRunner.js:14:39)
>     at App.init (/Applications/gridsome/techyourchance/node_modules/gridsome/lib/app/App.js:62:20)
>     at App.bootstrap (/Applications/gridsome/techyourchance/node_modules/gridsome/lib/app/App.js:42:23)
>     at module.exports (/Applications/gridsome/techyourchance/node_modules/gridsome/lib/app/index.js:11:13)
>     at module.exports (/Applications/gridsome/techyourchance/node_modules/gridsome/lib/develop.js:14:21)
>     at args (/Applications/gridsome/techyourchance/node_modules/gridsome/index.js:41:12)
>     at Command.program.command.description.option.option.action.args (/Applications/gridsome/techyourchance/node_modules/gridsome/index.js:8:44)
>     at Command.listener (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:315:8)
>     at Command.emit (events.js:182:13)
>     at Command.parseArgs (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:654:12)
>     at Command.parse (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:474:21)
>     at Object.<anonymous> (/usr/local/lib/node_modules/@gridsome/cli/bin/gridsome.js:48:9)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)

**
Thank you for your help.

**Comment by tomtev** [comment]
Hi @bhenbe . Could you try to update all your packages? Gridsome package must be 0.3.

**Comment by bhenbe** [comment]
Hi @tomtev my packages are up-to-date. The error still occurs.

**Comment by tomtev** [comment]
Do you get Gridsome v0.3 at top when running "gridsome develop"?

**Comment by tomtev** [comment]
Try run `yarn install` again

**Comment by bhenbe** [comment]
I updated the package.json to change the gridsome version needed and with a npm update, it works ! Thanks for your help.
