### ISSUE TITLE
g-image broken with dynamic source

### ISSUE THREAD

**Issue by envygeeks** [gridsome/gridsome#382]
## Description

```vue
<template>
    <footer class=post__meta>
      <g-image
        height=48
        class=post__meta__avatar
        :src="post.author.avatar"
        width=48
      />
    </footer>
</template>
<page-query>
  query {
    posts: allPost(perPage: 3) {
      edges {
        node {
          title
          timeToRead
          content
          path

          author {
            avatar
            website
            name
          }
        }
      }
    }
  }
</page-query>
```

* `post.author.avatar` == '~/assets/avatar/avatar.jpg`
  * exists as `src/assets/avatar/avatar.jpg`

### Expected result

An image, it works when not dynamic.

### Actual result

It doesn't work?

### Environment

* Safari, Chrome
* Latest version of Gridsome
  * As of date of ticket.
* node.js LTS

**Comment by Al-Rozhkov** [comment]
Duplicate #292 (g-images with dynamic paths not correctly generating full feature set).
