### ISSUE TITLE
/info causes heavy blocking.

### ISSUE THREAD

**Issue by envygeeks** [gridsome/gridsome#387]
## Description

When refreshing a page the "/info" url causes a hefty amount of blocking.  After checking this isn't apart of our site conversion, but seems to be causing a lot of blocking (even if the site is already built... and should refresh from cache with inline customizations removed.)

### Actual result

![Screen Shot 2019-04-27 at 5 34 13 PM](https://user-images.githubusercontent.com/99763/56855894-6c142500-6915-11e9-9786-545d24038cc4.png)

### Environment

* `@gridsome/cli` v0.0.9
* `gridsome` v0.5.8

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: LTS
- Platform:  MacOS

**Comment by tomtev** [comment]
What does the info page include? And is this from the built version?

**Comment by robaxelsen** [comment]
@envygeeks please see response from @tomtev :point_up:

**Comment by envygeeks** [comment]
I honestly don't know what comes from that page, as it's part of gridsome, I do know that it happens whenever I tell gridsome not to use 127.0.0.1, but all I know is that page is part of the graphql stuff probably.

**Comment by probil** [comment]
It seems to be fixed in the latest version (`v0.7.8`). 
Can you confirm that @envygeeks ?
