### ISSUE TITLE
Add support for Node 12

### ISSUE THREAD

**Issue by leopiccionia** [gridsome/gridsome#388]
Gridsome currently depends on `sharp` v0.21. But only `sharp` v0.22.1+ is compatible with Node 12, as it depended on some V8 internals that were removed (`v8::Handle`). Trying to install Gridsome on Node 12 fails with a `gyp` error.

For related issue upstream, see https://github.com/lovell/sharp/issues/1668.

**Comment by marcj** [comment]
@chore Cool, thanks! Can you tell us when the next version will be released, please?
