### ISSUE TITLE
Add support for Vue components in Markdown files

### ISSUE THREAD

**Issue by lobo-tuerto** [gridsome/gridsome#39]
Hello,

I have this use case:
I'd like to be able to use Vue components inside Markdown files.

Example (this is not currently working):

*src/components/Hello.vue*
```html
<template lang="pug">
p Hello component!
</template>
```

*src/templates/Post.vue*
```html
<template lang="pug">
layout
  div(v-html="$page.post.content")
</template>

<page-query>
query Post ($path: String!) {
  post: post (path: $path) {
    title
    content
  }
}
</page-query>

<script>
import Hello from '@/components/Hello.vue'

export default {
  components: { Hello },
  metaInfo () {
    return {
      title: this.$page.post.title
    }
  }
}
</script>
```

*blog/first-post.md*
```md
---
slug: first-post
title: This is my first post!
---

# This is some first level title

* Bullet point #12
* Bullet point #2
* Bullet point #3

## This is a second level title

> This is a blockquote

<Hello />
```

*gridsome.config.js*
```js
module.exports = {
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'blog/**/*.md',
        typeName: 'Post',
        route: '/blog/:slug'
      }
    }
  ]
}
```

**Hello component!** is not being rendering on `/blog/first-post`.

Is this possible? or easily achievable?
I think this feature could be a very powerful addition.

Cheers,
VA

**Comment by hjvedvik** [comment]
Yes, that would be powerful. I think there are two ways this could be achieved. Either by running all the markdown files through Vue loader and transform them into Single File Components in a source plugin. Or by server-side rendering them in a Remark transformer plugin and then hydrate the markup in the browser. Right now it's not possible but we will see if we can make it work before v1.0.

**Comment by lobo-tuerto** [comment]
Also, I don't know if this can help, but I'll leave it here:

https://github.com/egoist/vmark

**Comment by SteveEdson** [comment]
Would it be possible to just get this working client-side only as an interim solution? If I register the component as a global component, ie:

```js
Vue.component('HelloWorld', HelloWorld);
```

It's just being left in the DOM as

`<hello-world></hello-world>`

It'd be great if that could be rendered in the traditional way.

**Comment by hjvedvik** [comment]
We have been working on a plugin which lets you use Vue components in markdown files. It will run all the markdown files through webpack, so it is not like a source plugin. But it can be a replacement for the components in `src/pages` or be used for a documentation section etc. The syntax will be like this:

```jsx
---
title: A cool title
---
import MdComponent from '~/components/MdComponent.md'
import VueComponent from '~/components/VueComponent.vue'
import data from '~/data.json'

# {{ $frontmatter.title }}

<MdComponent :option="data.option"/>

Lorem ipsum dolor sit amet, consectetur adipisicing elit.

<VueComponent>{{ data.text }}</VueComponent>

```

The plugin also uses the `@gridsome/transformer-remark` under the hood so you will be able to use `@gridsome/remark-prismjs` etc. `page-query` and `static-query` will also work as in Vue components.

**Comment by SteveEdson** [comment]
This sounds perfect. Is this essentially .mdx support?

Is it possible to help test this plugin out now?

**Comment by hjvedvik** [comment]
It's not based on `mdx`. It simply transforms the markup into a single file component and lets the `vue-loader` handle the rest. So it will only support the same syntax as in a Vue template plus markdown. And it only supports the `import` statement for importing components or data, no `export`.

There are several things we want to improve in core before merging it, but we can probably open a PR that can be tested soon :)

**Comment by SteveEdson** [comment]
Perfect. Let me know as soon as I can test it please, it'd be great to have this feature available.

**Comment by callumflack** [comment]
FYI, [MDX has Vue support](https://github.com/mdx-js/mdx/issues/238).

Could be worthwhile describing the method as there seems to be many caveats & differences in approach around using "reactive javascript" components in markdown between [Nuxtent](https://github.com/nuxt-community/nuxtent-module/commits/master) (which finally has some progress), [vmark](https://github.com/egoist/vmark) and [bespoke](https://github.com/haiiro-io/violet) [solutions](https://github.com/galvez/nuxpress) (in Vue), and MDX.

**Comment by danrocha** [comment]
Could definitely be worthwhile. I am surprised this is not a more frequently requested feature. I was halfway building my blog in Gridsome but had to move Vuepress because of the lack of Vue-in-Markdown support in it. And I would gladly come back to Gridsome if it were ever implemented...

is this really an edge use case?

**Comment by hjvedvik** [comment]
@danrocha No, it isn't. We are working on a plugin which makes it possible. It will work like in my comment above. The main difference between that plugin and the filesystem plugin is that it will compile each markdown file with webpack to generate HTML markup that can be hydrated by Vue in the browser. I'm not sure how well it will perform for very large blogs etc but should be perfect for documentation sites or smaller blogs.

**Comment by hjvedvik** [comment]
@SteveEdson @danrocha Just created a PR #424 for the plugin. Any feedback would be appreciated.

**Comment by janvorisek** [comment]
Great work on the PR #424 so far.

I'm curious if anyone got Vue SFC working in the content files. Possibly without using markdown?
I'd sacrifice Markdown support in blog post content files for the ability to use components.

**Comment by Zyles** [comment]
Also looking for vue component support in Markdown files.

Articles and content is more than text nowadays and we need to fit content blocks, ads and what not between the text.

**Comment by hacknug** [comment]
This should be possible as of v0.7 https://gridsome.org/blog/2019/09/17/gridsome-v07/#vue-remark-plugin
