### ISSUE TITLE
How can I get all the markdown field to GraphQL node field?

### ISSUE THREAD

**Issue by godlike0108** [gridsome/gridsome#391]
## Summary

I use `@gridsome/source-filesystem` and `@gridsome/transformer-remark` to grab field data to GraphQL for use. Is it possible if I can get custom field from markdown file to GraphQL?

### Basic example

I have a custom named `desc` field in my `.md` file.

```
// a blog post md file
---
title: this is a blog
desc: this is descripton
---

This is a blog post
```

How can i config to fetch it successfully from query?

```
<page-query>
  query Posts ($page: Int) {
    allPost (page: $page) {
      edges {
        node {
          title
          desc
        }
      }
    }
  }
</page-query>
```

Include a basic example or links here.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

Because we may use custom field to define additional categories.

**Comment by namoda378** [comment]
something like this should work


```md
---
propa : sum A
title : sum title
---

```



```html
<template lang="pug">
    div
        h1 {{ this.$page.markdown.title }}
        h1 {{ this.$page.markdown.propA }}
</template>

<page-query>
    query Markdown ($path:String!) {
        markdown : markdown(path:$path){
            title
            propA
        }
    }
</page-query>
```

**Comment by danieldocki** [comment]
@namoda378 I did not understand your solution

I also need a similar solution...

```
---
path: home-page
main:
  about: >-
    **Bold Text**

    New Paragraph
  description: The Description
  title: The Title
---
```

**Comment by kaceo** [comment]
I also have source md files with many custom fields that I need to be able to access in GraphQL.  I think the source-filesystem package does not correctly parse custom fields, it apparently needs to know the type and format of each field to work, which is unnecessarily restrictive.  Also the error thrown by the parser is misleading --- in __explore you just see errors, which you find out is because __graphqql returns 404 (because the data nodes were not parsed).

**Comment by robaxelsen** [comment]
Assuming @kaceo's findings are correct, I am closing this. Feel free to open if new findings appear also in newest source-filesystem.

**Comment by kessir-cloudator** [comment]
@kaceo Are you saying custom fields work out of the box or did you have to change the config?

**Comment by wjustice** [comment]
@robaxelsen  I am using the most up-to-date version or source-filesystem and still getting the same behavior; no custom fields are being recognized.

**Comment by freshyill** [comment]
I have the exact same use case as @danieldocki and it just doesn't work. It seems like based on #445, #530 and #509 that this functionality is coming, but I don't see any movement on it for over a month.

@kaceo Is this actually working for you? How did you solve it? It sounds like you did something with your query, but I'm not sure. If you've found a workaround, could you share some more details?

For what it's worth, I'm working around it with [vue-markdown](https://www.npmjs.com/package/vue-markdown), but I'd rather not be using two completely separate Markdown parsers in one project.

**Comment by jlp0328** [comment]
@freshyill I reverted to 0.2.1 for the time being and this worked to allow for custom fields. Hope that helps!
