### ISSUE TITLE
Feature request: Infinite scroll

### ISSUE THREAD

**Issue by derevandal** [gridsome/gridsome#394]
## Summary

When user scrolls to end, another page will be loaded while he/she continue scrolling to the new page.

### Basic example

https://github.com/ElemeFE/vue-infinite-scroll

### Motivation

This feature increase user retention.

**Comment by hjvedvik** [comment]
We will include a `$fetch` method to fetch data for a specific path in Gridsome 0.6. You will then be able to get results for the next page in the `v-infinite-scroll` event. But you have to merge the results with your previous results manually. It will work like this for a blog with pagination:

```js
export default {
  data () {
    return {
      loadedPosts: [],
      currentPage: 1
    }
  },
  methods: {
    loadMore () {
      this.$fetch(`/blog/${this.currentPage + 1}`).then(({ data }) => {
        this.currentPage = data.posts.pageInfo.currentPage
        this.loadedPosts.push(...data.posts.edges)
      })
    }
  }
}
```

**Comment by derevandal** [comment]
Thanks!
Is  `currentPage` the page's id?
If am I using `/blog/post-slug`, how can I use $fetch without set next post is markdown as attr?

**Comment by hjvedvik** [comment]
The `currentPage` is just the current page number in the pagination. So the example above would fetch `/blog/2`, `/blog/3` and so on. But I think you want something like in this [comment](https://github.com/gridsome/gridsome/issues/177#issuecomment-464031727) to get the full path for the next post based on custom sorting. I have a working branch which lets you do that and might include it in 0.6 too.

**Comment by derevandal** [comment]
Oh, ok! This is that I'll need to use in what you commented.
I'll wait.
Thanks.

**Comment by dominiquedutra** [comment]
For anyone trying to acomplish this, I found https://peachscript.github.io/vue-infinite-loading/ to work quite well alongside gridsome 0.6.2.
For this example I`ll assume wordpress source as headless cms.

`yarn add vue-infinite-loading`

Import the component like so:

```
components: {
    Pager,
    Post,
    InfiniteLoading: () => import('vue-infinite-loading')
},
```

Ad the bottom of the list of posts on Index, render the component on ClientOnly tags (no SSR for this)

```
<ClientOnly>
    <infinite-loading @infinite="infiniteHandler" v-if="$page"></infinite-loading>
</ClientOnly>
```

Your infinite handler method will use gridsome 0.6.2 ability to fetch data from internal pages:
https://gridsome.org/docs/client-side-data#fetch-from-internal-pages

```
async infiniteHandler($state) {
    try {
        const results = await this.$fetch('/'+ (this.$page.allWordPressPost.pageInfo.currentPage+1) )
        if (results.data.allWordPressPost.edges.length > 0) {
            this.$page.allWordPressPost.pageInfo.currentPage = this.$page.allWordPressPost.pageInfo.currentPage + 1
            this.$page.allWordPressPost.edges = this.$page.allWordPressPost.edges.concat(results.data.allWordPressPost.edges)
            $state.loaded()
        } else {
            $state.complete()
        }
    } catch (error) {
        console.log(error)
    }
}
```

It works fine and you can navigate forward and backwards and it saves the correct height / state.
