### ISSUE TITLE
Support for Drupal

### ISSUE THREAD

**Issue by matt-e-king** [gridsome/gridsome#40]
Hello gridsome maintainers and community,

I work for the the University of Arizona, College of Agriculture and we primarily develop within VueJS and Drupal. We recently created a PWA with a "headless" Drupal 8 instance as our backend. Drupal 8 exposes a lot more RESTful endpoints and with the help of a jsonapi Drupal module, we were able to standardize this even further. 

Do you know if there is a roadmap for building out @gridsome/source-drupal (Drupal 8 support)? Or do you know any contributors in the community who might be starting this effort? If not, this is something we will be pursuing internally and would love to share our progress.

Thanks!

**Comment by hjvedvik** [comment]
Drupal is on our todo-list, but we haven't had the opportunity to look into it yet. No one is working on it as far as I know. And personally, I have only experience with Drupal 7, so it would be great if you want to create a source plugin for Drupal 8 :)

You can follow the [How to contribute](https://github.com/gridsome/gridsome#how-to-contribute) guide and create a PR. Then we can follow the progress and answer any questions you might have. Some APIs are still under development, so we can improve core with any necessary APIs or bugfixes if you run into problems during development. You can read about the [Data Store API](https://gridsome.org/docs/data-store-api) or look at the source code for the other source plugins to get started.

**Comment by matt-e-king** [comment]
Thanks, @hjvedvik, I will start that process now.

**Comment by matt-e-king** [comment]
https://github.com/gridsome/gridsome/pull/41
