### ISSUE TITLE
Vulnerabilities when installing Critical CSS plugin

### ISSUE THREAD

**Issue by willdante** [gridsome/gridsome#403]
## Description

When installing the Critical CSS plugin, I have 5 vulnerabilities.

Currently I use Gridsome 0.5.8 but the issue was already here when I discovered Gridsome, around 0.5.4.

### NPM Audit result

  Moderate        Prototype Pollution                                                                                                                         
  Package         lodash                                                                                                                                     
  Patched in      >=4.17.11                                                                                                                                  
  Dependency of   @gridsome/plugin-critical                                                                                                                
  Path            @gridsome/plugin-critical > critical > inline-critical > cave > lodash                                                 
                                                                                
  More info       https://npmjs.com/advisories/782                              
                                                                                                                                                             
  Moderate        Prototype Pollution                                                                                                                          
  Package         lodash                                                                                                                                       
  Patched in      >=4.17.11                                                                                                                                  
  Dependency of   @gridsome/plugin-critical                                                                                                                  
  Path            @gridsome/plugin-critical > critical > oust > cheerio > lodash                                                        
                                                                                
  More info       https://npmjs.com/advisories/782                              
                                                                                                                                                            
  Moderate        Prototype Pollution                                                                                                                      
  Package         lodash                                                                                                                                
  Patched in      >=4.17.11                                                                                                                     
  Dependency of   @gridsome/plugin-critical                                                                                                       
  Path            @gridsome/plugin-critical > critical > postcss-image-inliner  > asset-resolver > lodash                                     
                                                                                
  More info       https://npmjs.com/advisories/782                              
                                                                                                                                               
  Low             Prototype Pollution                                                                                                                      
  Package         lodash                                                                                                                             
  Patched in      >=4.17.5                                                                                                                             
  Dependency of   @gridsome/plugin-critical                                                                                                          
  Path            @gridsome/plugin-critical > critical > inline-critical > cave > lodash                                                 
                                                                                
  More info       https://npmjs.com/advisories/577                              
                                                                                                                                             
  Low             Prototype Pollution                                           
                                                                                
  Package         lodash                                                                                                                        
  Patched in      >=4.17.5                                                                                                                         
  Dependency of   @gridsome/plugin-critical                                                                                                           
  Path            @gridsome/plugin-critical > critical > oust > cheerio > lodash                                                        
                                                                                
  More info       https://npmjs.com/advisories/577                              
                                                                                
found 5 vulnerabilities (2 low, 3 moderate) in 16904 scanned packages
5 vulnerabilities require manual review. See the full report for details.

**Comment by robaxelsen** [comment]
@wildante thanks! could you also test with latest release 0.6 release, please?

@tomtev @hjvedvik any comment on this?

**Comment by willdante** [comment]
@robaxelsen Hi, it's ok with 0.6 ;)
