### ISSUE TITLE
SSR UnhandledPromiseRejectionWarning question

### ISSUE THREAD

**Issue by mjatharvest** [gridsome/gridsome#405]
## Description
I'm usign "vue-carousel" and setting it up for SSR as shown in the docs (https://gridsome.org/docs/assets-scripts/#without-ssr-support)

<code><pre>
<script>
export default {
  metaInfo: {
    title: 'The Vision for 90 North'
  },
  components: {
    Carousel: () =>
      import('vue-carousel')
      .then(m => m.Carousel)
      .catch(),
    Slide: () =>
      import('vue-carousel')
      .then(m => m.Slide)
      .catch()
  },
  data () {
   return {
     modalIndex: 0
   }
 }
}
</script></pre>
</code>

### Actual result

It's working ok but I get the following error when running "gridsome build"

<code><pre>
Compile assets - 11.7s                                                        a (node:3491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:24010)
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:20995
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:3491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:24010)
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:20995
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:3491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:24010)
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:20995
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:3491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:24010)
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:20995
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:3491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:3491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:24010)
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:20995
    at gridsome/node_modules/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:3491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Render HTML (12 pages) - 0.45s
Process files (0 files) - 0s
Process images (62 images) - 1.83s
</pre></code>

My question is, should I be concerned about these errors, or will I always get some kind of error when building?

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.8

Browser:
 
For Tooling issues:
- Node version: 10.5.0  
- Mac:  

</code></pre>

**Comment by mjatharvest** [comment]
Quick follow up, do I need to include something into the "mounted" hook also? Here is a full look at the complete vue template.

```
<template>
  <Layout>

    <ClientOnly>
      <Carousel
        :navigationEnabled="true"
        :navigationClickTargetSize="2"
        navigationNextLabel="&rsaquo;"
        navigationPrevLabel="&lsaquo;"
        :perPage="1"
        :perPageCustom="[[720,2],[960, 3]]">
         <Slide v-for="(edge, index) in $page.slideshow.edges" :key="edge.node.id">
           {{edge.node.title}}
         </Slide>
      </Carousel>
    </ClientOnly>

  </Layout>
</template>

<page-query>
  query Feature {
    slideshow: allFeature{
      edges{
  	    node {
          id
          title
        }
      }
    }
  }
</page-query>

<script>
export default {
  metaInfo: {
    title: 'Test Page'
  },
  components: {
    Carousel: () =>
      import('vue-carousel')
      .then(m => m.Carousel)
      .catch(),
    Slide: () =>
      import('vue-carousel')
      .then(m => m.Slide)
      .catch()
  }
}
</script>

<style></style>
```

**Comment by ndabAP** [comment]
Did you find a solution?

**Comment by mjatharvest** [comment]
No solution yet. The site builds and works ok so it's not a blocker. However I would love to get the bottom of the error at some point :)

**Comment by osama996** [comment]
What worked with me was that I put vue-carousel in a separate file and then import it and use it like this:
```
<ClientOnly>
    <Carousel />
</ClientOnly>
```

**Comment by mjatharvest** [comment]
@osama996 sounds good, could you post some sample code?

**Comment by osama996** [comment]
This is the component `VueCarousel` where I'm using "vue-carousel"

```
<template>
  <!-- eslint-disable -->
	<carousel
		:navigation-click-target-size="50"
		:per-page="1"
		:pagination-enabled="false"
		navigation-prev-label="〈"
		navigation-next-label="〉"
		class="mt-2"
		navigation-enabled
		autoplay
		loop
		:autoplay-timeout="4000"
	>
	<!-- eslint-enable -->
    <slide
      :key="partner.name"
      v-for="partner in partners"
    >
      <b-row class="text-center mb-5">
        <b-col
          cols="12"
          col
        >
          <b-img
            :src="partner.photo"
            :alt="`Foto von ${partner.name}`"
            class="photo"
            rounded="circle"
            width="200"
          />
          <span
            v-for="trait in partner.traits"
            :key="trait"
            class="hero-span badge font-weight-normal bg-transparent border badge-pill badge-light p-3 m-1"
          > {{ trait }}</span>
        </b-col>
      </b-row>

      <b-row class="justify-content-center">
        <b-col
          xs="12"
          md="7"
        >
          <h2 class="px-5 text-left">
            {{ partner.name }}
          </h2>
          <p class="px-5 text-left">
            {{ partner.description }}
          </p>
        </b-col>
      </b-row>
    </slide>
  </carousel>
</template>
<script>
export default {
  components: {
    Carousel: () =>
        import('vue-carousel')
          .then(m => m.Carousel)
          .catch(),
    Slide: () =>
        import('vue-carousel')
          .then(m => m.Slide)
          .catch()
  },
  props: {
    partners: {
      type: Object,
      default: () => ({})
    }
  }
}
</script>
```

And here's the parent component

```
<template>
  <section>
    <header>
      <h1>{{ config.title }}</h1>
    </header>
    <div class="decorator" />
    <b-container class="hero-container">
      <ClientOnly>
        <VueCarousel :partners="config.partners" />
      </ClientOnly>
    </b-container>
  </section>
</template>

<script>
import VueCarousel from './VueCarousel'
export default {
  components: { VueCarousel }
}
</script>
```

**Comment by clorichel** [comment]
Same TypeError while building with [vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper). Example template:

```vue
<template>
  <LayoutDefault>
    <div class="flex flex-wrap">
      <div class="w-full lg:w-7/12">
        <div class="lg:mx-48">
          <ClientOnly>
            <swiper :options="swiperOption" ref="mySwiper">
              <!-- slides -->
              <swiper-slide>
                slide1
              </swiper-slide>
              <swiper-slide>
                slide2
              </swiper-slide>
              <swiper-slide>
                slide3
              </swiper-slide>
              <div class="swiper-button-prev" slot="button-prev"></div>
              <div class="swiper-button-next" slot="button-next"></div>
              <div class="swiper-pagination"  slot="pagination"></div>
            </swiper>
          </ClientOnly>
        </div>
      </div>
  </LayoutDefault>
</template>

<script>
import LayoutDefault from '~/layouts/Default.vue'

export default {
  data() {
    return {
      swiperOption: {
        pagination: {
          el: '.swiper-pagination',
        },
      }
    }
  },
  components: {
    LayoutDefault,
    swiper: () =>
      import ('vue-awesome-swiper')
      .then(m => m.swiper)
      .catch(),
    swiperSlide: () =>
      import ('vue-awesome-swiper')
      .then(m => m.swiperSlide)
      .catch()
  }
}
</script>
```

And the `yarn build` output:

```
yarn run v1.13.0
$ gridsome build
Gridsome v0.7.7

Initializing plugins...
Load sources - 0.38s
Create GraphQL schema - 1.8s
Create pages and templates - 0.13s
Generate temporary code - 0.04s
Bootstrap finish - 5.38s
Compile assets - 13.41s
Execute GraphQL (191 queries) - 1.28s
Write out page data (191 files) - 0.05s
(node:5114) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (/gridsome-project/node_modules/vue/dist/vue.runtime.common.prod.js:6:24223)
    at /gridsome-project/node_modules/vue/dist/vue.runtime.common.prod.js:6:21188
    at /gridsome-project/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:5114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Render HTML (191 files) - 1.38s
Process files (0 files) - 0s
Process images (9 images) - 1.3s


  Done in 23.38s

✨  Done in 24.36s.
```

The built website

**Comment by clorichel** [comment]
Same TypeError while building with [vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper). Example template:

```vue
<template>
  <LayoutDefault>
    <div class="flex flex-wrap">
      <div class="w-full lg:w-7/12">
        <div class="lg:mx-48">
          <ClientOnly>
            <swiper :options="swiperOption" ref="mySwiper">
              <!-- slides -->
              <swiper-slide>
                slide1
              </swiper-slide>
              <swiper-slide>
                slide2
              </swiper-slide>
              <swiper-slide>
                slide3
              </swiper-slide>
              <div class="swiper-button-prev" slot="button-prev"></div>
              <div class="swiper-button-next" slot="button-next"></div>
              <div class="swiper-pagination"  slot="pagination"></div>
            </swiper>
          </ClientOnly>
        </div>
      </div>
  </LayoutDefault>
</template>

<script>
import LayoutDefault from '~/layouts/Default.vue'

export default {
  data() {
    return {
      swiperOption: {
        pagination: {
          el: '.swiper-pagination',
        },
      }
    }
  },
  components: {
    LayoutDefault,
    swiper: () =>
      import ('vue-awesome-swiper')
      .then(m => m.swiper)
      .catch(),
    swiperSlide: () =>
      import ('vue-awesome-swiper')
      .then(m => m.swiperSlide)
      .catch()
  }
}
</script>
```

And the `yarn build` output:

```
yarn run v1.13.0
$ gridsome build
Gridsome v0.7.7

Initializing plugins...
Load sources - 0.38s
Create GraphQL schema - 1.8s
Create pages and templates - 0.13s
Generate temporary code - 0.04s
Bootstrap finish - 5.38s
Compile assets - 13.41s
Execute GraphQL (191 queries) - 1.28s
Write out page data (191 files) - 0.05s
(node:5114) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (/gridsome-project/node_modules/vue/dist/vue.runtime.common.prod.js:6:24223)
    at /gridsome-project/node_modules/vue/dist/vue.runtime.common.prod.js:6:21188
    at /gridsome-project/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:5114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Render HTML (191 files) - 1.38s
Process files (0 files) - 0s
Process images (9 images) - 1.3s


  Done in 23.38s

✨  Done in 24.36s.
```

The built website is totally fine (no error in console, swiper fully functional). Also, the `yarn develop` command does NOT show that TypeError.

**Comment by renepardon** [comment]
Putting the component into a separate file like suggested by @osama996 worked for my. No longer receive those warnings.

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
