### ISSUE TITLE
Error importing 3rd packages in server.js (possible newbie error)

### ISSUE THREAD

**Issue by luochuanyuewu** [gridsome/gridsome#407]
Here is my code.
![image](https://user-images.githubusercontent.com/9363799/57266990-f9434080-70b0-11e9-9fd3-bfde7883ad27.png)

And i get following error.
![image](https://user-images.githubusercontent.com/9363799/57267016-12e48800-70b1-11e9-85f3-1323b86a7ee5.png)

I am very new to web development. can anybody give me some clue?

**Comment by hjvedvik** [comment]
The `import` syntax isn't supported in Node.js yet. You can import packages with `require` like this:

```js
const Strapi = require('strapi-sdk-javascript')
const strapi = new Strapi('https://localhost:1337')
```

**Comment by luochuanyuewu** [comment]
@hjvedvik  Thanks, problem fixed!
