### ISSUE TITLE
Docker and dist folder

### ISSUE THREAD

**Issue by EtienneR** [gridsome/gridsome#409]
Hello,

I use Docker with Caddy Server for testing building version of my Gridsome application. It's working good excepted when I rebuild the application with the classic command `gridsome build`. Why ? Because the folder **dist** is deleted and re-created. So, Docker doesn't like that because the folder **dist** is a volume with a inode. The only solution is to do rebuilding the container each time the application has been re-building :(.

So my question is can we just remove all files into the **dist** folder instead to delete the folder when building the Gridsome application like an option in `gridsome build` ?

**Comment by hjvedvik** [comment]
Sure, I'll fix that :)
