### ISSUE TITLE
0.6 source-filesystem refs no longer work

### ISSUE THREAD

**Issue by drehimself** [gridsome/gridsome#415]
## Description

Just updated to Gridsome 0.6 and source-filesystem 0.4. I try to do the following just like in the docs: https://gridsome.org/plugins/@gridsome/source-filesystem. Works fine in 0.5.8. 

```
refs: {
  tags: {
    typeName: 'Tag',
    route: 'tag/:id',
    create: true
  }
},
```
I'm getting this error when I run `gridsome develop`:

```
TypeError: Cannot read property 'tags' of undefined
    at FilesystemSource.createNodeRefs (/Users/Dre/code/gridsome-portfolio-starter/node_modules/@gridsome/source-filesystem/index.js:72:36)
    at Promise.all.files.map (/Users/Dre/code/gridsome-portfolio-starter/node_modules/@gridsome/source-filesystem/index.js:64:12)
```

### Steps to reproduce

Here's an example repo: https://github.com/drehimself/gridsome-portfolio-starter. This is still on 0.5.8 and works fine. I'm trying 0.6 locally.

I'm not sure if this was one of the breaking changes in 0.6

Thanks in advance!

**Comment by hjvedvik** [comment]
Looks like a bug in the filesystem plugin. We'll fix it asap.

**Comment by hjvedvik** [comment]
You can update you filesystem plugin and try again now.

**Comment by drehimself** [comment]
Works now! Thanks for the quick update.
