### ISSUE TITLE
:id in template routing switches to kebab case on build

### ISSUE THREAD

**Issue by davidleininger** [gridsome/gridsome#429]
## Description

I'm using Airtable as a database for an app that I'm working on. The ids in Airtable look like this: `fervyBx8lmlG19BoJ`. I'm using `:id` as a param for routing to each piece of content. When I run `gridsome build` it creates the directories in kebab case, like this: `fervy-bx8lml-g19-bo-j`. This breaks all of the routes that are based on the id.

### Steps to reproduce

1. Add a data source with ids that have mixed case.
2. Create dynamic routes based on those ids.
3. Run `gridsome build`
4. Look at dist folder to see kebab case directories

### Expected result

The expected result is that the directories should be the same as the string in the id field, mix case.

### Actual result

The actual result is that directories are named with kebab case and breaking the dynamic routing.

### Environment

<pre><code>
Libs:
- gridsome version: 0.0.6
- @gridsome/cli version: 0.0.9

Browser:
- [ ] Chrome (desktop) version 74.0.3729.157
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Mac
</code></pre>

**Comment by hjvedvik** [comment]
Oh, fields are slugified by default when used in routes. You can append `_raw` to use the original value instead like `/page/:id_raw`. But I think the `id` should be left untouched. Will fix that!
