### ISSUE TITLE
Pagination 404 when developing locally

### ISSUE THREAD

**Issue by cossssmin** [gridsome/gridsome#430]
Updated my starter to Gridsome v0.6.1, and I'm seeing the pagination returns a 404 when developing locally with `gridsome develop`.

However, this only happens locally - `gridsome build` generates the pages properly, and navigation works fine in production, as you can [see](https://gridsome-starter-bleda.netlify.com/).

### Steps to reproduce

You can test it out with the Bleda starter: 

https://github.com/cossssmin/gridsome-starter-bleda

The [Pagination component](https://github.com/cossssmin/gridsome-starter-bleda/blob/master/src/components/Pagination.vue) is used in the [Index page](https://github.com/cossssmin/gridsome-starter-bleda/blob/master/src/pages/Index.vue#L15).

### Expected result

Pagination to work when developing locally.

### Actual result

Trying to access any paginated URL (i.e. `/2/` or `/3/`) returns a 404.

**Comment by robaxelsen** [comment]
@hjvedvik can this be closed, ref your commit :point_up: ?

**Comment by tomtev** [comment]
@robaxelsen I think so :)
