### ISSUE TITLE
Missing slug and date in GraphQL after upgrade to 0.6 version

### ISSUE THREAD

**Issue by mjatharvest** [gridsome/gridsome#433]
Hi folks,

I have been using gridsome's local file system plugins to query data from Markdown files.

In gridsome 5.8 there were a slug and date added to each node automatically (even if they did not exist in yaml frontmatter).

After upgrading to gridsome 0.6 they the slug and date are gone. Is it possible to get them back in GraphQL data?

**Comment by hjvedvik** [comment]
`slug` and `date` is not added automatically in 0.6. The `date` field was just current date if no date was set on the node so it wouldn't make sense to use it. May I ask what your use case is for using `node.slug` in your components?

**Comment by mjatharvest** [comment]
Thanks for reply.

For the slug:
I would use slug on occasion in Vue templates as part of an attribute like a :key :class :id as it was safe in my case to consider the slug a unique identifier.

For the date:
The CMS I'm using builds the date into the filename as in "2019-01-01.article-title-slug.md" - I thought gridsome was parsing the date from the file name but sounds like I was mistaken.

I don't suppose I could access the created or modified date of the file in GraphQL could I?

**Comment by hjvedvik** [comment]
I see. The `slug` wasn't a unique value. So it's probably better to use `id` for keys etc.

And Gridsome didn't parse the date from the filename :) You have access to the filename with GraphQL with `node.fileInfo.name`. So you can try to parse the date in the templates. And you can use the filename for sorting too with `sortBy: "fileInfo__name"` as an argument in the query. But I think we need to add a hook to be able to add fields to nodes right before the schema is generated. It is on our list for 0.7 :)

**Comment by mjatharvest** [comment]
Sounds good!

That hook would be helpful to add things that we just can't get in the markdown file for one reason or another.

When fetching data from an API, looping over the results, and building nodes manually that's easier to do; but it seems like it's not possible with current set up of the file system plugin.

**Comment by robaxelsen** [comment]
Closing, as clarification and fix has been provided. Feel free to reopen or open a new issue if needed.
