### ISSUE TITLE
Context for pages not available during build

### ISSUE THREAD

**Issue by xyNNN** [gridsome/gridsome#434]
## Description

When I try to run `gridsome build` the manually created static pages have no access to the defined "context".

### Steps to reproduce

```
        createPage({
            path: "/Kontakt",
            component: "./src/pages/Contact.vue",
            context: {
                title: "Kontakt",
                content: "Something",
            }
        });
```

```
<template>
    <Layout>
        <div v-html="$context.content"></div>
    </Layout>
</template>

<script>
export default {
    metaInfo() {
        return {
            title: this.$context.title
        };
    }
};
</script>

<style lang="scss" scoped></style>

```
### Expected result

Should render as in the development mode.

### Actual result

Failed to render /kontakt
TypeError: Cannot read property 'content' of null

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.1
- @gridsome/cli version: 0.0.8
 
For Tooling issues:
- Node version: 11.15.0
- Platform:  Mac

**Comment by lasseklein** [comment]
I'm having the same issue in v0.6.3.

Referencing context veriables in the query works fine for develop, but I get the error "fun is not a function" in build.

Passing the context  in gridsome.server.js:
`
 context: {
            chapter: node.chapter
          }
`

The query on the template page:
`<page-query>
  query Requrements ($chapter: String) {
    allRequrements ( filter: { kapittel:{eq: $chapter }} ) {
... `

**Comment by NickStees** [comment]
@hjvedvik I am also having this problem in Gridsome v0.6.6

```
Error: fun is not a function

GraphQL request:130:3
129 | query Grades($school_number: String){
130 |   allGrades (filter: { School_Number: {eq: $school_number }}){
       |   ^
131 |     edges{
```

**Comment by NickStees** [comment]
I just tried Gridsome v0.6.7 and context variables in the query are working for me now. 🍻

**Comment by xyNNN** [comment]
I can confirm the proper behaviour with Gridsome v0.6.7 and it is working for me. So I think we can close this issue. Thanks!
