### ISSUE TITLE
Fixed Components through page changes

### ISSUE THREAD

**Issue by martifenosa** [gridsome/gridsome#439]
I'd love to know if there is, or request this feature if there isn't, a way to keep components loaded through pages.
At the begining I thought the 'Default.vue' layout file wouldn't refresh, but it is doing so. 

For instance, if I want a fixed header and I don't need it to refresh on every page change. 
Is there a way for this? Would the router-link update it's classes? 

Another case, I have a custom cursor follower on a site I'm currently working in, at every page change the cursor returns to it's original position and then goes to the mouse again. I could solve this with some 'patchin' but it wouldn't be the correct way.

**Comment by Ezra-Siton-UIX** [comment]
> For instance, if I want a fixed header and I don't need it to refresh on every page change.
> Is there a way for this? Would the router-link update it's classes?

Yes. Looks her. If you put the `<header/>` component outside of the transition - you get this effect. 
```
<template>
  <div id="main-wrapper">
    <header />
      <transition name="fade" appear>
        <main> <!-- a wrapper for slot is needed -->
          <slot /> <!-- the content -->
        </main>
      </transition>
    <footer />
  </div>
</template>

<style>
.fade-enter-active {
  transition: opacity .5s;
}

.fade-enter {
  opacity: 0;
}
</style>
```
