### ISSUE TITLE
builded static files has no styling

### ISSUE THREAD

**Issue by KrzysztofWelc** [gridsome/gridsome#44]
hello, static files generated with command gridsome build has no styling.

In console i'm getting warnings:
Loading failed for the <script> with source “file:///assets/js/component--home.fe581950910f6e650f25.js”.
and
Loading failed for the <script> with source “file:///assets/js/app.6126d53262e87d386d77.js”.

**Comment by tomtev** [comment]
Hi @ChrisTriesToCode . The built version only runs properly on a web server. But you could use https://www.npmjs.com/package/serve to preview the build locally.
