### ISSUE TITLE
Apollo GraphQL Support

### ISSUE THREAD

**Issue by rykersouthwick** [gridsome/gridsome#441]
## Summary

Ability to use apollo graphql inside gridsome.

_for the record I love to use Apollo paired with Adonis.js
[article](https://scotch.io/tutorials/build-a-graphql-server-with-apollo-server-and-adonisjs)_

### Basic example

You would use gridsome the same way but it will pull data from the apollo graphql server

### Motivation

I think using apollo as an api that static hosted websites can use is the future.

**Comment by robaxelsen** [comment]
Duplicate of #80. @rykersouthwick feel free to re-open if I have misunderstood your request. Otherwise please post any additional details in #80.
