### ISSUE TITLE
Data store API is not working

### ISSUE THREAD

**Issue by kubarazny** [gridsome/gridsome#442]
I'm trying to add basic example from: https://gridsome.org/docs/data-store-api/#basic

but it isn't adding node "customField". Node "title" is visible, but if I remove it from method "addNode" it's still existing in graphql...

**Comment by cfjedimaster** [comment]
I'm using the latest Gridsome and I'm seeing this now. Here is what I'm using:

```

const glob = require('glob');

module.exports = function (api) {
  api.loadSource(async actions => {

    const collection = actions.addCollection({
      typeName: 'Pictures'
    })

    glob('src/images/**/*.*', (err, files) => {
      console.log('in callback');
      files.forEach(f => {
        collection.addNode({
          id:f,
          dir:f,
          booger:'ray'
        });
      });
    });

  })
}
```

And id is stored, `dir` and `booger` (I was desperate) was ignored.

**Comment by noxify** [comment]
@cfjedimaster - i think, it's better to create a new issue instead of commenting to a closed issue :)

**Comment by cfjedimaster** [comment]
Agreed - filed a new issue on this. It's a documentation problem.
