### ISSUE TITLE
All pages get 301 on direct access

### ISSUE THREAD

**Issue by FactorPi** [gridsome/gridsome#444]
## Description

I have published very basic website to old fashion FTP server. The website is accessible at http://www.septictankdisposal.ie

All works as expected and I'm very happy that I have used Gridsome for this project because it's really fantastic tool.
However after doing technical audit to the website I have discovered that all pages are being 301 redirected and this is really bad for SEO. I'm not sure how to resolve this issue and if the issue is caused by my self and the incorrect use of Gridsome.

### Steps to reproduce

When any page is accessed by clicking main menu or any internal link pointing to that page it works fine.
**For example:** when I open the website in browser and on home page and I click in main menu on link contact, it will open url "http://www.septictankdisposal.ie/contact"

But If I try to access directly this page by submitting in browser the same url "http://www.septictankdisposal.ie/contact" I will be 301 redirected to "http://www.septictankdisposal.ie/contact/"

### Expected result

The pages are suppose to have only one accessible url

### Actual result

Pages are accessible on 2 different urls and on direct access all pages response is 301

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.8
- @gridsome/cli version: 0.0.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by hjvedvik** [comment]
The only way to work around it for now is to append a `/` when you use `g-link`. I think we are going to normalize the paths and append a slash automatically in Gridsome v0.7 (when using `g-link`).

```html
<g-link to="/contact/"></g-link>
<g-link :to="`${node.path}/`"></g-link>
```

**Comment by ameistad** [comment]
> But If I try to access directly this page by submitting in browser the same url "http://www.septictankdisposal.ie/contact" I will be 301 redirected to "http://www.septictankdisposal.ie/contact/"

On some servers (for example Apache), trailing slashes indicates that you're looking at a folder. An url without trailing slashes indicates a html file.

Gridsome creates folders with an index.html. When you try to access `http://www.septictankdisposal.ie/contact` your server thinks this points to `contact.html`.

Gridsome doesn't create a `contact.html` but `/contact/index.html`. When your server sees there is a folder named `contact` it automatically appends the trailing slash and sends (301) you to `contact/index.html`

Check out [mod_dir and DirectorySlash](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryslash) on the Apache docs.

**Comment by FactorPi** [comment]
Thanks for all the feedback. At the end I have decided to resolve this issue by adding extra slash to each link on the website as per @hjvedvik suggestion.
I didn't find any reference to this issue so it might be useful to have this information in Gridsome docs.
Keep up the good work.

**Comment by cizza** [comment]
Hi guys, 

I've run into the same issue and added the trailing slash on my g-links. However I think this issue might affect the **@gridsome-sitemap** plugin. The trailing slash is not present in the generated sitemap paths and therefore when submitting the sitemap.xml to google, the redirect issue persists.

**Comment by robaxelsen** [comment]
@cizza thanks for the comment.

@hjvedvik @tomtev: Should we and/or update docs and enchance the sitemap plugin, as suggested? :point_up:

**Comment by hjvedvik** [comment]
@robaxelsen I'll publish a fix for the sitemap plugin later today :)

**Comment by hwmaier** [comment]
@hjvedvik Rather than forcing trailing slashes onto all users, could that be made an option? That way users who operate a web server which can be configured to allow no slashes (for example Apache 2.4 using DirectorySlash/AllowNoSlash) can build sites with no-slash URLs.

**Comment by tyrion** [comment]
The way I am working around this problem is by adding the following at the top of my `gridsome.config.js`:
```javascript
const ContentType = require('gridsome/lib/store/ContentType')
const _wrapped = ContentType.prototype._createPath
ContentType.prototype._createPath = function(node) {
  return _wrapped.call(this, node) + '/'
}
```
This has the advantage that I don't have to manually edit every link and it works for every content type.

**Comment by hjvedvik** [comment]
PR #574 is going to fix this :)

**Comment by sanscheese** [comment]
Closing as #574 is now merged. Feel free to open if still an issue :)
