### ISSUE TITLE
Source request: Sanity plugin

### ISSUE THREAD

**Issue by igregson** [gridsome/gridsome#453]
### Summary 

Source plugin for [Sanity.io](https://www.sanity.io/)

### Basic example: 

Gatsby's: https://www.gatsbyjs.org/packages/gatsby-source-sanity/

**Comment by tomtev** [comment]
This is in development by Sanity team :)

**Comment by WvanDam** [comment]
@tomtev Could you tell us what the timeframe is for this plugin? I'm starting a small project at the end of this month and I'd love to try GridSome in combination with Sanity as headless CMS and Netlify for hosting!

**Comment by mornir** [comment]
The Sanity plugin was shipped in v0.7
https://www.sanity.io/blog/introducing-the-sanity-source-plugin-for-gridsome
https://gridsome.org/plugins/gridsome-source-sanity
