### ISSUE TITLE
Importing Bootstrap 4

### ISSUE THREAD

**Issue by nolfranklin** [gridsome/gridsome#456]
## Description

When importing Bootstrap 4 (node_modules) into main.js, 404 error is thrown. 

```
import 'bootstrap'
import 'bootstrap/dist/css/bootstrap.css'
```

### Expected result

jQuery + Bootrstrap working as intended.

### Actual result

Bootstrap JS works on "gridsome develop" but fails on "gridsome build"

```
Failed to render /404
TypeError: Cannot set property 'emulateTransitionEnd' of undefined
    at setTransitionEndSupport (node_modules/bootstrap/dist/js/bootstrap.js:121:0)
    at assets/js/app.787bb5f8.js:3196:3
    at module.exports.module.exports (node_modules/bootstrap/dist/js/bootstrap.js:7:62)
    at Object.<anonymous> (node_modules/bootstrap/dist/js/bootstrap.js:10:1)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.787bb5f8.js:22984:17)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (node_modules/gridsome/app/main.js:4:9)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (assets/js/app.787bb5f8.js:2348:18)
```

**Comment by LokeCarlsson** [comment]
Not sure what the issue is but I might have some tips you can look into.

https://github.com/LokeCarlsson/gridsome-starter-bootstrap

This is my gridsome starter project with bootstrap + bootstrap vue included. Might be helpsome in some way, other than that all I can think of is if you have tried bootstrap-loader?

**Comment by nolfranklin** [comment]
Thanks, @LokeCarlsson! I was able to get Bootstrap-Vue setup without any issues but was curious if there was a way to load Bootstrap 4 /dist/js into webpack via the main.js file? Haven't taken a go at the boootstrap-loader option yet though - giving that a try now. :)

**Comment by LokeCarlsson** [comment]
Adding it to head via main.js should work yeah 👍

**Comment by plpetkov-tech** [comment]
Hello, I'm having the same issue. I have npm installed jquery popper.js and bootstrap, all works well in gridsome develop but it won't let me build with the message : Could not generate HTML for "/register/":
TypeError: Cannot read property 'jquery' of undefined
    at Object.jQueryDetection (node_modules/bootstrap/dist/js/bootstrap.js:216:0)

Please can you give me a solution for this? I can't find useful info on the internet

**Comment by cameronrr** [comment]
@plpetkov-tech does the docs [here](https://gridsome.org/docs/assets-scripts/#without-ssr-support) about using jquery help? That error sounds like an issue accessing the 'window' in the build (ssr, no window).

**Comment by plpetkov-tech** [comment]
@cameronrr thank you for the quick response. I tried importing it in the layouts in the mounted section but still getting the same error, TypeError: Cannot read property 'jquery' of undefined
    at Object.jQueryDetection (node_modules/bootstrap/dist/js/bootstrap.js:216:0)

It seems like the error is in the bootstrap files installed with npm, it fails here : 
    jQueryDetection: function jQueryDetection() {
      if (typeof $__default['default'] === 'undefined') {
        throw new TypeError('Bootstrap\'s JavaScript requires jQuery. jQuery must be included before Bootstrap\'s JavaScript.');
      }

      var version = $__default['default'].fn.jquery.split(' ')[0].split('.'); <-------

but.. I don't know why and how can I fix it. Is there any way to import jquery globally during the ssr so this bootstrap file has access to $?

**Comment by mikkkeldp** [comment]
> @cameronrr thank you for the quick response. I tried importing it in the layouts in the mounted section but still getting the same error, TypeError: Cannot read property 'jquery' of undefined at Object.jQueryDetection (node_modules/bootstrap/dist/js/bootstrap.js:216:0)
> 
> It seems like the error is in the bootstrap files installed with npm, it fails here : jQueryDetection: function jQueryDetection() { if (typeof $__default['default'] === 'undefined') { throw new TypeError('Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.'); }
> 
> ```
>   var version = $__default['default'].fn.jquery.split(' ')[0].split('.'); <-------
> ```
> 
> but.. I don't know why and how can I fix it. Is there any way to import jquery globally during the ssr so this bootstrap file has access to $?

I have the same problem. Did you ever manage to fix this? @plpetkov-tech

**Comment by plpetkov-tech** [comment]
> > @cameronrr thank you for the quick response. I tried importing it in the layouts in the mounted section but still getting the same error, TypeError: Cannot read property 'jquery' of undefined at Object.jQueryDetection (node_modules/bootstrap/dist/js/bootstrap.js:216:0)
> > 
> > It seems like the error is in the bootstrap files installed with npm, it fails here : jQueryDetection: function jQueryDetection() { if (typeof $__default['default'] === 'undefined') { throw new TypeError('Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.'); }
> > 
> > ```
> >   var version = $__default['default'].fn.jquery.split(' ')[0].split('.'); <-------
> > ```
> > 
> > but.. I don't know why and how can I fix it. Is there any way to import jquery globally during the ssr so this bootstrap file has access to $?
> 
> I have the same problem. Did you ever manage to fix this? @plpetkov-tech 

No, I removed the dependency that gave me the issue and replaced it with something else if I recall correctly
