### ISSUE TITLE
Vue renderState window.__INITIAL_STATE__ question

### ISSUE THREAD

**Issue by cizza** [gridsome/gridsome#462]
Hi guys, 

I'm rather seeking clarification on an issue I have than reporting a bug. I've installed the v0.6.2 version of gridsome and updated my side project. After running the build and testing, the pages are killing the server. My issue lies in the window.__INITIAL_STATE__ script which is injected by VUE in to the renderer html pages, which in my case is very big (the injected script). The site doesn't load at all and just hangs loading (tested on Netlify as well).

Now, reading the blog post on release of Gridsome v0.6 Hans and Tommy state: "From now on, page data will be stored as raw JSON files..." makes me think, if it is really necessary to inject the  window.__INITIAL_STATE__ script in order to turn the site into an SPA? I thought that the meaning of the above is, that the data required will be pulled in by the page from a corresponding json file on demand. 

Could anyone shed some light on this? Btw, I don't even care for the site to be SPA, I just think it's a nice feature. 

Thank you!

**Comment by hjvedvik** [comment]
We have the initial data as `window.__INITIAL_STATE__` to render the current page without needing to fetch the data in another request (to hydrate the DOM faster). The browser should be able to handle it either its fetched or comes from the initial state object. Could it be the reactivity stuff that slows things down? Or did it work in v0.5 with the same amount of data?

I think we can set a max size for the initial state if the data size will be a problem in some cases. Gridsome would just fetch it normally if it doesn't exist.

**Comment by cizza** [comment]
Hi, 

I believe the reactivity is not an issue in this case. The problem is, that stuff doesn't get slow, that stuff simply won't load completely. 

Your question about the v0.5 (0.5.8) - it did work with even more data. The side project is a very simple website (yet with lots of data that I import from DB). The difference I can see in the versions - in the v0.5.8, it did not have the window.__INITIAL_STATE__ in the rendered files. (The pages on development server work without any problem). 

My personal view on this is - if it would be possible to disable the injection it would be a huge win for me. Because in order to make my site work, I have to manually remove the whole script. On each page. After every single build. 

I would even go so far to say, that I would like Gridsome to have the option to switch the SPA functionality off completely. But I guess that is a different topic. 

Thank you.

**Comment by cizza** [comment]
Hello hjvedvik, 

thank you for the fix. I've tested it on my project and I can confirm, there's no problem anymore.  

Thank you! Amazing work.
