### ISSUE TITLE
Markdown to static API

### ISSUE THREAD

**Issue by derevandal** [gridsome/gridsome#463]
Hi, how could I can generate a `.json` file with a list of items that I got from page query?

**Comment by dominiquedutra** [comment]
@derevandal could you please elaborate what you are trying to accomplish?

**Comment by derevandal** [comment]
@dominiquedutra I wanna generate static a way to my api consume my content without parse html.

**Comment by hjvedvik** [comment]
@derevandal You can try to do something like this:

```js
const path = require('path')
const fs = require('fs-extra')

module.exports = function (api) {
  api.createPages(async ({ graphql }) => {
    const { data } = await graphql('query { ... }')
    const filePath = path.join(api.config.outDir, 'filename.json')

    await fs.outputJson(filePath, data)
  })
}
```

**Comment by derevandal** [comment]
It works! Thanks @hjvedvik o/
