### ISSUE TITLE
g-link no longer working for pages?

### ISSUE THREAD

**Issue by SteveEdson** [gridsome/gridsome#464]
## Description

Describe the issue that you're seeing.

Since updating to 0.6.3 (from 0.5.8), my `g-link` elements no longer work for pages (they're still fine for posts).

### Steps to reproduce

```html
<ul class="uk-navbar-nav">
	<li><g-link :to="{ name: 'posts' }" active-class="uk-active">Posts</g-link></li>
	<li><g-link :to="{ name: 'projects' }" active-class="uk-active">Projects</g-link></li>
	<li><g-link :to="{ name: 'about' }" active-class="uk-active">About</g-link></li>
</ul>
```

With the corresponding `Posts.vue`, `Projects.vue` etc files within `src/pages`.

### Expected result

Previously, these links would resolve to `/posts`, `/projects` etc

### Actual result

Now, there is no URL, clicking the link just takes me to a blank page.

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.3

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v8.12.0
- Platform: Mac + Linux

**Comment by hjvedvik** [comment]
This is one of the breaking changes in v0.6. We no longer autogenerate names for pages in `src/pages`. And it's easier to just write `<g-link to="/projects/">Projects</g-link>` :)

**Comment by SteveEdson** [comment]
Fair enough, feels a little messy though. Do pages **have** to use the same url as the filename? Or is there scope for overriding the URL from the page meta etc?

**Comment by hjvedvik** [comment]
Yes, URLs for pages in `src/pages` are generated from the filename. You can read more about it in the [docs](https://gridsome.org/docs/pages#creating-pages). If you need something different, create them [programmatically](https://gridsome.org/docs/pages-api) instead.

**Comment by SteveEdson** [comment]
I might be wrong on this one, but previously if I had some nested folders within pages, could I just reference the generated name, and it would use the path to that file automatically? So if I reorganised that content, the URLs would automatically update?

**Comment by hjvedvik** [comment]
The name was generated from the path. So `/page/one` became `pageOne`. Which means `/page/One.vue` and `/PageOne.vue` would get the same name.

**Comment by SteveEdson** [comment]
Ah right ok, I was thinking you could do something like reference `one` and have it generate the `/page/one` URL.

Thanks for the clarification.
