### ISSUE TITLE
Playground Crash

### ISSUE THREAD

**Issue by martifenosa** [gridsome/gridsome#465]
## Description
Playground, the graphql explore crashes. 

### Steps to reproduce
In my opinion some query got stuck and make it crash. Don't really know what trigger it.

Only the background is visible on the browser.
Console messages:
<img width="394" alt="Screenshot 2019-05-28 at 16 23 36" src="https://user-images.githubusercontent.com/12196520/58485779-f8a84200-8164-11e9-858b-1727f1c04b20.png">

If I access the playground on incognito mode it works as expected. 

Libs:
- gridsome version: 0.6.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15
- Platform:  Mac

**Comment by robaxelsen** [comment]
@martifenosa thanks for reporting this. Could you please also share the code that caused it to crash, at least gridsome.config.js?

**Comment by martifenosa** [comment]
Sure.

I don't have any clue on what was the code that caused it to crash, but my gridsome.config.js is this one:
`module.exports = {
  siteName: "Domestic",
  siteDescription: "Domestic Data Streamers",
  plugins: [
    {
      use: "@gridsome/source-wordpress",
      options: {
        baseUrl: "https://domestic.llos.dev", // required
        apiBase: 'wp-json',
        typeName: "WordPress", // GraphQL schema name (Optional)
        perPage: 100, // How many posts to load from server per request (Optional)
        concurrent: 10, // How many requests to run simultaneously (Optional)
        routes: {
          page: "/:slug",
          works: "/work/:slug" // adds route for "post_tag" post type (Optional)
        }
      }
    },
  ],
  chainWebpack: config => {
    config.module
      .rule("vue")
      .use("vue-svg-inline-loader")
      .loader("vue-svg-inline-loader")
      .options({});
  }
};
`

**Comment by hjvedvik** [comment]
I'm able to reproduce the error if I insert a non-breaking space. And I hade to clear `localStorage` to make it work again. It's a bug with the `graphql-playground` package we use.

**Comment by robaxelsen** [comment]
Closing, as per @hjvedvik findings that this is not an issue with gridsome itself.

@martifenosa Would you be ok reporting this issue to [graphql-playground](https://github.com/prisma/graphql-playground) directly?
