### ISSUE TITLE
Dynamic External Data inside GraphQL data layer

### ISSUE THREAD

**Issue by ryancookio** [gridsome/gridsome#468]
Testing out Gridsome, trying to get my bearings together. I have been able to load an external API into the local GraphQL data layer as per the documentation:

```
const axios = require('axios')

module.exports = function (api) {
  api.loadSource(async store => {
    const { data } = await axios.get('https://api.example.com/posts')

    const contentType = store.addContentType({
      typeName: 'BlogPosts',
      route: '/blog/:year/:slug'
    })

    for (const item of data) {
      contentType.addNode({
        id: item.id,
        title: item.title,
        slug: item.slug,
        date: item.date,
        content: item.content
      })
    }
  })
}
```

However, the data fetched from the endpoint is only fetched **once** per build. That's doesn't seem too useful. Is the expectation to rebuild the site any time the data from an external API changes? I see this functionality is acknowledged on the Fetching API doc page.

As a workaround, I can use Vuex and write something like this inside one of my page components to request the data and have it available for my components.

````
axios.get('https://api.example.com/posts')
  .then((res) => {
  	this.$store.commit('change', res.data)
  	this.apidata = this.$store.getters.change
  })
  .catch((err) => {
    console.log(err);
  })
````

So now I have data I can manipulate in JSON format, but I really want the JSON to be available to me as a GraphQL query so I can use it for templates and whatnot. I thought the Gridsome Wordpress boilerplate might have a solution to this, so I installed it, pulled some data, created a new post on the Wordpress site I was pulling from...and realized that it operates the same way. Any external API you pull into the GraphQL data layer isn't really dynamic. The data is only as fresh as your last build.

Are there any plans to make external data available in `<page-query>` actually dynamic?

**Comment by robaxelsen** [comment]
@ryancookio Thanks for submitting your issue.

Gridsome is a Static Site Generator at it's core, using GraphQL in the build process to pull in the data source and generate the site based on the data and your templates and Vue.js logic. This is by design. You should still be able to use the data as state for your components though, so the main thing you'll be lacking compared to vanilla Vue.js or Nuxt.js is dynamic fetching.

Have a look at our documentation for more information:
[](https://gridsome.org/docs/how-it-works)

**Comment by robaxelsen** [comment]
You can fetch data after load though, which might be what you're looking for. See here:
[](https://gridsome.org/docs/client-side-data/)
