### ISSUE TITLE
Cannot read property 'metaData' of undefined

### ISSUE THREAD

**Issue by chorijan** [gridsome/gridsome#469]
## Description

I'm trying to read the configuration data via GraphQL in the `Default Layout` in order to add dynamic SEO tags (JSON-LD schema and canonical urls) and get undefined errors. 

Also is there a way to get the actual page title here dynamically?

This is my `Default Layout` code:

```
<template>
  <div class="layout site d-flex flex-column h-100">
    <Header/>
    <main id="main" class="flex-shrink-0 site-main" role="main">
      <slot/>
    </main>
    <Footer/>
  </div>
</template>

<page-query>
query {
  metaData {
    siteName
    siteUrl
  }
}
</page-query>

<script>
import Header from '~/components/Header.vue';
import Footer from '~/components/Footer.vue';

export default {
  components: {
    Header,
    Footer
  },
  data() {
    return {
      url: this.$page.metaData.siteUrl + this.$route.path
    };
  },
  metaInfo() {
    return {
      link: [{ rel: 'canonical', href: this.url }],
      script: [
        {
          innerHTML: JSON.stringify({
            '@context': 'http://schema.org',
            '@type': 'WebSite',
            name: this.$page.metaData.siteName,
            url: this.url
          }),
          type: 'application/ld+json'
        }
      ]
    };
  }
};
</script>
```

<img width="598" alt="Screen Shot 2019-05-29 at 10 38 40" src="https://user-images.githubusercontent.com/1315380/58542569-21304a80-81fe-11e9-9ebd-a570dabf3b36.png">

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8

Browser:
- [x] Chrome (desktop) version 74
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [] Firefox version XX
- [] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.5.0
- Platform:  Mac
</code></pre>

**Comment by hjvedvik** [comment]
`page-query` only works in components for pages or templates. You can use `static-query` in the layout component and access the results at `this.$static` :)
