### ISSUE TITLE
<page-query> highlight in Atom

### ISSUE THREAD

**Issue by sergeyfilimonov** [gridsome/gridsome#470]
Is there any way to highlight GraphQL queries within `<page-query>` and `<static-query>` in Atom? It is possible in VS Code with ESLint and Vetur extensions ([described here](https://www.leveluptutorials.com/tutorials/static-vue-with-gridsome/tooling)).

**Comment by snoopdouglas** [comment]
For those arriving here from Google: this is currently possible in VS Code by configuring eg.:

```json
"vetur.grammar.customBlocks": {
  "docs": "md",
  "i18n": "json",
  "page-query": "graphql",
  "static-query": "graphql"
}
```

..and then running the command **Vetur: Generate grammar from \`vetur.grammar.customBlocks\`**

**Comment by zacnomore** [comment]
@sergeyfilimonov It looks like [atom vue](https://github.com/hedefalk/atom-vue) is the most common package for adding syntax highighting for Vue in Atom. So assuming you're using that, it doesn't appear that it supports adding custom grammar in the same way Vetur for VS Code does. I think it would make sense to ask for that feature in their repository.
