### ISSUE TITLE
No way to have optional data in GraphQL queries.

### ISSUE THREAD

**Issue by rylandg** [gridsome/gridsome#471]
## Description

I'm not sure this is a bug or a feature-request. It seems that while a specific <page-query> can have nullable GraphQL fields, if you want to query a source that you've personally defined it does not allow nullable entries.

### Steps to reproduce

Using the `gridsome/gridsome-starter-blog` try and create a post without a cover image. The only way to do so is by rewriting the Page component (and Index etc) to not rely on the `cover_image`.

### Expected result

It should be possible to mark fields as optional or nullable, or just natively support it.

### Actual result

```
Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "cover_image" on type "Post".

GraphQL request (124:5)
123:     content
124:     cover_image (width: 860, blur: 10)
         ^
125:     meta_image (width: 860, blur: 10)
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.2
- @gridsome/cli version: 0.1.1

Browser:
- [X] Chrome (desktop) version 74.0.3729.169
 
For Tooling issues:
- Node version: 12.0
- Platform:  Mac

</code></pre>

**Comment by hjvedvik** [comment]
Gridsome can only generate the schema based on the data you have. We are working on APIs for letting you defined the schema yourself to make sure the `cover_image` always exists. It will be available in v0.7 :)

**Comment by Acidic9** [comment]
Is there any alternative solution we can use in the meantime?

**Comment by u12206050** [comment]
@Acidic9 you can create a Post that contains all the fields, just give it some random name and exclude it from showing up in your site. Better yet is if you have a Post that is actually used that contains all the fields, you just need 1.

Closing this though since it will be fixed in v0.7

**Comment by Acidic9** [comment]
For anyone using Netlify CMS, you can just add a default value of `''` and the field will be there regardless of whether the field has a value.
You should add a default to all non-required fields to be safe.

**Comment by dizid** [comment]
Here is a [plugin](https://germano.dev/fix-netlify-cms-paths-on-gridsome/) that might solve this

**Comment by jltxwesley** [comment]
> @Acidic9 you can create a Post that contains all the fields, just give it some random name and exclude it from showing up in your site. Better yet is if you have a Post that is actually used that contains all the fields, you just need 1.
> 
> Closing this though since it will be fixed in v0.7

Not sure if it's fixed in v0.7? I am still experiencing the same issue?

**Comment by platform-kit** [comment]
@u12206050 would you mind writing out instructions for the method you mentioned? I'm having this issue in the latest release (0.7.13) and it looks like your idea could solve it, but I'm not sure where to begin.

**Comment by u12206050** [comment]
@platform-kit  It is best to just define the schema if you have this issue, here is how you would do that:
[schema-api](https://gridsome.org/docs/schema-api/)
