### ISSUE TITLE
Suggest matching commands if the user makes a typo

### ISSUE THREAD

**Issue by jamesgeorge007** [gridsome/gridsome#476]
## Summary

Suggest matching commands if the user mistypes.

### Basic example

`gridsome serv` results in the following prompt:-
```md
Did you mean serve?
```

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?
As per what I think it is a worth feature to be included in the next release.

**Comment by jamesgeorge007** [comment]
@hjvedvik Shall I go ahead and shoot up a PR :thinking:

**Comment by robaxelsen** [comment]
Sounds good to me, and I'd love it if you submitted a PR. @hjvedvik: feel free to interject/comment.
