### ISSUE TITLE
How to change default VueRouter settings

### ISSUE THREAD

**Issue by calebanthony** [gridsome/gridsome#478]
I know in `main.js` you can utilize the Client API to add router methods, but how would I set a router setting?

In my specific use case, I want to globally set the [active class](https://router.vuejs.org/api/#linkactiveclass) rather than having to set it on each `<g-link>` in my code.

I tried:
```js
export default function (Vue, { router, head, isClient }) {
  router.linkActiveClass = 'is-active';
}
```
but that doesn't work.

**Comment by hjvedvik** [comment]
You should be able to use `router.options.linkActiveClass = 'is-active'` in latest version to set a default active link class :)
