### ISSUE TITLE
Loading external JS 

### ISSUE THREAD

**Issue by abhishektiwari** [gridsome/gridsome#48]
Hello, I am trying to migrate my Ghost theme to Gridsome and it has some theme specific JS file which I would like to include. I assume one has to use webpack loader but not sure how. Any hints will be much appreciated.

**Comment by abhishektiwari** [comment]
I tried a few things but ended up with the following hack which works perfectly

1. Add external JS files in `/static/assets/js`
2. In component script used `mounted` to `createElement("script")`
```
export default {
  mounted: function() {
    var scriptTagTheme = document.createElement("script")
    scriptTagTheme.src = "/assets/js/theme.min.js"
    document.getElementsByTagName('head')[0].appendChild(scriptTagTheme)
    var scriptTagJQ = document.createElement("script")
    scriptTagJQ.src = "/assets/js/jquery-3.3.1.slim.min.js"
    document.getElementsByTagName('head')[0].appendChild(scriptTagJQ)
  }
}
```
3. Any jQuery should be executed after `updated` 
```
  updated: function() {
		jQuery("selector").each(function() {
			// Do something here
		});
  }
```

**Comment by renepardon** [comment]
Sorry for commenting on an old issue but i've tried the head.script.push method and receive a lot of different errors (randomly). Weird thing is: sometimes it works, sometimes not:

```javascript
if (isClient) {
    require('cookieconsent')

    head.script.push({ src: 'https://code.jquery.com/jquery-3.4.1.min.js' })
    head.script.push({ src: 'https://code.jquery.com/ui/1.12.1/jquery-ui.min.js' })

    /*head.script.push({ src: '/assets/js/jquery.js' })*/
    head.script.push({ src: '/assets/js/plugins.js', body: true })
    head.script.push({ src: '/assets/js/jquery.layerslider.js', body: true })
    head.script.push({ src: '/assets/js/custom.js', body: true })
  }
```

Something which is displayed within a  "dev" build but not on production: 

```
GET http://localhost:8081/manifest.json 404 (Not Found)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
```

If i first load the page, everything seems to work properly but as soon as i navigate, nothing works anymore. So the jQuery thing will just stop doing it's thing.

**Comment by WebShapedBiz** [comment]
@renepardon same here. The biggest issue in my case is with `jquery.` Sometimes it's loaded as it should but most of the time I'm getting an error in the console saying `Bootstrap's JavaScript requires jQuery`. The reason why it's working fine one day and not working the other is beyond me.
BTW, I'm loading jquery in `<head>` and all other scripts before `</body>`

**Comment by renepardon** [comment]
@WebShapedBiz I got it working with a setTimeout of ~200ms before executing jQuery stuff within created Hook. See at: https://www.acv-container.de

**Comment by WebShapedBiz** [comment]
Thank you @renepardon for your time and effort, but I'm not sure how to apply it on external scripts.

**Comment by renepardon** [comment]
@WebShapedBiz 

In my gridsome.client.js:

```javascript
export default function (Vue, options, {router, head, isClient, appOptions}) {
  // theme.bundle.js is a combined file generated with webpack.
  head.script.push({src: '/assets/js/theme.bundle.js', body: true})
}
```

In my main.js file 
```javascript
// Here i set an interval to check every 50ms if my jQuery spaghetti code is already loaded and if so, unset the timer and call the page related method to initialize the corresponding plugins (e.g. navigation, dropdowns, tabs etc)
router.afterEach((to, from) => {
    if (isClient) {
      var interval = setInterval(function () {
        if (typeof initThemePlugins !== 'undefined') {
          // initThemePlugins call's just the usual jQuery spaghetti code 
          initThemePlugins()
          clearInterval(interval)
        }
      }, 50)

    }
  })

```

Hope it help you. It's just a dirty workaround but it's doing it's job :P

**Comment by WebShapedBiz** [comment]
Thank you so much @renepardon

**Comment by dcruz1990** [comment]
Sorry for replying here, im trying to import webflow JS but i get this:

`Uncaught SyntaxError: Unexpected token '<'` 
 
Is there a way to specify injected scripts to load only in client side?.
