### ISSUE TITLE
No polyfill for `Promise`

### ISSUE THREAD

**Issue by ocboogie** [gridsome/gridsome#480]
## Description

I was porting a Vue cli 3 app to gridsome, everything was going good, then I tested it on IE 11. That's when I got the classic `'Promise' is undefined`, so I thought something went wrong when porting. Later I tested it on a brand new gridsome site using `gridsome create`, and got the same error.

### Steps to reproduce

Here is the project I'm porting
https://github.com/ocboogie/ror2-unlocks
But you don't need that.
```
gridsome create no-promise
cd no-promise
yarn build
npx serve dist
```
Open in IE

I've also tried updating to gridsome `0.6.3`

### Expected result

`Promise` gets a polyfill

### Actual result

`Prmise` is undefined

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.3
- @gridsome/cli version: v0.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version any
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.15.3
- Platform: WSL but that shouldn't change anything

Others:

</code></pre>

**Comment by ocboogie** [comment]
I've even tried adding something like `console.log(Promise)` to `main.js` to make sure that babel knows that I'm using `Promise`s. But this shouldn't even matter sense `@vue/babel-preset-app` has `Promise`s as a default polyfill.
https://github.com/vuejs/vue-cli/blob/next-major/packages/%40vue/babel-preset-app/index.js#L8

**Comment by cizza** [comment]
In my case I did install the es6-promise polyfill manually and imported it in the main.js file. I would recommend to try that if you need a quick solution.

**Comment by ocboogie** [comment]
Yeah, that's what I've done, but using [promise-polyfill](https://www.npmjs.com/package/promise-polyfill). Not sure which is better though.

**Comment by hjvedvik** [comment]
Does it work better in v0.6.4?

**Comment by ocboogie** [comment]
Works great, thanks. But I am getting `Object doesn't support property or method 'closest'` from [here](https://github.com/gridsome/gridsome/blob/f79f89aea9727aaf34288b727ce395d5703ad067/gridsome/app/entry.client.js#L18). I got this before the update too. My app has no route change, so I think it should still work fine. I can submit another issue for that if you want.

**Comment by mjatharvest** [comment]
For those with the same 'closest' bug here was how I resolved the issue.


```
//in src/main.js

 /*
  * For error: Object does not suppor property or method 'closest'
  *
  * https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
  */
if(typeof Element !== "undefined") {

 if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
  }

  if (!Element.prototype.closest) {
    Element.prototype.closest = function(s) {
      var el = this;

      do {
        if (el.matches(s)) return el;
        el = el.parentElement || el.parentNode;
      } while (el !== null && el.nodeType === 1);
      return null;
    };
  }

}
```

**Comment by hjvedvik** [comment]
@mjatharvest Does it work okay in IE11 with those polyfills? I'm going to add them to Gridsome in the next update.

**Comment by mjatharvest** [comment]
@hjvedvik Yes, I resolved IE 11 errors by adding the closest polyfill mentioned above, and I also had to manually add the following packages: isomorphic-fetch, es6-promise

`yarn add isomorphic-fetch es6-promise`

```
// in src/main.js

/*
 * For fetch and Promises not natively supported in IE 11
 */
import 'isomorphic-fetch'
```

There may have been a much better way to do this using chainWebpack in gridsome config, babel, or browsersList but those other ways are beyond my skill :)

**Comment by hjvedvik** [comment]
Great! I'm also switching to `XMLHttpRequest` instead of `fetch` in the production build. The `Promise` polyfill should be added by Babel in Gridsome v0.6.4 I hope :)

**Comment by ngoclx** [comment]
@hjvedvik how about gridome v0.7.20? My axios is not working on ie11.
