### ISSUE TITLE
Querying data using query result as an argument

### ISSUE THREAD

**Issue by FistMeNaruto** [gridsome/gridsome#487]
Hi!

I'm trying to build a blog using Foresty as my CMS. Currently I have two folders - `Posts` and `Authors` which contain the data in .md files and I'm using `source-filesystem` to get the data into GraphQL.

Posts content:
```
"data": {
    "allPost": {
      "edges": [
        {
          "node": {
            "title": "Post title",
            "author": "authors/author-name.md"
          }
        },
        {
          "node": {
            "title": "Post title 2",
            "author": "authors/author-name-2.md"
          }
        }
      ]
    }
  }
}
```

Authors content:
```
  "data": {
    "allAuthor": {
      "edges": [
        {
          "node": {
            "title": "Author name",
            "path": "/authors/author-name"
          },
          {
          "node": {
            "title": "Author name 2",
            "path": "/authors/author-name-2"
          }
        }
      ]
    }
  }
}
```

Is there a way to construct the query to get the author data according to the path specified in post author field?

Ideally I'd like my post data to look something like this:

```
"node": {
  "title": "Post title 2",
  "author": "authors/author-name-2.md",
  "authorData": {
    "title": "Author name 2",
    "path": "/authors/author-name-2"
  }
}
```

I have tried figuring out how `belongsTo` and `... on` works, but I'm not sure if it's applicable in this case. Another issue here would be Forestry saving reference paths to other documents with file extensions and without a preceding slash, but I think this could be fixed in `gridsome.server.js`

Thanks!

**Comment by hjvedvik** [comment]
It's currently only possible to reference with an ID, unfortunately.. But we are working on a way to do this for v0.7 :)

**Comment by FistMeNaruto** [comment]
Roger, waiting for updates :)

**Comment by mgd722** [comment]
@hjvedvik Do you know if this ever made it into v0.7?
