### ISSUE TITLE
Pages for refs not created when sharing path with nodes

### ISSUE THREAD

**Issue by subdiff** [gridsome/gridsome#492]
## Description

When setting up a blog creation of tag pages fails when sharing part of the path with the blog posts.

### Steps to reproduce
Have this kind of source filesystem description for creating blog posts with tags:
```
{
  use: '@gridsome/source-filesystem',
  options: {
    path: 'blog/**/*.md',
    typeName: 'BlogPost',
    route: '/blog/:year/:slug',
    refs: {
      tags: {
        typeName: 'BlogTag',
        route: '/blog/tags/:id',
        create: true
      }
    }
  }
}
```
### Expected result

Blog tag page can be visited at: `www.example.com/blog/tags/my-tag`

### Actual result
With `gridsome develop` tag pages can't be visited. `gridsome build` fails with error message:
```
Failed to render /blog/tags/xorg
TypeError: Cannot read property 'cover_image' of undefined
    at a.render (src/templates/BlogPost.vue?f778:1:244)
    at a.t._render (/home/roman/dev/website/org.subdiff/gridsome/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:70663
    at Yi (/home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:67227)
    at io (/home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:70639)
    at ro (/home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:70270)
    at eo (/home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:67517)
    at /home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:71126
    at Yi (/home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:67227)
    at /home/roman/dev/website/org.subdiff/gridsome/node_modules/vue-server-renderer/build.prod.js:1:71110
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.4
- @gridsome/cli version: 0.2.0

Browser:
- [x] Chrome (desktop)
 
For Tooling issues:
- Node version: 8.10.0
- Platform: Linux

</code></pre>

**Comment by hjvedvik** [comment]
Try having `/blog/:year(\\d+)/:slug` as route for the `BlogPost` type. It should make it match only if `year` is a number :)

**Comment by subdiff** [comment]
Thanks, I assume the proposed solution in #493 is therefore not correct?

I have to say though that checking on the type seems like a workaround. There might be situations where one has just same types and still want to routes nodes on the same sub-path as a static address of a "ref".

**Comment by hjvedvik** [comment]
The change in #493 works for you because each post and tag will get a static route instead. When they are dynamic, the `/blog/:year/:slug` route will also match for paths like `/blog/tags/1`. I don't think param types are a workaround but rather a way to help Vue Router match the correct route.

But we are going to let you decide if you want dynamic or static routes in `gridsome.config.js` sometime soon. Static routes result in more routes, but will not have matching issues :)

**Comment by subdiff** [comment]
> The change in #493 works for you because each post and tag will get a static route instead. When they are dynamic, the /blog/:year/:slug route will also match for paths like /blog/tags/1. I don't think param types are a workaround but rather a way to help Vue Router match the correct route.

Hmm, yea makes sense. I'll close this issue and the pull request. Thank you for explanation!
