### ISSUE TITLE
Missing license for @gridsome/cli package on npm

### ISSUE THREAD

**Issue by tvthatsme** [gridsome/gridsome#507]
## Description

The license of a package is important within some companies before being able to get approval for use.

### Steps to reproduce

Go to the [package listing on npm](https://www.npmjs.com/package/@gridsome/cli)

Observe that the license field shows "none"

### Expected result

Because the GitHub repo has a MIT license file, I'd expect that the NPM listing would be the same.

**Comment by hjvedvik** [comment]
Thanks for noticing. We'll fix that :)
