### ISSUE TITLE
Ability to bind gridsome develop to a specific host

### ISSUE THREAD

**Issue by ryancookio** [gridsome/gridsome#508]
Gatsby allows you to bind development server to any IP with the -H option. For example:

`gatsby develop -H 0.0.0.0`

Could a similar option be created for Gridsome?

This is useful for testing your development site on a physical mobile device. Additionally, it would also allow Gridsome to take advantage of instant previews on Forestry.io.

**Comment by dominiquedutra** [comment]
Hey
What I do when I need to preview the built website (using mobile, iPad, another windows computer) on the local network is using http-server, which can simply be installed  and then used like so:

`gridsome build && http-server ./dist`

Binding to external IP if you need that would be done on your local network device/router.
As for forestry.io previews I am unaware of how it works, but it should work with http-server.

Hope it helps while we don't have this out of the box.

IMO, serving http with node is so easy that I don't really think much effort should be put into implementing this over other features that are queued.

**Comment by ameistad** [comment]
The -h (lowercase h) flag will let you set a custom host.

```sh
gridsome develop -h 0.0.0.0
Site running at:          http://0.0.0.0:8080/
Explore GraphQL data at:  http://0.0.0.0:8080/___explore
```
