### ISSUE TITLE
Source request: NetlifyCMS plugin

### ISSUE THREAD

**Issue by Devportobello** [gridsome/gridsome#51]
Hi,

I'd like to add a support to integrate netlifycms as a source for gridsome, but i'm facing some problem,
Following netlifycms doc : [Add to your site](https://www.netlifycms.org/docs/add-to-your-site/)

How can i inject with plugin a new page (from router) with required basic html and on other page add the Netlify Identity Widget ?

So we need to populate a new folder eg: 'admin/' with
- index.html
- config.yml

Example of GatsbyJS : [Gatsbyjs plugin netlifycms](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms)

**Comment by mittalyashu** [comment]
Have you considered asking this question in the [Gridsome discord community](https://discord.gg/7znJUkH)?

**Comment by kaceo** [comment]
I think the NetlifyCMS admin files are meant to be included verbatim into the /admin path.  So probably a strategy is to place them inside /public/admin and let the build process combine them with Gridsome.

**Comment by hacknug** [comment]
That's correct according to the Netlify CMS Docs: https://www.netlifycms.org/docs/add-to-your-site/#app-file-structure

**Comment by Devportobello** [comment]
Steps:

1. The build process and develop process need to create an admin folder, populate 2 files (index.html and config.yml) depending of the plugin's config

2. add the Netlify Identity Widget on all page

**Comment by Devportobello** [comment]
Close as plugin exists

https://github.com/gethypervisual/gridsome-plugin-netlify-cms
