### ISSUE TITLE
Gridsome package plugin-facebook-pixel

### ISSUE THREAD

**Issue by nuriaheep** [gridsome/gridsome#510]
## Summary

It would be very nice a plugin to add the facebook pixel in the sites.

I have a client that asks to include the facebook pixel code, but in the packages of gridsome it doesn't exist yet, I tried to make the plugin but I don't know enough to create one. I tried to refactor the google-analytics one but I coudn't advance much

**Comment by dominiquedutra** [comment]
@nuriaheep 

Just use Google Tag Manager + Gridsome Google Tag Manager plugin to deploy anything you like, facebook pixel included. You can do so much with GTM.

Hope it helps.

**Comment by dominiquedutra** [comment]
@nuriaheep I`ll close this.
If you really think of a reason why not to use GTM and why this should be implemented, please ping me so I can reopen.

**Comment by Rocketpilot** [comment]
There's not really a lot of end-to-end documentation on how to configure any of this. Like, the GTM plugin suggests consulting the Vue Google Tag Manager docs for help but Gridsome has a few idiomatic ways of doing things. It would be nice to have some more of this advice spelled out.
