### ISSUE TITLE
Can't seem to query - TypeError: undefined

### ISSUE THREAD

**Issue by cartoonmadrasah** [gridsome/gridsome#513]
I have been scratching my head for the whole day. I can't seem to figure this out. I don't know what mistake I am doing. Any help or guidance would be appreciated. Thank you.

![Image 1](https://user-images.githubusercontent.com/7679807/59881975-6a715580-93ca-11e9-9ea9-9673cc3c20e0.png)

**Comment by hjvedvik** [comment]
It might be something wrong with the JSON data. Since Axios or `JSON.parse()` isn't able to parse it. So the `data` variable in the screenshot is a string.
