### ISSUE TITLE
Markdown not transformed in rss feed plugins

### ISSUE THREAD

**Issue by subdiff** [gridsome/gridsome#514]
## Description

Using any of the available rss plugins [1][2] I am not able to include Markdown content such that it is converted to html. But the respective `node.content` entries on my BlogPost types are in html format when I query them in the playground.

Could it be that this is because the plugins use the hook `beforeBuild` and `afterBuild` when the build has already been finished / not yet started and the transformer is not yet/anymore available here?

[1] https://github.com/onecrayon/gridsome-plugin-feed
[2] https://github.com/darthmeme/gridsome-plugin-rss

**Comment by subdiff** [comment]
Live version: https://subdiff.org/blog/feed.xml
Website repo: https://gitlab.com/romangg/gridsome-org.subdiff

**Comment by hjvedvik** [comment]
The plugins are getting the nodes directly from the store, while the HTML transformation actually happens in the GraphQL layer. We'll try to provide APIs for them to get the nodes through GraphQL instead in one of the next versions.

**Comment by hjvedvik** [comment]
I've been thinking about this... It might be difficult for those plugins to get transformed node fields unless they change their options. They would either generate GraphQL queries or let developers write them manually. For now, I would recommend using the [`marked`](https://www.npmjs.com/package/marked) package to transform the markdown like this:

```js
const marked = require('marked')
...
nodeToFeedItem: node => ({
  title: node.title,
  date: node.fields.date,
  content: marked(node.content)
})
```

It won't include all the Remark plugins etc, but you will at least have HTML instead of markdown :)

**Comment by subdiff** [comment]
Thank you. I tried out using the marked package and this indeed is a nice workaround. Closing the issue now since most people will probably be happy with this solution for markdown-to-html-transformation for their rss feeds.

**Comment by RehanSaeed** [comment]
Is there a way to get the full HTML with all remark plugins I've configured in Gridsome?

**Comment by BobWalsh** [comment]
+1

**Comment by freaktechnik** [comment]
The workaround fails whenever the markdown files reference a file like an image or other attachment that will be bundled with gridsome by remark.
