### ISSUE TITLE
Default curl command returning errors from graphql

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#518]
## Description

The default curl command provided by the explorer is not working for me.

### Steps to reproduce

1. Go to the explorer, make a query (like a query to list all pages).

```
query {
  allPage {
    path
  }
}
```

2. Run it, see that everything works fine
3. Copy the curl command
4. Run it from the commandline

```
curl 'http://0.0.0.0:8080/___graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://0.0.0.0:8080' --data-binary '{"query":"query {\n  allPage {\n    path\n  }\n}"}' --compressed
```

### Expected result

A 200 status and a non-erroring json response

### Actual result

Error returned

```
{"errors":[{"message":"Cannot destructure property `__path` of 'undefined' or 'null'.","stringified":"TypeError: Cannot destructure property `__path` of 'undefined' or 'null'."}]}
```

### Environment

```
Libs:
- gridsome: 0.6.4

Tools
- curl: 7.58.0
```

Side note: Is there an easy way to query graphql directly from javascript?  (i.e., some nice function that performs the fetch etc, given a query?)

**Comment by u12206050** [comment]
Have you tried :
```
allPage { edges { node { path } } }
```

**Comment by hjvedvik** [comment]
I'll fix this :)

Gridsome only has a [`this.$fetch('/page-path')`](https://gridsome.org/docs/client-api#fetchpath) method which will run the query for a specific page because fetching data from the GraphQL server wouldn't work in production. But you can use Axios or just `fetch` with a query string in the body to retrieve data from other GraphQL servers.

**Comment by cco3** [comment]
@u12206050 the query shouldn't be an issue, it works in the explorer.

@hjvedvik , right, just given the errors I'm encountering, it's not clear if special headers etc are needed with the fetch, so having a simple wrapper would be nice.  I'll check out axios.
