### ISSUE TITLE
Can't click links in production

### ISSUE THREAD

**Issue by gabrielkoerich** [gridsome/gridsome#520]
## Description

Hi there! I'm having problems with internal links. Everything works fine in dev, but running `gridsome build` some links doesn't open. The URL changes, but the page won't load.

I saw some stuff here in github about Vue hydration and wrong or incomplete tags but I can't get it to work.

I already tried to remove g-image component, tried using href and to, tried to validate it on w3c but the only error is having a div inside ul/li, and I already tried to remove those and still pages didn't load... Not sure what to try anymore. 

I'm using boostrap-vue in the navbar, maybe it has something to do with it?

### Steps to reproduce

Go to https://develop.bulldesk.com.br/ and click on "Planos".

### Expected result

Load the page.

### Actual result

Page won't load.

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.3
- @gridsome/cli version: 0.1.1

Browser:
- [x] Chrome (desktop) version 73.0.3683.86
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 12.1.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.2  
- Platform:  Mac and Linux

Others:

</code></pre>

**Comment by hjvedvik** [comment]
Do you have any HTML minification enabled on the host? It looks like some HTML comments have been removed from the markup. You can also try to build the site in [development mode](https://gridsome.org/docs/troubleshooting#debugging-hydration-errors) and see if you get any meaningful errors.

Nice site btw :)

**Comment by gabrielkoerich** [comment]
@hjvedvik All good now!

It was an issue with Cloudflare minification + a tbody missing in some tables. Thanks for pointing me in the right direction.
