### ISSUE TITLE
Cannot read property 'toISOString' of null 

### ISSUE THREAD

**Issue by u12206050** [gridsome/gridsome#525]
## Description

When having date fields that could be set or be null graphql silently fails causing page-query result to be null. 

### Steps to reproduce

Declare a content type eg. `Post` with at least two objects containing a field that would be a date, except in the one object set the value of the `date` field to null. Query for `allPost` with the `date` field. You'll see error from graphql.

### Expected result

If the field is null it should just return null instead of trying to convert to date and transforming it.

### Actual result

```
"message": "Cannot read property 'toISOString' of null",
      "stringified": "Cannot read property 'toISOString' of null
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.4
- @gridsome/cli version: 0.6.4
</code></pre>

**Comment by martifenosa** [comment]
If I'm not mistaken this https://github.com/gridsome/gridsome/pull/509 will offer a solution.

**Comment by u12206050** [comment]
@martifenosa thanks for the tip, however I can't seem to get the resolver to work as it does by default if the date value does indeed exist. I found the file in Gridsome `gridsome/lib/graphql/types/date.js` which I am trying to update to see if it helps.

**Comment by martifenosa** [comment]
We had the same issue in our projects, we use the wordpress-source plugin and when a acf field is requested it is a must that it exists with content **in at least one of the pages** (it doesn't matter if you call another page that has empty fields if at least one has it filled).  So our "fix" is creating a fake page where all the fields have fake content while waiting for the https://github.com/gridsome/gridsome/pull/509 to be merged. 

Im not sure thought that we are having the same exact issue. What source are you using for the content? 

Another possible solution could be to set up a fake date in the default date field and create a custom field for the date you need inside the post (if I'm not mistaken this wouldn't pass through the 'stringified' so it should't crash).

**Comment by u12206050** [comment]
I understand what the issue is, it isn't really the same as yours, since in our case the field always does exist, it is just that the value could be either a valid `date` or `null`.

I will be making a PR once I have built the site on production to make sure it works.

**Comment by u12206050** [comment]
#527
