### ISSUE TITLE
Markdown file as index.html (Startpage)

### ISSUE THREAD

**Issue by BenRoe** [gridsome/gridsome#531]
Hello,
i have some md files in the docs folder.
How can i show the README.md file in the docs folder as the homepage?
If i use `route: '/',` i get the error `DocPage > Failed to add node: Duplicate key for property path: /`

```
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        index: ['README'],
        path: 'docs/**/*.md',
        typeName: 'DocPage',
       route: '/'
      }
    },
  ],
```

Motivation: The home page content should be readable via GitHub.

**Comment by hjvedvik** [comment]
Hi :) You need to remove the `route` option. Then set `baseDir: './docs'` and `path: '**/*.md'` to make the `docs/README.md` your homepage. And also make sure you don't have a `src/pages/Index.vue` page.
