### ISSUE TITLE
Fetch fails if Content-Type is missing

### ISSUE THREAD

**Issue by dweldon** [gridsome/gridsome#534]
## Description

If the Content-Type response header is missing from a `.json` file (if the web host doesn't add it for some reason), then page transitions where data is needed will fail.

### Steps to reproduce

This is a bit tricky because you'd have to create a host which doesn't add Content-Type headers...

### Expected result

The route transition should happen anyway.

### Actual result

Exception is thrown: `Resource at ${jsonPath} is not JSON`

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.5
- @gridsome/cli version: 0.2.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
</code></pre>

### Other notes

I was able to get this working in production by removing this from `app/fetch.js`:

```js
if (contentType && /application\/json/.test(contentType)) {
}
```

Is this check really necessary? What if we throw an exception only if the JSON doesn't parse?

**Comment by brandonpittman** [comment]
This bit me today. Wasted an hour on it. Rolled back to 0.6.4 and the issue seemed to go away.

**Comment by hjvedvik** [comment]
@brandonpittman Sorry for that... Just publish a new version on npm (v0.6.6) that should fix it.

**Comment by dweldon** [comment]
Awesome. Thanks for the fast response @hjvedvik.

**Comment by brandonpittman** [comment]
@dweldon @hjvedvik Thanks for the fix. Glad to know I wasn't just crazy. 😀 Worked on the staging server but not the production server.
