### ISSUE TITLE
content filtering based on today's date and published date frontmatter (draft content)

### ISSUE THREAD

**Issue by rumansaleem** [gridsome/gridsome#536]
Is there some configuration available, to draft the content based on published date used as frontmatter?

By drafting content, I mean that the content is not visible on production build until marked published, while everything is visible in development mode.

I know that we can use a boolean `published` variable to filter content. But, just curious to know if there is some other way to publish content based on date variable and today's date.

I couldn't figure out how to avoid filtering in development mode.

**Comment by hjvedvik** [comment]
We've been working on a few new API hooks which will let you do that. It will work like this:
```js
api.onCreateNode(node => {
  if (node.internal.typeName === 'Post' && node.published !== true) {
    return null // do not add this node to the store
  }
  // modify node or return a new node
})
```
We'll try to publish it next week if everything goes well :)

**Comment by rumansaleem** [comment]
Yeah! this seems a powerful one. How about also accepting node type as a parameter?

```js
api.onCreateNode('Post', node => {
   if(node.published !== true) {
         return true
    }
    return node;
});
```

**Comment by khrome83** [comment]
@hjvedvik - any chance you can let me know when this is live? This is the big thing preventing me from publishing drafts to my blog right now. I write them elsewhere then past them in when they want to go live. 

I found I can prevent graphql from pulling pages based on dates, but I can't prevent the tags that are created from pulling those same pages. So basically they still get made...

**Comment by hjvedvik** [comment]
@khrome83 Sure :)

As a workaround, for now, you can get the content type and remove the node in the `loadSource` hook. `loadSource` in your `gridsome.server.js` file will be executed after plugins so the content type should exist.

```js
api.loadSource(store => {
  const posts = store.getContentType('Post')

  posts.data().forEach(node => {
    if (node.published !== true) {
      posts.removeNode(node.id) // must remove by node id
    }
  })
})
```

**Comment by khrome83** [comment]
@hjvedvik you saved me so many hours I already spent lost on this. Thank you very much.

**Comment by khrome83** [comment]
This worked great. I made one small change for anyone reading this - 

```js
api.loadSource(store => {
  if (process.env.NODE_ENV === "production") {
    const posts = store.getContentType('Post')

    posts.data().forEach(node => {
      if (node.published !== true) {
        posts.removeNode(node.id) // must remove by node id
      }
    }
  }
```
I wanted to see drafts locally. This way only my deployment server which I set `NODE_ENV` in build lambda too "production".
