### ISSUE TITLE
 TypeError: Cannot destructure property collection of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by cartoonmadrasah** [gridsome/gridsome#538]
![Image 1](https://user-images.githubusercontent.com/7679807/60800435-a3614680-a18e-11e9-9e8e-c857ec10b31d.png)

**Added Paginate data to the page and getting this error, kindly help. I am using Gridsome 0.6.6:**

The code is running fine with Gridsome Develop but throws this error during build:

TypeError: Cannot destructure property collection of 'undefined' or 'null'. at calcTotalPages (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\gridsome\lib\pages\createRenderQueue.js:26:32) at createRenderQueue (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\gridsome\lib\pages\createRenderQueue.js:11:26) at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:16) at AsyncSeriesWaterfallHook.lazyCompileHook (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\tapable\lib\Hook.js:154:20) at Promise (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\gridsome\lib\build.js:51:34) at new Promise (<anonymous>) at createRenderQueue (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\gridsome\lib\build.js:50:10) at module.exports (E:\TCA\Clients\PRE Dubai\predubai.com\node_modules\gridsome\lib\build.js:23:23)

**Comment by hjvedvik** [comment]
I think your content type name `predubai` is causing problems for you. There is currently a limitation/bug in the query parser that makes `@paginate` only work when the type name starts with an uppercase letter. It will be greatly improved in the next version of Gridsome. But for now, you can rename your type name to `Predubai`.

**Comment by cartoonmadrasah** [comment]
Yes, working fine now with the uppercase change. Thank you so much.
