### ISSUE TITLE
Question - Is there an advantage to using the file system instead of an API for data

### ISSUE THREAD

**Issue by mjatharvest** [gridsome/gridsome#540]
Is there a key benefit (speed or otherwise) to fetching data from the local file system using a source plugin vs getting data from an API using gridsome.server.js?

https://gridsome.org/docs/fetching-data

**Comment by brandonpittman** [comment]
That's all the source plugins do under the hood.

**Comment by dominiquedutra** [comment]
@mjatharvest don't think so.
I am running a customized version of source-wordpress hacked and copied `pasted on gridsome.server.js. It does the same in the same amount of time basically.

Don't think it would be any different on the local file system scenario.

**Comment by mjatharvest** [comment]
sounds good, thank you all
