### ISSUE TITLE
Named routes for Gridsome

### ISSUE THREAD

**Issue by krstic-duci** [gridsome/gridsome#542]
## Description

For every page inside _src/pages/_  I specifically added the **name** (please see the image No.1) property with the names I would like to call my pages inside the website. But after inspecting the **.temp/routes.js** I could only see the following (please see the image No.2), only `Index.vue` and `404.vue` has **name** property.

Image No.1
![pages file](https://user-images.githubusercontent.com/22850096/60960560-95383500-a30a-11e9-90a3-cffdc9773d7b.png)

Image No.2
![routes files](https://user-images.githubusercontent.com/22850096/60960415-3d013300-a30a-11e9-8e51-7fec988475cf.png)

### Expected result

All the routes should have the **name** properties

### Environment
<pre><code>
Libs:
- gridsome version: 0.6.6
- @gridsome/cli version: 0.2.1

Browser:
- [x] Chrome (desktop) version 75
 
For Tooling issues:
- Node version: 10.15.0 
- Platform:  Windows

</code></pre>

**Comment by krstic-duci** [comment]
@hjvedvik @tomtev How can I be of an assistance for this particular problem? I would like to tackle with it...

**Comment by hjvedvik** [comment]
Gridsome can't get the `name` value from the `<script>` tag without evaluating and executing it. And I'm not sure if that's a good idea. There is a PR (#756) open that suggests implementing front matter for components in `src/pages`. That might be a better way to set a route name for a page.

**Comment by krstic-duci** [comment]
@hjvedvik Thanks for pointing me the directions, will close the issue for now. Please reopen if needed.

**Comment by FistMeNaruto** [comment]
What about inferring the route name from the filename, like Nuxt does?

**Comment by silasabbott** [comment]
This is an issue I'm still experiencing with v0.7.23

Route names are only generated for **index.vue** as `home` and for '404.vue' as `*`. When using [gridsome-plugin-gtm](https://gridsome.org/plugins/gridsome-plugin-gtm), page view events are only sent to Google Tag Manager for routes that have names. I can manually send the event on page/component mount, but it would be a huge time-saver to have auto-generated, filename-inferred routes like Nuxt does.
