### ISSUE TITLE
vue-scroll-reveal in Gridsome SSR not building

### ISSUE THREAD

**Issue by LukeXF** [gridsome/gridsome#543]
Is it possible to use [vue-scroll-reveal](https://github.com/tserkov/vue-scroll-reveal) with Gridsome? I have had it working in Nuxt with `vue-scroll-reveal.js` having:
```
import Vue from 'vue';
import VueScrollReveal from 'vue-scroll-reveal';

Vue.use(VueScrollReveal, {
	reset: false,
	class: 'v-scroll-reveal',
	duration: 500,
	distance: '20px',
	mobile: true,
	interval: 600
});
```

and then loading `main.js` with:
```
plugins: [{src: '~/plugins/vue-scroll-reveal', ssr: false}],
```

I've got `vue-scroll-reveal` working with `gridsome develop` but it fails to build with `gridsome build` because the scroll-reveal package uses another package that tries to use `window` or `document` (which you can't access on SSR) also seen [here](https://github.com/gridsome/gridsome/issues/335#issuecomment-491003185).

on Girdsome in my `main.js` I have recently been using:

```
if (process.isClient) {
	const VueScrollReveal = () => import('vue-scroll-reveal');

	VueScrollReveal().then(scrollReveal => {
		console.log(scrollReveal);
		Vue.use(scrollReveal, {
			reset: false,
			class: 'v-scroll-reveal',
			duration: 500,
			distance: '20px',
			mobile: true,
			interval: 600
		});
	});
}
```

Which does actually add the VueScrollReveal into the project (I think), but then when viewing the HTML, none of the HTML elements have the `v-scroll-reveal` which I've given them. I'm guessing because on building Gridsome can't see a use for ` v-scroll-reveal` in HTML so it removes it maybe?

Is there any way you could add this a plugin to Gridsome or help point me in the right direction?

**Comment by u12206050** [comment]
Sorry for the slow reply. Have you tried wrapping the components where you use the `v-scroll-reveal` inside `<ClientOnly>` tags?
[Read more here](https://gridsome.org/docs/assets-scripts/#without-ssr-support)

**Comment by LukeXF** [comment]
I have yes, but unfortunately, the whole site uses `v-scroll-reveal` as I've animated every page. So it would defeat the point of using SSR if I decided to use `<ClientOnly>` across the whole site right? 

Ultimately I'd like to get the HTML attributes `v-scroll-reveal` rendered onto my front end code without it renders on the server-side (or for the server-side to ignore it), but I think I'm probably going to be out of luck.

It's strange that it works in Nuxt though, is it possible that someone can add this as a Gridsome plugin?

**Comment by derevandal** [comment]
I had same problem with `vue-if-bot`... Works with NuxtSSR, but not with Gridsome SSR.

**Comment by LukeXF** [comment]
@derevandal exactly! Can anyone at Gridsome provide some guidance?

**Comment by u12206050** [comment]
Hi everyone, I currently have two separate solutions that we can publish, but only want to publish one. 

**1** Please vote 🚀rocket for the first one; which is simply a fork of `vue-scroll-reveal` that we can publish as `gridsome-scroll-reveal` as a simple drop in replacement. eg.

```
import GridsomeScrollReveal from 'gridsome-scroll-reveal';

export default function (Vue, { router, head, appOptions, isClient, isServer }) {
  Vue.use(GridsomeScrollReveal)

  …
}
```

**2** Else vote 👀 eyes for the second; which is an extra library you include `gvue-scroll-reveal` that you would use like such within `main.js`

```
import VueScrollReveal from 'vue-scroll-reveal';
import GVueScrollReveal from 'gvue-scroll-reveal';

export default function (Vue, { router, head, appOptions, isClient, isServer }) {
  if(isServer) {
    Vue.use(GVueScrollReveal)
  } else Vue.use(VueScrollReveal)

  …
}
```

**Comment by u12206050** [comment]
In the meanwhile this will also work, which is basically what **Option 2** from above looks like:

```
import VueScrollReveal from 'vue-scroll-reveal';

export default function (Vue, { router, head, appOptions, isClient, isServer }) {
  if(isServer) {
    Vue.use({
      install(Vue, defaultOptions) {
        Vue.directive('scroll-reveal', {
          inserted: (el, binding) => {},
          update: (el, binding) => {},
        });
      }
    })
    Vue.prototype.$sr = {
      isSupported() {},
      sync() {},
      reveal() {},
    }
  } else Vue.use(VueScrollReveal)
}
```

**Comment by u12206050** [comment]
`gridsome-scroll-reveal` is published as a drop-in-replacement for `vue-scroll-reveal`

`npm install gridsome-scroll-reveal -S`

```
import GridsomeScrollReveal from 'gridsome-scroll-reveal';

export default function (Vue, { router, head, appOptions }) {
  Vue.use(GridsomeScrollReveal, {
			reset: false,
			class: 'v-scroll-reveal',
			duration: 500,
			distance: '20px',
			mobile: true,
			interval: 600
		})
}
```

**Comment by u12206050** [comment]
BTW, none of this is needed if you just use `process.isClient` around `Vue.use()`
eg.

```
import DefaultLayout from '~/layouts/Default.vue'

export default function(Vue) {
  Vue.component('Layout', DefaultLayout)

  if (process.isClient) {
    Vue.use(require('vue-scroll-reveal').default, {
      reset: true,
      class: 'v-scroll-reveal',
      duration: 500,
      distance: '20px',
      mobile: true,
      interval: 600
    })
  }
}
```

**Comment by LukeXF** [comment]
@u12206050 thank you so much for your multiple solutions. Your interim solution worked, and I've also installed `gridsome-scroll-reveal` which worked a treat since the code is so simple.

My working solution:

`yarn add gridsome-scroll-reveal`

```
// main.js
import GridsomeScrollReveal from 'gridsome-scroll-reveal';

export default function (Vue, {router, head, appOptions, isClient, isServer}) {

	// other code...

	Vue.use(GridsomeScrollReveal);
}
```

Appreciate you taking the time to help me out and add the plugin to Gridsome!

**Comment by loleg** [comment]
For situations like this there's now some guideance in the Gridsome documentation: https://gridsome.org/docs/assets-scripts/#without-ssr-support

**Comment by LukeXF** [comment]
Is there anything new added to Gridsome regarding that page?
