### ISSUE TITLE
Allow dynamic routes to be customized on single pages

### ISSUE THREAD

**Issue by tyrion** [gridsome/gridsome#546]
## Summary

I have a Post content type configured as follows:
```
      use: '@gridsome/source-filesystem',
      options: {
        typeName: 'Post',
        path: 'content/posts/*.md',
        route: '/:slug',
```

I would like some posts to have a different route. I am not sure if it is currently possible to do so. Looking at the doc I understood that I could specify `path` for each Post manually, which I would like to avoid. But as far as I understood `route` takes precedence over `path`, so I would not be able to specify `path` only for a couple of posts.

* Is there actually a way to do this? (For example, I tried passing a function to route but I did not succeed)
* Wouldn't it make more sense for path to have precedence over `route`?

### Motivation

I have an old blog where the routes had the form `/:year/:slug` and I would like to keep the old urls working, while switching to using only the slug in the url.

Thank you :)

**Comment by u12206050** [comment]
The proper way to do this is with redirects on your hosting platform. Netlify and most other host platforms support redirects. You would have something such as `/\d{4}/(.)* /$1` Meaning any route with 4 digits and then the slug would be redirected to just the slug.

For SEO this is also the better option since you are notifying browsers and search engines that this same page is now just under a different url.

**Comment by tyrion** [comment]
Ok, that makes sense, thanks for the reply.

Meanwhile I had already found a workaround, which I will share hoping it can be useful to someone else.

Basically I removed the `route` setting from the ContentType definition in `gridsome.config.js`. This way I would need to manually specify a path for each Post. In order to avoid that I added the following snippet in `gridsome.server.js`:
```javascript
module.exports = function(api) {
  const Post = api.store.getContentType('Post')

  // Automatically use the slug or title as a path by default
  Post.on('add', post => {
    if (post.path.startsWith('/content/posts')) {
      post.path = '/' + api.store.slugify(post.slug || post.title)
    }
  })
}
```
In this way, if I want to define a custom path, I just need to specify a `path` field in the frontmatter of one of my posts.

**Comment by Jonarod** [comment]
@tyrion interesting piece of code, however I couldn't make it work somehow. What I understand is that if you can get the existing `getContentType('Post')` that means the `add` has already been fired before `Post.on('add' ...` gets a chance to com into play. At least in my case, nothing happens.

Did you, by any chance, got it working using a slightly different code ?
Thanks !

**Comment by tyrion** [comment]
Hello @Jonarod, I don't remember exactly, because since then I switched to using Netlify redirects as suggested by @u12206050 . However I think it should work as is. Notice that I put the code directly inside the `module.exports` function. It should get executed before everything else and `getContentType('Post')` will create the `Post` ContentType since it does not exist yet.
