### ISSUE TITLE
Error with object spread syntax in gridsome 0.6.6

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#547]
## Description

Upgrading from 0.6.4 to 0.6.6, getting an issue with spread syntax in the Link component.

### Steps to reproduce

Upgrade to Gridsome 
Include any <g-link>

### Expected result

Everything works

### Actual result

Error in browser
```
vue.runtime.esm.js?2b0e:1888 ReferenceError: _objectSpread is not defined
    at render (Link.js?0ce5:52)
    at createFunctionalComponent (vue.runtime.esm.js?2b0e:3058)
    at createComponent (vue.runtime.esm.js?2b0e:3231)
    at _createElement (vue.runtime.esm.js?2b0e:3416)
    at createElement (vue.runtime.esm.js?2b0e:3353)
    at vm._c (vue.runtime.esm.js?2b0e:3485)
```

### Environment

Libs:
- gridsome version: 0.6.6

Browser:
- [ ] Chrome (desktop) version 75

For Tooling issues:
- Platform: Linux

**Comment by cco3** [comment]
Issue also exists in 0.6.5

**Comment by cco3** [comment]
Specifying "@babel/plugin-proposal-object-rest-spread": "^7.5.4", in my package.json fixed the issue.

**Comment by lynden-jones** [comment]
I am seeing this issue with the most recent version of gridsome (0.7.12).

I added `@babel/plugin-proposal-object-rest-spread` to `package.json` and also put this in .babelrc:

```
{
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}
```

Any ideas why I might still be seeing this issue?  🤔

**Comment by lynden-jones** [comment]
Ok figured it out.  Turns out that I had some code that must have been missed by the build transpiler process.  It was dynamic content that didn't load until after certain user actions.  I thought all code was transpiled, but I guess not.
