### ISSUE TITLE
No error during Develop. Lots of errors during Build

### ISSUE THREAD

**Issue by FilledStacks** [gridsome/gridsome#549]
## Description

When using some vue packages I'm seeing that it works during development. When I try to build for a release it fails. I'll use one of the dependent packages as an example.

### Steps to reproduce

1. npm install vue-custom-scrollbar
2. make use of the component like [this](https://binaryify.github.io/vue-custom-scrollbar/en/#why-custom-scrollbar)
3. Run `gridsome develop` (it works)
4. Run `gridsome build` (it fails)

### Expected result

The project should build properly during development and build to keep suprises before a release to a minimum.

### Actual result

Project fails when trying to build with error

```
ReferenceError: document is not defined
```

### Environment

@gridsome/cli v0.0.9
gridsome v0.5.8

Browser:
- [x] Chrome (desktop) 
- [x] Safari (desktop) version XX

**Comment by u12206050** [comment]
Try wrapping the component in `<ClientOnly>` 
Here are the docs: https://gridsome.org/docs/assets-scripts/#without-ssr-support

**Comment by FilledStacks** [comment]
Hi I'll try that. I don't know how i would do that in the vue component itself since it's being used in the template as well. Should i wrap the import statement?

________________________________

**Comment by u12206050** [comment]
Hi, 
you wrap i around the component. eg.
```
<template>
</template>
```

**Comment by FilledStacks** [comment]
Much appreciated. I will let you know when I've tried it and close this issue. Thank you.

________________________________

**Comment by FilledStacks** [comment]
Much appreciated. This worked, definitely need some friendlier errors to indicate some errors :)

**Comment by u12206050** [comment]
Just in summary for anyone getting this error: `ReferenceError: document is not defined`, and it is a third party component such as `vue-custom-scrollbar` then you have to wrap it in the `<ClientOnly>` tags as shown above such that it will not try and render within Nodejs when building the site.

More info [here](https://gridsome.org/docs/assets-scripts/#without-ssr-support)

**Comment by mklueh** [comment]
Would it be possible to add at least the corresponding file to the logs to make it easier finding the cause?

**Comment by zync09** [comment]
> Hi,
> you wrap i around the component. eg.
> 
> ```
> <template>
>   <div>
>     <ClientOnly>
>       <vue-custom-scrollbar></vue-custom-scrollbar>
>     </ClientOnly>
>   </div>
> </template>
> 
> <script>
> // Don't import it here
> export default {
>   components: {
>     vueCustomScrollbar: () => import('vue-custom-scrollbar') // Lazy load it in
>   }
> }
> ```

Thanks heaps for this. Was stuck trying to build with gridsome for ages. Lazy load the component and wrap the tag with ClientOnly. Thanks heaps for this!!

**Comment by rubenmarcus** [comment]
this should be at the docs. Lot of issues with Vue plugins, but for me worked, thanks

**Comment by stefanaz** [comment]
Hi guys, just in case someone has the same issue, with lazy load and **destructuring**,  solution is here: 

```
<ClientOnly>
    <Slide />
</ClientOnly>
```

```
  components: {
      Slide: async () => {
          const { Slide } = await import('vue-burger-menu')
          return Slide
      },
  }
```
