### ISSUE TITLE
Question: Generate pages dynamically from GraphQL data?

### ISSUE THREAD

**Issue by Js-Brecht** [gridsome/gridsome#554]
I have a particular use case I am investigating, and I would like to know if it is even feasible with Gridsome.

I would like to generate pages dynamically (i.e. determine what components & design the page should use from data).  There will be an engine examining the data, to determine what components should be placed on the page, where, and how.  I would have a plugin querying data, and feeding it to a page that would act as a generator, using the data to generate the component instances and the design, based off what is provided to it through the pipeline.

The page might work something like this:
[Dynamically loaded components from Store data](https://jsfiddle.net/Myrlin1/yLf89vwz/)

That's the general concept.  Probably quite a few things would need to change.  For one, I would need to load the component dynamically.  So, it would need to `require(./path/to/component)`, and then use that data to create the Vue component instance.  There's also differences between Object based components, and class based components, so the actual generation process would be a little different (class based components are actually easier), but this is the general idea.

I'm certain I could make this work, but would all of that actually build a static site?  Or does that defeat the purpose of Gridsome?  I don't know enough about the internals yet.

---------

I'd also like to know if it is possible, or could it be possible, to pass a Vue component to the `createPage()` API, instead of passing it the **path** to a Vue component.  Reason being, it would be nice to pass props to the page, instead of making it read everything from a page-query.

**Comment by u12206050** [comment]
Hi @Js-Brecht, Yes this is totally feasible, and to some extent I have done the same except only on a "block" level not entire pages, however that shouldn't cause an issue.

First off the engine will still need to **know about** but **not load** all the dynamic components that you want. To do this simply specify you'll probably have an engine component looking a lot like this:

EXTRA: I am wrapping each component to also lazy load (using LazyHydrate) which will also speed up the initial page load.
```
// src/structure/section.vue

<template>
  <div class="section-blocks" :class="classes">
    <template v-for="(block, index) in blocks">
      <div class="block" :key="`${block.component}-${index}`">
        <LazyHydrate when-visible>
          <component :is="block.component" v-bind="block.props"></component>
        <LazyHydrate when-visible>
      </div>
    </template>
  </div>
</template>

<script>
export default {
  name: 'Section'
  props: {
    blocks: {
      type: Object,
      required: true
    },
    classes: {
      type: Array
    }
  },
  components: {
    Gallery: () import('~/components/Gallery.vue'),
    Slider: () import('~/components/Slider.vue'),
    Chart: () import('~/components/Chart.vue'),
    Html: () import('~/components/Html.vue'),
    ImageGrid: () import('~/components/ImageGrid.vue'),
    Banner: () import('~/components/Banner.vue'),
    CallToAction: () import('~/components/CallToAction.vue')
  }
}
</script>
```


**Example of blocks:**
```
[
  {
    component: 'Section',
    props: {
      blocks: [
        {
          component: 'Banner',
          props: {
            title: 'Lorem Ipsum',
            byline: 'Nice to meet you',
            background: 'https://via.placeholder.com/1200/600'
          }
        }
      ],
      classes: ['top-blocks']
    }
  }
  {
    component: 'Gallery',
    props: {
      images: [{
        thumb: 'https://via.placeholder.com/150,
        image: 'https://via.placeholder.com/800',
        label: 'First image'
      },{
        thumb: 'https://via.placeholder.com/150,
        image: 'https://via.placeholder.com/800',
        label: 'Second image'
      },{
        thumb: 'https://via.placeholder.com/150,
        image: 'https://via.placeholder.com/800',
        label: 'Third image'
      }]
    }
  },
  {
    component: 'Section',
    props: {
      blocks: [
        {
          component: 'CallToAction',
          props: {
            title: 'Lorem Ipsum'
            label: 'Contact us now'
            link: '/contact'
          }
        }
      ],
      classes: ['bottom-blocks']
    }
  }  
]
```
Notice you can reuse the Section component recursively.
Add this component to your pages that contain these dynamic blocks.

Hope this helps.

**Comment by Js-Brecht** [comment]
Ah, so the components **MUST** be registered explicitly?  Is that just so Gridsome knows about them?

I would be willing to do that, but it is another maintenance step.  I would prefer to have the server manage components: let users design components that conform to design specifications that the server can understand, then upload their component package to the server.  Let the server maintain its own container for components, and just tell the Gridsome build process how to find them.

This is another reason I was asking if you could feed Gridsome Vue objects, because the components could then be added to the Vue object at build time, before they are processed.  I don't suppose Webpack would know about them in that case, though.... or some extra work would need to be done for Webpack to see them.

The whole point is to keep the page engine a server managed process, and let people plug in to it, without having to worry about going and changing its code.  I want people to be able to create their own custom components, plug them in, and use them for designing pages, without having to worry about modifying the core design to register their component.  And by designing pages, I mean by using a UI.  This way, somebody who doesn't code can take working components, and design their site using them, even including new components somebody else has wrote; then the server can build and publish the site.

I guess I could have the server generate the source code for the component registrations... ugh...

**Comment by u12206050** [comment]
Ah I understand. Yeh it is webpack that essentially needs to know about the
components otherwise you'd be downloading the same libraries again and
again unless...

You create generic component that is just a wrapper that accepts the path
or name of a component to use. Then you fetch that component which should
be built as a standalone component UMD, you could use requirejs for this
step.
But once loaded you then mount it programmatically like so:

```
const comps = {};

export default {
beforeMount() {
  if (process.isServer) return

  this.loading = true

 require(`/dynamic/comps/${this.block.compName}.js`, (comp) => {
  if (!comps[this.block.compName])
    comps[this.block.compName] = this.extend(comp)

  this.comp = new comps[this.block.compName](this.block.props)

  this.comp.$mount()
  this.$refs.container.appendChild(this.comp.$el)
  this.loading = false
})
}
```

I just found this link which explains the same
[creating-instances-programmatically](
https://css-tricks.com/creating-vue-js-component-instances-programmatically/
)

Really nice idea you have btw but there are a few things I would consider.

1. For this to work each component would need to be bundled into a UMD,
which would mean that unless you force the use of requires to handle
dependencies you are going to be downloading possible duplicate code
multiple times.

2. Code splitting might be hampered but since you are lazy loading this
might not be such a big issue until you are loading a lot of blocks.

3. Unsure if this will work server side.

**Comment by u12206050** [comment]
Ah I understand. Yeh it is webpack that essentially needs to know about the
components otherwise you'd be downloading the same libraries again and
again unless...

You create generic component that is just a wrapper that accepts the path
or name of a component to use. Then you fetch that component which should
be built as a standalone component UMD, you could use requirejs for this
step.
But once loaded you then mount it programmatically like so:

```
<template>
  <div ref="container" :class="{loading: loading}"></div>
</template>

<script>
const comps = {};
export default {
  props: {
    block: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      loading: true
    }
  },
  beforeMount() {
    if (process.isServer) return

    this.loading = true

    require(`/dynamic/comps/${this.block.compName}.js`, (comp) => {
      if (!comps[this.block.compName])
        comps[this.block.compName] = this.extend(comp)

      this.comp = new comps[this.block.compName](this.block.props)
      this.comp.$mount()
      this.$refs.container.appendChild(this.comp.$el)
      this.loading = false
    })
  }
}
</script>
```

I just found this link which explains the same
[creating-instances-programmatically](https://css-tricks.com/creating-vue-js-component-instances-programmatically/)

Really nice idea you have btw but there are a few things I would consider.

1. For this to work each component would need to be bundled into a UMD,
which would mean that unless you force the use of requires to handle
dependencies you are going to be downloading possible duplicate code
multiple times.

2. Code splitting might be hampered but since you are lazy loading this
might not be such a big issue until you are loading a lot of blocks.

3. Unsure if this will work server side.

**Comment by Js-Brecht** [comment]
I like that idea, using a ComponentLoader wrapper.  I also found this: [Using VueJS computer properties for dynamic module imports](https://medium.com/@codetheorist/using-vuejs-computed-properties-for-dynamic-module-imports-2046743afcaf).  It looks like when you use `import()`, WebPack automatically splits your code.

I set up a test respository, built off of the typescript starter:
https://github.com/Js-Brecht/gridsome-ts

Let me know what you think of that method.

I ran it with webpack-bundle-analyzer, and the components did get loaded into their own chunks.  It looks like it just looks at the static part of the path you are using in your `import()` function, and adds all of the files underneath it to a chunk.  `webpackChunkName` is supposed to put each different request into its own chunk; see what I did in `components/ComponentLoader.vue`.  Looks like `ComponentLoader` got loaded into the `Index.vue` chunk, and `Tabs.vue` got its own chunk.  I need to test with more components, to see what happens, but I think this might work for concern #2.

I would think that since Webpack picks these modules up automatically from a dynamic `import()` function, it should pick up anything statically imported in each of those modules.  So code-splitting should be working correctly.  Unless I'm mistaken, shouldn't that solve concern #1?

About #3, do you mean SSR?  I really don't think this would work with SSR... not dynamic imports.

Correct me if I'm wrong, but this kind of use would deviate from the whole static site concept, yeah?  All the data fetching would be done already, but there would still be a lot of rendering being done in Javascript, for all of the pages generated like this.  I wonder what the performance impact would be.

What would be nice would be to have a renderer do some pre-processing, resolving each of the dynamic components, using the data that is provided from the GraphQL layer during build time, .  As dynamic as this is, the data itself is static once it has been collected, so the design itself wouldn't change after it's been loaded.  Then the content delivered could be static + the Vue layer, just like a standard page is.

**Comment by u12206050** [comment]
For Webpack to split your code it would still need to know about it at build time, meaning you have to rebuild your entire project whenever you add a new component. Whereas the method I pointed out earlier would have one core Webpack bundle which is the main website, and then each component would be built separately. 

Static site rendering could still work but yes it will ruin the speed benefits but not as much. You would be including a lot of extra requests that first need to fetch each component and then mount them. However you might be able to balance that out with SSR only built blocks. Meaning blocks with information that are only built server side and not client side (just note, methods won't work one such blocks so use them for static content only, links are fine).

btw, SSR in terms of Static site rendering I refer to the site being built in Nodejs, such as when it is being built.

**Comment by Js-Brecht** [comment]
Rebuilding the project is basically what's going to be happening every time you make changes to the design, anyway.  I will have a server handling all of the build details, like the component store, the database, building and publishing the site... all of that.  It will essentially be the go-between between the user, and the site build process (Gridsome, here).  It's the piece of this that shouldn't need to be rebuilt every time a new component is added; and one great thing about using a static site generator like this is that the server doesn't need to run unless you are making changes to the design of the site or your data.

This is just another kind of CMS.  I have seen plenty of CMS that will build a static site for you, driven by data, and several of them let you build markdown pages; but that still means you need to write your templates beforehand.  What I'm working on is a CMS, but also a template engine that will let the user generate their templates, modularly, through the user interface, so they don't need to know how to write the code to make everything work... but it still needs to be extensible, pluggable.  There are some of those out there, too, but I have yet to see any that will generate a static site.

I have been in SPFx land for quite some time now.  If you've ever used Sharepoint, especially their Modern framework, then you know what I'm talking about.  You can also do the same kind of thing using Drupal, and I'm sure there's more.  But systems like Sharepoint tend to be bloated, are not very performant, can get expensive, and they require a 24/7 server... plus there's always some issues in the design, and it can be difficult to alter the trajectory of projects like that.

I think that this will work for my purposes.  I will just need to build it and see how it runs.
Thank you for your input!
