### ISSUE TITLE
Question: how to filter belongsTo nodes

### ISSUE THREAD

**Issue by jfet97** [gridsome/gridsome#556]
I've used taxonomy to connect Posts to Authors, and the `<page-query>` inside the `Author.vue` template is the following:

```
query Author ($id: String!) {
  author: author (id: $id) {
    name
    surname
    nickname
    url
    content
    belongsTo {
      edges {
        node {
          ... on Post {
            title
            path
            id
          }
        }
      }
    }
  }
}
```

### Request
I'd like to filter the fragment query into the `belongsTo` field to retrieve only published posts: 
```
filter: { published: { eq: true } }
```
but the following is not allowed:
```
query Author ($id: String!) {
  author: author (id: $id) {
    name
    surname
    nickname
    url
    content
    belongsTo {
      edges {
        node {
          ... on Post(filter: { published: { eq: true } }) {
            title
            path
            id
          }
        }
      }
    }
  }
}
```
I'm quite a beginner with GraphQL, IDK if that is a limitation of the parser used to handle  `<page-query>` tags or if GraphQL doesn't allow such a query or if I am doing it wrong.

**Comment by u12206050** [comment]
Hi @jfet97. Unfortunately this is a limitation on GraphQL however in some cases, including yours it might work if you rewrite your query two request the author and their posts separately such as:

```
query Author ($id: String!) {
  author: author (id: $id) {
    name
    surname
    nickname
    url
    content
  }
  posts: allPost(filter: { author: { in: [$id] }, published: { eq: true } }) {
    edges {
      node {
        id
        title
        path
      }
    }
  }
}
``` 

Try it in the explorer, you might have to adjust the author filter a bit. But this will then give you `this.$page.author` and `this.$page.posts`
Hope this helps

**Comment by jfet97** [comment]
Thanks @u12206050 for your fast feedback and for making me clear that is a GraphQL limitation.
The workaround you presented makes completely sense to me, so thanks :D for your time

**Comment by muhhizbe** [comment]
> Hi @jfet97. Unfortunately this is a limitation on GraphQL however in some cases, including yours it might work if you rewrite your query two request the author and their posts separately such as:
> 
> ```
> query Author ($id: String!) {
>   author: author (id: $id) {
>     name
>     surname
>     nickname
>     url
>     content
>   }
>   posts: allPost(filter: { author: { in: [$id] }, published: { eq: true } }) {
>     edges {
>       node {
>         id
>         title
>         path
>       }
>     }
>   }
> }
> ```
> 
> Try it in the explorer, you might have to adjust the author filter a bit. But this will then give you `this.$page.author` and `this.$page.posts`
> Hope this helps

I try this like this,

```
query Tag ($id: ID!, $page: Int) {
    tag : tag(id: $id) {
        title
    }
    posts: allPost(perPage: 2, page: $page, sortBy: "date", filter: { tag: { in: [$id] }, published: { eq: true } }) @paginate {
        pageInfo {
            totalPages
            currentPage            
        }
        edges {
            node {
                title
                path
                date (format: "D MMMM YYYY")
                timeToRead
                description
                content
            }
        }
    }
}
```

but I get this an Error message in terminal
`Error: Field "in" is not defined by type TagListQueryOperatorInput. Did you mean id?`

**Comment by u12206050** [comment]
@muhhizbe 

Try without the `in` like this:  `filter: { tag: $id, published: … `
