### ISSUE TITLE
Wordpress Souce Plugin - Error: ECONNREFUSED - /wp-json/wp/v2/types

### ISSUE THREAD

**Issue by simduchaine** [gridsome/gridsome#557]
## Description

Trying to setup a gridsome site using the official wordpress plugin (@gridsome/source-wordpress) but when I'm running `gridsome explore` or `gridsome develop` I get an Error.

### Steps to reproduce

Setup a new gridsome website using the WordPress starter kit (`gridsome create my-blog wordpress`). Add the website baseUrl then run `gridsome develop`. 

### Expected result

Gridsome should be able to start the development server and fetch the WordPress data.

### Actual result

```
$ gridsome develop
Gridsome v0.6.6

Initializing plugins...
Initialize - 1.81s
Loading data from
Error: ECONNREFUSED - /wp-json/wp/v2/types
    at WordPressSource.fetch (B:\Projets\Dev\Websites\travel-blog-gridsome\node_modules\@gridsome\source-wordpress\index.js:168:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I tried hitting the endpoint `/wp-json/wp/v2/types` in my browser and in Postman and everything is okay. I have a few types there outside of `post`, `page` and `attachments`. I see `wp_blocks`, `feedback`, `jp_pay_order` and `jp_pay_product`. 

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.6
- @gridsome/cli version: 0.0.8

Browser:
- [X ] Chrome (desktop) version 75.0.3770.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.10.0
- Platform:  Windows 10

Others:

</code></pre>

**Comment by u12206050** [comment]
@simduchaine This might be a rate limit issue which is the server trying to block a DDOS attack. You can check if this is the case if some of the other queries are getting data eg. `/wp-json/wp/v2/posts` if so, then the WP plugin will have to implement a rate limiter such as to not create so many consecutive requests.

Could you check this?

**Comment by simduchaine** [comment]
@u12206050 After your comment, I thought that some security plugins like Jetpack or Wordfence (both installed on my Wordpress website) could block the request. I disabled them and changed the gridsome.config.js file from `concurent: 10` to `concurent: 1`. 

It didn't work. 

Then, I checked at my apache logs and I found this when fetching the data: 
```
 [15/Jul/2019:23:18:05 +0000] "-" 408 3266 "-" "-"
::1 - - [15/Jul/2019:23:18:08 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.29 (Ubuntu) Ope                                nSSL/1.1.0g (internal dummy connection)"
```

So I see code 200, which I assume is okay on the server side.

This is such a headache.

**Comment by simduchaine** [comment]
Ok I realised that on project setup I used the Wordpress Starter Kit `gridsome create my-gridsome-site wordpress`. 

I setup a new project with the standard setup `gridsome create my-gridsome-site` and added the wordpress source plugin by hand. I don't have the ECONNREFUSED problem anymore! So it looks like the problem come from the wordpress starter.

**Comment by simduchaine** [comment]
@u12206050 Now I realize that even if I don't get the ECONNREFUSED error on `develop`, it's like if Graphql is unresponsive and crashed. When I go to the graphql explorer I get an "unresponsive" alert and on the frontend I have a lot of "undefined".

**Comment by u12206050** [comment]
@simduchaine do you mind adding me to your code repo, or sending me the Wordpress url you are using such that I can try and reproduce?

**Comment by simduchaine** [comment]
@u12206050 I'm trying to fetch my blog `https://voyage.simonduchaine.com`. REST API is active and functional (tested it in Postman). 

You can test this. Nothing fancy on my project, just the default starter gridsome config and added the `source-wordpress` plugin in my `gridsome.config.js`.

**Comment by ehibes** [comment]
Same problem. I use Wordpress with built-in server in local. WP API is ok from postman, but  ECONNREFUSED from Gridsome. 
```
Gridsome v0.7.3

Initializing plugins...
Loading data from http://localhost:8000
Error: ECONNREFUSED - http://localhost:8000/wp-json/wp/v2/types
    at WordPressSource.fetch (/Users/theuser/Documents/gridsome-test/node_modules/@gridsome/source-wordpress/index.js:165:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I just made a fresh install of Wordpress, and configured permalink to activate API.

**Comment by u12206050** [comment]
@simduchaine Loading the site from https://voyage.simonduchaine.com works for me. It downloads all the images and starts up the local server.

**Comment by smth** [comment]
I get a very similar error, in a specific context. Running on my Mac everything works as expected. Trying to run on Windows Subsystem for Linux I get:

```
Error: ECONNREFUSED - wp/v2/types
    at WordPressSource.fetch (/mnt/c/path/to/node_modules/@gridsome/source-wordpress/index.js:190:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by simduchaine** [comment]
@u12206050 I'll give it a try. Been letting this project aside for a while now. Might work with a fresh gridsome wordpress starter project.

**Comment by simduchaine** [comment]
@u12206050 it's not working. I get this error when running the `gridsome develop` command:

```
Initializing plugins...
Loading data from https://voyage.simonduchaine.com
Error: Status 401 - wp/v2/feedback
Load sources - 22.33s
Error: Cannot get field 'undefined' from type 'WordPressAttachment_Smush'. Field does not exist.
    at ObjectTypeComposer.getField (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\graphql-compose\lib\ObjectTypeComposer.js:173:13)
    at ObjectTypeComposer.getFieldExtensions (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\graphql-compose\lib\ObjectTypeComposer.js:1052:24)
    at ObjectTypeComposer.extendFieldExtensions (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\graphql-compose\lib\ObjectTypeComposer.js:1065:26)
    at addFieldExtensions (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:158:25)
    at addInferredFields (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:146:9)
    at createFields (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:120:3)
    at createNodesSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:37:5)
    at createSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\createSchema.js:59:3)
    at Schema.buildSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\app\Schema.js:28:28)
    at Plugins.createSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\app\Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by jcooley8** [comment]
Been getting this as well @simduchaine -- any updates? I think it has to do with the smush plugin.

> Initializing plugins...
> Loading data from https://voyage.simonduchaine.com
> Error: Status 401 - wp/v2/feedback
> Load sources - 22.33s
> Error: Cannot get field 'undefined' from type 'WordPressAttachment_Smush'. Field does not exist.
>     at ObjectTypeComposer.getField (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\graphql-compose\lib\ObjectTypeComposer.js:173:13)
>     at ObjectTypeComposer.getFieldExtensions (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\graphql-compose\lib\ObjectTypeComposer.js:1052:24)
>     at ObjectTypeComposer.extendFieldExtensions (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\graphql-compose\lib\ObjectTypeComposer.js:1065:26)
>     at addFieldExtensions (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:158:25)
>     at addInferredFields (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:146:9)
>     at createFields (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:120:3)
>     at createNodesSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\nodes\index.js:37:5)
>     at createSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\graphql\createSchema.js:59:3)
>     at Schema.buildSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\app\Schema.js:28:28)
>     at Plugins.createSchema (B:\Projets\Coding_Dev\Websites\travel-blog-gridsome-wp\node_modules\gridsome\lib\app\Plugins.js:94:22)
>     at processTicksAndRejections (internal/process/task_queues.js:85:5)
> ```

**Comment by simduchaine** [comment]
@jcooley8 Oh that's right I didn't realised there was that "smush" keyword in the attachment type.

I'll try to deactivate smush plugin and try again.

**Comment by simduchaine** [comment]
Okay so I deactivated the SMUSH plugin and now it's working like a charm!
