### ISSUE TITLE
In-component guards not called

### ISSUE THREAD

**Issue by f-elix** [gridsome/gridsome#558]
I'm trying to call beforeRouteLeave() on a page component and nothing happens. Any idea how to access these vue-router guards from inside the component?

**Comment by hjvedvik** [comment]
The `beforeRouteLeave()` method isn't available on `this`. It's a life-cycle hook that Vue Router uses and is not meant to be called manually. You can instead move any logics in it to a normal method which you can use both in the component and in the `beforeRouteLeave()` hook.

**Comment by f-elix** [comment]
Thanks for the response I didn't know that! Appreciate it. Closing the issue.
