### ISSUE TITLE
[CLI]: How about having a banner

### ISSUE THREAD

**Issue by jamesgeorge007** [gridsome/gridsome#559]
> This is just a basic illustration, all the color-combo can be customized as required

![Screenshot from 2019-07-17 09-56-57](https://user-images.githubusercontent.com/25279263/61347176-8d800f80-a879-11e9-9ab5-c131e582662c.png)
.

**Comment by jamesgeorge007** [comment]
There is a pre-available package for the purpose - [node-banner](npmjs.com/package/node-banner)

**Comment by jamesgeorge007** [comment]
cc @hjvedvik

**Comment by jamesgeorge007** [comment]
I have had put together an npm package for the purpose - [node-banner](https://www.npmjs.com/package/node-banner)

**Comment by jamesgeorge007** [comment]
cc @hjvedvik @clarkdo

**Comment by jamesgeorge007** [comment]
cc @hjvedvik @tomtev @clarkdo

**Comment by jamesgeorge007** [comment]
@hjvedvik @tomtev @clarkdo shall I go ahead :thinking:

**Comment by hjvedvik** [comment]
Looks like a good package, but I think we'll leave the CLI simple an clean for now :)
