### ISSUE TITLE
Failed to compile with 1 errors

### ISSUE THREAD

**Issue by codenamezjames** [gridsome/gridsome#565]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

<pre><code>
Libs:
@gridsome/cli v0.2.0
gridsome v0.6.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.13.0
- Platform:  Mac
</code></pre>

**Comment by u12206050** [comment]
Closing due to lack of information.
