### ISSUE TITLE
Having a dedicated command to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [gridsome/gridsome#566]
## Summary

Presently, as in the issue-template the user is required to provide information concerning his local environment. 

### Basic example

`gridsome info`

### Motivation

A dedicated `info` command would ease the workflow, and all the user has to do is to paste the results as shown.

**Comment by jamesgeorge007** [comment]
cc @hjvedvik

**Comment by jamesgeorge007** [comment]
cc @hjvedvik @tomtev

**Comment by jamesgeorge007** [comment]
cc @tomtev @clarkdo

**Comment by hjvedvik** [comment]
Good idea @jamesgeorge007 :) I did something similar for the `gridsome -v` command once: https://github.com/gridsome/gridsome/issues/176#issuecomment-461860150. But we ended up only showing the CLI and local Gridsome version instead. A `gridsome info` command is probably better for that kind of info.
