### ISSUE TITLE
router.push() behaving differently than g-link

### ISSUE THREAD

**Issue by mnlmaier** [gridsome/gridsome#567]
## Description

`router.push()` doesn't unmount the layout

### Steps to reproduce

add an action to the `mounted` hook of the layout and notice that it's always called when navigating via `g-link` but not when navigating via `push()`

### Expected result

Mounting/unmounting should behave consistently for both cases

### Actual result

`g-link` unmounts/mounts the layout, `push()` doesn't

### Notes
To be honest, I don't even know if this is a bug or just something I wasn't able to find in the docs. I would like to programmatically navigate between pages with the same behavior as it would occur when clicking on a `g-link`. Any ideas? :)

**Comment by hjvedvik** [comment]
The `g-link` component is a wrapper around the `router-link` component from Vue Router. And `router-link` calls `push()` internally. So it should have the same behavior :) I tested it now and it seems to work as expected.

**Comment by mnlmaier** [comment]
@hjvedvik thanks for checking out my issue! how are you calling `push()`, are you passing any options which I might have missed?

**Comment by hjvedvik** [comment]
@mnlmaier I just tested with this code and it behaved like expected:
```html
<button @click="$router.push({ path: '/about' })">About</button>
```
How are you calling `router.push()` in your code?

**Comment by mnlmaier** [comment]
Just a quick heads up: Of course, the issue was not related to the router itself – i was using a template to create pages based on and filled with graphql content, which did not trigger the Vue hooks I was expecting since the actual template has not been updated.

To solve this, I am now using a randomly generated key (or something like `Date.now()`) as a prop on the components I want to update to trigger a forced update on each route change.

Maybe someone will find this helpful :)

**Comment by platform-kit** [comment]
@mnlmaier or @hjvedvik , could either of you shed some light on what exactly determines whether a component is re-rendered upon route change?

My mounted() code doesn't seem to run when I use g-link, but does run if it's the first page loaded.
