### ISSUE TITLE
GraphQL not building schema

### ISSUE THREAD

**Issue by cbaone** [gridsome/gridsome#573]
## Description

Even with the default starter project the GraphQL schema has nothing more than path and context. I can't grab id, path, title, slug, content, date or anything else. It seems I have done something wrong, but I followed the install step by step, several times with no luck.  I'm happy to have someone tell me it was a stupid mistake, because then I could move on. I don't know that there's any other information I can give.

### Steps to reproduce

Install Gridsome as defined on the Gridsome site.

### Expected result

GraphQL schema should display all the nodes in this query:
<pre><code>
query {
  allPage {
    context
    id
    type
    title
    slug
    path
    component
    pageQuery {
      type
      content
      options
    }
    content
    date
  }
}
</pre></code>

### Actual result

The schema returns:

path
context

Even this query returns errors after a "stock" install

<pre><code>
query {
  allPage {
    id
    title
  }
}
</pre></code>

<img width="660" alt="Screen Shot 2019-07-22 at 11 18 37 AM" src="https://user-images.githubusercontent.com/239041/61651593-6a879e00-ac73-11e9-8dcd-8fab2330809d.png">

<img width="1027" alt="Screen Shot 2019-07-22 at 11 25 16 AM" src="https://user-images.githubusercontent.com/239041/61651594-6a879e00-ac73-11e9-955c-9224b65cf583.png">

### Environment

<pre><code>
Libs:
@gridsome/cli v0.2.1
gridsome v0.6.6

Browser:
- [x] Chrome (desktop) version 75.0.3770.142
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.4.0
- Platform:  Mac

</code></pre>

**Comment by hjvedvik** [comment]
The `Page` type in the schema is very limited and not very useful atm. It just lists the paths for the registered pages on your site :) You should instead add your own data with custom fields etc. It can either be done with source plugins or manually with the [Data Store API](https://gridsome.org/docs/data-store-api).

**Comment by cbaone** [comment]
OK. That helps.

If I want to avoid .md files, will Gridsome still dynamically generate routes for .vue files in the /pages directory? Because I'm not able to access anything in GraphQL when trying to run v-for to build out the menu. I guess I'm dense, not getting how to get the nodes into GraphQL. 

I realize that I need to create the data structures, but is this not allowed?

<pre><code>
use: '@gridsome/source-filesystem',
      options: {
        path: 'docs/**/*.vue',
        typeName: 'CodeSample'
      }
</pre></code>

**Comment by hjvedvik** [comment]
Yes, Vue components in `src/pages` will have their own routes automatically. But it's not possible to automatically generate a menu for them atm. So I would recommend settings the menu up manually instead for now. We might allow some front matter data (like title etc.) for the pages that will be available in the schema, but it's not implemented yet.

Using `*.vue` files with the `@gridsome/source-filesystem` plugin won't work because there is no transformer that can parse the files.

**Comment by cbaone** [comment]
Yes. I figured that out last night. Thanks for confirming. 

However, I did discover the mdvue plugin that's being built and I might be able to use that. It looks nearly ready, do you have a potential release date? In the meantime, I will just build out the menu manually.
