### ISSUE TITLE
Question: Possible to serve static version to certain browsers?

### ISSUE THREAD

**Issue by jarred** [gridsome/gridsome#577]
I have a site with some complicated interactions that is just not worth the effort/time trying to make it work in Edge and IE.

What is the best way to serve the static generated html (no javascript) to some browsers? 

Would it be to wrap `Vue.component("Layout", DefaultLayout);` in `main.js` in some conditional statements? Or with this affect static rendering also?

Also, is there a static version of `<ClientOnly>` ? E.g. `<StaticOnly>` where the content is only compiled into the initial html templates and later overwritten by Vue.

Thank you for any help. Enjoying the framework, will share the site once it launches.

**Comment by hjvedvik** [comment]
You can check out the [vue-lazy-hydration](https://github.com/maoberlehner/vue-lazy-hydration) package and see if you can accomplish what you want with it. Especially the [Manually trigger hydration](https://github.com/maoberlehner/vue-lazy-hydration#manually-trigger-hydration) section. The idea is to server-side render the component, but only hydrate it in the browser when you want to.

**Comment by jarred** [comment]
@hjvedvik thank you, this looks great.
