### ISSUE TITLE
How to pass variables in a query?

### ISSUE THREAD

**Issue by cartoonmadrasah** [gridsome/gridsome#580]
How can I replace this agent's name with the one in this query? Instead of hardcoding umer, i want to use listing_agent._text from the query. I tried my best to understand the variables part here: https://gridsome.org/docs/querying-data/#query-data-in-templates - but can't seem to get it working. Please help. Thank you.

![Image 1](https://user-images.githubusercontent.com/7679807/61998149-f0b54180-b0c4-11e9-8682-c106955f8b86.png)

**Comment by hjvedvik** [comment]
If I understand correctly, you want to use the value of `predubai.listing_agent._text` in the filter for `allPredubai`? The opposite is not possible, unfortunately.

When using an automated template, Gridsome will pick values from the current node based on a certain naming convention. You could try a variable named `$listing_agent___text` (three underscores) to get the `node.listing_agent._text` value as a variable.

**Comment by cartoonmadrasah** [comment]
Yes, It's working great now. I had tried this earlier, I am sure I must have missed the three underscores. Thank you once again. I am loving gridsome so much.

**Comment by RehanSaeed** [comment]
Would you mind posting the final query? I'd really appreciate seeing what the answer was.
