### ISSUE TITLE
Question: Vue filtering from graphql dataset

### ISSUE THREAD

**Issue by thomas-evensen** [gridsome/gridsome#586]
Hi!

How do I create a dynamical filter using a computed property from vue and the graphql dataset from gridsome? I've looked at several articles that all use the array.filter()-method, but I can't get it to work on my case. It seems like the "node"-part of the graphql-object ($page.posts.edges.node.[values]) are making it difficult to use the array.filter(). Is there a way of removing the "node"-part so that the object would be $page.posts.edges.[values]?

This is my first coding project since early 2000, so please feel free to point me in the right direction if this is the wrong forum for this question.

This is my page query:
```graphql
<page-query>
    query Members {
        posts: allMember(sort: [{ by: "priority", order: ASC }, { by: "created", order: DESC }]) {
            edges {
                node {
                    id
                    slug
                    name
                    image
                    created
                    priority
                    team {
                        name
                    }
                }
            }
        }
    }
</page-query>
```
I loop through the dataset with:
```html
<member-card 
v-for="item in filteredData" 
:key="item.node.id" 
:item="item">
</member-card>
```

And try to filter the data from a search box:
```html
<input
type="text"
placeholder="Enter keyword  ..."
v-model="search"
v-on:keyup="getfilteredData"
/>
```
My method for returning the filteredData is:
```javascript
getfilteredData: function() {
      this.filteredData = this.$page.posts.edges;
      let filteredDataByfilters = [];
      let filteredDataBySearch = [];
      if (this.search !== "") {
        filteredDataBySearch = this.filteredData.node.filter(
          obj => obj.name.indexOf(this.search.toLowerCase()) >= 0
        );
        this.filteredData = filteredDataBySearch;
      }
    }
```

I tried to set up a [jsfiddle](https://jsfiddle.net/3n8yeqmz/) to play with the case without the graphql from gridsome (using an example from https://jsfiddle.net/paulsandip2110/23wws1ac/14/).

**Comment by hjvedvik** [comment]
Computed properties in a Vue component should return your filtered data like this:

```js
export default {
  data () {
    return {
      search: ''
    }
  },
  computed: {
    filteredData () {
      return this.$page.posts.edges.filter(edge => {
        return edge.node.name.indexOf(this.search.toLowerCase()) >= 0
      })
    }
  }
}
```
With this computed property, there is no need to call a `getfilteredData` method on `keyup`. The reactivity system in Vue will automatically re-evaluate `filteredData` and re-render your template when `search` is changed :)

**Comment by thomas-evensen** [comment]
That worked. Thanks!

**Comment by darrylmorley** [comment]
Hi, can this be ammended to filter posts from allPages?
