### ISSUE TITLE
Accessing Arrays within arrays.

### ISSUE THREAD

**Issue by cartoonmadrasah** [gridsome/gridsome#588]
I guess I am not even sure what the proper title should be. But here is my problem. I am using [Vue-Gallery](https://www.npmjs.com/package/vue-gallery) to display images in a lightbox. Everything is running fine, except I am unable to display the array of images because of my graphql structure which is like this: 

![Image 1](https://user-images.githubusercontent.com/7679807/62415186-156a6580-b63f-11e9-8730-9165fd201658.png)

That is inside the array of image, it needs to display '_text' for the image path. So I am trying like this and other ways but I am unsuccessful: 

![Image 4](https://user-images.githubusercontent.com/7679807/62415216-932e7100-b63f-11e9-9991-76e4f52b4b63.png)

Should I use computed method for this, if yes then how or is there a simpler solution that I am missing. Please guide. Thank you.

**Comment by u12206050** [comment]
It seems like `images` is the array so yes a computed property would best
to extract the `_text` property.

```
computed: {
  images() {
    return this.$page.Predubai.images.map(img => img.image._text)
  }
}
```

Then on the component assign `:images="images"`

**Comment by cartoonmadrasah** [comment]
Yes, working great. Thank you so much. It solves so many of my problems. Thank you once again!
