### ISSUE TITLE
Gridsome Build Doesn't Work

### ISSUE THREAD

**Issue by andrew-gw** [gridsome/gridsome#593]
## Description

I type `gridsome build` on the example project, and it generates files without error. I try to load the contents of `/dist/` either in a browser locally, or from my server after uploading the contents via FTP. All assets are 404'ing. I thought this was a permissions issue, but I can set them all to 777 and the thing still doesn't work. The files are seemingly named correctly as it generated them.

The dev server works fine. Whatever this thing is builds is broken. There's no other help out there. I am sad and alone.

![image](https://user-images.githubusercontent.com/2128025/62571305-04983a80-b85f-11e9-8baf-6d529e4b0ef8.png)

### Steps to reproduce

1. Follow the Gridsome Getting Started instructions
2. Run `gridsome build`
3. Nothing works

### Expected result

I should see the Example Project.

### Actual result

I see a broken page with no styles or images.

### Environment

<pre><code>
Libs:
- @gridsome/cli v0.2.1
- gridsome v0.6.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.0
- Platform: Mac

Others:
Mac OS X Mojave 10.14.6
</code></pre>

**Comment by andrew-gw** [comment]
I solved this on my own after running into many walls and finding no help, which was a horrible introduction to this "stack".

For posterity / future reference, I had to set `pathPrefix` to `/gridsome` in `gridsome.config.js`, which was mentioned nowhere. Apparently the paths can't be relative for some reason.

**Comment by paolotim** [comment]
Hi Andrew, I am having the same issue but I am not sure what you mean with adding /gridsome as I have no such directory. Can you be more specific? Thanks

**Comment by kissu** [comment]
The build actually works out of the box, in a `production` environment with no additional setting needed. In `development`, it does not create any sitemap.

@andrew-gw your approach of trying to load it in some hacky `777` way is not the correct one. Btw, bashing on the stack is not helpful in any way.
You should rather join a Slack/Discord or alike and help it grow. :smile_cat: 
A bigger community will help the Stack grow (it's currently not `LAMP`-sized indeed :man_shrugging:). :wink:

**Comment by corybagozzi** [comment]
I spent some time bashing my head against the wall until I dug into the docs on configuration a bit more. https://gridsome.org/docs/config/ Gridsome assumes you are serving the site from the root of your web server so the urls get weird when it's just in a local folder. I solved this by hooking a MAMP server up to the dist folder and running it there. The pathPrefix solution might be easier but for a really low level development hobbyist (like me) this was an easy way to make it work until sent it to my actual webhost. 

This solved an issue I had with url/links and tailwind not working :)

**Comment by webmasterowi** [comment]
I'm facing the same issue, any help? look like all my url are broken and I just get 404

**Comment by jogoeire** [comment]
Having the same issue, and adding **pathPrefix: '/gridsome',** didn't work for me. 

Seems table-stakes that this should work in static folder once generated. I guess ill try this MAMP route, although if it worked I wouldn't feel confident about it working on S3 without testing that also. 

In summary, I think this should mention in the starter/docs page.
