### ISSUE TITLE
Question: How to load static assets?

### ISSUE THREAD

**Issue by stursby** [gridsome/gridsome#6]
First of all, awesome project!

So I'm trying to load a `config.yml` file but can't seem to get it to work.

I've tried a `static` dir in the root and in `/src` and then tried different path options like `~/config.yml`, `@/config.yml` and relative paths too and I can't seem to load the file.

Hopefully, this is a simple thing that I'm missing.

Thanks!

**Comment by hjvedvik** [comment]
Thank you! You can have a static folder in the next update. Will publish it within a few days.

**Comment by hjvedvik** [comment]
Gridsome v0.2 was just published. It allows you to have a `/static` folder with files which will be copied to the `/dist` folder. Hope that solves your issue.

**Comment by stursby** [comment]
@hjvedvik Awesome! Thank you very much. I'm going to close for now as this should solve my issue. Thanks!

**Comment by cdvillard** [comment]
A question about the use of the static folder: Is this just meant for specific files and not assets such as styles? I can't link to anything in the static folder using `g-image` or `g-link`, and Gridsome seems to break at the thought of accessing it for anything at compile time.

**Comment by u12206050** [comment]
@cdvillard Think of the static folder as a place where you can put pdf documents or any other resource that you only need access to once the site is built. Any resource you want Gridsome to have access to should be in your `src/assets` directory

**Comment by gustawdaniel** [comment]
It does not works. Please example or documentation.

**Comment by pierrejoye** [comment]
The static folder in the root directory of your project seems to only support only one level. Adding f.e.
static
   | _ myimg1.png
   |_ images
          |_ myimg2.png

myimg1.png will be accessible at /myimg1.png
mypng2.png will not be avaible at all using /images/myimg2.png

Also the src/assets directory fails on me, not matter if I use sub folders or not. Digging the code :)
