### ISSUE TITLE
Formatting date in GraphQL query

### ISSUE THREAD

**Issue by freshyill** [gridsome/gridsome#600]
I see lots of examples of people formatting their date in a query, like this:

```gql
post(path: $path) {
    title
    date(format: "YYYY-MM-DD")
    content
  }
```

When I attempt this, I get an error like this:

```json
{
  "error": {
    "errors": [
      {
        "message": "Unknown argument \"format\" on field \"date\" of type \"Session\".",
        "stringified": "Unknown argument \"format\" on field \"date\" of type \"Session\".\n\nGraphQL request:6:11\n5 |     id\n6 |     date(format: \"YYYY-MM-DD\")\n  |           ^\n7 |     end"
      }
    ]
  }
}
```
Do my dates need to be stored in a certain format for this to be enabled? Right now, they're just formatted like `'2019-08-10 18:36'`. I'm going to be using this with Netlify CMS, so I have complete control over this with Moment tokens.

**Comment by freshyill** [comment]
I figured this out. It's looking for ISO8601, but I don't see that this is documented anywhere.

**Comment by egrechko** [comment]
If anyone else is having this issue the solution is to make sure your date in your markdown files is based on ISO8601 standard.

It looks something like this
date: 2019-05-12
or 
date: 2019-02-28 07:16:11

if you want to add time as well.
