### ISSUE TITLE
Vuetify 2 isDark issue

### ISSUE THREAD

**Issue by cartoonmadrasah** [gridsome/gridsome#603]
Hi. I can't seem to get Vuetify (2.0) on Gridsome (0.6.7) right. I followed the instructions, added vuetify, whitelisted it in the server config and then when I place a test component, I am not seeing any colors:

![Image 1](https://user-images.githubusercontent.com/7679807/62859208-ed04fa00-bd15-11e9-8c2a-36b5eeed2acc.png)

The error in the console shows as:
Error in getter for watcher "isDark": "TypeError: this.$vuetify.theme is undefined".

On build I get this error:
![Image 2](https://user-images.githubusercontent.com/7679807/62859297-250c3d00-bd16-11e9-9b54-41beff8f4454.png)

I did some research on this issue, and they say I need to wrap <v-app> in my Default.vue . But when I am wrapping it the screen becomes totally blank.

![Image 4](https://user-images.githubusercontent.com/7679807/62859328-3ce3c100-bd16-11e9-8acf-aed135d40b6d.png)

 I also suspect it might have to do something with Vuetify 2.0 and Bootstrapping the Vuetify Object but cant seem to make it right.

![Image 7](https://user-images.githubusercontent.com/7679807/62859435-8d5b1e80-bd16-11e9-9115-d4d09e6d9730.png)

Kindly help and guide. Thank you.

**Comment by cartoonmadrasah** [comment]
Just checked Vuetify version 1.5.16 works fine but version 2.0.5 breaks (need a solution):
![Image 8](https://user-images.githubusercontent.com/7679807/62887102-088ff500-bd56-11e9-9bc1-8d98383ffd6f.png)

**Comment by cartoonmadrasah** [comment]
Ok i got it working. Here's what I did:

In Default.vue I added this code:
<script>
import Vuetify from 'vuetify'

export default {
  vuetify: new Vuetify(),
}
</script>

And for build I added this code to gridsome.server.js:

const nodeExternals = require('webpack-node-externals');

module.exports = function(api) {
  api.chainWebpack((config, { isServer }) => {
    if (isServer) {
      config.externals([
        nodeExternals({
          whitelist: [/^Vuetify/,/^vuetify/]
        })
      ]);
    }
  });
};

**Comment by DakshMiglani** [comment]
I think the right way to do this for vuetify 2 is

main.js

```vue
import DefaultLayout from '~/layouts/Default.vue'
import Vuetify from 'vuetify'
import "vuetify/dist/vuetify.min.css"

export default function (Vue, { appOptions }) {
  // Set default layout as a global component
  Vue.use(Vuetify);
  appOptions.vuetify = new Vuetify({});
  Vue.component('Layout', DefaultLayout)
}
```

layouts/Default.vue
```vue
  <v-app>
    <v-content>
      <!-- your code here -->
      <v-container fluid>
        <slot />
      </v-container>
    </v-content>
  </v-app>
```

**Comment by EmmyMay** [comment]
How do you add vuetify to gridsome

**Comment by hacknug** [comment]
> How do you add vuetify to gridsome

https://gridsome.org/docs/assets-css/#vuetify
