### ISSUE TITLE
Image path in vue plugin

### ISSUE THREAD

**Issue by thomas-evensen** [gridsome/gridsome#607]
Hi!

I'm using the [Vue LazyLoad-plugin](https://github.com/hilongjw/vue-lazyload) as my images is hosted on an external server.

I'm trying to set an animation-gif to show when images are loading. This is set in main.js.

    Vue.use(VueLazyload, {
        observer: true,
        loading: '~/assets/loading.gif'
    });

The file "loading.gif" exist in the "assets"-folder, but I get a 404-error when the site is trying to use it. 

Changing the variable to './assets/loading.gif' provides the "correct" url, but still gets a 404.

Any tips?

**Comment by hjvedvik** [comment]
The `~` alias only works with `import`, `require` and some static element attributes like `src`. You can instead have your image in the [`/static`](https://gridsome.org/docs/directory-structure#the-static-directory) folder, for example at `/static/assets/loading.gif`. Content in that folder is copied to `/dist` after build which means your image will be visible at `/assets/loading.gif` in the browser.

**Comment by thomas-evensen** [comment]
Thanks! This could be made clearer in the docs.
