### ISSUE TITLE
Multiple order on query

### ISSUE THREAD

**Issue by derevandal** [gridsome/gridsome#614]
## Summary

Collections can be sorted by multiple fields but with only one option for order.
There isn't a option to order multiple fields in a different way.

### Basic example

```
query {
  allStoreItens(
    sort: [{ by: "date" }, { by: "title" }]
    order: { "date": "DESC" }, { "title": "ASC"}
   ) {
    ...
  }
}
```

### Motivation

With this option, we be able to order all items by more recent date and the items that have same date will sorted alphabetically descending.

**Comment by hjvedvik** [comment]
You can set an order with the `sort` argument like this:

```graphql
query {
  allStoreItens(sort: [{ by: "date", order: DESC }, { by: "title", order: ASC }]) {
    ...
  }
}
```

We have probably forgotten to mention it in the docs... :)

**Comment by derevandal** [comment]
Thanks @hjvedvik!
I send a PR to fix that.
