### ISSUE TITLE
gridsome develop - uses a random port each time

### ISSUE THREAD

**Issue by amrnn** [gridsome/gridsome#615]
## Description

Each time I run `gridsome develop` it chooses a random port, I tried using the **--port** option but it made no difference (I made sure that the chosen port is not in use).

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.4
- @gridsome/cli version: 0.2.1

For Tooling issues:
- Node version: 10.15.0
- Platform:  Linux (Ubuntu 18.10)

</code></pre>

**Comment by hjvedvik** [comment]
Just noticed the same. Something broke in the latest version of `portfinder` which Gridsome use to find an available port. If you use Yarn you can downgrade with this in `package.json`:

```
{
  "resolutions": {
    "gridsome/portfinder": "1.0.21"
  }
}
```

But we'll publish a fix for the **--port** argument pretty soon to force port 8080.

**Comment by hjvedvik** [comment]
@amrnn Gridsome v0.6.8 was just published and should make the  **--port** option work as expected. You will still get a random port without it until it's fixed in `portfinder`.

**Comment by amrnn** [comment]
@hjvedvik  Awesome, thanks for the quick response.

**Comment by hjvedvik** [comment]
This has also been fixed in the latest version of `pathfinder` now, so I'm closing :)
