### ISSUE TITLE
Gridsome fails at build using AOS

### ISSUE THREAD

**Issue by jd-fillmore** [gridsome/gridsome#617]
## Description

Locally, the AOS animations work. However, when I run "gridsome build", it fails to build.

The error message I get below:

![pic](https://user-images.githubusercontent.com/36431227/63360758-f527ef80-c33c-11e9-8397-3968f633c181.jpg)

### Steps to reproduce

It's a local build and it can't publish to Netlify, because the build fails.

### Expected result

It should complete the build successfully, pushing changes live.

### Actual result

The build fails with the error attached above.

**Comment by hjvedvik** [comment]
You probably need to initialize AOS only in the browser. You can try something like this:

```js
if (process.isClient) {
  AOS.init()
}
```

**Comment by jd-fillmore** [comment]
@hjvedvik 

Works! Thank you very much.

**Comment by typerory** [comment]
I'm using @hjvedvik suggestion and my app builds. Netlify builds and publishes the app but I can't see the animations or the text for that matter. I can see it locally.

Any suggestions?
