### ISSUE TITLE
Unable to use Vue Instance Properties since Gridsome 0.3.0

### ISSUE THREAD

**Issue by Devportobello** [gridsome/gridsome#62]
## Description

Accessing Vue instance property $refs or $store in computed property of component lead to error in renderer with undefined value

### Steps to reproduce

in src/layouts/default.vue use a computed property, eg
```javascript
...,
computed: {
  userIsAuthenticated: function () {
    return this.$store.getters['user/user'] ...
```

For the $refs, you could add `ref="test"`in html and then in computed `console.log(this.$refs.test)`

### Expected result

Computed property return value fro mstore

### Actual result

[Vue warn]: Error in render: "TypeError: this.$store is undefined"

NB: was working on Gridsome <= 0.2.5

**Comment by hjvedvik** [comment]
How do you install Vuex?

And using `$refs` in a computed property should be avoided because the references are set up after the component has been rendered.

**Comment by Devportobello** [comment]
in main.js
```javascript
export default function (Vue, arg) {
  ...
  const store = new Vuex.Store({ ...

  arg.options.store = store
```

Maybe i'm wrong here ?

**Comment by hjvedvik** [comment]
The `arg.options` was renamed to `args.appOptions` in the new API :)

**Comment by Devportobello** [comment]
> And using `$refs` in a computed property should be avoided because the references are set up after the component has been rendered.

Damn, you right, thx for pointing me this
https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

But if i try to use this.$refs in method property this is not working too

**Comment by Devportobello** [comment]
solved, 

Wrapping <slot /> with a component leaving me to unexpected behavior
