### ISSUE TITLE
Ability to override titleTemplate

### ISSUE THREAD

**Issue by petethompson** [gridsome/gridsome#638]
## Summary

Presently, it seems as though it's not possible to adjust the way the site's `<title>` is generated, aside from adding a title in metaInfo. 

It would be a useful feature to be able to configure the site's title tag to appear in a different way than the default, `%s - <siteName>`

I tried to do this using titleTemplate, as described in the docs here: 
https://gridsome.org/docs/config#titletemplate. This doesn't seem to have any effect.

### Basic example

For example, instead of: `%s - <siteName>`, I might want some sites to have the title formatted as: `<siteName> | %s`

Or, a developer might like to exclude `<siteName>` from all pages aside from the home page. As it stands, this doesn't seem possible.

### Motivation

The reason for this feature request is that I'm finding this too inflexible. For SEO purposes, I might want to precisely specify the `<title>` of any given page. Or, a client might have a certain way that they'd like their page title to appear, for brand identity reasons or for some other reason.

**Comment by xhostcom** [comment]
Something like this with Vuetify?
<v-toolbar >
      <v-toolbar-title>
        <g-link to="/">{{ $static.metaData.siteName }}</g-link>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <nav class="nav">
        <g-link class="nav__link" to="/">Home</g-link>
        <g-link class="nav__link" to="/about">About</g-link>
      </nav>
    </v-toolbar>
<static-query>
query {
  metaData {
    siteName
  }
}
</static-query>

**Comment by petethompson** [comment]
After a little digging, I found that gridsome is using vue-meta to interpret that metaInfo object. After looking at the vue-meta docs for 2 minutes I saw what I was doing wrong. titleTemplate is working as expected. 

When I have a chance, I'll submit a PR for docs/head.md so other users don't run into the same wall as I just did

**Comment by veljkoza** [comment]
For anyone that is finding about this now, here is the solution if you want for example to have just your site name  in title of your index page, you need to override `titleTemplate`. By default it's `%s - siteName`, but you can override it in your page where you want to change it:
`<script>
   export default{
    metaInfo:{
    title:"",
    titleTemplate: "yourSiteName or whatever"
   }
}
</script>`
