### ISSUE TITLE
Full path of local working directory in component--home.js

### ISSUE THREAD

**Issue by yadu-ki** [gridsome/gridsome#67]
## Description

Gridsome made a file: `testproject/dist/assets/js/component--home.random.js`.
That file contains string `filePath: "/home/myname/projects/testproject/src/favicon.png"`.
I don't want deploy a file with full path of local working directory.

### Steps to reproduce

I build Gridsome project at local working directory.
```bash
$ npx -p @gridsome/cli gridsome create testproject
$ cd ./testproject/
$ npm run build
```

### Expected result

Relative path. just like `./src/favicon.png`.

**Comment by hjvedvik** [comment]
You're right, will publish a fix later today :)

**Comment by robaxelsen** [comment]
@hjvedvik did you fix this already? if so, feel free to close.

**Comment by hjvedvik** [comment]
@robaxelsen Yes, this is fixed :)
