### ISSUE TITLE
Refs for source-filesystem not building on gridsome 0.7.2

### ISSUE THREAD

**Issue by FilledStacks** [gridsome/gridsome#670]
## Description

When using the [Gridsome Starter Blog](https://github.com/gridsome/gridsome-starter-blog) and upgrading to gridsome 0.7.2 the grdisome develop & build commands fail.

I have a [filed an issue](https://github.com/gridsome/gridsome-starter-blog/issues/37) with the blog starter project as well. But I'm thinking it might be the source-filesystem.

### Steps to reproduce

1. gridsome create my-gridsome-site https://github.com/gridsome/gridsome-starter-blog.git
2. cd my-gridsome-site to open folder
3. yarn upgrade gridsome --latest
4. gridsome develop

### Expected result

Should generate the website and start up a server to test locally

### Actual result

Fails with the following log printed out.

```
Initializing plugins...
Tag > Failed to add node: Duplicate key for property id: Flutter
Tag > Failed to add node: Duplicate key for property id: Dependency Injection
Tag > Failed to add node: Duplicate key for property id: Provider
Load sources - 0.19s
Error: Cannot get field 'tags' from type 'Post'. Field does not exist.
    at ObjectTypeComposer.getField (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\graphql-compose\lib\ObjectTypeComposer.js:167:13)
    at ObjectTypeComposer.isFieldPlural (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\graphql-compose\lib\ObjectTypeComposer.js:365:23)
    at mapValues (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\nodes\index.js:260:25)
    at D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:13401:38
    at D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:2990:24)
    at mapValues (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\lodash\lodash.js:13400:7)
    at createReferenceFields (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\nodes\index.js:257:16)
    at createNodesSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\nodes\index.js:30:5)
    at createSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\graphql\createSchema.js:59:3)
    at Schema.buildSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\app\Schema.js:28:28)
    at Plugins.createSchema (D:\Code\Clients\MdkStudio\filledstacks\filledstack-webapp\website\node_modules\gridsome\lib\app\Plugins.js:93:22)
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.2
- @gridsome/cli version: 0.0.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.5.2
- Platform:  Windows

</code></pre>

**Comment by hjvedvik** [comment]
Which version of the filesystem plugin are you using?

**Comment by FilledStacks** [comment]
@hjvedvik  In the startup project cloned above it's ^0.3.0 and in my production site.

**Comment by FilledStacks** [comment]
@hjvedvik I just bumped it up to ^0.6.0 and still getting the same error. Here's the start project above's package.json

```javascript
{
  "name": "my-gridsome-site",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/plugin-google-analytics": "^0.1.0",
    "@gridsome/remark-prismjs": "^0.0.4",
    "@gridsome/source-filesystem": "^0.6.0",
    "@gridsome/transformer-remark": "^0.2.0",
    "gridsome": "^0.7.2"
  },
  "devDependencies": {
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0"
  }
}

```

**Comment by hjvedvik** [comment]
Please upgrade other Grudsome plugins you use too. Specially the Remark transformer.

**Comment by FilledStacks** [comment]
Upgrading all the plugins worked. Thanks for the help.

**Comment by Edmund1645** [comment]
I'm getting a similar problem too. I recently updated from gridsome `0.5.x` to `0.7.7` and gridsome cli to `0.3.0` but I get this error when I run gridsome develop:
`Error: Cannot query field "title" on type "Tag".`
I tried exploring the Playground and it seems like a lot of things have changed and I'm a bit lost.
This is what my query looks like on the index page:
```
query Posts($page:Int){
  post: allPost(perPage: 15, page: $page, filter: { fields: { published: {eq: true} }}) @paginate {
    pageInfo {
      totalPages
      currentPage
    }
    edges {
      node {
        id
        title
        path
        date (format: "D. MMMM YYYY")
        timeToRead
        tags {
          id
          title
          path
        }
        fields{
          description
          cover_image (width: 770, height: 380, blur: 10)
        }
        ...on Post {
            id
            title
            path
        }
      }
    }
  }
}
```
CLI version: `0.3.0`
Gridsome version: `0.7.7`
O.S: Linux
Browser: Chrome 77

If I query without `title` for tags, I get `null` in the field.

**Comment by Edmund1645** [comment]
#751

**Comment by jltxwesley** [comment]
All my plugins are upgraded to the latest version, but still having the same issue.

**Comment by LorenAmelang** [comment]
I had a similar issue:

> Error: Cannot query field "title" on type "Tag".

For other newbies, using (for example):

> npm install @gridsome/remark-prismjs

only updates partway, and didn't solve my problem. 

> npm install @gridsome/remark-prismjs@latest

got a much newer version, which worked! 

package.json has a  "dependencies" list of what might need updating. The new versions will show in the list after you build or develop.
