### ISSUE TITLE
Form input name breaks g-link navigation.

### ISSUE THREAD

**Issue by dkodeit** [gridsome/gridsome#673]
## Description

Depending on the naming of a form input, g-link navigation fails with app build. 

### Steps to reproduce
```
<form action="xyz" method="post">
<input type="hidden" name="foo" value="abc"> <<< works
<input type="hidden" name="inf_form_xid" value="abc"> <<< does not work
</form>
```
### Expected result

The value of the input name should not affect the build. Third party services may require specific names to be used.

### Actual result

After building, attempting to navigate results in the url/meta changing but fails to load the page navigating to.

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.9
- @gridsome/cli version: 0.2.2

Browser:
- [x] Chrome (desktop) version 76.0.3809.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 69.0 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version 42.17134.1.0
 
For Tooling issues:
- Node version: v10.15.1
- Platform:  windows

Others:

</code></pre>

**Comment by hjvedvik** [comment]
Hi, I can't reproduce this. It shouldn't matter what you have as a name for inputs :)

Can you check "View Page source" (not the DOM inspector) in Firefox and see if you find any HTML tag names marked in red?

**Comment by dkodeit** [comment]
This one is a bit odd to reproduce, at this point I feel confident I can rule out the initial claim of the input name causing the issue. 

The only thing that stands out when I view the source as you suggested is there are duplicate data attributes for some of the g-image tags. 
Example:

```
<noscript data-v-0bc9c927 data-v-0bc9c927>
<img src="/assets/static/theimage.f1294d6.0ffaa0a.jpg" class="g-image g-image--loaded" width="520" alt="theimage">
</noscript>
```

I ran the source through a validator and the only complaint that stood out was: 
```
Bad value for attribute “src” on element “img”: Illegal character in scheme data: space is not allowed.
```

Basically the g-image's get stuck in the blur stage, never renders. When the images do render, navigation works. I'll have to do some more testing, closing this issue for now.
