### ISSUE TITLE
Webpack alias resolvers via configureWebpack and chainWebpack in gridsome config don't work

### ISSUE THREAD

**Issue by whizkydee** [gridsome/gridsome#676]
### Steps to reproduce

1. Create a new gridsome project
2. Import `path` and add the lines below to the `gridsome.config.js` file
```js
  configureWebpack: {
    resolve: {
      alias: {
        '@saucedrip': path.resolve('../literal-sauce-drip/'),
      }
    }
  }
```
3. Start the project with `gridsome develop`

### Expected result

The aliases should be recognised and everything should work fine.

### Actual result

Gridsome yells errors saying "These dependencies were not found... To install them, you can run: npm install...".

**NOTE:** I get the same result when I try to use `chainWebpack` to merge the config objects or assign properties to the `config.resolve.alias` object directly.

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.3
- @gridsome/cli version: 0.2.1

 
For Tooling issues:
- Node version: 11.12.0
- Platform:  Mac

**Comment by whizkydee** [comment]
cc @hjvedvik

**Comment by hjvedvik** [comment]
Just tested and it seems to work as expected. You can try to move the `literal-sauce-drip` folder into the Gridsome project folder and see if that makes any difference.

**Comment by whizkydee** [comment]
Alright, I'll test that. I went ahead to use Yarn workspaces though.

Just curious: Isn't it supposed to work even if the directory is outside the gridsome root folder?

**Comment by hjvedvik** [comment]
Yes, it should. Both worked for me. Do you have a local package with a name starting with `@saucedrip/*` in your workspace? If so, then that might cause problems.

But you should be able to import local packages using the names in their `package.json` files instead of using webpack aliases when using Yarn workspaces :)

**Comment by whizkydee** [comment]
Nope. I don't have any local package starting with `@saucedrip/*`. In fact, I renamed it multiple times to ensure there wasn't some kind of conflict (excluding the `@` too considering gridsome's `@` alias).

When I was using the webpack resolver, the `literal-sauce-drip` directory didn't have an `index.js` file or a `package.json` which I don't think should be a problem at all and also because the same alias works in a `vue-cli` project.

The vue-cli project, the gridsome project and `literal-sauce-drip` are on the same level. 

And no, I'm not using Yarn workspaces with webpack aliases, that could cause conflicts.

**Comment by hjvedvik** [comment]
Ah, I misread your comment. Though you were using aliases and workspaces together... :) Workspaces is probably a better approach. Not sure why the alias didn't work for you. Might be that it would work better with `path.resolve(__dirname, '../literal-sauce-drip/')`.

**Comment by whizkydee** [comment]
Yeah, I had that from the beginning. Same result actually. I'll spin up a new project and try to reproduce.

In the meantime, mind if you share your config file? It's weird that it works for you and I doubt there's much that can be different in configuration.

**Comment by whizkydee** [comment]
Closing this as it now works in `gridsome@0.7.6`. It still doesn't work in `0.5.0`. Maybe it wasn't supported then? Also, I just noticed that I included the version of the globally installed gridsome instead of the local one in the initial issue description (my bad).

**Comment by hjvedvik** [comment]
Great! The `configureWebpack` option was added in v0.6 so that is probably why it didn't work :)
