### ISSUE TITLE
vue-remark not processing markdown within component

### ISSUE THREAD

**Issue by IHIutch** [gridsome/gridsome#677]
My assumption was that vue-remark would still process markdown within components similar to [Hugo's Shortcodes](https://gohugo.io/content-management/shortcodes/). I seem to just be getting plain text inside my new component.

Am I doing something wrong or am I misunderstanding this plugin?

**Comment by hjvedvik** [comment]
You are not doing something wrong :) Markdown inside components isn't implemented yet. But we will look into it sometime soon.

**Comment by IHIutch** [comment]
Good to know, thanks! Looking forward to it

**Comment by hjvedvik** [comment]
This should work in the latest version of `vue-remark`. Try it out when you have time :)

**Comment by IHIutch** [comment]
Awesome! Yes, looks like it is working!

Although I noticed a bug that occurs when I have some HTML in the markdown. It looks like when the HTML starts a new line, it gets replaced with <p> and then I get a "No matching end tag error"

**Example**
My markdown: 
`<sup>1</sup> Up to 16 stories may be allowed only with approval of City Planning Board as part of major site plan review.`

The error when compiling:
`<p>1</sup> Up to 16 stories may be allowed only with approval of City Planning Board as part of major site plan review.</p>`

Let me know if there is anything I can do to help :)

**Comment by hjvedvik** [comment]
Ah, I will publish a fix in a few moments :)

**Comment by hjvedvik** [comment]
Should work better if you update to 0.1.3 :)

**Comment by IHIutch** [comment]
Working 👍  Thanks! <3
