### ISSUE TITLE
[Question] gridsome.server.js

### ISSUE THREAD

**Issue by nongtiny** [gridsome/gridsome#682]
Hello, I have a question.

Is the gridsome.server.js run only one time when the server start?

If it not
Can we pass a data to this file? 

Thank you.

**Comment by hjvedvik** [comment]
Yes, it's only loaded once. What kind of data would you like to pass to it? You can pass plugin options which will be available as the second argument in the constructor.

**Comment by nongtiny** [comment]
Thank you very much :D
