### ISSUE TITLE
Create command with starters is broken

### ISSUE THREAD

**Issue by danrocha** [gridsome/gridsome#684]
## Description

When following instructions from [starters](https://gridsome.org/starters/), the command does not work as expected.

Not sure what needs to be updated, docs or code?

### Steps to reproduce

```
npm install --global @gridsome/cli
gridsome create new-site https://github.com/gridsome/gridsome-starter-blog.git
```

### Expected result

It should create a new Gridsome installation after cloning the starter repo.

### Actual result

`create.js` is inserting the value of the `starter` parameters within a Github URL:

```
// @gridsome/cli/lib/command/create.js
// line 23
const url = `https://github.com/${starter}.git`
```

And the command results, naturally, in an error:
```
❯ Clone https://github.com/https://github.com/gridsome/gridsome-starter-blog.git.git
❯ Update project package.json
❯ Install dependencies
Error: Failed to clone repository
    at Object.task (/usr/local/lib/node_modules/@gridsome/cli/lib/commands/create.js:35:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.3
- @gridsome/cli version: 0.2.3

 
For Tooling issues:
- Node version: 12.10.0  
- Platform:  Mac
</code></pre>

**Comment by hjvedvik** [comment]
Can you double-check your `@gridsome/cli` version?. It should be `0.2.3` instead of `6.10.3`.

**Comment by danrocha** [comment]
Sorry, my bad:
```
~ npm list -g @gridsome/cli

/Users/danroc/.nvm/versions/node/v12.10.0/lib
└── @gridsome/cli@0.2.3
```

**Comment by danrocha** [comment]
It seems there is a small discrepancy in the docs. If you go on the "Install Now" button on the top right corner and use the command displayed:

```
gridsome create my-project gridsome/gridsome-starter-blog
```

It works as expected. But if you miss that and follow the instructions down bellow:

```
gridsome create my-gridsome-site https://github.com/gridsome/gridsome-starter-blog.git
```

It returns the errors described above.

I would be happy to fix the docs for you, if needed.

**Comment by hjvedvik** [comment]
It works as expected when I test latest version (0.2.3). And the line you refer to doesn't exist in the published version. So it seems like you have an older version installed somewhere. Do you get the same version if you run `gridsome -v`?

**Comment by danrocha** [comment]
You are right. I had a mess up with global npm installs and nvm.
So sorry for wasting you time!!

**Comment by hjvedvik** [comment]
No problem :)

**Comment by nishantwrp** [comment]
@danrocha Can you tell how did you fix this problem. I am experiencing the same issue!

**Comment by danrocha** [comment]
@nishantwrp just make sure you have the latest version of gridsome installed in the correct place. Check what happens when you type `gridsome -v` and start from there.

**Comment by nishantwrp** [comment]
@danrocha Got the real issue. #1126 Thanks!

**Comment by dgknca** [comment]
It works when using git bash instead of command line.
