### ISSUE TITLE
Issue: I seem to have my layout wrapped in my layout trying to override App.vue...

### ISSUE THREAD

**Issue by rchrdnsh** [gridsome/gridsome#685]
So, maybe not a bug, probably me, but not sure...

Trying to override App.vue to add route transitions, but I'm getting a double layout situation going on...I'm going off of the tutorial that you just published, but it does not seem to be working properly. Here is a screen shot:

<img width="1440" alt="Screen Shot 2019-09-19 at 2 11 26 PM" src="https://user-images.githubusercontent.com/7884263/65281586-c93c8d00-dae7-11e9-98a1-deba43a78f49.png">

...and you can see that my layout has another layout inside of it, and I don't know how to remedy this situation. 

Here is my code. First, the `App.vue` file:

```vue
<template>
  <MainLayout>
    <transition name="fade">
      <router-view />
    </transition>
  </MainLayout>
</template>

<static-query>
query App {
  metadata {
    siteName
    siteDescription
  }
}
</static-query>

<script>
import MainLayout from '~/layouts/Main.vue'

export default {
  components: {
    MainLayout
  },
  metaInfo() {
    return {
      title: this.$static.metadata.siteName,
      meta: [
        {
          key: 'description',
          name: 'description',
          content: this.$static.metadata.siteDescription
        }
      ]
    }
  }
}
</script>

<style>

/*----------------------------------------------------------------
Transition Styles
----------------------------------------------------------------*/

.fade-enter-active, .fade-leave-active {
  transition-property: opacity;
  transition-duration: 0.25s;
}

.fade-enter-active {
  transition-delay: 0.25s;
}

.fade-enter, .fade-leave-active {
  opacity: 0
}

</style>

```

...and my layout file, which is called `Main.vue`:

```vue
<template>
  <div>
    <header>
      <g-link class="nav__link" to="/">Home</g-link>
      <g-link class="nav__link" to="/about/">About</g-link>
    </header>
    <main>
    <slot /> <!-- Page content will be inserted here  -->
    </main>
    <footer>
      <p>Hello People</p>
    </footer>
  </div>
</template>

<style scoped>

div {
  margin: 0;
  padding: 0;
  width: 100vw;
  height: 100vh;
  display: grid;
  grid-template-rows: 10vh 80vh 10vh;
  grid-template-columns: 100vw;
}

header {
  grid-row: 1;
  background-color: rgb(220,220,220);
}

main {
  grid-row: 2;
  background-color: rgb(200,200,200);;
}

footer {
  grid-row: 3;
  background-color: rgb(220,220,220);;
}

</style>
```

Any thoughts or pointers would be much appreciated. Thank you :-)

**Comment by tomtev** [comment]
You should not import any layout to App.vue :) You should use it as a wrapper for all other layouts. So the stuff you have in Main.vue should go in App.vue if you want it on all pages.

**Comment by rchrdnsh** [comment]
hmmmm...I’m following this tutorial, and it didn’t mention that, so maybe it should be altered?

https://gridsome.org/docs/overriding-app/

**Comment by hjvedvik** [comment]
@rchrdnsh The `src/pages/Index.vue` file is probably also wrapped in a layout component.

**Comment by rchrdnsh** [comment]
ahhhh, that got rid of the issue :-) Thank you both! 🤗

**Comment by rchrdnsh** [comment]
Mind if update the docs with some of this additional info?
