### ISSUE TITLE
Deprecation notice on source-filesystem on Gridsome 0.7.4

### ISSUE THREAD

**Issue by jimmyangel** [gridsome/gridsome#688]
## Description

After upgrading to Gridsome 0.7.4 and source-filesystem 0.6.0 I am seeing the following deprecation notice on both develop and build:

```
The route option in addCollection() is deprecated. Use templates instead.
Documentation: https://gridsome.org/docs/templates/                      
./node_modules/@gridsome/source… -filesystem/index.js:43:23
```

### Steps to reproduce

Just run develop or build

### Expected result

Clean, no deprecation output

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.4
- @gridsome/cli version: 0.2.2

Browser:
- [X ] Chrome (desktop) version 77.0.3865.75
 
For Tooling issues:
- Platform:  Mac

</code></pre>

**Comment by hjvedvik** [comment]
Which options are you passing to the filesystem plugin?

**Comment by jimmyangel** [comment]
```
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/vcards/**/*.md',
        typeName: 'VegetationCard',
        route: 'vcards/:title'
      }
    },
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/home.md',
        typeName: 'HomeData'
      }
    }
  ]
```

**Comment by hjvedvik** [comment]
The deprecation notice means that the `route` option should be moved to a `templates` config. You can read more about it by following the URL in the notice :)

**Comment by jimmyangel** [comment]
Oops, RTFM I guess... Sorry to bother you.

**Comment by hjvedvik** [comment]
No problem :)

**Comment by cco3** [comment]
To be fair, it's a little confusing, because it's not any end client code that calls "addCollection"

**Comment by hjvedvik** [comment]
@cco3 I agree. Plugins should have the possibility to add deprecation notices too. Will try to make it possible in v0.8.
