### ISSUE TITLE
internal anchor links clicked more than once causes NavigationDuplicated error

### ISSUE THREAD

**Issue by soongsta** [gridsome/gridsome#703]
## Description

Clicking an anchor on the same page twice causes the following error
NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/#bottom") is not allowed", stack: "Error↵    at new NavigationDuplicated (webpack-int…/node_modules/gridsome/app/entry.client.js:82:10)"}
message: "Navigating to current location ("/#bottom") is not allowed"

### Steps to reproduce

1. gridsome create my-gridsome-site 
2. cd my-gridsome-site 
3. Edit index.vue (copy paste large html content)
4. Near the top of index.vue put 
<pre><code>
&#x3C;a href=&#x22;#bottom&#x22;&#x3E;click here to go to bottom &#x3C;/a&#x3E;
</code></pre>

5. Near the bottom of index.vue page put 
<pre><code>
&#x3C;a id=&#x22;bottom&#x22;&#x3E;You have reached the bottom&#x3C;/a&#x3E;
</code></pre>

6. run gridsome develop 
7. click "click here to go to bottom" (this works)
8. Navigate back to top using mouse or keyboard (Ctl Home)
9. click "click here to go to bottom" again (this throws error above)

### Expected result

What should happen?
The user should be able to click anchor more than once and reach the bottom.

### Actual result

What happened.
NavigationDuplicated Error

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.9
- @gridsome/cli version: 0.2.3

Problem occurs on version 0.7.5

Browser:
- [x ] Chrome (desktop) version  76.0.3809.132
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  Windows 10

Others:

</code></pre>

**Comment by anthonyholmes** [comment]
I have a similar issue that is currently being looked into and might be related. Gridsome appears to be treating regular `<a>` tags like `<g-link>`. Adding `@click.stop` has fixed the issue for me but normal `<a>` should not be treated like `<g-link>` by IMO

**Comment by hjvedvik** [comment]
@anthonyholmes You're right and I agree with you. The behavior will probably be removed sometime before v1.0 and may be enabled by an optional config or plugin instead.

**Comment by soongsta** [comment]
Hi
Just an update on this. The error has gone away, but the a tag does not navigate to the bottom of the page.

**Comment by typerory** [comment]
> Hi
> Just an update on this. The error has gone away, but the a tag does not navigate to the bottom of the page.

@soongsta use the `@click.stop` that @anthonyholmes suggested.
