### ISSUE TITLE
Feature request: More programmatic control of template paths

### ISSUE THREAD

**Issue by ramiroazar** [gridsome/gridsome#709]
## Summary

Allow greater programmatic control of node fields when defining paths in [template options](https://gridsome.org/docs/templates/#setup-templates).

### Basic example

The `createPage` function allows the use of node fields as both [path parameters](https://gridsome.org/docs/dynamic-routing/#programmatic-dynamic-routes) and [object properties](https://gridsome.org/docs/pages-api/#create-pages-from-graphql).

Obviously `createPage` is used in a different context, so not sure about how viable this actually is, but perhaps it would be possible to make the `path` option accept a callback function?

``path: ({node}) => { return `/product/${node.slug}/reviews` }``

### Motivation

The previous work done in #53 to facilitate any node field to be used as a path parameter is great and much appreciated, thank you!

However, even though using path parameters is enough and preferable for most use cases, it is still limiting in some circumstances.

For example, it would be nice to be able to set the `path` to a URL returned by a source plugin as a node field, such as the use case described in gridsome/gridsome-starter-wordpress#19.

`path: new URL(node.link).pathname`

**Comment by hjvedvik** [comment]
The `path` option for templates can be a function :) The first argument is the node and you return a path like in your example. We have probably forgotten to document it.

**Comment by ramiroazar** [comment]
That's amazing, @hjvedvik! I've just tested this and it indeed works perfectly. Sorry, I should have have had a better look at the relevant source code. This is a really great feature, so I think it's worth documenting it. I can try to submit a pull request for [gridsome/gridsome.org](https://github.com/gridsome/gridsome.org). Thank you very much for the prompt reply!

**Comment by hjvedvik** [comment]
That would be great :) @ramiroazar
