### ISSUE TITLE
favicon.ico is throwing a 404

### ISSUE THREAD

**Issue by clorichel** [gridsome/gridsome#711]
## Description

While having a `./src/favicon.png` works like a charm by adding the relevant `rel="icon"` head links, browsers keep trying to download `favicon.ico` at the root level of the website...

This throws a 404 error, which actually downloads the 404 html, whatever its size.

### Steps to reproduce

Open your Gridsome website in a browser (say Chrome) and open the console.

### Expected result

No 404 error, because a `favicon.ico` file would be there, be it a default empty file, or the automatically `.ico`nized version of the `./src/favicon.png` file.

### Actual result

A 404 error, seen in console as :

`GET http://localhost:8080/favicon.ico 404 (Not Found)`

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.5
- @gridsome/cli version: 0.2.3

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by hjvedvik** [comment]
We can add a default icon link tag with just has an empty icon like this:
```html
<link rel="icon" href="data:,">
```
Its valid HTML5 and prevents browsers to always look for the `/favicon.ico`.

**Comment by clorichel** [comment]
Thanks! ❤️ I guess I'll close that one.
