### ISSUE TITLE
Build Error - "Field does not exist" - 'keywords' in WordPressAttachment_MediaDetails

### ISSUE THREAD

**Issue by petethompson** [gridsome/gridsome#713]
## Description

I've been working on a website using the WordPress data source for a couple months. Today, the build process to Netlify encountered an error. In the past I've been able to debug these errors, because they've been due to something on my end. This seems different.

I reverted the change I made between the previous build and this one, and the same error occurred.

I updated WordPress core on the source URL this afternoon, so that might have something to do with it.

Below is the error from the Netlify console:

```
2:16:21 PM: Error: Cannot get field 'keywords' from type 'WordPressAttachment_MediaDetails_ImageMeta'. Field does not exist.
2:16:21 PM:     at ObjectTypeComposer.getField (/opt/build/repo/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:13)
2:16:21 PM:     at ObjectTypeComposer.getFieldExtensions (/opt/build/repo/node_modules/graphql-compose/lib/ObjectTypeComposer.js:976:24)
2:16:21 PM:     at ObjectTypeComposer.extendFieldExtensions (/opt/build/repo/node_modules/graphql-compose/lib/ObjectTypeComposer.js:989:26)
2:16:21 PM:     at addFieldExtensions (/opt/build/repo/node_modules/gridsome/lib/graphql/nodes/index.js:153:25)
2:16:21 PM:     at addFieldExtensions (/opt/build/repo/node_modules/gridsome/lib/graphql/nodes/index.js:156:9)
2:16:21 PM:     at addInferredFields (/opt/build/repo/node_modules/gridsome/lib/graphql/nodes/index.js:141:9)
2:16:21 PM:     at createFields (/opt/build/repo/node_modules/gridsome/lib/graphql/nodes/index.js:113:3)
2:16:21 PM:     at createNodesSchema (/opt/build/repo/node_modules/gridsome/lib/graphql/nodes/index.js:30:5)
2:16:21 PM:     at createSchema (/opt/build/repo/node_modules/gridsome/lib/graphql/createSchema.js:60:3)
2:16:21 PM:     at Schema.buildSchema (/opt/build/repo/node_modules/gridsome/lib/app/Schema.js:28:28)
2:16:21 PM:     at Plugins.createSchema (/opt/build/repo/node_modules/gridsome/lib/app/Plugins.js:94:22)
2:16:21 PM:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to reproduce

Running `gridsome build` on a project using WordPress as the data source might work, presumably on a WordPress site with the most recent version of WordPress, 5.2.3.

### Expected result

The build normally succeeds without any issues

### Actual result

The build failed, attempting to get the 'keywords' endpoint from WordPressAttachment_MediaDetails_ImageMeta

N.B. I'm not accessing that endpoint anywhere in the project. The only endpoints I'm accessing for WordPressAttachment_MediaDetails are:
width
height

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.6
- @gridsome/cli version: 0.2.1

**Comment by hjvedvik** [comment]
You are right. Some changes in 0.7.6 caused som issued with inferred fields. We'll fix that asap :)

**Comment by petethompson** [comment]
Thanks. Definitely interested to know what caused the issues and to see your fix, so I can attempt to patch issues like this, if they come up in the future.

**Comment by hjvedvik** [comment]
The fix is in [these](https://github.com/gridsome/gridsome/commit/b4776e2cf1b219ce421f8f6eb2f098959aff6bc3#diff-5d181a4d15a6ad9fb54e5a05e695ed12R39-R44) lines. The other changes in the commit are mostly tests to ensure this doesn't happen again :)

**Comment by petrvalek** [comment]
Thank you guys for fixing this bug. It will be possible to udpate npm/yarn packages?

**Comment by hjvedvik** [comment]
The fix has been published to npm now. Hopefully without introducing new bugs.

**Comment by petethompson** [comment]
Amazing. This worked perfectly. Thanks @hjvedvik

**Comment by hacknug** [comment]
@hjvedvik break for me https://github.com/hacknug/klayaya/pull/92

**Comment by hjvedvik** [comment]
@hacknug It seems like the WordPress plugin creates a reference to a post type that hasn't been fetched. You can try to enable the `DlmDownload` post type for the REST API in WordPress. But I'll take a look at how it was handled in earlier versions.

**Comment by hacknug** [comment]
@hjvedvik tried that but now [it breaks](https://travis-ci.com/hacknug/klayaya/builds/130264780) because it's getting a 404 in `/blocks` (`"No route was found matching the URL and request method"`).

~This is weird because that definitely is the `rest_base` listed under [`types`](https://dev.nestorvera.com/klayaya/wp-json/wp/v2/types).~

Just found the culprit of that `/blocks`. For some reason either _WP REST Cache_ or _Ultimate WP REST_ (this one's been disabled for a while, only tried it out) probably tweaked that and didn't put theit cached version in there. After disabling/enabling the plugin again, `rest_base` points to `/wp-block` where the content should appear.

I guess the only gridsome issue is breaking the build when encountering a 404. This should be handled the same way 401 are, no?
