### ISSUE TITLE
Use source-graphql with prismic.io

### ISSUE THREAD

**Issue by Dansuncoin** [gridsome/gridsome#717]
Hello there !

First thing first : Gridsome is awesome !

## Summary

I was giving a try to prismic.io as a CMS for my Gridsome App.
Prismic API endpoint is available in many technology as JavaScript, Node.js, JSON but also GraphQL ([Introduction to the Prismic GraphQL API](https://prismic.io/docs/graphql/getting-started/intro-to-the-graphql-api)).

I've tried to ping the GraphQL API with the source-graphql plugin but it fails because 
> contrary to a classic GraphQL API, you need to use a GET request to query the Prismic GraphQl API.

To achieve this, you only need to set `useGETForQueries : true` when you create the [`HttpLink`](https://github.com/gridsome/gridsome/blob/b4776e2cf1b219ce421f8f6eb2f098959aff6bc3/packages/source-graphql/index.js#L61) like this : `const http = new HttpLink({ uri, useGETForQueries: true, fetch })`

So it could be great if the request methods could be an option or something ?

Edit :
It might be related to this issue : https://github.com/gridsome/gridsome/issues/116

### Basic example

```
{
  use: '@gridsome/source-graphql',
  options: {
    url: process.env.PRISMICIO_API_URL,
    fieldName: 'prismicio',
    typeName: 'prismicio',
    method: 'GET',
    headers: {
      'Prismic-Ref': process.env.PRISMICIO_REF,
      'Authorization': `Token ${process.env.PRISMICIO_API_TOKEN}`,
    }
  }
}
```

### Motivation

I think this could be good because it will avoid to create and maintain another plugin for such a slight change.
But maybe there are other consequences I don't know for now...

**Comment by hjvedvik** [comment]
@jakedohm Would you like to look at this? :)

**Comment by qdpy** [comment]
Interested ! 
Can you PM me @Dansuncoin ? quentin[at]leasy.co

**Comment by harrison-ifeanyichukwu** [comment]
there is the `fetchOptions` field, where you can set `fetchOptions.method` to **GET**

**Comment by michaelpumo** [comment]
Any movement on this? Sounds like it would be great to fix in.

**Comment by Dansuncoin** [comment]
@michaelpumo 

In fact, @alariclg create a source plugin for Prismic.io https://gridsome.org/plugins/gridsome-source-graphql-prismic and it works fine !

I've should close these issue months ago...
Best,
