### ISSUE TITLE
Path field with @gridsome/source-wordpress from v.4.0

### ISSUE THREAD

**Issue by matt88120** [gridsome/gridsome#719]
Hi, there,

i have some issue with GraphQL since @gridsome/source-wordpress 4.0. 
Path field doesn't exist anymore for custom post type. 

<pre>Error: Cannot query field "path" on type "WordPressRealisation". Did you mean "date"?

GraphQL request:86:9
85 |         title
86 |         path
   |         ^
87 |         date(format: "YYYY", locale: "fr")
    at Object.module.exports (/Applications/MAMP/htdocs/lz2019/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)
</pre>

<pre><code>
Libs:
- gridsome version: 0.7.6
</code></pre>

**Comment by hjvedvik** [comment]
Does the `WordPressRealisation` collection have a [template](https://gridsome.org/docs/templates/) configured in `gridsome.config.js`? The WordPress plugin used to add fallback routes for collections (which generated paths), but from Gridsome v0.7 only collections defined in the templates config will have a generated path.

**Comment by matt88120** [comment]
Oh yeahhhh! Thanks. 
Code below solve the problem.

`templates: {
		WordPressPlaylist: '/playlist/:slug',
		WordPressRealisation: '/realisation/:slug',
		WordPressPost: '/actualites/:slug',
    },`

**Comment by hjvedvik** [comment]
Great :)
