### ISSUE TITLE
Passing options to gridsome remark

### ISSUE THREAD

**Issue by tyrion** [gridsome/gridsome#726]
Hello, I am trying to pass options to `transformer-remark`. Specifically I would like to turn footnotes on ( https://github.com/remarkjs/remark/blob/master/packages/remark-parse/readme.md#optionsfootnotes ).

Setting it in `gridsome.config.js` does not seemto work:
```
  transformers: {
    //Add markdown support to all file-system sources
    remark: {
      // ...
      footnotes: true,
    },
```

Is this currently possible, am I missing something really stupid?
Thanks

**Comment by GoulvenC** [comment]
UP !
Is there anything new about this problem? I'm having the same problem, and I really need a solution to support the footnotes in Gridsome :/

**Comment by tmm** [comment]
wanted to chime in on this too. love using gridsome, but might need to switch to gatsby if footnotes aren't coming anytime soon.

**Comment by noxify** [comment]
added a PR to solve this :) Now we have to wait :)
