### ISSUE TITLE
CSS code missing in build

### ISSUE THREAD

**Issue by MWSolutions** [gridsome/gridsome#737]
Hi,

I use the tailwind CSS plugin and the remark-highlightjs plugin. Indevelopment the source code is highlighted, but not in the build version. After the build only used CSS classes for tailwind CSS are included which is has expected. The problem is that the CSS classes from highlight.js are not included, is this because my source is a markdown file which did not include the html tags with the neede classes (remark-highlightjs plugin converts the markdwon to html). Is there an option to include the css file of highlighjs without checking if the classes are used on the site (only for highlight.js, for tailwind CSS only used classes may be included in the build)

Thanks in advance.

**Comment by tomtev** [comment]
Try remove purge from the Tailwind plugin.
