### ISSUE TITLE
Duplicate meta properties

### ISSUE THREAD

**Issue by 108kb** [gridsome/gridsome#74]
## Description

Duplicate `meta` properties.

### Steps to reproduce

As we know Gridsome uses `vue-meta` to manage meta information. To prevent duplicate properties, we should add `vmid` key as [described](https://github.com/declandewet/vue-meta#meta-object) [here](https://github.com/declandewet/vue-meta#how-metainfo-is-resolved).

I have real world example for this, you can check it [here](https://rebase.evilfactory.id/blog/hello-world/). For source code related this issue, [available in here](https://github.com/evilfactorylabs/rebase/blob/master/src/templates/BlogPost.vue#L20-L31)

### Expected result

It should not return duplicate meta tag with same `vmid`, for example in this case is

```
<meta name='description'>
```

### Actual result

Returning duplicate tag.

```html
<meta data-vue-tag="true" vmid="description" name="description" content="enjoy our thoughts, experiments, and case studies in web technologies"/>

<meta data-vue-tag="true" vmid="description" name="description" content="We are just getting started!"/>
```

### Notes

I don't know is this `vue-meta` related issues or `gridsome`. But I don't have any issues related this
since I'm using `vue-meta` in SSR. Thanks!

**Comment by 108kb** [comment]
@hjvedvik hi, thanks! Will try it. Anyway, how to add some instruction to [this docs](https://gridsome.org/docs/head)?

**Comment by hjvedvik** [comment]
Yes, it should be some info about it on that page. I'll add it to our todo list, but feel free to create a PR if you want to.

**Comment by physcocode** [comment]
@hjvedvik I think this issue can be safely closed now, the docs are up to date
