### ISSUE TITLE
Mailto links in gridsome/vue-remark fail to compile

### ISSUE THREAD

**Issue by NickStees** [gridsome/gridsome#740]
## Description

Email links In markdown files that are processed with @gridsome/vue-remark cause build failures because I think Gridsome thinks they are relative links?

### Steps to reproduce

Using a `<email@example.com>` or `[mailto](mailto:email2@example2.com)` in markdown files causes `!!assets-loader` errors and the site fails to compile. Here is a [demo repo](https://github.com/NickStees/gridsome-bugs/blob/bug-mailto-in-md/docs/test.md)

### Expected result

Mailto/email links created

### Actual result

<pre><code>ERROR  Failed to compile with 2 errors                                                                                                                                       10:24:00 PM

These dependencies were not found:

* !!assets-loader?to=mailto%3Aemail2%40example2.com&target=_blank&rel=nofollow%20noopener%20noreferrer!mailto:email2@example2.com in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/gridsome","cacheIdentifier":"7ca0bfbb-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??ref--17-0!./node_modules/@gridsome/vue-remark/lib/loader.js??ref--17-1!./docs/test.md?vue&type=template&id=2a569395&
* !!assets-loader?to=mailto%3Aemail%40example.com&target=_blank&rel=nofollow%20noopener%20noreferrer!mailto:email@example.com in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/gridsome","cacheIdentifier":"7ca0bfbb-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??ref--17-0!./node_modules/@gridsome/vue-remark/lib/loader.js??ref--17-1!./docs/test.md?vue&type=template&id=2a569395&

To install them, you can run: npm install --save !!assets-loader?to=mailto%3Aemail2%40example2.com&target=_blank&rel=nofollow%20noopener%20noreferrer!mailto:email2@example2.com !!assets-loader?to=mailto%3Aemail%40example.com&target=_blank&rel=nofollow%20noopener%20noreferrer!mailto:email@example.com</code></pre>

### Environment

<pre><code>
Libs:
- gridsome version: 0.3.0
- @gridsome/cli version: 0.7.7

Browser:
- [ X ] Chrome (desktop) version 77
 
For Tooling issues:
- Node version: 10.15.1  
- Platform:  Windows
</code></pre>

**Comment by EldoranDev** [comment]
Looks to me like its relatedto `vue-remark`.

When using the transformer-remark directly this works fine for me.

**Comment by hjvedvik** [comment]
Yes, the `vue-remark` plugin somehow transforms it into a `g-link` component. I'll fix it.

**Comment by Al-Rozhkov** [comment]
I tested this and it works as expected with Gridsome 0.7.9
