### ISSUE TITLE
TypeError: actions.addCollection is not a function

### ISSUE THREAD

**Issue by nemanjas-shyft** [gridsome/gridsome#743]
I'm trying to connect Contentful and Gridsome, and when I add plugin in gridsome.config.js and try to run gridsome develop I am getting the next error code

TypeError: actions.addCollection is not a function
    at ContentfulSource.getContentTypes (C:\web projects\shyft\node_modules\@gridsome\source-contentful\index.js:52:15)  
    at process._tickCallback (internal/process/next_tick.js:68:7)

I'm new to Gridsome so maybe I have missed some step. 

When I remove 

module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/source-contentful',
      options: {
        space: 'SPACE_ID', // required
        accessToken: 'API_KEY', // required
        typeName: 'Contentful'
      }
    }
  ]
}

### Steps to reproduce

I have also tried to install new project Starter for Contentful and when run gridsome develop I got the same error.

**Comment by nemanjas-shyft** [comment]
My mistake, I had outdated version of gridsome, just updated package and error is gone

**Comment by marcel-fluid** [comment]
I'm new to Gridsome and Vue.js, but I'm getting this same error. 

Can anyone point me to instructions on figuring out if my version of gridsome is outdated, and how to update the package? npm update gridsome doesn't seem to work.

**Comment by tobott** [comment]
@marcel-fluid in your cli run `gridsome -v` to check your version. If it's outdated then run:
Yarn:
`yarn upgrade gridsome --latest`
npm:
`npm install gridsome@latest`
