### ISSUE TITLE
Environment Variables not working

### ISSUE THREAD

**Issue by soongsta** [gridsome/gridsome#744]
## Description

Environment variables are undefined

### Steps to reproduce

1. gridsome create test1
2. cd test1
3. start editor (we use visual code, so we type code . to start editor
4. create new file ".env.development" in same folder as gridsome.config.js
5. add line TESTAPI=123
6. save file
7. edit index.vue
8. add the following : 

```
  mounted: function() {
    console.log(process.env.NODE_ENV);
    console.log(process.env.TESTAPI);
  }
```

9 . save file
10. run project "gridsome develop"
11. View console output
12. it display 
```
development
undefined
```

### Expected result

We expected 
development
123

What should happen?

the value of TESTAPI displayed in the console

### Actual result

displays undefined

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.7
- @gridsome/cli version: 0.3.0

Browser:
- [x ] Chrome (desktop) Version 77.0.3865.90 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  windows

Others:
>
</code></pre>

**Comment by u12206050** [comment]
You have to prefix your enviroment variable with `GRIDSOME_` if you want to use it in the client side such as showing in the console. try `GRIDSOME_TESTAPI`
[ENV DOCS](https://gridsome.org/docs/environment-variables/)

**Comment by seriiserii825** [comment]
And where in documentation i can read about GRIDSOME_ ? 
https://i.imgur.com/6cS5xZb.png

Can you explain who you are writing the documentation for, for yourself?

Thanks for gridsome, i love them.

**Comment by noxify** [comment]
@seriiserii825 you can find the reference to the `GRIDSOME_` prefix in the section "Usage in the browser"

**Comment by seriiserii825** [comment]
Sorry, you are right.

**Comment by pmfeo** [comment]
Same issue here. 
I'm trying to use an Instagram token inside an axios call. 
Token is called from .env file and logs undefined, both with GRIDSOME_ prefix and without it.

Any clue? maybe some pkg missing? this is my package.json:

`{
  "name": "vallvuler-2021-gridsomewp-front-end",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "buefy": "^0.9.4",
    "bulma": "^0.9.2",
    "gridsome": "^0.7.23",
    "sass-loader": "^10.1.1",
    "vue-feather-icons": "^5.1.0"
  },
  "devDependencies": {
    "node-sass": "^5.0.0",
    "style-resources-loader": "^1.4.1",
    "vue-svg-loader": "^0.16.0"
  }
}`

Thanks in advance.
