### ISSUE TITLE
PurgeCSS + RemarkPrism Conflict

### ISSUE THREAD

**Issue by zacnomore** [gridsome/gridsome#747]
## Description

When using both the @gridsome/remark-prismjs transformer (based on these [instructions](https://gridsome.org/plugins/@gridsome/remark-prismjs)) and the gridsome-plugin-purgecss plugin. PurgeCSS is removing the prismjs css despite it being used by the code blocks in the markdown based sourced pages.

### Steps to reproduce

Checkout this branch:
https://github.com/zacnomore/portfolio/tree/demonstrate-purgecss-prismjs-conflict

`yarn gridsome build`
Navigate to dist/assets/css/0.styles.xxxx.css
Note the file size

Remove this from `gridsome.config.js
```
    {
      use: 'gridsome-plugin-purgecss'
    },
```

`yarn gridsome build`
Navigate to dist/assets/css/0.styles.xxxx.css
Note the larger file size from the prismjs styling being included

### Expected result

PurgeCSS would not remove the prismjs styles since they are used in the final generated html

### Actual result

PurgeCSS removes the prismjs styles

### Environment

<pre><code>
Libs:
@gridsome/cli v0.3.0
gridsome v0.7.7

Browser: All, none? It's not really browser related.
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.15.3
- Platform:  Mac

Others:
gridsome info
------------------------------------------------------------------------------
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - /var/folders/s0/5yvl85f918x41fd_wx9p3h1j40qvfd/T/yarn--1570759062487-0.4239502627949241/node
    Yarn: 1.17.3 - /var/folders/s0/5yvl85f918x41fd_wx9p3h1j40qvfd/T/yarn--1570759062487-0.4239502627949241/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.2
  npmPackages:
    @gridsome/plugin-sitemap: ^0.2.2 => 0.2.2 
    @gridsome/remark-prismjs: ^0.2.0 => 0.2.0 
    @gridsome/source-filesystem: ^0.6.1 => 0.6.1 
    @gridsome/transformer-remark: ^0.3.4 => 0.3.4 
    gridsome: ^0.7.7 => 0.7.7 
    gridsome-plugin-purgecss: ^1.0.12 => 1.0.12 
</code></pre>

**Comment by zacnomore** [comment]
This is rather silly, I should really be filing this with the purgecss plugin, not the remark prism plugin....

**Comment by atymic** [comment]
Curious, did you get this solved?

**Comment by zacnomore** [comment]
Unfortunately not, for the moment I pulled it out of the project. The plugin is very small though, [repo](https://github.com/brandonpittman/gridsome-plugin-purgecss)
I suspect this is an order of operation issue

**Comment by mariofriz** [comment]
As I stumbled on this while looking for a solution, I'll share what I found here.

PrismJS classes are added on client side that's why they are removed by PurgeCSS. 
By whitelisting some PrismJS classes, it works. [See more whitelisting options here](https://purgecss.com/whitelisting.html#patterns).

```js
module.exports = {
  plugins: [
    {
      use: 'gridsome-plugin-purgecss',
      options: {
        whitelistPatterns: [/token.*/, /class.*/],
        whitelistPatternsChildren: [/token.*/, /class.*/],
      }
    }
  ]
}
```

**Comment by joeelia** [comment]
I tested the code from @mariofriz and it didn't work for me, but the below did once I ran `gridsome build` I saw the expected styles.

```
module.exports = {
  plugins: [
    {
      use: 'gridsome-plugin-purgecss',
      options: {
         whitelistPatternsChildren: [/^token/, /^pre/, /^code/],
      }
    }
  ]
}
```

**Comment by LindaOjo** [comment]
GRIDSOME - just incase the above solution didn't work for some weird reason.
Try adding a safelist in your `gridsome.config.js` as shown below. It worked for me.

```
{
        use: 'gridsome-plugin-purgecss',
        options: {
          safelist: {
            greedy: [/^token/, /^pre/, /^code/, /token$/, 'pre', 'gridsome']
          },
        }
}
```
