### ISSUE TITLE
Can't define my own source-filesystem typeName? 

### ISSUE THREAD

**Issue by dhiegomaga** [gridsome/gridsome#752]
## Description

I'm using source-filesystem to query local posts in .md files, as such: 

![image](https://user-images.githubusercontent.com/25873377/66706814-366dc780-ed0e-11e9-99ac-a11c5cf87124.png)

However, the **Posts** structure doesn't have an **image** field, which I would like to use, it only has the default **Post** fields, i.e., **path, title, content**, etc. 

![image](https://user-images.githubusercontent.com/25873377/66706971-5acaa380-ed10-11e9-8ed6-fbb454e668e5.png)

Therefore, I can't add a field like image to the post, like this

![image](https://user-images.githubusercontent.com/25873377/66706989-83529d80-ed10-11e9-98de-649d8c818af8.png)

and query it without getting an error

![image](https://user-images.githubusercontent.com/25873377/66707001-b432d280-ed10-11e9-8ee4-ca8e96d7718f.png)

There doesn't seem to be a simple way to add this field, and also I can't find anywhere how to add a new typeName type to use it on local files, so that I can use a new field other than the default ones.

**Comment by CraigHead** [comment]
Can you try it as an array in your front-matter? 
```
images: [
    {
        item: ./images/DSC_3558.jpg,
        caption: 'Test Caption'
    },
    {
        item: ./images/DSC_3559.jpg,
        caption: 'Test Caption2',
        cover: true
    }
]
```

and then in your template

```
    excerpt
    images{
      item (width: 300, quality: 100)
      caption
    }
```

**Comment by dhiegomaga** [comment]
> Can you try it as an array in your front-matter?
> 
> ```
> images: [
>     {
>         item: ./images/DSC_3558.jpg,
>         caption: 'Test Caption'
>     },
>     {
>         item: ./images/DSC_3559.jpg,
>         caption: 'Test Caption2',
>         cover: true
>     }
> ]
> ```
> 
> and then in your template
> 
> ```
>     excerpt
>     images{
>       item (width: 300, quality: 100)
>       caption
>     }
> ```

Where do I put this array, exactly?

**Comment by dhiegomaga** [comment]
Any ideas? .. I strongly believe this a very basic feature, and gridsome shouldn't be so rigid with regard to the data layer, and posts, etc. 

I should be able to put different fields I wished to blog posts, like tags, visualizations, likes, etc. 

Or at the very minimum, be able to create my own data structure to use, instead of needing to use these pre-defined structures:

![image](https://user-images.githubusercontent.com/25873377/66720209-1a325f00-edd0-11e9-8d4c-a69669241263.png)

But no where in the documentation I can find a 'simple' way to do this. In fact, I only see how to apply this to data queried from API's, and not local files.

**Comment by CraigHead** [comment]
<pre>
<code>
---
title: Some Title
date: 2019-03-10
summary: Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic rerum earum quos explicabo suscipit maxime iste qui nihil. Reiciendis asperiores minus necessitatibus
tags: ['photo', 'album', 'test']
images: [
    {
        item: ./images/DSC_3558.jpg,
        caption: 'Test Caption'
    },
    {
        item: ./images/DSC_3559.jpg,
        caption: 'Test Caption2',
        cover: true
    }
]
---

Blah blah blah. This is the content of your post, etc. 🎉🙌
</code>
</pre>

You can have one image in the array. Or you can just add your images to .md directly using the markdown image syntax but you won't be able to query that data in GraphQL (I believe). I personally wanted more metadata associated with each image which is why I broke mine into an object graph array. 
Btw, you're not stuck with the structures that were shipped with the quick starts. You should check out the collections and templates sections in the gridsome docs. You can invent your own as see fit.

**Comment by hjvedvik** [comment]
@dhiegomaga Also, you need to restart `gridsome develop` after adding new fields to your frontmatter. Gridsome currently only generates the GraphQL schema on startup (but that might change when Gridsome is ready for a v1.0 release).

**Comment by dhiegomaga** [comment]
> @dhiegomaga Also, you need to restart `gridsome develop` after adding new fields to your frontmatter. Gridsome currently only generates the GraphQL schema on startup (but that might change when Gridsome is ready for a v1.0 release).

Indeed, after restarting it I was able to query the field...

**Comment by Al-Rozhkov** [comment]
Looks like this one can be closed. Lets keep the issue queue lean. @dhiegomaga please reopen if you still have any questions.
