### ISSUE TITLE
g-image incorrect crop dimensions

### ISSUE THREAD

**Issue by russellbrown** [gridsome/gridsome#759]
Thank you for the fantastic project. There is just a little issue I'm running into with image cropping...

### Description

g-image seems to apply the wrong crop dimensions when the source image is smaller than the desired one.

### Steps to reproduce

Using a source image of **200x300**, try to output a square of **400x400**:

`<g-image src="~/assets/source.jpg" width="400" height="400"></g-image>`

### Expected result

We should get a **400x400** crop (or at least **200x200** if g-image is deliberately limiting to source dimensions).

### Actual result

But we actually get a **200x400** crop, i.e. g-image is respecting the desired height - even though it is larger than the source height - but is limiting the width to the source width, resulting in a very tall rectangle.

However when you open the image in a new browser tab (in develop mode) and manually change the URL from `?width=200&height=400` to `?width=400&height=400` we do get the **400x400** image that we expect.  So the crop functionality itself seems to work properly but g-image just seems to be applying the wrong dimensions.

### Environment

Gridsome v0.7.8

**Comment by hacknug** [comment]
Should have been fixed in v0.7.9. Can you confirm it works as expected now?

**Comment by russellbrown** [comment]
Works as expected in v0.7.9.  Thank you so much for fixing this!
