### ISSUE TITLE
Add search to the documentation

### ISSUE THREAD

**Issue by Haroenv** [gridsome/gridsome#76]
## Summary

Hi there, the docs seem great, but it's a bit hard to find what you need without searching.

This can be done with [DocSearch](https://community.algolia.com/docsearch/). I can help out if needed 🙂 

### Basic example

the function `loadSource` I'd have to know it would be in the server API docs

### Motivation

We want to be able to find things more easily.

**Comment by tomtev** [comment]
Hi @Haroenv . Any idea where I should start? :) How does DocSearch scan our pages?

**Comment by Haroenv** [comment]
it should all be explained on the page of docsearch: https://community.algolia.com/docsearch/, but the pages will be scraped once every 24h. All you will need to do on your side is to add the frontend code to add the search bar somewhere on your page

**Comment by tomtev** [comment]
I applied to the program a while ago but never got an email back.  I'm trying again now, so I will wait for them to send me the javascript snippet.

**Comment by s-pace** [comment]
👋 @tomtev 

We have replied to your request made from the gridsome address.

```html
<!-- at the end of the HEAD --> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 

<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
apiKey: 'a7400a3a94b256c5283cb05efb860fc1', 
indexName: 'gridsome', 
inputSelector: '### REPLACE ME ####', 
debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script> 
```

Please check this email if you need more information

**Comment by tomtev** [comment]
Thanks :)

**Comment by tomtev** [comment]
Added now :) Thanks for the help
