### ISSUE TITLE
Vue-Remark loads all pages unnecessarily

### ISSUE THREAD

**Issue by NickStees** [gridsome/gridsome#762]
## Description

On the homepage of a Gridsome site using vue-remark plugin I am seeing it load every markdown pages contents up even when not needed, on large sites with hundreds of markdown files this is bloating up the network requests for each page. Seems to only happen when a site is built with `gridsome build`. I don't believe its prefetching, because some pages don't even have links to that content.

### Steps to reproduce

Create a site that uses vue-remark and many markdown files. Create an almost empty homepage. Run `gridsome build` and visit the compiled index.html homepage. Open the Network tab in DevTools and inspect the network request you should see a number of `vue-remark-- .js` files loading up for each markdown file.

Repo Example: https://github.com/NickStees/gridsome-bugs/tree/markdowns-on-home

Demo Site: https://optimistic-tesla-75ad3a.netlify.com/ Which the home page does not link to any markdown files, but in the Network tab you see them loading in. 

Such as
- https://optimistic-tesla-75ad3a.netlify.com/assets/js/vue-remark--docs--area-information-md.aef5db2b.js
- https://optimistic-tesla-75ad3a.netlify.com/assets/js/vue-remark--docs--careers-md.7b3aa741.js

### Expected result

When loading a page it would not load other pages on the site. 

### Actual result

All markdown files are loaded up when not needed.

### Environment

<pre><code>
Libs:
- gridsome version: 0.3.0
- @gridsome/cli version: 0.7.8

Browser:
- [ X ] Chrome (desktop) version 77
 
For Tooling issues:
- Node version: 10.15.1  
- Platform:  Windows

**Comment by zacnomore** [comment]
Hey @NickStees I'm wondering if what you're experiencing is due to this feature? [https://gridsome.org/docs/linking/#how-it-works](https://gridsome.org/docs/linking/#how-it-works)

**Comment by NickStees** [comment]
@zacnomore No I don't believe so, the demo homepage has absolutely 0 links to any of the markdown pages https://optimistic-tesla-75ad3a.netlify.com/ it only links to the `/about/` page so that should be the only page prefetched. If you inspect source you will see every markdown page in the site has processed there is a corresponding `<link rel="prefetch" href="/assets/js/vue-remark--docs--a-eligendi-md.4e624273.js">` on the homepage. 

So it kind of pre-loads the entire website even if there isn't any links to that content.

**Comment by NickStees** [comment]
Updating to `gridsome 0.7.10` and adding `prefetch: { mask: '^$', },` to the gridsome.config.js removed all script tags corresponding to each site page. So I will close this now since you stated in #786 that in the future you will have an API for greater control.
