### ISSUE TITLE
A formatting issue

### ISSUE THREAD

**Issue by WebShapedBiz** [gridsome/gridsome#766]
## Description
I'm fetching a course description with Axios from TalentLMS API. The field is pure textarea (multiline) field, no rich text, no WYSIWYG, no markup, but it is formated as you can see in the screencast below.
Now, if I log the field in console, it looks all right, as formated in TalentLMS. In my REST API testing app, JSON is returning correctly formatted text (partially visible in the video, on the second workspace, bottom window). In Chrome DevTools also, the output is correctly formatted, visible in the video.

On the web page, however, the formatting is gone, like all spaces have been deleted and all I'm left with is a long string of text.

You can see the details in the screenshot below (sorry for few glitches, it's my graphic card issue).

### Steps to reproduce
[Video](https://youtu.be/CMlLxybZhbM)

### Environment
gridsome --version:
@gridsome/cli v0.2.3
gridsome v0.6.9

Cheers.

**Comment by courcelan** [comment]
@WebShapedBiz What you are outputting to the webpage is not HTML, but just a string. HTML will ignore/remove any line breaks `/n`. You'll need to either convert that field to markdown using some fancy stuff in `gridsome.server.js` or create a computed property and split your content up.

Here's some pseudo code that you can play around with:

```javascript
computed: {
    content () {
        return this.$page.<whatever your content prop is called>.split("\n") // or maybe "\n\n", not sure
    }
}
```

```html
<template>
<p v-for="item in content">{{ content }}</p>
</template>
```

**Comment by courcelan** [comment]
@WebShapedBiz  for questions like this, its best if you join the Gridsome Discord server and ask there! 

https://discord.gg/daeay6n

**Comment by WebShapedBiz** [comment]
Thank you very much @courcelan for your time and effort. I'll dig into your pseudo-code and I'm already on Gridsome Discord server, but that's something I've forgot :-/

Cheers.

**Comment by courcelan** [comment]
@WebShapedBiz sure thing! if you run into trouble, feel free to ping me on Discord.

**Comment by hjvedvik** [comment]
@WebShapedBiz Might also be worth trying with `white-space: pre`:

```html
<div style="white-space: pre">
  {{ $page.lmsCourse.description }}
</div>
```

**Comment by WebShapedBiz** [comment]
Thank you so much @hjvedvik, you're golden. This `white-space` thingy is new for me but it works.

**Comment by hjvedvik** [comment]
Great! Glad it worked :)
