### ISSUE TITLE
html and body tags after build

### ISSUE THREAD

**Issue by zvekov** [gridsome/gridsome#772]
After the application build, additional tags for **html** and **body** have this kind
`<html data-html-server-rendered="true" lang="ru" class="h-full" data-vue-tag="%7B%22lang%22:%7B%22ssr%22:%22ru%22%7D,%22class%22:%7B%22ssr%22:%22h-full%22%7D%7D">`

and

`<body class="font-sans" data-vue-tag="%7B%22class%22:%7B%22ssr%22:%22font-sans%22%7D%7D">`

in main.js these are strings

```
  head.htmlAttrs = { lang: 'ru', class: 'h-full' }
  head.bodyAttrs = { class: 'font-sans' }
```

Gridsome 0.7.8

**Comment by probil** [comment]
It seems to be the intendent behaviour of `vue-meta`:
https://github.com/nuxt/vue-meta/releases/tag/v2.3.0

Gridsome uses `vue-meta` which always adds `data-` attributes to track attributes on the client side has been changed. To track this data from a ssr page, the data- tag is  with a JSON encoded map.

Why it's a bug? :thinking:

**Comment by zvekov** [comment]
> 
> 
> It seems to be the intendent behaviour of `vue-meta`:
> https://github.com/nuxt/vue-meta/releases/tag/v2.3.0
> 
> Gridsome uses `vue-meta` which always adds `data-` attributes to track attributes on the client side has been changed. To track this data from a ssr page, the data- tag is with a JSON encoded map.
> 
> Why it's a bug? 🤔

you're right. thanks )

**Comment by DimaO2** [comment]
//in main.js before use

export default function(Vue, { head }) {
  // Set default layout as a global component
  Vue.component("Layout", DefaultLayout);
  head.htmlAttrs = { lang: "ru", class: "h-full" };
}
