### ISSUE TITLE
Error installing Sharp on FreeBSD v12.0 + Node 10 and 12

### ISSUE THREAD

**Issue by jhfoo** [gridsome/gridsome#783]
## Description
Received `fatal error: 'vips/vips8' file not found` running `npm install` manually after `gridsome create app`. Auto module installation also failed.

### Steps to reproduce
- In FreeBSD v12.0 with Nodejs v10
- Exec `gridsome create myapp` (message will appear asking to install manually)
- Exec `npm install` in myapp/
- Error message shows up trying to build Sharp 0.22.1

### Expected result
Installation completes susccessfully.

### Actual result
Error log
```
> sharp@0.22.1 install /usr/home/app/ihazcodez3/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp BSD/SunOS systems require manual installation of libvips >= 8.7.4
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gmake: Entering directory '/usr/home/app/ihazcodez3/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
warning: unknown warning option '-Wno-cast-function-type'; did you mean
      '-Wno-bad-function-cast'? [-Wunknown-warning-option]
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
```

### Environment
```
 System:
    OS: freebsd
    CPU: (4) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
```

**Comment by zacnomore** [comment]
Hello @jhfoo, on the third line of output in your error log it looks like it may be presenting a solution.
`ERR! sharp BSD/SunOS systems require manual installation of libvips >= 8.7.4`

Have you attempted to manually install libvips?

**Comment by jhfoo** [comment]
Yeah the package is installed
```
app@dev1 ~ %pkg info | grep vips                              
vips-8.7.4_9                   Free image processing system
```
Looking at the logs
```
ERR! sharp BSD/SunOS systems require manual installation of libvips >= 8.7.4
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
```
It looks like somehow the installed vips package isn't recognized.

**Comment by zacnomore** [comment]
Hey, I have two idears for you!
Looking at the documentation for the library, I see there's a [bug that affects FreeBSD's install process](http://sharp.pixelplumbing.com/en/stable/install/#freebsd), perhaps this is the issue?

This isn't a solution but more of a stopgap. I'm seeing a similar issue [over here in the sharp repo](https://github.com/lovell/sharp/issues/1407) so perhaps using an older version of gridsome would use an older version of sharp and fix the issue!

**Comment by jhfoo** [comment]
> Hey, I have two idears for you!
> Looking at the documentation for the library, I see there's a [bug that affects FreeBSD's install process](http://sharp.pixelplumbing.com/en/stable/install/#freebsd), perhaps this is the issue?

Yeah I tried that and didn't work. The issues seem to be rather old.

> This isn't a solution but more of a stopgap. I'm seeing a similar issue [over here in the sharp repo](https://github.com/lovell/sharp/issues/1407) so perhaps using an older version of gridsome would use an older version of sharp and fix the issue!

Holy cow installing sharp@0.20.8 on node 10 (not 12) was successful! I note the vips detection log entry:
```
info sharp Detected globally-installed libvips v8.7.4
```

So the latest shap version that works is 0.22.1. The versions after that (0.23.0 onwards) do not detect libvips. 

Thanks @zacnomore !
