### ISSUE TITLE
TypeError: app.pages.data is not a function

### ISSUE THREAD

**Issue by drinkmorewaters** [gridsome/gridsome#788]
On gridsome serve there is an issue randomly where the whole thing will crash and not be able to run. It happened once when changing the name of a pages file (changing back seemed to stop it) and then later when changing some div's in a component.

I have removed all modules and reinstalled, i have updated NPM and all tooling, i made sure postcss-svgo was updated. Still get the same error "app.pages.data is not a function"

Gridsome develop gives:
```
Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.02s
Create pages and templates - 0.03s
Generate temporary code - 0.03s
Bootstrap finish - 0.79s
TypeError: app.pages.data is not a function
    at createRoutes (/Users/computer/Downloads/my-gridsome-site/node_modules/gridsome/lib/serve.js:57:34)
    at module.exports (/Users/computer/Downloads/my-gridsome-site/node_modules/gridsome/lib/serve.js:29:18
```

Gridsome build gives:

```Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.03s
Create pages and templates - 0.04s
Generate temporary code - 0.03s
Bootstrap finish - 2.32s
Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined
    at promises.push.getSvgo.optimize.then.catch.error (/Users/dell/Downloads/my-gridsome-site/node_modules/postcss-svgo/dist/index.js:95:19)```

**Comment by drinkmorewaters** [comment]
postcss-svgo had killed a lot of things [https://github.com/facebook/create-react-app/issues/7901](url)

**Comment by cfjedimaster** [comment]
Query - why was this closed? I just ran into this today. I made a new site. Did VERY little changes to it, did a build ok, then went to serve again and I've got this error.

**Comment by cfjedimaster** [comment]
Oddly, build still works fine, I just can't run the development server anymore.

**Comment by cfjedimaster** [comment]
I'm sorry - new user here - forgot it was `develop` I want, not serve!

**Comment by tomtev** [comment]
@cfjedimaster You got it sorted? :)

**Comment by cfjedimaster** [comment]
Yeah, just did `gridsome develop` instead. Sorry for the noise!

**Comment by idueppe** [comment]
But great to have this close issue... ran in the same issue :-)
