### ISSUE TITLE
Files referenced in frontmatter other than images are not moved into static sometimes

### ISSUE THREAD

**Issue by nestarz** [gridsome/gridsome#792]
👋 

## Description

Absolute path (relative to the root of the project) to files other than images (like video) in frontmatter of markdown either produce a correct object (with src, type and mimeType), or just a string, consisting of an absolute path (but relative to the root of my computer here). I don't know when or why it produce either of these results.

### Steps to reproduce

---
date: 2019-11-01T00:47:40Z
release_date: 2019-11-01T00:47:40Z
media_type: none
title: Step in the Arena
description: Step in the Arena - Graffiti Walls is an alternative live art gallery
  in Eindhoven open 24/7
main_media: '/content/images/graffiti.mp4'' // this will make a wrong absolute path string and will not move the asset into the static folder OR sometimes a valid object
main_external_video: ''
thumbnail: "/content/images/graffiti-1.jpg" //this will make an object and move the image inside static folder

---

### Expected result

See my video inside the static folder when referencing it inside my frontmatter and see an object when querying with GraphQL.

### Environment
My repo:
https://github.com/howtolivetogether/web

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.11.0 - ~/.nvm/versions/node/v12.11.0/bin/node
    Yarn: 1.19.0 - ~/.nvm/versions/node/v12.11.0/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 13.0.2
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.9 => 0.7.9 

🙏

**Comment by nestarz** [comment]
Ok, so don't ask me why, but I just added this line 

`value === "the absolute path of my file relative to the computer" && console.log(value, mimeType);`

Inside https://github.com/gridsome/gridsome/blob/master/gridsome/lib/graphql/types/file.js

And now I have my object.... Something is wrong, but I can't tell where ! Cache ? I emptied it before, and it wasn't working either. Do you guys can point me out where I'm wrong or if it is a bug worth investigate ?

**Comment by hjvedvik** [comment]
I've done some debugging and think I have managed to fix it :) Absolute paths were not resolved correctly if the project folder contained an extension. For example, `/projects/howtolivetogether` worked, while `/projects/howtolivetogether.com` did not.

**Comment by nestarz** [comment]
Thanks, closing for now, I don't manage to reproduce the error since I changed some content of my posts. You do a fantastic work, thanks again :)
