### ISSUE TITLE
using source-graphql with Postgraphile: Error: contains multiple types named "Query"?

### ISSUE THREAD

**Issue by danrocha** [gridsome/gridsome#794]
## Description

When using @gridsome/source-graphql with a schema generated by [Postgraphile](https://www.graphile.org/postgraphile/introduction/), it returns the error:

```
Error: Schema must contain uniquely named types 
          but contains multiple types named "Query".
```

### Steps to reproduce

Public repo: https://github.com/danrocha/tfa-gridsome

My `source-graphql` plugin config:
```js
    {
      use: '@gridsome/source-graphql',
      options: {
        url: 'https://api.theforeignarchitect.com/graphql',
        fieldName: 'buildings',
        typeName: 'buildingType',
      },
    },
```
Snippet from my Schema:

```gql
"""
The root query type which gives access points into the data universe.
"""
type Query implements Node {
  """
  Exposes the root query type nested one level down. This is helpful for Relay 1
  which can only query top level fields if they are in a particular form.
  """
  query: Query!
  """
  The root query type must be a `Node` to work well with Relay 1 mutations. This just resolves to `query`.
  """
  id: ID!
  """
  Fetches an object given its globally unique `ID`.
  """
  node(
    """
    The globally unique `ID`.
    """
    id: ID!
  ): Node

(...)
```
The full schema is here:
https://gist.github.com/danrocha/453e5f29d0800af083bc49431345df49#file-schema-gql

I believe this `type Query` declaration might be causing the issue?
If so, couldn't this be solved by the plugin's namespacing?

### Environment
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    @gridsome/source-graphql: ^0.1.0 => 0.1.0
    @gridsome/vue-remark: ^0.1.7 => 0.1.7
    gridsome: ^0.7.0 => 0.7.8
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by danrocha** [comment]
I since then moved away from accessing the postgraphile server directly. 
So I am closing this issue as it seems to be something quite specific.

**Comment by mathroc** [comment]
in case someone else finds this via google, I found a workaround on postgraphile: I disabled this plugin : graphile-build/node8plus/plugins/MutationPayloadQueryPlugin (this plugin add a `query: Query` field on mutation output payload.

I still have `query: Query` inside the schema, so I’m not sure why it works for me and not for @danrocha 


note: I already add the NodePlugin disabled
