### ISSUE TITLE
404 page for templates routes break

### ISSUE THREAD

**Issue by yaminncco** [gridsome/gridsome#799]
## Description

this happen at gridsome.org too, if you visit for example: [https://gridsome.org/starters/fsdqs](https://gridsome.org/starters/fsdqs) the 404 page seems to work fine, but with multiple errors in the console which break the page functionality (using the search or switching theme)

### Steps to reproduce

visit https://gridsome.org/starters/fsdqs
check the console

**Comment by hacknug** [comment]
This is more of an issue for https://github.com/gridsome/gridsome.org than core. It's due to one of those components assuming some things will be available when they're not in 404 pages.

You can see how this other 404 works just fine: https://gridsome.org/blog/ffdsfdfdfsds

**Comment by zacnomore** [comment]
Moved to https://github.com/gridsome/gridsome.org/issues/353

**Comment by adamJLev** [comment]
No, I would say this is actually a bug in gridsome. Same thing is happening on my site and others, if you happen to have a Route registered for that route - and it 404's, there will be errors on the 404 page - Basically its like the 404.vue file is loaded, but also the target Template component:
https://github.com/gridsome/gridsome.org/issues/353#issuecomment-625615881

Please reopen this issue :)
