### ISSUE TITLE
Changing UI Layer

### ISSUE THREAD

**Issue by antony** [gridsome/gridsome#8]
How closely integrated is the view layer (Vue) with the backend? I'd like to use this project but I would rather use [Svelte](https://svelte.technology) as the view layer. It's very similar to Vue, so I would imagine that it would be *relatively* trivial to swap it, if the integration allows.

**Comment by hjvedvik** [comment]
Supporting other frameworks would be cool! The backend is currently depending on `vue-server-render` and `vue-router`. But are planning to not use `vue-router` on the server. I have been thinking about moving all Vue specific code into it's own package to make this possible for a while. So Gridsome would need APIs for adding a custom server renderer and a custom app for the browser.

Our priority right now is to fix bugs and make the current API stable + write docs for it, so not sure when we'll look into separating the Vue code.. but will look at it sometime later :)

**Comment by yieme** [comment]
I'd also like to use Svelte. Would it be possible to add this to the roadmap?
