### ISSUE TITLE
Right way of using the type/:id/:slug pattern

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#802]
A common url pattern is to have `type/:id/:slug` where the routing only occurs based on the `id` and not on the `slug`, so that changing the name of the page, etc. does not break the URL.

What is the right way of accomplishing this in gridsome?  My experiments with dynamic routing, redirects, etc. have all been unfruitful.

**Comment by hjvedvik** [comment]
Static routes (pages and templates) are depending on resources at a certain location, so the full path must match. You can probably do it with dynamic routing, but you won't get generated markup and will only be able to fetch data client-side. For example, you can create a collection with `/data/:id` as path to generate JSON data for each node. Then create a dynamic route `/type/:id/:slug` with a component which runs ``$fetch(`/data/${params.id}`)`` to load the static data.

**Comment by cco3** [comment]
Thanks for the suggestion!
