### ISSUE TITLE
Gridsome documentation header preventing text selection

### ISSUE THREAD

**Issue by ilicmarko** [gridsome/gridsome#804]
Not sure where I should post this but its related to the Gridsome docs site.

The headings on the dock have a huge padding and a negative margin. This is preventing some text from being copied as you can't select it.

Here is an image from the start page:

![image](https://user-images.githubusercontent.com/2827249/68541478-6d340d80-03a0-11ea-9cbf-a6cb01688674.png)

I know this is probably a hack to offset the navigation when a user has an anchor.

I guess the easiest fix is to add:

```css
position: relative;
z-index: 1;
```

**Comment by RomainLanz** [comment]
Hey @ilicmarko! 👋 

In case you want to create a PR here's the [website repository](https://github.com/gridsome/gridsome.org).

**Comment by RomainLanz** [comment]
Issue moved to [gridsome/gridsome.org #305](https://github.com/gridsome/gridsome.org/issues/305) via [**ZenHub**](https://www.zenhub.com/)
