### ISSUE TITLE
Is there a plan for refactoring Gridsome on TypeScript?

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/gridsome#817]
## Summary

TypeScript is awesome.
Because types make easier to develop.
If we can use TypeScript, which stage?

### Basic example
nothing.

### Motivation

- Easy maintenance
- Get IntelliSense https://code.visualstudio.com/docs/typescript/typescript-tutorial#_intellisense
- Be able to provide types. ref: https://github.com/tyankatsu0105/types-gridsome

**Comment by hjvedvik** [comment]
Realy good work on the ´types-gridsome´ repo @tyankatsu0105 :) I haven't used TypeScript much myself yet, but I've been looking into it for some weeks now. The plan has been to do some cleanup and refactoring in the codebase first, then use TypeScript with JSDoc. It doesn't require a build step etc. and works really well as far as I have tested :) But any feedback on the approach is appreciated.

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Thank you for your compliments!

OK! I'd like to refactor with TS💙

The first step for us is to do some cleanup and refactoring while adding JSDoc.
Then, we refactor with TS while referencing JSDoc, right?

**Comment by hjvedvik** [comment]
It would be great if you want to help out @tyankatsu0105 :)

You can take a look at the [webpack](https://github.com/webpack/webpack/blob/master/lib/webpack.js) repo to see what I mean with JSDoc. TypeScript 3.7 can also [generate types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs) from JSDoc comments in JS files.

And yes, I think the codebase needs some cleanups and refactoring and it is probably better to do it before implementing TypeScript/JSDoc. But we could create types for the plugin API now if it is possible.

**Comment by tyankatsu0105** [comment]
OK! That sounds great!
I will close this issue. Because we can understand plans about refactoring with TypeScript/JSDoc.
Thank you sharing your plan @hjvedvik  :)

**Comment by hjvedvik** [comment]
Here is an update, @tyankatsu0105. I've been using TypeScript in other projects for a few months now, and I think we'll go all-in on TypeScript in Gridsome instead of only using JSDoc. I'll start by moving all files in the `lib` folder to an `src` folder in v0.8. And then we can start to refactor the different parts to TS. I hope that makes sense. But I'm open if you have a better approach :)

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Awesome!!

I would like to actively work on the moving to typescript :)

**Comment by Mini-ghost** [comment]
Awesome
Gridsome is very easy to use, I look forward to having better TypeScript support ❤️❤️

**Comment by sebtiz13** [comment]
@hjvedvik it's a great news.

**Comment by orblazer** [comment]
Hello, i am so happy for that news !

For now i have make an gist for types nodes.
You can find types and example here : https://gist.github.com/orblazer/16ebd67fc4a5c0dd21efcc4b2b0d58ae
