### ISSUE TITLE
Make it possible to use <g-link> on external links

### ISSUE THREAD

**Issue by tomtev** [gridsome/gridsome#82]
## Summary
We should make it possible to use `<g-link>` on external links.
Many are trying to use it on external links and it does not work.

### Basic example
`<g-link href="http://outsidelink.com"/>` or `<g-link to="http://outsidelink.com"/>`

### Motivation
This will make it possible to automatically add rel="noopener" or rel="noreferrer" to external links  for a better lighthouse score.

Ref: https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by hjvedvik** [comment]
This is already implemented by @tyankatsu0105 :)
