### ISSUE TITLE
metaInfo() ignored in template file

### ISSUE THREAD

**Issue by danrocha** [gridsome/gridsome#826]
## Description

After adding a `metaInfo()` property to a template file, Gridsome seems to silently ignore it both with `develop` and `build`. 

### Steps to reproduce

Repo: https://github.com/danrocha/tfa-gridsome/

Template with `metaInfo()`:  https://github.com/danrocha/tfa-gridsome/blob/master/src/templates/Guide.vue

### Expected result

The resulting page should get the title, description, and other meta tags from the `$page` query, as demonstrated [in the docs](https://gridsome.org/docs/head/).

### Actual result

The `metaInfo()` is ignored, silently. This is one resulting page, please check the head:
https://theforeignarchitect.com/guides/singapore/

### Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3
    @gridsome/source-graphql: ^0.1.0 => 0.1.0
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0
    @gridsome/vue-remark: ^0.1.8 => 0.1.8
    gridsome: ^0.7.10 => 0.7.10
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by MrEssex** [comment]
Having looked through your code you're missing a closing brace on the <page-query> and also a comma in your list. I've created a PR in your repo so you can see this.

**Comment by danrocha** [comment]
Thanks @MrEssex .
It seems to be working now.

It would be great, though, if Vue-Meta would not fail silently, so we could debug dumb mistakes like this one more easily, no? A simple error message on build/develop would be so helpful.

Would this be a Gridsome issue or a vue-meta issue?

(Also, weirdly enough neither did my eslint plugin detected this mistake)

**Comment by hacknug** [comment]
@danrocha this is what I have in my `.eslintrc.js` and it picks up the missing closing brace issue

```js
module.exports = {
  env: {
    node: true,
    browser: true,
    es6: true,
    // es2020: true,
  },
  extends: [
    // 'eslint:recommended',
    'standard',
    'plugin:vue/essential',
    'plugin:gridsome/recommended',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly'
  },

  parser: 'vue-eslint-parser',
  parserOptions: {
    // parser: 'babel-eslint',
    ecmaVersion: 2018,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: [
    // 'vue',
    'gridsome'
  ],

  rules: {
    'comma-dangle': ['error', 'always-multiline'],
    'no-cond-assign': ['error', 'except-parens'],
  },
}
```
