### ISSUE TITLE
Icons have undefined height

### ISSUE THREAD

**Issue by emg36** [gridsome/gridsome#827]
## Description

Favicons and touch icons are being created without any height

### Steps to reproduce

Create a new gridsome project and run gridsome develop

### Expected result

`<link data-vue-tag="1" rel="icon" type="image/png" sizes="16x16" href="/assets/static/src/favicon.png?width=16&amp;key=4ce9702">`

### Actual result

`<link data-vue-tag="1" rel="icon" type="image/png" sizes="16xundefined" href="/assets/static/src/favicon.png?width=16&amp;key=4ce9702">`

### Environment

Paste the information here as shown by `gridsome info`

gridsome info just returns 
`Please run npm install to install dependencies first.`
even after running npm install.

### current work around

in node_modules > gridsome > app > head.js

```
icons.favicons.forEach(({ width, height, src: href }) => {
  var isHeight = height ? height : width
  head.link.push({
    rel: 'icon',
    type: icons.faviconMimeType,
    // sizes: `${width}x${height}`,
    sizes: `${width}x${isHeight}`,
    href
  })
})

icons.touchicons.forEach(({ width, height, src: href }) => {
  var isHeight = height ? height : width
  head.link.push({
    rel: `apple-touch-icon${icons.precomposed ? '-precomposed' : ''}`,
    type: icons.touchiconMimeType,
    // sizes: `${width}x${height}`,
    sizes: `${width}x${isHeight}`,
    href
  })
})

```

**Comment by hjvedvik** [comment]
The height should be correct in v0.7.11, which was published earlier today :)
