### ISSUE TITLE
TypeError: app.pages.data is not a function

### ISSUE THREAD

**Issue by mdobydullah** [gridsome/gridsome#828]
## Description

Pages API doesn't work in after building. I've created [programmatic dynamic routes](https://gridsome.org/docs/dynamic-routing/#programmatic-dynamic-routes).  It works in development mode but it doesn't work after building. It shows "404 Not Found".

gridsome.server.js:
```javascript
module.exports = function (api) {
    api.createPages(({createPage}) => {
        createPage({
            path: '/products/:slug',
            component: './src/templates/Product.vue'
        })
        createPage({
            path: '/categories/:slug',
            component: './src/templates/Category.vue'
        })
        createPage({
            path: '/shops/:slug',
            component: './src/templates/Shop.vue'
        })
    })
}
```

### The error

```bash
Gridsome v0.7.11

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.02s
Create pages and templates - 0.03s
Generate temporary code - 0.02s
Bootstrap finish - 1.13s
TypeError: app.pages.data is not a function
    at createRoutes (E:\Web Projects\Vuejs\my-gridsome-site\node_modules\gridsome\lib\serve.js:57:34)
    at module.exports (E:\Web Projects\Vuejs\my-gridsome-site\node_modules\gridsome\lib\serve.js:29:18)
```

### Note

I've created a new fresh gridsome project but shows the same error.

I'm unable to make my website live due to this problem. Please check and provide me a solution. Thanks.

**Comment by hjvedvik** [comment]
Hi, the `gridsome serve` command is very unstable and only maintained occasionally. Use a tool like [`serve`](https://www.npmjs.com/package/serve) to run it locally instead.

**Comment by mdobydullah** [comment]
Thank you so much for the quick reply. From now I'll use serve. :)

**Comment by ricardov03** [comment]
@hjvedvik is it any way to replace the ```gridsome serve``` with the ```serve``` npx command?

**Comment by hjvedvik** [comment]
@ricardov03 Yeah, that could probably be a good idea :) The initial thought with the `gridsome serve` command was to serve a Node.js app with SSR etc. But we will probably implement a `node` build target for Gridsome instead. So that means that `gridsome serve` should either be removed or used for something else.
