### ISSUE TITLE
Gridsome serve failing with TypeError

### ISSUE THREAD

**Issue by eoinom** [gridsome/gridsome#830]
## Description

`gridsome serve` is giving me the following error:

> TypeError: app.pages.data is not a function
>     at createRoutes (\node_modules\gridsome\lib\serve.js:57:34)
>     at module.exports (\node_modules\gridsome\lib\serve.js:29:18)

### Steps to reproduce

Run `gridsome serve` from the command line.

### Environment

`gridsome info` just tells me to run yarn to install dependencies which I've tried, even after deleting the node_modules and cache folders but unfortunately still getting the same results.

I'm currently on gridsome v.0.7.11 and @gridsome/cli v0.2.1.

**Comment by AsterYujano** [comment]
Hello, Just to say I am running with the same error.
I have a clean & fresh install of npm / yarn,  & gridsome up-to-date.

**Comment by Tchoupinax** [comment]
Hey !

Same issue with a fresh new gridsome project and theses following versions :
```
@gridsome/cli v0.3.1
gridsome v0.7.11
node 13.1.0
npm 6.12.1
nvm 0.35.0
```

**Comment by RomainLanz** [comment]
It seems that when the PR https://github.com/gridsome/gridsome/pull/570 was merged the code of the `serve` command wasn't updated.

We are referencing not existing property on the Page instance.
I believe the fix should be quite simple, I'll see later on today if I can make one.

**Comment by sunilrana123** [comment]
Hi RomainLanz.. have you pushed the fix for this?

> It seems that when the PR #570 was merged the code of the `serve` command wasn't updated.
> 
> We are referencing not existing property on the [Page instance](https://github.com/gridsome/gridsome/blob/master/gridsome/lib/pages/pages.js).
> I believe the fix should be quite simple, I'll see later on today if I can make one.

Hi RomainLanz, have you pushed the fix for this?

**Comment by hjvedvik** [comment]
The `gridsome serve` command is still experimental and only maintained occasionally. So it is very unstable. But the plan is to have it ready for v1 with tests etc to ensure it doesn't break :)

**Comment by RomainLanz** [comment]
I haven't got time to do further troubleshooting, the easiest workaround is to serve the code using any kind of local server (since it's static assets).

**Comment by hjvedvik** [comment]
The [`serve`](https://www.npmjs.com/package/serve) package works well for serving the `dist` folder locally. The `gridsome serve` command actually has a very different use case. It will build assets for production, but won't generate any static HTML or JSON files. Instead, each route is renderer server-side when visited and data is fetched from the GraphQL endpoint.
