### ISSUE TITLE
Programmatic dynamic routes - Animation/Transition/Rendering issues

### ISSUE THREAD

**Issue by nicolaisimonsen** [gridsome/gridsome#835]
First of - this might not be a bug, it might just be me trying to learn & figure out Gridsome.
(Which is awesome by the way...)

## What's going on?

**Navigating to/between same template will not trigger transitions, nor will it trigger simple CSS animations.** However, navigating to another template works fine?

Site in action: 
https://trusting-poincare-afff69.netlify.com/
Also the repo, if you want to see what's cooking:
https://github.com/nicolaisimonsen/starwars-gridsome

## What's wrong with you?
I'm not sure.
I did however setup 2 templates programmatically with the Pages API

```
    data.wpgraphql.pages.edges.forEach(({ node, id }) => {

      createPage({
        path: `/${node.uri}`,
        component: './src/templates/Page.vue',
        context: {
          id: node.id,
          uri: node.uri,
        }
      });
    })

   ... (same for Character template)
```

1. Page.vue - Displaying WP pages data
2. Characters.vue - Displaying WP custom post type data

All content is being pulled from Wordpress and displayed correctly with page-queries.
I'm so happy with this - getting teary-eyed just thinking about it.

**However, the basic enter transition was not triggered when navigating from a page route to another page route (same with character -> character)**

```
// Default layout

      <transition name="fade" appear>
        <main>
          <slot/>
        </main>
      </transition>
```

I've added a simple animation to a component, currently present on all routes.
It should transition the color from yellow to red.

```
// OneColumn.vue (component)

mounted() {
    const column = document.querySelector('section.one-column')
    column.classList.add('active')
  }

...
  &.active {
    color: red;
    transition: 10s ease color;
  }
```

Again, that's not happening on the same template routes. The color is just red from the start. 
No transitions, no animation. The content differs, pulled in dynamically and displayed correctly however.

Can any of you guys spot the reason for it?
Or am I going about this the wrong way?

Any help is really appreciated.

**Comment by nicolaisimonsen** [comment]
@hjvedvik Ahhh, that makes sense. 😯 
Thanks a lot for helping me out. Making router-view unique/setting a key did the trick.
Also moved the layout to App.vue. Transitions are working beautifully now. 
(However, a hard refresh/page-load wont trigger a transition - I'll try to figure that out)
```
<template>
  <div>
    <Header></Header>
    <div class="layout">
      <main>
        <transition name="fade" mode="out-in">
          <router-view :key="$route.fullPath" />
        </transition>
      </main>
    </div>
  </div>
</template>
```
What am I giving up doing it this way and not mounting the layout like in the docs/starters?

Also still don't have the CSS animation. I can append classes and do animations at the end, on beforeDestroy() but not at the start/after the route has rendered. Probably need to study more Vue, obviously there's a solution for this 😏

Again, thanks for helping out!

**Comment by nicolaisimonsen** [comment]
Just need to use <transition> for components/content as well, and not just the router-view.
Works fine 😅

**Comment by yet-another-dev** [comment]
A cleaner way to force the component to re-render (that keeps it at the component level, too): 

```js
beforeRouteUpdate (to, from, next) {
    // Called when the route that renders this component has changed,
    // but this component is reused in the new route.
    // For example, for a route with dynamic params `/foo/:id`, when we
    // navigate between `/foo/1` and `/foo/2`, the same `Foo` component instance
    // will be reused, and this hook will be called when that happens.

    // Explicitly calling `next` here forces the component to re-render.

   next()
}
```

From https://stackoverflow.com/a/55999879/1971662

**Comment by nicolaisimonsen** [comment]
Thanks a lot for letting me know!
I'll def check it out even though the app is working as expected (as of this moment, anyway) 🙂

**Comment by sys99** [comment]
Hi I know this issue is closed, but I would like to leave this comment as a reference. 

If you're using the layout inside a gridsome template or a page, just add the key in the layout tag. Now the transitions trigger at every route change.

`<template>
  <my-custom-layout :key="$route.fullPath">
    
  </my-custom-layout>
</template>`

**Comment by cameronrr** [comment]
Thanks this was very helpful. I've added the key attribute to first element in 'Template.vue' instead of on the router-view or layout components which also seems to do the trick. Just in case this helps with normal optimsation of reusable components.
