### ISSUE TITLE
External links without trailing "/" don't work because gridsome tries to process them as internal links

### ISSUE THREAD

**Issue by leonardlin** [gridsome/gridsome#836]
## Description

Per documentation links that lead outside the gridsome app, should be written using the standard 
`<a href="">` 

tag.

What I observe is that the a-links don't work.

Instead an error message appears in the console, showing how gridsome tries to featch the data and treat the link as an internal link.

This happens only if the there is no trailing "/" in the link
It happens only with build apps.

### Steps to reproduce

Create a blank project
Add to the homepage a link like this:
`<a href="https://localhost/schnell-bestellung" class="btn btn-primary" rel="nofollow">Click Me</a>`

Run: npm run build

Open the page with the browser and go to the new page: https://localhost/

The page is loaded: click on the "Click Me" llink

Error is thrown.

### Comments

this does not happen when it runs on: npm run develop
It does not happen if the link has a trailing "/"

Thesis: the hostname is the same as the app hostname, therefore gridsome assumes it's an internal link.

![image](https://user-images.githubusercontent.com/5815009/69603468-0eff5f80-101b-11ea-98fa-757daa2aafa3.png)

As comparison: A link created via g-link tag has a click handler
![image](https://user-images.githubusercontent.com/5815009/69603541-4b32c000-101b-11ea-998c-f2d05113e2d3.png)

### Expected result

It will navigate to https://localhost/scnell-bestellung

Gridsome should only try to handle links that are created using <g-link> and not all <a> links.

### Actual result

Javascript error thrown:
![image](https://user-images.githubusercontent.com/5815009/69580889-c40f2900-0fd5-11ea-8d8a-7c15bf480b60.png)

### Environment

 System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmPackages:
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
    @gridsome/source-strapi: ^0.1.0 => 0.1.0 
    gridsome: ^0.7.10 => 0.7.10

**Comment by leonardlin** [comment]
@courcelan gave some good pointers.

Workaround is to add to external links an empty click-handler with "stop" propagation on it.

`<a href="https://externallink" v-on:click.stop="">Click me</a>`

that prevents the event from bubbling up to the global event handler.

**Comment by a-kriya** [comment]
Duplicate of #939.

@leonardlin A config was added from that issue to address what you're noticing. If you set `catchLinks: false` in gridsome.config.js, it'll disable this behavior. See more at #959.

**Comment by leonardlin** [comment]
@a-kriya  thanks
