### ISSUE TITLE
Error: Cannot get field 'id' from type 'Page'. Field does not exist.

### ISSUE THREAD

**Issue by sHoskens** [gridsome/gridsome#837]
## Short Description

Stuck trying to enable a file collection in NetlifyCMS with gridsome. Builds and deployment worked before with folder collections, but not with a file collection.

## Description

I'm currently quite stuck on an error related to NetlifyCMS and Gridsome. It's my first time using both systems, so I'm not ruling out I've not found a crucial piece of this puzzle in the docs.

I've successfully set up NetlifyCMS within my project, deployed it to Github Pages and wired up the authentication. This all worked quite fine while my config.yml still contained the 'posts' collection from the example on [the official guide page](https://gridsome.org/docs/guide-netlify-cms/).

However, I now wanted to change the structure of the CMS to actually adhere to the needs of my site. For this, I wanted to use a file collection as [described here](https://www.netlifycms.org/docs/collection-types/), as it seemed the best option for the static text content of the landing page I wanted to implement.

I removed the posts collection from my config.yml and changed it to this:

```
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "cms/pages/home.yml"
        fields:
          - label: "Intro"
            name: "intro"
            description: "Example"
            widget: "text"
```

My gridsome.config.js file contains has these objects in it's plugins array:

```
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'cms/pages/*.yml',
        typeName: 'Page',
      }
    },
    {
      use: `gridsome-plugin-netlify-cms`,
      options: {
        publicPath: `/admin`,
        htmlPath: 'src/admin/index.html',
      }
    },
    {
      use: `gridsome-transformer-netlify`,
      options: {
        imageKey: 'image',
        markdownKey: 'body',
      }
    }
```

Attempting to build my project using `gridsome build` now results in this (partial) error message:
```
Gridsome v0.7.11

Initializing plugins...
Load sources - 0.05s
Error: Cannot get field 'id' from type 'Page'. Field does not exist.
 at ObjectTypeComposer.getField (/Users/my.name/Documents/projects/my-project/node_modules/graphql-compose/lib/ObjectTypeComposer.js:169:13)
```

So, I added a few logs to the ObjectTypeComposer just to get a look in where exactly it is throwing this error. The relevant function with added logs:

```
  getField(fieldName) {
    const field = this._gqcFields[fieldName];
    console.log('fieldName: ', fieldName);
    console.log('field: ', field);

    if (!field) {
      throw new Error(`Cannot get field '${fieldName}' from type '${this.getTypeName()}'. Field does not exist.`);
    }

    return field;
  }
```

A partial log after running it with these console.logs in place:

```
_gqcFields:  {
  path: { type: NonNullComposer { ofType: [ScalarTypeComposer] } },
  context: { type: NonNullComposer { ofType: [ScalarTypeComposer] } }
}
fieldName:  context
field:  {
  type: NonNullComposer {
    ofType: ScalarTypeComposer {
      schemaComposer: [SchemaComposer],
      _gqType: JSON,
      _gqcSerialize: [Function: identity],
      _gqcParseValue: [Function: identity],
      _gqcParseLiteral: [Function: parseLiteral]
    }
  }
}
_gqcFields:  {
  path: { type: NonNullComposer { ofType: [ScalarTypeComposer] } },
  context: { type: NonNullComposer { ofType: [ScalarTypeComposer] } }
}
fieldName:  id
field:  undefined
Error: Cannot get field 'id' from type 'Page'. Field does not exist.
```

I started looking into what all of this means, but got lost without a proper grasp of all the moving parts here. Does anyone know what I'm doing wrong?

### Steps to reproduce

I hope the code snippets above are sufficient to reproduce. Additionaly, here are the dependencies in my package.json:

```
  "dependencies": {
    "@gridsome/source-filesystem": "^0.6.2",
    "@gridsome/transformer-remark": "^0.4.0",
    "gh-pages": "^2.1.1",
    "gridsome": "^0.7.0",
    "gridsome-plugin-netlify-cms": "^1.0.9",
    "gridsome-plugin-tailwindcss": "^2.2.27",
    "gridsome-transformer-netlify": "^1.0.3",
    "netlify-cms": "^2.9.7",
    "postcss-loader": "^3.0.0",
    "tailwindcss": "^1.1.3"
  }
```

### Expected result

A succesfull build of gridsome, ready to use the defined file collection from netlifyCMS.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 69.0.3
    Safari: 13.0.3
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0
    gridsome: ^0.7.0 => 0.7.11
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9
    gridsome-plugin-tailwindcss: ^2.2.27 => 2.2.27
    gridsome-transformer-netlify: ^1.0.3 => 1.0.3
```

**Comment by hjvedvik** [comment]
Gridsome has a built-in `Page` type in the GraphQL schema, so you need to have another type name. I'll see if we can improve the error message when there is a name conflict :)

And we might rename the built-in `Page` type in the next version to avoid this.

**Comment by sHoskens** [comment]
Thanks, that did the trick!
