### ISSUE TITLE
Redirects array in afterBuild hook always empty

### ISSUE THREAD

**Issue by gilesbutler** [gridsome/gridsome#841]
## Description

I'm trying to access the redirects array listed at [https://gridsome.org/docs/dynamic-routing/#generating-rewrite-rules](https://gridsome.org/docs/dynamic-routing/#generating-rewrite-rules). Whenever I log it out though it's empty even on a brand new install of Gridsome.

### Steps to reproduce

In `gridsome.server.js` add the following...
```js
module.exports = function (api, options) {
  api.afterBuild(({ redirects }) => {
    console.log(redirects);
  });
}
```

### Expected result

The redirects array in the afterBuild hook should container all necessary rewrite rules that should be generated.

### Actual result

The array is empty `[]`

### Environment

```
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 13.0.3
  npmPackages:
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
    @gridsome/source-datocms: ^0.2.1 => 0.2.1 
    gridsome: ^0.7.11 => 0.7.11 
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1 
    gridsome-plugin-tailwindcss: ^2.2.27 => 2.2.27 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by hjvedvik** [comment]
Only paths for dynamic pages will be added to the `redirects` array since static assets usually don't require any special server config :) Or do you create dynamic pages in your project that aren't included?

**Comment by gilesbutler** [comment]
Hey @hjvedvik, 

Thanks for the response.

Yes we're creating dynamic pages and the `redirects` array is empty. Well I assume we are as we're using the Dato plugin and creating the following templates...
```
templates: {
    DatoLandingPage: "/:slug",
    DatoArticle: "/article/:slug",
    DatoService: "/services/:slug"
  },
```
My assumption was the above created dynamic pages, is that correct?

We're only trying to use the `redirects` array because we can't get the 404 page to work in production due to [https://github.com/gridsome/gridsome/issues/834](https://github.com/gridsome/gridsome/issues/834) and we thought using the redirects array might be a work around to that issue e.g we write all the redirects to the `_redirects` file on Netlify and anything else is treated as a 404.  Because the 404 pages aren't working correctly we are starting to be penalised by Google so we are trying to find a solution.

**Comment by hjvedvik** [comment]
Template routes are dynamic routes, but not treated like dynamic pages :) I'll do some debugging and see if I can figure out why it doesn't show a 404 page. You can fix the problem temporarily by setting the path for the landing page with a function instead, like this:
```
DatoLandingPage: node => `/${node.slug}`
```

**Comment by gilesbutler** [comment]
Ahh ok that makes sense. Thanks @hjvedvik setting the path with a function works 👌I've set it on all of the templates because incorrect child routes on a service for example weren't working either e.g `/services/sddsfsd` would try and return a service instead of a 404. But setting it with a function instead works! Thank you!
```
templates: {
    DatoLandingPage: node => `/${node.slug}`,
    DatoArticle: node => `/article/${node.slug}`,
    DatoService: node => `/services/${node.slug}`
}
```

Would you like me to close this issue and https://github.com/gridsome/gridsome/issues/834 or leave them open if you're still working on them?

**Comment by gilesbutler** [comment]
Actually I spoke too soon @hjvedvik - the 404s still don't work properly in production. I wonder if it's an issue with Netlify. I was testing them locally before by running `gridsome build` then serving them using [Superstatic](https://www.npmjs.com/package/superstatic). They even work locally with [Netlify Dev](https://www.netlify.com/products/dev/) so I'm not sure why they wouldn't be working in production. It feels like it's an issue with the router not recognising the route and serving up the index route. We're seeing some of the 404 page components load and the rest is the homepage, very strange. You can see the behaviour here: [current](https://staging--maiafinancial.netlify.com/sdfsdf) vs [expected](https://staging--maiafinancial.netlify.com/404). Thanks

**Comment by hjvedvik** [comment]
I'm not sure why the `/index.html` file is opened for missing paths. It should have been the `/404.html` file. Do you have any rewrite rules in a `netlify.toml` or `_redirects` file?

**Comment by gilesbutler** [comment]
Hey @hjvedvik yes we have the following redirects rule applied in our Netlify _redirects file:
`/* /index.html 200`
Netlify recommends you do this in their [redirect docs](https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps).
I've tested without it and the homepage works but all other routes don't load.

**Comment by gilesbutler** [comment]
Hey @hjvedvik `/* /index.html 200` was the issue. I've removed it and everything is working fine now. I still have to use the `node => `/${node.slug}` fix for the LandingPage route but that's fine. 

> I've tested without it and the homepage works but all other routes don't load.

To clarify I tested without the index.html so `/* / 200`. That loads the root route but nothing else.

Is it worth adding something to [https://gridsome.org/docs/deploy-to-netlify/](https://gridsome.org/docs/deploy-to-netlify/) to avoid any confusion for other people in the future? I'm happy to submit a PR for this.

Thanks for your help and sorry for the confusion on this end.

**Comment by hjvedvik** [comment]
Great @gilesbutler :) Yes, it would probably be good to mention it in the docs. Usually, a SPA has only one `/index.html` file, so paths must be rewritten to open that file. But Gridsome generates HTML files for every path on the site, so rewrite rules aren't necessary (except for dynamic pages).

**Comment by gilesbutler** [comment]
Thanks @hjvedvik - yep makes perfect sense now. I think my mind was in SPA mode because Gridsome uses Vue under the hood ha. I'll get this added to the docs and send through a PR :)

**Comment by gilesbutler** [comment]
Done @hjvedvik https://github.com/gridsome/gridsome.org/pull/319

**Comment by redraw** [comment]
Hey, just happen to came across this same issue. Does it make sense to use the string template syntax [as the docs explain](https://gridsome.org/docs/templates/#setup-templates) if 404 will not work properly? `path` as a function works property with a custom 404 page.

**Comment by smakinson** [comment]
Just ran into this, just wanted to verify that, since this is closed, is the function way for templates:

```
node => `/${node.slug}`
```

the official way to handle this?

**Comment by laxadev** [comment]
Hey, I was facing with the same issue. I'm not using Netlify I serve one of my websites from my own server.
So I just set the following in nginx end:
```
error_page 404 /404/index.html;
location / {
  index index.html;
  try_files $uri $uri/ =404;
}
```
Maybe this will help someone in the future.
