### ISSUE TITLE
User input like Star-rating Widget for Posts

### ISSUE THREAD

**Issue by nawalnew** [gridsome/gridsome#847]
## Summary

Its not just a Feature Request, its more a questing how to get User Inputs to a Post into Gridsome.

**I want to achieve a Star rating below each post.  But from Users, **  not me as an admin, this is easy. 
Ive searched the whole Internet to get this to work, but maybe I did not searched for the Right Keywords. 

I'm using Gridsome with Markdown and Contentful together and Hosted on Netlify. 
All working great. But I want this Feature. 

**Does someone has an Idea to get User input like a Star rating Widget or something simmilar? 
Maybe with Contentful or Plain Markup? **

Would be awesome to get a tip how to solve the Problem with Static Pages. 

Maybe something like https://staticman.net ?

**Comment by Microflash** [comment]
You can take a look at @keystonejs's [jamstack-plus](https://github.com/keystonejs/keystone-jamstack-plus) and @taniarascia's [Roll Your Own Comment System for a Static Site](https://www.taniarascia.com/add-comments-to-static-site/). Both the solutions require a backend, though.

**Comment by iam-jam** [comment]
If you're already using Netlify then you could use Netlify Functions to build some endpoints but you'll need to use another service to store the data that represents your 'stars'. Netlify have on article on this sort of thing using FaunaDB: 

https://www.netlify.com/blog/2018/07/09/building-serverless-crud-apps-with-netlify-functions-faunadb/#2-set-up-faunadb

**Comment by nawalnew** [comment]
Thank you for pointing me in the right direction. :) @iam-jam @Microflash 

I will take a closer look on that. 

i think i will post then here the Explanation if I got this to work to share this with the community. 

If no one has another Solution, please close this thread.

**Comment by zacnomore** [comment]
Closing as resolved. If you, @nawalnew, found a gridsome specific solution you'd be willing to share, please do!
