### ISSUE TITLE
Gridsome build failing with TypeError

### ISSUE THREAD

**Issue by MFukazawa** [gridsome/gridsome#849]
## Description

Gridsome build gives me the following error:

> Could not generate HTML for "/work/":
TypeError: Cannot read property 'console' of null
    at Object.<anonymous> (C:\Users\Micah\Desktop\my-gridsome-site\node_modules\vue-meta\dist\vue-meta.common.js:103:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Users\Micah\Desktop\my-gridsome-site\node_modules\vue-server-renderer\build.prod.js:1:77671
    at Object.<anonymous> (webpack:/external "vue-meta":1:0)

### Steps to reproduce

Run `gridsome build` from command line.

### Environment

 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.11 => 0.7.11
    gridsome-plugin-tailwindcss: ^2.2.26 => 2.2.26

**Comment by MFukazawa** [comment]
The site runs on localhost with no problem. I tried `npm install gridsome@latest` to no avail.

**Comment by vishnucr** [comment]
i'm getting the same error, did you find any solution @MFukazawa

**Comment by EbenOladutemu** [comment]
@vishnucr Please how did you fix this? Don't seem to get what you said. I'm still getting the same error.

**Comment by Sergix** [comment]
@EbenOladutemu If you are using [@gridsome/vue-remark](https://www.npmjs.com/package/@gridsome/vue-remark) or a similar package to load markdown files from the filesystem, switch to using [@gridsome/source-filesystem](https://gridsome.org/plugins/@gridsome/source-filesystem). [This starter project pretty much has everything you need.](https://gridsome.org/starters/gridsome-minimal-markdown-starter/)

**Comment by Sergix** [comment]
Actually, I seem to have found the issue. If you are globally loading a non-SSR compatible Vue component in `main.js`, the build will fail...

**Comment by Sergix** [comment]
https://github.com/gridsome/gridsome/issues/882
