### ISSUE TITLE
`pathPrefix` not working as expected

### ISSUE THREAD

**Issue by timothyis** [gridsome/gridsome#85]
## Description

I first deployed a monorepo including a Gridsome app, using Now, but realised that the assets were trying to load from the root path, which is expected for an app like this: https://now-examples-p1p0qbqf7.now.sh/ (note how there is one directory called `gridsome` and clicking it shows the content.)

I looked up your documentation and saw that you had [a `pathPrefix` option](https://gridsome.org/docs/config#pathprefix) so I applied that an ended up with the following deployment: https://now-examples-dkzvrgkjw.now.sh/

As you can see with the latter deployment, by clicking on `gridsome`, there is a generated second `gridsome` directory, rather than just the assets being loaded from the `gridsome` directory I had already created.

*Note*: All deployment URLs shared here have the source publically accessible if you [append `/_src` to the URL](https://zeit.co/docs/v2/deployments/concepts/special-paths/#source-view).

### Steps to reproduce

1. Generate a Gridsome application in a sub-directory of a project directory, the full steps that I took can be found here: https://github.com/zeit/now-examples/tree/master/gridsome#gridsome
2. Setup a `now.json` file in the project's root directory with the following:
```json
{
    "version": 2,
    "name": "now-examples",
    "builds": [
        { "src": "gridsome/package.json", "use": "@now/static-build" },
    ]
}
```
and add the following script to the gridsome package.json:
```json
"now-build": "yarn build"
```
3. Deploy the project with [Now](https://zeit.co/now) and realise that the assets are not correctly pointing to the sub-directory that Gridsome exists in.
4. Change the Gridsome config to have the following content:
```
module.exports = {
  pathPrefix: '/gridsome'
  plugins: []
}
```
5. Deploy again and get the duplicate directory issue

### Expected result

Gridsome should resolve assets to the directory set in the `pathPrefix` option instead of generating a duplicate directory so that monorepos can contain all Gridsome content in a single sub-directory.

### Actual result

Gridsome generated a directory with the name of the `pathPrefix` settings

**Comment by hjvedvik** [comment]
I agree that the current behavior of `pathPrefix` isn't as one would expect. Gridsome should generate files as normal directly under `dist`, and only prefix URLs for routes and assets. I'll include a fix for this in the next update  :)

**Comment by robaxelsen** [comment]
@timothyis see comment above from @hjvedvik :point_up: 

Have you tested if this works as expected in current version?
