### ISSUE TITLE
How to add a postcss plugin?

### ISSUE THREAD

**Issue by lynden-jones** [gridsome/gridsome#850]
This is more of a question than an "issue".

Has anyone figured out how to add a postcss plugin that is not included with the postcss plugin? If you can give me any hints it would be much appreciated!

I'm trying to add the rfs plugin (https://github.com/twbs/rfs) but everything I've tried doesn't seem to work.

In a vanilla vue cli project I'd just add this to the `postcss.config.js` file:

```
module.exports = {
  plugins: {
    tailwindcss: {},
    rfs: {},
    "vue-cli-plugin-tailwind/purgecss": {},
    autoprefixer: {}
  }
};
```

I've tried adding this to `gridsome.config.js`:

```
...
css: {
    loaderOptions: {
      postcss: {
        plugins: {
          rfs: {}
        }
      }
    }
  }
```

But I get the following error:

```
$ gridsome develop
Gridsome v0.7.11

Initializing plugins...
Load sources - 7.7s
Create GraphQL schema - 0.1s
Create pages and templates - 0.07s
Generate temporary code - 0.05s
Bootstrap finish - 9.92s
TypeError: (postcss.plugins || []).concat is not a function
    at applyLoaders (~project/node_modules/gridsome/lib/webpack/createBaseConfig.js:298:44)
    at createCSSRule (~project/node_modules/gridsome/lib/webpack/createBaseConfig.js:271:5)
    at module.exports (~project/node_modules/gridsome/lib/webpack/createBaseConfig.js:150:3)
    at module.exports (~project/node_modules/gridsome/lib/webpack/createClientConfig.js:8:18)
    at Compiler.resolveChainableWebpackConfig (~project/node_modules/gridsome/lib/app/Compiler.js:23:25)
    at createWebpackConfig (~project/node_modules/gridsome/lib/develop.js:107:39)
    at module.exports (~project/node_modules/gridsome/lib/develop.js:28:31)
```

**Comment by nawalnew** [comment]
Hey, 
you use Tailwind as i see in your Config. 

Than you dont need to add a seperate PostCSS Plugin. Its already built in.

https://www.npmjs.com/package/gridsome-plugin-tailwindcss

Just add this to your Gridsome config.
`modules.exports = {
  plugins: [
    {
      use: 'gridsome-plugin-tailwindcss',
      options: {
        tailwindConfig: './some/file/js',
        purgeConfig: {},
        presetEnvConfig: {},
        shouldPurge: true,
        shouldImport: true,
        shouldTimeTravel: true,
        shouldPurgeUnusedKeyframes: true,
      }
    }
  ]
}`

Let me know if you need further assistance

**Comment by Microflash** [comment]
The error itself tells you that `postcss.plugins` is an array and you should be adding your plugins in the array. 

Try the following:

```js
const rfs = require('rfs/postcss')

// and then

css: {
  loaderOptions: {
    postcss: {
      plugins: [
        rfs()
      ]
    }
  }
}
```

**Comment by lynden-jones** [comment]
Awesome, thank you @Microflash ! 

I thought that I had tried every possible combination of things but apparently not!
