### ISSUE TITLE
Using <g-image /> in a Contentful Rich Text Block?

### ISSUE THREAD

**Issue by Polcius** [gridsome/gridsome#854]
## Summary

So, I am using Contenful's Rich Text renderer to query blog posts, following the docs. If use <img /> it works and loads the asset, but not if I use <g-image />.

### Basic example
```
methods: {
    richTextToHTML(content) {
      return documentToHtmlString(content, {
        renderNode: {
          [BLOCKS.EMBEDDED_ASSET]: node => {
            return `<g-image width="200" height="200" quality="70" src="${node.data.target.fields.file.url}" alt="${node.data.target.fields.title}" />`;
          }
        }
      });
    }
  },
```

### Motivation

Is it possible? I have tried changing multiple values but no luck so far. Regards.

**Comment by tomtev** [comment]
It's currently not possible, but will be possible in the future with a GraphQL extension plugin :)
