### ISSUE TITLE
Routing working on local but not on Netlify

### ISSUE THREAD

**Issue by 0xantman** [gridsome/gridsome#857]
## Description
Hello, i have build a multilingual website for a client, routing is working on local but not on Netlify my route folder structure for pages are:

```
/pages
     /en/index.vue
     index.vue
```
Additional info:

Router is working after this step when i go to https://5de83978a05857000eb4e6d5--lagranfamilia.netlify.com/en/contact-success and go back with button, after go back nav link to EN and ES are working as expected.

i'am using scoped layout for every index.vue.
I'am using bootstrap vue so urls are `<b-dropdown-item to="/en/">EN</b-dropdown-item>`
at this moment i'am using `document.location.replace("/en")` forcing the page to reload is working but not efficient.

### Steps to reproduce

got to:
https://5de83978a05857000eb4e6d5--lagranfamilia.netlify.com/
click on dopdown button lang
select EN

### Expected result

When user click on English button i expect a navigation to https://5de83978a05857000eb4e6d5--lagranfamilia.netlify.com/en showing the website in english.

### Actual result

When i click on English button only the url is changing but nothing happen, the page is the same but i lost JS interactivity (Dropdown not working, button not responding...)

### Environment

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 53.0
    Safari: 13.0.3
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.0 => 0.7.11 
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9

**Comment by tomtev** [comment]
You're using some JS that are not SSR compatible. I see this error: "Failed to execute 'querySelector' on 'Document': '#' is not a valid selector." Remember to have all scripts in mounted() and not created. Or wrap the component in <client-only>

**Comment by 0xantman** [comment]
Woow that's true!! Thank your is now working!
