### ISSUE TITLE
Accessing website with wrong path routing doesn't work after page 404 loads

### ISSUE THREAD

**Issue by sys99** [gridsome/gridsome#858]
Hello I'm starting with Gridsome and was migrating a project when I found the following issue.

## Description

Accesing a website with wrong path by typing in the browser's address bar
Page for error 404 is loaded but routing doesn't work.

 I thought that there was something wrong with my project so I created a new one with the gridsome CLI and just added a 404.vue file and a link to an inexistent page in the example menu that is created. And it happened again. Thank you for your help!. 

### Steps to reproduce
https://bancoazul.sysg9.com/about/ 
Loads correctly and router works without problems

Access this page from  browser's address bar
https://bancoazul.sysg9.com/abuot/
Loads the page for 404 and routing doesn't work, path in address bar is updated when clicking links in the menu.

When the user enters the site with a correct path and them  clicks a link to a page that doesn't exist, "Abuot(error 404)" routing works without problems.

### Expected result

When accesing a site with a wrong path, page 404 should load and Links in menu(routing) should work properly and pages must change.

### Actual result
When accesing a site with a wrong path, page 404 loads, but routing doesn't work when clicking links in the menu, the path is updated in the address bar but the error 404 page is always displayed.

### Environment

Centos 7
nginx 1.17.6
Gridsome 0.7.0

**Comment by tomtev** [comment]
Where do you host this? This only works on web hosts that supports a 404.html  file. Like Netlify and Zeit.

**Comment by sys99** [comment]
> Where do you host this? This only works on web hosts that supports a 404.html file. Like Netlify and Zeit.

Hi I'm hosting it in a Vultr VM.
Is running centos 7 and I installed nginx 1.1.7.6.

So it probably is a nginx configuration problem? Thank you!.

**Comment by sys99** [comment]
To "fix" because i don't think is a real fix but will do for now is that in the 404.vue file I added in the mounted lifecycle hook:

`
mounted(){
if (window.location.href !== "/404/") {
      window.location.href = "/404/";
}
}
`
