### ISSUE TITLE
Filter on reference field (graphql)

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#859]
Using source-filesystem to establish references, I'd like to be able to query on the fields of that reference, something like this:

`allCity(filter: { country: { population: { gt: $val } } })`

However, as it stands right now with this example, CityFilterInput has a StringQueryOperatorInput for country.

Does this make sense?  Is there something I'm missing?

**Comment by noxify** [comment]
sounds like #856 / #852

**Comment by cco3** [comment]
I think you are right.
