### ISSUE TITLE
Feature Request: Strapi | Please provide Starter version for Strapi - The Open Source Node.js Headless CMS

### ISSUE THREAD

**Issue by IamManchanda** [gridsome/gridsome#86]
I see you have Starter version for [Contentful](https://github.com/gridsome/gridsome-starter-contentful) and [Wordpress](https://github.com/gridsome/gridsome-starter-wordpress) but it will be great if you have for Strapi also because I am personally (and there will be many like me) looking for some **Node.js Headless CMS** and it should be **Open Source** and not Freemium/Premium one ...

Thanks, Harry Manchanda

**Comment by tomtev** [comment]
Hi, I agree we should have this. 

We should first make a data source plugin for Strapi and then a starter.

**Comment by IamManchanda** [comment]
@tomtev I would like to create a feature request for Netlify too as it's cheap (in what they provide) and good enough for Professional Websites such as https://www.smashingmagazine.com/

So I would like to create one for same on starter stuff ... Shall I create a new thread for that?

**Comment by cschweda** [comment]
+1 for Strapi. That would be fantastic.

**Comment by jahusa02** [comment]
+1 for Strapi!

**Comment by indiecore-fm** [comment]
+1 for Strapi!

I don't want to do it by hand anymore in nuxt lol

**Comment by IamManchanda** [comment]
cc @soupette @Aurelsicoko @lauriejim @pierreburgy for providing help/resources on Integration for Netlify!

**Comment by IamManchanda** [comment]
cc @soupette @Aurelsicoko @lauriejim @pierreburgy for providing help/resources on Integration for Strapi!

**Comment by lauriejim** [comment]
Happy to see this issue!

**Comment by Truemedia** [comment]
@IamManchanda I am a big fan of strapi after using it and have done plugins for gatsby before.

So I am going to try to port over the gatsby plugin when I get some free time one weekend.

**Comment by robaxelsen** [comment]
@Truemedia Great, and thanks! Created a separate issue for the plugin only, and assigned it to you:
https://github.com/gridsome/gridsome/issues/201

**Comment by GerhardMes** [comment]
+1 for Strapi!
and Thanks @Truemedia

**Comment by hjvedvik** [comment]
Strapi source plugin is published :) https://gridsome.org/plugins/@gridsome/source-strapi
