### ISSUE TITLE
Document use of local plugins

### ISSUE THREAD

**Issue by iam-jam** [gridsome/gridsome#863]
## Description

Documentation on plugin configuration insufficient for me to configure Gridsome to use a local plugin which is a helpful thing to know when developing a plugin.

Initially I was trying to use a path relative to `gridsome.config.js` but was getting a `Error: Cannot find module`.

`use: './plugins/my-amazing-plugin'`

After some digging through `loadConfig.js` it seems a tilde is needed to resolve to the project root.

`use: '~/plugins/my-amazing-plugin',`

**Comment by hjvedvik** [comment]
There was some documentation for it, but I can't find it now either... It seems like the "How to use plugins" page is redirected to `/plugins` instead.

Also, Gridsome should support `./` paths too. Not sure why only `~/` was implemented.

**Comment by hacknug** [comment]
> Also, Gridsome should support `./` paths too.

It does when using `require` like this: `use: require('./src/plugins/gridsome-plugin-pagination'),`
