### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by arttemiuss43** [gridsome/gridsome#88]
We should be able to specify environment specific variables that will be available in Vue components? May be something like `development.env` and `production.env` in the root of a project?

**Comment by matt-e-king** [comment]
Or maybe Gridsome can fall inline with Vue CLI 3:
https://cli.vuejs.org/guide/mode-and-env.html#modes

For the time being, you can `yarn add dotenv`, then create an `.env` in the root on your project. In that file, add some values:
```
MEANING_OF_LIFE=42
```
and then in your `gridsome.config.js` and the following:
```
require('dotenv').config()

module.exports = {
  chainWebpack: config => {
    config
      .plugin('env')
      .use(require.resolve('webpack/lib/EnvironmentPlugin'), ['MEANING_OF_LIFE'])
  },
  plugins: []
}

```

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Do you have any plans to add option for `gridsome build` and `gridsome develop`?
