### ISSUE TITLE
Javascript can't work properly

### ISSUE THREAD

**Issue by sofyanlabs** [gridsome/gridsome#881]
## Description

I have some problem when using other vue component 
i use vue2-datepicker from : https://github.com/mengxiong10/vue2-datepicker

Component can run well in local, but when i push to netlify. Javascript can't work properly.
Anyone can help?

## Local Server
![Screenshot_9](https://user-images.githubusercontent.com/31101961/70868186-94d65100-1fb0-11ea-9762-24dcb2492ccc.png)

## Netlify Server
![Screenshot_8](https://user-images.githubusercontent.com/31101961/70868176-838d4480-1fb0-11ea-8640-12f3fedb2268.png)

```
import DatePicker from 'vue2-datepicker';

export default {
    components: {
      DatePicker
    },
}
```

**Comment by dominiquedutra** [comment]
By local server you mean `gridsome develop`?
Is the project building correctly without any errors when using `gridsome build`?

Also, try installing  http-server with yarn / npm and then building the project and serving it locally with `http-server ./dist` (you have to be on the root directory of gridsome project). Does it work when building & serving locally with http-server?

Also be sure to have read https://gridsome.org/docs/assets-scripts/.

**Comment by sofyanlabs** [comment]
I found it, its mistake from not getting the CSS code for this DatePicker

But I've input css in main. js

```
import DefaultLayout from '~/layouts/Default.vue'

import '~/assets/index.scss'

import DatePicker from 'vue2-datepicker'
import 'vue2-datepicker/index.css'

export default function (Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.component('Layout', DefaultLayout)

  Vue.use(DatePicker)
}
```

**Comment by dominiquedutra** [comment]
@sofyanlabs please read my previous comment and provide the requested information.

**Comment by sofyanlabs** [comment]
This problem is complete when I use the CDN link for the CSS in the plugin that is installed (Vue2-DatePicker). 

It seems purgecss or something removes the CSS when the ' Gridsome build ' runs, because I use plugin gridsome with tailwind. 

can you help me to fix this? i want to use local css, not 3rd party like cdn css

**Comment by a-kriya** [comment]
@sofyanlabs Have you tried disabling PurgeCSS and checking if it works? If it does, then you might have to whitelist selectors for the picker: https://purgecss.com/configuration.html#options

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
