### ISSUE TITLE
sass import file that themselves import from other node_modules fails

### ISSUE THREAD

**Issue by khalyomede** [gridsome/gridsome#885]
## Description

I am using [material-components-web](https://github.com/material-components/material-components-web) in my project.

When I try to import a sass file, in one of my component, Webpack's SASS loader is angry because there is no `~` in the material-components-web source SASS file.

### Steps to reproduce

1. Install material-components-web: `npm install --save-dev material-components-web@4.*`
2. Create a component named `MaterialTopAppBar.vue` like so:

```vue
<template lang="pug">
  header.mdc-top-app-bar
    .mdc-top-app-bar__row
      section.mdc-top-app-bar__section.mdc-top-app-bar__section--align-start
        button.mdc-icon-button.material-icons.mdc-top-app-bar__navigation-icon--unbounded menu
          span.mdc-top-app-bar__title San Francisco, CA 
      section.mdc-top-app-bar__section.mdc-top-app-bar__section--align-end
        button.mdc-icon-button.material-icons.mdc-top-app-bar__action-item--unbounded(aria-label="Download") file_download
        button.mdc-icon-button.material-icons.mdc-top-app-bar__action-item--unbounded(aria-label="Print this page") print
        button.mdc-icon-button.material-icons.mdc-top-app-bar__action-item--unbounded(aria-label="Bookmark this page") bookmark
</template>
<script>
  import { MDCTopAppBar } from "@material/top-app-bar";

  export default {
    mounted() {
      new MDCTopAppBar(this.$el);
    }
  };
</script>
<style lang="sass">
  @import "~@material/top-app-bar/mdc-top-app-bar";
  @import "~@material/icon-button/mdc-icon-button";
</style>
```

_(sorry, I use pug, feel free to convert it back to html: [https://pughtml.com/](https://pughtml.com/))_

3. Use this component somewhere (in the `Layout.vue` for example)

### Expected result

The file compiles without errors.

### Actual result

This error pops instead:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                           21:36:41
 error  in ./src/components/MaterialTopAppBar.vue?vue&type=style&index=0&lang=sass&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import "@material/elevation/mixins";
^
      File to import not found or unreadable: @material/elevation/mixins.
      in C:\xampp\htdocs\test-gridsome\node_modules\@material\top-app-bar\mdc-top-app-bar.scss (line 23, column 1)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--5-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MaterialTopAppBar.vue?vue&type=style&index=0&lang=sass& 4:14-448 14:3-18:5 15:22-456
 @ ./src/components/MaterialTopAppBar.vue?vue&type=style&index=0&lang=sass&
 @ ./src/components/MaterialTopAppBar.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
```

### Environment

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12
    gridsome-plugin-pug: 0.* => 0.0.3
    gridsome-plugin-pwa: 0.* => 0.0.10
```

### Notes

1. I use an (hopefully temporary) fix, by passing the compiled CSS file instead of using SASS files

```vue
<style lang="sass">
  @import "~@material/top-app-bar/dist/mdc.top-app-bar"
</style>
```

2. The file `~@material/top-app-bar/mdc-top-app-bar` is itself requiring another SASS file inside another node_modules, `@material/elevation`, which seems to cause the issue
3. In the source file `@material/top-app-bar/mdc-top-app-bar`, if I manually add a `~`, webpack is happy
4. I am a complete newbie with Webpack and how to configure it, I have mostly worked with Gulp for my previous build, before I fell in love with Gridsome 🙄

I know that with Gulp, instead of using the `~` syntax, you can specify in the sass compiler to also try to find the package from `node_modules` like so:

```javascript
import { src, dest } from "gulp";
import browserify from "gulp-bro";

const css = () => src("src/js/index.js")
  .pipe(browserify({
    transform: [
      "babelify",
      ["vueify-fork", { sass: { includePaths: ["node_modules] } }]
    ]
  }))
  .pipe(dest("dist/js"));
```

And then in the SFC you can do this:

```vue
<style lang="sass">
  @import "@material/top-app-bar/mdc-top-app-bar";
</style>
```

Which passes the compilation.

I do not know if this parameter also exists with webpack-sass-loader...

**Comment by Microflash** [comment]
I'd suggest to import a SASS file from `node_modules` using relative paths.

**Comment by khalyomede** [comment]
Thank you, I tried with these syntaxe and it still throwed an error:

- `@import "./node_modules/@material/top-app-bar/mdc-top-app-bar";`
- `@import "node_modules/@material/top-app-bar/mdc-top-app-bar";`
- `@import "~/../node_modules/@material/top-app-bar/mdc-top-app-bar";`

But I just (1 min ago) solved my issue by:

0. If you do not have it, install `npm install --save-dev sass-loader`
1. Adding this configuration into my `gridsome.config.js` file:

```javascript
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: ["node_modules"]
      }
    }
  }
};
```
2. Using this syntax to import my component:

```vue
<style lang="sass">
    @import "@material/top-app-bar/mdc-top-app-bar"
</style>
```

Which solve my issue, thank you for your time!

**Comment by jd-0001** [comment]
Hey @khalyomede can you import SCSS using:

```scss
# Without prefixing `@` or `~`
@import 'bootstrap/scss/functions';
```

I can use `~` or `@` but I have legacy SCSS where everything is imported without these prefixes. Any Idea?

**Comment by khalyomede** [comment]
Hi @jd-0001 , I confirm, on a blank new Gridsome project:

1. `gridsome create test-import-scss-gridsome`
2. `npm install --save-dev bootstrap sass sass-loader`
3. Add the `css` options [I mentioned](https://github.com/gridsome/gridsome/issues/885#issuecomment-568306981)
4. `gridsome develop`
5. Add a line in the file `src\layouts\Default.vue` in the `<style lang="scss">` tag like you mentioned

It worked like that without any errors. Did you reproduced the same steps?

**Comment by jd-0001** [comment]
@khalyomede Yes, it works. Thanks man :+1:
