### ISSUE TITLE
Add @babel/plugin-proposal-export-default-from to support export from syntax

### ISSUE THREAD

**Issue by khalyomede** [gridsome/gridsome#891]
## Summary

I wanted to create a file to ease importing my components in my pages. When I tried to use the `export name from "file";` syntax, Gridsome thrown an error.

### Basic example

1. In the `src/components` folder, create a component name `BaseButton.vue` with the following code

```vue
<template>
  <button>
    <slot />
  </button>
</template>
```

2. Still in the components folder, create an `index.js` file, and add the following code:

```javascript
export BaseButton from "./BaseButton.vue";
```

3. In the file `src/pages/Index.vue`, in the `<script>` tag, add the following code:

```vue
<template>
  <!-- ... -->
</template>
<script>
  import { BaseButton } from "~/components";

  // ...
</script>
```

4. Run `gridsome develop`, you should see the following error

```
 ERROR  Failed to compile with 1 errors                                                                                                                                         23:45:04
 error  in ./src/components/index.js

Syntax Error: SyntaxError: C:\xampp\htdocs\anwar.io\src\components\index.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):

> 1 | export MaterialGrid from "./MaterialGrid.vue";
    |        ^
  2 | 

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.


 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js& 5:0-44
 @ ./src/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
```

### Motivation

I can sometime import 5 to 10 components in my real web app. I would like to make importing my components easier. 

Instead of having this (taken from my app):

```vue
<!-- Index.vue -->
<script>
  import MaterialCard from "~/components/MaterialCard.vue";
  import MaterialGrid from "~/components/MaterialGrid.vue";
  import MaterialGridCell from "~/components/MaterialGridCell.vue";
  import cardActionButton from "~/directives/card-action-button";
  import typography from "~/directives/typography";
</script>
```

I would like to be able to do this:

```vue
<!-- Index.vue -->
<script>
  import { MaterialCard, MaterialGrid, MaterialGridCell } from "~/components";
  import { cardActionButton, typography } from "~/directives";   
</script>
```

### Notes

While I thought of a workaround without using the export from proposal, I thought maybe Gridsome can handle it for us? Maybe we could have an `src/components/index.js` by default when Gridsome installs, with a code that would automatically scan for `**/*.vue` files in the folder, and export them automatically? Just an idea crossing my mind 🙄

### Resources

- [@babel/plugin-proposal-export-default-from (babeljs.io)](@babel/plugin-proposal-export-default-from)
- [export default from proposal (TC39)](https://github.com/tc39/proposal-export-default-from)

**Comment by hjvedvik** [comment]
The proposal is still at stage 1, so I think we'll wait before including it :)

But you can try to have this in `components/index.js` instead:

```
export { default as BaseButton } from './BaseButton.vue'
```

You should then be able to import it anywhere with:
```
import { BaseButton } from '~/components'
```

**Comment by khalyomede** [comment]
Nice trick, thank you a lot ;) I think this solves this issue for me!
