### ISSUE TITLE
Pages have scroll position near bottom when navigated to.

### ISSUE THREAD

**Issue by cbaone** [gridsome/gridsome#892]
## Description

When building the site on my localhost I run into a problem where if I'm scrolled to the bottom of a page and I click a link in the footer, it takes me to the new page as expected, but scrolled down - the page doesn't return to the top. Not even sure this is gridsome specific, but I have to ask because I can't find anything from anywhere.

### Steps to reproduce

The issue result is the only specific thing about this issue. I can't say when the site started doing this behavior, but when I noticed it, it was happening on every page.

### Expected result

If I'm scrolled to the bottom of a page and navigate to a different page, the new page should render scrolled all the way to the top, not at the same scroll position as the other page I navigated away from.

### Actual result

The new page I'm navigating to has a scroll position near the bottom.

### Environment

System:
OS: macOS 10.15.2
CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Binaries:
Node: 13.3.0 - /usr/local/bin/node
yarn: 1.17
Browsers:
Chrome: 79.0.3945.79
Firefox: 70.0
Safari: 13.0.4
npmPackages:
gridsome: ^0.7.0 => 0.7.12
npmGlobalPackages:
@gridsome/cli: 0.3.1

**Comment by cbaone** [comment]
An odd scripting error in another plugin created this issue. Thankfully the script in question was no longer necessary and it solved our issue.

**Comment by sir-red-dab** [comment]
I'm currently having the same problem. This problem is only occuring in Firefox and not in Chrome. I try to fix this with the following code:

```javascript
window.onbeforeunload = function () {
    window.scrollTo(0, 0);
}
```

Unfortunately it's not working.

**Comment by luka-bacic** [comment]
This is still happening in Firefox
