### ISSUE TITLE
Spread Syntax Issue Choking IE/Edge

### ISSUE THREAD

**Issue by yb-admin** [gridsome/gridsome#893]
## Description

Spread Syntax Transpiling error:
Script error in IE/EDGE "SCRIPT1028: SCRIPT1028: Expected identifier, string or number"

added this to address with no luck:
"plugins": ["@babel/plugin-proposal-object-rest-spread"]

### Steps to reproduce

Just a typical build will result in an app.js that IE/Edge choke on

### Expected result

Transpiling should result in an app.js that IE/Edge can read.

### Actual result

IE/Edge choke on the app.js and kill all other scripts on the page making page unusable.

### Environment

Mac OS
@gridsome/cli v0.2.1
gridsome v0.7.12

**Comment by lynden-jones** [comment]
I'm seeing the same thing!  The site is unusable on ie.  It's seems as though `.bablerc` isn't getting picked up at all.

**Comment by yb-admin** [comment]
Here's some more context...

![edge-error](https://user-images.githubusercontent.com/54604921/71325457-72f63600-24aa-11ea-8949-ea448ec8b585.png)

Edge is erroring out on this specific piece of the app.js and killing the rest of the page. Obviously, all other non-Windows browsers are handling it fine.

**Comment by yb-admin** [comment]
We sussed it out... Turns out we had a rogue SVG - the only one that wasn't run through our cleaner... Sorry for all the hubbub.

**Comment by edlefebvre** [comment]
@yb-admin how did you cleaned up your svg files exactly? I have the same issue.

**Comment by yb-admin** [comment]
This tool helped clean up the SVG: https://jakearchibald.github.io/svgomg/

**Comment by edlefebvre** [comment]
OK thanks @yb-admin I'll have a look at it. Do you use `vue-svg-loader`?

**Comment by yb-admin** [comment]
We used to. I apologize for not mentioning that... Because now that I think about it, removing `vue-svg-loader` actually might have been the fix. :/ It's been a whirlwind lately so it all seems like a jumble. When I saw the question I jumped the gun and assumed the svg was the issue.

**Comment by yb-admin** [comment]
It may or may not be helpful, but the plugin author gave us this advice: Try setting plugins to defaultPlugins.concat(svgo). We had already disabled the plugin so we didn't try it, but it may help in your case.

**Comment by edlefebvre** [comment]
OK I see, no problem! On my hand, the problem was clearly with `vue-svg-loader`...
I change the way I load svg files, using vue components, and the problem is gone. Thanks again!

**Comment by u12206050** [comment]
Found a fix by including babel loader before vue-svg-loader and using @babel/plugin-proposal-object-rest-spread
