### ISSUE TITLE
DOM for Pager

### ISSUE THREAD

**Issue by EtienneR** [gridsome/gridsome#90]
Hi,

I think the pagination generated by Pager should have a better DOM. Actually DOM looks like.

```
nav > a
```

What we should have when I looking in [Bootstrap](http://https://getbootstrap.com/docs/4.1/components/pagination) and [Bulma](https://bulma.io/documentation/components/pagination) documentation pagination, should be a list.

```
nav > ul > li > a
```

And not forget class for active / current page as props.

Thanks :)

**Comment by tomtev** [comment]
Hi there, bootstrap can also do this: 
<img width="975" alt="skjermbilde 2019-01-03 kl 20 12 00" src="https://user-images.githubusercontent.com/48070/50656546-e0f0d700-0f93-11e9-97d5-69ae7efc2ac1.png">

This is from their official docs.

**Comment by tomtev** [comment]
But I agree we need to add an option to change the active class :)

https://gridsome.org/docs/pagination
