### ISSUE TITLE
@gridsome/transformer-remark doesn't support backslash for linebreak

### ISSUE THREAD

**Issue by tobyhage** [gridsome/gridsome#908]
## Description

@gridsome/transformer-remark doesn't support backslash for linebreak. Instead backslash is displayed.

### Steps to reproduce

Make a markdown file with following content, where "Here some content" is on the next line.

`**Heading**\
Here some content
`

### Expected result

**Heading**
Here some content

### Actual result

**Heading**\ Here some content

### Environment

Gridsome 0.7
@gridsome/transformer-remark 0.4.0

Probably two spaces instead of backslash is working. But i use Netlify CMS and two spaces are converted too a backslash.

**Comment by matthieu-locussol** [comment]
I also use Gridsome with Netlify CMS and have the same problem.

Did anyone find a solution ?

**Comment by AMFTech512** [comment]
For anyone still searching for this answer... I found a solution.

In the `gridsome.config.js` file, add the `commonmark: true` to the remark config. It should look something like this:
```Javascript
module.exports = {
   ...
   transformers: {
       remark: {
           config: {
               commonmark: true
           }
       }
   }
};
```

I hope I can help some poor future soul on the internet.

**Comment by tobyhage** [comment]
Thank you for the answer.

But for me it is still not working.
I'am at: "@gridsome/transformer-remark": "^0.6.3",
