### ISSUE TITLE
GraphQL Subscriptions

### ISSUE THREAD

**Issue by mihajlon97** [gridsome/gridsome#91]
## GraphQL Subscriptions Queries

It would be nice to have already integrated graphql subscriptions for real-time applications!
something like

`<subscription>
subscription{
  id: somethingChanged{
    id
  }
}
</subscription>`

**Comment by robaxelsen** [comment]
@mihajlon97 Do you mean that a website made with Gridsome should be able to have websocket subscriptions to an external source, or that this should be used as part of Gridsome's build process?

GraphQL is used by Gridsome as a middle layer to pull in the data, and then builds the static site based on the data. I don't see how it can be part of that process, as once it's built no more data is being pulled until a new build is done.
