### ISSUE TITLE
Not in NPM registry

### ISSUE THREAD

**Issue by xhostcom** [gridsome/gridsome#913]
## Description
It is shown as not in the npm registry

Describe the issue that you're seeing.

### Steps to reproduce
npm install --global @gridsome/cli
Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result
Install Gridsome
What should happen?

### Actual result
Not in registry?
What happened.

### Environment
Linux, Node/NPM latest
Paste the information here as shown by `gridsome info`

**Comment by xhostcom** [comment]
Just not showing in registry at all?

**Comment by noxify** [comment]
@xhostcom - what is not showing in the npm registry?

**Comment by xhostcom** [comment]
Gridsokme? just get error npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@gridsome%2fcli
npm ERR! 404
npm ERR! 404  '@gridsome/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.


On 02/01/2020, Marcus Reinhardt <notifications@github.com> wrote:
> @xhostcom - what is not showing in the npm registry?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/gridsome/gridsome/issues/913#issuecomment-570156930


-- 
I'd love to add you as a connection, if you're on Linkedin just click
the link below and shoot me a request. I'll accept ASAP. If you're
prompted to put in my email, just use anthonymcgowan1@gmail.com

https://www.linkedin.com/in/b2binitiatives/"Connect on Linkedin

**Comment by noxify** [comment]
I'm sorry, but i can't reproduce your issue:

```
//uninstalled the cli first
sudo npm uninstall --global @gridsome/cli@latest
$ up to date in 0.028s

//installed it via @latest
sudo npm install --global @gridsome/cli@latest 
$ /usr/local/bin/gridsome -> /usr/local/lib/node_modules/@gridsome/cli/bin/gridsome.js
$ + @gridsome/cli@0.3.1
$ added 173 packages from 119 contributors in 5.461s
```
My setup:
```
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
```

**Comment by noxify** [comment]
Does it work with:
```
npm install --global @gridsome/cli
```
?

Tag `0.3.1` is the latest version - there are no other changes in the `cli`.

**Comment by xhostcom** [comment]
still get this, using nvm
npm install --global @gridsome/cli@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@gridsome%2fcli
npm ERR! 404
npm ERR! 404  '@gridsome/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.


any version of npm to use/ thanks

On 02/01/2020, Marcus Reinhardt <notifications@github.com> wrote:
> Does it work with:
> ```
> npm install --global @gridsome/cli
> ```
> ?
>
> Tag `0.3.1` is the latest version - there are no other changes in the
> `cli`.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/gridsome/gridsome/issues/913#issuecomment-570160107


-- 
I'd love to add you as a connection, if you're on Linkedin just click
the link below and shoot me a request. I'll accept ASAP. If you're
prompted to put in my email, just use anthonymcgowan1@gmail.com

https://www.linkedin.com/in/b2binitiatives/"Connect on Linkedin

**Comment by noxify** [comment]
@xhostcom - and did you tried it without the `@latest` in the command? 

For me, it seems there is something wrong with your npm config.
This sounds similar to your problem: 
https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404

Here are some other questions:
* Which OS are you using?
* node version?
* npm version?

**Comment by xhostcom** [comment]
anton@anton-pc:~$ npm install --global @gridsome/cli@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@gridsome%2fcli
npm ERR! 404
npm ERR! 404  '@gridsome/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anton/.npm/_logs/2020-01-02T14_23_28_539Z-debug.log
anton@anton-pc:~$
Hi its latest node via nvm node 13.5  npm 6.13.4  on Lubuntu

On 02/01/2020, Marcus Reinhardt <notifications@github.com> wrote:
> @xhostcom - and did you tried it without the `@latest` in the command?
>
> For me, it seems there is something wrong with your npm config.
> This sounds similar to your problem:
> https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404
>
> Here are some other questions:
> * Which OS are you using?
> * node version?
> * npm version?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/gridsome/gridsome/issues/913#issuecomment-570216560


-- 
I'd love to add you as a connection, if you're on Linkedin just click
the link below and shoot me a request. I'll accept ASAP. If you're
prompted to put in my email, just use anthonymcgowan1@gmail.com

https://www.linkedin.com/in/b2binitiatives/"Connect on Linkedin

**Comment by xhostcom** [comment]
Its OK now had Npm/yarn etc issues fixed them Thanks

On 02/01/2020, Paul Anthony McGowan <xhostcom@gmail.com> wrote:
> anton@anton-pc:~$ npm install --global @gridsome/cli@latest
> npm ERR! code E404
> npm ERR! 404 Not Found - GET http://registry.npmjs.org/@gridsome%2fcli
> npm ERR! 404
> npm ERR! 404  '@gridsome/cli@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name
> yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/anton/.npm/_logs/2020-01-02T14_23_28_539Z-debug.log
> anton@anton-pc:~$
> Hi its latest node via nvm node 13.5  npm 6.13.4  on Lubuntu
>
> On 02/01/2020, Marcus Reinhardt <notifications@github.com> wrote:
>> @xhostcom - and did you tried it without the `@latest` in the command?
>>
>> For me, it seems there is something wrong with your npm config.
>> This sounds similar to your problem:
>> https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404
>>
>> Here are some other questions:
>> * Which OS are you using?
>> * node version?
>> * npm version?
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/gridsome/gridsome/issues/913#issuecomment-570216560
>
>
> --
> I'd love to add you as a connection, if you're on Linkedin just click
> the link below and shoot me a request. I'll accept ASAP. If you're
> prompted to put in my email, just use anthonymcgowan1@gmail.com
>
> https://www.linkedin.com/in/b2binitiatives/"Connect on Linkedin
>


-- 
I'd love to add you as a connection, if you're on Linkedin just click
the link below and shoot me a request. I'll accept ASAP. If you're
prompted to put in my email, just use anthonymcgowan1@gmail.com

https://www.linkedin.com/in/b2binitiatives/"Connect on Linkedin
