### ISSUE TITLE
Question: How to create a bidirectional relation in GraphQL?

### ISSUE THREAD

**Issue by brpaz** [gridsome/gridsome#915]
## Summary

Hello. 
It´s possible to create a bidirectional relationship between two collections?

Considering the official example from the documentation of Taxonomies  (Posts and Tags).

Let´s say I want to get all tags of a Post and also get the post associated with a specific tag. 
I would expect to have a "Post" property in the "Tag" schema and an array of "tags" in the "Post" schema.

Thank you.

**Comment by iam-jam** [comment]
Hi @brpaz 

If you could describe\show me the schema of your source data I should be able to help you...

**Comment by guirreri** [comment]
Pretty sure this is related to the issue [I just posted here](https://github.com/gridsome/gridsome/issues/964)

**Comment by noxify** [comment]
@brpaz please take a look at #964 and also in the discord chat where have described two options to generate the relations.

https://discordapp.com/channels/476372673564246017/504192730667155466/674370183116095489

For now i will close this issue. If there are any questions, feel free to reopen the issue or create a new one :)
