### ISSUE TITLE
How to increase the timeout on netlify

### ISSUE THREAD

**Issue by sofyanlabs** [gridsome/gridsome#916]
I have wordpress site with 30k post, inside the post have many image

im use source wordpress + images

i got this error  Execution timed out after 15m0s
how to incerease the timeout on netlify?

**Comment by Larsklopstra** [comment]
You should not be able to increase the timeout on Netlify itself, the building process should be done faster 👀

**Comment by noxify** [comment]
#901

**Comment by lorvent** [comment]
Well, you already responded in my issue but there is no direct solution for this,

but i found alternate solution i.e. use http://render.com/ who doesn't have any limits.

another good thing i found with render.com is build time is getting reduced with each build (not sure if they are doing cache or what)... my first build is around 30mins and it has come down to <20mins now.

**Comment by sofyanlabs** [comment]
> Well, you already responded in my issue but there is no direct solution for this,
> 
> but i found alternate solution i.e. use http://render.com/ who doesn't have any limits.
> 
> another good thing i found with render.com is build time is getting reduced with each build (not sure if they are doing cache or what)... my first build is around 30mins and it has come down to <20mins now.

thankyou, works!

**Comment by hacknug** [comment]
In case someone lands here, another thing you could try is build locally and deploy using Netlify's  [`netlify-cli`](https://github.com/netlify/cli). In my case the build/deploy time was reduced ~95% after doing this and disabling _Asset optimization_. Disabling the later also resulted in an improved TTI on my tests (but this might be unrelated and irrelevant for this convo).

![Captura de pantalla 2020-02-05 a las 16 56 21](https://user-images.githubusercontent.com/1107521/73858343-8847d980-4838-11ea-9618-c328f16a8163.png)
