### ISSUE TITLE
This is the most crappy framework I've ever seen. It doesn't support element selectors at all. The packaged styles are mixed together

### ISSUE THREAD

**Issue by baixuexiyang** [gridsome/gridsome#919]
## Description

This is the most crappy framework I've ever seen. It doesn't support element selectors at all. The packaged styles are mixed together

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Paste the information here as shown by `gridsome info`

**Comment by noxify** [comment]
Hello @baixuexiyang,

thanks for reporting.

Could you please so kind and let us know what you mean exactly?

Thanks!

**Comment by baixuexiyang** [comment]
> Hello @baixuexiyang,
> 
> thanks for reporting.
> 
> Could you please so kind and let us know what you mean exactly?
> 
> Thanks!

I've turned all scss into CSS，don't use scss

**Comment by baixuexiyang** [comment]
I turn it with a tool
