### ISSUE TITLE
Docs on Layout suggest they are not global, but in the default app they are

### ISSUE THREAD

**Issue by cfjedimaster** [gridsome/gridsome#920]
## Description

Pardon the somewhat awkward title. In Core Concepts (https://gridsome.org/docs/core-concepts/), the docs for layouts say you must import them to use them, but that they can be made global. This leads you to this page (https://gridsome.org/docs/layouts/#make-a-layout-global) that explains how to do it.

It looks like now the default Gridsome app does this for you automatically. Therefore the docs are a bit confusing as it implies you may need to do something you don't have to.

### Expected result

I'd suggest changing the docs in Core Concept to *not* include the Layout component as it's done by default now. In the Layout docs, definitely mention why this works, and that it is the default, but that a person may change that of course.

**Comment by tomtev** [comment]
Very good suggestion @cfjedimaster . Maybe it's best to remove the global layout in the default starter? To make a layout global should just be a "Hot tip" or something.

**Comment by cfjedimaster** [comment]
As a Gridsome user for like 5 minutes (grin), my opinion is to keep it as is. It feels like something I'd want 90% of the time and I'd rather remove it when I don't need it. 

But again - *really* new user so I don't know if most folks use this or remove it from the code.

**Comment by brandonpittman** [comment]
Most people want a global layout. Taking it out would cause the majority of people a headache.

**Comment by a-kriya** [comment]
@cfjedimaster Would you be able to submit a PR with updates to the doc as you suggested?

**Comment by cfjedimaster** [comment]
Sure... can't promise how quickly. :)

**Comment by cfjedimaster** [comment]
Filed: https://github.com/gridsome/gridsome.org/pull/414

**Comment by a-kriya** [comment]
@tomtev Can be closed.

**Comment by a-kriya** [comment]
@cfjedimaster Will you be able to close the ticket?
