### ISSUE TITLE
How to set the picture centered in markdown

### ISSUE THREAD

**Issue by hotblin** [gridsome/gridsome#922]
```js
  transformers: {
    remark: {
      plugins: [
         somethig...
      ]
    }
  }
```

**Comment by hotblin** [comment]
```html
<p style="text-align:center;">
   <img src="https://avatar.gitee.com/uploads/group/122450135007185.png"/>
</p>

```

**Comment by equinusocio** [comment]
Or

```
<p align="center">
   <picture>...</picture>
</p>
```

**Comment by cco3** [comment]
I think the best way to do this is to use [remark-attr](https://github.com/arobase-che/remark-attr) to specify a class and then define the class as centering the image.  (In this particular case you would probably make the width of the image 100% and then specify the [object fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit))

**Comment by noxify** [comment]
if you want you have every image centered you could also 
* https://gridsome.org/plugins/@noxify/gridsome-remark-classes

but if only some image should be centered, then you should use `remark-attr` which @cco3 mentioned already.

Here the reference to the docs, how to enable `remark-attr`: https://github.com/gridsome/gridsome/tree/master/packages/transformer-remark#add-additional-plugins
