### ISSUE TITLE
Question: Is there a way to skip README.md in source-filesystem?

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#929]
I'd like to use `path: 'dir/*.md',`, is there an easy way to skip README.md?

**Comment by noxify** [comment]
Hi @cco3,

based on the documentation for [source-filesystem](https://gridsome.org/plugins/@gridsome/source-filesystem) you can exclude the file from the path definition.

> Where to look for files. Should be a glob pattern.

Example:

```
{
    use: '@gridsome/source-filesystem',
    options: {
        typeName: 'Blog',
        path: './content/blog/**/*[!README].md'
    }
}
```

**Comment by cco3** [comment]
I'm going to close this as answered, but that exclude pattern isn't ideal since it would also exclude anything that ends in one of those letters.

**Comment by cco3** [comment]
So apparently I can pass multiple globs, i.e., `path = ['dir/*.md', '!dir/README.md']`
