### ISSUE TITLE
Vue Slider Component

### ISSUE THREAD

**Issue by MarcoFaul** [gridsome/gridsome#935]
Hi,

I'm using the vue-slider-component v3.1.0 (https://github.com/NightCatSama/vue-slider-component) as a component.

Script
```
<script>
    import VueSlider from 'vue-slider-component/dist-css/vue-slider-component.umd.min.js'
    import 'vue-slider-component/dist-css/vue-slider-component.css'
    import 'vue-slider-component/theme/default.css'

    export default {
        ...
        components: {
            VueSlider
            // VueSlider: () => import('vue-slider-component')
        },
    }
</script>
```

Template
```
<ClientOnly>
                                <vue-slider name="slider" class="appearance-none border-border-color-primary rounded outline-none focus:border-ui-main"
                                            v-model="value"
                                            :interval="steps"
                                            :min="min"
                                            :max="max"
                                />
                            </ClientOnly>
```

The slider works at dev but on production (on build) it won't show up. I even tried 
VueSlider: () => import('vue-slider-component') as it got suggested with other components.

With the umd version and without the ClienOnly tags, it shows up, but js + styles are broken
Any suggestions?

**Comment by noxify** [comment]
Hi,

i have tested it only with the umd version, but the styles are shown correctly.

```
<template>
  <Layout :hideHeader="true" :disableScroll="true">
    <div class="container mx-auto pt-24 pb-16 px-4 sm:px-0">
      <div class="lg:mx-32 md:mx-16 sm:mx-8">
        <vue-slider v-model="value"></vue-slider>
      </div>
    </div>

  </Layout>
</template>

<script>

// import component
import VueSlider from 'vue-slider-component/dist-css/vue-slider-component.umd.min.js'
import 'vue-slider-component/dist-css/vue-slider-component.css'

// import theme
import 'vue-slider-component/theme/material.css'

export default {
  metaInfo: {
    title: "Slider"
  },
  data: function () {
    return {
      value: 0,
    }
  },
  components: {
    VueSlider
  }
};
</script>

```

Here the screenshot from the example above:
![image](https://user-images.githubusercontent.com/521777/72207826-a40bca00-349c-11ea-8554-20bb619ac39c.png)

**Comment by MarcoFaul** [comment]
Hey @noxify thanks for the fast reply. On development mode it works like a charm. But after building it, it looks like this
![image](https://user-images.githubusercontent.com/6201946/72207956-9e62b400-349d-11ea-8514-b59339f9a5e4.png)

**Comment by noxify** [comment]
Tested it also with `<ClientOnly>` and 
```
VueSlider2: () =>
        import ('vue-slider-component')
        .then(m => m.VueSlider2)
        .catch()
```

But then I got the following error:

```
app.b1a21706.js:7 Uncaught (in promise) TypeError: Cannot read property '__esModule' of undefined
    at Fe (app.b1a21706.js:7)
    at app.b1a21706.js:7
    at app.b1a21706.js:7
```

**Comment by noxify** [comment]
Based on the `vue-slider-component` documentation, i would go with the `umd version.

--> https://nightcatsama.github.io/vue-slider-component/#/?hash=server-side-rendering-ssr

**Comment by noxify** [comment]
Are you using `purgecss`? 
Maybe you have to update the whitelist... I had this issue the last days :D

**Comment by MarcoFaul** [comment]
Yeah, I'm using `purgecss` and `stylewind`. Tried now the following: whitelistPatterns: [/vue-slider$/],
But still no styles after building…

**Comment by noxify** [comment]
But if you disable purgecss, it is working? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MarcoFaul** [comment]
Kind of. The styles are loaded but the slide doesn't work.

![image](https://user-images.githubusercontent.com/6201946/72208814-a45d9280-34a7-11ea-8e8d-efc6acf1e53d.png)

I don't get it why it throws me that error and why the whitelist/whitelistpattern don't work either.
```
"dependencies": {
    "@fullhuman/postcss-purgecss": "^1.3.0",
    "@gridsome/plugin-google-analytics": "^0.1.0",
    "@gridsome/plugin-sitemap": "^0.2.3",
    "@gridsome/source-ghost": "^0.2.0",
    "axios": "^0.19.0",
    "gridsome": "^0.7.11",
    "gridsome-plugin-robots-txt": "^1.0.2",
    "gridsome-plugin-tailwindcss": "^2.2.27",
    "lodash.pick": "^4.4.0",
    "vue-cookieconsent-component": "^1.2.0",
    "vue-cookies": "^1.5.13",
    "vue-fuse": "^2.1.2",
    "vue-i18n": "^8.15.1",
    "vue-scrollto": "^2.17.1",
    "vue-slide-bar": "^1.2.0",
    "vue-slider-component": "^3.1.0"
  },
```

**Comment by noxify** [comment]
How did you solved it @MarcoFaul ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by markholdt** [comment]
> Based on the `vue-slider-component` documentation, i would go with the `umd` version.
> 
> --> https://nightcatsama.github.io/vue-slider-component/#/?hash=server-side-rendering-ssr
> 
> Edit: I tried this:
> 
> ```
> <template>
>   <Layout :hideHeader="true" :disableScroll="true">
>     <div class="container mx-auto pt-24 pb-16 px-4 sm:px-0">
>       <div class="lg:mx-32 md:mx-16 sm:mx-8">
>         <ClientOnly>
>         <vue-slider2 v-model="value"></vue-slider2>
>         </ClientOnly>
>       </div>
>     </div>
> 
>   </Layout>
> </template>
> 
> <script>
> 
> // import component
> //import VueSlider from 'vue-slider-component/dist-css/vue-slider-component.umd.min.js'
> import 'vue-slider-component/dist-css/vue-slider-component.css'
> 
> // import theme
> import 'vue-slider-component/theme/material.css'
> 
> export default {
>   metaInfo: {
>     title: "Slider"
>   },
>   data: function () {
>     return {
>       value: 0,
>     }
>   },
>   components: {
>     //VueSlider
>     VueSlider2: () =>
>         import ('vue-slider-component')
>         
> 
>   }
> };
> </script>
> ```
> 
> And it seems to work.
> 
> * no errors in the web console
> * slider is working
> 
> ![image](https://user-images.githubusercontent.com/521777/72208029-8c354580-349e-11ea-9923-ade423f21932.png)

This worked for me!
