### ISSUE TITLE
Html for unpublished pages are still generated

### ISSUE THREAD

**Issue by Edmund1645** [gridsome/gridsome#940]
## Description

When an article is set to `published: false` in the front matter field, I noticed that the page is still built, but it just won't display on the page.

### Steps to reproduce

In the front matter of any markdown blog post, set the `published` field to `false`, and now try navigating to the blog post using the full path, for example: `localhost:8080://top-10-js-frameworks`

### Expected result

Navigating to an unpublished page should result in a 404 error because the page should not exist just yet.

### Actual result

Navigating to the page manually displays the content of the page.

### Environment
OS: Mac OS
Browser: Chrome
Gridsome version: 0.7.12

**Comment by noxify** [comment]
We had similar question in the chat.

One option was to create your pages via the Pages API and `createPage` ( Example: https://gridsome.org/docs/pages-api/#create-pages-from-graphql ) then you can filter your not published posts.

What you have to know: 
* Don‘t define a `component` inside the `templates` block in your `gridsome.config.js`
* ensure that that inside `/src/templates` you don‘t have a file with the same name as you have as `typeName` ( / collection name ) otherwise, Gridsome will use this template and auto generates the HTML files.

If you have any questions, feel free to ask :) 

P.S. you can find the complete question and the solution in the #graphql channel from the Gridsome discord chat (09.01.2020 - question was asked from robbin) 

Hope that helps :)


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hjvedvik** [comment]
@Edmund1645 As @noxify wrote; using the Pages API instead of templates configuration will give you full control over which articles get generated :) Another option could be to use [`api.onCreateNode()`](https://gridsome.org/docs/server-api/#apioncreatenodefn) to filter out articles. Something like this will prevent nodes with `published: false` from being generated or visible in any query results:

```js
api.onCreateNode(node => {
  if (node.internal.typeName === 'YourTypeName' && node.published === false) {
    return null
  }
)
```

**Comment by noxify** [comment]
@Edmund1645 - Could we close this issue or are there some questions?

**Comment by Edmund1645** [comment]
No questions, thanks

**Comment by Edmund1645** [comment]
> @Edmund1645 As @noxify wrote; using the Pages API instead of templates configuration will give you full control over which articles get generated :) Another option could be to use [`api.onCreateNode()`](https://gridsome.org/docs/server-api/#apioncreatenodefn) to filter out articles. Something like this will prevent nodes with `published: false` from being generated or visible in any query results:
> 
> ```js
> api.onCreateNode(node => {
>   if (node.internal.typeName === 'YourTypeName' && node.published === false) {
>     return null
>   }
> )
> ```

Hello @hjvedvik , the solution above seemed to do the trick until today when the local dev server won't even start because of this:
```
Gridsome v0.7.12

Initializing plugins...
TypeError: Cannot read property 'tags' of null
    at FilesystemSource.createNodeRefs (/Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:77:29)
    at /Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:69:12
    at async Promise.all (index 14)
    at async FilesystemSource.createNodes (/Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:65:5)
    at async /Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:33:7
    at async Plugins.run (/Users/edmund/projects/mine/ninja-blog/node_modules/gridsome/lib/app/Plugins.js:141:11)
```

Maybe I'll try @noxify's

**Comment by Edmund1645** [comment]
Hello @hjvedvik I'm still having issues with this, the nodes for unpublished content still get created.

I used @noxify's solution and it worked for a while, now I'm getting this error below: 
Gridsome v0.7.12


```
Initializing plugins...
TypeError: Cannot read property 'tags' of null
    at FilesystemSource.createNodeRefs (/Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:77:29)
    at /Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:69:12
    at async Promise.all (index 2)
    at async FilesystemSource.createNodes (/Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:65:5)
    at async /Users/edmund/projects/mine/ninja-blog/node_modules/@gridsome/source-filesystem/index.js:33:7
    at async Plugins.run (/Users/edmund/projects/mine/ninja-blog/node_modules/gridsome/lib/app/Plugins.js:141:11)
```
I usually display nodes related by tags on the page, I just noticed that the unpublished articles appear as recommendations.

returning `null` for unpublished pages do not seem to do the trick anymore.

**Comment by Edmund1645** [comment]
Fixed.

The problem was from `@gridsome/source-filesystem` upgrading from `0.6.0` to `0.6.2` fixed the issue.

**Comment by wisnuwiry** [comment]
My `@gridsome/source-filesystem` version is `0.6.2` but I have the same issue.

Log:
```
TypeError: Cannot read property 'cover_image' of undefined
    at a.metaInfo (assets/js/page--src--templates--post-vue.517fffff.js:1441:30)
```

**Comment by platform-kit** [comment]
I'm getting the same error with the gridsome 0.7.13 and gridsome/source-filesystem 0.6.2

>  error  in ./src/components/SiteFooter.vue?vue&type=custom&index=0&blockType=static-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js):
Error: Cannot query field "title" on type "Tag".

GraphQL request:54:11
53 |           id
54 |           title
   |           ^
55 |           path
    at Object.module.exports (/Users/jameshuntercarter/htdocs/dharmaworks/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:38:21)

 @ ./src/components/SiteFooter.vue?vue&type=custom&index=0&blockType=static-query 1:0-340 1:356-359 1:361-698 1:361-698
 @ ./src/components/SiteFooter.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

**Comment by noxify** [comment]
Hi @wisnuwiry ,

Could you please create a new issue with some more details about your environment etc. 

This issue is closed since one month and it‘s hard to track closed issues ;)
