### ISSUE TITLE
Website page does not load until the complete css bundle in downloaded

### ISSUE THREAD

**Issue by mehtaanshul** [gridsome/gridsome#945]
## Description
I am testing my website page on Chrome (Slow 3G) and what i see is the html document downloads in 1-2 seconds but i cannot see anything on the page until the complete css bundle is downloaded which takes almost 60 seconds.

Paste the information here as shown by `gridsome info`
System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 12.1
  npmPackages:
    @gridsome/plugin-sitemap: ^0.2.1 => 0.2.1
    gridsome: 0.6.5 => 0.6.5
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1
    gridsome-source-directus: 0.0.2 => 0.0.2
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

**Comment by iam-jam** [comment]
Hi @mehtaanshul 

Is all of your CSS within your components?

**Comment by mehtaanshul** [comment]
Hey @iam-jam 
We have scss in all vue components and also there is global scss which we are importing in main.js.
After the buld only one css file is generated and the static html document generated by gridsome has no css in it.

**Comment by iam-jam** [comment]
@mehtaanshul before trying anything else you might want to use the latest version of Gridsome as 0.6.5 is quite out of date now...

**Comment by mehtaanshul** [comment]
@iam-jam Will do that. Anything else you think that can help?

**Comment by mehtaanshul** [comment]
@iam-jam updated the gridsome version. It didn't have any effect on the problem

**Comment by hjvedvik** [comment]
@mehtaanshul You can try [@gridsome/plugin-critical](https://gridsome.org/plugins/@gridsome/plugin-critical) and see if it will help. The plugin will extract critical CSS and lazy-load everything else. By default, it only processes the front page, but you can process more pages if you want to.

**Comment by mehtaanshul** [comment]
@iam-jam @hjvedvik We updated the gridsome version and then used https://gridsome.org/plugins/@gridsome/plugin-critical. This has solved our issue :)
