### ISSUE TITLE
Preload Link Tags doesn't get added a hash in the filename part

### ISSUE THREAD

**Issue by chrispreisler** [gridsome/gridsome#948]
## Description
Hey guys,

I would like to add preload link tags for the fonts I use. When I build the project, the fonts are getting added a hash. For example:

Brown-Regular.099e55b2.woff2

Unfortunately that hash is not added to the filename in the <link> tag.

`<link data-vue-tag="ssr" rel="preload" href="/assets/fonts/Brown-Regular.woff2" as="font"  type="font/woff2" crossorigin="anonymous">`

Is this a bug in the build process? Ist it possible to add the hash manually in the main.js in the head.link.push?

`head.link.push(
    {
      rel: "preload",
      href: "/assets/fonts/Brown-Regular.woff2",
      as: "font",
      type: "font/woff2",
      crossorigin: "anonymous"
    }
  );`

Thank you very much for your answers in advance.

Best regards
Chris

System:
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4
  npmPackages:
    gridsome: ^0.7.12 => 0.7.12 
    gridsome-plugin-flexsearch: ^0.1.10 => 0.1.10 
    gridsome-plugin-tailwindcss: ^2.2.32 => 2.2.32 
    gridsome-source-shopify: ^0.1.9 => 0.1.9 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

**Comment by chrispreisler** [comment]
I also fount out the following:

The fonts are only transfered into the build folder, because of the @font-face declaration. When I only add the head.push.link part in the main.js without any further @font-face declaration, the font itsself doesn't get transfered to the dist folder. I hope that helps.

**Comment by hjvedvik** [comment]
The hash is added by webpack. You can try to disable hashes by setting `cacheBusting: false` in `gridsome.config.js` and add the prefetch link with `head.link.push`. Another option is to check out  [this](https://github.com/gridsome/gridsome/pull/716) PR which lets you set a regex for the `shouldPrefetch` option to the Vue server renderer. It's not documented because it is a temporary solution.

**Comment by catenthusiast** [comment]
You need to import the font file first. Something like this should work:

```javascript
import BrownRegular from "~/fonts/Brown-Regular.woff2"

export default function(Vue, { head }) {
  head.link.push( { rel: "preload", href: BrownRegular, as: "font" } )
}
```

**Comment by chrispreisler** [comment]
Hey guys,

thank you very much for your help. I indeed forgot to import the fonts in the main.js. Now everything is working as expected.

Cheers Chris

**Comment by felixdenoix** [comment]
> You need to import the font file first. Something like this should work:
> 
> ```js
> import BrownRegular from "~/fonts/Brown-Regular.woff2"
> 
> export default function(Vue, { head }) {
>   head.link.push( { rel: "preload", href: BrownRegular, as: "font" } )
> }
> ```

And don't forget to add the `crossorigin: true` option to prevent the font to be loaded by the browser twice because of the fontloading in the css file and in link=preload from the head !

```js
import BrownRegular from "~/fonts/Brown-Regular.woff2"
 
export default function(Vue, { head }) {
  head.link.push( { rel: "preload", href: BrownRegular, as: "font", crossorigin: true } )
}
```

**Comment by felixdenoix** [comment]
Don't forget to set the crossorigin attribute to true to ensure the font loaded by the links is not loaded again by the `@font-face` declatations 

```js
import BrownRegular from "~/fonts/Brown-Regular.woff2"

export default function(Vue, { head }) {
  head.link.push( { rel: "preload", href: BrownRegular, as: "font", crossorigin:true } )
}
```
