### ISSUE TITLE
Specify custom transformers

### ISSUE THREAD

**Issue by RedKenrok** [gridsome/gridsome#952]
## Summary

Be able to specify custom transformers in the config.gridsome.js, which as far as I can find does not seem possible yet.

### Basic example

```JavaScript
module.exports = {
  transformers: {
    use: '~/transformers/json.js',
    options: {
      // Global transformer options.
    }
  }
}
```

### Motivation

I would like to use a custom transformer that is special to my use case. Would be terrific if I could without needing to create a separate NPM package for it.

**Comment by hjvedvik** [comment]
Custom transformers within a project is a good idea :) We are actually thinking about moving away from transformers as they work now, and use schema extensions instead. Gridsome v7 does have APIs for creating custom extensions, but it isn't documented yet. You can take a look at [this](https://github.com/gridsome/gridsome/blob/extension-vue-remark/packages/extension-remark/index.js#L83-L90) code to see how it's done. The [readme](https://github.com/gridsome/gridsome/tree/extension-vue-remark/packages/extension-remark) file shows how you use the extension in the components :)

**Comment by RedKenrok** [comment]
Awesome! I had already been messing around with editing the config of the app itself. The code below checks for a `transformersCustom` property in the `gridsome.config.js`. Using extensions definitely feels like a better way of doing it and will certainly look into it. Thank you for your response.

```
// Import node modules.
const fs = require('fs');
const path = require('path');
// Import config file.
const processDirectory = process.cwd();
const config = require(path.join(processDirectory, 'gridsome.config.js'));

const addTransformers = function(api) {
	config.transformersCustom.forEach(function(_transformer) {
		// Check if transformer option has the `use` key.
		if (!Object.prototype.hasOwnProperty.call(_transformer, 'use') || typeof(_transformer.use) !== 'string') {
			console.error('Invalid custom transformer.');
			return;
		}

		// Get transformer module.
		let transformerPath = path.join(processDirectory, _transformer.use);
		let TransformerClass;
		try {
			if (fs.lstatSync(transformerPath).isFile()) {
				TransformerClass = require(transformerPath);
			} else {
				TransformerClass = require(_transformer.use);
			}
		} catch (error) {
			console.error(error);
		}

		// Construct transformer option.
		let transformerData = {
			TransformerClass: TransformerClass
		};
		if (_transformer.name) {
			transformerData.name = _transformer.name;
		}
		if (_transformer.options) {
			transformerData.options = _transformer.options;
		}

		TransformerClass.mimeTypes().forEach(_mimeType => {
			// Manually add to api.config.
			api.config.transformers[_mimeType] = transformerData;
		});
	});
};

module.exports = addTransformers;
```
