### ISSUE TITLE
External component library and core-js dependencies

### ISSUE THREAD

**Issue by clorichel** [gridsome/gridsome#953]
## Description

Importing a component from an external component library bootstrapped with lastest vue-cli fails with core-js dependencies issues.

### Steps to reproduce

- Bootstrap a simple vue-cli (latest) project
- create `AnExample` component
- add `"main": "dist/my-component-library.umd.js"` in the `package.json`
- actually build this dist file as a lib through `vue-cli-service build --target lib --name my-component-library ./src/index.js`
- import it from a gridsome project page `import { AnExample } from 'my-component-library';`

vue-cli project `src/index.js` just imports the component and exports it:

```js
import AnExample from './components/AnExample';

export { AnExample };
```

### Expected result

The component is loaded and displayed on the page.

### Actual result

Gridsome build fails with error:

```
These dependencies were not found:
* core-js/modules/es6.function.bind in ../my-component-library/dist/my-component-library.umd.js
* core-js/modules/es6.object.create in ../my-component-library/dist/my-component-library.umd.js
* core-js/modules/es6.object.define-property in ../my-component-library/dist/my-component-library.umd.js
* core-js/modules/es6.regexp.match in ../my-component-library/dist/my-component-library.umd.js
* core-js/modules/es6.symbol in ../my-component-library/dist/my-component-library.umd.js
* core-js/modules/es7.symbol.async-iterator in ../my-component-library/dist/my-component-library.umd.js
* core-js/modules/web.dom.iterable in ../my-component-library/dist/my-component-library.umd.js
To install them, you can run: npm install --save core-js/modules/es6.function.bind core-js/modules/es6.object.create core-js/modules/es6.object.define-property core-js/modules/es6.regexp.match core-js/modules/es6.symbol core-js/modules/es7.symbol.async-iterator core-js/modules/web.dom.iterable
```

### Environment

```
System:
  OS: macOS Mojave 10.14.6
  CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
Binaries:
  Node: 12.14.0 - /var/folders/tf/jmjn1q4j56l_l0nlxwj0gws80000gn/T/yarn--1579621161003-0.5021645095039184/node
  Yarn: 1.13.0 - /var/folders/tf/jmjn1q4j56l_l0nlxwj0gws80000gn/T/yarn--1579621161003-0.5021645095039184/yarn
  npm: 6.13.4 - /usr/local/bin/npm
Browsers:
  Chrome: 79.0.3945.117
  Safari: 13.0.2
npmPackages:
  gridsome: ^0.7.0 => 0.7.12
```

### Leads

That issue has been bugging me for a while now, and I wonder if it's not related to the [babel 7.4.0 release](https://babeljs.io/blog/2019/03/19/7.4.0) with @babel/polyfill deprecation, but can't find a way to get it working.

Using an "older vue-cli" project (say https://github.com/carbon-design-system/carbon-components-vue through a simple `import { CvButton } from '@carbon/vue';`) works out of the box, which at this point is obviously very annoying to me 😅

**Comment by clorichel** [comment]
Thanks @hjvedvik for having a look 🤗 Feel free to let me know if and how I can help! 🤓 

Looks similar to https://github.com/storybookjs/storybook/issues/9306 which first comment from earlman might give more insights (core-js@3).

**Comment by clorichel** [comment]
FYI, I've just pushed a lerna monorepo to easily reproduce this issue, it's here: https://github.com/clorichel/lerna-gridsome-vuecli

Install notes on the Readme, once you run `npx lerna run --stream --scope my-gridsome-app develop` you'll get the error described by this issue:

```
my-gridsome-app:  ERROR  Failed to compile with 6 errors2:00:39 PM
my-gridsome-app: These dependencies were not found:
my-gridsome-app: * core-js/modules/es6.function.bind in ../my-component-library/dist/my-component-library.umd.js
my-gridsome-app: * core-js/modules/es6.object.create in ../my-component-library/dist/my-component-library.umd.js
my-gridsome-app: * core-js/modules/es6.object.define-property in ../my-component-library/dist/my-component-library.umd.js
my-gridsome-app: * core-js/modules/es6.regexp.match in ../my-component-library/dist/my-component-library.umd.js
my-gridsome-app: * core-js/modules/es6.symbol in ../my-component-library/dist/my-component-library.umd.js
my-gridsome-app: * core-js/modules/es7.symbol.async-iterator in ../my-component-library/dist/my-component-library.umd.js
my-gridsome-app: To install them, you can run: npm install --save core-js/modules/es6.function.bind core-js/modules/es6.object.create core-js/modules/es6.object.define-property core-js/modules/es6.regexp.match core-js/modules/es6.symbol core-js/modules/es7.symbol.async-iterator
```

**Comment by clorichel** [comment]
Turns out we just need to update `"@vue/babel-preset-app": "^3.4.0"` to `"@vue/babel-preset-app": "^4.2.2"` in [gridsome/package.json](../blob/master/gridsome/package.json).

E2e tests will fail until we update in [project-basic.build.e2e.js](../blob/master/gridsome/lib/__tests__/project-basic.build.e2e.js):

```
// from
expect(appJS).toMatch('core-js/modules/es6.promise.js')
expect(appJS).toMatch('core-js/modules/es6.symbol.js')
expect(appJS).toMatch('core-js/modules/es6.string.ends-with.js')
// to
expect(appJS).toMatch('core-js/modules/es.promise.js')
expect(appJS).toMatch('core-js/modules/es.symbol.js')
expect(appJS).toMatch('core-js/modules/es.string.ends-with.js')
```

See #982. Let me know here or on the PR if I missed something 🤓

**Comment by hjvedvik** [comment]
I'll merge the PR now. Thanks for all the time you've put into debugging this issue @clorichel :)
