### ISSUE TITLE
can't install @gridsome/source-ghost

### ISSUE THREAD

**Issue by yvza** [gridsome/gridsome#966]
## Description

Im on fresh gridsome project, my plan is to connecting gridsome to ghost cms using official plugin called @gridsome/source-ghost, but installation seem not successful, i already googling this issue, but i cant find the solution

### Actual result

installation result :
![Image 111](https://user-images.githubusercontent.com/25668079/73595480-ca78ce80-454b-11ea-8f75-83f9872ae864.png)

after follow [this instruction](https://ghost.org/docs/api/v3/gridsome/) i got this error :
![Image 1111](https://user-images.githubusercontent.com/25668079/73595460-9a313000-454b-11ea-8440-f43a8987fd84.png)

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 AMD FX-9830P RADEON R7, 12 COMPUTE CORES 4C+8G
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12

**Comment by zacnomore** [comment]
Hey @yxxa! In that error this part looks pretty promising:
```
MSBUILD: error MSB3428: Could not load the Visual C++ component "VSBuild.exe". To fix this, 
1) install the .NET Framework 2.0 SDK, 
2) install Microsoft Visual Studio 2005 or 
3) add the location of the component to the system path if it is installed elsewhere.
```

Are you able to try one of those solutions?

**Comment by a-kriya** [comment]
@yvza Were you able to resolve your issue?

**Comment by yvza** [comment]
Hi guys, sorry for my late response. I already googling this error, and try lot of tutorial, and i bookmarked my last tutorial [check this](https://superuser.com/questions/1032689/how-do-i-add-vcbuild-exe-to-windows-10-w-o-visual-studio) and still no clue. also i already moving to learn hugo for alternative

progress installing still got error
![errrImage 1](https://user-images.githubusercontent.com/25668079/78810806-1126f100-79f3-11ea-826d-2a4884daf6c1.png)

**Comment by a-kriya** [comment]
@yvza Can you try running `npm install -g --production windows-build-tools`? I remember having to setup a Windows machine a while ago and that package resolved the error that you got.

**Comment by a-kriya** [comment]
@yvza Ah, if that doesn't do it, then you may have to pass `--vs2015` flag: https://github.com/nodejs/node-gyp/issues/1486#issuecomment-451719871

**Comment by yvza** [comment]
@a-kriya i dont know what happend, its work after adding flag `--production`, but unfortunately my vps already destroyed at the end of February, so i cant test it again

btw thanks @a-kriya for your time helping me out

here is result after running `npm install -g --production windows-build-tools`
![secImage 1](https://user-images.githubusercontent.com/25668079/78975572-8ce18480-7b3e-11ea-990d-fe116f5a0fda.png)

**Comment by a-kriya** [comment]
@yvza No problem. Setting up dev environments on Windows can be a hassle sometimes. Anyway, with the build tools successfully installed, there shouldn't be any issue to install @gridsome/source-ghost package. Do you think you'd be able to close this ticket now?

**Comment by yvza** [comment]
yes
