### ISSUE TITLE
Is there a way to create markdown snippets?

### ISSUE THREAD

**Issue by SilencerWeb** [gridsome/gridsome#970]
Is there a way to mention a keyword or something else in the markdown file and get rendered a component instead of this keyword?

Here is an example from another language of what I mean — https://gohugo.io/content-management/shortcodes, a pretty useful feature (:

**Comment by noxify** [comment]
I haven’t found a plugin but it’s definitely possible.

You could create a remark plugin which checks the content if the defined placeholder exists.

Here an example to embed a twitter feed.

https://github.com/danvega/gridsome-plugin-remark-twitter

You only have to change the search pattern and the result.

Hope that helps.

But it sounds like a nice plugin 🤔

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
