### ISSUE TITLE
WPML support?

### ISSUE THREAD

**Issue by simplenotezy** [gridsome/gridsome#972]
I am about to develop a new theme in Vue.js for a WooCommerce shop that uses WPML. Is this supported in Gridsome? Really can't find anything if I am searching through issues or the documentation.

**Comment by thetre97** [comment]
Multilingual sites can be built with Gridsome, but this would have to be done manually by using the `createPage` API - i.e. creating either a separate page for each locale `some-post/en`, `some-post/fr/*` etc, or by loading multiple locales into a  page and using  a Vue i18n plugin.

**Comment by a-kriya** [comment]
@simplenotezy Does the above help?

**Comment by mtlynch** [comment]
Closing this, as @simplenotezy has not responded for several weeks.
