### ISSUE TITLE
Caching g-image results?

### ISSUE THREAD

**Issue by tobsch** [gridsome/gridsome#976]
We are migrating a grown wordpress setup to gridsome. Biggest challange is now lower deployment time.
We are building on github actions and hosting on google cloud. All wordpress assets (images) are hosted on google cloud storage (similar to s3).

Is there any best practice on how to cache assets / images rendered by g-image?
Reading from s3/gcs is slow and re-generating all images every time feels like bloat.
From my perspective, It would be best to cache all images after generating them.

Any hints?

Tobi

**Comment by Al-Rozhkov** [comment]
Related: [Should images be processed on every build?](https://github.com/gridsome/gridsome/issues/494)

**Comment by hjvedvik** [comment]
@tobsch It should be possible to cache the images in `.cache/assets/static/*`. Gridsome will copy any image that exists in that folder to `dist/assets/static/*` instead of processing it. You can try to use the `api.afterBuild()` hook to cache the processed images.
