### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined

### ISSUE THREAD

**Issue by nabeelatsanaulla** [gridsome/gridsome#977]
HI,
I am using VueTyper (https://github.com/cngu/vue-typer), it is running fine during development but while build throws this error:

`(node:17336) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (E:\sanaulla-launch\node_modules\vue\dist\vue.runtime.common.prod.js:6:24223)
    at E:\sanaulla-launch\node_modules\vue\dist\vue.runtime.common.prod.js:6:21188
    at E:\sanaulla-launch\node_modules\vue\dist\vue.runtime.common.prod.js:6:2394
(node:17336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Could not generate HTML for "/":
ReferenceError: document is not defined
    at o (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:3355)
    at r (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:3186)
    at t.exports (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:4808)
    at Object.<anonymous> (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:22736)
    at e (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:320)
    at Object.<anonymous> (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:5430)
    at e (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:320)
    at Object.<anonymous> (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:5606)
    at e (E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:320)
    at E:\sanaulla-launch\node_modules\vue-typer\dist\vue-typer.min.js:6:703`

I have already tried other probable solutions mentioned here:
- I am using ClientOnly
- I tried moving it to a separate component, but still no luck.

Kindly help. Thanks.

**Comment by noxify** [comment]
Hi @nabeelatsanaulla, 

could you please share the related files, where you have implemented `vue-typer`?

**Comment by nabeelatsanaulla** [comment]
Please check the files here: https://github.com/nabeelatsanaulla/Launch

**Comment by nabeelatsanaulla** [comment]
Got it solved. My mistake. Sorry.

**Comment by noxify** [comment]
@nabeelatsanaulla How did you solved it?  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dnndev** [comment]
@noxify I am getting the same issue during build. It's a warning now but it's a deprecation warning. I'm using Vue-Carousel and have set things up according to the code here which, lucky for me, was for Vue-Carousel :)  https://gridsome.org/docs/assets-scripts/#without-ssr-support. Here's my message:

```
Execute GraphQL (6 queries) - 0.01s
Write out page data (6 files) - 0s
(node:9276) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (/Users/kford/Sites/gridsome/test-tailwind/node_modules/vue/dist/vue.runtime.common.prod.js:6:24223)
    at /Users/kford/Sites/gridsome/test-tailwind/node_modules/vue/dist/vue.runtime.common.prod.js:6:21188
    at /Users/kford/Sites/gridsome/test-tailwind/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
(node:9276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Render HTML (6 files) - 0.38s
Process files (0 files) - 0s
Process images (19 images) - 1s
```
I'm using vue-carousel on /src/Index.vue

**Comment by dnndev** [comment]
BTW, I was never able to resolve this. I removed `vue-carousel` and switched to `vue-slick-carousel` which supports SSR. That cleared up the issue.

**Comment by mjatharvest** [comment]
+1 for switching to vue-slick-carousel https://github.com/gs-shop/vue-slick-carousel

Resolved my issue as well.
