### ISSUE TITLE
About Gridsome and Contentful settings

### ISSUE THREAD

**Issue by sawachika0428** [gridsome/gridsome#978]
## Description

Setting up Gridsome and setting up the Contentful plugin,
If you type the following command,
`npm run develop` or `yarn run develop` The following error occurs.

> GraphQLError: Syntax Error: Unexpected Name "ContentfulLayout"

### Environment

@gridsome/source-contentful": "^0.5.2",
    "gridsome": "^0.7.0",
    "markdown-it": "^10.0.0"

**Comment by JamesCrann** [comment]
@sawachika0428 What the cause of this error?

**Comment by Rafi992** [comment]
This problem occurs when you do not create an empty space on contentful

**Comment by patrikengborg** [comment]
This seems to occur when you use camelCase for any of your content type's API identifier / content type id. It started to work when I switched to snake_case.
