### ISSUE TITLE
Errors persists after even fixing in tailwind.config.js

### ISSUE THREAD

**Issue by b0nbon1** [gridsome/gridsome#979]
## Description
Made an error in `tailwind.config.js` and then resolved it but after hot reload the console still shows the until I run `gridsome develop` again.

Describe the issue that you're seeing.

I removed a `}` from `line: 32`  and an error was thrown, which is on the `console`

![image](https://user-images.githubusercontent.com/46062609/74081646-10f19000-4a5a-11ea-88ea-2f883f568feb.png)

And then resolved it by adding the `}` but the error is still there

![image](https://user-images.githubusercontent.com/46062609/74081676-6037c080-4a5a-11ea-9d90-e6b6b35f02ae.png)

**Comment by hjvedvik** [comment]
The `tailwind.config.js` file is probably only loaded by vue loader when webpack starts, so the development server must be restarted to load it again. I don't think we can do anything about it in Gridsome, unfortunately.
