### ISSUE TITLE
Cache Busting in Gridsome

### ISSUE THREAD

**Issue by nabeelaejaz** [gridsome/gridsome#980]
hi,
How do I implement cache busting in gridsome. Right now most of the time the browser loads the old cached site, instead of the updated one, on live server, until we press refresh. Kindly guide on how do we implement cache busting. Thanks.

**Comment by nabeelaejaz** [comment]
Use Service Workers

**Comment by a-kriya** [comment]
@nabeelaejaz The docs for the service worker plugin at https://gridsome.org/plugins/gridsome-plugin-service-worker says that the `networkOnly` only strategy is the default. Which other strategy did you use to resolve this issue? `networkFirst`?

**Comment by nabeelaejaz** [comment]
Yes, I ended up using networkFirst.

**Comment by a-kriya** [comment]
Okay, cool. Thanks. How do you determine when to show a the toast?

**Comment by nabeelaejaz** [comment]
I placed a 'document version' variable in the website which cross checked (axios) with a 'latest version' field on Airtable (free, so I used). So if the document version was behind the latest version variable, it would bring up the toast, asking the user to refresh. And so after refreshing both document and latest version would match and be latest.

**Comment by a-kriya** [comment]
I see. And do you bump up the "document version" manually or use Gridsome's build id somehow?

**Comment by nabeelaejaz** [comment]
Yes, unfortunately, I had to do this manually, as the app was up for launch so couldn't think of a better solution then.

**Comment by a-kriya** [comment]
Alright, thanks for responding, dude. The site looks pretty slick!
