### ISSUE TITLE
Register g-link and g-image in PascalCase

### ISSUE THREAD

**Issue by souljorje** [gridsome/gridsome#983]
## Summary

I use PascalCase for components name by default in my project, following [official style-guide](https://vuejs.org/v2/style-guide/#Single-file-component-filename-casing-strongly-recommended). 
When I try to use `<GImage>` I get an error: 
`[Vue warn]: Unknown custom element: <GImage> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

I registered it by myself:
```js
// main.js
import GImage from 'gridsome/app/components/Image';
export default function (Vue, { appOptions, head }) {
  // ...
  Vue.component('GImage', GImage);
  // ...
}
```
But component doesn't work in proper way, I get this in my HTML:
```html
<img alt="Example image" src="@/favicon.png" class="g-image">
```
Props aren't handled.

### Basic example

Not needed.

### Motivation

[Vue component registration docs](https://vuejs.org/v2/guide/components-registration.html#Name-Casing):
> When defining a component with `kebab-case`, you must also use `kebab-case` when referencing its custom element, such as in <my-component-name>.

> When defining a component with `PascalCase`, you can use either case when referencing its custom element. That means both `<my-component-name>` and `<MyComponentName>` are acceptable.

So, please, register custom components in PascalCase by default 🙏

**Comment by hjvedvik** [comment]
Yes, I agree! I'll add it to the todo project, but feel free to submit a PR if you want to.

**Comment by brandonpittman** [comment]
I messed around with this once. One of them was easy to get working, but the other one broke **hard**. Can't remember which was which anymore.

**Comment by brandonpittman** [comment]
@hjvedvik Registering GImage (instead of g-image) works in that it registers the component how we want, but Webpack isn't processing the !/@ in urls.

**Comment by hjvedvik** [comment]
@brandonpittman The `src` attribute is processed by a custom Vue compiler module [here](https://github.com/gridsome/gridsome/blob/master/gridsome/lib/webpack/modules/assets.js#L8-L14). So it must also check for `GImage` and `GLink`.

**Comment by brandonpittman** [comment]
@hjvedvik Thanks for pointing me in the right direction. #985 should fix this issue.
