### ISSUE TITLE
<g-image :src="$page.post.image" /> Not Working

### ISSUE THREAD

**Issue by Codzaa** [gridsome/gridsome#986]
## Loading image via Graphql not working.

When l try load my image via graphql in my pages its not working.Its giving a blank webpage.
I am trying to load a list of blog posts via graphql on one page.Everything else(titles,authors) is loading properly but when l trying loading the images using
<g-image :src="$page.post.image" />
it is giving me a blank webpage.

Images are getting stored in this directory 'src/assets'

Im getting this error in the browser terminal

[Vue warn]: Invalid prop: type check failed for prop "src". Expected Object, String, got Undefined

'I am using Netlify CMS'

**Comment by noxify** [comment]
Hi @Codzaa 

have you tried it with `:src="page.postimage"`?

**Comment by Codzaa** [comment]
Hi @noxify 

I tried `:src="page.post.image"`

I now get the following error

 [Vue warn]: Property or method "page" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**Comment by noxify** [comment]
Hey @Codzaa,

could you share your vue template?

Without this, it's hard to see what's wrong.

Thanks.

**Comment by Codzaa** [comment]
<template>
  <Layout>

    <div class="container fill-c">

      <div class="jumbotron jumbotron-fluid jumbo3">
        <div class="container">
          <div class="blog-center">
            <h1 class="display-4 b-title2" v-html="$page.story.title"></h1>
            <span class="span-a">By </span><p class="lead" v-html="$page.story.author"></p>
            <small class="text-muted" v-html="$page.story.date"></small>
          </div>
             <p class="para" v-html="$page.story.content">
               <g-image :src="$page.story.image" /> 
             

            </p>
            <h3>Follow <span v-html="$page.story.author"></span> </h3>
            
            <h4>
            <span> 
              <g-link :to="$page.story.twitter" class="card-footer-item twitter-icon">
                <font-awesome :icon="['fab', 'twitter']"/>
                </g-link>
              <span> and </span>
              <g-link :to="$page.story.github" class="card-footer-item git-icon">
                 <font-awesome :icon="['fab', 'github']"/>
                 </g-link>
              
             </span>
            
            </h4>
    
        </div>
      </div>

    </div>



  </Layout>
</template>

<page-query>

query Stories ($path:String!){
  story: story(path:$path)
  {
    title
    author
    date
    content
    github
    twitter
    image
  }
}

</page-query>

**Comment by hjvedvik** [comment]
@Codzaa You can also try to set `v-if="$page.story.image"` on the `g-image` tag just in case a story doesn't have an image.

**Comment by Codzaa** [comment]
@hjvedvik Let me Try that

**Comment by a-kriya** [comment]
@Codzaa Did the above suggestion resolve your issue?

**Comment by Codzaa** [comment]
@a-kriya  No it didnt

**Comment by a-kriya** [comment]
@Codzaa The error that you're noticing, `[Vue warn]: Invalid prop: type check failed for prop "src". Expected Object, String, got Undefined`, basically says that `image` is not set for (at least) one of your posts. Try inspecting the data in the GraphQL Playground at http://localhost:8080/___explore to look for those posts:

```
query Stories {
  allStory {
    edges {
      node {
        title,
        image
      }
    }
  }
}
```

**Comment by noxify** [comment]
I close this issue for now, feel free to reopen :)
