### ISSUE TITLE
Rules within CSS calc() are compressed incorrectly.

### ISSUE THREAD

**Issue by michaelpumo** [gridsome/gridsome#995]
## Description

Using arithmetic in CSS calc (through SCSS) results in incorrect output. It appears to remove spaces and sometimes remove some of the division rules.

### Steps to reproduce

**Raw SCSS:**
```
$clip-rule: "(var(--button-size) / 2) + (var(--spacing-unit) / 2)";
clip-path: circle(calc(var(--button-size) / 2) at calc(#{$clip-rule}) calc(#{$clip-rule}));
```

### Expected result

**npm run develop (correct output)**
`clip-path: circle(calc(var(--button-size) / 2) at calc((var(--button-size) / 2) + (var(--spacing-unit) / 2)) calc((var(--button-size) / 2) + (var(--spacing-unit) / 2)));`

### Actual result

**npm run build (incorrect output)**
`clip-path: circle(calc(var(--button-size)/2) at calc(var(--button-size) + var(--spacing-unit)) calc(var(--button-size) + var(--spacing-unit)));`

Spaces are removed (which is invalid in calc()) and some divison is removed.

Could this be related to a compression of the CSS in the production build https://github.com/yui/yuicompressor/issues/59

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @gridsome/source-graphql: ^0.1.0 => 0.1.0
    gridsome: ^0.7.13 => 0.7.13
    gridsome-source-graphql-prismic: ^0.1.6 => 0.1.6
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

```

**Comment by michaelpumo** [comment]
Further to this, I managed to get it to work by fixing a `* 1` in the end of the `calc()` function.

Instead of this:
```
$clip-rule: "(var(--button-size) / 2) + (var(--spacing-unit) / 2)";
clip-path: circle(calc(var(--button-size) / 2) at calc(#{$clip-rule}) calc(#{$clip-rule}));
```

Do this:
```
$clip-rule: "(var(--button-size) / 2) + (var(--spacing-unit) / 2) * 1"; // See the * 1 here.
clip-path: circle(calc(var(--button-size) / 2) at calc(#{$clip-rule}) calc(#{$clip-rule}));
```

I have no idea why this fixes it but either way, it's dirty and something is definitely going wrong with how Gridsome handles `calc()` in production build of SCSS.

There is something up with using the `+` character.

**Comment by tomtev** [comment]
Weird bug 😅 But glad you found a workaround

**Comment by michaelpumo** [comment]
Why has this issue been closed though? I found a work-around but this is still an issue with the build process of Gridsome?

**Comment by tomtev** [comment]
I'm pretty sure it's not a Gridsome issue, but might be the the sass loader?  Gridsome does not do anything with the CSS.

**Comment by michaelpumo** [comment]
Does Gridsome do anything to the assets after the fact though? Like any optimisations on the compiled CSS such as minification / compression etc (regardless of pre-processor used)?

All I have running is `node-sass` and `sass-loader` and I do not see this behaviour in any of my Vue.js or Nuxt.js sites (so far as I can tell).

**Comment by itsnwa** [comment]
Not sure where this problem happens, but I'm pretty sure it's not on Gridsome's end. Gatsby community has been writing about the same issue. There are some issues with `+` like you mentioned.

This is how I fixed my function:
```scss
// From
--grid-two: calc((100vw - (var(--outer-padding) * 2)) / 2 + (var(--grid-gap) / 2));
// To
--grid-two: calc((100vw - (var(--outer-padding) * 2)) / 2 - (var(--grid-gap) * -1 / 2) * 1);
```

I think the last `* 1` is redundant, but I basically used minus instead of plus and flipped the variable value.
