### ISSUE TITLE
ReferenceError: IDBIndex is not defined with Firebase

### ISSUE THREAD

**Issue by silasalis** [gridsome/gridsome#999]
when using firebase with gridsome develop it is normal, but when trying to build it generates the error: ReferenceError: IDBIndex is not defined.

**Comment by zacnomore** [comment]
@silasalis Could you share the results of `gridsome info`? Also, are you using this in the browser or only at build time?

**Comment by supertommy** [comment]
I think this error is related to https://github.com/firebase/firebase-js-sdk/issues/1797

**Comment by silasalis** [comment]
RESOLVED!!

in App.vue, I imported a singleton created for Firebase called getFirebase.
then in the mounted hook of App.vue

     const lazyApp = import('firebase/app')
      const lazyAuth = import('firebase/auth')
      const lazyDb = import('firebase/database')
      const lazyStorage = import('firebase/storage')

      Promise.all([lazyApp, lazyAuth, lazyDb,       
       lazyStorage]).then(([firebase]) => {
        getFirebase(firebase)
      })
    }    

code for getFirebase: 

import { config } from './config'

let firebaseInstance
export const getFirebase = firebase => {
    if (firebaseInstance) {
        return firebaseInstance
    }

    firebase.initializeApp(config)
    firebaseInstance = firebase

    return firebase
}

**Comment by zacnomore** [comment]
Fantastic, thank you for sharing!
